### ISSUE TITLE
curl is no longer present in bitnami/kubectl:1.22

### ISSUE THREAD

**Issue by Heldenkrieger01** [bitnami/containers#10087]
### Name and Version

bitnami/kubectl:1.22

### What steps will reproduce the bug?

curl was removed in this automated pull request.
https://github.com/bitnami/containers/pull/8848

### What is the expected behavior?

I expect curl to be present.

### What do you see instead?

curl gets uninstalled during docker build

**Comment by recena** [comment]
@Heldenkrieger01 The removing was intentional. We want to stop including extra packages when are not required by the software.

**Comment by Heldenkrieger01** [comment]
@recena Thanks for your answer, I will build my own container based on yours then.
