### ISSUE TITLE
[bitnami/postgresql] Container for PostgreSQL 15

### ISSUE THREAD

**Issue by galanoff** [bitnami/containers#10110]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Add support for a PostgreSQL version 15

### What is the feature you are proposing to solve the problem?

Create a build pipeline for PostgreSQL version 15

**Comment by carrodher** [comment]
Thanks for letting us know. Our automated test & release pipeline already detected the new version, but since it is a totally brand new major branch some manual work is needed.
We will update this thread once released the new version.

**Comment by carrodher** [comment]
Hi, we would like to inform you that the new PostgreSQL major version was released on our side, both as a container image (https://github.com/bitnami/containers/pull/11456) and Helm chart (https://github.com/bitnami/charts/pull/13203)
