### ISSUE TITLE
[bitnami/postgresql] arm64 build for PostgreSQL

### ISSUE THREAD

**Issue by owenthereal** [bitnami/containers#10122]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Add support for postgresql  arm64 build

### What is the feature you are proposing to solve the problem?

Run it on raspberry pi

**Comment by owenthereal** [comment]
Related to https://github.com/bitnami/charts/issues/7305

**Comment by javsalgar** [comment]
Hi,

We are now funnelling all conversations to the issue you mentioned. In order to avoid duplications, we will close this one. Thank you so much for the feature request.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
