### ISSUE TITLE
No SSH @ bitnami/php-fpm:8.1

### ISSUE THREAD

**Issue by hulkthedev** [bitnami/containers#10134]
### Name and Version

bitnami/php-fpm:8.1

### What steps will reproduce the bug?

Please excuse my bad English.
Composer Install throws errors because no SSH is installed in the image.

Would it be possible to deliver SSH by default?

### What is the expected behavior?

SSH Support.

### What do you see instead?

Failed to execute git clone --mirror -- [...]
[...]
error: cannot run ssh: No such file or directory                                                                                                                                          
fatal: unable to fork

**Comment by javsalgar** [comment]
Hi,

I'm afraid that adding ssh would add more packages and therefore more risk surface. As an alternative, if you are using the image as a `FROM` in your Dockerfile, you can add this command

```
RUN install_package openssh-client
```

**Comment by hulkthedev** [comment]
> Hi,
> 
> I'm afraid that adding ssh would add more packages and therefore more risk surface. As an alternative, if you are using the image as a `FROM` in your Dockerfile, you can add this command
> 
> ```
> RUN install_package openssh-client
> ```

Thanks, that's exactly what I'm doing now.
Suddenly Docker tells me that wget command is unknown.

Even the older images (bitnami/php-fpm:8.1.9-debian-11-r8) suddenly don't work when I want to build them, wget was apparently removed.

Is there any information about this?

**Comment by javsalgar** [comment]
Hi,

Recently we removed the wget command to reduce the security surface. Could you add more details on how you are using wget?
