### ISSUE TITLE
"SSL operation failed with code 5" when calling Vertex as root user

### ISSUE THREAD

**Issue by ntroyer** [bitnami/containers#10150]
### Name and Version

bitnami/magento:2.4.3

### What steps will reproduce the bug?

1. Start the container with user set to root.
2. Navigate to <local url>/<backend>/admin/system_config/edit/section/tax/
3. Under Vertex > Connection Settings, enable Vertex Tax Links, then add valid credentials and click "Save Config".
4. Under Vertex > Integration Settings, set Vertex Tax Calculation to Enabled and click "Save Config".

### What is the expected behavior?

Vertex API Status returns Valid

### What do you see instead?
```
Warning: SoapClient::SoapClient(): SSL operation failed with code 5. OpenSSL Error messages: error:0200100D:system library:fopen:Permission denied error:20074002:BIO routines:file_ctrl:system lib error:0B06F002:x509 certificate routines:X509_load_cert_file:system lib error:0200100D:system library:fopen:Permission denied error:20074002:BIO routines:file_ctrl:system lib error:0B06F002:x509 certificate routines:X509_load_cert_file:system lib error:0200100D:system library:fopen:Permission denied error:20074002:BIO routines:file_ctrl:system lib error:0B06F002:x509 certificate routines:X509_load_cert_file:system lib error:0200100D:system library:fopen:Permission denied error:20074002:BIO routines:file_ctrl:system lib error:0B06F002:x509 certificate routines:X509_load_cert_file:system lib error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /opt/bitnami/magento/vendor/vertexinc/sdk/src/Utility/SoapClientFactory.php on line 72
```
### Additional information

Vertex is able to connect to the endpoint correctly in my container with the user set to 1001, and "podSecurityContent" enabled with fsGroup set to 1001. However, I get the above error with the root user and "podSecurityContent" disabled.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ntroyer** [comment]
This was solved on our end. Ended up being the certificates in our pod had the wrong permissions set. We corrected this by adjusting the `podSecurityContext` to be the same user that had Magento permissions.
