### ISSUE TITLE
OpenCart 4.x

### ISSUE THREAD

**Issue by sorscode** [bitnami/containers#1017]
### Name and Version

bitnami/opencart4.0.0.0

### What is the problem this feature will solve?

Looking to see when you might support 4.x

### What is the feature you are proposing to solve the problem?

Moving to the latest version

### What alternatives have you considered?

building my own docker container.

**Comment by dgomezleon** [comment]
Hello @sorscode ,

We have just released version 4.0.1-1.

Regards

**Comment by m18unet** [comment]
> Hello @sorscode ,
> 
> We have just released version 4.0.1-1.
> 
> Regards

@dgomezleon, you are awesome! Thanks for your interest.
