### ISSUE TITLE
ISSUE WHILE STARTING KEYCLOAK SERVER

### ISSUE THREAD

**Issue by mukuljoshi123** [bitnami/containers#10180]
### Name and Version

bitnami/keycloak:19.0.3

### What steps will reproduce the bug?

I have a postgres server already installed in my system (Not in docker) wilth database and user created. while connecting it to psql server it says
"keycloak    | timeout reached before the port went into state "inuse""
attaching below my docker-compose file
version: '3.8'
services:
  keycloak:
    image: bitnami/keycloak:19.0.3
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KEYCLOAK_CREATE_ADMIN_USER: 'true'
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: 123456
      KEYCLOAK_DATABASE_HOST: localhost
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_DATABASE_SCHEMA: public

### What is the expected behavior?

it should start the keycloak server

### What do you see instead?

i am getting this error instead
keycloak    | keycloak 20:22:58.40 
keycloak    | keycloak 20:22:58.41 Welcome to the Bitnami keycloak container
keycloak    | keycloak 20:22:58.41 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak    | keycloak 20:22:58.41 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak    | keycloak 20:22:58.41 
keycloak    | keycloak 20:22:58.41 INFO  ==> ** Starting keycloak setup **
keycloak    | keycloak 20:22:58.42 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak    | keycloak 20:22:58.42 INFO  ==> Trying to connect to PostgreSQL server postgresql...
keycloak    | cannot resolve host "postgresql": lookup postgresql: Temporary failure in name resolution
keycloak    | cannot resolve host "postgresql": lookup postgresql: Temporary failure in name resolution
keycloak    | cannot resolve host "postgresql": lookup postgresql: Temporary failure in name resolution
keycloak    | cannot resolve host "postgresql": lookup postgresql: Temporary failure in name resolution
keycloak    | cannot resolve host "postgresql": lookup postgresql: Temporary failure in name resolution

**Comment by kriscamilleri** [comment]
I am having the exact same issue. How did you resolve this please?

**Comment by michagriesser** [comment]
I have the same problem with an Oracle database and a higher keycloak version. It works on the standard port 1521. On another database listening on a different port, I get the same error.

**Comment by mukuljoshi123** [comment]
the issue with me was i have configuration issues as you can see i have provided localhost for postgres host so when keycloak starts inside the container the search inside its docker network and it was not able to find postgres .the way i solved it is by providing my host machine ip instead of localhost.hope it helps
