### ISSUE TITLE
Permission Denied - /opt/bitnami/redis/tmp

### ISSUE THREAD

**Issue by Anuj28282828** [bitnami/containers#1018]
### Name and Version

bitnami/bitnami-docker-redis

### What steps will reproduce the bug?

I am getting
mkdir: cannot create directory '/opt/bitnami/redis/tmp' : Permission Denied

I have a limitation that i can't give permissions to root though
Can we somehow override this location?

### What do you see instead?

Permission denied

**Comment by gsharma-jiggzy** [comment]
> > Hi,
> > In order for the containers to work, it needs to belong to the root group. This is currently the standard required for Openshift
> 
> Thanks @javsalgar!
> 
> You are saying that we should remove `runAsGroup` or set it to root's group?
> 
> ```diff
> - runAsGroup: 1000
> ```

@mamachanko I'm facing a similar issue with RabbitMQ on RKE2. what fixed it was 
- runAsGroup: 0

**Comment by javsalgar** [comment]
> You are saying that we should remove runAsGroup or set it to root's group?

That's it
