### ISSUE TITLE
Distribution failed

### ISSUE THREAD

**Issue by clcc2019** [bitnami/containers#1023]
### Name and Version

bitnami/rabbitmq:3.10.5

### What steps will reproduce the bug?

deploy rabbitmq charts on openEuler os

### What do you see instead?

![Uploading image.png…]()

**Comment by rafariossaa** [comment]
I can see that there was previous data, could you remove it and give it a clean start ?.

**Comment by clcc2019** [comment]
> I can see that there was previous data, could you remove it and give it a clean start ?. Also, are you running this on a ARM machine ?
arch is amd64，I am a fresh deployment

**Comment by clcc2019** [comment]
> I can see that there was previous data, could you remove it and give it a clean start ?. Also, are you running this on a ARM machine ?

![image](https://user-images.githubusercontent.com/46099295/182100143-a6c50623-f2fe-483f-b0d5-f28190caceca.png)
