### ISSUE TITLE
mod_dav_svn could not be loaded

### ISSUE THREAD

**Issue by wang-fut** [bitnami/containers#1028]
### Name and Version

bitnami/apache:2.4

### What steps will reproduce the bug?

1. After install some required packages, add "LoadModule dav_svn_module /usr/lib/apache2/modules/mod_dav_svn.so" to httpd.conf. (mod_dav had been enabled and worked fine)
2. Restart container

### What is the expected behavior?

container restart normally

### What do you see instead?

container restart failed with logs below:

```bash
apache 02:00:53.42 INFO  ==> ** Starting Apache **
httpd: Syntax error on line 162 of /opt/bitnami/apache/conf/httpd.conf: Cannot load /usr/lib/apache2/modules/mod_dav_svn.so into server: /usr/lib/x86_64-linux-gnu/libsvn_subr-1.so.1: undefined symbol: apr_crypto_block_cleanup
```

### Additional information

I had tried:
1. reinstall subversion by apt
2. reinstall subversion by tar
3. reinstall libapr1, libapache2-mod-svn, libaprutil1
4. install apr, apr-util

Nothing helped.

**Comment by lehmannk** [comment]
I have the same issue with the `bitnami/apache` image (latest 2.4.57-debian-11-r124) and `mod_dav_svn`, means my container also runs into error 
```
Cannot load /usr/lib/apache2/modules/mod_dav_svn.so into server: /usr/lib/x86_64-linux-gnu/libsvn_subr-1.so.1: undefined symbol: apr_crypto_block_cleanup
```
upon start. Is there any way to get svn running with bitnami/apache without much hassle? I tried the above mentioned solution of rebuilding the whole svn server and then grabbing out `mod_dav_svn.so` as well as instantiating the VMWare subversion solution and grabbing the file from there. But these tries resulted in other problems. I am aware of issue #16240 but I do not understand what needs to be done there. Can you help me understand what to do now?

**Comment by miao1007** [comment]
I met the same problem, It's because the lack of  `./configure --with-crypto` option while compiling apr-uitl from source, it should be verified via grepping the missing method in the compiled dynamic library `libaprutil-1.so`.
