### ISSUE TITLE
[bitnami/wordpress-nginx] The wrong wp-config.php is checked for existence

### ISSUE THREAD

**Issue by ziodave** [bitnami/containers#1051]
### Name and Version

bitnami/wordpress-nginx:6

### What steps will reproduce the bug?

1. Map a local wp-content folder to /bitnami/wordpress/wp-content
2. Spin up a container
3. WordPress is not initialized

### What is the expected behavior?

The startup script should configure WordPress because the /bitnami/wordpress/wp-config.php is not existing.

### What do you see instead?

The startup script is considering the app already initialized.

### Additional information

The error is at https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/6/debian-11/rootfs/opt/bitnami/scripts/libwordpress.sh#L231 since we're looking for /opt/bitnami/wordpress/wp-config.php instead of /bitnami/wordpress/wp-config.php.

/opt/bitnami/wordpress/wp-config.php is always present since it's part of the image.

**Comment by siddjellali** [comment]
up !

**Comment by timofey-drozhzhin** [comment]
I can confirm that the container by default comes with `/opt/bitnami/wordpress/wp-config.php` file present, regardless if you have the actual file mounted in `/opt/bitnami/wp-config.php`, which results in a false positive check.

To replicate this:
Spin up a new container `docker run -td --name wordpress-nginx bitnami/wordpress-nginx:6 sleep infinity`
SSH into the container `docker exec -it wordpress-nginx bash`
Confirm the existence of the wp-config.php `ls -lah /opt/bitnami/wordpress/wp-config.php`

I am also affected by the same issue, but different case scenario (#4314).

**Comment by siddjellali** [comment]
any update here, please ?
