### ISSUE TITLE
Airflow containers not running LTS

### ISSUE THREAD

**Issue by bdsoha** [bitnami/containers#10519]
### Name and Version

bitnami/airflow

### What steps will reproduce the bug?

The latest release of *Apache Airflow* is [ `2.4.1`](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-4-1-2022-09-30), but the latest available container is [`2.3.4`](https://hub.docker.com/layers/bitnami/airflow/2.3.4-debian-11-r13/images/sha256-4ea517f8bd6b8ceb4c0a50a3452f6f4fdfbf2aba030b1712b81e159f7a69b4f2?context=explore)

### What do you see instead?

The *minor* version to be updated to `2.4.1`

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.
At this moment the team is working on it. We will update this thread once released the new version.

**Comment by bdsoha** [comment]
@carrodher Airflow has been bumped once again, to `2.4.2`.

**Comment by carrodher** [comment]
No problem about that, the track and download process is working fine on our side. Once fixed the issue building the container, we will release the latest available version at the moment

**Comment by Mauraza** [comment]
Hi @bdsoha,

Airflow 2.4.2  was released!
