### ISSUE TITLE
[bitnami/keycloak] chart should use default env variables instead of bitnami ones, to work with keycloak's own chart

### ISSUE THREAD

**Issue by yelhouti** [bitnami/containers#10515]
### Name and Version

keycloak/bitnami 10.1.5

### What steps will reproduce the bug?

When I tried using `proxy: edge` with the default chart it didn't work, because the variable you are using is: `KEYCLOAK_PROXY` instead of `KC_PROXY `. This works great with the bitnami image but not the default one.

### Are you using any custom parameters or values?

proxy: edge

### What is the expected behavior?

It should work with quay.io/keycloak/keycloak

### What do you see instead?

It fails to login because proxy wasn't set correctly and wastes a lot of time debugging

**Comment by fmulero** [comment]
If you like to contribute by creating a PR to solve the issue, The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by MichaoDev** [comment]
when do you plan to release  chart and container for Keycloak:20.0?

**Comment by fmulero** [comment]
We are working on it #13333 but we can not share at the moment any estimation.
