### ISSUE TITLE
Release for Suitecrm 8.2.0

### ISSUE THREAD

**Issue by sweettbug3** [bitnami/containers#10531]
### Name and Version

bitnami/suitecrm:8.2.0

### What is the problem this feature will solve?

Provide 8.2.0 release of Suitecrm (https://docs.suitecrm.com/8.x/admin/releases/8.2/). This adds several features provided by this Salesagility release 8.2.0.

### What is the feature you are proposing to solve the problem?

8.2.0 provides more authentication methods, and therefore is a very good addition to bitnami's suitecrm releases.

### What alternatives have you considered?

Layering Suitecrm code for 8.2.0 on top of the bitnami/suitecrm 8.1.3 docker mostly works.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by sweettbug3** [comment]
Thanks!

**Comment by corico44** [comment]
Hello @sweettbug3,
We inform you that the new version 8.2.0 for suiteCRM has been released and you can already use it.

Thank you very much for the contribution!
