### ISSUE TITLE
Install less command for git config -l

### ISSUE THREAD

**Issue by jguay** [bitnami/containers#10823]
### Name and Version

bitnami/git:2.38.1-debian-11-r0

### What is the problem this feature will solve?

Trying to list git configuration uses less command which is not installed so just wondering if it is documented somewhere maybe or if less should be installed
```
docker run --rm --name git bitnami/git:2.38.1-debian-11-r0 git config -l
error: cannot run less: No such file or directory
```

### What is the feature you are proposing to solve the problem?

install less command in the docker image

### What alternatives have you considered?

The `git config -l` works when first installing less command
```
apt-get update && apt-get install less
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. We just created the above PR adding `less` to the list of packages installed by default.
Using the latest versions of the bitnami/git container image you should be able to run `git config -l` without any issue:
```console
root@2ea74b382bf0:/# git init
root@2ea74b382bf0:/# git config --list
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```
