### ISSUE TITLE
[bitnami/rails] Rails with up to date ruby and node versions

### ISSUE THREAD

**Issue by stevenbarragan** [bitnami/containers#10883]
### Name and Version

bitname/rails

### What is the problem this feature will solve?

This image is tight with old version of ruby and node. Having up to date libraries will improve the performance and capabilities of the application.

### What is the feature you are proposing to solve the problem?

Update ruby and node versions. Maybe another image with the tag "uptodate"

### What alternatives have you considered?

update this lines https://github.com/bitnami/containers/blob/main/bitnami/rails/7/debian-11/Dockerfile#L24-L25 but I'd love to have the changes upstream.

**Comment by gongomgra** [comment]
Hi @stevenbarragan,

Just a quick note to let you know that we released a new revision of our Rails 7.x container (tag ` 7.0.4-0-debian-11-r27`) upgrading Ruby and NodeJS versions. From now on, Rails 7.x will include Ruby 3.1.x and NodeJS 18.x.

```
$ docker run --rm -it bitnami/rails:7.0.4-0-debian-11-r27 bash
rails 10:03:15.81
rails 10:03:15.81 Welcome to the Bitnami rails container
rails 10:03:15.81 Subscribe to project updates by watching https://github.com/bitnami/containers
rails 10:03:15.81 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rails 10:03:15.81

root@9fe579ed6023:/app# ruby --version
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
root@9fe579ed6023:/app# node --version
v18.12.1
root@9fe579ed6023:/app#
```
