### ISSUE TITLE
[bitnami/minio-client] The client container always exit with an error

### ISSUE THREAD

**Issue by gidoUninova** [bitnami/containers#11180]
### Name and Version

bitnami/minio-cllient:latest

### What steps will reproduce the bug?

Using Docker desktop on Mac
I ran the command:
```
docker run --name minio-client \
    --env MINIO_SERVER_HOST="bd4nrg-htap.vm.fedcloud.eu" \
    --env MINIO_SERVER_ACCESS_KEY="***" \
   --env MINIO_SERVER_PORT_NUMBER="9005" \
    --env MINIO_SERVER_SECRET_KEY="***" \
    bitnami/minio-client
```

### What do you see instead?

As soon as I start the container the output is:
```
 09:41:53.40
 09:41:53.40 Welcome to the Bitnami minio-client container
 09:41:53.41 Subscribe to project updates by watching https://github.com/bitnami/containers
 09:41:53.41 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 09:41:53.41
 09:41:53.41 INFO  ==> ** Starting MinIO Client setup **
minio-client 09:41:53.41 INFO  ==> Adding Minio host to 'mc' configuration...
Added `minio` successfully.

 09:41:53.74 INFO  ==> ** MinIO Client setup finished! **
mc: <ERROR> `/opt/bitnami/scripts/minio-client/run.sh` is not a recognized command.
```

**Comment by carrodher** [comment]
Are you using a Macbook M1? Please note Bitnami containers are not supported on ARM architectures, just in case it is your case

**Comment by gidoUninova** [comment]
Hi carrodher,

no I am using MAC with intel chipset. Ok understood, thank you for your answer.

**Comment by arshamalh** [comment]
I have almost the same issue, 

I'm not running it in Mac M1, 
I'm running it on Openshift OKD4.

logs:
```
10:04:14.80 Welcome to the Bitnami minio-client container
10:04:14.80 Subscribe to project updates by watching https://github.com/bitnami/containers
10:04:14.81 Submit issues and feature requests at https://github.com/bitnami/containers/issues
10:04:14.82
10:04:14.90 INFO ==> ** Starting MinIO Client setup **
minio-client 10:04:14.92 INFO ==> Adding Minio host to 'mc' configuration...
/opt/bitnami/scripts/libminioclient.sh: line 37: am_i_root: command not found
Added `minio` successfully.
10:04:15.72 INFO ==> ** MinIO Client setup finished! **
mc: <ERROR> `/opt/bitnami/scripts/minio-client/run.sh` is not a recognized command. Get help using `--help` flag.
```

**Comment by Ladrillo84** [comment]
I have the same issue.

$ kubectl run --namespace default minio-client \
     --rm --tty -i --restart='Never' \
     --env MINIO_SERVER_ROOT_USER=$ROOT_USER \
     --env MINIO_SERVER_ROOT_PASSWORD=$ROOT_PASSWORD \
     --env MINIO_SERVER_HOST=minio \
     --image docker.io/bitnami/minio-client:2023.5.4-debian-11-r0 -- admin info minio
Unable to use a TTY - input is not a terminal or the right kind of file
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs:
 23:43:04.41
 23:43:04.41 Welcome to the Bitnami minio-client container
 23:43:04.41 Subscribe to project updates by watching https://github.com/bitnami/containers
 23:43:04.41 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 23:43:04.41
 23:43:04.41 INFO  ==> ** Starting MinIO Client setup **
minio-client 23:43:04.42 INFO  ==> Adding Minio host to 'mc' configuration...
/opt/bitnami/scripts/libminioclient.sh: line 37: am_i_root: command not found
pod "minio-client" deleted
pod default/minio-client terminated (Error)

**Comment by Mauraza** [comment]
Hi @Ladrillo84 , @arshamalh  and @gidoUninova 

I'm working on a solution, I will update this thread when I have more information

**Comment by Mauraza** [comment]
Hi @Ladrillo84 , @arshamalh and @gidoUninova,

In the last version (2023.5.4-debian-11-r3) of minio-client, the problem should be fixed. Could you check it?

**Comment by tvlc** [comment]
The issue has not been resolved. It cannot work according to documentation, as Dockerfile defines both ENTRYPOINT and CMD. Providing command to docker run overwrites original CMD.
A workaround is to call docker run as follows:
`docker run --rm --name minio-client --env MINIO_SERVER_HOST="my.minio.domain" --env MINIO_SERVER_ACCESS_KEY="minio-access-key" --env MINIO_SERVER_SECRET_KEY="minio-secret-key"     bitnami/minio-client   /opt/bitnami/scripts/minio-client/run.sh  mb minio/my-bucket`
