### ISSUE TITLE
Incorrect SPARK_VOLUMEDIR export

### ISSUE THREAD

**Issue by george-zubrienko** [bitnami/containers#11199]
### Name and Version

bitnami/spark:3.3.0

### What steps will reproduce the bug?

Running spark you get this message as a warning:
```
15:18:13.65 
 15:18:13.65 Welcome to the Bitnami spark container
 15:18:13.65 Subscribe to project updates by watching https://github.com/bitnami/containers
 15:18:13.65 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 15:18:13.65 
 15:18:13.65 INFO  ==> ** Starting Spark setup **
realpath: /bitnami/spark/conf: No such file or directory
```

This is due to incorrect path `/bitnami/spark` instead of `/opt/bitnami/spark` in SPARK_VOLUMEDIR

https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/rootfs/opt/bitnami/scripts/libspark.sh#L28-L32

### What is the expected behavior?

No errors are printed on startup.

### What do you see instead?

```
realpath: /bitnami/spark/conf: No such file or directory
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by george-zubrienko** [comment]
Sure, I'll send a PR end of this week then :)

**Comment by george-zubrienko** [comment]
I will create a PR for this shortly
