### ISSUE TITLE
[bitnami/spark] SPARK_JAVA_OPTS variable is unassigned in entrypoint.sh script

### ISSUE THREAD

**Issue by george-zubrienko** [bitnami/containers#11198]
### Name and Version

bitnami/spark:3.3.0

### What steps will reproduce the bug?

Run a spark job with --master k8s:// and Java 17 instead of Java8/11. We replace base java component in the image using the same approach as in Dockerfile.

This happens because in `entrypoint.sh` of `apache/spark` there is an additional line which is missing from bitnami script:

```
env | grep SPARK_JAVA_OPT_ | sort -t_ -k4 -n | sed 's/[^=]*=\(.*\)/\1/g' > /tmp/java_opts.txt
readarray -t SPARK_EXECUTOR_JAVA_OPTS < /tmp/java_opts.txt
```

while in bitnami script `SPARK_EXECUTOR_JAVA_OPTS` is used right away, while Spark driver creates no such variable.

You can also run the job with bitnami/spark:3.3.0 with Java 8 and notice that spark jvm doesn't have any custom options applied in k8s mode.

### What is the expected behavior?

Spark job runs w/o issues with custom java options applied

### What do you see instead?
With Java 17:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x777c111) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x777c111
	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:222)
```
With Java11/8: no custom jvm options applied.

**Comment by george-zubrienko** [comment]
Correction:

```
    set +o pipefail

    env | grep SPARK_JAVA_OPT_ | sort -t_ -k4 -n | sed 's/[^=]*=\(.*\)/\1/g' > /tmp/java_opts.txt
    readarray -t SPARK_EXECUTOR_JAVA_OPTS < /tmp/java_opts.txt
    
    set -o pipefail
```
is a better option.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Would you like to create a PR fixing the assigning of the variable?
