### ISSUE TITLE
[bitnami/mariadb] Add backup mariabackup to mariadb docker image

### ISSUE THREAD

**Issue by devMls** [bitnami/containers#11212]
### Name and Version

bitmani/mariadb

### What is the problem this feature will solve?

I want to use mariabackup to backup mariadb instances.

The mariadb offical image has it.

Automated cron backup will be, in fact perfect.

I am working in mariadbcluster stack for docker swarm: https://github.com/devMls/docker-mariadb-cluster

And i want to provide a backup feature. I want use your image because is awsome, but maybe i need use the official image because the backup feature.

### What is the feature you are proposing to solve the problem?

Minimum add mariabackup to the docker image, just like official mariadb image

Provide a way to automatize this backup will be perfect.

### What alternatives have you considered?

add mariabackup as part of the image

**Comment by devMls** [comment]
This apply to the bitnami/mariadb-galera images

**Comment by marcosbc** [comment]
Hi @devMls, AFAIK the `bitnami/mariadb` image includes `mariabackup` by default:

```
$ docker run -ti bitnami/mariadb:10.9 which mariabackup 2>/dev/null
mariadb 13:59:48.76
mariadb 13:59:48.76 Welcome to the Bitnami mariadb container
mariadb 13:59:48.76 Subscribe to project updates by watching https://github.com/bitnami/containers
mariadb 13:59:48.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mariadb 13:59:48.76

/opt/bitnami/mariadb/bin/mariabackup
```

If your image does not have it, could you share the specific image name/version combination that you are using?

**Comment by devMls** [comment]
Hi @marcosbc 

You are right . Using the console I can find it.

Maybe is a good idea update the  instructions of the image, like mariadb official image, explaining how to do a backup.

Outside of that, is a pain use the terminal for create backups, any recommendation for automatice the backup process inside the container? Provide a way to do that will be fantastic.

**Comment by marcosbc** [comment]
Hi @devMls, we are not recommending any additions to the container images for supporting cron jobs, instead we encourage sysadmins to implement scheduled jobs using their preferred technology, for instance, using Kubernetes CronJob objects.

There, you would only have the need of modelling the specific command to perform the backup, in your case, with `mariabackup`, and the schedule.
