### ISSUE TITLE
[bitnami/kafka] kafka log level

### ISSUE THREAD

**Issue by benitogf** [bitnami/containers#11360]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

using docker compose I set the  enviroment variables to change the log level:
```yml
environment:
      - KAFKA_CFG_LOG4J_ROOT_LOGLEVEL=ERROR
      - KAFKA_CFG_LOG4J_LOGGERS=org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR,kafka.coordinator.group.GroupCoordinator=ERROR,kafka.coordinator.group.GroupMetadataManager=ERROR
```

### What is the expected behavior?

the log level should change to ERROR

### What do you see instead?

log level remains in INFO

```
[2022-10-25 06:57:23,156] INFO [GroupMetadataManager brokerId=1] Finished unloading __consumer_offsets-17 for coordinator epoch Some(5). Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
```
...
```
[2022-10-25 06:57:41,890] INFO [GroupMetadataManager brokerId=1] Finished loading offsets and group metadata from __consumer_offsets-36 in 8 milliseconds for epoch 0, of which 8 milliseconds was spent in the scheduler. (kafka.coordinator.group.GroupMetadataManager)
```

I checked the `cat /opt/bitnami/kafka/config/server.properties`

and the values in the docker enviroment variable is reflected there too:
```
...
log4j.loggers=org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR,kafka.coordinator.group.GroupCoordinator=ERROR,kafka.coordinator.group.GroupMetadataManager=ERROR
log4j.root.loglevel=ERROR
max.partition.fetch.bytes=1048576
...
```
 but it doesnt change the log level

**Comment by carrodher** [comment]
Please note the variables you are setting affect Kafka itself, while the log you are sharing is the one related to the Bitnami initialization.

From the above snippet, you can see how at some point the following sentence appears:
```
kafka 06:57:35.81 INFO  ==> ** Kafka setup finished! **
kafka 06:57:35.82 INFO  ==> ** Starting Kafka **
```

From that moment on, the log shown is the one related to Kafka itself, but previously, it is related to the Bitnami initialization logic.

**Comment by benitogf** [comment]
@carrodher true, the logs after those are kafka though and are still on INFO level

is there a way to change the bitnami log level too? sorry if its a bit offtopic

**Comment by aoterolorenzo** [comment]
I'm afraid you cannot set the loglevel for the Bitnami scripts, but only set it to _DEBUG_ using `BITNAMI_DEBUG=true` os let it by default (_INFO_)

**Comment by benitogf** [comment]
@aoterolorenzo does this default to INFO affects kafka logs too? sorry if the bitnami log level got mixed up here :) just wanted to change the kafka log level to ERROR

**Comment by aoterolorenzo** [comment]
@benitogf the environment variables you used are already setting the kafka log level to `ERROR`, which is independent from the bitnami's output log level. Which you see in your output is the bitnami output log.

`kafka 06:57:35.82 INFO  ==> ** Starting Kafka **` is not a kafka output but an output from the bitnami scripts running on the container to start kafka. After then, you should see no more log than the kafka `ERROR` ones.

**Comment by benitogf** [comment]
@aoterolorenzo sorry for the confusion, I updated the issue removing the bitnami logs, my problem is that after setting the env as described above I can still see INFO level logs from kafka

**Comment by aoterolorenzo** [comment]
I see you are trying with `KAFKA_CFG_LOG4J_LOGGERS=org.apache.kafka=ERROR`

Could you try using `CONNECT_LOG4J_LOGGERS="log4j.logger.io.confluent.<connector-name>=DEBUG"` 
or `KAFKA_CFG_LOG4J_LOGGERS="log4j.logger.io.confluent.<connector-name>=DEBUG"`
  following the documentation from [Using environment variables (Docker)](https://docs.confluent.io/platform/current/connect/logging.html#using-environment-variables-docker)?
  
  Let me know if the problem persist.

**Comment by OneCricketeer** [comment]
@aoterolorenzo  That link is for Confluent containers. They have their own log4j template file in their images...

Also, `CONNECT_` prefix is specifically for Kafka Connect, and will not help with`bitnami/kafka`

`KAFKA_CFG` variables in bitami images only affect Kafka's `server.properties`, not its log4j files, which from what I can find, the bitnami images never allow. 

---

The workaround is to mount a custom `log4j.properties` file, then set [`LOG4J_DIR`](https://github.com/apache/kafka/blob/trunk/bin/kafka-run-class.sh#L218-L236) variable

**Comment by benitogf** [comment]
@OneCricketeer clould you share a docker compose example of using the bitnami image with kafka of error log level? 🥲

**Comment by OneCricketeer** [comment]
I don't have one. The confluentinc/cp-kafka images should be able to be used by any service you're testing

**Comment by aoterolorenzo** [comment]
Hi @OneCricketeer,

I will then raise an internal task for our team to investigate this. We will be in touch when it gets to an outcome.

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. After analyzing internally our priorities and due to other issues/initiatives we are working on, we didn't find the bandwidth to implement this feature.

Being said that, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by benitogf** [comment]
bump

**Comment by benitogf** [comment]
up
