### ISSUE TITLE
[bitnami/wordpress-nginx] exec /opt/bitnami/scripts/wordpress/entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by ivanbarlog** [bitnami/containers#11423]
### Name and Version

bitnami/wordpress-nginx:latest

### What steps will reproduce the bug?

1. I am trying to run `bitnami/wordpress-nginx:latest` with `bitnami/mariadb:latest` on AWS EC2 T4G instance - with graviton (it suppose to be linux/arm64)
2. I've tried to use `docker buildx` in order to build the images for the `linux/arm64` architecture but there is always the same error
3. run `docker run ivanbarlog/bitnami.wordpress-nginx:latest --platform=linux/arm64` on AWS EC2 T4G instance 
4. you should see following error: `exec /opt/bitnami/scripts/wordpress/entrypoint.sh: exec format error`
 
> **Note**
> 
> `ivanbarlog/bitnami.wordpress-nginx:latest` image has been created by following command:
>
> ```bash
> docker buildx build -t "ivanbarlog/bitnami.wordpress-nginx" --platform linux/amd64,linux/arm64 --push .
> ```
> 
> used dockerfile:
> 
> ```Dockerfile
> FROM bitnami/wordpress-nginx:latest
> ```

### What is the expected behavior?

The container should run without problems.

### What do you see instead?

I see following error:

```
exec /opt/bitnami/scripts/wordpress/entrypoint.sh: exec format error
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid that we don't have ARM containers available. In this sense, you may need to use `amd64` instances or use proper architecture emulation in order to make it work.

**Comment by ivanbarlog** [comment]
Is there any plan for creating arm based containers? Or is there any way for me to help you with this?

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversations in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
