### ISSUE TITLE
[bitnami/kafka] Would you consider tagging this repo when publishing container tags

### ISSUE THREAD

**Issue by joostdecock** [bitnami/containers#11540]
### Name and Version

bitnami/kafka:3.3.1

### What is the problem this feature will solve?

Yesterday, I was trying to get `bitnami/kafka:3.2.3` running in KRaft mode. I could not get passed an error (in `kafkalib.sh`) about broker IDs not being matched to quorum voters.

In the end, I decided to create my own build (from this repo) to add some extra debug logging to figure out what was going on. Guess what: It worked.

So the code in the repo had a change that meant it worked. Sure enough, during the night, `bitnami/kafka:3.3.1` was pushed to dockerhub and the issue is now resolved in the upstream image 🎉 

However, it would be a lot easier to know what's changed if this repo would tag the commit from which a given image was built. This way, we could see exactly what was changed between releases, or what is different between HEAD and the latest built image.

Since the build pipeline is automated, I was hoping it would not be a lot of work to also tag the commit a given container tag was built from.

### What is the feature you are proposing to solve the problem?

Tag the commit in this repo that an image was built from with the same tag as the docker image. (in an automated way)

### What alternatives have you considered?

I have saved the docker image, looked into the layers, and tried to figure out what has changed. It's no fun.
Perhaps there's more efficient ways to do this, but I do feel git tags should be relatively straight-forward to add, yet make life easier.

thank you 🙏

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! I will forward this to the team for evaluation.

**Comment by javsalgar** [comment]
Hi!

I'm afraid we currently don't have short term plans to work on this feature, as it would require important change in our automation pipeline.

As soon as there are updates, we will notify the community.
