### ISSUE TITLE
More details for EJBCA image

### ISSUE THREAD

**Issue by chaliy** [bitnami/containers#11908]
### Name and Version

bitnamu/ejbca

### What is the problem this feature will solve?

EJBCA has a considerably non-typical installation and configuration experience. For example, to access the admin part, you have to know the default password, then enroll for the certificate, then download and import the certificate and then you will have access.

### What is the feature you are proposing to solve the problem?

There is already an explanation of the post-install steps at https://github.com/bitnami/bitnami-docker-ejbca/issues/6#issuecomment-822237907 by @rafariossaa , so it would be easy to incorporate this into the README file.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
