### ISSUE TITLE
[bitnami/argo-cd] Release display v99.99.99+unknown instead of v2.5.1+504da42

### ISSUE THREAD

**Issue by SoulKyu** [bitnami/containers#12224]
### Name and Version

bitnami/argocd:2.5.1

### What steps will reproduce the bug?

Create an argocd application with this image

### What is the expected behavior?

UI should display good release v2.5.1+504da42
![image](https://user-images.githubusercontent.com/30684712/199443922-db2f2b72-1681-4eb3-9548-799fa2d6f14e.png)

### What do you see instead?

UI display bad release v99.99.99+unknown
![image](https://user-images.githubusercontent.com/30684712/199444000-f0b334ff-4f1c-45e0-a383-3429b7dfa05f.png)

**Comment by juan131** [comment]
I confirm the issue. The binary seems to be compiled without the corresponding flags:

```console
$ docker run --rm -it docker.io/bitnami/argo-cd:2.5.1-debian-11-r0 argocd version
...
argocd: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit:
  GitTreeState:
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will open a task for fixing it. As soon as there are news, we will let you know.

**Comment by SoulKyu** [comment]
Would it be possible to re-open this as it hasnt been corrected yet ....

**Comment by larsWtz** [comment]
Is there any estimate when this will be resolved? I deployed using version 4.4.9 and still having this issue.

**Comment by smolinari** [comment]
Me too. Having the same issue. 

Scott

**Comment by jssss93** [comment]
Me too , How long take to solve this problem?

**Comment by Camoukey** [comment]
in 4.4.14 the problem is still there

**Comment by melalj** [comment]
Same problem here!

**Comment by noman13** [comment]
In bitnami/argo-cd chart version 4.5.2, this issue still persists.

**Comment by LeTuR** [comment]
Same issue with image `bitnami/argo-cd:2.6.7-debian-11-r3`

**Comment by Mercbot7** [comment]
+1 to resolution.

**Comment by carrodher** [comment]
Latest version of the image show the proper version, see
```console
$ docker run --rm -it docker.io/bitnami/argo-cd:2.13.2 argocd version
 11:07:29.30 INFO  ==>
 11:07:29.30 INFO  ==> Welcome to the Bitnami argo-cd container
 11:07:29.30 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 11:07:29.30 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
 11:07:29.30 INFO  ==>
 11:07:29.31 INFO  ==> Configuring libnss_wrapper

argocd: v2.13.2+dc43124.dirty
  BuildDate: 2024-12-11T19:27:25Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: dirty
  GoVersion: go1.23.4
  Compiler: gc
  Platform: linux/arm64
```
