### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by vincentsarago** [bitnami/containers#12246]
### Name and Version

bitnami/python

### What is the problem this feature will solve?

new version of Python was release last month

### What is the feature you are proposing to solve the problem?

add python 3.11 image 😄

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by vincentsarago** [comment]
thanks for the update @carrodher 

I wanted to start a PR but I didn't really understand where the `COMPONENT` packaging was made!

**Comment by dgomezleon** [comment]
Hi @vincentsarago ,

New Python 3.11 is [available](https://github.com/bitnami/containers/tree/main/bitnami/python/3.11) in the containers repo.

**Comment by vincentsarago** [comment]
@dgomezleon thank you 🙏
