### ISSUE TITLE
[bitnami/kubectl] kube config permission denied

### ISSUE THREAD

**Issue by DavidConnack** [bitnami/containers#12755]
### Name and Version

bitnami/kubectl:latest

### What steps will reproduce the bug?

I am running bitnami/kubectl:latest as follows: `podman run --rm -v $HOME/Documents/config/kube/config:/.kube/config docker.io/bitnami/kubectl:latest`

The permissions on my config are:
```
➜  kube ls -l
total 12
-rw------- 1 david david 11170 Nov  5 20:16 config
```
Perhaps it has to do with the user that the container is running as?
Thank you

### What is the expected behavior?

That the config should be read and used

### What do you see instead?

```
➜  ~ kubectl version
error: error loading config file "/.kube/config": open /.kube/config: permission denied
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid you may need to adapt the permissions so it is accessible by user 1001. If not, try launching the container with the same uid as the one you have in your host.

**Comment by DavidConnack** [comment]
Ok
Thank you for the response

**Comment by bashilias** [comment]
This issue is still present. Started the container with the same uid and id is still set to 1001. Starting the container with user root (--user 0:0) works though.

**Comment by javsalgar** [comment]
Could you let us know how you launched the container so we can reproduce?
