### ISSUE TITLE
[bitnami/wordpress] Set default value for PHP error_log to /dev/stderr

### ISSUE THREAD

**Issue by morremeyer** [bitnami/containers#12775]
### Name and Version

bitnami/wordpress:6.1.0

### What is the problem this feature will solve?

When PHP errors occur, they are not logged anywhere since the error log is turned off.

### What is the feature you are proposing to solve the problem?

Set the `error_log` directive in `/opt/bitnami/php/etc/php.ini` to `error_log = /dev/stderr`.

This might be useful for all containers using PHP.

### What alternatives have you considered?

I'm currently building my own image for this, see [git.mor.re:docker-images/wordpress](https://git.mor.re/docker-images/wordpress/-/blob/7ecf3acc13560a02743bfc3c7d56966de8c9938a/Dockerfile#L6), since I need some other values changed, too.

However, as the logs for the Apache in the container are already set to `/dev/stderr` for errors and `/dev/stdout` for other logs, doing the same for PHP seems sensible to me.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! Would you like to submit a PR?

**Comment by javsalgar** [comment]
I think that place should work

**Comment by morremeyer** [comment]
@javsalgar Where do I need to make the change so that it is used for all containers? I do not know where the source files for the stacksmith build of https://github.com/bitnami/containers/blob/3efd96c8cbd00577a110c2615597a5dc9265cbf3/bitnami/wordpress/6/debian-11/Dockerfile#L25 are maintained
