### ISSUE TITLE
[bitnami/kafka] Kafka Cluster ID different than specified value

### ISSUE THREAD

**Issue by dmtrs4renzic** [bitnami/containers#12917]
### Name and Version

kafka 3.3

### What steps will reproduce the bug?

1. Create a docker-compose file for three kafka instances and assign them to the same cluster using KAFKA_KRAFT_CLUSTER_ID
2. Deploy them using Docker Stack
3. Log into one of the containers and view the cluster id info in meta.properties files (in the Kafka log directory)

### What is the expected behavior?

I expected the cluster id I specified in my docker-compose file to be used.

### What do you see instead?

When I did this, I specified the cluster id as OTMwNzFhYTY1ODNiNGE5OT.  In the meta.properties file, it has OTMwNzFhYTY1ODNiNGE5OQ.  Note the last character difference.  I re-deployed again with a different cluster id and the same thing occurred (last character different).

**Comment by dmtrs4renzic** [comment]
It looks like the environment has the appropriate value.  I started up one Kafka server specifying ZDFiZmU3ODUyMzRiNGI3NG as the cluster id.  The meta.properties file shows the incorrect value (cluster.id=ZDFiZmU3ODUyMzRiNGI3NA) but the environment variable is set correctly (KAFKA_KRAFT_CLUSTER_ID=ZDFiZmU3ODUyMzRiNGI3NG).  I issued `env` in the container to get variables.

**Comment by javsalgar** [comment]
Hi! Could you share the docker-compose you are using to trigger the issue?

**Comment by dmtrs4renzic** [comment]
Make sure to update the ip addresses for machine-{1,2,3}.  They are three separate machines.  Also, my OS is Ubuntu 20.04.5 LTS.

================

version: '3.2'

services:
  kafka01:
    image: 'docker.io/bitnami/kafka:3.3'
    ports:
      - 9194:9194
      - 9193:9193
      - 9192:9192
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9192,CONTROLLER://0.0.0.0:9193,CLIENT://0.0.0.0:9194
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@<machine-1>:9193,2@<machine-2>:9293,3@<machine-3>:9393
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<machine-1>:9192,CLIENT://<machine-1>:9194      
    networks:
      - kafka_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == 1]
    volumes:
      - "/home/dmtrs4renzic/kafka/kafka_data01:/bitnami"

  kafka02:
    image: 'docker.io/bitnami/kafka:3.3'
    ports:
      - 9294:9294
      - 9293:9293
      - 9292:9292
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_BROKER_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9292,CONTROLLER://0.0.0.0:9293,CLIENT://0.0.0.0:9294
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@<machine-1>:9193,2@<machine-2>:9293,3@<machine-3>:9393
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<machine-2>:9292,CLIENT://<machine-2>:9294
    networks:
      - kafka_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == 2]
    volumes:
      - "/home/dmtrs4renzic/kafka/kafka_data02:/bitnami"

  kafka03:
    image: 'docker.io/bitnami/kafka:3.3'
    ports:
      - 9394:9394
      - 9393:9393
      - 9392:9392
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_BROKER_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9392,CONTROLLER://0.0.0.0:9393,CLIENT://0.0.0.0:9394
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@<machine-1>:9193,2@<machine-2>:9293,3@<machine-3>:9393
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<machine-3>:9392,CLIENT://<machine-3>:9394
    networks:
      - kafka_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == 3]
    volumes:
      - "/home/dmtrs4renzic/kafka/kafka_data03:/bitnami"


networks:
  kafka_network:
    driver: overlay
    attachable: true

**Comment by mdhont** [comment]
Could you try using only `KAFKA_CFG_BROKER_ID`, removing `KAFKA_BROKER_ID`?

**Comment by vohoang2002** [comment]
This is my config and it's work. All kafka client can access in kafka1:9194, kafka2:9294, kafka4:9394. If kafka client in the same network as kafka brokers, we can remove expose port in each service
version: '3.8'

services:
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    ports:
      - 9194:9194
    networks:
      - bigdata
    environment:
      # Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193,2@kafka2:9293,3@kafka3:9393
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9192,CONTROLLER://0.0.0.0:9193,CLIENT://0.0.0.0:9194
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9192,CLIENT://kafka1:9092
  
  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:
      - 9294:9294
    networks:
      - bigdata
    environment:
      # Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193,2@kafka2:9293,3@kafka3:9393
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Protocol
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9292,CONTROLLER://0.0.0.0:9293,CLIENT://0.0.0.0:9294
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9292,CLIENT://kafka2:9294
    
  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    ports:
      - 9394:9394
    networks:
      - bigdata
    environment:
      # Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193,2@kafka2:9293,3@kafka3:9393
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Protocol
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9392,CONTROLLER://0.0.0.0:9393,CLIENT://0.0.0.0:9394
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9392,CLIENT://kafka3:9394
    
networks:
  bigdata:
    external: true
