### ISSUE TITLE
[bitnami/phpmyadmin] Unable to start phpmyadmin

### ISSUE THREAD

**Issue by nobiit** [bitnami/containers#12916]
### Name and Version

phpmyadmin:5.2.0-debian-11-r56

### What steps will reproduce the bug?

1. Run a pod in kubernetes

### What is the expected behavior?

Can run phpmyadmin without any error

### What do you see instead?

container exited without error
![image](https://user-images.githubusercontent.com/45024177/200594852-abd23e28-4e99-44a9-b46b-2fdddc91d123.png)

I think the problem lies in httpd
![image](https://user-images.githubusercontent.com/45024177/200595884-80f0ba0d-d72e-4981-b3ce-a56b5df791a3.png)

### Additional information

Versions:
  - kubernetes: v1.24.7
  - containerd: v1.6.9
  - dockerd: 20.10.21
  - OS: Ubuntu 20.04.5 LTS (x86_64 - amd64)

I can run it using docker/containerd.
![image](https://user-images.githubusercontent.com/45024177/200594998-b5ec2b8d-c1d3-495a-88c9-16c26baa882f.png)

I tried getting the source and compiling httpd (https://github.com/nobidev/bitnami-stacksmith/blob/main/httpd/Dockerfile), copy it to bitnami/phpmyadmin and everything works fine

**Comment by nobiit** [comment]
I installed kubernetes as instructed on the homepage
```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys FEEA9169307EA071 8B57C5C2836F4BEB
$ gpg --export FEEA9169307EA071 8B57C5C2836F4BEB | sudo tee /etc/apt/trusted.gpg.d/kubernetes.gpg >>/dev/null
$ echo 'deb https://apt.kubernetes.io kubernetes-xenial main' | sudo tee /etc/apt/sources.list.d/kubernetes.list
$ sudo apt-get -qq update
$ sudo apt-get -qq install -y kubeadm kubectl kubelet
$ kubeadm init
```

**Comment by nobiit** [comment]
I think this is a hardware issue, when running bitnami/php-fpm. I can't run it on that machine either, but on another machine I can run both

**Comment by nobiit** [comment]
However, when I compile php-fpm/httpd from source, everything works fine

**Comment by javsalgar** [comment]
Could it be an architecture issue?

**Comment by nobiit** [comment]
I also guess it's a structural issue. Regarding how php-fpm/httpd is compiled. Can you try recompiling httpd ?

**Comment by nobiit** [comment]
I am using amd64, here is my `uname -a` info.
```
# uname -a
Linux myid-s1 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by javsalgar** [comment]
This is strange because we are using amd64 to compile. Does the kernel show anything meaningful? Maybe the issue lies there.

**Comment by nobiit** [comment]
I also think the problem lies in the kernel. But I don't know what to check. Do you have suggestions for them?

**Comment by javsalgar** [comment]
I would let them know the specs of the machine where it works and the specs where it fails, maybe that could give them some clues

**Comment by chornthorn** [comment]
I have the same problem.
