### ISSUE TITLE
[bitnami/jasperreports] init script for tomcat connectors allways produce "localhost" in AJP connector

### ISSUE THREAD

**Issue by Kendak** [bitnami/containers#12994]
### Name and Version

bitnami/jasperreports:8

### What steps will reproduce the bug?

- grab source url from for docker-compose.yml: https://hub.docker.com/r/bitnami/jasperreports/
- $ curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/jasperreports/docker-compose.yml > docker-compose.yml
- edit docker-compose.yml
- add into section environment:
            - TOMCAT_AJP_PORT_NUMBER=8009
            - TOMCAT_ENABLE_AJP=yes
- $ docker-compose up -d

After start init scripts produce in server.xml this for AJP connector:
```
    <Connector protocol="AJP/1.3" address="localhost" secretRequired="false" port="8009" redirectPort="8443"/>
```
'localhost' value is hardcoded in scripts

### What is the expected behavior?

It would be fine: add new parameter called e.g.: TOMCAT_AJP_ADDRESS with default value "localhost", that can be overrided from docker-compose.yml

### What do you see instead?

Hardcoded address 'localhost' produce allways address localhost in AJP connector in server.xml:
```
    <Connector protocol="AJP/1.3" address="localhost" secretRequired="false" port="8009" redirectPort="8443"/>
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! Would you like to submit a PR adding support for the variable?
