### ISSUE TITLE
Bitnami Laravel Certification documentation or link

### ISSUE THREAD

**Issue by DockerComposeFiles** [bitnami/containers#13236]
### Name and Version

bitnami/laravel

### What is the problem this feature will solve?

I don't no how to edit nginx to configure servers certificate.
There is no nginx.conf file inside of the container. I don't no if nginx will use an file if it will bind into the container

### What is the feature you are proposing to solve the problem?

Description how to add nginx.conf to the project
and adding the According volume path:
volumes:
  - ./conf:/etc/nginx/conf.d

to document how the certificate configuration can be.

### What alternatives have you considered?

Maybe it should be impossible to edit the nginx config of bitnami-Laravel, in this case there should be an notice which alternatives to certificate it gives or link to them.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
