### ISSUE TITLE
bitnami/airflow airflow worker after the second worker is trying to upload the webserver and not a worker

### ISSUE THREAD

**Issue by alon050** [bitnami/containers#13245]
### Name and Version

bitnami/airflow:2.4.2

### What steps will reproduce the bug?

i dont know if it will recreate the bug to do it by yourself because i run it on-prem on openshift, and i modified the image a little bit.

you can try and install the helm with more than 2 workers and maybe it will be recreated.

### What is the expected behavior?

expected behavior is airflow-helm-worker-0, airflow-helm-worker-1, airflow-helm-worker-2, will all be workers and run normally

### What do you see instead?

instead, the third pod that comes up is running the webserver image instead of the worker image

### Additional information

i am trying to install the airflow helm chart on openshift, and i did all the modification i needed too.

i had airflow helm chart on the 2.3.4 version with the same modification and it works just fine.
after i updated the images to the 2.4.2 version the worker statefulset then after the first and second worker pod goes up, the third one is running the webserver instead of the worker image.

the airflow-helm-worker-0, and the airflow-helm-worker-1 is running workers and the airflow-helm-worker-2 is running the webserver, i dont know why the image is getting mixed up. did it happen to anyone else?

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
