### ISSUE TITLE
Listing of components used for containers

### ISSUE THREAD

**Issue by andrewmiskell** [bitnami/containers#13255]
### Name and Version

bitnami/testlink

### What steps will reproduce the bug?

Apologies in advance if I'm asking in the wrong area, but I didn't see any other place to ask. 

Is there's a listing of all the component packages used by the Dockerfile for Bitnami containers hosted on download.bitnami.com? I could seem to find any documentation around that or any information about components via searching.

I'm wanting to update the deprecated testlink container to make sure security patches are installed as we still use the application and chart. As part of that, knowing the available component packages would help to make sure I'm pulling in the latest components packaged by Bitnami.

I'm also wanting to customize/extend the apache container to create a Bugzilla container utilizing Bitnami's base containers instead of reinventing the wheel on a number of areas.

### What do you see instead?

Unable to find information on bitnami packaged components used in their docker containers.

**Comment by carrodher** [comment]
The only way that comes to my mind is accessing the DockerHub repository (https://hub.docker.com/repository/docker/bitnami/testlink) and then going to the _Tags_ view. You can click on any tag, for instance, [`latest`](https://hub.docker.com/layers/bitnami/testlink/latest/images/sha256-ae830f921c84f81026c928d1eb79ae3d66ad8f4d2f78bd7ad95f625bc5bf61b2?context=repo&tab=layers), and there is a view of the _Dockerfile_ used to build this tag.

Taking a look at the _Dockerfile_ you can see the different components installed as part of that image, i.e
```
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.28-7" --checksum 845211ef822dcf886765c285f8a98342f375b62c8a30b998257b0cabe376747f
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "apache" "2.4.53-0" --checksum 716e4948a2c40f0a0cc5b1656052aeef916a79152250b0b6c1392dd1187f575a
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "mysql-client" "10.3.34-4" --checksum bb0089c26028b568dbe8b8875d39cca3c7835c582dda4fcbdcbed599320c57fe
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "libphp" "7.4.28-4" --checksum 216cab0049a1737702a17c924ed7c20128347adc605e6b78fd40db3064c92f5c
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "testlink" "1.9.20-13" --checksum e21d2d1e7a7c0b281b1609d416f8f37e87161278fd68eb218ee55b29f1ba4b9a
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "render-template" "1.0.1-10" --checksum 97c2ae4b001c5937e888b920bee7b1a40a076680caac53ded6d10f6207d54565
/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.14.0-7" --checksum d6280b6f647a62bf6edc74dc8e526bfff63ddd8067dcb8540843f47203d9ccf1
```

**Comment by andrewmiskell** [comment]
I understood that part, but what if I wanted to see if there was an upgrade to the apache component (either in version or patch)? Because testlink is deprecated looking at its Dockerfile doesn't help because it's no longer updated by Bitnami. I'd have to dig around other container Dockerfiles in order to see if there was a newer component to backport into the testlink container.

I guess the core question I'm asking is if there is a public inventory or listing of the component tarballs that are stored on download.bitnami.com? If there was, I could choose the newest component tarballs to backport into the testlink container to make sure it has the latest components installed.

**Comment by carrodher** [comment]
Since those artifacts are not a final product and are just intermediate artifacts there is no dedicated inventory. You need to check other Dockerfiles which are not deprecated and look for the latest versions. Since all the Dockerfiles are stored in this monorepo, obtaining that info shouldn't be complex.
