### ISSUE TITLE
[bitnami/discourse] New version 2.8.10 with several CVE's fixed is not auto builded

### ISSUE THREAD

**Issue by notz** [bitnami/containers#13330]
### Name and Version

bitnami/discourse:2.8.10

### What steps will reproduce the bug?

New release is available since 10 days. Here is the announcement: https://meta.discourse.org/t/2-8-10-security-release/243761

### What is the expected behavior?

New image is build and published to docker

### What do you see instead?

No new build

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.
