### ISSUE TITLE
bitnami spark runs on java8 and there is no bitnami spark image with java 11

### ISSUE THREAD

**Issue by anilchalissery** [bitnami/containers#13409]
### Name and Version

bitnami/spark:3.3.3

### What is the problem this feature will solve?

I had the same issue as https://github.com/bitnami/bitnami-docker-spark/issues/40#issue-952454432 and https://github.com/bitnami/bitnami-docker-spark/issues/40#issuecomment-886405776

was the fix they suggested but the checksum seems outdated 

### What is the feature you are proposing to solve the problem?

`RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "11.0.15-1-1" --checksum 6d176a8b3c894c608106fee2cf10aaf3771015defb0b7e08fe60ce6c9c1cd342`

this solved the issue

### What alternatives have you considered?

Hope we could get a new spark with java 11 from bitnami

**Comment by carrodher** [comment]
You don't need to care about the checksum, just edit the Spark Dockerfile (for instance the one present at `bitnami/spark/3.3/debian-11`) using the Java version you prefer. You can obtain the exact versions from the Java Dockerfile (i.e https://github.com/bitnami/containers/blob/main/bitnami/java/11/debian-11/Dockerfile#L24):
```diff
__________________________________________________________________
modified: bitnami/spark/3.3/debian-11/Dockerfile
__________________________________________________________________
@ bitnami/spark/3.3/debian-11/Dockerfile:27 @ RUN install_packages ca-certificates curl libbz2-1.0 libcom-err2 libcrypt1 libff
RUN mkdir -p /tmp/bitnami/pkg/cache/ && cd /tmp/bitnami/pkg/cache/ && \
    COMPONENTS=( \
      "python-3.8.15-1-linux-${OS_ARCH}-debian-11" \
-     "java-1.8.352-1-linux-${OS_ARCH}-debian-11" \
+     "java-11.0.17-7-1-linux-${OS_ARCH}-debian-11" \
      "spark-3.3.1-1-linux-${OS_ARCH}-debian-11" \
      "gosu-1.14.0-155-linux-${OS_ARCH}-debian-11" \
    ) && \
```

Building the Dockerfile with the above modification will create a Spark image bundling Java 11.0.17
