### ISSUE TITLE
[bitnami/minio] Minio container update problems with tag 2022.10.29 and higher

### ISSUE THREAD

**Issue by micudaj** [bitnami/containers#13592]
### Name and Version

bitnami/minio:2022.10.29+

### What steps will reproduce the bug?

I am running the bitnami minio container since quite a few months now. since I tries to update the container to version 2022.10.29 and higher the container does not start anymore. It repeatedly tries "Adding local Minio host to 'mc' configuration..." but after some tries it fails and the container restarts. It works in a fresh setup, but not in my config.
Tag 2022.10.24 is the last version to run fine for me. Any hints?

### What is the expected behavior?

I can update my minio container to a tag 2022.10.29 or newer.

### What do you see instead?

I can not run a container with my config with tag 2022.10.29 or newer

**Comment by javsalgar** [comment]
Hi,

Could you launch the container with `BITNAMI_DEBUG=true`? This should provide more insight on the issue

**Comment by micudaj** [comment]
Thank you for the hint! Seems like I have to migrate my deployment.

**Comment by ekeih** [comment]
@micudaj What do you mean with `Seems like I have to migrate my deployment.`? What did you change to make it work?

I am asking because this looks like the same issue as https://github.com/bitnami/charts/issues/13245. 🤔

**Comment by micudaj** [comment]
Yes. that is what I figured out as well. I did not migrate yet though, but that is the path I will go.

**Comment by ekeih** [comment]
Thanks for the quick response!
I just finished the migration. It is a bit cumbersome but the instructions on https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html work perfectly.

**Comment by morremeyer** [comment]
As noted here, the startup scripts run into a loop of 

```
Adding local Minio host to 'mc' configuration...
```

I think this message could be improved to hint at problems while adding the host. If that causes an error, it should be displayed in the logs.

I would open a PR for that myself, but due to the complexity of the scripts, I'm not exactly sure where to start with this.
