### ISSUE TITLE
[bitnami/discourse] How to not pass SMTP Username and Password for discourse image

### ISSUE THREAD

**Issue by subbareddydagumati** [bitnami/containers#13632]
### Name and Version

bitnami/discourse:2

### What is the problem this feature will solve?

Our SMTP server doesn't need any authentications to send emails. Not sure how can we utilize it for the discourse image
Is there any way to pass the DISCOURSE_SMTP_AUTH as none?

### What is the feature you are proposing to solve the problem?

Allow DISCOURSE_SMTP_AUTH: none

**Comment by javsalgar** [comment]
Hi! Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
