### ISSUE TITLE
[bitnami/postgresql] Please bring back curl

### ISSUE THREAD

**Issue by tonsV2** [bitnami/containers#13637]
### Name and Version

bitnami/postgresql:14

### What is the problem this feature will solve?

I seed my databases using a shell script which first checks if the database needs to be seeded. Therefor it can't be done from an init container (since the database isn't running yet).
The database dumps are rather big so I only want to download if I really need too. Furthermore, even if it made sense to download them I can't use the pgc format. Since only .sh, .sql and .sql.gz formats are supported.

I understand why curl was removed and I'm all in favor of minimizing the attack surface. However just like we don't ban cars or phones because they're some times used to do bad things, we still need them in our everyday life.

### What is the feature you are proposing to solve the problem?

Bring back curl

### What alternatives have you considered?

I considered using an init container which isn't feasible because it runs before the database is running. So I can't check if the database should be seeded.

I considered reinstalling curl but this means I can't run my container as unprivileged and using a ro fs. So despite curl being removed to make the image more secure it'll have quite the opposite effect in my case.

**Comment by carrodher** [comment]
Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. In this case, `curl` is not used by the PostgreSQL application but by a custom script you're loading assuming that `curl` is installed in the container. We reviewed when `curl` (and other packages) are used by the main application and remove it when it was not used.

You can use the `install_packages` script to install it if it is needed for your use case when creating your custom image based on Bitnami’s or using `curl` as part of any custom script.
Please take into account, Bitnami containers are non-root by default, in order to be able to install packages you will need to run the container as root (at least when installing the package)

**Comment by tonsV2** [comment]
> Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. In this case, `curl` is not used by the PostgreSQL application but by a custom script you're loading assuming that `curl` is installed in the container. We reviewed when `curl` (and other packages) are used by the main application and remove it when it was not used.

I understand the motivation for trimming down the image but isn't it a fairly normal use case to download some data and import it?

> You can use the `install_packages` script to install it if it is needed for your use case when creating your custom image based on Bitnami’s or using `curl` as part of any custom script. Please take into account, Bitnami containers are non-root by default, in order to be able to install packages you will need to run the container as root (at least when installing the package)

How can I do that? Upgrade to root when installing the package only?

**Comment by carrodher** [comment]
In the following links you can find some info about how to work with non-root containers:
* https://docs.bitnami.com/tutorials/work-with-non-root-containers
* https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/

**Comment by tonsV2** [comment]
@carrodher sorry for being a bit slow, but how's that suppose to help me?

**Comment by carrodher** [comment]
In those links you can find information about how to run/execute the non-root images as root in order to be able to install the desired package.

**Comment by tonsV2** [comment]
But running the database as root isn't a viable solution

**Comment by carrodher** [comment]
You can build your own image using root only when installing any desired package:
```Dockerfile
FROM bitnami/postgresql
USER root
RUN install_packages curl
USER 1001
```
