### ISSUE TITLE
[bitnami/mongodb-exporter] Authentication failed issue with SCRAM-SHA-1

### ISSUE THREAD

**Issue by sandeepmuthathi** [bitnami/containers#13650]
### Name and Version

bitnami/mongodb-exporter

### What steps will reproduce the bug?

"Cannot connect to MongoDB: cannot connect to MongoDB: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed."

### What do you see instead?

"Cannot connect to MongoDB: cannot connect to MongoDB: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed."

**Comment by javsalgar** [comment]
Hi,

Do you have a sample docker-compose or chart values that we can use to reproduce the issue?

**Comment by javsalgar** [comment]
Thanks for letting us know!
