### ISSUE TITLE
how to get authentication?

### ISSUE THREAD

**Issue by AdewuyiOyawoye** [bitnami/containers#13665]
### Name and Version

bitnami 2.3.2-debian-11-r14 release

### What steps will reproduce the bug?

run locally

try to GET request to http://localhost:8080/api/v1/dags/my-DAG/dagRuns

gets 401

How do I get authenticated? I've tried basic auth using the username I used to log in i.e `user` and `bitnami` and added this  `AIRFLOW_API_AUTH_BACKENDS = airflow.api.auth.backend.basic_auth` to my _dockerfile_ but it doesn't work, can you please point me in the right direction? Thanks

**Comment by carrodher** [comment]
Could you provide more info to reproduce the issue on our side? It would be great to have the _Dockerfile_ and _docker-compose.yaml_ to deploy the same scenario

**Comment by AdewuyiOyawoye** [comment]
this has now been solved with AIRFLOW__API__AUTH_BACKENDS, double underscore was needed between the first 3 words
