### ISSUE TITLE
[bitnami/kubectl] curl

### ISSUE THREAD

**Issue by vhsantos** [bitnami/containers#13820]
### Name and Version

bitnami/kubectl:1.24.6-debian-11-r4

### What is the problem this feature will solve?

Hello there,

I have been reading different requests (for example [13637](https://github.com/bitnami/containers/issues/13637), [9096](https://github.com/bitnami/containers/pull/9096), [10087](https://github.com/bitnami/containers/issues/10087)) to bring back curl on the containers and the same explication mentioning that the idea is to reduce the attack surface on the containers. But in this case, are not **kubectl** and **curl** very close systems that access the API system ? Should not be enough reason to have both installed on the same container ?

We have used the bitnami/kubectl container to run some commands via kubectl and curl to report the output to another system (via https/API) in the past and now we got the error because curl has been removed.

We know that we can install curl by ourselves and/or create a new image, but this will make bitnami/kubectl useless by itself.

PR with the changes [here](https://github.com/bitnami/containers/pull/8846/commits/328f20446cc64d467daac93f3edefe8e62a735e8) 
PS: I saw some comments about the [size of the containers](https://blog.bitnami.com/2022/10/bitnami-improves-container-catalog-size.html), but on [this case](https://hub.docker.com/r/bitnami/kubectl/tags?page=1&name=1.24.6) we are talking about less than 200k.

### What is the feature you are proposing to solve the problem?

Add curl package back on the container.

**Comment by OneCricketeer** [comment]
Could you not use `kubectl run` to execute `busybox` container within the k8s cluster, then `curl` within busybox?

**Comment by javsalgar** [comment]
Hi,

The amount of packages that curl adds to the system and its update cadence because of CVEs was the main justification for removing the package. We don't have enough evidence to prove that a substantial amount of users use `kubectl` in conjunction with `curl`. If that's the case, we could consider re-adding it.
