### ISSUE TITLE
[bitnami/thanos] Release v0.29.0

### ISSUE THREAD

**Issue by hbollon** [bitnami/containers#13825]
### Name and Version

bitnami/thanos:v0.29.0

### What steps will reproduce the bug?

v0.29.0 was released few weeks ago (cf. https://quay.io/repository/thanos/thanos/manifest/sha256:4766a6caef0d834280fed2d8d059e922bc8781e054ca11f62de058222669d9dd) but your automated release process seems to haven't saw it.

### What is the expected behavior?

If I understand correctly your release workflow, your automation should have already released a new bitnami/thanos:v0.29.0 

### What do you see instead?

The latest available bitnami/thanos image is *0.28.1-scratch-r0*

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by corico44** [comment]
Hello @hbollon,

We inform you that the issues have been fixed and that version 0.29.0 of Thanos is now available.

Thank you very much for the contribution!
