### ISSUE TITLE
[bitnami/ejbca] Could non-production version tag be added?

### ISSUE THREAD

**Issue by Luk164** [bitnami/containers#13830]
### Name and Version

bitnami/ejbca

### What is the problem this feature will solve?

EJBCA comes with a build in swagger, but it is only available when built with[ `ejbca.productionmode=false`](https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/protocols/ejbca-rest-interface)

Could a container image with this flag be added please? I tried building it on my own but I cannot find the conf/ejbca.properties file anywhere.

### What is the feature you are proposing to solve the problem?

Adding a tagged version of image with the aforementioned setting used for easier debugging a development.

### What alternatives have you considered?

Nothing comes to mind.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that our system does not support building two flavors for EJBCA. I'm not sure if this file is only used at `maven` build time. In this sense, you would need to create your own fork of EJBCA and use it.

**Comment by Luk164** [comment]
> Hi,
> 
> I'm afraid that our system does not support building two flavors for EJBCA. I'm not sure if this file is only used at `maven` build time. In this sense, you would need to create your own fork of EJBCA and use it.

I am sorry but I have no idea how to do something like that. I am not familiar with bitnami build process. Do you have some tips for me to get this working?

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the build scripts are not available at the moment, but we perform `ant build` to build ejbca, and then place the contents in `/opt/bitnami/ejbca`. Hope this helps

**Comment by Luk164** [comment]
@javsalgar I am sorry but try as I might I could not get EJBCA to build by myself. There is quite a lot of requirements and I had trouble setting them all up. Is there by any chance a container image with all the requirements pre-installed?

**Comment by Luk164** [comment]
@javsalgar I am not asking to move everything to the non-production mode. That would defeat the primary purpose of the container. I am just asking to add a secondary tagged version.

**Comment by javsalgar** [comment]
Hi,

I understand, but currently that's not something our automations can implement. If, in the future, this is something we can add in our pipeline, we'll evaluate it, but at the moment we don't have support for different flavours (apart from branches) of the same product.

**Comment by Luk164** [comment]
@javsalgar In that case, could another branch be added? Or would that be just too much to maintain for such a small feature?

**Comment by javsalgar** [comment]
I'm afraid yes, the maintenance effort would be too high for a non-production product.

**Comment by Luk164** [comment]
@javsalgar Oh well...
