### ISSUE TITLE
[bitnami/pgbouncer] Container won't accept an IPv6 or wildcard listen address

### ISSUE THREAD

**Issue by jgnieuwhof** [bitnami/containers#13866]
### Name and Version

bitnami/pgbouncer:1.17.0

### What steps will reproduce the bug?

Specify an IPv6 address, or asterisk (`*`), as a value for the `PGBOUNCER_LISTEN_ADDRESS` environment variable.

### What is the expected behavior?

That the `PGBOUNCER_LISTEN_ADDRESS` would accept IPv4, IPv6, and `*` values, as pgBouncer does:

https://www.pgbouncer.org/config.html#listen_addr

### What do you see instead?

An error stating that the `PGBOUNCER_LISTEN_ADDRESS` should be an IPv4 address or a resolvable hostname.

### Additional information

I ended up forking the repo to remove the IPv4 check, which solved the problem for me (for now):

https://github.com/jgnieuwhof/containers/pull/1/files

Just raising this issue in hopes of removing the fork. I suppose the real version of this could either remove the check (as above), or extend the existing validation to accept both wildcard and IPv6 address.

Thanks for the great image, everything else worked as expected!

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting the issue. Would you like to submit a PR with the fix you made so it is available in the container?

**Comment by jgnieuwhof** [comment]
Sure thing!

**Comment by carrodher** [comment]
Thanks for the PR, the team will review and provide feedback!
