### ISSUE TITLE
how to add LDAP ACL to allow write access for all users in specific ou

### ISSUE THREAD

**Issue by bnaigaonkar** [bitnami/containers#13891]
### Name and Version

bitnami/openldap:2.6.3-debian-11-r16

### What steps will reproduce the bug?

**root@ip-10-31-2-91:~# cat /opt/test/test.ldif**
```
dn: cn=brohan,ou=people,dc=bty,dc=com
objectClass: ptyBusinessRolePermissions
objectClass: device
permissionName: "Appliance CLI Viewer"
permissionInfo: "user that can login the CLI as a viewer"
attribute: businessCategory=pap_viewer
attribute: businessCategory=can_login_os
cn: brohan
```
### What is the expected behavior?

Allow write access for all users in specific ou.
As per below example, we want user under ou=people to have the write access to the LDAP

### What do you see instead?

```
ldapadd -Y EXTERNAL -H ldapi:/// -D "cn=admin,ou=people,dc=bty,dc=com" -w "admin123" -f  /opt/test/test.ldif
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=brohan,ou=people,dc=bty,dc=com"
**ldap_add: Insufficient access (50)
        additional info: no write access to parent**
**ldif file: -**
```

**root@ip-10-31-2-91:~# cat /opt/test/test.ldif**
```
dn: cn=brohan,ou=people,dc=bty,dc=com
objectClass: ptyBusinessRolePermissions
objectClass: device
permissionName: "Appliance CLI Viewer"
permissionInfo: "Appliance user that can login the CLI as a viewer"
attribute: businessCategory=pap_viewer
attribute: businessCategory=can_login_os
cn: brohan
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami openldap container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by gutmensch** [comment]
Confirming the comment from @carrodher, no issue of the container, but needs to be implemented by the user.

@bnaigaonkar You need to work with ACLs to manipulate write access to certain users or subtrees (and deviating from the existing olcAccess settings applied by default), an untested example according to your input would be 
```
dn: olcDatabase{1}hdb,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to dn.subtree="ou=people,dc=bty,dc=com" by dn.exact
 ="cn=admin,ou=people,dc=bty,dc=com" write by * break
olcAccess: {1}to attrs=userPassword,shadowLastChange by self write by anonym
 ous auth by * none
olcAccess: {2}to dn.base="" by users read
olcAccess: {3}to * by users read
```
NB: The database might be different for you and the olcAccess defaults you should also check from your local config, then adapt this to your needs and run ldapmodify.
