### ISSUE TITLE
consider lua support for haproxy

### ISSUE THREAD

**Issue by jouve** [bitnami/containers#13890]
### Name and Version

bitnami/haproxy

### What is the problem this feature will solve?

https://github.com/haproxy/haproxy/blob/master/doc/lua.txt

https://www.haproxy.com/fr/blog/5-ways-to-extend-haproxy-with-lua/

### What is the feature you are proposing to solve the problem?

lua support compiled into haproxy  (`USE_LUA=1`)

### What alternatives have you considered?

https://github.com/docker-library/haproxy/blob/master/2.6/Dockerfile#L52 but I'd rather stay with bitnami :)

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your suggestion, I am creating a internal task to analyze it an eventually implement it.
  However, we are a small team so I could not provide an ETA for this.
  We will come back as soon as we have news.

**Comment by CeliaGMqrz** [comment]
Hi @jouve,

This [version](https://github.com/bitnami/containers/pull/27470) has just been released. The support for Lua is now enabled in Haproxy. The container provides an updated version of Lua. Your feedback is welcome :)
