### ISSUE TITLE
Where do we mount logs to in the bitname airflow docker?

### ISSUE THREAD

**Issue by AdewuyiOyawoye** [bitnami/containers#13998]
### Name and Version

[bitnami/airflow] Release 2.4.2-debian-11-r0 

### What steps will reproduce the bug?

I know we can mount custom dags to `/opt/bitnami/airflow/dags`.
I do it this way volumes:
```
    - ./dags:/opt/bitnami/airflow/dags
```
But how can we mount logs? I've tried
```
    - ./logs:/opt/bitnami/airflow/logs
```
but it doesn't mount any logs it just creates a log folder but it doesn't create the log folders and files like it does when airflow is run without docker on wsl 

### What is the expected behavior?

expect to see logs in opt/bitnami/airflow/logs

### What do you see instead?

No logs seen

**Comment by carrodher** [comment]
Custom DAG files can be mounted to `/opt/bitnami/airflow/dags` but the logs are redirected to the stdout of the container

**Comment by AdewuyiOyawoye** [comment]
> Custom DAG files can be mounted to `/opt/bitnami/airflow/dags` but the logs are redirected to the stdout of the container

Hi but I can't see them in the container logs for either airflow, airflow-worker or airflow-scheduler when I use dockerdesktop to view the container logs

**Comment by AdewuyiOyawoye** [comment]
trying to lock to docker and to azure, AIRFLOW__CORE__REMOTE_LOGGING=True doesn't seem to work, it actually breaks the deployment.
Added AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=https://xxxxxxx.blob.core.windows.net/airflow-logs too but it doesn't solve the problem

**Comment by gongomgra** [comment]
Hi @AdewuyiOyawoye,

By default, Airflow is configured to write DAGs execution logs into files in the worker's filesystem under the `/opt/bitnami/airflow/logs/<dag-name>` folder. Alternativelly, you can set the `AIRFLOW_SECRET_KEY` with the same value in all the airflow-containers (airflow, scheduler, worker), and it will make the logs to be available in the Airflow web UI.

As an example, I run the `example_bash_operator` DAG and I retrieved the logs both from the filesystem and the web UI

```
$ docker exec -it -u root debian-11-airflow-worker-1 bash
root@9b84f27cea1e:/opt/bitnami/airflow/logs# cat /opt/bitnami/airflow/logs/dag_id\=example_bash_operator/run_id\=manual__2022-12-15T16\:51\:53.880466+00\:00/task_id\=runme_0/attempt\=1.log
[2022-12-15T16:51:55.499+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
[2022-12-15T16:51:55.512+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
[2022-12-15T16:51:55.512+0000] {taskinstance.py:1283} INFO -
--------------------------------------------------------------------------------
[2022-12-15T16:51:55.512+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-15T16:51:55.513+0000] {taskinstance.py:1285} INFO -
--------------------------------------------------------------------------------
[2022-12-15T16:51:55.533+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): runme_0> on 2022-12-15 16:51:53.880466+00:00
[2022-12-15T16:51:55.540+0000] {standard_task_runner.py:55} INFO - Started process 163 to run task
[2022-12-15T16:51:55.561+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', 'manual__2022-12-15T16:51:53.880466+00:00', '--job-id', '10', '--raw', '--subdir', '/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpyjebkpiu']
[2022-12-15T16:51:55.562+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask runme_0
[2022-12-15T16:51:55.707+0000] {task_command.py:389} INFO - Running <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [running]> on host 9b84f27cea1e
[2022-12-15T16:51:55.882+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T16:51:53.880466+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T16:51:53.880466+00:00
[2022-12-15T16:51:55.884+0000] {subprocess.py:63} INFO - Tmp dir root location:
 /tmp
[2022-12-15T16:51:55.885+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "example_bash_operator__runme_0__20221215" && sleep 1']
[2022-12-15T16:51:55.905+0000] {subprocess.py:86} INFO - Output:
[2022-12-15T16:51:55.907+0000] {subprocess.py:93} INFO - example_bash_operator__runme_0__20221215
[2022-12-15T16:51:56.910+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-12-15T16:51:56.953+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20221215T165153, start_date=20221215T165155, end_date=20221215T165156
[2022-12-15T16:51:56.981+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-15T16:51:57.017+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

![Screen Shot 2022-12-15 at 18 13 59](https://user-images.githubusercontent.com/6660452/207924813-c09b7555-da58-44b2-9430-072de8ddc6c5.png)

Please check the [official Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html) for further information on how to remotely consume these log messages.

**Comment by AdewuyiOyawoye** [comment]
> Hi @AdewuyiOyawoye,
> 
> By default, Airflow is configured to write DAGs execution logs into files in the worker's filesystem under the `/opt/bitnami/airflow/logs/<dag-name>` folder. You can also set the `AIRFLOW_SECRET_KEY` with the same value in all the airflow-containers (airflow, scheduler, worker), and it will make the logs to be available in the Airflow web UI.
> 
> As an example, I run the `example_bash_operator` DAG and I retrieved the logs both from the filesystem and the web UI
> 
> ```
> $ docker exec -it -u root debian-11-airflow-worker-1 bash
> root@9b84f27cea1e:/opt/bitnami/airflow/logs# cat /opt/bitnami/airflow/logs/dag_id\=example_bash_operator/run_id\=manual__2022-12-15T16\:51\:53.880466+00\:00/task_id\=runme_0/attempt\=1.log
> [2022-12-15T16:51:55.499+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1283} INFO -
> --------------------------------------------------------------------------------
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
> [2022-12-15T16:51:55.513+0000] {taskinstance.py:1285} INFO -
> --------------------------------------------------------------------------------
> [2022-12-15T16:51:55.533+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): runme_0> on 2022-12-15 16:51:53.880466+00:00
> [2022-12-15T16:51:55.540+0000] {standard_task_runner.py:55} INFO - Started process 163 to run task
> [2022-12-15T16:51:55.561+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', 'manual__2022-12-15T16:51:53.880466+00:00', '--job-id', '10', '--raw', '--subdir', '/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpyjebkpiu']
> [2022-12-15T16:51:55.562+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask runme_0
> [2022-12-15T16:51:55.707+0000] {task_command.py:389} INFO - Running <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [running]> on host 9b84f27cea1e
> [2022-12-15T16:51:55.882+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
> AIRFLOW_CTX_DAG_OWNER=airflow
> AIRFLOW_CTX_DAG_ID=example_bash_operator
> AIRFLOW_CTX_TASK_ID=runme_0
> AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T16:51:53.880466+00:00
> AIRFLOW_CTX_TRY_NUMBER=1
> AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T16:51:53.880466+00:00
> [2022-12-15T16:51:55.884+0000] {subprocess.py:63} INFO - Tmp dir root location:
>  /tmp
> [2022-12-15T16:51:55.885+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "example_bash_operator__runme_0__20221215" && sleep 1']
> [2022-12-15T16:51:55.905+0000] {subprocess.py:86} INFO - Output:
> [2022-12-15T16:51:55.907+0000] {subprocess.py:93} INFO - example_bash_operator__runme_0__20221215
> [2022-12-15T16:51:56.910+0000] {subprocess.py:97} INFO - Command exited with return code 0
> [2022-12-15T16:51:56.953+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20221215T165153, start_date=20221215T165155, end_date=20221215T165156
> [2022-12-15T16:51:56.981+0000] {local_task_job.py:159} INFO - Task exited with return code 0
> [2022-12-15T16:51:57.017+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
> ```
> 
> ![Screen Shot 2022-12-15 at 18 13 59](https://user-images.githubusercontent.com/6660452/207924813-c09b7555-da58-44b2-9430-072de8ddc6c5.png)
> 
> Please check the [official Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html) for further information on how to remotely consume these log messages.
> 
> Additionally, you can try to mount your custom `logs` folder into the `airflow-worker` container instead of the `airflow` one.



> Hi @AdewuyiOyawoye,
> 
> By default, Airflow is configured to write DAGs execution logs into files in the worker's filesystem under the `/opt/bitnami/airflow/logs/<dag-name>` folder. You can also set the `AIRFLOW_SECRET_KEY` with the same value in all the airflow-containers (airflow, scheduler, worker), and it will make the logs to be available in the Airflow web UI.
> 
> As an example, I run the `example_bash_operator` DAG and I retrieved the logs both from the filesystem and the web UI
> 
> ```
> $ docker exec -it -u root debian-11-airflow-worker-1 bash
> root@9b84f27cea1e:/opt/bitnami/airflow/logs# cat /opt/bitnami/airflow/logs/dag_id\=example_bash_operator/run_id\=manual__2022-12-15T16\:51\:53.880466+00\:00/task_id\=runme_0/attempt\=1.log
> [2022-12-15T16:51:55.499+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [queued]>
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1283} INFO -
> --------------------------------------------------------------------------------
> [2022-12-15T16:51:55.512+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
> [2022-12-15T16:51:55.513+0000] {taskinstance.py:1285} INFO -
> --------------------------------------------------------------------------------
> [2022-12-15T16:51:55.533+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): runme_0> on 2022-12-15 16:51:53.880466+00:00
> [2022-12-15T16:51:55.540+0000] {standard_task_runner.py:55} INFO - Started process 163 to run task
> [2022-12-15T16:51:55.561+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', 'manual__2022-12-15T16:51:53.880466+00:00', '--job-id', '10', '--raw', '--subdir', '/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpyjebkpiu']
> [2022-12-15T16:51:55.562+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask runme_0
> [2022-12-15T16:51:55.707+0000] {task_command.py:389} INFO - Running <TaskInstance: example_bash_operator.runme_0 manual__2022-12-15T16:51:53.880466+00:00 [running]> on host 9b84f27cea1e
> [2022-12-15T16:51:55.882+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
> AIRFLOW_CTX_DAG_OWNER=airflow
> AIRFLOW_CTX_DAG_ID=example_bash_operator
> AIRFLOW_CTX_TASK_ID=runme_0
> AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T16:51:53.880466+00:00
> AIRFLOW_CTX_TRY_NUMBER=1
> AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T16:51:53.880466+00:00
> [2022-12-15T16:51:55.884+0000] {subprocess.py:63} INFO - Tmp dir root location:
>  /tmp
> [2022-12-15T16:51:55.885+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "example_bash_operator__runme_0__20221215" && sleep 1']
> [2022-12-15T16:51:55.905+0000] {subprocess.py:86} INFO - Output:
> [2022-12-15T16:51:55.907+0000] {subprocess.py:93} INFO - example_bash_operator__runme_0__20221215
> [2022-12-15T16:51:56.910+0000] {subprocess.py:97} INFO - Command exited with return code 0
> [2022-12-15T16:51:56.953+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20221215T165153, start_date=20221215T165155, end_date=20221215T165156
> [2022-12-15T16:51:56.981+0000] {local_task_job.py:159} INFO - Task exited with return code 0
> [2022-12-15T16:51:57.017+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
> ```
> 
> ![Screen Shot 2022-12-15 at 18 13 59](https://user-images.githubusercontent.com/6660452/207924813-c09b7555-da58-44b2-9430-072de8ddc6c5.png)
> 
> Please check the [official Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html) for further information on how to remotely consume these log messages.
> 
> Additionally, you can try to mount your custom `logs` folder into the `airflow-worker` container instead of the `airflow` one.

Thanks I'm now able to see the logs through the UI, using the secret key.
