### ISSUE TITLE
[Discouse] Permissions problem on random posts

### ISSUE THREAD

**Issue by matheusnagatsuka** [bitnami/containers#14165]
### Name and Version

bitnami/discourse:2.8.9

### What steps will reproduce the bug?

We are having permission problems with some posts. Even users with the proper permissions cannot access the content of these posts, we have tried to redo the permissions from scratch and leave them open however only users with admin permissions can view them.

### What do you see instead?

The logs only show the error 403
`Completed 403 Forbidden in 35ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 4004)`

### Additional information

Has anyone experienced the same problem? If so how was it solved?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
