### ISSUE TITLE
[mongodb] Doesn't start properly on macbook silicon

### ISSUE THREAD

**Issue by denis-zhdanov** [bitnami/containers#14169]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

noop-dummy

### bndiagnostic was not useful. Could you please tell us why?

docs: The Bitnami Diagnostic Tool is a command line tool that gathers relevant information for the Bitnami Support Team to debug certain issues in Bitnami Stacks. This tool is located in the installation directory of the stack at /opt/bitnami. I don't have any bitnami stack, I just want to run a container from one of bitnami images

### Describe your issue as much as you can

Running docker container from bitnami mongo image on my macbook pro m1 apple silicon:

```
docker run -it -p 27017:27017 docker.io/bitnami/mongodb:6.0.2-debian-11-r11
```

getting the following output:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
mongodb 17:20:04.02
mongodb 17:20:04.05 Welcome to the Bitnami mongodb container
mongodb 17:20:04.08 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 17:20:04.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 17:20:04.14
mongodb 17:20:04.16 INFO  ==> ** Starting MongoDB setup **
mongodb 17:20:04.32 INFO  ==> Validating settings in MONGODB_* env vars...
```

After that there is nothing else, can't connect to mongo on `localhost 27017`, file `/opt/bitnami/mongodb/logs/mongodb.log` inside the container is empty. Please advice on how to use the bitnami image

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversations in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by suhdev** [comment]
For anyone running into an issue with bitnami/mongo not working on Mac M1 for local development, in your `values.yaml` add the following:
```bash
image:
  tag: 6.0.4-jammy
  repository: mongo
persistence:
  mountPath: /data/db
```
This forces the bitnami/mongo helm chart to use mongo's own docker image (which supports arm64).
