### ISSUE TITLE
[bitnami/consul] Add description for the env var CONSUL_BIND_ADDR

### ISSUE THREAD

**Issue by fsdrw08** [bitnami/containers#14525]
### Name and Version

bitnami/consul:1.14.1

### What is the problem this feature will solve?

The environment variable **CONSUL_BIND_ADDR** is used in [bitnami/consul/1/debian-11/rootfs/opt/bitnami/scripts/consul/run.sh](https://github.com/bitnami/containers/blob/main/bitnami/consul/1/debian-11/rootfs/opt/bitnami/scripts/consul/run.sh)

But it had not metion in readme [environment-variables](https://github.com/bitnami/containers/tree/main/bitnami/consul#environment-variables)

### What is the feature you are proposing to solve the problem?

The discription for the env var CONSUL_BIND_ADDR is missed in consul's readme document, this is an importent env var for consul, it should be add

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
