### ISSUE TITLE
ERROR: for bitnami_wordpress_1  a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lerlands** [bitnami/containers#1462]
### Name and Version

bitnami-bot 6.0.0-debian-11-r0 release

### What steps will reproduce the bug?

1. Downloaded https://github.com/bitnami/containers/blob/main/bitnami/wordpress/docker-compose.yml
2. Ran 'docker-compose up'

### What is the expected behavior?

(no errors)

### What do you see instead?

[wordpress.log.txt](https://github.com/bitnami/containers/files/9232906/wordpress.log.txt)

### Additional information

Started with the deprecated version at https://github.com/bitnami/bitnami-docker-wordpress . This shows the same error message.

**Comment by carrodher** [comment]
I am not able to reproduce the issue by following the instructions from https://github.com/bitnami/containers/tree/main/bitnami/wordpress#tldr

Please note this container is not ready for ARM processors, just in case you're trying it in a MAC M1

**Comment by lerlands** [comment]
lerlands@mint20:~/src/deezine/scratchpad/bitnami$ uname -a
Linux mint20 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
lerlands@mint20:~/src/deezine/scratchpad/bitnami$ 

[wordpress.log.2.txt](https://github.com/bitnami/containers/files/9233320/wordpress.log.2.txt)

**Comment by lerlands** [comment]
lerlands@mint20:~/src/deezine/scratchpad/bitnami$ uname -a
Linux mint20 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
127 lerlands@mint20:~/src/deezine/scratchpad/bitnami$ python3 --version
Python 3.8.10
lerlands@mint20:~/src/deezine/scratchpad/bitnami$ docker-compose --version
docker-compose version 1.25.0, build unknown
lerlands@mint20:~/src/deezine/scratchpad/bitnami$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
lerlands@mint20:~/src/deezine/scratchpad/bitnami$

**Comment by carrodher** [comment]
Unfortunately, we are not able to reproduce the issue by running 
```console
$ curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/wordpress/docker-compose.yml > docker-compose.yml
$ docker-compose up
```

It seems something related to the environment used in your use case

**Comment by lerlands** [comment]
Found it! ( https://github.com/docker/compose/issues/4972 )
String handling in remote buffers in python 3. Python converts the string to a utf-8 buffer of bytes. Fixed with:

pip3 uninstall docker
pip3 uninstall docker-compose

pip3 install docker==2.3.0
pip3 install docker-compose==1.14.0
