### ISSUE TITLE
[bitnami/discourse] Specific version for Postgres

### ISSUE THREAD

**Issue by kosssi** [bitnami/containers#14632]
### Name and Version

bitnami/discourse:2.8.11

### What is the problem this feature will solve?

`bitnami/discourse` have a dependency with a Postgres version.

Actually is v14.6 https://github.com/bitnami/containers/blob/c81cc5cfd6f0a8c4c843e876e40da85c728c8814/bitnami/discourse/2/debian-11/Dockerfile#L27

I install my discourse with Postgres v15.1, binary `pg_dump` is not compatible so automatic backups failed:

```
[2022-11-23 14:37:59] '*****' has started the backup!
[2022-11-23 14:37:59] Marking backup as running...
[2022-11-23 14:37:59] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-11-23-143759' exists...
[2022-11-23 14:37:59] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-11-23 14:37:59] Updating metadata...
[2022-11-23 14:38:00] Dumping the public schema of the database...
[2022-11-23 14:38:00] EXCEPTION: pg_dump failed
[2022-11-23 14:38:00] /opt/bitnami/discourse/lib/backup_restore/backuper.rb:152:in `dump_public_schema'
/opt/bitnami/discourse/lib/backup_restore/backuper.rb:36:in `run'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:9:in `backup'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:34:in `block in <main>'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `fork'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `<main>'
[2022-11-23 14:38:00] Deleting old backups...
[2022-11-23 14:38:00] pg_dump: error: server version: 15.1; pg_dump version: 14.6
[2022-11-23 14:38:00] Cleaning stuff up...
[2022-11-23 14:38:00] Removing '.tar' leftovers...
[2022-11-23 14:38:00] Marking backup as finished...
[2022-11-23 14:38:00] Refreshing disk stats...
[2022-11-23 14:38:00] Notifying '*****' of the end of the backup...
[2022-11-23 14:38:05] Finished!
```

### What is the feature you are proposing to solve the problem?

Maybe you could generate discourse version with multi Postgres version:
- 2.8.11-debian-11-r1-pg13
- 2.8.11-debian-11-r1-pg14
- 2.8.11-debian-11-r1-pg15

### What alternatives have you considered?

Update container with commands:

```
docker exec -it container_name bash
apt update
apt install curl
COMPONENT=postgresql-client-15.1.0-0-linux-${OS_ARCH}-debian-11
mkdir -p /tmp/bitnami/pkg/cache/ && cd /tmp/bitnami/pkg/cache/
curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O
curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O
sha256sum -c "${COMPONENT}.tar.gz.sha256" && \
tar -zxf "${COMPONENT}.tar.gz" -C /opt/bitnami --strip-components=2 --no-same-owner --wildcards '*/files' && \
rm -rf "${COMPONENT}".tar.gz{,.sha256}
```

**Comment by javsalgar** [comment]
Hi! Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by kosssi** [comment]
Thanks for the works, I create this issue to have a documentation.

**Comment by ByteInSpace** [comment]
We ran too in the same problem (see Issue https://github.com/bitnami/charts/issues/12592 down in text). It looks like it affectes multiple versions of Bitnami Discourse Kubernetes images: pg_client and delivered PostgreSQL do not match, rendering backup via Discourse virtually impossible .

**Comment by carrodher** [comment]
We just created an internal task to fix the issue and release a new [bitnami/discourse container image](https://github.com/bitnami/containers/tree/main/bitnami/discourse) bundling postgresql-client 15.x.x in order to match with the PostgreSQL version used by the bitnami/discourse Helm chart.

**Comment by carrodher** [comment]
Hi, we just released a new bitnami/discourse container image bundling postgresql-client 15.1.0, see https://github.com/bitnami/containers/pull/15327. This image was released as `bitnami/discourse:2.8.11-debian-11-r4`.

In the same way, at https://github.com/bitnami/charts/pull/13740, a new version of the Helm chart (`9.0.3`) was released including the new container image:
```yaml
image:
  registry: docker.io
  repository: bitnami/discourse
  tag: 2.8.11-debian-11-r4
```

Please let us know if that solve your issue.

**Comment by kosssi** [comment]
Thanks a lot for me, but now this image will break autosave for people who have postgres 14 ;)

It's not possible to create multi images to variante postgres ?

**Comment by carrodher** [comment]
Unfortunately is not something supported at this moment. The bitnami/discourse container image is built bundling a specific version for postgresql-client. In the same way, the Helm chart uses a specific version of the bitnami/postgresql subchart, which, in turn, it is pinned to a specific PostgreSQL version.

**Comment by ByteInSpace** [comment]
There should be no problem using pg_dump 15 with Postgres 14. This is our configuration, too, and it works with chart 9.0.4 without issues.
