### ISSUE TITLE
[bitnami/dokuwiki] New version of dokuwiki released (2022-07-31)

### ISSUE THREAD

**Issue by xberna16** [bitnami/containers#1470]
### Name and Version

bitnami/dokuwiki

### What is the problem this feature will solve?

Release 2022-07-31 "Igor"
Fix various errors in PHP8 support
Drop support for PHP versions earlier than 7.2
SVG-based smileys replace GIF versions
:!: may require template update [3344](https://github.com/splitbrain/dokuwiki/pull/3344)
:!: plugins directly embedding SVG may need CSS adjustments [3690](http://bugs.dokuwiki.org/index.php?do=details&task_id=3690)
Allow “revert” action for logged in users only
Various translation updates
Add a class .logo to the h1 title to let administrators remove the h1 around the logo [3408](https://github.com/splitbrain/dokuwiki/pull/3408)
Use [Slika library](https://github.com/splitbrain/slika) for image resizing and cropping, with:
auto rotation based on EXIF tags
support for WEBP
Refactored logging mechanism [3230](https://github.com/splitbrain/dokuwiki/pull/3230), [3203](https://github.com/splitbrain/dokuwiki/pull/3203) and [logviewer](https://www.dokuwiki.org/plugin:logviewer)
Refactored media manager [3372](https://github.com/splitbrain/dokuwiki/pull/3372) and lazy loading of images
Support for SVG images
New form events used. :!: Plugins should implement them, because the old form events are not triggered anymore
Some smaller security fixes

https://www.dokuwiki.org/changes

### What is the feature you are proposing to solve the problem?

Update the image with newer version of dokuwiki.

**Comment by carrodher** [comment]
Thanks for letting us know. This version was already detected by our system but since it is major a version it will require manual changes on our side and it is now being evaluated by our engineering team. We will update this GH issue once released.

**Comment by dgomezleon** [comment]
Just a quick note to confirm the release of this new version.
