### ISSUE TITLE
[bitnami/postgresql] provide wal2json

### ISSUE THREAD

**Issue by betaboon** [bitnami/containers#14919]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Including [wal2json](https://github.com/eulerto/wal2json) in the bitnami-postgresql images will remove the need from users to maintain their own bitnami-based container images for usecases where it is required.

### What is the feature you are proposing to solve the problem?

[wal2json](https://github.com/eulerto/wal2json) is a postgresql-output-plugin that is widely being used for real-time data-updates between postgresql and services.

please include it by default in the bitnami-container-images.

`wal2json` is included out-of-the-box on [azure](https://learn.microsoft.com/en-us/azure/postgresql/single-server/concepts-logical), [aws rds](https://aws.amazon.com/blogs/database/stream-changes-from-amazon-rds-for-postgresql-using-amazon-kinesis-data-streams-and-aws-lambda/) and [google cloud](https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication) for several years.

### What alternatives have you considered?

We're currently building a custom container-image that is based on the bitnami-image.
but this is maintenance hassle.

this is the `Dockerfile` that we are currently using:

```Dockerfile
ARG POSTGRESQL_TAG=15.1.0-debian-11-r3
FROM docker.io/bitnami/postgresql:${POSTGRESQL_TAG} as builder

ARG WAL2JSON_TAG=wal2json_2_5

USER root
RUN apt-get update && apt-get install -y gcc git make && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/eulerto/wal2json.git --branch ${WAL2JSON_TAG}
RUN cd wal2json && USE_PGXS=1 make && USE_PGXS=1 make install

FROM docker.io/bitnami/postgresql:${POSTGRESQL_TAG}
COPY --from=builder /opt/bitnami/postgresql/lib/wal2json.so /opt/bitnami/postgresql/lib/
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. In this sense, we are conservative in the number of plugins we add to the image, as it has several implications:

  - The size of the container may potentially increase
  - The attack surface also increases, as the plugin may have CVEs 

Therefore, we would like first to understand whether this is a feature/plugin that is widely used by the community. I will leave this ticket open to see if more users request it.

**Comment by betaboon** [comment]
thanks for the reply.
just for reference here's an old issue also referring to wal2json usage together with the bitnami postgres-image

https://github.com/bitnami/bitnami-docker-postgresql/issues/310

**Comment by betaboon** [comment]
still very much interested in this.

**Comment by jennydaman** [comment]
@javsalgar chiming in to express interest in this issue.

wal2json facilities integration of [Meilisearch with PostgreSQL](https://www.meilisearch.com/docs/learn/cookbooks/meilisync_postgresql).

**Comment by betaboon** [comment]
just fyi: 

I'm maintaining this for quite a while: https://hub.docker.com/r/betaboon/bitnami-postgresql-wal2json

these images are automatically built and track the upstream tags.

the code that does this is here: https://github.com/betaboon/bitnami-postgresql-wal2json

**Comment by jennydaman** [comment]
@betaboon thank you! I saw your repo yesterday and i really appreciate your effort to go all the way with that GitHub actions version matrix

**Comment by betaboon** [comment]
@javsalgar just an update:
- we've been using the images from my repo for quite a while i production now
- the issue has 11 thumbs-up
- the post sharing my repo has 2 responses
- the images on docker-hub have 10k+ pulls
- aws, azure, gcp all support wal2json out-of-the-box

maybe you could reconsider?

**Comment by javsalgar** [comment]
Thank you for bringing this to our attention. Let me check with the team.

**Comment by betaboon** [comment]
any update here?

**Comment by javsalgar** [comment]
I'm currently working on it, as soon as I have news, I will update the ticket

**Comment by javsalgar** [comment]
Just a note to let you know that these revisions of postgresql and postgresql-repmgr contain wal2json

https://github.com/bitnami/charts/commit/3c161f7033eff31b2f3d98879bcac07c7070c0d6
https://github.com/bitnami/charts/commit/0dd0944cfdf3470777cf47f4e57c5d944cf488fd

Can you confirm so we can close the issue?

**Comment by javsalgar** [comment]
https://hub.docker.com/layers/bitnami/postgresql/12.20.0-debian-12-r10/images/sha256-d64bb747e77ac0896890107da2559ba90028658b1a492d68fb61f9c7dd4e2a27?context=explore

https://hub.docker.com/layers/bitnami/postgresql/13.16.0-debian-12-r9/images/sha256-f9b29615c6684d7809753703ab256ecbc8ecac8d3130ea56ab6a78ecfe50f275?context=explore

https://hub.docker.com/layers/bitnami/postgresql/14.13.0-debian-12-r9/images/sha256-b4df253df957bc42da32d4ac6623a61f5da1418f95622656cfb3d45bb0211c40?context=explore

https://hub.docker.com/layers/bitnami/postgresql/15.8.0-debian-12-r9/images/sha256-e900e469a6530ed3f6ab931851650470bcb05a1a3fa491b4310f998310ff86cf?context=explore

https://hub.docker.com/layers/bitnami/postgresql/16.4.0-debian-12-r8/images/sha256-fa41bcc906b8507bc18ee84cebf08a98f853e3a6bb3c92f26e4bea331ae5b788?context=explore

**Comment by betaboon** [comment]
seems to be working as expected. thanks a bunch :)
