### ISSUE TITLE
[bitnami/magento] Catalog Search index process error during indexation process

### ISSUE THREAD

**Issue by mathos77** [bitnami/containers#14927]
### Name and Version

bitnami/magento

### What steps will reproduce the bug?

When I run the scripts in trace mode, I see the problem with **Reindexing** step fails at:
`gosu daemon php /opt/bitnami/magento/bin/magento indexer:reindex`

Executing this manually in a running container reveals:
```bash
root@25e0b6c3606e:/# php /opt/bitnami/magento/bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search index process error during indexation process:
{"error":"no handler found for uri [/magento2_product_1_v2/document/_mapping?include_type_name=true] and method [PUT]"}
```

### What is the expected behavior?

Starting of container goes as planned

### What do you see instead?

Re-Indexing returns -1 exit code, and container stops

### Additional information

I tried this with the latest, and also with 2.4.5.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
