### ISSUE TITLE
[bitnami/spark] Getting error "java.io.IOException: No such file or directory" when running Python Spark jobs.

### ISSUE THREAD

**Issue by pekkalaaksonen** [bitnami/containers#14943]
### Name and Version

bitnami/spark:3.3

### What steps will reproduce the bug?

Laptop: Apple M1 Pro
OS version: 13.0.1 (Ventura)
Docker version 20.10.20, build 9fdeb9c

I started testing Spark on Docker with the standard Bitnami [docker-compose file](https://raw.githubusercontent.com/bitnami/containers/main/bitnami/spark/docker-compose.yml). I made no alterations to the file. Just downloaded it and ran: `docker compose up`.

Next I tried running one of the example Python files:

`docker exec test-spark-1 spark-submit /opt/bitnami/spark/examples/src/main/python/pi.py 5 --deploy-mode cluster --master spark://spark:7077`

Job executed and printed out the result:
`22/11/25 21:04:59 INFO DAGScheduler: Job 0 finished: reduce at /opt/bitnami/spark/examples/src/main/python/pi.py:42, took 13.083411 s
Pi is roughly 3.145000`

### What do you see instead?

However, after that I get the following error:
```
> 22/11/25 21:05:00 WARN AbstractConnector:
java.io.IOException: No such file or directory
	at sun.nio.ch.NativeThread.signal(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:291)
        .
        .
        .
```
I get the same error when running my own Python apps on the cluster. Is there something I can do to fix this?

**Comment by carrodher** [comment]
Hi, please note that M1 processors have an ARM architecture which is not supported at this moment by the Bitnami containers. We have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversations in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
