### ISSUE TITLE
[bitnami/pgbouncer] pgbouncer requires password set, but passwords are not strictly required

### ISSUE THREAD

**Issue by mbrancato** [bitnami/containers#15344]
### Name and Version

bitnami/pgbouncer 1.17.0

### What steps will reproduce the bug?

1. Run the bitnami/pgbouncer container without setting a `POSTGRESQL_PASSWORD` value

### What is the expected behavior?

pgbouncer should startup.

### What do you see instead?

```
pgbouncer 20:13:59.28 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 20:13:59.29 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 20:13:59.29 ERROR ==> POSTGRESQL_PASSWORD must be set
```

### Additional information

You might be thinking "Why would anyone want to use no password? It's not secure". Well that is normally true, but its also not required.

Anyway, Google Cloud SQL proxy will use instance identity information to inject authentication when the password is left blank. And I'm trying to use that here.
https://cloud.google.com/sql/docs/postgres/iam-logins

**Comment by Mauraza** [comment]
Hi @mbrancato 

[Here](https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/docker-compose.yml) you can find an example without a password using the environment `PGBOUNCER_AUTH_TYPE=trust`.
For more information please check the [README.md ](https://github.com/bitnami/containers/tree/main/bitnami/pgbouncer#authentication)of the container and the official documentation.

**Comment by mbrancato** [comment]
Thanks. It does seem like nothing in the README indicates this as authentication is client auth, and the POSTGRESQL_PASSWORD is backend auth. But this solves my issue, thanks.
