### ISSUE TITLE
About bitnami-Docker-kafka server.properties

### ISSUE THREAD

**Issue by huangmq-code** [bitnami/containers#1541]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

I hope we can use the Docker env settings to set the `server.properties` because we need to set the setting in the config file in Kafka's server.properties:
```
message.max.bytes=5242880
replica.fetch.max.bytes=6291456
```

**Comment by carrodher** [comment]
You can customize this image by using environment variables (see [README](https://github.com/bitnami/containers/tree/main/bitnami/kafka#configuration)) or by passing a whole config file (see [README](https://github.com/bitnami/containers/tree/main/bitnami/kafka#full-configuration))
