### ISSUE TITLE
[bitnami/ruby]  jemalloc

### ISSUE THREAD

**Issue by stevenbarragan** [bitnami/containers#15868]
### Name and Version

bitname/ruby

### What is the problem this feature will solve?

It will provide an optimized version of ruby to run on servers

### What is the feature you are proposing to solve the problem?

Compile ruby with jemalloc and provide an image with it

### What alternatives have you considered?

I've tried installing libjemalloc2 and setting it up with the LD_PRELOAD environment variable
Still I think it'd better to compile ruby with it directly.

**Comment by javsalgar** [comment]
Hi,

Could you add more details on the importance of this package that justifies adding it to the ruby image? Please note that adding new packages increases not only the size but the vulnerability surface of the image.
