### ISSUE TITLE
redis-cluster docker-compose does not work as per docs

### ISSUE THREAD

**Issue by mmhealey1** [bitnami/containers#1589]
### Name and Version

bitnami/redis-cluster:7.0

### What steps will reproduce the bug?

1. Environment - docker on macos (Docker version 20.10.17-rd, build c2e4e01)
2. config - default
3. Run 
```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-redis-cluster/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

### What is the expected behavior?

cluster should initialise

### What do you see instead?

>   Executing task: docker logs --tail 1000 -f 0a0c3e180e1a538402b0979f2a0ffe873318991ced4f9514383efa1a2a4f6904 
> 
> ,;: missing operand after ' '
> Two strings must be given when translating.
> Try ',; --help' for more information.
> 1:C 02 Aug 2022 15:04:32.427 # Fatal error, can't open config file '/6379': No such file or directory

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  Are you using an M1 Mac ?

**Comment by mmhealey1** [comment]
Turns out this is related to rancher-desktop's latest release. Not an issue
with bitnami containers itself.
