### ISSUE TITLE
[bitnami/postgresql-repmgr] Postgresql manager might logs password in clear when unable to ping itself

### ISSUE THREAD

**Issue by mulder999** [bitnami/containers#15904]
### Name and Version

bitnami/postgresql-repmgr:14

### What steps will reproduce the bug?

Enable REPMGR but start only one of the node.
Exhaust the connection pool so that PQPing would fail.

### What do you see instead?

Then the following might be logged which includes all the connection information in clear:

```logs
[2022-12-04 14:03:21] [WARNING] unable to ping "user=<USER> password=<PASSWORD> host=<HOST> dbname=<DB> port=5432 connect_timeout=5"
[2022-12-04 14:03:21] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2022-12-04 14:03:21] [WARNING] connection to node "<HOST>" (ID: 14) lost
```

**Comment by javsalgar** [comment]
Hi,

These logs are not from the Bitnami logic, but from the application itself. I think this should be reported to the upstream `repmgr` developers. 

https://groups.google.com/group/repmgr

**Comment by mulder999** [comment]
Hi @javsalgar, thanks for feedback, reported issue on their [github](https://github.com/EnterpriseDB/repmgr/issues/780). Meanwhile log level for repmgr should be raised to `ERROR` instead of `NOTICE`.

**Comment by mulder999** [comment]
Have publish [PR](https://github.com/EnterpriseDB/repmgr/pull/781) on upstream `repmgr` project.

Until it gets eventually accepted, the work around is to set environment variable to `REPMGR_LOG_LEVEL=ERROR`. Should we change the docker project default if upstream team is delaying too much the merge ?

**Comment by javsalgar** [comment]
Hi!

Thank you so much! Yes, I think we should change the log level if the merge gets delayed.

**Comment by mulder999** [comment]
No stale
