### ISSUE TITLE
[bitnami/postgresql-repmgr] How does postgres repmagr implement witness service? thank you

### ISSUE THREAD

**Issue by zhbog521** [bitnami/containers#15976]
### Name and Version

bitnami/postgresql-repmgr

### What steps will reproduce the bug?

How does postgres repmagr implement witness service? thank you

### What is the expected behavior?

How does postgres repmagr implement witness service? thank you

### What do you see instead?

How does postgres repmagr implement witness service? thank you

### Additional information

How does postgres repmagr implement witness service? thank you

**Comment by javsalgar** [comment]
Hi,

Looking at the code, it seems that the witness mode is not implemented in the helm chart or container. Could you add more details on how this mode works or how it is configured?
