### ISSUE TITLE
How does postgres repmagr implement witness service? thank you

### ISSUE THREAD

**Issue by zhbog521** [bitnami/containers#15975]
### Name and Version

bitnami/postgresql-repmgr

### What is the problem this feature will solve?

How does postgres repmagr implement witness service? thank you

### What is the feature you are proposing to solve the problem?

How does postgres repmagr implement witness service? thank you

**Comment by javsalgar** [comment]
Duplicate of https://github.com/bitnami/containers/issues/15976
