### ISSUE TITLE
[bitnai/kafka] Kafka Configuration in docker and docker-compose how to make changes in Kafka config path of docker Bitnami image

### ISSUE THREAD

**Issue by joshiraavi** [bitnami/containers#16216]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://github.com/bitnami/containers/tree/main/bitnami/kafka

### bndiagnostic was not useful. Could you please tell us why?

I didn't find any relevant trouble shoot refrences 

### Describe your issue as much as you can

Were using bitnami Kafka and zookeeper docker image and deployed it has the docker-compose file of bitnami, here some of the features are affecting us due to missing some parameters in Kafka config, we need to add some parameters in the Kafka config of docker could you please suggest from where is the exact location of Kafka config path in the docker container, as we have made some changes in server.properties as volume mount but the changes are not reflecting, Could you help and provide more information on this?

**Comment by javsalgar** [comment]
Hi!

Did you check this section in the README.md file? These env vars should be helpful

> Additionally, any environment variable beginning with KAFKA_CFG_ will be mapped to its corresponding Apache Kafka key. For example, use KAFKA_CFG_BACKGROUND_THREADS in order to set background.threads or KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE in order to configure auto.create.topics.enable.

**Comment by joshiraavi** [comment]
Hi @javsalgar 
 We need the exact location of producer configurations to take effect and add these params "enable.idempotence" to be configured and ways to validate whether it is applied.

The issue is the first message is replacing the second message it is creating duplicate for the first message we need a solution for this how to print messages without duplication.  what are the exact params where to be added to fix this issue

**Comment by OneCricketeer** [comment]
Producers shouldn't run in the brokers. But Kafka config files are stored under /opt/bitnami

**Comment by joshiraavi** [comment]
Hi @OneCricketeer 
we have mounted the Kafka config files using docker-compose, but the params which were added additionally that were not reflecting can you suggest a better way to overcome this issue the first message is replacing the second message it is creating a duplicate for the first message we need a solution for this how to print messages without duplication. what are the exact params where to be added to fix this issue

**Comment by OneCricketeer** [comment]
Like I said, producers shouldn't run in the Kafka container. If you're getting duplicates, that's not anything that can be solved from config files on broker. But if you want the location, it's under /opt

Also, env vars for the broker starting with `KAFKA_CFG` will always override whatever you mount, I believe

**Comment by joshiraavi** [comment]
Hi @OneCricketeer in our case producers and Kafka are running separate containers and still facing this duplication issue can you suggest any other way to fix this

**Comment by OneCricketeer** [comment]
Without seeing your code, that cannot be answered, plus Kafka does nothing to prevent duplicates from being produced; if you are sending the exact same record twice, that's a unique offset on each record, not a duplicate, and the latter never override those before. 

You mentioned you've enabled idempotent producer, but are you using a transactional one? Did you [configure the consumer isolation to read_comitted](https://stackoverflow.com/q/56047968)?
