### ISSUE TITLE
[bitnami/moodle] Support Use of Moodle's Aurora MySQL Database Driver

### ISSUE THREAD

**Issue by cgrycki** [bitnami/containers#1636]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

The Moodle container is unable to install Moodle when using a MySQL compatible Aurora database. The startup scripts for the Moodle container require that the value of the environment variable "MOODLE_DATABASE_TYPE" is one of the following:
- mysqli 
- mariadb 
- pgsql
https://github.com/bitnami/containers/blob/4fee4a6c96a3c162beb63323ef10f6a5697aa4f0/bitnami/moodle/4/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L90

Moodle added support for MySQL compatible Aurora in version 3.9. Attempting to use the mysqli database driver with an Aurora database results in the error "Index column size too large. The maximum column size is 767 bytes." during installation. The "auroramysql" driver solves this by extending the mysqli driver and disabling compressed row format.
https://tracker.moodle.org/browse/MDL-58931
https://github.com/moodle/moodle/compare/master...mackensen:MDL-58931-master

### What is the feature you are proposing to solve the problem?

Support "auroramysql" as one of the permitted values for MOODLE_DATABASE_TYPE. It can very likely reuse the same logic as the "mysqli" type in the libmoodle.sh script.

### What alternatives have you considered?

Provision a new MySQL or MariaDB database on RDS.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
