### ISSUE TITLE
[bitnami/dotnet-sdk] default templates are missing in dotnet-sdk

### ISSUE THREAD

**Issue by zstadler** [bitnami/containers#17158]
### Name and Version

bitnami/dotnet-sdk:7.0.101-debian-11-r0

### What steps will reproduce the bug?

1. Run

```
docker run --rm bitnami/dotnet-sdk:latest dotnet new console --name Send
```
2. Receive this error

```
No templates or subcommands found matching: 'console'.

To list installed templates similar to 'console', run:
   dotnet new list console
To search for the templates on NuGet.org, run:
   dotnet new search console
```

### What is the expected behavior?

The expected behavior of `dotnet new console --name Send` is that a new `Send` project will be created using the `console` template.

Microsoft's [.NET default templates for dotnet new](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates) says:

> When you install the [.NET SDK](https://dotnet.microsoft.com/download), you receive over a dozen built-in templates for creating projects and files, including console apps

Unfortunately, this does not seem to be the case for the `bitnami/dotnet-sdk` container.

### What do you see instead?

I got stuck.

1. My attempts to search and install the missing template did not succeed.

`docker run --rm bitnami/dotnet-sdk:latest dotnet new search console --author Microsoft --language C#`
produced one inappropriate result:

```
Searching for the templates...
Matches from template source: NuGet.org
These templates matched your input: 'console', --author='Microsoft', --language='C#'

Template Name            Short Name   Author     Language  Package                                      Downloads
-----------------------  -----------  ---------  --------  -------------------------------------------  ---------
WebAssembly Console App  wasmconsole  Microsoft  C#        Microsoft.NET.Runtime.WebAssembly.Templates        13k
```

2. My attempt to use ` bitnami/dotnet-sdk:6` did not succeed either
`docker run --rm bitnami/dotnet-sdk:6 dotnet new console --name Send`
produced a similar error:

```
Welcome to the Bitnami dotnet-sdk container
Subscribe to project updates by watching https://github.com/bitnami/containers
Submit issues and feature requests at https://github.com/bitnami/containers/issues


Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.404

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
No templates found matching: 'console'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new console --search
```

**Comment by Mauraza** [comment]
Hi @zstadler,

As it appears in the logs, the command has changed. 
Could you try this `docker run --rm bitnami/dotnet-sdk:latest dotnet new search Send`?
The other command is: `docker run --rm bitnami/dotnet-sdk:latest dotnet new search --author Microsoft --language C#`

**Comment by zstadler** [comment]
Hi @Mauraza,

It seems like the **What do you see instead?** section above created some lack of clarity. I'm sorry about that.

The core of the reported issue is that
```
docker run --rm bitnami/dotnet-sdk:latest dotnet new console --name XXXX
```
fails in the container. You may replace `XXXX` with any other project name.

You wrote:
> Could you try this docker run --rm bitnami/dotnet-sdk:latest dotnet new search Send?
> The other command is: docker run --rm bitnami/dotnet-sdk:latest dotnet new search --author Microsoft --language C#

The commands proposed above are **searching** for a **Send** template or **any Microsoft C#** template, while I would like to **create a new project** using the **console** template.

**Comment by Mauraza** [comment]
Hi @zstadler,

As I said the command is changed. You can run `docker run --rm bitnami/dotnet-sdk:latest dotnet new -h` to access the help of the command.

But I think your want something like this:
```console
docker run --rm bitnami/dotnet-sdk:latest bash -c "dotnet new install Microsoft.NET.Runtime.WebAssembly.Templates && dotnet new create wasmconsole"
```

**Comment by zstadler** [comment]
Hi @Mauraza

`docker run --rm bitnami/dotnet-sdk:latest dotnet new -h` says:

```
Description:
  Template Instantiation Commands for .NET CLI.

Usage:
  dotnet new [<template-short-name> [<template-args>...]] [options]
  dotnet new [command] [options]

Arguments:
  <template-short-name>  A short name of the template to create.
  <template-args>        Template specific options to use.

Options:
  -o, --output <output>    Location to place the generated output.
  -n, --name <name>        The name for the output being created. If no name is specified, the name of the output directory is used.
  --dry-run                Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force                  Forces content to be generated even if it would change existing files.
  --no-update-check        Disables checking for the template package updates when instantiating a template.
  --project <project>      The project that should be used for context evaluation.
  -v, --verbosity <LEVEL>  Sets the verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], and diag[nostic]. [default: normal]
  -d, --diagnostics        Enables diagnostic output.
  -?, -h, --help           Show command line help.
```

`dotnet new console --name XXXX` is  using the new syntax:

- `<template-short-name>` is `console` 
- `--name <name>` is `--name XXX`

I am not interested in instantiating the `wasmconsole` template`.

I need the `console` template which is readily available in the Windows, non-docker version, of the node-sdk:

```
f:\Temp\b>dotnet new console --name XXXX
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring f:\Temp\b\XXXX\XXXX.csproj:
  Determining projects to restore...
  Restored f:\Temp\b\XXXX\XXXX.csproj (in 72 ms).
Restore succeeded.



f:\Temp\b>dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22623
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\
```

**Comment by Mauraza** [comment]
Hi @zstadler ,

In windows, non-docker version, did you can find the console with something similar to `dotnet new search console --author Microsoft `?

**Comment by zstadler** [comment]
No. `console` is not found by `dotnet new search console --author`. It is expected because the `console` template is built-in the distribution and need not be searched or installed.

Here is a demonstration that the `wasmconsole` template is different than the desired `console` template. We can see that `dotnet new console --name XXXX` succeeds in using the `console` template while the `wasmconsole` is not installed. 

```
F:\Temp>dotnet new console --name XXXX
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring F:\Temp\XXXX\XXXX.csproj:
  Determining projects to restore...
  Restored F:\Temp\XXXX\XXXX.csproj (in 70 ms).
Restore succeeded.



F:\Temp>dotnet new search console --author Microsoft
Searching for the templates...
Matches from template source: NuGet.org
These templates matched your input: 'console', --author='Microsoft'

Template Name        Short Name   Author     Language  Package                                      Downloads
-------------------  -----------  ---------  --------  -------------------------------------------  ---------
WebAssembly Cons...  wasmconsole  Microsoft  [C#]      Microsoft.NET.Runtime.WebAssembly.Templates        13k


To use the template, run the following command to install the package:
   dotnet new install [<package>...]
Example:
   dotnet new install Microsoft.NET.Runtime.WebAssembly.Templates
```

**Comment by Mauraza** [comment]
Hi @zstadler,

It seems that the 'console' is not available in a container. 
I tried to install dotnet in a container and 'console' still not appears but in a local environment appears. So I think this issue is more related to dotnet that the bitnami/dotnet.

**Comment by Mauraza** [comment]
Hi @zstadler,

I going to create an internal task to continue investigating the issue.
We will come back as soon as we have news.

**Comment by fevisera** [comment]
Hi @zstadler,

A new `dotnet-sdk` container image has been released and now you can run `dotnet new console --name Send` in both versions. Make sure to pull the container image before running the command. You can do it as:

```
$ docker run --pull=always --rm bitnami/dotnet-sdk:latest dotnet new console --name Send
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /app/Send/Send.csproj:
  Determining projects to restore...
  Restored /app/Send/Send.csproj (in 150 ms).
Restore succeeded.
```

```
$ docker run --pull=always --rm bitnami/dotnet-sdk:6 dotnet new console --name Send
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /app/Send/Send.csproj...
  Determining projects to restore...
  Restored /app/Send/Send.csproj (in 100 ms).
Restore succeeded.
``` 

Please, confirm to us the error is solved for you before we close this issue.
Thank you.
