### ISSUE TITLE
How to disable SSL/HTTPS?

### ISSUE THREAD

**Issue by AlejandroAkbal** [bitnami/containers#17170]
### Name and Version

bitnami/wordpress & bitnami/nginx

### What steps will reproduce the bug?

1. I'm running Dokku on an Ubuntu server
2. Default config with only Database environment variables set
3. Run container
4. See SSL/HTTPS certificate from Lets Encrypt used

### What is the expected behavior?

No HTTPS/SSL certificate used by this container, just a PHP runtime on HTTP

### What do you see instead?

A custom certificate signed by Lets Encrypt

### Additional information

I'm running Dokku on my Ubuntu server and I don't need the lets encrypt certificate, I'm already providing my own certificate with Dokku's own reverse Nginx proxy

And I don't want to supply it internally, I configure everything on Dokku, not on a per-app basis

**Comment by carrodher** [comment]
Can you take a look at the [customization section in the README](https://github.com/bitnami/containers/tree/main/bitnami/wordpress#customize-this-image)? There is a section for configuring SSL

**Comment by AlejandroAkbal** [comment]
I know there's a way to configure SSL, but what I want to do is entirely disable it. It's on by default.

Alejandro Akbal
akbal.dev <https://akbal.dev>



Dec 19, 2022, 11:14 by ***@***.***:

**Comment by migruiz4** [comment]
Hi @AlejandroAkbal,

The `bitnami/nginx` won't be configured with SSL/HTTPS unless the environment variable `NGINX_HTTPS_PORT_NUMBER` is provided, which is not by default.

Same case for `bitnami/wordpress` and other images using Apache, HTTPS port won't be configured unless the env variable `APACHE_HTTPS_PORT_NUMBER` is configured, which is not set by default.

I think your issue may be related to Dokku and not the container images used. By reading Dokku's documentation, appears that it deploys a reverse-proxy in from of the container applications, which is configured with HTTPS and Let's Encrypt.

I would recommend asking this question in Dokku support channels and checking Dokku documentation, maybe the following links help you:
- https://dokku.com/docs/configuration/ssl/
- https://blog.semicolonsoftware.de/securing-dokku-with-lets-encrypt-tls-certificates/

**Comment by AlejandroAkbal** [comment]
You are right, sorry, I had a DNS/SSL issue with Dokku
