### ISSUE TITLE
JRExpressionEvalException / Java 8 is incompatible with jasperreports v8.1.0

### ISSUE THREAD

**Issue by a-skorina** [bitnami/containers#17198]
### Name and Version

bitnami/jasperreports:8.1.0

### What steps will reproduce the bug?

Run a report that uses, for example, the following function: 
`net.sf.jasperreports.functions.standard.DateTimeFunctions#DATEFORMAT(Date, String)`

The exceptions occurs due to java incompatibility. 

`jasperreports-functions` requires minimum Java 9

### What is the expected behavior?

Report is generated

### What do you see instead?

An exception:

```
Caused by: net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: DATEFORMAT($P{StartTimeThisPeriod}, $F{date_format} + " " + $F{time_format})
```

### Additional information

> jasperreports-functions 6.19.1 and 6.20.0 are not (fully) compatible with Java 8 as a method introduced in Java 9 is used by certain functions.

https://community.jaspersoft.com/jasperreports-server/issues/14426#comment-879436

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
