### ISSUE TITLE
Upgrade Jasperreports to 8.1.1

### ISSUE THREAD

**Issue by a-skorina** [bitnami/containers#17196]
### Name and Version

bitnami/jasperreports

### What is the problem this feature will solve?

Fixing security vulnerabilities

> JasperReports Server 8.1.1 is a maintenance release for the mainstream release that addresses security
vulnerabilities. All installations of mainstream release 8.1.0 should upgrade to 8.1.1 as soon as possible.

https://docs.tibco.com/pub/js-jrs/8.1.1/TIB_js-jrs_8.1.1_relnotes.pdf?id=1

### What is the feature you are proposing to solve the problem?

Fix Dockerfile

**Comment by carrodher** [comment]
Thanks for the suggestion, we are actively monitoring the JasperReports release page at https://github.com/TIBCOSoftware/jasperreports-server-ce/releases; when the new version appears in that page, our automated track & release system should cut a new release of the bitnami/jasperreports container
