### ISSUE TITLE
Compatibility to gitlab/gitlab-runner

### ISSUE THREAD

**Issue by mahoromax** [bitnami/containers#17202]
### Name and Version

bitnami/gitlab-runner:15.6.1

### What is the problem this feature will solve?

Coming from the original image provided by GitLab, using a docker volume for the config file the switch to the bitnami docker is not plug'n'play.

After swapping the docker images, (I used the same run arguments as before, except for the image name of course) I noticed errors like
` ERROR: Failed to load config stat /.gitlab-runner/config.toml: no such file or directory  builds=0` in the docker log of the bitnami docker.
The original runner reads the config from `/etc/gitlab-runner/config.toml`. 

### What is the feature you are proposing to solve the problem?

Set up the bitnami image to be compatible to the default paths of gitlab image.

### What alternatives have you considered?

I tried to set a symlink, but ran into permission issues (gitlab-runner was running with a uid 1001 that I could not find). At this point I swapped back to gitlab image, which was easier...

**Comment by carrodher** [comment]
Thanks for reporting this issue, unfortunately supporting plug-and-play migrations from the upstream container to this one is not something on our roadmap in the short term. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
