### ISSUE TITLE
[bitnami/suitecrm] Generating an API access_token throws an error

### ISSUE THREAD

**Issue by ckeeney** [bitnami/containers#17280]
### Name and Version

bitnami/suitecrm:8

### What steps will reproduce the bug?

Use the API to request a new access token via a POST request to `/Api/access_token`.

### What is the expected behavior?

A new token should be generated.

### What do you see instead?

```json
{
    "error": "unknown_error",
    "message": "It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line"
}
```

### Additional information

There is discussion of this issue on the SuiteCRM community forums [here](https://community.suitecrm.com/t/api-and-docker-error-it-was-not-possible-to-parse-your-key/84638).

This seems related to the bump to PHP version 8.

Possibly Related: 
- https://github.com/lcobucci/jwt/issues/310
- https://stackoverflow.com/questions/67733476/when-i-login-then-error-will-be-ocuurred-it-was-not-possible-to-parse-your-key
- https://stackoverflow.com/questions/73211594/lombucci-jwt-it-was-not-possible-to-parse-your-key-reason-error0909006cpem-r

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/suitecrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by R0Wi** [comment]
For me this seems to be related to SuiteCRM 8.X in combination with PHP 8.0. I can reproduce the same behaviour in other Docker containers where I manually installed PHP 8.0. See also https://github.com/salesagility/SuiteCRM-Core/issues/185#issuecomment-1364708097
