### ISSUE TITLE
I can't change the username and password for airflow for some reason

### ISSUE THREAD

**Issue by AdewuyiOyawoye** [bitnami/containers#17566]
### Name and Version

bitnami airflow release 2.4.2

### What steps will reproduce the bug?

I entered the environment variables below to airflow
```yaml
      - AIRFLOW_PASSWORD=[MyNewPsssword]
      - AIRFLOW_USERNAME=[MyNewUserName]
      - AIRFLOW_EMAIL=[MyEmail]
```
### What is the expected behavior?

This should change the password from the default

### What do you see instead?

Credentials not updated, it still uses the defaults "User"  and password "bitnami". What am I missing?

**Comment by carrodher** [comment]
Are you persisting the data in a volume and reusing it? Please note the creds from a first installation can be stored in a volume, if you reuse the same volume in a second installation there will be a mismatch between the values set this second time as environment variables and the ones used during the first deployment and stored in the volume.

Could you try again without reusing the volume?

**Comment by AdewuyiOyawoye** [comment]
the only volumes I've got are the dags, redis and postgres. Will this affect airflow credentials?

**Comment by corico44** [comment]
To make sure, could you do a total cleaning of the volumes and launch it again @AdewuyiOyawoye?

**Comment by AdewuyiOyawoye** [comment]
> To make sure, could you do a total cleaning of the volumes and launch it again @AdewuyiOyawoye?

Thanks this did the trick!
