### ISSUE TITLE
[bitnami/schema-registry] broker ssl connection can`t be used

### ISSUE THREAD

**Issue by b3rnh8rd** [bitnami/containers#17582]
### Name and Version

bitnami/schema-registry:7.3.1

### What steps will reproduce the bug?

Similar to [Keystore can`t be used for HTTPS Listener](https://github.com/bitnami/containers/issues/9819), the broker connection cannot be configured via SSL, because of a missing ENV mapping.

### What is the expected behavior?

schema-registry can be used with SSL secured kafka-broker

### What do you see instead?

Due to unmapped parameters, the keystore cannot be used, as only SCHEMA_REGISTRY_KAFKA_KEYSTORE_PASSWORD can be set, but not SCHEMA_REGISTRY_KAFKA_KEY_PASSWORD.

### Additional information

I`m going to create a pullrequest soon.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback.

**Comment by OneCricketeer** [comment]
You should be able to set [any arbitrary config value](https://github.com/bitnami/containers/blob/main/bitnami/schema-registry/7.3/debian-11/rootfs/opt/bitnami/scripts/libschemaregistry.sh#L200-L209)
