### ISSUE TITLE
[Odoo] Support TLS connection to PostgreSQL database

### ISSUE THREAD

**Issue by tobru** [bitnami/containers#17590]
### Name and Version

bitnami/odoo:latest

### What is the problem this feature will solve?

Some database service providers require TLS connections to their database. With such managed services, it's currently not possible to use the Odoo image from Bitnami.

### What is the feature you are proposing to solve the problem?

Introduce support for TLS connection to PostgreSQL. Odoo itself supports it with the `db_sslmode` configuration parameter. See [upstream documentation](https://www.odoo.com/documentation/16.0/administration/install/deploy.html#ssl-between-odoo-and-postgresql) for more information.

### What alternatives have you considered?

There is no alternative, connections which do not support TLS simply do not work.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by tobru** [comment]
It looks like TLS already works out of the box, therefore closing this issue.
