### ISSUE TITLE
MySQL check ignores SSL settings

### ISSUE THREAD

**Issue by duk3luk3** [bitnami/containers#17802]
### Name and Version

bitnami/wordpress:6.1.1

### What steps will reproduce the bug?

1. Set up a MySQL server with `require_secure_transport` configuration
2. Configure these wordpress options:
  * DB host etc.
  * `WORDPRESS_ENABLE_DATABASE_SSL=yes`
  * `WORDPRESS_VERIFY_DATABASE_SSL=no`
  * `BITNAMI_DEBUG=yes`
4. Start the container

### What is the expected behavior?

Wordpress is initialized and started, and all DB connections are secured

### What do you see instead?

Container fails with "Could not connect to the database" error

### Additional information

The root cause for this issue is that the `wordpress_wait_for_mysql_connection` never attempts a secure connection:

https://github.com/bitnami/containers/blob/208c7fdbc5330ae7122edb041fa693ccc0eee3a0/bitnami/wordpress/6/debian-11/rootfs/opt/bitnami/scripts/libwordpress.sh#L562-L575

This needs to be fixed.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ferronsw** [comment]
Having the same issue!
