### ISSUE TITLE
Please help upgrade bitnami/drupal to drupal version 9.5.0 and 10.0.0

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/containers#18353]
### Name and Version

bitnami/drupal

### What is the problem this feature will solve?

Drupal 9.5.0 and 10.0.0 has been out for a little while, please help upgrade the bitnami/drupal container version (now the version is drupal 9.4.9). Thanks very much.

### What is the feature you are proposing to solve the problem?

version upgrade.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by serchie** [comment]
Now we already upgraded from 9.4.9 to 9.5.2. But, how can we upgrade from 9.5.x to 10.x?

I already uninstalled all deprecated modules and themes from 9.5.2, then I changed the tag of the container from drupal:9 to drupal:10, but it doesn't work: container gets stuck while trying to connect to database.

Any suggestions?

Thanks in advance.

**Comment by carrodher** [comment]
In order to not mix topics, could you please create a separate issue for the topic you're describing?
