### ISSUE TITLE
[bitnami/mariadb-galera] Loading user's custom files from /docker-entrypoint-startdb.d hangs and timeouts

### ISSUE THREAD

**Issue by pantovad** [bitnami/containers#18423]
### Name and Version

bitnami/mariadb-galera:10.6.11

### What steps will reproduce the bug?

1. setup a startup SQL script loaded from /docker-entrypoint-startdb.d through appropriate docker volume. For example start.sql:
```
CREATE DATABASE IF NOT EXISTS `data2`;
GRANT ALL ON `data2`.* TO 'galera'@'%';
```
2. start the bootstrap node container
3. restart the container
4. check the docker logs

### What is the expected behavior?

The container should start the DB and execute the SQL script(s) on each start.

### What do you see instead?

The container hangs and timeouts while trying to execute SQL script:
```
mariadb 09:14:33.70 
mariadb 09:14:33.71 Welcome to the Bitnami mariadb-galera container
mariadb 09:14:33.71 Subscribe to project updates by watching https://github.com/bitnami/containers
mariadb 09:14:33.71 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mariadb 09:14:33.71 
mariadb 09:14:33.71 INFO  ==> ** Starting MariaDB setup **
mariadb 09:14:33.73 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 09:14:33.73 INFO  ==> Initializing mariadb database
mariadb 09:14:33.74 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 09:14:33.74 INFO  ==> Setting user option
mariadb 09:14:33.75 INFO  ==> Setting slow_query_log option
mariadb 09:14:33.76 INFO  ==> Setting long_query_time option
mariadb 09:14:33.77 INFO  ==> Setting wsrep_node_name option
mariadb 09:14:33.78 INFO  ==> Setting wsrep_node_address option
mariadb 09:14:33.78 INFO  ==> Setting wsrep_sst_auth option
mariadb 09:14:33.79 INFO  ==> Injecting custom configuration 'my_custom.cnf'
mariadb 09:14:33.79 INFO  ==> Persisted data detected. Restoring
mariadb 09:14:33.80 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
mariadb 09:24:37.31 ERROR ==> Timed out waiting for MySQL to be accessible
```

### Additional information

The debug shows that the function called `mysql_custom_scripts 'start'` get stuck until timedout while executing the function `wait_for_mysql_access "$DB_ROOT_USER"` (see https://github.com/bitnami/bitnami-docker-mariadb-galera/issues/23 and https://github.com/bitnami/bitnami-docker-mariadb-galera/commit/dff271f2a065c22e0139512590e73036006ede84) as apparently the DB is not ready at that stage.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by pantovad** [comment]
Hi @carrodher - this issue seems to be going a bit deeper into the startup logic that seems to be broken and is not trivial for solving:

- the setup.sh script called by entrypoint.sh would start the DB in the background on the bootstrap node through `mysql_initialize` (`mysql_start_bg`) function **only on initial creation of the container** and only then the function `mysql_custom_scripts` with `init` and `start` parameters will be executed successfully
- on each subsequent container start the DB will not be started by the setup.sh  (`mysql_initialize`) script and thus will cause failure of `mysql_custom_scripts start` expecting the DB available.

The logic needs to be properly rechecked and startup scripts implementation properly done or abandoned.

I would gladly provide a PR but this issue requires more of a redesign rather then a fix.

**Comment by gongomgra** [comment]
Hi @pantovad,

Sorry for the delay. I think I couldn't reproduce your issue.

I launched a test on my side with your custom SQL file, and although it got run, it didn't work because the galera user doesn't exist initially on the database.

```
debian-11-mariadb-galera-1  | mariadb 16:07:01.23 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
debian-11-mariadb-galera-1  | mariadb 16:07:01.25 DEBUG ==> Executing SQL command:
debian-11-mariadb-galera-1  | select 1
debian-11-mariadb-galera-1  | 1
debian-11-mariadb-galera-1  | mariadb 16:07:01.26 DEBUG ==> Executing /docker-entrypoint-startdb.d/start.sql
debian-11-mariadb-galera-1  | mariadb 16:07:01.26 DEBUG ==> Executing SQL command:
debian-11-mariadb-galera-1  | CREATE DATABASE IF NOT EXISTS `data2`;
debian-11-mariadb-galera-1  | GRANT ALL ON `data2`.* TO 'galera'@'%';
debian-11-mariadb-galera-1  | 2023-01-10 16:07:01 20 [Warning] WSREP: Ignoring error 'Can't find any matching row in the user table' on query. Default database: ''. Query: 'GRANT ALL ON `data2`.* TO 'galera'@'%'', Error_code: 1133
debian-11-mariadb-galera-1  | ERROR 1133 (28000) at line 2: Can't find any matching row in the user table
```

If I update your SQL command with a valid user (for example `root`), the initialization process works fine

```
debian-11-mariadb-galera-1  | mariadb 16:10:46.55 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
debian-11-mariadb-galera-1  | mariadb 16:10:46.56 DEBUG ==> Executing SQL command:
debian-11-mariadb-galera-1  | select 1
debian-11-mariadb-galera-1  | 1
debian-11-mariadb-galera-1  | mariadb 16:10:46.57 DEBUG ==> Executing /docker-entrypoint-startdb.d/start.sql
debian-11-mariadb-galera-1  | mariadb 16:10:46.57 DEBUG ==> Executing SQL command:
debian-11-mariadb-galera-1  | CREATE DATABASE IF NOT EXISTS `data2`;
debian-11-mariadb-galera-1  | GRANT ALL ON `data2`.* TO 'root'@'%';
debian-11-mariadb-galera-1  | mariadb 16:10:46.60 INFO  ==> Stopping mariadb
debian-11-mariadb-galera-1  | 2023-01-10 16:10:46 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
(...)
```

After that, the restart also works, and the `start.sql` file is skipped because the MariaDB node is not detected as primary (although I don't know why)

```
debian-11-mariadb-galera-1  | mariadb 16:12:03.28 WARN  ==> This node was previouly booted, you may need to force bootstrapping in one of the nodes.
(...)
debian-11-mariadb-galera-1  | mariadb 16:12:03.34 INFO  ==> Persisted data detected. Restoring
debian-11-mariadb-galera-1  | mariadb 16:12:03.35 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
debian-11-mariadb-galera-1  | mariadb 16:12:03.36 WARN  ==> Custom SQL startdb is not supported on non-primary nodes, ignoring /docker-entrypoint-startdb.d/start.sql
```

And the MariaDB server is running fine after that. Can you tell us if I miss any step? Do you have any other SQL file adding the `galera` user? Can you also set the `BITNAMI_DEBUG=true` environment variable in your docker-compose file to get debug logs on your execution?

> The container should start the DB and execute the SQL script(s) on each start.

About this, it is true that scripts in the  `/docker-entrypoint-startdb.d` folder should be run on every container restart. I will continue checking this. Not sure why the node is not detected as primary, because I only had one node on my docker-compose file.

**Comment by pantovad** [comment]
> Hi @pantovad,
> 
> Sorry for the delay. I think I couldn't reproduce your issue.
> 
> I launched a test on my side with your custom SQL file, and although it got run, it didn't work because the galera user doesn't exist initially on the database.
**The env var needs to be set in your docker-compose or command: MARIADB_DATABASE and MARIADB_USER for an initial DB/user to be created - check the docs please**
> 
> ```
> debian-11-mariadb-galera-1  | mariadb 16:07:01.23 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
> debian-11-mariadb-galera-1  | mariadb 16:07:01.25 DEBUG ==> Executing SQL command:
> debian-11-mariadb-galera-1  | select 1
> debian-11-mariadb-galera-1  | 1
> debian-11-mariadb-galera-1  | mariadb 16:07:01.26 DEBUG ==> Executing /docker-entrypoint-startdb.d/start.sql
> debian-11-mariadb-galera-1  | mariadb 16:07:01.26 DEBUG ==> Executing SQL command:
> debian-11-mariadb-galera-1  | CREATE DATABASE IF NOT EXISTS `data2`;
> debian-11-mariadb-galera-1  | GRANT ALL ON `data2`.* TO 'galera'@'%';
> debian-11-mariadb-galera-1  | 2023-01-10 16:07:01 20 [Warning] WSREP: Ignoring error 'Can't find any matching row in the user table' on query. Default database: ''. Query: 'GRANT ALL ON `data2`.* TO 'galera'@'%'', Error_code: 1133
> debian-11-mariadb-galera-1  | ERROR 1133 (28000) at line 2: Can't find any matching row in the user table
> ```
> 
> If I update your SQL command with a valid user (for example `root`), the initialization process works fine
> 
> ```
> debian-11-mariadb-galera-1  | mariadb 16:10:46.55 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
> debian-11-mariadb-galera-1  | mariadb 16:10:46.56 DEBUG ==> Executing SQL command:
> debian-11-mariadb-galera-1  | select 1
> debian-11-mariadb-galera-1  | 1
> debian-11-mariadb-galera-1  | mariadb 16:10:46.57 DEBUG ==> Executing /docker-entrypoint-startdb.d/start.sql
> debian-11-mariadb-galera-1  | mariadb 16:10:46.57 DEBUG ==> Executing SQL command:
> debian-11-mariadb-galera-1  | CREATE DATABASE IF NOT EXISTS `data2`;
> debian-11-mariadb-galera-1  | GRANT ALL ON `data2`.* TO 'root'@'%';
> debian-11-mariadb-galera-1  | mariadb 16:10:46.60 INFO  ==> Stopping mariadb
> debian-11-mariadb-galera-1  | 2023-01-10 16:10:46 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
> (...)
> ```
> 
> After that, the restart also works, and the `start.sql` file is skipped because the MariaDB node is not detected as primary (although I don't know why)
**In order to have your node assigned the bootstrap role you need env var MARIADB_GALERA_CLUSTER_BOOTSTRAP set to yes/true. Check the docs please.**
> 
> ```
> debian-11-mariadb-galera-1  | mariadb 16:12:03.28 WARN  ==> This node was previouly booted, you may need to force bootstrapping in one of the nodes.
> (...)
> debian-11-mariadb-galera-1  | mariadb 16:12:03.34 INFO  ==> Persisted data detected. Restoring
> debian-11-mariadb-galera-1  | mariadb 16:12:03.35 INFO  ==> Loading user's custom files from /docker-entrypoint-startdb.d
> debian-11-mariadb-galera-1  | mariadb 16:12:03.36 WARN  ==> Custom SQL startdb is not supported on non-primary nodes, ignoring /docker-entrypoint-startdb.d/start.sql
> ```
> 
> And the MariaDB server is running fine after that. Can you tell us if I miss any step? Do you have any other SQL file adding the `galera` user? Can you also set the `BITNAMI_DEBUG=true` environment variable in your docker-compose file to get debug logs on your execution?
**You just missed basic configs with env vars in your setup as explained above**
> 
> > The container should start the DB and execute the SQL script(s) on each start.
> 
> About this, it is true that scripts in the `/docker-entrypoint-startdb.d` folder should be run on every container restart. I will continue checking this. Not sure why the node is not detected as primary, because I only had one node on my docker-compose file.

@gongomgra please see my comments about scripts and their behavior above - there should be quite enough information to understand the issue and why they do not behave es expected. Apparently, the scripts were inherited from MariDB single instance Docker image but not fully adjusted for Galera ...

**Comment by gongomgra** [comment]
Hi Pantovac,

We have been checking this issue further. We have found the cause of what is preventing your start SQL script to be run. However, we don't think running SQLs commands like the one you shared makes sense to be run every time the bootstrap node is started, as MariaDB Galera should be taken into account as a whole cluster and not as a single node. The information added by those SQL scripts would be part of the cluster already, and the synchronization algorithm of the cluster would make the information available to the new node as well. If you want to add new information to the cluster, then we recommend you to include the SQL scripts under the `docker-entrypoint-initdb.d` folder, for the new information to be included only once: the first time the cluster is created.

We understand the `docker-entrypoint-startdb.d` scripts can be useful for other purposes, like registering the new node on an external monitoring service via a curl's POST action. Can you tell us why do you need to run some SQL commands multiple times?

**Comment by gongomgra** [comment]
Hi @pantovad ,

Thanks for your message and sorry for the delay. As mentioned previously, we do not think that restarting a node of the cluster is a good solution for adding new data, but you can achieve your desired behavior using a custom shell script in the `docker-entrypoint-startdb.d` folder.
