### ISSUE TITLE
MONGODB_ROOT_PASSWORD incorrect validation condition makes it required on a non-primary node under some condition

### ISSUE THREAD

**Issue by tguez** [bitnami/containers#18506]
### Name and Version

bitnami/mongodb:6.0.3-debian-11-r14

### What steps will reproduce the bug?

Run this [docker-compose](https://github.com/bitnami/containers/blob/main/bitnami/mongodb/docker-compose-replicaset.yml) but add `MONGODB_USERNAME` env variable to a non-primary node.

This secondary node will not be able to start because of the error:

`The MONGODB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with a blank root password. This is only recommended for development.`

This is just a quick way to reproduce it, the actual use case I encountered this bug in is running the[ mongodb-sharded helm chart](https://github.com/bitnami/charts/tree/main/bitnami/mongodb-sharded/) with the following configuration:

`common.initScriptsCM` which points to an init script that creates some initial users.
This script needs the user credentials, which consists of a user name, that user name comes from

`common.extraEnvVarsSecret` where we define a `MONGODB_USER` secret.

### What is the expected behavior?

The non-primary node should pass the env variables validation with `MONGODB_USERNAME` env variable set and `MONGODB_ROOT_PASSWORD` not set.

### What do you see instead?

If MONGODB_USERNAME env variable is set in the container of a non-primary node, the non-primary node will fail to start because of this validation error:

`The MONGODB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with a blank root password. This is only recommended for development.`

### Additional information

In non-primary nodes there shouldn't be a `MONGODB_ROOT_PASSWORD` set, [in fact there is even a validation that doesn't allow for this env variable to be set. ](https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh#L132)

So putting aside whether or not we should have user `MONGODB_USERNAME` env variable for our custom script, there shouldn't be a condition, where on a non-primary there must be `MONGODB_ROOT_PASSWORD` set, [as in line 189.](https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh#L189)

I want to make sure I'm not missing something before opening an MR that fixes it, I guess there should be an additional condition on line 185 to check the node is a primary, but then it makes all of this if elif condition redundant because there is already a validation for this exact condition [in line 145](https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh#L145).

Our current workaround is simply changing the name of the `MONGODB_USERNAME` env variable we define.

**Comment by tguez** [comment]
@migruiz4 

> Hi @tguez,
> 
> I'm sorry but I'm not sure I understand your use case.
> 
> The env variables `MONGODB_USERNAME`/`MONGODB_PASSWORD`/`MONGODB_DATABASE` are not supported in a mongodb-sharded environment. If you are adding them for your init scripts, I recommend setting a different variable name.
> 
> Unlike regular MongoDB, the user creation on MongoDB Sharded requires the cluster to be up and running. In the following discussion, you can find approaches used by other users that you may find helpful, like adding a passive wait for the cluster to be up: [bitnami/charts#1655](https://github.com/bitnami/charts/issues/1655)


@migruiz4 Hi thanks for replying

The use case is that bitnami sharded mongodb chart supports a custom init script, using `common.initScriptsCM`.

In the custom logic of this init script that we wrote, we used an environment variable, so the init script will be configurable. This env variable name was chosen by us to be `MONGODB_USERNAME`. This env variable isn't used for any bitnami specific documented purpose, but for out script purposes, and this script results are successful using this env variable.

The bug is that the container of the image fails to start on non-primary nodes if this env variable name(`MONGODB_USERNAME`) is defined in the container, because of bitnami custom validation scripts.

As explained in the issue there is no reason for the validations to be written as they are, in a way that causes this error to occur when this env variable is used, as if this env variable name is reserved and forbidden, in the very least there should be an appropriate error message.

**Comment by migruiz4** [comment]
Hi @tguez 

> In the custom logic of this init script that we wrote, we used an environment variable, so the init script will be configurable. This env variable name was chosen by us to be MONGODB_USERNAME. This env variable isn't used for any bitnami specific documented purpose, but for out script purposes, and this script results are successful using this env variable.

That would be the cause of the issue. Simply using a different env var name should fix your issue.

The env var MONGODB_USERNAME is not documented for the mongodb-sharded as it is not supported yet as I mentioned in my previous comment, but is included in the container logic that is shared with the mongodb container (libmongodb.sh).

**Comment by tguez** [comment]
> Hi @tguez
> 
> > In the custom logic of this init script that we wrote, we used an environment variable, so the init script will be configurable. This env variable name was chosen by us to be MONGODB_USERNAME. This env variable isn't used for any bitnami specific documented purpose, but for out script purposes, and this script results are successful using this env variable.
> 
> That would be the cause of the issue. Simply using a different env var name should fix your issue.
> 
> The env var MONGODB_USERNAME is not documented for the mongodb-sharded as it is not supported yet as I mentioned in my previous comment, but is included in the container logic that is shared with the mongodb container (libmongodb.sh).

Hi thanks again, I know the cause of the issue, I pointed to where the issue is in bitnami validation scripts, and the workaround we used, as mentioned in the issue body.
The point of opening this issue is not for me I already have the workaround, it's to support this project so other people won't encounter the same issue, my main point is as follows:

An undocumented env variable shouldn't break the image of the container, it can be seen from both the behavior and the source code that this is unintended behavior and the validations in `libmongodb.sh` are contradictory with or without mongodb sharded, as explained under "Additional info" in my issue. It's just that this invalid logic is only discovered when using the env variable `MONGODB_USERNAME` with replication.

It's a bug in an edge case that should preferably be resolved, because as I mentioned, there are other valid reasons for env variables to exist besides the documented env variables, for personal usage, and if a user by chance chose the wrong naming for his env variable, the image intended functionality breaks without a proper error message.

**Comment by alanionita** [comment]
Reviving this because the issue with MONGODB_ROOT_PASSWORD still occurs when using the documented replication configuration seen here (https://github.com/bitnami/containers/blob/main/bitnami/mongodb/README.md#setting-up-replication)

`MONGODB_ROOT_PASSWORD shouldn't be set on a 'non-primary' node`

No `MONGODB_ROOT_PASSWORD` is set on the secondary services as per example config.

Also no `MONGODB_USERNAME` is set on the main db node

Side-effect: Once this error appears the secondary nodes fail, which then causes the whole replication stack to be unusable. 

Importance: This is an issue because newer ORMs require a replication stack for CREATE ops. Meaning that the setup for replication is the main happy path for MongoDB.
