### ISSUE TITLE
Minio: mac check in GCM failed 

### ISSUE THREAD

**Issue by sathishkumar-p** [bitnami/containers#18837]
### Name and Version

bitnami/minio:2022.1.28-debian-10-r0

### What steps will reproduce the bug?

1. Install the official helm chart of bitnami/minio
2. List users in minio using Minio Admin Client from java
![image](https://user-images.githubusercontent.com/25504642/210210425-2e1ed579-a277-43c7-ad5d-69547e1e25cb.png)
![image](https://user-images.githubusercontent.com/25504642/210210458-7ac7d713-08b8-4219-b350-0385479b8650.png)

### What is the expected behavior?

List users from minio server

### What do you see instead?

I am getting the following error while listing the users. InvalidCipherTextException: mac check in GCM failed

### Additional information

Also raised the bug on minio offical: They closed with the issue go version is different.
https://github.com/minio/minio/issues/16244

**Comment by rafariossaa** [comment]
Thanks for reporting this.
Do you think this is caused by the Go version ?

**Comment by gongomgra** [comment]
Hi @sathishkumar-p,

Sorry for the delay. I have not been able to reproduce your issue using the same minio `2022-12-12` version.

I deployed the chart locally, added a couple of users using the `mc` command-line, and then listed the users from a different pod using a sample `ListUsers.java` file.

* minio server pod
```
root@minio-6fc88bbfc7-2mg6v:/opt/bitnami/minio-client# minio --version
minio version DEVELOPMENT.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.18.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

root@minio-6fc88bbfc7-2mg6v:/opt/bitnami/minio-client# mc admin user add local foo bar123456
Added user `foo` successfully.

root@minio-6fc88bbfc7-2mg6v:/opt/bitnami/minio-client# mc admin user add local test bitnami123
Added user `test` successfully.
```

* java pod
```
javac -cp jackson-datatype-jsr310-2.9.10.jar:minio-8.5.1-all.jar:minio-admin-8.5.1.jar ListUsers.java && java -cp minio-8.5.1-all.jar:minio-admin-8.5.1.jar:jackson-datatype-jsr310-2.9.10.jar:. ListUsers
minio client created!
test: io.minio.admin.UserInfo@48bb62
foo: io.minio.admin.UserInfo@1750fbeb
```

And here is the sample `ListUsers.java` file

```java
(...import...)

public class ListUsers {
    public static void main(String[] args)
      throws IOException, NoSuchAlgorithmException, InvalidKeyException, ErrorResponseException, InsufficientDataException, InvalidCipherTextException {
        MinioAdminClient minioClient = MinioAdminClient.builder().endpoint("http://minio:9000").credentials("PUT-YOUR-ADMIN-USERNAME-HERE", "PUT-YOUR-PASSWORD-HERE").build();
        System.out.println("minio client created!");
        try {
            Map <String, UserInfo> users = minioClient.listUsers();
            users.forEach((key, value) -> System.out.println(key + ": " + value));
        } catch (InvalidCipherTextException e ) {
            System.out.println(e);
        }
        System.exit(0);
    }
}
```

I tested the same with the most recent 2023 version we have published using the docker-compose file, and I was not able to reproduce the issue either. Can you try with the updated version?
