### ISSUE TITLE
"settings.php No such file or directory" when starting Drupal from backup volume

### ISSUE THREAD

**Issue by kopeboy** [bitnami/containers#18862]
### Name and Version

bitnami/drupal-nginx:9

### What steps will reproduce the bug?

1. Run the application using Docker Compose
2. Backup the persisted volumes like suggested in your docs at https://github.com/bitnami/containers/tree/main/bitnami/drupal-nginx#backing-up-your-container
```
docker run --rm -v /Users/kopeboy/drupal-test-2/backups:/backups --volumes-from drupal-test-2-drupal-1 busybox \
  cp -a /bitnami/drupal /backups/
```
and 
```
docker run --rm -v /Users/kopeboy/drupal-test-2/backups:/backups --volumes-from drupal-test-2-mariadb-1 busybox \
  cp -a /bitnami/mariadb /backups/
```
3. Change the volumes paths in the docker-compose.yml:
mariadb:
```yaml
volumes:
      - '/Users/kopeboy/drupal-test-2/backups:/bitnami/mariadb'
```
drupal:
```yaml
volumes:
      - '/Users/kopeboy/drupal-test-2/backups:/bitnami/drupal'
```
4. Run docker-compose up and the drupal container can't start.

### What do you see instead?

From the drupal container logs I can see:
```
INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
```
```
INFO  ==> Trying to connect to the database server
grep: /opt/bitnami/drupal/sites/default/settings.php: No such file or directory
```
```
WARN  ==> The Drupal configuration file '/opt/bitnami/drupal/sites/default/settings.php' is not writable. Configurations based on environment variables will not be applied for this file.
```

It seems there aren't problems on the mariadb container instead (nothing different than from the first compose up).

### Additional information

From your image docs I can see 
> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001."

so I guess that's the problem?
If that's the case, how should I set proper permissions?

Old stale (unresolved) issue on the same topic for reference: https://github.com/bitnami/bitnami-docker-drupal/issues/120

Thank you

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
