### ISSUE TITLE
[bitnamin/node] Install Vite

### ISSUE THREAD

**Issue by dominikkrulak** [bitnami/containers#19056]
### Name and Version

bitnami/node:18.12.1-debian-11-r20

### What steps will reproduce the bug?

This isn't a bug! More of a help.

Before my attempt to dockerize Vite I have it successfully running locally. 

So my local working directory is:
```
project
|_ package.json
|_ .eslintrc.json
|_ .stylelintrc.json
|_ postcss.config.js
|_ tailwind.config.js
|_ tsconfig.json
|_ vite.config.ts
|_ src
   |_ js
   |_ ts
   |_ vue
|_ web
    |_ static
```

So the same files and folders from my local project are copied to the `app` directory in node's image from which docker tries to run and install everything from `package.json` file.

Dockerfile
```
FROM docker.io/bitnami/node:18.12.1-debian-11-r20

COPY src /app
COPY web /app
COPY package.json /app
COPY .eslintrc.json /app
COPY .stylelintrc.json /app
COPY postcss.config.js /app
COPY tailwind.config.js /app
COPY tsconfig.json /app
COPY vite.config.ts /app

WORKDIR /app

RUN npm install

CMD npm run vite-dev
```
package.json
```
{
    "name": "vite frontend tooling",
    "version": "1.0.0",
    "bunch-of-other-keys": "...",
    "scripts": {
        "vite-dev": "vite",
        "vite-build": "npm run lint && vite build",
        "lint": "npm run lint-css && npm run lint-ts && npm run lint-js",
        "lint-css": "stylelint './src/css/*.{scss,css}' --fix --allow-empty-input && stylelint './src/vue/*.vue' --fix --allow-empty-input",
        "lint-ts": "tsc --noEmit && vue-tsc --noEmit",
        "lint-js": "eslint './src/ts/*.ts' --fix --no-error-on-unmatched-pattern && eslint './src/vue/*.vue' --fix --no-error-on-unmatched-pattern && eslint './src/js/*.js' --fix --no-error-on-unmatched-pattern"
    }
}
```

### What is the expected behavior?

Running Vite's dev server.

### What do you see instead?

```
npm ERR! Missing script: "vite-dev"
2023-01-03T13:42:55.425261959Z npm ERR! 
2023-01-03T13:42:55.425270125Z npm ERR! Did you mean this?
2023-01-03T13:42:55.425276916Z npm ERR!     npm run vite dev # run the "vite dev" package script
2023-01-03T13:42:55.425284130Z npm ERR! 
2023-01-03T13:42:55.425289953Z npm ERR! To see a list of scripts, run:
2023-01-03T13:42:55.425295883Z npm ERR!   npm run
2023-01-03T13:42:55.431176357Z 
2023-01-03T13:42:55.431209209Z npm ERR! A complete log of this run can be found in:
2023-01-03T13:42:55.431219112Z npm ERR!     /root/.npm/_logs/2023-01-03T13_42_55_288Z-debug-0.log
```

### Additional information

The error I get seems like there is no `vite` installed in `node_modules` folder or there isn't no `node_modules` folder at `app` directory.

I don't understand what I'm doing wrong.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Node container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
