### ISSUE TITLE
[bitnami/openldap] - HA support

### ISSUE THREAD

**Issue by itmwiw** [bitnami/containers#19077]
### Name and Version

bitnami/openldap:2.6.3

### What is the problem this feature will solve?

It's rather a question than a problem. I don't know if it's the right section to ask this.

### What is the feature you are proposing to solve the problem?

What I'd like to ask is if we can implement HA using bitnami docker image. Can we for exemple deploy 2 or 3 replicas in Kubernetes without having to worry about anything?
Thanks in advance

**Comment by fmulero** [comment]
Hi @itmwiw 

To be perfectly blunt, our OpenLDAP container is very simple and we have not implemented nor tested any cluster configuration. That's the reason why we don't provide a helm chart for OpenLDAP. Said that, the short answer to your question is: _You have to worry about everything_. Maybe you can use our container as baseline, but you have to configure and implement the replication strategy that you need by yourself.

Regards

**Comment by oernii** [comment]
I was thinking of using this image for a Kubernetes replication. You basically need 2 replicas in a StatefulSet and set up syncrepl between them. Not sure how to failover, but the PGoperator uses patroni to do it's magic for postgres and seems to work very nicely.

Otherwise some liveness probe could be used to assign the service to an active pod.

As for the syncrepl, that can be set up by following https://openldap.org/doc/admin26/replication.html .

**Comment by rohan-97** [comment]
Hi @oernii ,  

I went through the link https://openldap.org/doc/admin26/replication.html .
It specifies adding following configuration in slapd.conf

```
        database mdb
        maxsize 1073741824
        suffix dc=Example,dc=com
        rootdn dc=Example,dc=com
        directory /var/ldap/db
        index objectclass,entryCSN,entryUUID eq

        syncrepl rid=123
                provider=ldap://provider.example.com:389
                type=refreshOnly
                interval=01:00:00:00
                searchbase="dc=example,dc=com"
                filter="(objectClass=organizationalPerson)"
                scope=sub
                attrs="cn,sn,ou,telephoneNumber,title,l"
                schemachecking=off
                bindmethod=simple
                binddn="cn=syncuser,dc=example,dc=com"
                credentials=secret
```

However I am not able to find slapd.conf file in the container, also I am not able to find any environment variable which would add custom configuration in slapd.conf,

I think I might be missing something, can you please help me out with the configurations?
