### ISSUE TITLE
[bitnami/pgbouncer] Impossible to set auth_hba_file

### ISSUE THREAD

**Issue by afabrySibylone** [bitnami/containers#19196]
### Name and Version

bitnami/pgbouncer:latest

### What steps will reproduce the bug?

With the lastest image of bitnami/pgbouncer
When I run the following docker command :
`
docker run --name pgbouncer \
  -v pathr:/opt/bitnami/pgbouncer/hba \
  -e PGBOUNCER_AUTH_TYPE=hba \
  -e PGBOUNCER_AUTH_HBA_FILE=/opt/bitnami/pgbouncer/hba/pg_hba.conf \
    bitnami/pgbouncer:latest
`
The environement variable PGBOUNCER_AUTH_TYPE is used to fill the variable auth_type in the file pgbouncer.ini but the environment variable PGBOUNCER_AUTH_HBA_FILE is not use to fill the variable auth_hba_file in the same file. How to define the path to the pg_hba.conf when we want to use the hba AUTH_TYPE ?

### What is the expected behavior?

the variable auth_hba_file in the file pgbouncer.ini must be filled with the PGBOUNCER_AUTH_HBA_FILE environment variable

### What do you see instead?

there is no variable auth_hba_file in the file pgbouncer.ini

**Comment by javsalgar** [comment]
Hi,

I don't see declared in the container logic a `PGBOUNCER_AUTH_HBA_FILE` env var. Would it make sense to create one for defining the path to the file? If so, would you like to submit a PR adding that support?
