### ISSUE TITLE
how to set etcd member parameters? example: quota-backend-bytes auto-compaction-mode

### ISSUE THREAD

**Issue by huangjiasingle** [bitnami/containers#19342]
### Name and Version

etcd image etcd:3.5.6-debian-11-r0

### What is the problem this feature will solve?

modify etcd storage capicity and anothers member paramters

### What is the feature you are proposing to solve the problem?

modify more etcd memeber parameters

### What alternatives have you considered?

command line flag

**Comment by javsalgar** [comment]
Hi,

In the etcd container we have the function `etcd_setup_from_environment_variables` , which allows to set configuration variables using the `ETCD_CFG_*` env vars.

https://github.com/bitnami/containers/blob/main/bitnami/etcd/3.5/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh#L63

Could you try with `ETCD_CFG_QUOTA_BACKEND_BYTES` or `ETCD_CFG_AUTO_COMPACTION_MODE` env vars?
