### ISSUE TITLE
[bitnami/postgresql] Shutdown mode ignored - always smart shutdown

### ISSUE THREAD

**Issue by brightdroid** [bitnami/containers#19662]
### Name and Version

bitnami/postgresql:15.1.0-debian-11-r12

### What steps will reproduce the bug?

1. deploy using helm chart https://artifacthub.io/packages/helm/bitnami/postgresql
2. connect to the database and leave the connection open
3. restart statefulset

### What is the expected behavior?

Postgres should by default use "fast" shutdown as defined in `postgresql-env.sh`.
Also, it should use the env var `POSTGRESQL_SHUTDOWN_MODE`.

### What do you see instead?

Regardless if I set env `POSTGRESQL_SHUTDOWN_MOD`E to "fast" or not the server always uses "smart" shutdown mode.

### Additional information

When I exec `env` inside the running container I can see the correct (fast) value for `POSTGRESQL_SHUTDOWN_MODE`.

**Comment by rafariossaa** [comment]
Hi,
  This environment variable is used in [postgresql_stop](https://github.com/bitnami/containers/blob/6b2abe15f3134460dd5f963d484b089ed398472d/bitnami/postgresql/14/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L735), and this function is used at the end of the initialization or in the trap in the setup script, but it is not being used in `run.sh`.
  I will do some tests on this.

**Comment by rafariossaa** [comment]
Thanks for the links.

Would you like to send a PR implementing this ? We will be glad to review and merge it.

**Comment by brightdroid** [comment]
I'll try to, but I've found a maybe better solution using [Dockerfile STOPSIGNAL](https://docs.docker.com/engine/reference/builder/#stopsignal).
Though this would remove the (currently not working) shutdown mode option.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the info.

**Comment by brightdroid** [comment]
I've found the solution to my problem which already existed but may be added as a default.
```yaml
primary:
  lifecycleHooks:
    preStop:
      exec:
        command: ["pg_ctl", "stop", "-m", "fast"]
```
