### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by zhangwenjing** [bitnami/containers#19740]
### Name and Version

bitnami/kubectl

### What steps will reproduce the bug?
```console
$ docker run --rm --name kubectl  bitnami/kubectl:latest /bin/bash
error: unknown command "/bin/bash" for "kubectl"

$ docker run --rm --name kubectl  bitnami/kubectl:latest /bin/sh
error: unknown command "/bin/sh" for "kubectl"
```
I used the dockerhub recommend command to start a container and failed. Would you please tell me what's wrong with it?
I want to start the container and get into the container to execute some commands.

### What is the expected behavior?

I want to start a container and get into the container to execute some command

### What do you see instead?

I don't know how to use the image.

**Comment by carrodher** [comment]
This container directly executes the `kubectl` binary, you can find info about how to use it in the README, see https://github.com/bitnami/containers/tree/main/bitnami/kubectl#configuration

**Comment by OneCricketeer** [comment]
The correct way to do what you're trying is

```
docker run --rm -ti --entrypoint=/bin/bash bitnami/kubectl:latest
```

(removed `name` since it's pointless with `rm`)
