### ISSUE TITLE
Cassandra env:auto_snapshot_ttl

### ISSUE THREAD

**Issue by nevlkv** [bitnami/containers#19750]
### Name and Version

bitnami/cassandra:4.1.0

### What is the problem this feature will solve?

On default  `auto_snapshot = true` snapshots take up a lot of space, and needed regular cleanups

### What is the feature you are proposing to solve the problem?

Need **env** variable, for enable and set [auto_snapshot_ttl](https://cassandra.apache.org/doc/latest/cassandra/configuration/cass_yaml_file.html#auto_snapshot_ttl)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by mdhont** [comment]
The PR has been merged. Thank you for contributing.
