### ISSUE TITLE
[bitnami/haproxy] enable LINUX_SPLICE feature on haproxy build

### ISSUE THREAD

**Issue by IceCodeNew** [bitnami/containers#19816]
### Name and Version

bitnami/haproxy:2

### What is the problem this feature will solve?

With `option splice-auto` specified in the HAProxy, the `bitnami/haproxy` image complains about this feature is not enabled.

[option splice-auto](http://docs.haproxy.org/2.6/configuration.html#4.2-option%20splice-auto)
> When this option is enabled either on a frontend or on a backend, HAProxy
will automatically evaluate the opportunity to use kernel tcp splicing to
forward data between the client and the server, in either direction. HAProxy
uses heuristics to estimate if kernel splicing might improve performance or
not. Both directions are handled independently. Note that the heuristics used
are not much aggressive in order to limit excessive use of splicing. This
option requires splicing to be enabled at compile time, and may be globally
disabled with the global option "[nosplice](http://docs.haproxy.org/2.6/configuration.html#nosplice)". Since splice uses pipes, using it
requires that there are enough spare pipes.

SUSE had enabled this feature in practice, you can see their blog here: https://www.suse.com/c/speeding-ssl-need-know-haproxy/

This feature is enabled by default in the official image. It should make sense to enable this feature in the `bitnami/haproxy` image.

### What is the feature you are proposing to solve the problem?

Simply do not specifically disable the `LINUX_SPLICE` feature should solve this problem.
In my experience, this feature is enabled by default when building HAProxy from the source without specifying any args.
// Refer to: https://github.com/haproxy/haproxy/blob/a9de7ea1dc3bbc627ae3ab82de9e012d10ed7ffb/Makefile#L362

### What alternatives have you considered?

Use the official image `haproxy:lts-alpine` instead of `bitnami/haproxy:2`

**Comment by javsalgar** [comment]
Hi,

Thank you for raising this issue. We are currently compiling haproxy with these flags:

```
'TARGET=generic', 'USE_OPENSSL=1', 'USE_THREAD=1', 'USE_CPU_AFFINITY=1', 'USE_PROMEX=1'
```

As you can see, we are not disabling the splice flag. Could it be that any of the flags above are incompatible?

**Comment by IceCodeNew** [comment]
> Hi,
> 
> Thank you for raising this issue. We are currently compiling haproxy with these flags:
> 
> ```
> 'TARGET=generic', 'USE_OPENSSL=1', 'USE_THREAD=1', 'USE_CPU_AFFINITY=1', 'USE_PROMEX=1'
> ```
> 
> As you can see, we are not disabling the splice flag. Could it be that any of the flags above are incompatible?

I would say it is the `TARGET=generic` causing this problem.
If there is no good reason for specifying the TARGET, I would like to suggest you let make detect the proper target itself.
Or the arg `TARGET` could be set to `linux-glibc` or `linux-musl`. Since the repo `bitnami/haproxy` only provides images for `linux/amd64` now, such a change SGTM.

**Comment by IceCodeNew** [comment]
```
	makeOpts=' \
		TARGET=linux-musl \
		USE_GETADDRINFO=1 \
		USE_LUA=1 LUA_INC=/usr/include/lua5.3 LUA_LIB=/usr/lib/lua5.3 \
		USE_OPENSSL=1 \
		USE_PCRE2=1 USE_PCRE2_JIT=1 \
		USE_PROMEX=1 \
		\
		EXTRA_OBJS=" \
		" \
```

this will also fix #13890, as it turns on the Lua feature

**Comment by javsalgar** [comment]
Thank you for the input! I will forward this to the engineering team.

**Comment by CeliaGMqrz** [comment]
Hi @IceCodeNew,

Sorry for the delay. This [version](https://github.com/bitnami/containers/pull/27470) has just been released. The changes required to activate LINUX_SPLICE are already implemented. Your feedback is welcome!
