### ISSUE TITLE
[bitnami/wordpress] image doesn't support UNIX socket DB connection setup

### ISSUE THREAD

**Issue by czka** [bitnami/containers#20007]
### Name and Version

bitnami/wordpress:6.1.1

### What steps will reproduce the bug?

1. Create a Cloud SQL instance with a public IP, e.g. as described by Google at https://cloud.google.com/sql/docs/mysql/connect-run#command-line. The IP isn't going to be used (you will use a UNIX socket instead), but it's required just to be able to create the instance. A shared core 1 vCPU, 0.614 GB + 10G HDD will do (costs few cents a day, takes 15 minutes to spawn).

2. Enable the following APIs in your GCP project:
   - artifactregistry.googleapis.com
   - sqladmin.googleapis.com
   - run.googleapis.com
   - cloudbuild.googleapis.com

3. Run `docker pull bitnami/wordpress:latest` on your local machine.

4. Create a `Dockerfile` with a following 1 line of content, in an empty directory on your local machine:
   ```
   FROM bitnami/wordpress:latest
   ```

5. Deploy it to Cloud Run from that same directory, trying to use the Cloud SQL's UNIX socket exposed in the container's `/cloudsql/` directory:
   ```
   gcloud run deploy wp-1 --source . \
   --allow-unauthenticated \
   --add-cloudsql-instances <your Cloud SQL instance connection string> \
   --update-env-vars WORDPRESS_DATABASE_USER=root,\
   WORDPRESS_DATABASE_PASSWORD=<root's password>,\
   WORDPRESS_DATABASE_HOST=127.0.0.1:/cloudsql/<your Cloud SQL instance connection string>
   ```

6. Observe errors in your Cloud Run logs:
   ```
   Hostname 127.0.0.1:/cloudsql/<your Cloud SQL instance connection string> could not be resolved, this could lead to connection issues
   Trying to connect to the database server
   Could not connect to the database
   ```

To verify that the socket is indeed available in the container's `/cloudsql/` directory:

- Modify your Dockerfile created in step 4 above as follows:
  ```
  FROM bitnami/wordpress:latest
     
  ENTRYPOINT ["/opt/bitnami/mysql/bin/mysql"]
  CMD ["--user=root", "--password=<root's password>", "--socket=/cloudsql/<your Cloud SQL instance connection string>", "--execute=SHOW DATABASES;"]
  ```

- Deploy the modified image:
  ```
  gcloud run deploy wp-1 --source . \
  --allow-unauthenticated \
  --add-cloudsql-instances <your Cloud SQL instance connection string>
  ```

- In the Cloud Run logs observe a list of DBs, indicating the `mysql` command in the container was able to connect to Cloud SQL using the socket at `/cloudsql/<your Cloud SQL instance connection string>` - something like:
  ```
  Database
  information_schema
  mysql
  performance_schema
  sys
  ```

### What is the expected behavior?

I would expect that setting `WORDPRESS_DATABASE_HOST=127.0.0.1:<path to a socket>` at container's startup would configure WP to communicate with MySQL using the specified socket.

As per WP docs it should support sockets just fine:
- https://developer.wordpress.org/apis/wp-config-php/#set-database-host
- https://wordpress.org/support/article/how-to-install-wordpress/#step-3-set-up-wp-config-php

If `WORDPRESS_DATABASE_HOST` is not supposed to support socket connection strings please provide a variable dedicated for socket connectivity, e.g. `WORDPRESS_DATABASE_SOCKET`.

### What do you see instead?

When I set `WORDPRESS_DATABASE_HOST=127.0.0.1:<path to a socket>` at container startup I get the following errors in my Cloud Run logs:

```
Hostname 127.0.0.1:/cloudsql/<your Cloud SQL instance connection string> could not be resolved, this could lead to connection issues
Trying to connect to the database server
Could not connect to the database
```

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. This is the first time we get a use case like this, in principle it should be tweaking the container logic to allow this kind of connections, would you like to propose a PR in libwordpress.sh with the change?

**Comment by czka** [comment]
@javsalgar I should be able to. Do you have any implementation hints, besides starting in libwordpress.sh? The shell code here is few thousands lines long in ~40 files. I could use some guiding.

**Comment by javsalgar** [comment]
You may want to change the `wordpress_wait_for_mysql_connection` function adding the possibility to use sockets. Also, you will need to tweak the `wordpress_set_db_settings` function.

**Comment by czka** [comment]
@javsalgar I'm putting this on hold. It shows that the [vanilla Wordpress image](https://hub.docker.com/_/wordpress) supports socket DB connections without extra effort by [accepting any env var content it's passed](https://github.com/docker-library/wordpress/blob/master/latest/php8.0/apache/wp-config-docker.php#L59). I might get back to this ticket if any issues occur there.

**Comment by medvedev** [comment]
I face the similar issue trying to setup Bitnami Wordpress on Google Cloud Run + Google Cloud SQL.
@czka  did you manage to find some kind of workaround?

**Comment by czka** [comment]
@medvedev I have used the official WordPress image instead: https://github.com/bitnami/containers/issues/20007#issuecomment-1396659483
