### ISSUE TITLE
[bitnami/wordpress] Fails during wordpress setup in Galera Cluster

### ISSUE THREAD

**Issue by EmilianoBruni** [bitnami/containers#20004]
### Name and Version

bitnami/wordpress:6

### What steps will reproduce the bug?

In Galera Cluster, auto_increment columns increase by a greater amount than 1. So your wordpress setup script fails here

```
+ cmd=('/opt/bitnami/php/bin/php' '/opt/bitnami/wp-cli/bin/wp-cli.phar' 'user' 'meta' 'set' '1' 'first_name' 'UserName')
+ local -a cmd
+ local -a wp_extra_cli_flags
+ read -r -a wp_extra_cli_flags
+ [[ 0 -gt 0 ]]
+ am_i_root
++ id -u
+ [[ 0 = \0 ]]
+ true
+ gosu daemon env WP_CLI_CONFIG_PATH=/opt/bitnami/wp-cli/conf/wp-cli.yml WP_CLI_CACHE_DIR=/dev/null /opt/bitnami/php/bin/php /opt/bitnami/wp-cli/bin/wp-cli.phar user meta set 1 first_name UserName
Error: Invalid user ID, email or login: '1'
```

because the setup script supposes that the first user have id:1 but this id is an auto_increment in wp_users and so, in galera, can be  2,3,4,... (2 or 3 in my env where the cluster has three nodes). 

I temporary patched it by manually update user id in wp_users, wp_usermeta, wp_posts setting it to 1 and reload the setup script.

### What is the expected behavior?

.

### What do you see instead?

.

**Comment by javsalgar** [comment]
Hi!

Could you share the patch that you applied? This should help us in order to find a workaround in this kind of installations.

**Comment by EmilianoBruni** [comment]
The "patch" was to update all wrong user id in tables to 1 with these SQL queries

`UPDATE wp_users SET ID= 1`
`UPDATE wp_usermeta SET user_id= 1`
`UPDATE wp_posts SET post_author= 1`

**Comment by javsalgar** [comment]
Thank you! Would you like to submit a PR adding that logic in the `wordpress_initialize` function? If not we will work on it but we cannot guarantee an ETA.
