### ISSUE TITLE
[Drupal docker image] Extra database for accessing non-Drupal data

### ISSUE THREAD

**Issue by LeoVe** [bitnami/containers#20012]
### Name and Version

bitnami/docker/9.4.9

### What steps will reproduce the bug?

We have the latest Drupal docker image (Drupal 9.4.9) running, works great.

But, if we add a database in databases[] in settings.php though, Drupal won't startup after stopping with error: "ERROR ==> Could not connect to the database".

As it turned out after testing, Drupal won't start again after any setup changes to the array databases[].

The same changes were tested and do work in other installations that not make use of the Bitname Drupal Docker image.

Could anyone shine a light on what could be the matter or how to find the solution/work-around?

Thanks !

### What is the expected behavior?

We would expect to be able to access the external data and incorporate it in pages.

### What do you see instead?

Drupal won't restart after shut-down. 
It works OK if you update the settings.php and keep the container running, but the container won't restart after shutdown.

 "ERROR ==> Could not connect to the database"

### Additional information

Any changes to the settings.php databases[] seem to have the effect of not being able to restart the container.

This is tested on both a Synology NAS and a QNAP NAS.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
