### ISSUE TITLE
[bitnami/postgresql-repmgr] Runnin postgress HA across two K8s cluster across GeO

### ISSUE THREAD

**Issue by rajeshjose** [bitnami/containers#20074]
### Name and Version

bitnami/postgresql-repmgr:15

### What is the problem this feature will solve?

Usecase:
We have a geo reduntant deployment where we have one K8s cluster running in primary site and a seperate cluster on standby site. 

- We want the postgress in primary site and standby site to pair up and replicate
- We also want the fail-over/switch-over to be controlled by our fail over process rather than the repmgr automatically deciding

We took the bitnami/postgresql-repmgr image and created a custom image (FROM bitnami/postgresql-repmgr:xx) with one modification to change the failover settings from  "automatic" to "manual" in the repmg configuration file.

However, we are stuck with another problem: In "librepmgr.sh", there is a check that "$REPMGR_NODE_NAME" should match the expression ^.*+-[0-9]+$. I presume this check is assuming that the deployment is a statefulset an will have an odinal number at the end of the node name. Since we are deploying it across two clusters, we are connecting the two nodes using either ingress or host IP (deployed using hostNetwork) where we have some constraints in giving an "-xx" at the end of it.

We also tried giving the pod name for REPMGR_NODE_NAME (eg: pg-0) and then explicitly secifying "REPMGR_NODE_ID". Now it fails wit error "[ERROR] repmgr extension not found on this node". I presume this is because the node is not listed in "REPMGR_PARTNER_NODES" because there we have to use the ingress/host-ip.

My question is, can one of the following be done? 

- If "REPMGR_NODE_ID" is specfied, don't check for "$REPMGR_NODE_NAME" == ^.*+-[0-9]+$
- "REPMGR_NODE_NETWORK_NAME" be used for checking against "REPMGR_PARTNER_NODES" and "REPMGR_PRIMARY_HOST" to validate the cluster membership insteda of "$REPMGR_NODE_NAME"

### What is the feature you are proposing to solve the problem?

Sync between two postgress in a geo reduntant deployment where we have one K8s cluster running in primary site and a seperate cluster on standby site. 

### What alternatives have you considered?

Alternate approach-1: 
- https://www.crunchydata.com/blog/streaming-replication-across-kubernetes-postgres-clusters
- Still being experimented

Alternate approach-2: 
- https://cloud.google.com/architecture/architectures-high-availability-postgresql-clusters-compute-engine
- Not stuitable for on-premise deployment

Alternate approach-3: 
- Backup and restore. 
- This approach does not meet out RTO objectives

**Comment by javsalgar** [comment]
Hi,

Thanks for sharing your use case. It seems that you want to propose a change in the container logic. It would make sense to open a PR and start a discussion based on the changes in the logic that would fit your use case without breaking the standard cases.

**Comment by javsalgar** [comment]
Thank you so much!
