### ISSUE TITLE
Sonarqube: It's not possible to select the Developer Edition 

### ISSUE THREAD

**Issue by rowi1de** [bitnami/containers#2015]
### Name and Version

docker.io/bitnami/sonarqube:9.4.0-debian-10-r20

### What steps will reproduce the bug?

I deploy via the bitnami helm chart: 
- https://github.com/bitnami/charts/tree/master/bitnami/sonarqube
- https://github.com/bitnami/charts/issues/11595

### What is the expected behavior?

- There should be an image that supports the sonbarqube developer edition like the official chart: https://hub.docker.com/_/sonarqube?tab=tags

### What do you see instead?

- Only the Community Edition is supported, which is not useful as it lacks basic features like Pull Request integration

**Comment by carrodher** [comment]
In order to avoid duplications, I'm closing this ticket in favor of https://github.com/bitnami/charts/issues/11595
