### ISSUE TITLE
Mac M1 cheap unable to start ETCD 

### ISSUE THREAD

**Issue by shyandsy** [bitnami/containers#20252]
### Name and Version

bitnami/etcd:latest

### What steps will reproduce the bug?

1. pull moodle image
2. running the container
3. after ** Starting ETCD **
4. container exit

### What is the expected behavior?

start success

### What do you see instead?

[+] Running 0/0
 ⠿ Container gonivinck-etcd-1                                                                                                              [+] Running 0/2rting 0.1s
 ⠿ Container gonivinck-etcd-1                                                                                                              [+] Running 1/2rting 0.2s
 ⠿ Container gonivinck-etcd-1                                                                                                                          Started 0.2s
 ⠹ etcd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s

### Additional information

base on the info from github etcd, mac m1 has been supported from V3.5.5
> https://github.com/etcd-io/etcd/issues/14001

<img width="767" alt="image" src="https://user-images.githubusercontent.com/5271457/212482483-e26c68dd-3938-4396-96b8-c7a88a61e2e8.png">

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
