### ISSUE TITLE
[bitnami/zookeeper] Cannot effectively use `(Initial|Min|Max)RAMPercentage` cgrups aware java args in zookeeper container

### ISSUE THREAD

**Issue by kchaber** [bitnami/containers#20542]
### Name and Version

bitnami/zookeeper:latest (3.8-debian-11)

### What steps will reproduce the bug?

We cannot effectively use `(Initial|Min|Max)RAMPercentage` java arguments as zookeeper container always requires and adds fixed heap size via `-Xmx`, `-Xms` arguments.

The validation is done in the below function inside `scripts/libzookeeper.sh`:
```shell
zookeeper_configure_heap_size() {
    local -r heap_size="${1:?heap_size is required}"

    if [[ "$JVMFLAGS" =~ -Xm[xs].*-Xm[xs] ]]; then
        debug "Using specified values (JVMFLAGS=${JVMFLAGS})"
    else
        debug "Setting '-Xmx${heap_size}m -Xms${heap_size}m' heap options..."
        zookeeper_export_jvmflags "-Xmx${heap_size}m -Xms${heap_size}m"
    fi
}
```

### What is the expected behavior?

Zookeeper container should not require the `Xmx`, `Xms` arguments to be provided in `JVMFLAGS` env variable. 

### What do you see instead?

`(Initial|Min|Max)RAMPercentage` should be used instead to dynamically allocate heap size based on container `cgrups` settings.

**Comment by Mauraza** [comment]
Hi @kchaber,

We are always open to a contribution, if you want you can create a PR with a change and we will be more than happy to review it

**Comment by OneCricketeer** [comment]
Depending on the JRE that's used, it should respect `JAVA_TOOL_OPTIONS` environment variable for arbitrary settings

**Comment by Mauraza** [comment]
Thanks @OneCricketeer for the comment, if @kchaber makes the contribution he should take it into account.

**Comment by jrsherry** [comment]
Why was this issue closed?  Seems that it's still a concern.
