### ISSUE TITLE
Unable to configure dynamic module memberof.la in bitnami/openldap

### ISSUE THREAD

**Issue by KremlinGhost** [bitnami/containers#20571]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

1. I use this .env in the image:
```yaml
- LDAP_ROOT=dc=example,dc=com
- LDAP_ADMIN_USERNAME=admin
- LDAP_ADMIN_PASSWORD=admin
- LDAP_PORT_NUMBER=1389
- LDAP_LDAPS_PORT_NUMBER=1636
- LDAP_SKIP_DEFAULT_TREE=no
- LDAP_CONFIG_ADMIN_ENABLED=yes
- LDAP_CONFIG_ADMIN_USERNAME=config
- LDAP_CONFIG_ADMIN_PASSWORD=config
- LDAP_EXTRA_SCHEMAS=cosine, inetorgperson, nis, misc, openldap
- LDAP_USERS=pols
- LDAP_PASSWORDS=pols
- LDAP_ENABLE_TLS=yes
- BITNAMI_DEBUG=true
- LDAP_LOG_LEVEL=9
```
3.  Then I try to add dynamic module with this ldif file:
```
dn: cn=module,cn=config
objectClass: olcModuleList
cn: module
olcModulePath: /usr/lib/ldap
olcModuleLoad: back_mdb.la
```
_olcModulePath: /usr/lib/ldap_ not exist in the container, but ldapmodify with this .ldif file corectly executed.
4. Then I try to add another module, memberof.la with this .ldif file:
```
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: memberof.la
```
with command:
`ldapmodify -D "cn=config,cn=config" -w "config" -f ./module.ldif`
and see this error:
```
modifying entry "cn=module{0},cn=config"
ldap_modify: Other (e.g., implementation specific) error (80)
        additional info: <olcModuleLoad> handler exited with 1
```
After more researching i try to use ldapadd with this .ldif on the clear base:
```
dn: cn=module,cn=config
cn: module
objectClass: olcModuleList
olcModuleLoad: memberof
olcModulePath: /usr/lib/ldap

dn: olcOverlay={0}memberof,olcDatabase={2}mdb,cn=config
objectClass: olcConfig
objectClass: olcMemberOf
objectClass: olcOverlayConfig
objectClass: top
olcOverlay: memberof
olcMemberOfDangling: ignore
olcMemberOfRefInt: TRUE
olcMemberOfGroupOC: groupOfNames
olcMemberOfMemberAD: member
olcMemberOfMemberOfAD: memberOf
```
and get the same error.
[Here](https://serverfault.com/a/357018) I found solution in reinstalling openldap, but it's useless for a docker I suppose.
Then I try to install openldap on a local machine and mount directory /usr/lib/ldap with the necessary .la files, but it didn't work

### What is the expected behavior?

I want to add dynamic module memberof.la in order to use memberOf attribute

### What do you see instead?

```
modifying entry "cn=module{0},cn=config"
ldap_modify: Other (e.g., implementation specific) error (80)
        additional info: <olcModuleLoad> handler exited with 1
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami OpenLDAP container image or Helm chart but about how the application or environment is being used/configured. It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
