### ISSUE TITLE
Ghost "mail.options.secure" property instead of "mail.options.secureConnection"

### ISSUE THREAD

**Issue by zaycker** [bitnami/containers#20872]
### Name and Version

bitnami/ghost:5.30.1

### What steps will reproduce the bug?

1. Check documentation of Ghost [here](https://ghost.org/docs/config/#mail)
2. It uses `secure` property to define secured connection for SMTP setup

### What is the expected behavior?

Configuration is consistent with tool documentation

### What do you see instead?

Bitnami generates property `secureConnection` which is not by Ghost documentation

### Additional information

I tried to dive deeper into [smtp-connection](https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/index.js#L55) which is used by Ghost. It uses `secure` property from the constructor arguments but stores it in the instance property called `secureConnection`. Not sure honestly, maybe Ghost can do reassignments later to save compatibility with previous `secureConnection` naming. But documentation contains `secure`.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
