### ISSUE TITLE
GHOST_EMAIL is used for "mail.from" instead of checking GHOST_SMTP_FROM_ADDRESS

### ISSUE THREAD

**Issue by zaycker** [bitnami/containers#20871]
### Name and Version

bitnami/ghost:5.30.1

### What steps will reproduce the bug?

1. Define `GHOST_SMTP_FROM_ADDRESS` as "noreply@example.com" but `GHOST_EMAIL` as "real_user@example.com"
2. Check config.production.json

### What is the expected behavior?

`GHOST_SMTP_FROM_ADDRESS` should be used instead of `GHOST_EMAIL` for `mail.from` setting if exists. Some mailers are critically require an equality of `mail.from` and `mail.options.auth.user` fields.

### What do you see instead?

`GHOST_SMTP_FROM_ADDRESS` is not used

### Additional information

See [here](https://github.com/bitnami/containers/blob/main/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/libghost.sh#L310) the according code

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
