### ISSUE TITLE
Ghost example of adding Storage Adapter for S3 in the documentation doesn't work

### ISSUE THREAD

**Issue by zaycker** [bitnami/containers#20873]
### Name and Version

bitnami/ghost:5.30.1

### What steps will reproduce the bug?

1. Create new image based on bitnami/ghost with adding S3 adapter by the example in the bottom part of [README.md](https://github.com/bitnami/containers/tree/main/bitnami/ghost#customize-this-image)
2. Try to start container with appropriate properties

### What is the expected behavior?

Container successfully started, S3 works

### What do you see instead?

Container shutdowns after a message
```
- Inspecting operating system
````

### Additional information

Critical part here
```
RUN cd /bitnami/ghost \
    && npm i --silent ghost-storage-adapter-s3 \
    && mkdir -p /opt/bitnami/ghost/content/adapters/storage/s3 \
    && cp -r ./node_modules/ghost-storage-adapter-s3/* /opt/bitnami/ghost/content/adapters/storage/s3/
```

`npm i` creates `node_modules` with `ghost-storage-adapter-s3` alongside with necessary dependencies for it. At least it needs `aws-sdk`. Then we copy only the content of the module but dependencies are gone by the new location.
for me it helped to add there additional row, but not sure it is the best solution. Something like that:
```
RUN cd /bitnami/ghost
RUN yarn add --silent ghost-storage-adapter-s3
RUN mkdir -p /opt/bitnami/ghost/content/adapters/storage/s3
RUN cp -r ./node_modules/ghost-storage-adapter-s3/* /opt/bitnami/ghost/content/adapters/storage/s3/
RUN cd /opt/bitnami/ghost/content/adapters/storage/s3/ && yarn install --production
```

and now it works but probably contains some amount of excess libraries (actually there is not a lot)

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by derek-adair** [comment]
> ```
> RUN cd /bitnami/ghost
> RUN yarn add --silent ghost-storage-adapter-s3
> RUN mkdir -p /opt/bitnami/ghost/content/adapters/storage/s3
> RUN cp -r ./node_modules/ghost-storage-adapter-s3/* /opt/bitnami/ghost/content/adapters/storage/s3/
> RUN cd /opt/bitnami/ghost/content/adapters/storage/s3/ && yarn install --production
> ```

@zaycker This is the way to do this.  You should 100% submit this as a PR change to the docs.
