### ISSUE TITLE
Log retention

### ISSUE THREAD

**Issue by AdewuyiOyawoye** [bitnami/containers#20879]
### Name and Version

[bitnami/airflow] Release 2.4.2-debian-11-r0

### What steps will reproduce the bug?

Hi I was wondering if there's a way to change the "log_retention_days" and "log_retention_clean_dags" settings for bitnami airflow, and do you know what the default values for this are?

### What do you see instead?

change the "log_retention_days" and "log_retention_clean_dags" settings for bitnami airflow

**Comment by dgomezleon** [comment]
Hello @AdewuyiOyawoye ,

Could you point us to that options? I can only find `log_retention_days` in [this Dockerfile](https://github.com/a0x8o/airflow/blob/master/Dockerfile).

I think you may find [`logrotate` documentation](https://linux.die.net/man/8/logrotate) interesting for your purpose.

Note that in a container/k8s environment storing the logs in the containers is highly discouraged. Instead, a system to collect/aggregate the logs from every container in the cluster is highly recommended. We have a [tutorial](https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/) where we talk broadly about this topic.

I hope it helps
