### ISSUE TITLE
Laravel Container CHMOD Error

### ISSUE THREAD

**Issue by HeroesLament** [bitnami/containers#2092]
### Name and Version

bitnami/laravel:9.3.2

### What steps will reproduce the bug?

1. Run our laravel project's Containerfile
2. Pull laravel:9.3.2
3. Run all of our laravel bootstrapping and dependency pulls
4. `podman run myprojectname`

### What is the expected behavior?

Container should start cleanly. 

### What do you see instead?
```
laravel 13:53:49.64 
laravel 13:53:49.64 Welcome to the Bitnami laravel container
laravel 13:53:49.64 Subscribe to project updates by watching https://github.com/bitnami/containers
laravel 13:53:49.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
laravel 13:53:49.64 
laravel 13:53:49.64 INFO  ==> ** Running Laravel setup **
laravel 13:53:49.69 INFO  ==> Configuring PHP options
laravel 13:53:49.69 INFO  ==> Setting PHP opcache.enable option
laravel 13:53:49.70 INFO  ==> Setting PHP expose_php option
chmod: changing permissions of '/proc/self/fd/1': Permission denied
chmod: changing permissions of '/proc/self/fd/2': Permission denied
```

### Additional information

I can run this container with `podman run --privileged myprojectname`, but this should not require running the container itself as root. Any thoughts on how to best handle this?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-laravel#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
