### ISSUE TITLE
IPv6 support for Keycloak

### ISSUE THREAD

**Issue by luker31337** [bitnami/containers#21223]
### Name and Version

bitnami/keycloak:20.0.3

### What is the problem this feature will solve?

Not able to use IPv6 address as part of the container. https://github.com/bitnami/containers/blob/9f20db31e1e6037dd2dadd15c503069b7327f15d/bitnami/keycloak/20/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L73

### What is the feature you are proposing to solve the problem?

Add IPv6 validation or remove this IPv4 validation from the bitnami/keycloak environment variable checks. Keycloak support IPv6.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
