### ISSUE TITLE
Please provider an alternative docker registry for your containers, ideally one that does have such dumb rate limits

### ISSUE THREAD

**Issue by onedr0p** [bitnami/containers#21233]
### Name and Version

All Images

### What is the problem this feature will solve?

Hi 👋🏼 Pushing to an alternate registry will improve user experience by image pulls not being rate limited by Dockerhub.

### What is the feature you are proposing to solve the problem?

Push to an alternative docker registry, like Quay, GHCR, or ECR.

**Comment by carrodher** [comment]
Thanks for the suggestion, at this moment we are not considering pushing the container images in other registries, please note Bitnami is part of the [Docker Verified Publisher Program](https://docs.docker.com/docker-hub/publish/), one of the advantages is the removal of rate limiting for developers

**Comment by onedr0p** [comment]
> one of the advantages is the removal of rate limiting for developers

Does that mean for users signed into dockerhub that are part of the bitnami team? That wording isn't very clear.

**Comment by carrodher** [comment]
No, it is not needed to belong to the Bitnami team. All the images stored under the Bitnami organization are exempt from any rate limit

**Comment by onedr0p** [comment]
That's for confirming

**Comment by viceice** [comment]
- https://github.com/docker/hub-feedback/issues/2421
😕
