### ISSUE TITLE
[bitnami/harbor-registry] Where is registry binary repo?

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/containers#21503]
### Name and Version

bitnami/harbor-registry

### What is the problem this feature will solve?

Question: I see the binary for harbor-registry is taken from https://downloads.bitnami.com/files/stacksmith/ which contains a prebuilt binary but I could not find a source code for it. The story is: I'm very interested in applying this patch: https://github.com/distribution/distribution/pull/3589 to distribution project and I bet you use some fork (maybe original) of this repo. Please clarify how and where this binary is built.

**Comment by carrodher** [comment]
We obtain the source code or already compiled binaries for the different components from the upstream projects, in this case from https://github.com/goharbor/harbor.
We track this repository and when a new version appears there our automated test & release pipeline detects it and generates a new version on our side.

The `https://downloads.bitnami.com/files/stacksmith/` is just an intermediate storage where we put some intermediate assets used by the container images.

I recommend you send a PR to the upstream project to be included in future versions of the application

**Comment by Antiarchitect** [comment]
Thank you for clarification @carrodher!
