### ISSUE TITLE
OpenLDAP Replication Support

### ISSUE THREAD

**Issue by robigan** [bitnami/containers#21511]
### Name and Version

bitnami/openldap:2

### What is the problem this feature will solve?

Ability to replicate, either via master-slave or master-master replication schemes, between ldap servers.

Current issue that occurs when setting up the syncprov module manually is the run.sh script for this image doesn't pass the hostname properly to slapd, resulting in no matching serverIDs to be found and slapd refusing to start.

### What is the feature you are proposing to solve the problem?

Integration of replication through the use of environment variables like osixia/openldap does.

### What alternatives have you considered?

Passing the right hostname paramater to slapd based on HOSTNAME variable so that slapd will pick the right serverID when manually setting up the syncprov module.

**Comment by robigan** [comment]
Hmm, I am full of work this week, so I might in due time if I can find some time.

**Comment by zerowebcorp** [comment]
Is there a plan to add replication support? Not everyone is aware of how to extend the image and add this and submit a PR fyi

**Comment by carrodher** [comment]
Currently, we're working on other stuff with more priority; given the number of assets we are maintaining it's going to be difficult to consider it in the short/mid-term. That's why we encourage users to contribute with this kind of new features
