### ISSUE TITLE
Error on installing Dokuwiki

### ISSUE THREAD

**Issue by oschihin** [bitnami/containers#21796]
### Name and Version

bitnami/Dokuwiki:latest (is)  bitnami/dokuwiki:20220731.1.0-debian-11-r48

### What steps will reproduce the bug?

* OS: Ubuntu Server 20.04.5 LTS
* Docker version 20.10.23

```bash
$ docker run bitnami/dokuwiki
Unable to find image 'bitnami/dokuwiki:latest' locally
latest: Pulling from bitnami/dokuwiki
dfe669f82390: Pull complete
6587c57171b8: Pull complete
Digest: sha256:5b8331337e855d32e6a46b4ca3393cec976a2039d76eeaf2d22d41fcd5712948
Status: Downloaded newer image for bitnami/dokuwiki:latest
dokuwiki 08:26:51.15
dokuwiki 08:26:51.16 Welcome to the Bitnami dokuwiki container
dokuwiki 08:26:51.16 Subscribe to project updates by watching https://github.com/bitnami/containers
dokuwiki 08:26:51.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
dokuwiki 08:26:51.16
dokuwiki 08:26:51.16 INFO  ==> ** Starting DokuWiki setup **
realpath: /bitnami/apache/conf: No such file or directory
dokuwiki 08:26:51.18 INFO  ==> Configuring Apache ServerTokens directive
dokuwiki 08:26:51.19 INFO  ==> Configuring PHP options
dokuwiki 08:26:51.20 INFO  ==> Setting PHP expose_php option
dokuwiki 08:26:51.26 INFO  ==> Configuring file permissions for DokuWiki
dokuwiki 08:26:51.26 INFO  ==> Starting apache in background
[Wed Jan 25 08:26:51.331156 2023] [ssl:warn] [pid 69] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 25 08:26:51.331580 2023] [ssl:warn] [pid 69] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki 08:26:56.36 INFO  ==> apache started
dokuwiki 08:28:11.43 ERROR ==> An error occurred while installing DokuWiki
```

### What is the expected behavior?

Successfull install

### What do you see instead?

It seems Apache cannot start or aborts, but I do not see any more precise error messages.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/dokuwiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
