### ISSUE TITLE
[bitnami/wordpress] Add a way to launch WordPress from subfolder via ALB

### ISSUE THREAD

**Issue by bohdan-shulha** [bitnami/containers#21803]
### Name and Version

bitnami/wordpress:*

### What is the problem this feature will solve?

We need to have the WordPress to be accessible via /blog URI.

Our website is served by an AWS ALB, so routing all requests from /blog to WP installation was the easiest part.

However, it is not all things that one have to do to get the working blog, WP Admin and loadable assets.

### What is the feature you are proposing to solve the problem?

- Add a way to set the WP_HOME and WP_SITEURL constants or the `/` (trailing slash part)
```
define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/' . $configuredSubfolder);
define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/' . $configuredSubfolder);
```
- Put following rules into apache config:
```
RewriteEngine on
RewriteRule "^/$configuredSubfolder(.*)" "$1" [PT]
```

**Comment by javsalgar** [comment]
Hi,

The WordPress container has support for mounting your own configuration, as well as using init scripts to modify the configuration in `/docker-entrypoint-init.d`, as you can see in this script: https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/rootfs/post-init.sh

 Did you try any of these features?

**Comment by bohdan-shulha** [comment]
Hi @javsalgar ,

Nope, I didn't. Probably, I'll try the post-init later and it seems that custom script would work (this time I've done it half-manually). Thank you for bringing my attention to this feature.

But is it such a rare case that it is not (will not be) a simple configuration parameter for a container itself, like a dozen of different flags?

**Comment by javsalgar** [comment]
Hi,

In this sense we try to be conservative in the features because it has its maintenance challenges in both container and chart. If this is a feature that is desired by a substantial amount of users, then we could consider it. In addition to this, contributions are welcome, in case you want to participate with a PR.

**Comment by madkep** [comment]
hello @bohdan-shulha , were you able to make the post init script? i am looking to make the same configuration on my wordpress server.

**Comment by bohdan-shulha** [comment]
Hi @madkep ,

Not yet, I haven't tried it at all.

@javsalgar , thanks for your answers. Unfortunately, I don't have enough time now to contribute back to community. I hope it will happen one day.
