### ISSUE TITLE
[bitnami/keycloak] Oracle database support for bitnami/keycloak

### ISSUE THREAD

**Issue by revendex** [bitnami/containers#21897]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

You're writing explicitly the following in your README:

_The Bitnami Keycloak container requires a PostgreSQL database to work._

What does it mean exactly? It means, I can run your keycloak container only with a PostgreSQL database and with an Oracle database it's not working?

Many thanks for your feedback.

Best Regards,
Marco

### What is the feature you are proposing to solve the problem?

Support for Oracle database.

**Comment by revendex** [comment]
I had with Keycloak 16.1.1 from another docker-image-provider the following path:

`/opt/keycloak/modules/system/layers/base/com/oracle/jdbc/main/driver`

and there I could put a jar-file "ojdbc.jar" from Oracle, to be able to connect with Keycloak to an Oracle database.

It seems it doesn't work anymore, right?

**Comment by revendex** [comment]
In addition, I also needed to set the following environment variable with the old Keycloak 16.1.1 docker-container-image:

`DB_VENDOR: ORACLE`

**Comment by javsalgar** [comment]
Hi,

In this sense, we have automations configured for PostgreSQL. Oracle support is not something that we have support in our bash scripts or tested in our pipelines. However, contributions are welcome, so feel free to submit a PR with the changes that the container would need in order to support this database.

**Comment by dgomezleon** [comment]
Hello @m4rcoschmucki ,

The first 2 steps should be explained in the README.md, and pointing to [this section](https://github.com/bitnami/containers/tree/main/bitnami/keycloak#initializing-a-new-instance)

The 3rd one looks good to me. You only would need to add this in `keycloak-env.sh`:

```
export KEYCLOAK_DATABASE_VENDOR="${KEYCLOAK_DATABASE_VENDOR:-postgresql}"
```

I would use KEYCLOAK_DATABASE_TYPE instead (as Moodle does).

I think with that you can go ahead with a PR.

Thanks
