### ISSUE TITLE
[opencart4] https login redirect to http

### ISSUE THREAD

**Issue by john-yan** [bitnami/containers#22114]
### Name and Version

bitnami/opencart:4.0.1-1-debian-11-r40

### What steps will reproduce the bug?

1. How to reproduce the environment: `helm upgrade --install --create-namespace -n opencart opencart bitnami/opencart --set service.type=ClusterIP,opencartHost=opencart.example.com,image.debug=true,opencartEnableHttps=true`
2. Note: the instance is hosted behind a reversed proxy with SSL configured on the reversed proxy.
3. go to `https://opencart.sauraca.com/administration/` on browser and login with user/pass
4. check the response of the POST request.

### What is the expected behavior?

 the json response should be this: 
```json
{"redirect":"https:\/\/opencart.example.com\/administration\/index.php?route=common\/dashboard&user_token=29ce87673b0e07831acc5eb15e0f898f"}
```

### What do you see instead?

 the json response is:
```json
{"redirect":"http:\/\/opencart.example.com\/administration\/index.php?route=common\/dashboard&user_token=29ce87673b0e07831acc5eb15e0f898f"}
```

### Additional information

Therefore, it won't work if http is block on firewall. Also, it's not secure to send http request with user_token.

Root cause:
HTTP_SERVER is used to define `$_['site_url']` in `/opt/bitnami/opencart/system/config/admin.php`. If replace HTTP_SERVER as HTTPS_SERVER, the redirect link is fixed to https. There are a few other places with similar issues: 
```sh
/opt/bitnami/opencart/system/config/catalog.php
/opt/bitnami/opencart/system/config/install.php
/opt/bitnami/opencart/system/config/admin.php
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/opencart#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
