### ISSUE TITLE
Don't --force mysql_upgrade on MariaDB

### ISSUE THREAD

**Issue by grooverdan** [bitnami/containers#22193]
### Name and Version

bitnami/mariadb:10.10 (and all others)

### What steps will reproduce the bug?

1. start mariadb:10.10 after already upgraded
2. mysql_upgrade is run with --force despite no upgrade needed

### What is the expected behavior?

mysql_upgrade run without force so that it didn't check every table.

### What do you see instead?

its checking every table.

### Additional information

Its set here: https://github.com/bitnami/containers/blob/main/bitnami/mariadb/10.10/debian-11/rootfs/opt/bitnami/scripts/libmariadb.sh#L768

It was removed on purpose - https://github.com/bitnami/containers/tree/main/bitnami/mariadb#10241-debian-10-r12-10332-debian-10-r13-10422-debian-10-r13-10513-debian-10-r14-and-1065-debian-10-r13

This was also described [upstream in MDEV-27060](https://jira.mariadb.org/browse/MDEV-27060).

If you've got a private historical record refer to the discussion on https://github.com/bitnami/bitnami-docker-mariadb/issues/252.

So its regressed.

**Comment by jotamartos** [comment]
Hi @grooverdan,

Thank you for reporting this issue. It seems we accidentally recovered the `--force` flag just after removing it. I'll create a task on our side to investigate this and update the code to not to run the upgrade with the force option. 

https://github.com/bitnami/containers/commit/425727c99863d2384a740039bc50b322f884c804
https://github.com/bitnami/containers/commit/9e8ec214180157bdfd197254c8a0d22229b8c439

Sorry for the inconvenience.

**Comment by grooverdan** [comment]
Hi, what's the on-hold for? I [noticed wasn't fixed](https://github.com/bitnami/containers/blob/main/bitnami/mariadb/10.10/debian-11/rootfs/opt/bitnami/scripts/libmariadb.sh#L768) in the latest release.

**Comment by corico44** [comment]
Hello @grooverdan. We are working on it. We will notify you when this issue has been fixed!

**Comment by grooverdan** [comment]
Fixed 7b9645a33a710602f2c4d728399c22e377a1bc6c and others
