### ISSUE TITLE
Add image tags with another linux distro base (alpine)

### ISSUE THREAD

**Issue by pryhodkin** [bitnami/containers#22207]
### Name and Version

bitnami/mongodb
bitnami/rabbitmq
bitnami/redis

### What is the problem this feature will solve?

Hi bitnami-containers team,

The debian-based images have many vulnerabilities and for some business organizations, it is an important policy to don't have vulnerabilities in their services.
It would be pretty good if you could add the tags with images to the registry with alpine Linux based images.
Could you, please, consider this possibility of improvement?

Thank you,
Yaroslav

**Comment by carrodher** [comment]
Hi, the Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a **custom container and Helm Charts catalog based on the desired base image** (generic distros such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by wkoot** [comment]
> custom container and Helm Charts catalog based on the desired base image

But this is not published to dockerhub and would not provide a solution for docker based deploys. Scanning the containers which are currently published to dockerhub for vulnerabilities, with a tool such as Trivy (or Anchore), will report many issues.
