### ISSUE TITLE
Upgrade Discourse to version 3.0.1

### ISSUE THREAD

**Issue by obeyler** [bitnami/containers#22208]
### Name and Version

bitnami/discourse

### What is the problem this feature will solve?

The current main release is now 3.0.1 it offers several new functionality
https://meta.discourse.org/t/discourse-3-0-is-here/251372

### What is the feature you are proposing to solve the problem?

Adapt build container script to use this version instead of 2.8.13 
My main trouble to make a PR for this: the Dockerfile tries to upload a component from https://downloads.bitnami.com/files/stacksmith/ and I don't know how to provide or build the new "discourse-3.0.1.0-linux-amd64-debian-11.tar.gz" on it.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by gongomgra** [comment]
Hi @obeyler,

Just a quick note to let you know that we have released a container for [Discourse 3.0.1](https://github.com/bitnami/containers/tree/main/bitnami/discourse/3/debian-11).

You can also pull it from `docker.io` registry

```
docker pull docker.io/bitnami/discourse:3
```

**Comment by obeyler** [comment]
Thanks a lot !
