### ISSUE TITLE
Permission denied in /opt/bitnami/apache/htdocs (setup.sh#L43)

### ISSUE THREAD

**Issue by ibexa-yuna** [bitnami/containers#22205]
### Name and Version

bitnami/apache:2.4

### What steps will reproduce the bug?

1. Using bitnami/apache:2.4 as a FROM image
build new docker image using the following Dockerfile

```dockerfile
FROM bitnami/apache:2.4

COPY GUI/dist/ /app
```

2. Run this image
3. Observe the permission denied error
4. Repeat with `2.4.55-debian-11-r4` (previous one as of this moment)

### What is the expected behavior?

Image setups and starts apache serving my static content.

### What do you see instead?

Permission denied error in the container.

### Additional information

Running in K8s and Rancher Desktop (local environment)

**Comment by ibexa-yuna** [comment]
<img width="1904" alt="Screenshot 2023-01-30 at 07 49 27" src="https://user-images.githubusercontent.com/67897517/215452370-844c1a12-6cd9-4dd1-a959-4c1c729b2996.png">

**Comment by MirKml** [comment]
Same here, its problem, no of our new built apps can start because of this error.
We have simple app based on this docker image, only with /vhosts according documentation, nothing more

But it crashes immediately
```
apache 11:36:37.13
apache 11:36:37.13 Welcome to the Bitnami apache container
apache 11:36:37.13 Subscribe to project updates by watching https://github.com/bitnami/containers
apache 11:36:37.14 Submit issues and feature requests at https://github.com/bitnami/containers/issues
apache 11:36:37.14
apache 11:36:37.14 INFO ==> ** Starting Apache setup **
apache 11:36:37.17 INFO ==> Found mounted virtual hosts in '/vhosts'. Copying them to '/opt/bitnami/apache/conf/vhosts'
apache 11:36:37.19 INFO ==> Mounting application files from '/app'
rm: cannot remove '/opt/bitnami/apache/htdocs': Permission denied
```
 How can we e.g. switch to older docker image as temporary workaround?

**Comment by MirKml** [comment]
previous one works - docker tag  2.4.55-debian-11-r4
It seems as permissions issue on upstream or ...

**Comment by MirKml** [comment]
Maybe related to #21905? Scripts and permissions principles are mostly same for all bitnami containers.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Please note there is an already in-progress issue related to this topic at https://github.com/bitnami/containers/issues/22226.

In order to funnel the conversations in a single place, we will continue in that one closing the rest as duplicates.
