### ISSUE TITLE
Drupal 9: adding contrib and custom modules to bitnami/drupal via extending image

### ISSUE THREAD

**Issue by wdt-dh** [bitnami/containers#22436]
### Name and Version

bitnami/drupal:latest

### What steps will reproduce the bug?

My team manages over 50 Drupal sites and we are moving to Docker for our platform update to Drupal 9. We are hoping to leverage the Bitnami/Drupal image and add in some of our own custom modules and needed contrib modules to the images automatically. We were able to get the contrib modules loaded in the 9.4.9 version of the Bitnami/Drupal image from Dockerhub but since then the newest version is not working.

We are fairly new to docker and we may be fundamentally missing something to do this properly. Below is what we did to get a few necessary contrib modules loaded in the image. We have yet to solve the issue of adding custom modules.

Per documentation extending the bitnami drupal image with our own Dockerfile:

```dockerfile
FROM bitnami/drupal

USER 0
RUN install_packages vim
USER 1001 

COPY sh_files /opt/bitnami/scripts/drupal
RUN /opt/bitnami/scripts/drupal/file.sh
```
Inside the .sh file the goal is to use composer to load some contrib modules and change private file directory:

```bash
#!/bin/bash

# shellcheck disable=SC1090,SC1091

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace # Uncomment this line for debugging purposes

. /opt/bitnami/scripts/drupal-env.sh

# Load libraries
. /opt/bitnami/scripts/libdrupal.sh

# Configure private file directory - JM
drupal_conf_set "\$settings['file_private_path']" "../private"

# Move into Drupal root and run composer commands to bring in drupal.org modules
cd /opt/bitnami/drupal/
composer require 'drupal/variationcache:^1.2'
composer require 'drupal/entity:^1.4'
composer require 'drupal/group:^1.5'
```

### What is the expected behavior?

Using the above we expect the container to launch with the private file path changed and the contrib modules loaded via composer. We also used the DRUPAL_ENABLE_MODULES env var in the docker-compose.yml file to automatically enable them. This was working in 9.4.9 but the latest image is breaking.

### What do you see instead?

Drupal site fails to initialize.

### Additional information

We'd like some guidance on how best to accomplish adding contrib and custom modules by extending the Bitnami/Drupal image. We're currently worried our method is more of a hackjob.

Thanks for any help!

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by wdt-dh** [comment]
I believe the first hurdle is the line in our .sh file:

`drupal_conf_set "\$settings['file_private_path']" "../private"`

This was working before but is now producing this error while debugging during Drupal site installation:

`In install.core.inc line 2316:

  [Drupal\Core\Installer\Exception\InstallerException]
  File system:Writable (<em>public</em> download method)<br /><br />The direc
  tory <em class="placeholder">../private</em> does not exist. An automated a
  ttempt to create this directory failed, possibly due to a permissions probl
  em. To proceed with the installation, either create the directory and modif
  y its permissions manually or ensure that the installer has the permissions
   to create it automatically. For more information, see INSTALL.txt or the <
  a href="https://www.drupal.org/server-permissions">online handbook</a>.`

The file is being executed under USER 0. 

We're using AWS and EFS for private files. Settings this path in the settings.php is paramount.

**Comment by wdt-dh** [comment]
Another update. The code works in 9.5.1 but not 9.5.2.

**Comment by wdt-dh** [comment]
I have solved the initial private files in settings.php issue with the following code in my extended image:

`USER 0
RUN mkdir -p /opt/bitnami/private/
RUN chown 1001:root /opt/bitnami/private/
RUN chmod g+rwX /opt/bitnami/private
RUN /opt/bitnami/scripts/drupal/file.sh
USER 1001`

I'm just making the private directory and changing the permissions so Drupal core can drop in the .htaccess file. As I expected, this leads to a new error with the composer commands:

`[02-Feb-2023 12:22:42 UTC] PHP Fatal error:  Cannot redeclare format_size() (previously declared in /opt/bitnami/drupal/core/includes/common.inc:137) in /opt/bitnami/drupal/vendor/drupal/core/includes/common.inc on line 137
 [warning] Drush command terminated abnormally.`

One step closer.

**Comment by wdt-dh** [comment]
I have "solved" the final issue with the PHP error. Reading through various issue tickets on Drupal.org led me to understand that the problem was being caused by the composer commands executing more than once. I moved the execution of the file.sh back to the USER 1001 and the error resolved.

I would still like some guidance, if available, that my current approach is fine. If there are better ways to extend and add contrib and custom modules to this bitnami image, I'd love to hear them. Trying to learn as much as possible here. I hope this issue also helps out some other party.

If anything was unclear, please reach out. Thanks.
