### ISSUE TITLE
[bitnami/kafka] Kafka leader election delay

### ISSUE THREAD

**Issue by LHozzan** [bitnami/containers#22431]
### Name and Version

bitnami/kafka:3.3.2

### What steps will reproduce the bug?

I believe, that this isnt bug, but maybe missing configuration.

### What is the expected behavior?

Kafka in Raft mode start in K8s cluster without any initial restarts.

### What do you see instead?

When first Kafka instance/pod start, it starting election, but after one minute failed, because second instance just fetching image and vice versa.
It cost some time and meantime Kafka's pods are restarting.

I would like to ask have Kafka some settings to extend time for election process? Actually it seems, that is electing one minute and end with error message:

```
ERROR [BrokerLifecycleManager id=0] Shutting down because we were unable to register with the controller quorum. (kafka.server.BrokerLifecycleManager)
```

Yes, in the time second Kafka instance isn't ready (due to my slow internet connection) ...

### Additional information

I have local Kind cluster. When cluster is fresh new start, all images must be fetched. Unfortunately, some pods fetch same image soon, some later.

Actually I am not able to start all Kafka's instances at once and they starting randomly depend on the image pull time. This blocking election and when time for election is exhausted (~ 1 minute), affected Kafka instance end with error and K8s will restarting failed pod.

Fail is know, because another Kafka's instance is not started due to pulling image.

Or exist some mechanism to force Kafka instance waiting for another instance instead of extend election time?

**Comment by javsalgar** [comment]
Hi,

Our containers have the `KAFKA_CFG_*` env vars that allow you to set any configuration parameter that Kafka allows. Regarding the leader election timeout, this is something that the Kafka documentation or devs should confirm if it is possible to modify. Did you check their documentation?

**Comment by LHozzan** [comment]
HI @javsalgar 

Finally we founded worked parameter: [`initial.broker.registration.timeout.ms`](https://kafka.apache.org/documentation/#brokerconfigs_initial.broker.registration.timeout.ms)

By default have the parameter 1 minute and when I extend it to 3 minutes, started instances wait to starting instances and not restarting due to missing voters.

Thank you for your time and effort. Please, consider my question as answered.

Cheers!
