### ISSUE TITLE
[bitnami/matomo] Matomo config.ini.php file not updated with env var when made persistent

### ISSUE THREAD

**Issue by bebosudo** [bitnami/containers#22432]
### Name and Version

bitnami/matomo:4.13.3-debian-11-r0

### What steps will reproduce the bug?

We installed bitnami/matomo through the associated Helm Chart; the database was updated from stage to production using Helm chart variables, but the change wasn't propagated to the config.ini.php file, and it took us hours to debug why the init scripts were trying to contact the database using different values from what was defined in the environment variables.

### What is the expected behavior?

The environment variables should take precedence over the config file previously created on disk.

### What do you see instead?

```
matomo 12:12:01.39 DEBUG ==> Validating settings in MATOMO_* environment variables...
matomo 12:12:01.46 INFO  ==> Persisted Matomo installation detected
matomo 12:12:01.46 INFO  ==> Updating default plugins in persisted data
matomo 12:12:01.61 INFO  ==> Updating default js scripts in persisted data
matomo 12:12:01.66 INFO  ==> Restoring Matomo installation
matomo 12:12:02.08 INFO  ==> Trying to connect to the database server
matomo 12:12:02.10 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 1045 (28000): Access denied for user 'previous_user_no_longer_set_in_environment_variables'@'10.1.6.59' (using password: YES)
```

### Additional information

I'm available to provide more details if needed.

**Comment by javsalgar** [comment]
Hi,

This is something we have discussed in the past and we don't have an easy answer. At the moment, our design is to use these variables during the first boot, as users may have wanted to change these settings using admin panels or similar. Maybe we should make it more explicit in the README.md that these variables are first boot.
