### ISSUE TITLE
Discourse not working properly

### ISSUE THREAD

**Issue by vintage007** [bitnami/containers#22430]
### Name and Version

bitnami/discourse:2

### What steps will reproduce the bug?

1 :  curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/discourse/docker-compose.yml > docker-compose.yml
2: docker-compose up -d

### What is the expected behavior?

Normal connect to the server and use it 

### What do you see instead?

Blank black page or incorrect dashboard page
![Screenshot 2023-01-31 at 12 16 39](https://user-images.githubusercontent.com/33037326/215745893-a791e7d2-a2bf-4949-83dc-e9a3e37bb366.png)
when I push the signup button then I can see only back blank page

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by vintage007** [comment]
Ok, thanks for your explanation :)
