### ISSUE TITLE
How to add lua modules to openresty ? 

### ISSUE THREAD

**Issue by gnd** [bitnami/containers#22467]
### Name and Version

bitnami/openresty

### What is the problem this feature will solve?

Hello, 

how would one add additional lua modules into the bitnami openresty container ?

### What is the feature you are proposing to solve the problem?

The first idea that comes to mind is using luarocks (which would have to be installed with apt first, increasing the image size almost twofold). Another idea is to get the package from github and copy the .lua files somewhere to the openresty directory.

Is there some other preferred way to include some packages ? Or maybe some kind of wishlist where one could ask for package inclusion?

In this specific case we need lua-resty-http (https://luarocks.org/modules/pintsized/lua-resty-http).

**Comment by gongomgra** [comment]
Hi @gnd,

Thanks for using Bitnami. Openresty includes its own package manager (`opm`), which is included in our solution. They also discourage using `luarocks` as deprecated. You can get more information on this in the official article linked below

https://openresty.org/en/using-luarocks.html

However, I found a bug in our image trying to install a lua package using `opm`, as our image doesn't include `curl`.

```
root@8a6ea9d1b5b4:/app# opm get openresty/lua-resty-lock
* Fetching openresty/lua-resty-lock
sh: 1: curl: not found
ERROR: failed to run command "curl -sS -i -A 'opm 0.0.6 (x86_64-linux-gnu-thread-multi, perl v5.32.1)' 'https://opm.openresty.org/api/pkg/fetch?account=openresty&name=lua-resty-lock&op=&version='"
```

I filed an internal task to include `curl` in our images by default, and our engineering team is working on it. In the meantime, you can workaround this issue by building your custom image from ours

```
FROM bitnami/openresty:latest
RUN install_packages curl ca-certificates
```

We will post an update as soon as our updated images are available.

**Comment by gongomgra** [comment]
Hi @gnd,

We have just released a new container of Openresty fixing the issue installing the lua packages. The tag for this release is `1.21.4-1-debian-11-r86`. We also added a new section in the `README.md` file for this

https://github.com/bitnami/containers/tree/main/bitnami/openresty#adding-lua-modules

```
$ docker run --rm -it bitnami/openresty:1.21.4-1-debian-11-r86 opm get openresty/lua-resty-lock
Unable to find image 'bitnami/openresty:1.21.4-1-debian-11-r86' locally
1.21.4-1-debian-11-r86: Pulling from bitnami/openresty
1b0636f0609b: Pull complete
Digest: sha256:9ce744ae6f64f9161461be15e4b6946b71f3bc3c6a1217625a0b7a514fab3f86
Status: Downloaded newer image for bitnami/openresty:1.21.4-1-debian-11-r86
openresty 17:17:47.62
openresty 17:17:47.62 Welcome to the Bitnami openresty container
openresty 17:17:47.62 Subscribe to project updates by watching https://github.com/bitnami/containers
openresty 17:17:47.62 Submit issues and feature requests at https://github.com/bitnami/containers/issues
openresty 17:17:47.62

* Fetching openresty/lua-resty-lock
  Downloading https://opm.openresty.org/api/pkg/tarball/openresty/lua-resty-lock-0.08.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9041  100  9041    0     0  38147      0 --:--:-- --:--:-- --:--:-- 38147
Package openresty/lua-resty-lock 0.08 installed successfully under /opt/bitnami/openresty/site/ .
```

**Comment by gnd** [comment]
amazing, thank you !
