### ISSUE TITLE
DokuWiki: DOKU_INC not initialized on container upgrade

### ISSUE THREAD

**Issue by splitbrain** [bitnami/containers#22466]
### Name and Version

bitnami/dokuwiki:20220731

### What steps will reproduce the bug?

When you upgrade to the newest image version, it includes the mechanism to autoprepend the setting of the DOKU_INC define as discussed in #12535, however since the initialization has already been done with a previous image version it will be skipped completely, making the fix unavailable to users of previous versions.

### What is the expected behavior?

The existence of the auto prepend file should be checked on every container start and be initialized if necessary.

### What do you see instead?

No auto prepend is configured and DOKU_INC is pointing to the wrong location for non-main scripts.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/dokuwiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
