### ISSUE TITLE
Run keycloak by docker-compose, inside Running Jira and pgsql

### ISSUE THREAD

**Issue by mfaridi1394** [bitnami/containers#22469]
### Name and Version

keycloak:20

### What steps will reproduce the bug?

On our server we have Jira started by docker-compose and use pgsql for DB.
I want run Keycloak by use pgsql too on this server and use it for authentication for Jira.
How I can edit YAML for keycloak and pgsql run on different port on this servers.
I use default docker-compose file

### What do you see instead?

I run it this docker-compose file and see error about Exited (0)
pgsql is running but keycloak stop working

**Comment by carrodher** [comment]
It seems a very specific use case and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
