### ISSUE TITLE
odoo v15 live chat with multi workers

### ISSUE THREAD

**Issue by JimmyShalaby** [bitnami/containers#22468]
### Name and Version

odoo v15

### What steps will reproduce the bug?

when i increase the number of worker to any number more than 0 the live chat feature stop showing online status
iam using bitnami odoo with apache
what can i do

### What is the expected behavior?

to show online status

### What do you see instead?

offline status

### Additional information

no

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
