### ISSUE TITLE
[bitnami/moodle] Migration v3 to v4 with postgres database

### ISSUE THREAD

**Issue by Paulpatou** [bitnami/containers#23089]
### Name and Version

bitnami/moodle:3

### What steps will reproduce the bug?

I am trying to migrate my moodle v3.11.6 instance to v4 but it doesn't work I have an error in the database that says 
I deleted the moodle_data persistent volumes (I have of course a backup of the v3 if needed) and I kept the postgresql one for my data.
I replaced in my docker-compose the v3 image by `image: docker.io/bitnami/moodle:4`

### What do you see instead?

    I am trying to migrate my moodle v3.11.6 instance to v4 but it doesn't work I have an error in the database that says :
```
Database system is ready to accept connections
 ?column?
---------------
              1
(1 row)
Running Moodle install script
Moodle 4.1 (Build: 20221128) command line installation program
Database tables already present; CLI installation cannot  continue.
exited with code 1
```

### Additional information

Is there a specific procedure in your image, to make this migration?
Thanks for help

**Comment by javsalgar** [comment]
Hi,

Please, note this container is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.

**Comment by geek-at** [comment]
have you ever solved this @Paulpatou ?

I'm having the same problems. I can update fine from cli but the container doesn't start because of the error message. Seems like if the container sees a new version it tries to run the install_database php script and get's the "already installed" error because it should have just ran the upgrade.php script

but there don't seem to be any flags or something to skip install
