### ISSUE TITLE
The link to the body cannot be downloaded

### ISSUE THREAD

**Issue by EricCaoHZ** [bitnami/containers#23231]
### Name and Version

docker-compose.yml

### What is the problem this feature will solve?

https://raw.githubusercontent.com/bitnami/containers/main/bitnami/APP/docker-compose.yml
ERROR 404: Not Found

### What is the feature you are proposing to solve the problem?

Please give a new address

**Comment by javsalgar** [comment]
Hi,

Could you add more details on what you are trying to download? Note that APP is a placeholder for the application you want to use.

**Comment by EricCaoHZ** [comment]
I didn't notice this, thank you
