### ISSUE TITLE
[bitnami/external-dns] aarch64 image build for external-dns

### ISSUE THREAD

**Issue by neggles** [bitnami/containers#23230]
### Name and Version

bitnami/external-dns

### What is the problem this feature will solve?

Unable to deploy `bitnami/external-dns` chart on an aarch64 machine (e.g. Oracle Cloud Ampere Altra instance)

### What is the feature you are proposing to solve the problem?

Hi all! Would it be possible to set up an aarch64 image build for `external-dns`? The upstream project has been releasing aarch64 and armhf images for a little while now; I don't think there should be any major roadblocks?

### What alternatives have you considered?

Upstream has their own Helm chart now, but it doesn't integrate with secrets very well & the config in general leaves something to be desired, heh.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that we don't have plans to support aarch64 at the moment. As soon as there are changes on this, we will let the community know.
