### ISSUE TITLE
[bitnami/redis-cluster] Allow redis cluster to accept connection with hostname

### ISSUE THREAD

**Issue by deveshk0** [bitnami/containers#23244]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

This will allows redis cluster to accept connection with hostname.

### What is the feature you are proposing to solve the problem?

Add Support for 
```
cluster-announce-hostname
cluster-preferred-endpoint-type
```

This will allows redis to run on hostname and fix the tls problem explain here https://github.com/bitnami/charts/issues/14673

**Comment by javsalgar** [comment]
Hi,

Thank you for the feature request! I will forward this to the team. If you want to speed up the process, would you like to submit PR?
