### ISSUE TITLE
Apache Kafka 3.4.0

### ISSUE THREAD

**Issue by jtk94** [bitnami/containers#23537]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Kafka 3.4.0 includes a significant number of new features and fixes.  Notably, the version should address multiple open CVEs against Kafka.

### What is the feature you are proposing to solve the problem?

Apache Kafka 3.4.0 was released on Feb 7, 2023.  If it is not already in the works, I'd like to request Bitnami package the Kafka 3.4.0 version similar to how it has done previous versions of Kafka.

### What alternatives have you considered?

Using 3.3.2 until 3.4.0 is made available.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by carrodher** [comment]
I would like to share with you that the new version is already released, see https://github.com/bitnami/containers/pull/23958.

Now you can use Kafka 3.4 as the previous branches.

**Comment by ulpcan** [comment]
Thanks a lot. :pray: 

Is there any exampled docker-compose file for bitnami kafka 3.4.0 with KRaft ready without zookeeper?
