### ISSUE TITLE
Redmine Docker is without login and password information - Update documentation

### ISSUE THREAD

**Issue by FelipoAntonoff** [bitnami/containers#23588]
### Name and Version

bitnami/redmine: 5.0.4-debian-11-r24

### What is the problem this feature will solve?

Hello, Redmine's Docker is without login and password information.

I recommend adding the default login and password to all application images, when not set in docker-compose.yml and even informed that the login and password is in the configuration to make it clearer, it would also be good for every application to have the default password set in docker-compose.yml.

After installing Redmine, I tried several logins and passwords and none of them worked, I looked in the documentation and in docker-compose.yml and found nothing.

In the end I only found out after watching this video: https://www.youtube.com/watch?v=mKLK03UFVbg

Default login is `user `and password `bitnami1`
It worked after adding this data in the Redmine login.

Another suggestion would be to inform the URL to access the Panel of the installed application, even if it is only seen in docker-compose.yml, as it can facilitate access and sometimes the default URL is not just the IP or domain, some cases need /admin or another address.

### What is the feature you are proposing to solve the problem?

Add data such as login and password in Application Documentation.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
