### ISSUE TITLE
Redis does not have RDB persistent variables

### ISSUE THREAD

**Issue by huangjc7** [bitnami/containers#23836]
### Name and Version

bitnami/redis-cluster:v7.0.5-debian-11-r19-bitnami

### What steps will reproduce the bug?

Redis can set AOF persistent data through the `REDIS_AOF_ENABLED` environment variable, but why there is no RDB persistent parameter? I checked `/opt/bitnami/scripts/redis-cluster-env.sh` and found no relevant configuration. What is the consideration? I have perfected this function

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by huangjc7** [comment]
> 感谢您报告此问题。您想通过创建 PR 来解决问题来做出贡献吗？Bitnami 团队将很乐意对其进行审核并提供反馈。[在这里](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md)你可以找到贡献指南。

Yes, happy to contribute

**Comment by huangjc7** [comment]
This is the first time I submit a pr, how should I submit a pr? Currently, I have forked the project to my own warehouse and completed the code repair

**Comment by carrodher** [comment]
Thanks! Here you can find the GitHub documentation about how to create a PR:
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
