### ISSUE TITLE
cannot create directory '/bitnami/mariadb/data': Permission denied

### ISSUE THREAD

**Issue by BustedSec** [bitnami/containers#23841]
### Name and Version

maradb latest

### What steps will reproduce the bug?

1. Docker on Ubuntu 
2. docker run -e ALLOW_EMPTY_PASSWORD=yes -v /maradb-persist:/bitnami/mariadb bitnami/mariadb:latest

### What is the expected behavior?

the folder will be created and then the docker image will run maradb

### What do you see instead?

mariadb 16:53:36.43
mariadb 16:53:36.43 Welcome to the Bitnami mariadb container
mariadb 16:53:36.43 Subscribe to project updates by watching https://github.com/bitnami/containers
mariadb 16:53:36.44 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mariadb 16:53:36.44
mariadb 16:53:36.44 INFO  ==> ** Starting MariaDB setup **
mariadb 16:53:36.46 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 16:53:36.46 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb 16:53:36.46 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

### Additional information

the account attempting to the create the folder within the docker image may not have permissions to write to that folder is perhaps the reason, but I'm not sure.

**Comment by BustedSec** [comment]
set /maradb-persist folder to chmod 777 temporarily for troubleshooting and issue resolved, need to find better folder permissions and identify which account needs permissions - likely whatever account default docker install is running under. OK to close now.

**Comment by d4rklynk** [comment]
[The bitnami mariadb container set the user to UID 1001](https://github.com/bitnami/containers/blob/9a5ccf3f09011d577dab09430db9920d3059598e/bitnami/mariadb/11.1/debian-11/Dockerfile#L55).
So, create a user in your host machine with the UID 1001, then set the owner for your mariadb persistence repertory to the user 1001:

1 (host) - `useradd -u 1001 mariadb-bitnami`
2 (host) -  `chown -R mariadb-bitnami:mariadb-bitnami /path/to/your/host/repertory/mariadb-persistence`

_N.B.: you can call your user whatever you want as long as the UID is set to 1001 and your host repertory is owned by "1001" user._
