### ISSUE TITLE
[bitnami/mysql] 5.7.41 breaks code that expects UTF-8 defaults

### ISSUE THREAD

**Issue by hughpv** [bitnami/containers#23842]
### Name and Version

bitnami/mysql:5.7.41

### What steps will reproduce the bug?

1. Set up a docker-compose that uses the stock Keycloak 18 image with bitnami/5.7
2. Fire up the docker-compose

### What is the expected behavior?

It just works like it always did until 5.7.41 replaced 5.7.40

### What do you see instead?

```
2023-02-13 17:02:04,360 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-1.9.1.xml::1.9.1::keycloak:
     Reason: liquibase.exception.DatabaseException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: (1118) ALTER TABLE keycloak.REALM MODIFY CERTIFICATE VARCHAR(4000)]
```

### Additional information

The commit https://github.com/bitnami/containers/commit/a994d9bbb32040c4942e2b922bf9453f89b5e33e changed the defaults to use full-on Unicode instead of UTF-8. Under Unicode, the Keycloak table length becomes too long and that causes the failure.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Did you try changing the MYSQL_COLLATE variable or those related?

**Comment by javsalgar** [comment]
Hi,

Here you can find the env vars of the container. 

https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/mysql-env.sh#L140

There I saw the MYSQL_COLLATE one.

**Comment by aafb5cs** [comment]
I am using mysql '5.7.31' utf8mb4, keycloak 21.0.2 I run in to same problem, any solution?

**Comment by jaychang9** [comment]
Yeah! When I change the charset for db keycloak from utf8mb4 -- UTF-8 Unicode to utf8 -- UTF-8 Unicode , it worked!
