### ISSUE TITLE
[bitnami/openldap] add postfix-book.schema by default ?

### ISSUE THREAD

**Issue by fab-kaz** [bitnami/containers#23950]
### Name and Version

bitnami/openldap:2.6

### What is the problem this feature will solve?

Hello,

If postfix-book.schema (https://github.com/variablenix/ldap-mail-schema/blob/master/postfix-book.schema) was integrated in bitnami/openldap, the postfix integration wouldn't hurt us too much.

So we could use the ```LDAP_EXTRA_SCHEMAS=inetorgperson,cosine,postfix-book``` variable

Actually, i didn't have any success in adding the new schema, even with the help of https://github.com/bitnami/containers/issues/4984

### What is the feature you are proposing to solve the problem?

integration of postfix-book.schema in /opt/bitnami/openldap/etc/schema

### What alternatives have you considered?

trying to add the schema as explained in https://github.com/bitnami/containers/issues/4984 but it didn't work because it said: 
```
root@f8a8741bb0cf:/opt/bitnami/openldap/etc/schema# slaptest -v -f postfix-book.schema -F ldif/
postfix-book.schema: line 72 objectclass: AttributeType not found: "mail"
slaptest: bad configuration directory!
```

Because of the ```MUST mail``` which is present in inetorgperson.schema

Thank you for reading ;)
And btw, thank you for all of this amazing work !

f.

**Comment by javsalgar** [comment]
Hi!

Did you try using the init scripts feature to download and install the schema?

**Comment by fab-kaz** [comment]
Hello,

thank you for answering. I'm sorry to be se blind but where do i find "init scripts feature" ?

**Comment by javsalgar** [comment]
Hi,

Here you can find more information https://github.com/bitnami/containers/tree/main/bitnami/openldap#initializing-a-new-instance

**Comment by clayrisser** [comment]
I have an image with that schema baked into it. Feel free to fork it and add your own schemas.

https://github.com/clayrisser/docker-openldap

**Comment by williamdes** [comment]
To this error, I added `include /etc/ldap/schema/core.schema` before my schema.

**Comment by miamilabs** [comment]
> ### Name and Version
> 
> bitnami/openldap:2.6
> ### What is the problem this feature will solve?
> 
> Hello,
> 
> If postfix-book.schema (https://github.com/variablenix/ldap-mail-schema/blob/master/postfix-book.schema) was integrated in bitnami/openldap, the postfix integration wouldn't hurt us too much.
> 
> So we could use the `LDAP_EXTRA_SCHEMAS=inetorgperson,cosine,postfix-book` variable
> 
> Actually, i didn't have any success in adding the new schema, even with the help of #4984
> ### What is the feature you are proposing to solve the problem?
> 
> integration of postfix-book.schema in /opt/bitnami/openldap/etc/schema
> ### What alternatives have you considered?
> 
> trying to add the schema as explained in #4984 but it didn't work because it said:
> 
> ```
> root@f8a8741bb0cf:/opt/bitnami/openldap/etc/schema# slaptest -v -f postfix-book.schema -F ldif/
> postfix-book.schema: line 72 objectclass: AttributeType not found: "mail"
> slaptest: bad configuration directory!
> ```
> 
> Because of the `MUST mail` which is present in inetorgperson.schema
> 
> Thank you for reading ;) And btw, thank you for all of this amazing work !
> 
> f.
Sorry to comment on this old issue. I gave up a year ago, but now I want to switch back to LDAP. Could you please share the steps to implement the Postfix items into Bitnami LDAP?

I have already spent four days going back and forth before writing this comment.

**Comment by williamdes** [comment]
See https://github.com/sudo-bot/docker-openldap/blob/v2.2.6-1/docker/Dockerfile#L92C29-L92C54
