### ISSUE TITLE
[bitnami/moodle] wrong version inside image

### ISSUE THREAD

**Issue by nullsumme** [bitnami/containers#23956]
### Name and Version

bitnami/moodle:4; bitnami/moodle:4.1.1

### What steps will reproduce the bug?

Pulled image with tag "4.1.1". But the version running inside the container is 4.1.

### What is the expected behavior?

Version 4.1.1

### What do you see instead?

Version 4.1

**Comment by carrodher** [comment]
In order to reproduce the issue on our side, what is the process you are following to get the version once deployed the container?

**Comment by nullsumme** [comment]
![image](https://user-images.githubusercontent.com/369577/218972603-78e68174-e4c4-4ac3-a0b8-ba6b07572faf.png)
![image](https://user-images.githubusercontent.com/369577/218972679-39f63621-c368-46bb-a78d-105352de01b6.png)

**Comment by carrodher** [comment]
Please note we provide support for the LTS version (4.1) according to https://moodledev.io/general/releases/4.1 which is different from the 4.1.1+ that is the weekly release according to https://download.moodle.org/releases/latest/

**Comment by nullsumme** [comment]
The latest LTS should be 4.1.1:
![image](https://user-images.githubusercontent.com/369577/218992406-dfe813bc-1e59-4244-8e49-dd75bff23f82.png)

Even if I pull the "docker.io/bitnami/moodle:4.1.1" image, the version is: 4.1 Build: 20221128

**Comment by marcosbc** [comment]
Hi @nullsumme, you are indeed right. Even if we were to follow the LTS version naming, the version is still different from what the container version says. We're looking into this and update this issue once we have more information.
