### ISSUE TITLE
Add jenkins user to docker group

### ISSUE THREAD

**Issue by baloriole** [bitnami/containers#24132]
### Name and Version

bitnami/jenkins:latest

### What is the problem this feature will solve?

It is very difficult to have the jenkins user access the docker group that is defined on the host machine for running docker in docker. This is most evident when mounting /var/run/docker.sock as a volume from the host. 

### What is the feature you are proposing to solve the problem?

 If bitnami jenkins had a script directory that ran at docker runtime and not system initialization, runtime settings could be applied to the system. This way a user could mount a directory with custom scripts that would execute every time the container is brought up.

### What alternatives have you considered?

https://stackoverflow.com/questions/30072491/jenkins-in-docker-with-access-to-host-docker

**Comment by dgomezleon** [comment]
Hi @baloriole ,

Do you mean something like [clickhouse](https://github.com/bitnami/containers/tree/main/bitnami/clickhouse#initializing-a-new-instance) implements?

```
When the container is executed for the first time, it will execute the files with extensions .sh located at /docker-entrypoint-initdb.d. For scripts to be executed every time the container starts, use the /docker-entrypoint-startdb.d folder.
```

Would you like to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
