### ISSUE TITLE
[bitnami/neo4j] init scripts should allow usage of Neo4J's cypher-shell

### ISSUE THREAD

**Issue by Lance-Drane** [bitnami/containers#24133]
### Name and Version

bitnami/neo4j:5.4.0

### What steps will reproduce the bug?

1) Create an initialization script which calls cypher-shell. As an example, the following script just tries to list all databases (cypher-shell will utilize NEO4J_PASSWORD env variable by default: [see source here](https://github.com/neo4j/neo4j/blob/5.4/community/cypher-shell/cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java#L63) )

```bash
#!/usr/bin/env bash

# this is so we can get NEO4J_PASSWORD environment variable
. /opt/bitnami/scripts/neo4j-env.sh

set -euo pipefail

cypher-shell -u neo4j -d system "SHOW DATABASES;"

```

2) Mount initialization script to `/docker-entrypoint-initdb.d/` directory as a volume at runtime

### What is the expected behavior?

cypher-shell command should be able to execute at some point in an initialization script.

### What do you see instead?

The final log entry is a result of calling the above script in an entrypoint script

```
neo4j                 | neo4j 00:42:35.07 INFO  ==> Deploying Neo4j from scratch
neo4j                 | neo4j 00:42:35.07 INFO  ==> Configuring initial password
neo4j                 | neo4j 00:42:36.83 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
neo4j                 | Connection refused
```

(It's because neo4j has never started - cypher-shell will fail)

### Additional information

Some userscripts need to execute _before_ the neo4j database server starts up (for example, if wanting to modify mounted CSV files in `$NEO4J_HOME/import` immediately after mount), while other userscripts need to execute _after_ the neo4j database server starts up (for example, if running Cypher queries directly). Currently, only the former use-cases are supported.

This would probably require some additional function similar to `neo4j_custom_init_scripts`. It would need to be placed after starting neo4j in `run.sh`, and would need to use an additional mount directory (instead of just `$NEO4J_INITSCRIPTS_DIR`). 

Executing cypher statements against the DB will usually require sleeping a certain amount of time, but that's probably best left up to the userscript to determine.

**Comment by Mauraza** [comment]
Hi @Lance-Drane,

The script was running before starting Neo4j so is falling. This type the script should be running before the neo4j is running.
We are open to contributions if you want to contribute by adding what you said would be great.

> This would probably require some additional function similar to neo4j_custom_init_scripts. It would need to be placed after starting neo4j in run.sh, and would need to use an additional mount directory (instead of just $NEO4J_INITSCRIPTS_DIR).
