### ISSUE TITLE
[bitnami/harbor-registry] master.tar.gz download link is broken

### ISSUE THREAD

**Issue by wmunguiam** [bitnami/containers#24131]
### Name and Version

bitnami/harbor-registry

### What steps will reproduce the bug?

Step #1: Go to https://hub.docker.com/r/bitnami/harbor-registry/
Step #2:  Download tar.gz file from command CLI as described, fails:

To test: curl  https://github.com/bitnami/containers/blob/main/bitnami/harbor-portal/archive/master.tar.gz
Log received: "The 'bitnami/containers' repository doesn't contain the 'bitnami/harbor-portal/archive/master.tar.gz' path in 'main'. "

### What do you see instead?

"File not found"

**Comment by andresbono** [comment]
Thanks for reporting this issue, @wmunguiam. It seems the **TL;DR** section needs to be updated. Can you try the following commands instead?

```
curl -LO https://raw.githubusercontent.com/bitnami/containers/main/bitnami/harbor-portal/docker-compose.yml
curl -L https://github.com/bitnami/containers/archive/main.tar.gz | tar xz --strip=2 containers-main/bitnami/harbor-portal && cp -RL harbor-portal/config . && rm -rf harbor-portal
docker-compose up
```

Let us know if it works for you!

**Comment by andresbono** [comment]
@wmunguiam https://hub.docker.com/r/bitnami/harbor-registry/ is now updated. Thanks for reporting this issue.
