### ISSUE TITLE
Odoo 14

### ISSUE THREAD

**Issue by bajoski34** [bitnami/containers#24147]
### Name and Version

bitnami/odoo:14

### What steps will reproduce the bug?

The container exits. log does not show any errors as to why it exited. using the docker-compose.yml file provided in the repo.

### What is the expected behavior?

container does not exit immediately.

### What do you see instead?

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/39011309/219421567-bd8be59c-d523-4ad9-af5c-9baf03243eb1.png">

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by bajoski34** [comment]
Thanks @carrodher i will raise a pr
