### ISSUE TITLE
[bitnami/mongodb] Add section to documentation for setting up single node replica set locally for dev/testing

### ISSUE THREAD

**Issue by jrj2211** [bitnami/containers#24151]
### Name and Version

bitnami/mongodb:latest

### What is the problem this feature will solve?

I've spent the last day trying to figure out how to get the bitnami/mongodb setup as a single node replica server just for local dev/testing.

I ran into an issue where I could connect to my Mongo server only if it wasn't a replica server. If it was a replica server, I could see the container getting the connection, but then terminating it. It took me a while to realize that's because it trying to then connect to it via its hostname "mongodb", which on the host machine doesn't exist if you isolate your docker network.

There were several unanswered stackoverflow and mongo forum posts about this exactly. The only solution that was ever suggested was to add the hostname to your `hosts` file pointing to `127.0.0.1`. I really disliked that as I don't want to have to modify my host to get my development containers to work.

What I finally realized is I can just change the advertised hostname to be "localhost" and now everything works. I can connect to it from Mongo Compass from my host machine no problem.

```
MONGODB_ADVERTISED_HOSTNAME: localhost
```

### What is the feature you are proposing to solve the problem?

I think it might be nice to add a section to the readme for how to set it up for local dev/testing. With the amount of unanswered questions on various forums, I cant imagine others aren't trying this and giving up on using it. This image is so much nicer than setting up a bunch of scripts and multiple containers to initialize a replicaset for testing but I was on the verge of giving up. Very glad I didn't but I hope to help others not spend hours trying to figure out the same thing. Its such a simple solution, but was not inherently obvious to me that this was what I needed.

### What alternatives have you considered?

I have posted this as an answer to all the questions I found on the topic.

**Comment by Mauraza** [comment]
Hi @jrj2211,

We are open to contributions!! But I think the issues already help others when someone is search solutions.
