### ISSUE TITLE
[bitnami/openldap] Users are not recreated if TLS volumes are in place from previous containers

### ISSUE THREAD

**Issue by pat-s** [bitnami/containers#24150]
### Name and Version

bitnami/openldap:2

### What steps will reproduce the bug?

1. Create a container with some persistent volumes, e.g. TLS cert and key mappings and a custom LDIF 
2. Remove the container
3. Create a new container. I would expect the default users to get created as `/path/to/openldap-data-persistence:/bitnami/openldap/` was not mounted. 

Instead of printing out

```
 20:20:10.70 INFO  ==> Adding LDAP extra schemas
 20:20:10.73 INFO  ==> Creating LDAP default tree
```

LDAP is showing

```
 20:03:47.83 INFO  ==> Initializing OpenLDAP...
 20:03:47.87 INFO  ==> Using persisted data
 20:03:47.89 INFO  ==> ** LDAP setup finished! **
```

Yet in fact, no users are present. The persisted data is only used because some volumes are in place that map certs/keys but actually no volume that would persist the data.

### What is the expected behavior?

I would expect LDAP to create the default users if no users are in place/persisted.

### What do you see instead?

LDAP is showing "using persisted data" even though no persisted data exists.

### Additional information

This is quite tricky and costed me several hours. I was trying to get back to a "vanilla" container with new users, only keeping the certs. But these new users were never created until I also removed the TLS cert/key volumes.

**Comment by aoterolorenzo** [comment]
The persistence checks use to be triggered when anything is found on the `/bitnami/asset` directory. Are you provisioning anything in `/bitnami/openldap`? If not, could you enter the main pod and `ls -la /bitnami/openldap`? I'm pretty confident in some files are being contained there (which may be actually an issue).
