### ISSUE TITLE
[bitnami/gitlab-runner-helper] gitlab-runner-build: command not found

### ISSUE THREAD

**Issue by myysophia** [bitnami/containers#24153]
### Name and Version

bitnami/gitlab-runner-helper:15.8.0

### What steps will reproduce the bug?

1.  gitlab-runner:alpine-v15.8.0 install by helm chart 

`helm install my-gitlab-runner gitlab/gitlab-runner --version 0.49.2
`

2. k8s version 1.23
3. gitlab-runner [values.yaml](https://gist.github.com/myysophia/caae14af44d5c50a33952109c6b889ba)

- runner use kubernetes exector
- helper image use bitnami/gitlab-runner-helper:15.80 

4.  in my gitlab cicd web console

![image](https://user-images.githubusercontent.com/25994521/219611478-7c97be6e-a570-408c-915a-56cbfdb6e518.png)

5. helper container log
![image](https://user-images.githubusercontent.com/25994521/219612258-6fca393a-97f7-4c78-a082-d0cb04644f5b.png)

### What is the expected behavior?

I've been fighting hard with it but couldn't get it to work. Any help? Thanks!

### What do you see instead?

.

**Comment by javsalgar** [comment]
Hi,

It seems to me that one of the binaries is missing from the helper image. I will forward this to the engineering team to check it.

**Comment by myysophia** [comment]
![image](https://user-images.githubusercontent.com/25994521/219613457-1ae0d832-7781-474a-b17b-8bf500b446cb.png)

![image](https://user-images.githubusercontent.com/25994521/219613568-d5769559-e0bc-4175-bdf7-e2147486ca2c.png)

**Comment by migruiz4** [comment]
Hi @myysophia,

We have released a new version of the `bitnami/gitlab-runner-helper` image including the `gitlab-runner-build` command.

The fix is available starting from the image version `bitnami/gitlab-runner-helper:15.10.1-debian-11-r0`.

Please let us know if it fixes your issue.
