### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Bump JDK versions for Spring Cloud Dataflow images

### ISSUE THREAD

**Issue by OmegaVVeapon** [bitnami/containers#24449]
### Affected images:
* bitnami/spring-cloud-dataflow:2.10.0-debian-11-r14
* bitnami/prometheus-rsocket-proxy:1.5.0-debian-11-r61

### What steps will reproduce the bug?

1. Deploy a pod using Kubernetes 1.25 with `bitnami/spring-cloud-dataflow:2.10.0-debian-11-r14` and/or `bitnami/prometheus-rsocket-proxy:1.5.0-debian-11-r61` with CPU and memory limits.

### What is the expected behavior?

The containers should respect the Kubernetes resource limits

### What do you see instead?

The containers use more than the allotted memory and are OOMKilled.

### Additional information

The SCDF image
https://github.com/bitnami/containers/blob/main/bitnami/spring-cloud-dataflow/2/debian-11/Dockerfile#L26

and the Prometheus Rsocket Proxy image
https://github.com/bitnami/containers/blob/main/bitnami/prometheus-rsocket-proxy/1/debian-11/Dockerfile#L25

both use JDK 8.

In the most recent upgrade of Kubernetes 1.25, cgroups v2 has been activated by default.
https://kubernetes.io/docs/concepts/architecture/cgroups/#cgroup-v2

However, there's an issue in which JDK 8 does **NOT** respect the resource limits which k8s imposes using cgroups v2.
As a result, the containers push past their allotted CPU and memory and get constantly getting OOMKilled.

See: https://blog.kintone.io/entry/2022/03/08/170206
and https://github.com/Azure/AKS/issues/3443

Due to this, we'd like to request upgrading the JDK version used in these images, ideally to JDK 17 as it's the only LTS version that natively understands cgroups v2.
https://endoflife.date/java

I've run some tests by rebuilding these images using JDK 15 and can confirm that the issues do not occur there.

**Comment by javsalgar** [comment]
Thank you so much for the insight! I will forward this to the engineering team

**Comment by OmegaVVeapon** [comment]
SCDF Server was upgraded to JDK 17:
https://github.com/bitnami/containers/blob/main/bitnami/spring-cloud-dataflow/2/debian-11/Dockerfile#L26
and it fixed the cgroups v2 issue as expected.

Thank you!

Now only the Prometheus Rsocket Proxy is missing.
https://github.com/bitnami/containers/blob/main/bitnami/prometheus-rsocket-proxy/1/debian-11/Dockerfile#L25

@javsalgar would you accept a PR for this change if I send one?

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay. 
  Sure !! We are hesitant to receive PRs fixing or adding features. 
  Please, feel free to send a PR we will be glad to review and merge it.
  Thanks
