### ISSUE TITLE
[bitnami/suitecrm] : Documentation - DB Host Name

### ISSUE THREAD

**Issue by stellarpower** [bitnami/containers#24487]
### Name and Version

bitnami/suitecrm:8.2.1

### What is the problem this feature will solve?

The docs (to me) seem to imply that the containers are configured primarily by the environment variables. As is standard practice - this is good. We are basically just following the standard template [here](https://hub.docker.com/r/bitnami/suitecrm) and filling out our details - we create a compose file from this template, added in our own values for the DB settings, brought it up, all is well.

Except we had to restructure our pod setup a bit, and as a result the database server is now reached via a different hostname. It is located slightly differently within the container networking setup.

A few other things were at play in this migration, that aren't relevant, so I won't go into them - but it seems to me that I could bring down the pod, change the MariaDB username password, even the table name, and as long as this is reflected across both containers in the pod, when I bring it back up, things are fine. Great! As it should be with containers :heart:.  But if I change the hostname, the suiteCRM containers cycled endlessly complaining it can't connect to the database.

In the end I had to go into the volume and edit these files in order to get past this and connect:
- suitecrm_data/public/legacy/config.php
- suitecrm_data/public/legacy/config_si.php
- suitecrm_data/.env.local

Possibly not all are needed, it's a bit late at night for me to make a MRE, but I have changed at least those three.

### What is the feature you are proposing to solve the problem?

I'm not sure if this is an issue that should be resolved, or if this is as expected, I'd be grateful if the docs could be updated please to add some information about what needs done when migrating from one setup to another, or making small changes to a deployment. Again, this was compounded by some other things that are a fault on my end, but that is also the reality of maintenance, and rather a lot of stress and time was lost trying to work out the cause of this. At the least, output of more information than "failed to connect to database" would be really helpful in the logs. Is some inner exception thrown somewhere in this process? As this might provide really valuable logging in terms of diagnosing the problem (password was wrong; table does not exist; credentials not okay; could not connect to host on this port; could not resolve host's name).

Cheers

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! I'm afraid that currently this is intentional. The database settings are set on first boot and, in case they need to be changed, you would need to manually enter the container and perform the necessary changes. For this kind of scenarios, the charts have a `diagnosticMode.enabled=true`  flag that allows you to enter the container and perform modifications. I will forward this to the documentation team, but I cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and we will take a look
