### ISSUE TITLE
[bitnami/schema-registry] SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL don't support FORWARD_TRANSITIVE

### ISSUE THREAD

**Issue by icapa3** [bitnami/containers#24495]
### Name and Version

Helm Chart latest version -- bitnami/schema-registry

### What steps will reproduce the bug?

Helm chart schema-registry:

Chart documentation:
```
## @param avroCompatibilityLevel Avro compatibility type
## Valid options: none, backward, backward_transitive, forward, forward_transitive, full, or full_transitive
##
avroCompatibilityLevel: forward_transitive
```
ERROR LOG POD:
```
schema-registry 07:28:17.22 ERROR ==> The allowed values for SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL are: none, backward, forward or full
```

### What is the expected behavior?

ERROR LOG POD:
```
schema-registry 07:28:17.22 ERROR ==> The allowed values for SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL are: none, backward, forward or full
```
### What do you see instead?

ALL Versions

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue! Would you like to submit a PR changing the check in `libschemaregistry.sh`? If not, we will work on it but we cannot guarantee an ETA.

**Comment by icapa3** [comment]
Thanks, but I don't know what to change

**Comment by javsalgar** [comment]
Hi,

This section

```
    if [[ -n "$SCHEMA_REGISTRY_CLIENT_AUTHENTICATION" ]]; then
        if ! [[ "$SCHEMA_REGISTRY_CLIENT_AUTHENTICATION" =~ ^(NONE|REQUESTED|REQUIRED)$ ]]; then
            print_validation_error "The allowed values for SCHEMA_REGISTRY_CLIENT_AUTHENTICATION are: NONE, REQUESTED, or REQUIRED."
        fi
    fi
    if [[ -n "$SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL" ]]; then
        if ! [[ "$SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL" =~ ^(none|backward|forward|full)$ ]]; then
            print_validation_error "The allowed values for SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL are: none, backward, forward or full"
        fi
    fi
```

**Comment by icapa3** [comment]
if [[ -n "$SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL" ]]; then
        if ! [[ "$SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL" =~ ^(none|backward|backward_transitive|forward|forward_transitive|full|full_transitive)$ ]]; then
            print_validation_error "The allowed values for SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL are: none, backward, backward_transitive, forward, forward_transitive, full or full_transitive"
        fi
    fi

**Comment by icapa3** [comment]
The problem is I don't know how can I create a new branch in your repo for the PR. Need I create a fork, etc, etc?

**Comment by javsalgar** [comment]
Here you can find more information: https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md

**Comment by icapa3** [comment]
Please, plan it with your times. I can't working on it now

Sorry and thanks

**Comment by aoterolorenzo** [comment]
Hi @icapa3,

I'm opening an internal task for the team to address the issue. We will reach you back here once finished.

**Comment by OneCricketeer** [comment]
As an alternative to Helm, Confluent maintains a Kubernetes operator, where you can configure compatibility modes, and manage schemas as CRDs

**Comment by icapa3** [comment]
I think you don't change it and don't support all options when start container.
