### ISSUE TITLE
[bitnami/kubectl] error: open /.kube/config: permission denied

### ISSUE THREAD

**Issue by lxc455735702** [bitnami/containers#2453]
### Name and Version

bitnami/kubectl:latest

### What is the problem this feature will solve?

My config file has two clusters,i use kubectl to change cluster ,it show error: open /.kube/config: permission denied

### What is the feature you are proposing to solve the problem?

emm..

**Comment by corico44** [comment]
Hello @lxc455735702 

Could you give us more details about your use case like the steps taken specifically to reproduce the error and the values of your config file?? That will help us further understand its context and propose any related alternatives based on it.

**Comment by DavidConnack** [comment]
Reopening as I have the same issue.
I am running bitnami/kubectl:latest as follows: `podman run --rm -v $HOME/Documents/config/kube/config:/.kube/config docker.io/bitnami/kubectl:latest`

The permissions on my config are:
```
➜  kube ls -l
total 12
-rw------- 1 david david 11170 Nov  5 20:16 config
```

Perhaps it has to do with the user that the container is running as?
Thank you
