### ISSUE TITLE
[bitnami/influxdb] on Azure web app + storage account file share (mount) -> timeout in initial run

### ISSUE THREAD

**Issue by driesnollet** [bitnami/containers#24643]
### Name and Version

bitnami/influxdb:2.6.1

### What steps will reproduce the bug?

1. My config at a client is as follow 
(but don't focus on the private resources, also this setup publicly fails at this client):

- private storage account with a file share (private endpoint)
- private linux web app (vnet integrated and private endpoint) 
  - App settings: INFLUXDB_ADMIN_USER_PASSWORD = xx, INFLUXDB_ADMIN_USER_TOKEN = xx,
WEBSITES_PORT = 8086, WEBSITES_ENABLE_APP_SERVICE_STORAGE = false
  - Path mappings:  Mount path = /bitnami/influxdb
  - Deployment Center: Registry settings: bitnami/influxdb:latest (or bitnami/influxdb:2.6.1)
  - App Service Plan tier: P2V3

### What is the expected behavior?

I have exactly the same setup on a test environment publicly, working fine:
Influx DB has been configured and created after 6 seconds:
![image](https://user-images.githubusercontent.com/125258650/220165083-b3bceb35-ddca-4d5c-83e2-ec45fa5312e3.png)

Storage account:
![image](https://user-images.githubusercontent.com/125258650/220164503-63abf919-4b4b-4c26-9a13-0ea85f7de689.png)

### What do you see instead?

![image](https://user-images.githubusercontent.com/125258650/220164836-dcadfb64-2063-4944-9613-c754b4af7b5b.png)

files are not created:
![image](https://user-images.githubusercontent.com/125258650/220165149-b06646b8-0d32-4fa1-b73e-e646fd1e8c09.png)

### Additional information

Recreating the private resources to public ones, didn't fix the issue

**Comment by javsalgar** [comment]
Hi,

Could you add `BITNAMI_DEBUG=true` to see if it provides more insight on the issue?

**Comment by driesnollet** [comment]
> Hi,
> 
> Could you add `BITNAMI_DEBUG=true` to see if it provides more insight on the issue?

Thanks for the feedback @javsalgar 
I tried it and the funny thing is:
It gave exact the issue that we had with the original Influxdb image (official provider).
Thats why we changed to Bitnami - which seemed to work fine, until we tested on clients environment

![image](https://user-images.githubusercontent.com/125258650/220304669-85f66ce3-c078-46ab-b79e-7200126b306a.png)

original issue was logged here:
https://github.com/influxdata/influxdata-docker/issues/668
