### ISSUE TITLE
[bitnami/clickhouse]: Need options to setup Prometheus metrics  

### ISSUE THREAD

**Issue by amelkikh** [bitnami/containers#24651]
### Name and Version

bitnami/clickhouse:23.1.3

### What is the problem this feature will solve?

Hi!
I want to setup Prometheus metrics for my setup in docker for my mini cluster Clickhouse but port 9363 not exposed and config file is not compatible out of the box. 

Please add that port as exposed.
Doc: https://clickhouse.com/docs/en/guides/sre/network-ports/

Also please add some kind of option via environment variable to enable collection metrics following by this documentation
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus

### What is the feature you are proposing to solve the problem?

1) Expose port 9363 in Dockerfile for metric collectors 
2) Add env/build configuration to enable collecting metrics for prometheus

### What alternatives have you considered?

Best regards!

**Comment by javsalgar** [comment]
Hi,

Please note that you can mount your custom overrides in the container so you can apply your custom settings https://github.com/bitnami/containers/tree/main/bitnami/clickhouse#configuration-overrides

In case you want it to be set by default, the best place would be to edit the `postunpack.sh` script of the container. In that case, would you like to submit a PR?

**Comment by amelkikh** [comment]
> Hi,
> 
> Please note that you can mount your custom overrides in the container so you can apply your custom settings https://github.com/bitnami/containers/tree/main/bitnami/clickhouse#configuration-overrides
> 
> In case you want it to be set by default, the best place would be to edit the `postunpack.sh` script of the container. In that case, would you like to submit a PR?

Thanks for the idea. I'll try to create PR soon. 
Have a good day

**Comment by amelkikh** [comment]
I tried to figure out how to make an update for version 23. Unfortunately, I don't have the skills to figure it out.
Any config I've tried to set up to export metrics doesn't work.
Custom build with port export did not help. The protocols configuration examples didn't help. Mounted config file with settings for the server http handlers did not help.

Sorry, I hope you can make an example of the settings to be able to access /metrics path.

**Comment by javsalgar** [comment]
Hi,

Could you share the example that did not work?
