### ISSUE TITLE
[bitnami/magento] Azure Container Instances: Container fails after starting installation

### ISSUE THREAD

**Issue by kienzen87** [bitnami/containers#24844]
### Name and Version

bitnami/magento:latest

### What steps will reproduce the bug?

In Azure Container Instances I have deployed ElasticSearch and MariaDB - these two run fine. 
Then, I want to add Magento. Here is my bicep config:
```
resource MagentoContainerGroup 'Microsoft.ContainerInstance/containerGroups@2019-12-01' = {
  name: 'magento-containerinstance'
  location: parLocation
  properties: {
    restartPolicy: 'Never'
    containers: [
      {
        name: 'magento'
        properties: {
          image: 'bitnami/magento:latest'
          ports: [
            {
              protocol: 'Tcp'
              port: 8080
            }
            {
              protocol: 'Tcp'
              port: 80
            }
          ]
          environmentVariables: [
            {
              name: 'MAGENTO_HOST'
              value: 'localhost'
            }
            {
              name: 'MAGENTO_DATABASE_PORT_NUMBER'
              value: '3306'
            }
            {
              name: 'MAGENTO_DATABASE_HOST'
              value: '${reference(MariaDBContainerGroup.id).ipAddress.ip}'
            }
            {
              name: 'MYSQL_CLIENT_DATABASE_ROOT_PASSWORD'
              value: 'Password12345!@#$%'
            }
            {
              name: 'MAGENTO_DATABASE_PASSWORD'
              value: 'Password12345!@#$%'
            }
            {
              name: 'MAGENTO_DATABASE_USER'
              value: 'root'
            }
            {
              name: 'MAGENTO_DATABASE_NAME'
              value: 'bitnami_magento'
            }
            {
              name: 'MAGENTO_ELASTICSEARCH_HOST'
              value: '${reference(elasticsearchContainerGroup.id).ipAddress.ip}'
            }
            {
              name: 'ELASTICSEARCH_HOST'
              value: '${reference(elasticsearchContainerGroup.id).ipAddress.ip}'
            }
            {
              name: 'ELASTICSEARCH_PORT_NUMBER'
              value: '9200'
            }
          ]
          volumeMounts: [
            {
              mountPath: '/bitnami/magento'
              name: 'magentofile'
            }
          ]
          resources: {
            requests: {
              cpu: 1
              memoryInGB: '1.5'
            }
          }
        }
      }
    ]
    volumes: [
      {
        azureFile: {
          shareName: 'magento-share'
          storageAccountKey: listKeys(storageAccountName, '2021-06-01').keys[0].value
          storageAccountName: storageAccountName
        }
        name: 'magentofile'
      }
    ]
    networkProfile: {
      id: networkProfile.id
    }
    osType: 'Linux'
  }
  dependsOn: [
    MagentoFileShare
  ]
}
```
What I get in output:
```
[38;5;6mmagento [38;5;5m15:16:36.01 [0m
[38;5;6mmagento [38;5;5m15:16:36.02 [0m[1mWelcome to the Bitnami magento container[0m
[38;5;6mmagento [38;5;5m15:16:36.02 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mmagento [38;5;5m15:16:36.03 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mmagento [38;5;5m15:16:36.04 [0m
[38;5;6mmagento [38;5;5m15:16:36.06 [0m[38;5;2mINFO [0m ==> ** Starting Magento setup **
realpath: /bitnami/apache/conf: No such file or directory
[38;5;6mmagento [38;5;5m15:16:36.17 [0m[38;5;2mINFO [0m ==> Configuring Apache ServerTokens directive
[38;5;6mmagento [38;5;5m15:16:36.26 [0m[38;5;2mINFO [0m ==> Configuring PHP options
[38;5;6mmagento [38;5;5m15:16:36.27 [0m[38;5;2mINFO [0m ==> Setting PHP expose_php option
[38;5;6mmagento [38;5;5m15:16:36.34 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_CLIENT_* env vars
[38;5;6mmagento [38;5;5m15:16:36.56 [0m[38;5;2mINFO [0m ==> Ensuring Magento directories exist
[38;5;6mmagento [38;5;5m15:16:36.58 [0m[38;5;2mINFO [0m ==> Configuring permissions
[38;5;6mmagento [38;5;5m15:16:36.68 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mmagento [38;5;5m15:16:36.77 [0m[38;5;2mINFO [0m ==> Trying to connect to Elasticsearch
[38;5;6mmagento [38;5;5m15:16:36.82 [0m[38;5;2mINFO [0m ==> Running Magento install script
```
Then container is being terminated.

![image](https://user-images.githubusercontent.com/98391383/220385878-d87c2b29-25c4-43ca-9dbc-f48db97715ed.png)

### What is the expected behavior?

The container should start or throw a specific error

### What do you see instead?

Container does not start, one cannot log into it. It shows status "Terminated"

### Additional information

Config of my other containers:
```
resource elasticsearchContainerGroup 'Microsoft.ContainerInstance/containerGroups@2019-12-01' = {
  name: 'elasticsearch-containerinstance'
  location: parLocation
  properties: {
    containers: [
      {
        name: 'elasticsearch'
        properties: {
          image: 'elasticsearch:8.6.0'
          ports: [
            {
              protocol: 'Tcp'
              port: 9200
            }
          ]
          environmentVariables: [
            {
              name: 'ES_SETTING_DISCOVERY_TYPE'
              value: 'single-node'
            }
            {
              name: 'TINI_SUBREAPER'
              value: 'true'
            }
            {
              name: 'ES_SETTING_XPACK_SECURITY_ENABLED'
              value: 'false'
            }
          ]
          volumeMounts: [
            {
              mountPath: '/usr/share/elasticsearch/data'
              name: 'elasticsearchfile'
            }
          ]
          resources: {
            requests: {
              cpu: 1
              memoryInGB: '1.5'
            }
          }
        }
      }
    ]
    volumes: [
      {
        azureFile: {
          shareName: 'elasticsearch-share'
          storageAccountKey: listKeys(storageAccountName, '2021-06-01').keys[0].value
          storageAccountName: storageAccountName
        }
        name: 'elasticsearchfile'
      }
    ]
    networkProfile: {
      id: networkProfile.id
    }
    osType: 'Linux'
  }
  dependsOn: [
    ElasticsearchFileShare
  ]
}


resource MariaDBContainerGroup 'Microsoft.ContainerInstance/containerGroups@2019-12-01' = {
  name: 'mariadb-containerinstance'
  location: parLocation
  properties: {
    containers: [
      {
        name: 'mariadb'
        properties: {
          image: 'bitnami/mariadb:latest'
          ports: [
            {
              protocol: 'Tcp'
              port: 3306
            }
          ]
          environmentVariables: [
            {
              name: 'MARIADB_ROOT_PASSWORD'
              value: 'Password12345!@#$%'
            }
            {
              name: 'MARIADB_DATABASE'
              value: 'bitnami_magento'
            }
          ]
          volumeMounts: [
            {
              mountPath: '/var/lib/mysql'
              name: 'mariadbfile'
            }
          ]
          resources: {
            requests: {
              cpu: 1
              memoryInGB: '1.5'
            }
          }
        }
      }
    ]
    volumes: [
      {
        azureFile: {
          shareName: 'mariadb-share'
          storageAccountKey: listKeys(storageAccountName, '2021-06-01').keys[0].value
          storageAccountName: storageAccountName
        }
        name: 'mariadbfile'
      }
    ]
    networkProfile: {
      id: networkProfile.id
    }
    osType: 'Linux'
  }
  dependsOn: [
    MySQLFileShare

  ]
}
```

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by michelmelo** [comment]
2023-05-12 15:06:06 magento 14:06:06.29 
2023-05-12 15:06:06 magento 14:06:06.29 Welcome to the Bitnami magento container
2023-05-12 15:06:06 magento 14:06:06.29 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-05-12 15:06:06 magento 14:06:06.29 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-05-12 15:06:06 magento 14:06:06.29 
2023-05-12 15:06:06 magento 14:06:06.29 INFO  ==> ** Starting Magento setup **
2023-05-12 15:06:06 magento 14:06:06.32 INFO  ==> Generating sample certificates
2023-05-12 15:06:06 Generating RSA private key, 4096 bit long modulus (2 primes)
2023-05-12 15:06:06 ..............................................++++
2023-05-12 15:06:06 .............................................++++
2023-05-12 15:06:06 e is 65537 (0x010001)
2023-05-12 15:06:06 Signature ok
2023-05-12 15:06:06 subject=CN = example.com
2023-05-12 15:06:06 Getting Private key
2023-05-12 15:06:06 realpath: /bitnami/apache/conf: No such file or directory
2023-05-12 15:06:06 magento 14:06:06.69 INFO  ==> Configuring Apache ServerTokens directive
2023-05-12 15:06:06 magento 14:06:06.71 INFO  ==> Configuring PHP options
2023-05-12 15:06:06 magento 14:06:06.72 INFO  ==> Setting PHP expose_php option
2023-05-12 15:06:06 magento 14:06:06.72 INFO  ==> Setting PHP output_buffering option
2023-05-12 15:06:06 magento 14:06:06.74 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
2023-05-12 15:06:06 magento 14:06:06.76 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
2023-05-12 15:06:06 magento 14:06:06.80 INFO  ==> Ensuring Magento directories exist
2023-05-12 15:06:06 magento 14:06:06.81 INFO  ==> Configuring permissions
2023-05-12 15:06:06 magento 14:06:06.81 INFO  ==> Trying to connect to the database server
2023-05-12 15:06:11 magento 14:06:11.83 INFO  ==> Trying to connect to Elasticsearch
2023-05-12 15:06:21 magento 14:06:21.84 INFO  ==> Running Magento install script

**Comment by Santiagososs** [comment]
Here my values file
`externalDatabase:
  host: "EXTERNAL_DB"
  port: 3306
  user: "DBUSER"
  password: "DBPWD"
  database: "DBDATABASE"

mariadb:
  enabled: false

magentoHost: "localhost"
magentoUsername: DevopsMagento
magentoPassword: "DevopsMagento"

extraEnvVars:
        - name: PHP_ENABLE_OPCACHE
          value: "0"
        - name: LOG_LEVEL
          value: DEBUG

service:
  type: ClusterIP

volumePermissions:
  enabled: false

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

podSecurityContext:
  enabled: true
  fsGroup: 1001`

If i turn volumePermissions to true, i have i chown missing operator error, and if false, i have the error mentioned by @michelmelo. I tryed to set security contexts and set PHP_ENABLE_OPCACHE variable but also with no success.

**Comment by miniminsh82** [comment]
Wondering if anyone found a cure for this issue. I'm seeing the same issue when try to deploy this to any Azure container platform. 
works find locally in docker desktop. 
Is there something Azure is doing with permissions that is incompatible with how the magneto installation script is working?

**Comment by martyzz1** [comment]
I had this issue recently, on a simple docker-compose local dev setup. Turning on BITNAMI_DEBUG=true environment variable in the magento container allowed me to see the error messages, which basically said that the magento user password should have numbers and letters... and I'd only set letters...  But until discovering the DEBUG mechanism, I saw exactly what everybody has posted on this thread... So Whilst I can't comment on the Azure issues, I came here looking for a solution to a simillar problem... so hope this helps somebody...
