### ISSUE TITLE
[bitnami/suitecrm] v8 fails to start with SUITECRM_SKIP_BOOTSTRAP=yes

### ISSUE THREAD

**Issue by fbecher** [bitnami/containers#24845]
### Name and Version

bitnami/suitecrm:8.2.3

### What steps will reproduce the bug?
```
/tmp/suitecrm823$ curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/suitecrm/docker-compose.yml > docker-compose.yml
/tmp/suitecrm823$ docker-compose up -d
/tmp/suitecrm823$ docker-compose down
```
add SUITECRM_SKIP_BOOTSTRAP=yes to docker-compose.yml

remove volume to simulate a container start from scratch against an existing database
/tmp/suitecrm823$ docker volume rm suitecrm823_suitecrm_data

/tmp/suitecrm823$ docker-compose up

See the logs:
```
suitecrm_1  | suitecrm 15:32:02.81 INFO  ==> An already initialized SuiteCRM database was provided, configuration will be skipped
suitecrm_1  | suitecrm 15:32:02.81 INFO  ==> Generating SuiteCRM configuration file
suitecrm823_suitecrm_1 exited with code 255
```
### What is the expected behavior?

The container should start correctly and perform all required configuration steps without the database setup.

The same procedure with version 7 is working.

### What do you see instead?

The container stops with exit code 255:
```
suitecrm_1  | suitecrm 15:32:02.81 INFO  ==> An already initialized SuiteCRM database was provided, configuration will be skipped
suitecrm_1  | suitecrm 15:32:02.81 INFO  ==> Generating SuiteCRM configuration file
suitecrm823_suitecrm_1 exited with code 255
```

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
