### ISSUE TITLE
[bitnami/symfony] Wrong Symfony version 6 in 5.4 images

### ISSUE THREAD

**Issue by pierre-kubica** [bitnami/containers#24848]
### Name and Version

bitnami/symfony:5.4

### What steps will reproduce the bug?

1. simply run "docker-compose up -d"

### What is the expected behavior?

Version of Symfony installed is 5.4.

### What do you see instead?

Version of Symfony installed is 6

### Additional information

I have a clue. 
In Docker file at https://github.com/bitnami/containers/blob/main/bitnami/symfony/5.4/debian-11/Dockerfile the Symfony tar contains a version Symfony 6 (I checked after downloaded and extracted it).

**Comment by dgomezleon** [comment]
Hi @pierre-kubica ,

Thanks for reporting it. 

We have created an internal task to fix the issue ASAP.  We will let you know once it is fixed.

**Comment by dgomezleon** [comment]
Hi @pierre-kubica ,

The latest release fixes the issue.
