### ISSUE TITLE
[bitnami/openldap] Provide arm64 platform image for OpenLDAP

### ISSUE THREAD

**Issue by SergiiTsymbal** [bitnami/containers#24850]
### Name and Version

bitnami/openldap

### What is the problem this feature will solve?

With Apple Silicon being the only version of MacBook Pro available these days (Feb 2023) developers are forced to run OpenLdap in AMD64 emulation which, according to Docker, "may have poor performance or fail, if run via emulation".

### What is the feature you are proposing to solve the problem?

The request is to provide OpenLDAP images for multiple platforms, specifically arm64 (Apple silicon) platform.

### What alternatives have you considered?

Other OpenLDAP images like https://hub.docker.com/r/osixia/openldap/tags However, that image no longer appears to be supported.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! I'm afraid I cannot guarantee an ETA of ARM-based containers in our open source catalog. However, as soon as there are news on the matter, we will let the community know.

**Comment by AGSaidi** [comment]
Looks like it’s there now https://hub.docker.com/r/bitnami/openldap/tags

**Comment by carrodher** [comment]
Yes, we recently announced ARM support for the majority of the catalog, see https://github.com/bitnami/charts/issues/7305#issuecomment-1443187343

**Comment by SergiiTsymbal** [comment]
Wow, that was fast :) Thank you!
