### ISSUE TITLE
[bitnami/telegraf] Match upstream tagging for compatibility

### ISSUE THREAD

**Issue by jhogarth** [bitnami/containers#24869]
### Name and Version

bitnami/telegraf:1.25

### What is the problem this feature will solve?

The official telegraf respository uses persistent tags of 1.24 or 1.25 to provide a rolling image for everything within that "major" version, with the latest minor (eg 1.25.1) release coming under that.

This allows for pulling in minor bug fixes but avoids any larger changes.

This also allows for easier switching of image in the workflows from that repository to the Bitnami one.

### What is the feature you are proposing to solve the problem?

Add 1.25 to the rolling tags in https://github.com/bitnami/containers/blob/main/bitnami/telegraf/1/debian-11/tags-info.yaml

### What alternatives have you considered?

Switching from the bitnami image to the other respository.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that this is not something that we can currently implement in our automated pipeline. The closest we can offer is the `1` rolling tag

**Comment by jhogarth** [comment]
Fair enough ... I felt it was worth asking. Thanks for your swift response.
