### ISSUE TITLE
[bitnami/wordpress] Support Post-Initialization steps

### ISSUE THREAD

**Issue by dploeger** [bitnami/containers#24871]
### Name and Version

bitnami/wordpress:6.1.1-debian-11-r49

### What is the problem this feature will solve?

I'm trying to configure the authLdap plugin for Wordpress on a clean install. Currently, I can only install and activate, but not configure it.

### What is the feature you are proposing to solve the problem?

As far as I understood it, Wordpress plugins are configured using options. The proposed feature would be to directly support options to add after initialization or to add a feature of post-initialization scripts (post-init.d-scripts are running too soon)

### What alternatives have you considered?

Manually configuring the plugin or trying something like Terraform post-provisioners, but both solutions are not really satisfying. :)

**Comment by dploeger** [comment]
Added an example PR how this could work

**Comment by javsalgar** [comment]
Hi!

Thank you for using Bitnami. Actually, we have the option of mounting custom init scripts, as you can see here

https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/rootfs/post-init.sh

**Comment by dploeger** [comment]
@javsalgar Hmmm. You're right. I used a post-init script for that... I guess I did something wrong then. I'll try again. Thanks a lot.

**Comment by dploeger** [comment]
Yes, that actually worked. Don't know why it didn't in the first place. Thanks again.
