### ISSUE TITLE
[bitnami/magento] SSL cert Let's encrypt / BncertTool  - install directory not found  and ctlsrcipt.sh  not found on my installation for the laterntive approach

### ISSUE THREAD

**Issue by jaaf85** [bitnami/containers#24870]
### Name and Version

bitnami/magento2.4

### What steps will reproduce the bug?

I am trying to initialize for the first time bncert toool to create my first ssl certificate. 
but it doesn't found the install dir 

```
root@e93158f700b8:/# /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory []: /opt/bitnami

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:
```
i tried the approach with the lateste Bncert-tool or the previous one and it's the same result unfortunately.

i a m trying to use the laternative approach , but i noticed that i don't have the ctlscript.sh on the installation toot. 

### What is the expected behavior?

generate ssl certfiicate by let'sencrypt 

### What do you see instead?
````
root@e93158f700b8:/# /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory []: /opt/bitnami

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:
```

### Additional information

_No response_

**Comment by javsalgar** [comment]
Hi,

Please note that the bncert tool is meant for the Bitnami OVA,  not the Bitnami containers. In this sense, you may need to use other alternatives for getting the certificates. In Kubernetes, it is common to use tools like cert-manager.

**Comment by jaaf85** [comment]
Hi,

thank you for your answer . i tried other means but it seems that with bitnami stacks is prefered to use Bitnami alternative approach with your own doc https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/.

But i don't find ctlscript.sh in my Magento container nor in the ocntainer github. could you please send or copy paste the script here in order to try you rlaternatiev approach ? 

Thank you

**Comment by javsalgar** [comment]
Hi,

Please note that the documentation you pasted are for AWS machines but not for Kubernetes. My advice would be to check the cert-manager documentation as well as the ingress documentation for starting.

https://cert-manager.io/docs/
https://cert-manager.io/docs/usage/ingress/
https://cert-manager.io/docs/configuration/acme/
