### ISSUE TITLE
[bitnami/postgresql] Unable to work around the `EXPOSE` keyword in the postgresql `Dockerfile` in GitLab services

### ISSUE THREAD

**Issue by trevor-vaughan** [bitnami/containers#24930]
### Name and Version

bitnami/postgresql:latest

### What steps will reproduce the bug?

1. Spin up a [GitLab Service](https://docs.gitlab.com/ee/ci/services/) using the `bitnami/postgresql` image
2. Spin up a second GitLab Service using the `bitnami/postgresql` image
  * Attempt to set either `POSTGRESQL_PORT_NUMBER=5433` (undocumented) or `POSTGRESQL_EXTRA_FLAGS='--port=5433'`
3. Attempt to connect to both services

### What is the expected behavior?

I will be able to successfully use both postgresql services on different ports

### What do you see instead?

The container that I attempt to move to `5433` cannot be connected to.

### Additional information

I believe that this is because the GitLab Services are using the `EXPOSE` hint in the `Dockerfile` to limit the exposed ports.

I have not seen the same behavior with the `bitnami/keycloak` image which does not appear to have the `EXPOSE` keyword set.

**Comment by trevor-vaughan** [comment]
OK, `POSTGRESQL_PORT_NUMBER` actually worked (after I fixed a typo) but it's not documented in the README.

So, I guess this turns into a "please document the undocumented environment variables" ticket :-D

**Comment by javsalgar** [comment]
Hi,

Thank you so much for letting us know! Would you like to add the reference to that missing env var in the README.md file?

**Comment by trevor-vaughan** [comment]
@javsalgar I don't mind but there seemed to be quite a few undocumented variables in there and I haven't a clue what most of them do.

**Comment by carrodher** [comment]
Hello everyone,

We're thrilled to announce a significant enhancement to our container environments. Now, all the environment variables used by the containers are conveniently listed in the README for easy reference. You can find the detailed tables at [**Customizable Environment Variables**](https://github.com/bitnami/containers/tree/main/bitnami/postgresql#customizable-environment-variables) and [**Read-Only Environment Variables**](https://github.com/bitnami/containers/tree/main/bitnami/postgresql#read-only-environment-variables).

These tables provide comprehensive information:
- **Customizable Environment Variables:** Lists the environment variables that users can modify, along with their default values.
- **Read-Only Environment Variables:** Presents non-modifiable environment variables with their "hardcoded" values.

It's worth noting that these tables are automatically maintained by our test and release pipeline. Any additions or removals of environment variables trigger updates to ensure the information is always current.

We believe that this update will empower users to customize their deployments more effectively. Your feedback is valuable to us. If you have any questions or suggestions, please feel free to add a new comment in this thread.
