### ISSUE TITLE
Jasperreport:8.1.0 stuck at running upgrade scripts

### ISSUE THREAD

**Issue by irparajababu** [bitnami/containers#24944]
### Name and Version

bitnami/jasperreports:8.1.0

### What steps will reproduce the bug?

I run the bitnami/jasperreports:8.1.0 docker image I used the environment variable JASPERREPORTS_SKIP_BOOTSTRAP=yes

docker container stuck at Running the upgrade script for two days and still not moving forward I am not able to identify the issue and how to run the debug mode to see what's going on.
```
jasperreports 17:26:41.58
jasperreports 17:26:41.58 Welcome to the Bitnami jasperreports container
jasperreports 17:26:41.59 Subscribe to project updates by watching https://github.com/bitnami/containers
jasperreports 17:26:41.59 Submit issues and feature requests at https://github.com/bitnami/containers/issues
jasperreports 17:26:41.59
jasperreports 17:26:41.60 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
jasperreports 17:26:41.61 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
jasperreports 17:26:41.65 INFO  ==> Configuring port numbers
jasperreports 17:26:41.68 INFO  ==> Ensuring Tomcat directories exist
jasperreports 17:26:41.69 INFO  ==> Deploying Tomcat from scratch
jasperreports 17:26:41.92 INFO  ==> Ensuring JasperReports directories exist
jasperreports 17:26:41.93 INFO  ==> Trying to connect to the database server
jasperreports 17:26:41.96 INFO  ==> Configuring JasperReports with settings provided via environment variables
jasperreports 17:26:42.11 INFO  ==> An already initialized JasperReports database was provided, configuration will be skipped
jasperreports 17:26:42.11 INFO  ==> Executing upgrade scripts
jasperreports 17:26:42.12 INFO  ==> Running upgrade script
```

### What is the expected behavior?

The expected thing is it should be run without instilling the database scripts.

### What do you see instead?

It was stuck running upgrade scripts for two days

### Additional information

This jasper reports container is also coming up very slowly it is taking more than 30 minutes. when we are not using the `JASPERREPORTS_SKIP_BOOTSTRAP=yes` environment variable.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
