### ISSUE TITLE
current redis images do not include or support openssl 3.0

### ISSUE THREAD

**Issue by justinschw** [bitnami/containers#25015]
### Name and Version

bitnami/redis:6.2

### What steps will reproduce the bug?

Running the x86_64 version of redis in docker on macOS
Installed version of openssl is 1.1.1n
Also when I forked the repo and modified the dockerfile to create a custom build with openssl 3.0, I get a runtime error complaining that it can't find openssl 1.1.1.

### What is the expected behavior?

1. docker image should have the latest openssl lib, 3.0
2. bitnami redis package should support running with the latest openssl lib, 3.0

### What do you see instead?

```console
$ docker run -u root -it --platform=linux/amd64 -e "REDIS_PASSWORD=abc123" bitnami/redis:latest /bin/sh
...

# find -type f -name libssl.so.*
./usr/lib/x86_64-linux-gnu/libssl.so.1.1

# apt list --installed | grep libssl
libssl1.1/now 1.1.1n-0+deb11u4 amd64 [installed,local]
```

Running custom built with openssl 3.0 instead:
```
redis 18:03:45.05 
redis 18:03:45.08 Welcome to the Bitnami redis container
redis 18:03:45.10 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 18:03:45.13 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 18:03:45.15 
redis 18:03:45.17 INFO  ==> ** Starting Redis setup **
redis 18:03:45.34 INFO  ==> Initializing Redis
redis 18:03:45.54 INFO  ==> Setting Redis config file
redis 18:03:45.73 INFO  ==> ** Redis setup finished! **

redis 18:03:45.85 INFO  ==> ** Starting Redis **
redis-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Additional information

This happens for redis 7.0.8 as well

**Comment by haloxinyu** [comment]
I have the same questions, we want that redis cryptographic operations compliant with NIST FIPS 140-2, but the openssl version used by bitnami redis 7.0.10 is 1.1.1n which is not FIPS compliant.
Is there a way to change the openssl version of redis image?

**Comment by carrodher** [comment]
Hi @haloxinyu, the Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

From those distros, the PhotonOS ones are FIPS-compliant, using the required system packages for that. In the case of the OpenSource catalog, we are using the openssl package included by the distro.

**Comment by haloxinyu** [comment]
@carrodher 
Thank you very much! That's the information I required.

**Comment by mamachanko** [comment]
[OpenSSL 1.1.1 is now EOL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/index.html). At the time of writing `openssl (3.0.11-1~deb12u2)` is the stable version as considered by Debian https://packages.debian.org/source/stable/openssl.

What do think about re-opening this issue, @carrodher? By now it's a reasonable request I reckon.

**Comment by carrodher** [comment]
Since we are using the system packages, the openssl version is automatically updated to what is present in the Debian package repo:
```console
$ docker run --rm -it bitnami/redis:7.2 openssl version
redis 09:40:20.38 INFO  ==>
redis 09:40:20.38 INFO  ==> Welcome to the Bitnami redis container
redis 09:40:20.38 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis 09:40:20.38 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 09:40:20.38 INFO  ==>

OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)
```

**Comment by mamachanko** [comment]
Oh wow you are absolutely right! This is perfect. 😍
