### ISSUE TITLE
[bitnami/postgresql] Unable to set Postgresql config flag with POSTGRESQL_EXTRA_FLAGS if the value contains space

### ISSUE THREAD

**Issue by henribru** [bitnami/containers#25013]
### Name and Version

bitnami/postgresql:15.2.0

### What steps will reproduce the bug?

Run `docker run -e POSTGRESQL_DATABASE=foo -e POSTGRESQL_USERNAME=foo -e POSTGRESQL_PASSWORD=foo -e POSTGRESQL_EXTRA_FLAGS="-c default_transaction_isolation='read committed'" bitnami/postgresql` 

### What is the expected behavior?

I would expect to be able to set `default_transaction_isolation` even if the value contains a space, either by quoting it like in the reproduction or escaping the space or something. Maybe it's possible and I'm just missing something very obvious, but I can't figure it out.

### What do you see instead?

Fails with:
```
2023-02-23 16:37:36.352 GMT [1] FATAL:  invalid value for parameter "default_transaction_isolation": "'read"
2023-02-23 16:37:36.352 GMT [1] HINT:  Available values: serializable, repeatable read, read committed, read uncommitted.
```

### Additional information

The parsing happens at https://github.com/bitnami/containers/blob/218f5378c1d0c961078108981215ffed53092091/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql/run.sh#L19-L22. Looks like it's just splitting on space and also disabling backslash escapes.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by mehtadev17** [comment]
What version was this fixed for?

**Comment by javsalgar** [comment]
It seems that there was no contribution and the stale bot closed. Would you like to submit a PR fixing the issue?

**Comment by cowclaw** [comment]
I just stumbled upon the problem as well. If we'd omit the `-r` flag given to read in 

https://github.com/bitnami/containers/blob/218f5378c1d0c961078108981215ffed53092091/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql/run.sh#L19-L22

it would work with escaping the space in "repeatable read" with a backslash (`repeatable\ read`). 

I understand however that this is not possible preserve backwards compatibility and not break ones existing solutions. 

I thus suggest to introduce a new environment variable `POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION` and extending `run.sh` to honor it:

```bash
if [[ -n "${POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION:-}" ]]; then
    flags+=("-c" "default_transaction_isolation=$POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION")
fi
```
this way we could simply alter the default transaction isolation from within a docker-compose file by setting the environment variable `POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION: 'repeatable read'`.

I'd be happy to provide a PR. 

@javsalgar What do you think?

**Comment by javsalgar** [comment]
Hi!

That sounds great! If you want to submit a PR with the feature we'll be happy to review it so new releases contain the feature. Thank you!
