### ISSUE TITLE
[bitnami/kafka] broken KAFKA_HEAP_OPTS handling

### ISSUE THREAD

**Issue by Garreat** [bitnami/containers#25389]
### Name and Version

bitnami/kafka:3.4.0-debian-11-r3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. set KAFKA_HEAP_OPTS to any valid string eg:
```
environment:
  - KAFKA_HEAP_OPTS="-Xmx1536m -Xms1536m"
 ```

2. Run the container

### What is the expected behavior?

Kafka should start with provided Java options

### What do you see instead?

`Error: Could not find or load main class "-Xmx1536m -Xms1536m"`

**Comment by dgomezleon** [comment]
Hi @Garreat ,

This should work:

```
environment:
  - KAFKA_HEAP_OPTS=-Xmx1536m -Xms1536m
```
