### ISSUE TITLE
wordpress-nginx doesn't respect WORDPRESS_ENABLE_HTTPS in multisite mode

### ISSUE THREAD

**Issue by binaryfire** [bitnami/containers#25387]
### Name and Version

bitnami/wordpress-nginx:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Launch the container with these env variables:

      WORDPRESS_DATABASE_HOST: wordpress-mysql
      WORDPRESS_DATABASE_PORT_NUMBER: '3306'
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: password
      WORDPRESS_ENABLE_MULTISITE: 'yes'
      WORDPRESS_MULTISITE_HOST: wp.mysite.dev
      WORDPRESS_MULTISITE_NETWORK_TYPE: subdirectory
      WORDPRESS_AUTO_UPDATE_LEVEL: minor
      WORDPRESS_ENABLE_REVERSE_PROXY: 'yes'
      WORDPRESS_ENABLE_HTTPS: 'yes'
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: password

### What is the expected behavior?

The main domain multisite domain should be https://wp.mysite.dev  because WORDPRESS_ENABLE_HTTPS is set to yes. 

### What do you see instead?

The site URL is http://wp.mysite.dev. Tried WORDPRESS_SCHEME instead of WORDPRESS_ENABLE_HTTPS as well- same problem.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
