### ISSUE TITLE
[bitnami/pgbouncer] Support SO_REUSEPORT in pgbouncer

### ISSUE THREAD

**Issue by intellix** [bitnami/containers#25382]
### Name and Version

bitnami/pgbouncer:1.18.0

### What is the problem this feature will solve?

pgBouncer is only single threaded and can only take advantage of 1x CPU. Scaling pgBouncer by increasing replicas in a kubernetes cluster doesn't work well because the standard load balancing doesn't distribute load well and you'll essentially have 1x pgbouncer taking all the traffic and struggling on it's own

### What is the feature you are proposing to solve the problem?

Since pgBouncer 1.12.0, they've added the ability to use SO_REUSEPORT to run multiple instances of pgBouncer on the same container and have the traffic distributed evenly. 

> Add a setting to turn on the SO_REUSEPORT socket option. On some operating systems, this allows running multiple PgBouncer instances on the same host listening on the same port and having the kernel distribute the connections automatically.

If this image supports it, you could scale the container vertically and make better use of a single CPU: http://www.pgbouncer.org/config.html#so_reuseport

### What alternatives have you considered?

Creating my own simple container to take advantage of it. I've tried scaling horizontally in a kubernetes cluster, but the traffic is mostly hitting 1x pod. I've tried scaling vertically with 1x pgBouncer instance inside a container and it struggles due to being single-threaded.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! If you want to speed up the process, would you like to add a PR exposing a variable to change that setting? It should go under the libpgbouncer.sh script.
