### ISSUE TITLE
Ghost DB endpoint not found

### ISSUE THREAD

**Issue by Notespeak** [bitnami/containers#25393]
### Name and Version

docker.io/bitnami/ghost:5 , docker.io/bitnami/mysql:8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I am using ubuntu 22.04 with Docker version 20.10.12, build 20.10.12-0ubuntu4.
2. My config file is the default ghost docker-compose file. No changes at all.

I am currently facing issues with the Ghost Bitnami Docker image not working with out of the box docker-compose file. After downloading the image and running it using the docker-compose command, I can clearly see, that the Ghost container is unable to initialize a DB connection `ghost_1  | ghost 22:55:42.89 ERROR ==> Could not connect to the database`. Checking the docker logs, I have spotted an error, that predates this problem: `mysql_1  | find: '/docker-entrypoint-startdb.d/': No such file or directory`.

The full error looks like this:
```
ghost_1  | ghost 22:53:42.38 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
ghost_1  | ghost 22:53:42.39 INFO  ==> Ensuring Ghost directories exist
ghost_1  | ghost 22:53:42.40 INFO  ==> Trying to connect to the database server
mysql_1  | find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql_1  | mysql 22:54:01.99 INFO  ==> Stopping mysql
mysql_1  | mysql 22:54:07.09 INFO  ==> ** MySQL setup finished! **
mysql_1  | 
mysql_1  | mysql 22:54:07.18 INFO  ==> ** Starting MySQL **
mysql_1  | 2023-02-25T22:54:07.777451Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.32) starting as process 1
mysql_1  | 2023-02-25T22:54:07.802995Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql_1  | 2023-02-25T22:54:08.364039Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql_1  | 2023-02-25T22:54:08.971957Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1  | 2023-02-25T22:54:08.972110Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql_1  | 2023-02-25T22:54:09.050178Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
mysql_1  | 2023-02-25T22:54:09.051451Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.32'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
ghost_1  | ghost 22:55:42.89 ERROR ==> Could not connect to the database
```

### What is the expected behavior?

A successful ghost install.

### What do you see instead?

An exited ghost container, because it's unable to establish a connection.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
