### ISSUE TITLE
[bitnami/pgbouncer] Expose LOG Settings?

### ISSUE THREAD

**Issue by apiszcz** [bitnami/containers#25392]
### Name and Version

pgbouncer

### What is the problem this feature will solve?

Allow log setting parameters.

### What is the feature you are proposing to solve the problem?

Expose environment variables for LOG settings.
```
#log_connections = 0
#log_disconnections = 0
```
### What alternatives have you considered?

config file?

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! We are open to contributions, would you like to add a PR that exposes two variables for that setting?

**Comment by apiszcz** [comment]
Not sure on how to do that. Is each configuration parameter a separate activity? Seems like offering an inline configuration parameter would be helpful, sort of like the extra command line arguments. 
--configfiledata="key=val,key=val" or something better?

**Comment by javsalgar** [comment]
Hi,

In libpgbouncer.sh you can see how we are setting the configuration settings. It would be adding a similar environment variable.

**Comment by AntonFriberg** [comment]
Seems supported nowadays. https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L294
