### ISSUE TITLE
[bitnami/openldap] Insufficient access (50) error on OpenShift

### ISSUE THREAD

**Issue by zcahana** [bitnami/containers#25396]
### Name and Version

bitnami/openldap:2.6.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In an OpenShift environment, create the following OpenLDAP deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: Always
          env:
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_ADMIN_PASSWORD
              value: adminpassword
            - name: LDAP_USERS
              value: user01,user02
            - name: LDAP_PASSWORDS
              value: password01,password02
            - name: LDAP_USER_DC
              value: default
            - name: LDAP_GROUP
              value: default
            - name: LDAP_ROOT
              value: dc=example,dc=org
            - name: LDAP_ALLOW_ANON_BINDING
              value: "no"
            - name: BITNAMI_DEBUG
              value: "true"
          ports:
            - name: tcp-ldap
              containerPort: 1389
          readinessProbe:
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 2
            exec:
              # This probe validates that the slapd process (the actual LDAP
              # server running within the openldap container) has been started.
              # Note that slapd is also temporarily started in the background as part
              # of the initialization phase of the container, so we specifically check
              # for its PID to ensure it's the real LDAP server running as PID 1.
              command:
                - bash
                - -c
                - "[ $(pidof slapd) == 1 ]"
```

The pod created consistently crashes on startup with exit code 50;
Its logs shows the following:
```
02:29:21.37 INFO  ==> ** Starting LDAP setup **
 02:29:21.40 INFO  ==> Validating settings in LDAP_* env vars
 02:29:21.40 INFO  ==> Initializing OpenLDAP...
 02:29:21.41 DEBUG ==> Ensuring expected directories/files exist...
 02:29:21.42 INFO  ==> Creating LDAP online configuration
 02:29:21.42 INFO  ==> Creating slapd.ldif
 02:29:21.44 INFO  ==> Starting OpenLDAP server in background
63fac401.1acad064 0x7f6725f22740 @(#) $OpenLDAP: slapd 2.6.4 (Feb 22 2023 11:46:45) $
        @e337c9d3914b:/bitnami/blacksmith-sandox/openldap-2.6.4/servers/slapd
63fac401.1b56cb82 0x7f6725f22740 slapd starting
 02:29:22.45 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
63fac402.1b232a07 0x7f66e5180700 conn=1000 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63fac402.1b243ca8 0x7f66e5180700 conn=1000 op=0 BIND dn="" method=163
63fac402.1b24c3ed 0x7f66e5180700 conn=1000 op=0 BIND authcid="gidNumber=0+uidNumber=1000740000,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1000740000,cn=peercred,cn=external,cn=auth"
63fac402.1b250692 0x7f66e5180700 conn=1000 op=0 BIND dn="gidNumber=0+uidNumber=1000740000,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
63fac402.1b2573e1 0x7f66e5180700 conn=1000 op=0 RESULT tag=97 err=0 qtime=0.000009 etime=0.000098 text=
SASL username: gidNumber=0+uidNumber=1000740000,cn=peercred,cn=external,cn=auth
SASL SSF: 0
63fac402.1b276998 0x7f66e497f700 conn=1000 op=1 MOD dn="olcDatabase={2}mdb,cn=config"
63fac402.1b280f09 0x7f66e497f700 conn=1000 op=1 MOD attr=olcSuffix
63fac402.1b28d329 0x7f66e497f700 conn=1000 op=1 RESULT tag=103 err=50 qtime=0.000016 etime=0.000134 text=
ldap_modify: Insufficient access (50)
63fac402.1b29d9d0 0x7f66e5180700 conn=1000 op=2 UNBIND
modifying entry "olcDatabase={2}mdb,cn=config"

63fac402.1b2a67ba 0x7f66e5180700 conn=1000 fd=12 closed
63fac402.1b6e6605 0x7f66e5981700 daemon: shutdown requested and initiated.
63fac402.1b70a61a 0x7f66e5981700 slapd shutdown: waiting for 0 operations/tasks to finish
63fac402.1b773f49 0x7f6725f22740 slapd stopped.
```

### What is the expected behavior?

The pod should be running and able to serve LDAP queries.

### What do you see instead?

The pod is in CrashLoopBackOff state.

### Additional information

On a typical OpenShift environment, common pods (running with the default (`restricted`) [SecurityContextConstraint](https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html) are automatically assigned a UID within a UID range assigned to their namespace. In this particular example, the `openldap` has been assigned `uid=1000740000`.

[Starting with](https://github.com/bitnami/containers/pull/24902/commits/16a314920e8db308ccbeeded886ff8b250ee3448#diff-e3475f86379af4ff39cb9b913e41c53d0d63afab71771af1d7fcc4f4cb08b2fb) `bitnami:openldap:2.6.4`, there's seems to be a `slapd.ldif` file created at pod bootstrap time (via `libopenldap.sh`), which assumes the running UID is 1001 (`uidNumber=1001`). Later in `libopenldap.sh`, there's an attempt to inject the current UID with this command:
```sh
! am_i_root && replace_in_file "${LDAP_SHARE_DIR}/slapd.ldif" "uidNumber=0" "uidNumber=$(id -u)"
```

But this command attempts to replace `uidNumber=0` where in practice the file includes `uidNumber=1001` so no replacements are actually done, and the final configuration in `slapd.ldif` still includes `uidNumber=1001`.

The fix could be as simple as modifying that script to generate `slapd.ldif` with `uidNumber=0` so that it can be replaced with the actual UID (but there might be additional implications that I'm unaware of...).

Note that a workaround to this could be to deploy the OpenLDAP pod with `runAsUser: 1001`, but this requires running with a more privileged SCC than the default one, such as `nonroot`.

**Comment by zcahana** [comment]
> Your logic change approach makes sense, would you be open to contributing this change via a PR? We'd be glad to review and help with the release.

@corico44 definitely, I'll follow-up with a PR soon.

**Comment by stevenschader** [comment]
I too fell into this problem running on OCP 4.12.x
Locally I fixed it temp in my Container file with :
```
USER root
RUN sed -i 's/uidNumber=0/uidNumber=1001/g' /opt/bitnami/scripts/libopenldap.sh
```
my deployment went from failing to working like it used to on 2.6.3.
Thanks!

**Comment by zcahana** [comment]
@corico44 can you please help move this forward? There's a PR waiting for review in #25658.

**Comment by zcahana** [comment]
So, #25658 was successfully merged yesterday, but the fixed image hasn't been published yet.
What else needs to be done in order to rebuild and publish it?

@corico44 @aoterolorenzo
