### ISSUE TITLE
Replacing MOODLE_REVERSEPROXY with MOODLE_REVERSE_PROXY and MOODLE_SSLPROXY with MOODLE_SSL_PROXY is not reflected in READMY.md

### ISSUE THREAD

**Issue by myroslav-b** [bitnami/containers#25650]
### Name and Version

bitnami/moodle

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Open [https://github.com/bitnami/containers/tree/main/bitnami/moodle](https://github.com/bitnami/containers/tree/main/bitnami/moodle)
2. Find the section [Configuration/Environment variables/User and Site configuration](https://github.com/bitnami/containers/tree/main/bitnami/moodle#user-and-site-configuration)
3. Find the lines 
```
MOODLE_REVERSEPROXY: Allows you to activate the reverseproxy feature of Moodle. Default: no
MOODLE_SSLPROXY: Allows you to activate the sslproxy feature of Moodle. Default: no
```

### What is the expected behavior?

It is expected that the environment variables MOODLE_REVERSEPROXY and MOODLE_SSLPROXY is used for **all versions** of the bitnami/moodle image.

### What do you see instead?

Starting with version 3.9 (I think) of the Bitnami Moodle image, are used environment variables MOODLE_REVERSE_PROXY and MOODLE_SSL_PROXY.
For new versions of images variant MOODLE_REVERSEPROXY and MOODLE_SSLPROXY **does not work**.

### Additional information

I have not found information about this change in any currently available documentation from bitnami.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by andresjz** [comment]
This should be reopned since has not been fixed yet, all new releases are facing same issue. 
One workaround is to edit manually /bitnami/moodle/config.php but it needs to be handled by ENV var
