### ISSUE TITLE
[bitnami/kong] ARM support

### ISSUE THREAD

**Issue by tobsen111** [bitnami/containers#25762]
### Name and Version

bitnami/kong:3.2.0

### What is the problem this feature will solve?

Hi,

thanks for building and publishing bitnami ARM containers. 
Is there a reason why the kong image is not available for arm?
Can I contribute somehow to make this possible?

### What is the feature you are proposing to solve the problem?

ARM based build of kong image

**Comment by carrodher** [comment]
At this moment there are some limitations in our internal build, test & release pipeline when there are discrepancies in terms of packages between AMD and ARM.
