### ISSUE TITLE
bitnami/keycloak 21 release estimate date?

### ISSUE THREAD

**Issue by jasontseu-bgroup** [bitnami/containers#25814]
### Name and Version

bitnami/keycloak:21.0.0

### What is the problem this feature will solve?

Would like to request for a follow up release for keycloak 21 and helm chart.

### What is the feature you are proposing to solve the problem?

Update the Keycloak before EOL cycle

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by kherock** [comment]
Any progress to report on this?

**Comment by carrodher** [comment]
It's still in progress, we will update this ticket once released. Thanks for your patience

**Comment by jasontseu-bgroup** [comment]
Is there any possible opensource the stacksmith packaging process? which allow us to submit PR or work for it :)

**Comment by carrodher** [comment]
Unfortunately, those intermediate artifacts are not open-source. At this moment the release of the new major version is blocked because of an issue with the metrics already reported and with a fix in progress at https://github.com/aerogear/keycloak-metrics-spi/pull/157

**Comment by jasontseu-bgroup** [comment]
Yes. saw their release.

https://github.com/aerogear/keycloak-metrics-spi/releases/tag/3.0.0

**Comment by dyonathakramer** [comment]
Any progress on this?

**Comment by RaffaelGrob** [comment]
Can't wait for the new images. Are you far away from releasing?

**Comment by carrodher** [comment]
We can't provide an ETA, it depends on the team's capacity and other initiatives we are working on. We will update this thread once done

**Comment by pstrobl96** [comment]
Is there anything you need to help with?

**Comment by joancafom** [comment]
I am glad to announce that the latest version of Keycloak (21.0.2) was released some hours ago and both the [container image](https://github.com/bitnami/containers/commit/77d3ca972860f49f11dab4f975af37da24640385) and [chart](https://github.com/bitnami/charts) are currently available! 🎉

```bash
$ docker run --rm -it bitnami/keycloak kc.sh --version
...
Keycloak 21.0.2
```

**Comment by amir4895** [comment]
https://github.com/aerogear/keycloak-metrics-spi/issues/155
this issue still reproducing in all KC 21.X version
