### ISSUE TITLE
[bitnami/openldap] Authentication fails on ec2 host, but works on local host (Mac OS Ventura)

### ISSUE THREAD

**Issue by jrunrun** [bitnami/containers#25868]
### Name and Version

openldap:2.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Building and running the ldap docker container locally on my mac host works.

By works I mean:
1) My backend container (django rest framework) can authenticate and communicate with my ldap docker container to fetch user attributes.
2) I can use ldapsearch (at cmd line) or apache directory studio to authenticate and CRUD/mange user attributes

However, once I deploy to ec2 (ubuntu) using same exact docker-compose.yml file (all the same config, ENV variables) the authentication to ldap FAILS for both 1 & 2 above.

Even using ldapsearch locally on the ec2 host fails to authenticate. I see the requests hitting ldap and receive a response from ldap:  ldap_bind: Invalid credentials (49).

It’s really weird. I’ve tried to rebuild container and no luck.

### What is the expected behavior?

I would be able to authenticate with the admin user / password defined in the docker-compose.yml file.

E.g. 
```
 environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
```
### What do you see instead?

Response from ldap: ldap:  
ldap_bind: Invalid credentials (49)

Logs from container:
```
 18:36:22.49 INFO  ==> ** Starting LDAP setup **
 18:36:22.52 INFO  ==> Validating settings in LDAP_* env vars
 18:36:22.59 INFO  ==> Initializing OpenLDAP...
 18:36:22.59 DEBUG ==> Ensuring expected directories/files exist...
 18:36:22.61 INFO  ==> Using persisted data
 18:36:22.61 INFO  ==> ** LDAP setup finished! **
```
 18:36:22.64 INFO  ==> ** Starting slapd **
```
63ff9b26.26a442ce 0x7f29a1beb740 @(#) $OpenLDAP: slapd 2.6.4 (Feb 22 2023 11:46:45) $
	@e337c9d3914b:/bitnami/blacksmith-sandox/openldap-2.6.4/servers/slapd
63ff9b26.2821b80d 0x7f29a1beb740 slapd starting
63ff9b4c.243f2d75 0x7f2960e49700 conn=1000 fd=12 ACCEPT from IP=172.22.0.1:51264 (IP=0.0.0.0:1389)
63ff9b4c.2441446c 0x7f295bfff700 conn=1000 op=0 BIND dn="cn=justin,dc=example,dc=org" method=128
63ff9b4c.24431328 0x7f295bfff700 conn=1000 op=0 RESULT tag=97 err=49 qtime=0.000026 etime=0.000175 text=
63ff9b4c.2447ed45 0x7f2960e49700 conn=1000 op=1 UNBIND
63ff9b4c.2449ab0e 0x7f2960e49700 conn=1000 fd=12 closed
 20:39:09.17 INFO  ==> ** Starting LDAP setup **
 20:39:09.20 INFO  ==> Validating settings in LDAP_* env vars
 20:39:09.21 INFO  ==> Initializing OpenLDAP...
 20:39:09.21 DEBUG ==> Ensuring expected directories/files exist...
 20:39:09.23 INFO  ==> Using persisted data

 20:39:19.26 INFO  ==> ** LDAP setup finished! **
 20:39:19.28 INFO  ==> ** Starting slapd **
63ffb7f7.113f67e1 0x7fee8fad7740 @(#) $OpenLDAP: slapd 2.6.4 (Feb 22 2023 11:46:45) $
	@e337c9d3914b:/bitnami/blacksmith-sandox/openldap-2.6.4/servers/slapd
63ffb7f7.11d77843 0x7fee8fad7740 slapd starting
63ffb804.33295542 0x7fee4ed35700 conn=1000 fd=12 ACCEPT from IP=172.22.0.1:47002 (IP=0.0.0.0:1389)
63ffb804.332b6937 0x7fee4ed35700 conn=1000 op=0 BIND dn="cn=justin,dc=example,dc=org" method=128
63ffb804.332d3749 0x7fee4ed35700 conn=1000 op=0 RESULT tag=97 err=49 qtime=0.000023 etime=0.000174 text=
63ffb804.33321210 0x7fee4e534700 conn=1000 op=1 UNBIND
63ffb804.33341ecb 0x7fee4e534700 conn=1000 fd=12 closed
63ffb860.3b72583a 0x7fee4ed35700 conn=1001 fd=12 ACCEPT from IP=172.22.0.1:47018 (IP=0.0.0.0:1389)
63ffb860.3b73cf6c 0x7fee4e534700 conn=1001 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
63ffb860.3b755e18 0x7fee4e534700 conn=1001 op=0 RESULT tag=97 err=49 qtime=0.000023 etime=0.000147 text=
63ffb860.3b79962d 0x7fee4ed35700 conn=1001 op=1 UNBIND
63ffb860.3b7b3c54 0x7fee4ed35700 conn=1001 fd=12 closed
 ```

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml that we can use to reproduce the issue? Could you confirm that you do not have any volume from a previous installation?

**Comment by jrunrun** [comment]
Thank you so much for looking at this.

version: "3.3"
   
services:
  db:
    container_name: cdapp-services-postgres-dev
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
  web:
    container_name: cdapp-services-web-dev
    build:
      context: .
      dockerfile: Dockerfile_Dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  memcached:
    container_name: cdapp-services-memcached-dev
    image: 'bitnami/memcached:latest'
    expose:
      - "11211"
    entrypoint:
      - memcached
      - -m 64
    depends_on:
      - web
  openldap:
    container_name: cdapp-services-openldap-dev
    image: docker.io/bitnami/openldap:2.6
    # https://hub.docker.com/r/bitnami/openldap/
    user: root
    # https://docs.bitnami.com/tutorials/work-with-non-root-containers/
    expose:
      - "1389"
    ports:
      - "1389:1389"
      # - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=n639986,n420201
      - LDAP_PASSWORDS=password1,password2
      - LDAP_GROUP=Texas
    volumes:
      - 'openldap_data:/bitnami/openldap'
  
volumes:
  static_volume:
  openldap_data:
    driver: local

**Comment by jrunrun** [comment]
Same issue on two different ec2 instances. Both have never had a ldap volume.

**Comment by jotamartos** [comment]
Hi @jrunrun,

As you are using a custom configuration, can you try using the default configuration and try to log in to the server in both environments (locally and AWS)? We would like to verify if the issue is with the solution itself or with the parameters you are setting. 

Thanks

**Comment by jrunrun** [comment]
Hi @jotamartos -- sorry for delay. yes, I will verify default config tomorrow and follow up. Again, thank you so much for the help!

**Comment by jrunrun** [comment]
Hi @jotamartos  -- yes, same issue. I removed everything in the docker-compose.yml file except for the ports I need to expose to localhost to do the ldapsearch test.

  openldap:
    container_name: cdapp-services-openldap-prod
    image: docker.io/bitnami/openldap:2.6
    user: root
    expose:
      - "1389"
    ports:
      - "1389:1389"
      # - "1636:1636"
    volumes:
      - 'openldap_data:/bitnami/openldap'
      
   
I also did the following to remove all volumes, containers and images:
sudo docker volume prune
sudo docker system prune

Then I did:
sudo docker-compose -f docker-compose.yml up --build   

Same issue. It works on Mac, but it doen't on ec2 host (Ubuntu).

Ubuntu OS version:
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jotamartos** [comment]
Hi @jrunrun,

I just launched this solution (default docker-compose.yml file) in a brand new Ubuntu server and everything worked as expected 

```
ubuntu@ip-172-31-25-4:~/containers/bitnami/openldap$ ldapwhoami -D 'cn=admin,dc=example,dc=org' -w 'adminpassword' -H ldap://localhost:1389
dn:cn=admin,dc=example,dc=org
ubuntu@ip-172-31-25-4:~/containers/bitnami/openldap$ ldapsearch -D 'cn=admin,dc=example,dc=org' -w 'adminpassword' -s 'one' -b 'ou=users,dc=example,dc=org' -H ldap://localhost:1389
# extended LDIF
#
# LDAPv3
# base <ou=users,dc=example,dc=org> with scope oneLevel
# filter: (objectclass=*)
# requesting: ALL
#

# user01, users, example.org
dn: cn=user01,ou=users,dc=example,dc=org
cn: User1
cn: user01
sn: Bar1
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
userPassword:: cGFzc3dvcmQx
uid: user01
uidNumber: 1000
gidNumber: 1000
homeDirectory: /home/user01

# user02, users, example.org
dn: cn=user02,ou=users,dc=example,dc=org
cn: User2
cn: user02
sn: Bar2
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
userPassword:: cGFzc3dvcmQy
uid: user02
uidNumber: 1001
gidNumber: 1001
homeDirectory: /home/user02

# readers, users, example.org
dn: cn=readers,ou=users,dc=example,dc=org
cn: readers
objectClass: groupOfNames
member: cn=user01,ou=users,dc=example,dc=org
member: cn=user02,ou=users,dc=example,dc=org

# search result
search: 2
result: 0 Success

# numResponses: 4
# numEntries: 3
```

As you can see here, I could query the server and obtain the requested information. This is an Ubuntu (22.04) x64 (not ARM) machine in EC2. If your deployment doesn't work as expected, please ensure you are deploying it on top of a x64 instance.
