### ISSUE TITLE
Sensitive information disclosure

### ISSUE THREAD

**Issue by zoomzoomcloud** [bitnami/containers#26477]
### Name and Version

bitnami/moodle:4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deployed containers are leaking sensitive information. Use the following commands to reproduce the issue:

`curl -ski https://example.com/composer.lock`
`curl -ski https://example.com/composer.json`
`curl -ski https://example.com/package.json`
etc.

### What is the expected behavior?

The containers are not serving sensitive info such as package manager config files etc that could aid an attacker in targeting attacks against the web server and/or its hosted application.

### What do you see instead?

na

### Additional information

na

**Comment by carrodher** [comment]
Could you provide more info about how the container is being deployed? It would be nice to have the exact instructions (i.e `docker run` command) or docker-compose template in order to reproduce the issue on our side.

**Comment by zoomzoomcloud** [comment]
I have two deployments; the first one was on AWS and follows this article: https://aws.amazon.com/blogs/publicsector/modernize-moodle-lms-aws-serverless-containers/. As soon as we got it deployed we got alerts from a security vendor that we're leaking info. They analyzed the leaked info about the packages and found no security issues with them but we should not broadcast what packages are being used by the workload. From there, I replicated the issue on my local system with the following commands: 
`curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/moodle/docker-compose.yml > docker-compose.yml` 
then
`docker-compose up -d`
Than the curl commands I noted above.

**Comment by andresbono** [comment]
Those files are publicly available in the source code of Moodle, e.g. https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/composer.lock. In any case, there is no reason to expose them if it is not necessary. We are going to review the configuration and we will update this issue accordingly. Thanks!

**Comment by andresbono** [comment]
@zoomzoomcloud, https://github.com/bitnami/containers/pull/27398 provides a fix, see the `postunpack.sh` script.

Please, try the latest container version and let us know if you find any problem. Thanks for reporting this issue!

**Comment by andresbono** [comment]
Hi @zoomzoomcloud, the [Gruntfile.js](https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/Gruntfile.js) file is not listed in [Moodle docs: Apache - Hiding internal paths](https://docs.moodle.org/401/en/Apache#Hiding_internal_paths), but I think it makes sense to add a rule for this file as well. Let's reopen this issue.

Would you like to contribute opening a PR addressing the change?

You can add the rule below this line:
https://github.com/bitnami/containers/blob/e6c8aeaf805fbaa324ce8a8e8684d33d87d1112d/bitnami/moodle/4.1/debian-11/rootfs/opt/bitnami/scripts/moodle/postunpack.sh#L65

The same for the [`4.0` branch](https://github.com/bitnami/containers/blob/main/bitnami/moodle/4.0/debian-11/rootfs/opt/bitnami/scripts/moodle/postunpack.sh).

**Comment by zoomzoomcloud** [comment]
@andresbono I'll pass on PR offer.

**Comment by andresbono** [comment]
@zoomzoomcloud, https://github.com/bitnami/containers/pull/#27518 excludes the `Gruntfile.js` file, among other changes.

Please, try the latest container version. Thanks again!
