### ISSUE TITLE
Portainer: mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied

### ISSUE THREAD

**Issue by kred-jon** [bitnami/containers#2680]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

1. Kubenetes with Microk8s in Ubuntu Server 20.04
2. Install Portainer
3. Using Helm in Portainer
4. add Repo: https://quay.io/repository/keycloak/keycloak
5. Install Keycloak

### What is the expected behavior?

Keycloak pods will running:

keycloak-postgresql-0                 1/1     Running   18 (3m8s ago)   70m
keycloak-0                                   1/1     Running   12 (76s ago)      70m

### What do you see instead?

keycloak-postgresql-0                 0/1     CrashLoopBackOff   18 (3m8s ago)   70m
keycloak-0                                   0/1     CrashLoopBackOff   12 (76s ago)      70m

### Additional information

**Error for keycloak-postgresql-0** 

postgresql 07:27:57.12 
postgresql 07:27:57.12 Welcome to the Bitnami postgresql container
postgresql 07:27:57.12 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 07:27:57.13 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 07:27:57.13 
postgresql 07:27:57.15 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:27:57.18 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:27:57.19 INFO  ==> Loading custom pre-init scripts...
postgresql 07:27:57.20 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied

**Effected to keycloak-0** 

keycloak 07:32:31.11 
keycloak 07:32:31.11 Welcome to the Bitnami keycloak container
keycloak 07:32:31.11 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 07:32:31.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 07:32:31.12 
keycloak 07:32:31.12 INFO  ==> ** Starting keycloak setup **
keycloak 07:32:31.13 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 07:32:31.15 INFO  ==> Trying to connect to PostgreSQL server keycloak-postgresql...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
keycloak 07:35:01.22 ERROR ==> Unable to connect to host keycloak-postgresql

**Comment by kred-jon** [comment]
Screenshot from Portainer Applications List

![image](https://user-images.githubusercontent.com/38023611/183845062-8114ec95-c870-40ba-aaf6-c30fd0b9271f.png)

**Comment by kred-jon** [comment]
It is cause by:

runAsUser: 1001
fsGroup: 1001

not registered in the kubenetes?

**Comment by corico44** [comment]
Hello @kred-jon 
Thank you for your comment.
Based on what your error shows us, it seems that you don' have the permissions of the corresponding directories configured. Try to configure them with the corresponding permissions. For example, using the chmod command: sudo chown -R 1001:root ${YOUR_PATH}.

**Comment by kred-jon** [comment]
Hi @corico44 , appreciate with the response, which path  should change the permission? inside the container or in the Kubernetes server? can I have the sample?

**Comment by kred-jon** [comment]
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath
    volume.kubernetes.io/storage-provisioner: microk8s.io/hostpath
  creationTimestamp: "2022-08-23T05:46:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: postgresql
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:volume.kubernetes.io/storage-provisioner: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
        f:volumeName: {}
    manager: kubelite
    operation: Update
    time: "2022-08-23T05:46:07Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kubelite
    operation: Update
    subresource: status
    time: "2022-08-23T05:46:07Z"
  name: data-keycloak-postgresql-0
  namespace: default
  resourceVersion: "28807801"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/data-keycloak-postgresql-0
  uid: c4652982-4240-4147-8f0c-1be25e19aac3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  volumeName: pvc-c4652982-4240-4147-8f0c-1be25e19aac3
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound

**Comment by corico44** [comment]
@kred-jon Your container volume has a mount point which has a source path and a destination path. The one whose permissions should be modified is the source path.
For example, having the following mount point:
```
./data/main/data:/bitnami/postgresql/data
```
the permissions must be added to the different folders that make up the source path. 
In this case: 
```
./data/main/data
```

And, referring to your question if `/bitnami/postgresql` is a valid path as the destination path of the volume mount point, the answer is yes. There is no problem and it should work.

**Comment by kred-jon** [comment]
Hi, I have solved the problem!. If have any Postgresql created with permission denied,
just add in the values.yaml with below parameter:

volumePermissions:
     enabled: true


So it will trigger init under container:

Init Containers:
  init-chmod-data:
    Container ID:  containerd://601cf84027d0b75dbe391fa7662ea9571565f6f4a28d7e92b5b6619f79b1460a
    Image:         docker.io/bitnami/bitnami-shell:11-debian-11-r27
    Image ID:      docker.io/bitnami/bitnami-shell@sha256:69da2c87742d07ecc308bbd3aa12e797ec97a636e697bd59c7a4af34d4c28965
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
      chown 1001:1001 /bitnami/postgresql
      mkdir -p /bitnami/postgresql/data
      chmod 700 /bitnami/postgresql/data
      find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name "conf" -not -name ".snapshot" -not -name "lost+found" | \
        xargs -r chown -R 1001:1001
      chmod -R 777 /dev/shm


I think this parameter need to be update in the default setting in the helm bitnami/keycloak values.yaml.

**Comment by kred-jon** [comment]
If have problem to create Postgresql DB with permission denied. Try to add new parameter:

924 volumePermissions:
925      enabled: true

**Comment by corico44** [comment]
I'm glad it worked. Thank you for reporting the issue. Don't hesitate to open another issue if you need to!
