### ISSUE TITLE
[bitnami/redis-cluster]  add properties

### ISSUE THREAD

**Issue by yizhishang** [bitnami/containers#26819]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

I want to add "notify-keyspace-events Ex" to redis-cluster,  but i didn't find the env

### What is the feature you are proposing to solve the problem?

can you update the script ?

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the issue! I will forward this to the engineering team but, as it is not a critical feature, we cannot guarantee an ETA. However, if you want to speed up the process, would you like to submit a PR with the script update?
