### ISSUE TITLE
[bitnami/mongodb] mongodb pod uses significantly more memory than `wiredTigerCacheSizeGB`

### ISSUE THREAD

**Issue by haroonb** [bitnami/containers#27195]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy Mongodb using helm chart constraining the `wiredTigerCacheSizeGB` in this example it's 1GB.
`helm upgrade --install mongo --repo=https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami mongodb -n mongodb --wait --atomic  --version=13.6.7 --set extraFlags="--wiredTigerCacheSizeGB=1"`
2. Use the mongo 

### What is the expected behavior?

The memory usage to be marginally more than the `wiredTigerCacheSizeGB` constrain.

### What do you see instead?

The memory usage to be more than 5 times the `wiredTigerCacheSizeGB` constrain

### Additional information

This is the memory usage of the mogodb pods in our k8s cluster over the last sunday, when no one was working. The total size of the Mongodb is about 20GB. 

mongostat shows

```
insert query update delete getmore command dirty  used flushes vsize   res qrw arw net_in net_out conn set repl                time
    *0    11     *0      1       3    46|0  2.1% 80.2%       0 4.35G 1.87G 0|0 1|2  40.0k    682k  396 rs0  PRI Mar 13 12:29:35.071
    *0     9     *0      1      15    61|0  2.2% 80.7%       0 4.35G 1.87G 0|0 7|1  38.3k    462k  397 rs0  PRI Mar 13 12:29:36.078
    *0    19      4      1      16   124|0  2.2% 80.5%       0 4.35G 1.87G 0|0 20|2   383k   2.11m  397 rs0  PRI Mar 13 12:29:37.073
    *0     2     *0     *0       0    41|0  2.2% 85.1%       0 4.35G 1.87G 0|0 20|2  11.2k    174k  397 rs0  PRI Mar 13 12:29:38.069
```

<img width="757" alt="image" src="https://user-images.githubusercontent.com/62880411/224700891-69edd958-1fa7-45f9-8975-c745a9ad7771.png">

**Comment by javsalgar** [comment]
Hi,

Could you try disabling the liveness/readiness probes to see if it has to do with the mongosh client?

**Comment by rafariossaa** [comment]
Hi,
 Could you check if the process in the pod is launched with the `wiredTigerChacheSize` parameter ?
``` 
 I have no name!@mongo-mongodb-7d46f7fbf-29gqs:/$ ps -ef | grep mongo
1001           1       0  3 09:53 ?        00:00:01 /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf --wiredTigerCacheSizeGB=1
```

If that it the case, I would suggest you to rise the question in mongodb forums. I think they could give a better answer on how the mongodb shoud behave with the parameter.
