### ISSUE TITLE
[bitnami/discourse] Postgres container not starting

### ISSUE THREAD

**Issue by Squadz** [bitnami/containers#27217]
### Name and Version

bitnami/discourse:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/discourse/docker-compose.yml > docker-compose.yml
2. docker-compose up -d

### What is the expected behavior?

All containers should be running

### What do you see instead?

discourse_postgresql returns  `[123] FATAL:  role "bn_discourse" does not exist`

Also when trying to make persistent the application with:
```     volumes:
-      - 'postgresql_data:/bitnami/postgresql'
+      - /path/to/postgresql-persistence:/bitnami/postgresql
```

We are getting `mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied` ([issue 1210](https://github.com/bitnami/charts/issues/1210))

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
