### ISSUE TITLE
Sendmail not found and thus unable to send mail on the matomo container

### ISSUE THREAD

**Issue by JuhaniGeniem** [bitnami/containers#2726]
### Name and Version

bitnami/matomo:4

### What steps will reproduce the bug?

When using the "lost password" function I get the following error:

`Could not instantiate mail function.Possible reason: your host may have disabled the mail() function`

I'm trying to use AWS SES:

```
  MATOMO_SMTP_HOST: email-smtp.eu-west-1.amazonaws.com
  MATOMO_SMTP_PORT: 587
  MATOMO_SMTP_USER: AKIA...
  MATOMO_SMTP_PROTOCOL: tls
  MATOMO_SMTP_AUTH: Login
  MATOMO_SMTP_PASSWORD: ...
  ```
  
  I'm also unable to send mail via CLI:
  
  ```
I have no name!@myserver:/$ sendmail
bash: sendmail: command not found

I have no name!@myserver:/$ sendmailconfig
bash: sendmailconfig: command not found
```

### What is the expected behavior?

Mail to be sent

### What do you see instead?

sendmail not installed

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by dani-CO-CN** [comment]
If you want to use SES you will have to use `MATOMO_SMTP_AUTH: Plain`
