### ISSUE TITLE
Proxy through ldap backend

### ISSUE THREAD

**Issue by TomBeli** [bitnami/containers#27437]
### Name and Version

[bitnami/openldap] Release 2.5.14-debian-11-r7

### What is the problem this feature will solve?

Hello,
We need to implement an LDAP Proxy in front of the OpenLDAP servers.
Is it possible to change the container config to _ldap_ backend, instead of the default _mdb_.

There is only a limited set of environment variables in the documentation, is the container image limited in any way compared to the official [OpenLDAP Configuration Reference](https://www.openldap.org/doc/admin25/guide.html) (I'm asking the question to address concerns from some team members that the Bitnami container might not be a complete functional equivalent to OpenLDAP deployed on Linux VMs)

Much appreciated!
Tom

### What is the feature you are proposing to solve the problem?

To implement LDAP Proxy feature (which instead of replicating the directory tree, will retrieve data from a ldap backend).

Attribute translation (i.e. Attribute _EmployeeNumber_ mapped to _EmployeeID_ in the LDAP backend)

### What alternatives have you considered?

This request is actually a validation if the Bitnami container has a complete OpenLDAP feature set, so we would not need to deploy Linux VMs. Especially now, that OpenLDAP is no longer part of the RHEL8 distribution.

 

Alternative would be deploying OpenLDAP on Linux VMs.

**Comment by Mauraza** [comment]
Hi @TomBeli,

Did you try to use a [script to initialize](https://github.com/bitnami/containers/tree/main/bitnami/openldap#initializing-a-new-instance)?

**Comment by TomBeli** [comment]
Hello @Mauraza,
No we did not. Do you have an example of the kind of scripts you're referring to.
Are scripts meant to manipulate the configuration files?
Aside of scripts, is there another way to edit the configuration files?
Is there a complete feature parity between containerized and "traditional" OpenLDAP installed on a server?

Thank you,
Toma

**Comment by Mauraza** [comment]
Hi @TomBeli,

If you check the link, is related to adding scripts to initialize OpenLDAP. We offer the option to add these types of scripts.
All the information about this container is in the [README.md](https://github.com/bitnami/containers/blob/main/bitnami/openldap/README.md), please check it.

**Comment by TomBeli** [comment]
Hello @Mauraza,
Of course we checked the link and the readme and any other piece of doc we could find. 
Ss there another way to edit the configuration files?
Do you have a reference to a sample initialization script.
Your help is appreciated
Toma

**Comment by Mauraza** [comment]
Hi @TomBeli,

I don't know if exists an issue with an example with a script. If you want more information about the configuration files I recommend checking the [official documentation of OpenLDAP](https://www.openldap.org/doc/admin24/slapdconf2.html).  
Do not hesitate to write us back if you have any issues with the application.

**Comment by Mauraza** [comment]
Hi @mikekuzak,

please check this [comment](https://github.com/bitnami/containers/issues/13864#issuecomment-1324970558) about slapd.conf
