### ISSUE TITLE
Bitnami Kafka Streaming infrastrature

### ISSUE THREAD

**Issue by aboah** [bitnami/containers#27469]
### Name and Version

bitnami/ksql

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Installation of docker images for bitnami/ksql, bitnami/connect and bitnami/ksql-cli

### What do you see instead?

Images are not available in docker registry hub

**Comment by carrodher** [comment]
All the Bitnami images are listed in DockerHub at https://hub.docker.com/u/bitnami. If those images are not there it is because they are not part of the catalog.
