### ISSUE TITLE
Provide support for AWS Corretto for Zookeeper

### ISSUE THREAD

**Issue by abhijeetkushe** [bitnami/containers#27515]
### Name and Version

bitnami/zookeeper:11.1.14

### What is the problem this feature will solve?

Current Docker image of Zookeeper is built on OpenDJK.Open JDK 11 will end the active support from September 30. Java8 support has already ended. Please see https://endoflife.date/java
![image](https://user-images.githubusercontent.com/2093096/225669519-847bff3d-febf-4274-96f0-1c007366038c.png)
![Screen Shot 2023-03-16 at 11 37 23 AM](https://user-images.githubusercontent.com/2093096/225669912-63f16f89-3dd2-4cf6-a938-4bbeee81be1f.png)

Can Zookeeper start pushing official images for AWS corretto 11  for EKS on AWS users ?

### What is the feature you are proposing to solve the problem?

Allowing customers to keep using open source software

### What alternatives have you considered?

We are currently considering building our own images.But it will make upgrades harder

**Comment by carrodher** [comment]
According to the [zookeeper documentation](https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_supportedPlatforms), there are only three Java versions supported
> ZooKeeper runs in Java, release 1.8 or greater (JDK 8 LTS, JDK 11 LTS, JDK 12 - Java 9 and 10 are not supported)

In Bitnami we provide support for LTS versions, being in Java 8, 11 and 17. Because of that, we could upgrade Zookeeper from Java 11 to Java 17, but this is not something supported yet by Zookeeper itself

**Comment by abhijeetkushe** [comment]
@carrodher  That is right which is why I was hoping we can build a Corretto Java 11 image so that open source technologies which use Zookeeper don't have to build their own custom image

**Comment by carrodher** [comment]
There are no plans for this kind of addition at this moment, we will work on supporting the LTS versions of the different assets and updating the dependencies according to the developers guidelines
