### ISSUE TITLE
Clarify Bitnami's position regarding Docker's "Free Teams" being sunset

### ISSUE THREAD

**Issue by ericslandry** [bitnami/containers#27516]
### Name and Version

bitnami/kafka:3

### What is the problem this feature will solve?

I am a consumer of the `bitnami/kafka:3` Docker image hosted on Docker Hub. Docker has recently announced their April 13th sunset of "Free Teams", which _could_ result in deleted images. I unfortunately don't have a good mechanism to determine which image (organization) are at risk of deletion. 

### What is the feature you are proposing to solve the problem?

Could you please add a small text blurb indicating bitnami's roadmap regarding Docker Hub? For example, mentioning that "Bitnami is a paying Docker customer" or "Bitnami is part of https://www.docker.com/community/open-source/application/" and its consumers don't need to worry about disappearing docker images. Thank you!

### Link for more info

https://github.com/docker/hub-feedback/issues/2314

**Comment by carrodher** [comment]
Bitnami won't be affected by this change since Bitnami (via VMware) is part of the [_Docker Verified Publisher_ program](https://www.docker.com/partners/programs/) apart from other collaborations.

**Comment by nallenscott** [comment]
Shoutout to bitnami staff for being super responsive [cross-platform](https://twitter.com/beltranrubo/status/1636369658285813767) 🤝
