### ISSUE TITLE
[bitnami/mysql] fails to initialize db with docker-entrypoint-initdb.d when use database with backticks

### ISSUE THREAD

**Issue by qbx2** [bitnami/containers#27511]
### Name and Version

bitnami/mysql:5.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. I am using M1 macbook. I use lima+docker to run containers. But this issue occurs on my kubernetes clusters too.
2. Set up docker-entrypoint-initdb.d, I fill $PWD/fixtures/00-init.sql with:
```
CREATE DATABASE `my_test`;
USE `my_test`;
```
3. Run ```docker run -it -e BITNAMI_DEBUG=true -e ALLOW_EMPTY_PASSWORD=yes -v $PWD/fixtures:/docker-entrypoint-initdb.d bitnami/mysql:5.7```
4. It fails with an error message:
```
mysql 02:58:32.25 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mysql 02:58:32.25 DEBUG ==> Executing /docker-entrypoint-initdb.d/00-init.sql
mysql 02:58:32.25 DEBUG ==> Executing SQL command:
select 1
1
mysql 02:58:32.26 DEBUG ==> Executing SQL command:
SET autocommit=0; source /docker-entrypoint-initdb.d/00-init.sql; COMMIT;
ERROR 1046 (3D000) at line 2 in file: '/docker-entrypoint-initdb.d/00-init.sql': No database selected
mysql 02:58:32.27 ERROR ==> Failed executing /docker-entrypoint-initdb.d/00-init.sql
mysql 02:58:32.27 INFO  ==> Stopping mysql
```

### What is the expected behavior?

When I fix the sql file to `USE my_test` (without backticks), it works.

It works with official mysql:5.7 image regardless I use with backticks or not.

### What do you see instead?

ERROR 1046 (3D000) at line 2 in file: '/docker-entrypoint-initdb.d/00-init.sql': No database selected

### Additional information

There still also exists the issue with linux/amd64.

**Comment by qbx2** [comment]
Setting `MYSQL_DATABASE` to 'any' value could be used as an workaround.

**Comment by andresbono** [comment]
Thank you for reporting this issue, we can reproduce it and we are investigating. We'll get back to you soon.

**Comment by andresbono** [comment]
@qbx2, #27673 should fix the issue. Thanks for reporting it! Please, try the latest version (`5.7.41-debian-11-r18`) of the container and let us know if you find any issues now
