### ISSUE TITLE
Will images on Docker Hub be affected by Docker's new Organisation charges?

### ISSUE THREAD

**Issue by CowChris** [bitnami/containers#27520]
### Name and Version

bitnami/kubectl

### What is the problem this feature will solve?

Docker deleting images from Docker Hub for organisations who don't pay their subscription fee in approx 30 days time...

https://news.ycombinator.com/item?id=35166317

### What is the feature you are proposing to solve the problem?

Up to you guys I guess :)

### What alternatives have you considered?

Build and host own image.

**Comment by carrodher** [comment]
Bitnami won't be affected by this change since Bitnami (via VMware) is part of the [_Docker Verified Publisher_ program](https://www.docker.com/partners/programs/) apart from other collaborations.
