### ISSUE TITLE
[bitnami/keycloak] Error with class org.jboss.marshalling.river.ClassDescriptors since java 17 update

### ISSUE THREAD

**Issue by Drustan** [bitnami/containers#28129]
### Name and Version

bitnami/keycloak:20.0.5-debian-11-r9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In the Keycloak UI, navigate to the "Sessions tab" on the left menu 

### What is the expected behavior?

List the active sessions

### What do you see instead?

You will get a "Request failed with status code 500" message

### Additional information

This is introduced by the upgrade of Java from version 11 to 17. I'm using the Bitnami HELM chart to deploy Keycloak on K8S. The issue is only present when running three or more replicas.

Here's the commit : https://github.com/bitnami/containers/commit/a4444ad9fc9ae23b2377b82f35e36f75835aa0ee

**Comment by vruum** [comment]
@Drustan can I ask how you're running the image? I just tried to reproduce by running the docker compose setup, and I'm not seeing any issues.

**Comment by vruum** [comment]
That's odd. Can you check what the contents of /opt/bitnami/keycloak/providers is in the image?

**Comment by Drustan** [comment]
Here's the content :

```
keycloak@keycloak-2:/$ ls -l /opt/bitnami/keycloak/providers/
total 2640
-rw-rw-r-- 1 keycloak root     256 Mar 18 01:14 README.md
-rw-r--r-- 1 root     root  121836 Mar 23 12:28 asm-7.3.1.jar
-rw-r--r-- 1 root     root   71548 Mar 23 12:28 asm-commons-7.3.1.jar
-rw-r--r-- 1 root     root   84817 Mar 23 12:28 asm-util-7.3.1.jar
-rw-rw-r-- 1 keycloak root  234082 Mar 18 01:14 keycloak-metrics-spi-2.5.3.jar
drwxrwxr-x 2 keycloak root    4096 Mar 23 12:27 log
-rw-r--r-- 1 root     root 2167288 Mar 23 12:28 nashorn-core-15.3.jar
drwxrwxr-x 2 keycloak root    4096 Mar 23 12:27 tmp
```

**Comment by vruum** [comment]
okay, I don't have access to a k8s cluster to test atm. but just for reference, this is what I tried. 
* Build the image locally, called with-nashorn
* edit the docker-compose file to point to the with-nashorn image
* docker-compose up
* access keycloak admin with user/bitnami credentials
* Create new client with authz (check both client authentication and authorization on)
* Go to the client -> authorization -> evaluate
* Select user "user" and Roles "admin" click evalutate.
* With the current image nothing happens in the UI but the console will log the exception with the with-nashorn image the UI updates and the authorization is verified, no errors are logged from the container. 

If you could provide some information about what you're doing and how, it might be possible to understand why this isn't working for you

**Comment by Drustan** [comment]
I got back to the bitnami/keycloak:20.0.5-debian-11-r9 image. With only 1 replica, it works as expected. So the Keycloak image with Java 17 is introducing a regression with cluster mode setups it seems.

**Comment by vruum** [comment]
As mentioned I don't have a k8s cluster to test this on. It sounds a bit strange, especially that it's working with the current image when only running a single replica. 
You haven't really provided any detail as to what it is you're doing when you see the error. 
As mentioned above, the issue is reprodducible for me, even when just running a single instance. It might be that the issue you're seeing is actually not the same as the one I'm seeing. 
I don't really know what you've tried, but have you verified that all instances in the stateful set are running the image you expect before testing anything.

**Comment by vruum** [comment]
Oh no, I think we're talking about completely different issues then. I'm sorry I wasted time.

**Comment by javsalgar** [comment]
Hi,

You could track the Java versions by looking a the Dockerfile.

**Comment by Drustan** [comment]
That's not ideal but that will do until I can use the official image again :crossed_fingers:

**Comment by javsalgar** [comment]
Hi,

We don't compile keycloak but we redistribute the upstream version placing it in `/opt/bitnami/keycloak`. My advice would be to add an instruction in the fork that performs the replacement. You can try launching the container and browse the filesystem in search of the file.

**Comment by Drustan** [comment]
Just so you know, I just tried the last image with Keycloak version 21.0.2 (Java 17) and the problem is gone.
