### ISSUE TITLE
[bitnami/kubectl] read /.kube/config: is a directory

### ISSUE THREAD

**Issue by YorQat** [bitnami/containers#28125]
### Name and Version

bitnami/kubectl:1.26.3-debian-11-r0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```
- run: |
  # Create cluster credentials
  mkdir ${HOME}/.kube
  echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config  

- run: |
  # Run a command
  docker run -v ${HOME}/.kube/config:/.kube/config --rm bitnami/kubectl:1.26.3-debian-11-r0 get pods
```
 

### What is the expected behavior?

`./kube/config` would not be a directory and works fine just like in my workstation machine

### What do you see instead?

I get this error instead
```
error: error loading config file "/.kube/config": read /.kube/config: is a directory
Error: Process completed with exit code 1.
shell: /usr/bin/bash -e {0}
````

### Additional information

Executed using a self-hosted github actions runner arm64

**Comment by gongomgra** [comment]
Hi @YorQat,

Thanks for using Bitnami, and sorry for the delay on getting back to you. Can you give us a more detailed steps to reproduce your issue?
