### ISSUE TITLE
java 17 based version of bitnami/wildfly

### ISSUE THREAD

**Issue by ssill2** [bitnami/containers#28131]
### Name and Version

bitnami/wildfly

### What is the problem this feature will solve?

For those hoping to get a headstart on migration from java 11 to java 17,  it would be great if there was a tag of the bitnami/wildfly image that was based on java 17 instead of 11.

Of the current set of apps I'm responsible for, I have some converted to java 17(the vert.x based ones), and the remainder that are wildfly-based apps, are stuck on java 11.  To switch those apps I'll need to have a bitnami/wildfly image that's java 17 based.

Is there an anticpated date/version where this switch will happen?

### What is the feature you are proposing to solve the problem?

It will help people that are trying to get ahead of the curve on migrating from the java 11 LTS to java 17 LTS

### What alternatives have you considered?

Someone on the bitnami/wildfly team was helpful enough to tell me how I could pull the bitnami/wildfly repo and make changes locally to build a java 17 based version.  This did allow me to do some testing and get my apps working but I'd rather wait until builds released on hub.docker.com so I don't have to custom build the bitnami/wildfly image.

**Comment by carrodher** [comment]
Thanks for the suggestion, we already have an internal task to update the Java version. We will close this issue by posting a new comment once this task is done on our side and the new version is released. Thanks

**Comment by ssill2** [comment]
Do you have an anticipated date for that switch?

Thanks!

**Comment by carrodher** [comment]
We can't provide an ETA, it depends on the team's capacity and other initiatives we are working on. We will update this thread once done

**Comment by Mauraza** [comment]
Hi @ssill2,

The latest revisions of Wildfly are with Java 1, for example, 27.0.1-debian-11-r46 or 26.1.3-debian-11-r33

**Comment by ssill2** [comment]
java 17?

**Comment by Mauraza** [comment]
Yes, with Java 17!! sorry for the typo.

**Comment by ssill2** [comment]
lol. no worries!   That's great!   I've been stalled for months lol   I'll give this a whirl this week!  Thanks! :)

**Comment by Mauraza** [comment]
I'm closing this issue, do not hesitate to write us back if you have any other issues.

**Comment by ssill2** [comment]
yep thanks!
