### ISSUE TITLE
bitnami tomcat 9 on java 17

### ISSUE THREAD

**Issue by Controlix** [bitnami/containers#28332]
### Name and Version

bitnami/tomcat:9.0

### What is the problem this feature will solve?

I try to deploy a war created with spring-boot to a tomcat server. I need to use java 17 but that will not run om the bitnami/tomcat:9.0 docker container. When I downgrade my app to run on java 11 it starts without problem.

### What is the feature you are proposing to solve the problem?

Build a tomcat image packaged with java 17

### What alternatives have you considered?

I tried the official tomcat docker image and there my app with java 17 runs fine. But it lacks the easy of use of the bitnami tomcat version.

**Comment by carrodher** [comment]
Thanks for the suggestion, we already have an internal task to update the Java version. We will close this issue by posting a new comment once this task is done on our side and the new version is released. Thanks

**Comment by Mauraza** [comment]
In GitHub will appear when this [PR](https://github.com/bitnami/containers/pull/32307/files) will be merged but that version is already in the docker hub 
```bash
$ docker run --rm -ti bitnami/tomcat:9.0.74-debian-11-r5 java --version
tomcat 16:38:32.85 
tomcat 16:38:32.85 Welcome to the Bitnami tomcat container
tomcat 16:38:32.85 Subscribe to project updates by watching https://github.com/bitnami/containers
tomcat 16:38:32.85 Submit issues and feature requests at https://github.com/bitnami/containers/issues
tomcat 16:38:32.85 

openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)
```

**Comment by carrodher** [comment]
As announced at https://github.com/bitnami/containers/issues/75671, Tomcat 9.0 is not available in Bitnami, only as part of [Bitnami Premium](https://www.arrow.com/globalecs/na/vendors/bitnami?utm_source=GitHub&utm_medium=containers).
