### ISSUE TITLE
Missing ARM64 images for Kafka 3.0 and 3.1

### ISSUE THREAD

**Issue by nightswimmings** [bitnami/containers#28340]
### Name and Version

bitnami/kafka:3.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Multiarch images are not available for Kafka 3.0 and 3.1 in Dockerhub

### What is the expected behavior?

Avilable arm64 images for Kafka 3.x images under 3.2

### What do you see instead?

Multiarch images are not available for Kafka 3.0 and 3.1 in Dockerhub

### Additional information

FYI
Kafka 2.8 EOL is June '22
Kafka 3.0 EOL is October '23
Kafka 3.1 EOL is  April '24, and it is the version currently provided by Amazon MSK

**Comment by carrodher** [comment]
We maintain 3 branches for Apache Kafka: 3.2, 3.3 and 3.4; previous branches are present in DockerHub but without multi-arch support. Since multi-arch is not going to be added in a retroactive way, previous versions won't receive multi-arch support.
