### ISSUE TITLE
[bitnami/openldap:2.6]: mdb_idl_insert_keys: c_put id failed: MDB_MAP_FULL: Environment mapsize limit reached (-30792)

### ISSUE THREAD

**Issue by apilatzek** [bitnami/containers#28630]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use the bitnami openldpap 2.6 image with no special environment.
```yaml
version: '2'
 
services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '172.31.1.145:6100:1389'
    environment: ....
```

I have filled my OpenLDAP with some data. When I want to add more entries I get the error message
```
index generation failed". In docker logs I see: "mdb_idl_insert_keys: c_put id failed: MDB_MAP_FULL: Environment mapsize limit reached (-30792)
```

### What is the expected behavior?

The expected behavior would be, that the new data/entries would be added to the OpenLDAP.

### What do you see instead?

docker logs show:
```
6423221d.19c22770 0x7f5f709fc700 mdb_idl_insert_keys: e67 [00000000]
6423221d.19c26e8f 0x7f5f709fc700 mdb_idl_insert_keys: e67 [04d81bef]
6423221d.19c2b46b 0x7f5f709fc700 mdb_idl_insert_keys: e67 [7faff89e]
6423221d.19c57744 0x7f5f709fc700 mdb_idl_insert_keys: e67 [00000000]
6423221d.19c5ca54 0x7f5f709fc700 mdb_idl_insert_keys: e67 [860433ad]
6423221d.19c65e3f 0x7f5f709fc700 mdb_idl_insert_keys: e67 [00000000]
6423221d.19c6a791 0x7f5f709fc700 mdb_idl_insert_keys: e67 [39455bcb]
6423221d.19c6dcf8 0x7f5f709fc700 mdb_idl_insert_keys: e67 [28bbbb16]
6423221d.19c7c2fb 0x7f5f709fc700 => mdb_idl_insert_keys: c_put id failed: MDB_MAP_FULL: Environment mapsize limit reached (-30792)
6423221d.19c835ba 0x7f5f709fc700 <= index_entry_add( 3687, "cn=test-init-20230328-1746,ou=users,dc=example,dc=org" ) failure
6423221d.19c84567 0x7f5f709fc700 mdb_add: index_entry_add failed
6423221d.19c8541e 0x7f5f709fc700 send_ldap_result: conn=67127 op=1 p=3
6423221d.19c86160 0x7f5f709fc700 send_ldap_result: err=80 matched="" text="index generation failed"
6423221d.19c872d7 0x7f5f709fc700 send_ldap_response: msgid=2 tag=105 err=80
6423221d.19c89370 0x7f5f709fc700 ber_flush2: 37 bytes to sd 13
6423221d.19c8a1f7 0x7f5f709fc700   0000:  30 23 02 01 02 69 1e 0a  01 50 04 00 04 17 69 6e   0#...i...P....in
6423221d.19c8afe1 0x7f5f709fc700   0010:  64 65 78 20 67 65 6e 65  72 61 74 69 6f 6e 20 66   dex generation f
6423221d.19c8bbf4 0x7f5f709fc700   0020:  61 69 6c 65 64                                     ailed
6423221d.19c95cd2 0x7f5f709fc700 ldap_write: want=37, written=37
6423221d.19c96e33 0x7f5f709fc700   0000:  30 23 02 01 02 69 1e 0a  01 50 04 00 04 17 69 6e   0#...i...P....in
6423221d.19c97b67 0x7f5f709fc700   0010:  64 65 78 20 67 65 6e 65  72 61 74 69 6f 6e 20 66   dex generation f
6423221d.19c98733 0x7f5f709fc700   0020:  61 69 6c 65 64                                     ailed
6423221d.19c99d28 0x7f5f709fc700 conn=67127 op=1 RESULT tag=105 err=80 qtime=0.000025 etime=0.001196 text=index generation failed
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami OpenLDAP container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by apilatzek** [comment]
Ok, I have to check the application itself.
I found this https://serverfault.com/questions/962209/how-to-increase-size-of-openldap-mdb-database-mdb-map-full-error-code thats seems to solve the problem.
Could you point me to some documentation how to change the configuration for cn=config inside the docker image?

**Comment by StopMotionCuber** [comment]
I'm having the same problem and would like to solve that somehow within my environment.

The documentation says:
"You can bootstrap the contents of your database by putting LDIF files in the directory /ldifs (or the one you define in LDAP_CUSTOM_LDIF_DIR). Those may only contain content underneath your base DN (set by LDAP_ROOT). You can not set configuration for e.g. cn=config in those files."

However it's not pointing out what is the _correct_ way to change the configuration. That would be good to know
