### ISSUE TITLE
[bitnami/gitea] Customized config files break gitea installation

### ISSUE THREAD

**Issue by bebosudo** [bitnami/containers#28664]
### Name and Version

bitnami/gitea:1.18.5-debian-11-r9

### What is the problem this feature will solve?

I'm trying to pass a configuration file to gitea like mentioned in the README: https://github.com/bitnami/containers/tree/main/bitnami/gitea#configuration-overrides
Since the config file is mounted as ReadOnly as directed, the setup.sh script fails because it cannot modify the config file:
```
gitea@gitea-577489d5c7-7nw4p:/opt/bitnami/gitea$ ls -alh /opt/bitnami/gitea/custom/conf/
-rw-rw-r-- 1 root  root 1.2K Mar 18 22:51 app.ini
-rw-rw-r-- 1 gitea root 1.4K Mar 18 22:51 app.ini.template

gitea@gitea-577489d5c7-7nw4p:/opt/bitnami/gitea$ /opt/bitnami/scripts/gitea/setup.sh 
gitea 17:02:37.28 DEBUG ==> Validating settings in GITEA_* environment variables...
gitea 17:02:37.29 INFO  ==> Waiting for database connection...
gitea 17:02:37.30 INFO  ==> Initializing Gitea...
gitea 17:02:37.31 INFO  ==> Restoring persisted Gitea installation
gitea 17:02:37.33 DEBUG ==> Setting APP_NAME to 'My Gitea service' in Gitea configuration
open /opt/bitnami/gitea/custom/conf/app.ini: permission denied

gitea@gitea-577489d5c7-7nw4p:/opt/bitnami/gitea$ ls -alh /opt/bitnami/gitea/custom/conf/
lrwxrwxrwx 1 gitea gitea   34 Mar 29 17:25 app.ini -> /bitnami/gitea/custom/conf/app.ini
-rw-rw-r-- 1 gitea root  1.4K Mar 18 22:51 app.ini.template
```

I believe the script should not try to restore an installation, since I have nothing on my persistent storage other than the app.ini mounted externally as instructed, and I'm using an empty db.

https://github.com/bitnami/containers/blob/873b3fcddef735f2fd434a44c55f936bf197beeb/bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh#L123
I checked also by running `bash -x setup.sh`, and it shows that the `if` in the line above fails for the first condition (i.e. it finds something in the persisting directory) and it fails also the second condition, since `setup.sh` replaces `/opt/bitnami/gitea/custom/conf/app.ini` with a symlink to my read-only `/bitnami/gitea/custom/conf/app.ini`, but that makes `test -f` pass, so `! test -f` fails.

Could you provide a hint on how to make this work?

A bonus feature would be avoiding to repeat the values for the installation and for the execution in the environment variables and also the external config file, respectively.

### What is the feature you are proposing to solve the problem?

If an external config file is passed/found in the correct location, it should still detect that there's no installation yet, and not try to replace its values with those in the environment variables, and simply proceed with the wizard/skip it if an installation is found.

**Comment by marcosbc** [comment]
Hi @bebosudo, currently it does not seem to be supported by this container image.

But, it should be possible if you make some slight changes to the code:

```diff
diff --git a/bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh b/bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh
index b589523fb9e..60e14dfe76b 100644
--- a/bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh
+++ b/bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh
@@ -185,6 +185,11 @@ wait_for_connection() {
 #   None
 #########################
 gitea_update_conf_file() {
+    if ! is_file_writable "$GITEA_CONF_FILE"; then
+        warn "The Gitea configuration file '${GITEA_CONF_FILE}' is not writable. Configurations based on environment variables will not be applied for this file."
+        return
+    fi
+
     # https://docs.gitea.io/en-us/config-cheat-sheet/
     # That URL contains most of the settings that can be configured as well as their default value.
     gitea_conf_set "" "APP_NAME" "$GITEA_APP_NAME"
```

> NOTE: `is_file_writable()` is declared in `libfs.sh`.

Try it out, and if it works, feel free to contribute the changes via a PR! We'd be glad to help to release those changes.

**Comment by bebosudo** [comment]
Hi @marcosbc, I tried your suggestion and it improves things: the script doesn't attempt to update the config file, and it proceeds attempting to install the software, but there's an error returned by the gitea server both when attempting to install via curl or via browser manually:
```
Failed to save configuration: open /opt/bitnami/gitea/custom/conf/app.ini: read-only file system
```

I think the gitea app itself now tries to overwrite the config file somehow?

I'll investigate this more next week.

**Comment by bebosudo** [comment]
A quick google search found this interesting issue in the gitea repo: https://github.com/go-gitea/gitea/issues/5704

Folks in that thread then updated the docs with a section about how to run gitea with a read-only config file: https://docs.gitea.io/en-us/install-from-binary/#create-required-directory-structure

I suspect I also have something broken in my SECRET values; I'll make sure to follow that guide next week.
