### ISSUE TITLE
[bitnami/kafka] Kafka KRaft Cluster ID issue in container.

### ISSUE THREAD

**Issue by musama78** [bitnami/containers#29027]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

i am using following command to create the kafka kraft container. 
```
docker run -d --name kafka1 \
-e ALLOW_PLAINTEXT_LISTENER=yes \
-e KAFKA_KRAFT_CLUSTER_ID=my-cluster \
-e KAFKA_ENABLE_KRAFT=yes \
-e KAFKA_CFG_PROCESS_ROLES=broker,controller \
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
-e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093 \
-e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 \
-e KAFKA_BROKER_ID=1 \
bitnami/kafka:latest
```
### What is the expected behavior?

container should be created and running properly.

### What do you see instead?

it failed to start. and following are the logs.
```
kafka 16:58:05.08
kafka 16:58:05.09 Welcome to the Bitnami kafka container
kafka 16:58:05.09 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 16:58:05.09 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 16:58:05.09
kafka 16:58:05.10 INFO  ==> ** Starting Kafka setup **
kafka 16:58:05.17 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 16:58:05.19 INFO  ==> Initializing Kafka...
kafka 16:58:05.20 INFO  ==> No injected configuration files found, creating default config files
kafka 16:58:05.44 INFO  ==> Initializing KRaft...
kafka 16:58:05.44 INFO  ==> Formatting storage directories to add metadata...
```

**Comment by javsalgar** [comment]
Hi,

Could you add `BITNAMI_DEBUG=true` to see if it provides more insight on the issue?

**Comment by musama78** [comment]
hi,
I have figured out the issue. i believe, priviously i was giving very short cluster_id which was "my-cluster" but then after doing research about the issue, i saw few examples online where were using long cluster_id. then i also put "fMCL8kv1SWm87L_Md-I2hg" and it works. now its working fine. i did not find anything about the length of cluster_id.

**Comment by musama78** [comment]
> I have met the same issue, there are no document about the lenght of the CLUSER_ID, but the KAFKA process will silently crush is the CLUSTER_ID is too short.

yes you are right. when i configured long length CLUSTER_ID , it works fine.

**Comment by avmurashov** [comment]
I have just tried to put random UUID, and got the following WARNING:
> Cluster ID string c23ade2b-1922-4e19-99f7-4564e382a480 does not appear to be a valid UUID: Input string with prefix `c23ade2b-1922-4e19-99f7-` is too long to be decoded as a base64 UUID
 
So, I can conclude that `KAFKA_KRAFT_CLUSTER_ID` should exactly be base64 UUID...
