### ISSUE TITLE
[bitnami/phpMyAdmin] Cannot log in to the MySQL server using LDAP

### ISSUE THREAD

**Issue by goldmont** [bitnami/containers#29037]
### Name and Version

bitnami/phpMyAdmin:5.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start Bitnami OpenLDAP with the default configuration.
2. Start Bitnami Mariadb-Galera.
3. Configure PAM authenticated LDAP user on Mariadb.
4. Log in into Mariadb with LDAP user via CLI (it works).
5. Log in into Mariadb with LDAP user via phpMyAdmin (it doesn't work).

PAM authenticated LDAP user configured this way:
```sql
CREATE USER 'user01'@'%' IDENTIFIED VIA pam USING 'mariadb';
GRANT ALL ON *.* TO 'user01'@'%';
FLUSH PRIVILEGES;
```

### What is the expected behavior?

Being able to log in into Mariadb with LDAP user via phpMyAdmin.

### What do you see instead?

The following error:
`mysqli::real_connect(): (HY000/2054): The server requested authentication method unknown to the client`

User: `user01`
Password: `bitnami1`

![image](https://user-images.githubusercontent.com/6855692/229732505-0ab7ff3c-ca44-47d2-aff7-ccfd9416faeb.png)

### Additional information

I'm able to log in into Mariadb using `root` user by the way.

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket! It is not clear to me that the issue has to do with the Bitnami packaging of the application or in PhpMyAdmin itself. Did you check with upstream phpmyadmin devs?

**Comment by goldmont** [comment]
Hi,

I've found [this](https://github.com/phpmyadmin/phpmyadmin/issues/13855). It's the same error. Could you take a look?

**Comment by javsalgar** [comment]
Hi,

It seems it's a missing feature from PHP, so at the moment there's not much to do from our side (we only package the application but not change the code of the apps)
