### ISSUE TITLE
[bitnami/pgbouncer] Can't set config option reserve_pool_timeout from envs.

### ISSUE THREAD

**Issue by V-ampire** [bitnami/containers#29362]
### Name and Version

bitnami/pgbouncer:1.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

No enviroment for reserve_pool_timeout

### What do you see instead?

Can't set config option reserve_pool_timeout from envs.

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket. The logic of the avaliable values are done in the `libpgbouncer.sh`. If you want to add a new env var, would you like to submit a PR adding the feature?

**Comment by V-ampire** [comment]
> Hi,
> 
> Thank you for opening the ticket. The logic of the avaliable values are done in the `libpgbouncer.sh`. If you want to add a new env var, would you like to submit a PR adding the feature?

Hi, yeap I can do it today
