### ISSUE TITLE
[bitnami/openldap] Sudoers/Sudo schema

### ISSUE THREAD

**Issue by j-clavoie** [bitnami/containers#29627]
### Name and Version

bitnami/openldap:lastest

### What architecture are you using?

amd64
My OS is Ubuntu 22.04
My docker version: 23.0.3, build 3e7cbfd

### What steps will reproduce the bug?

First, I've to say that I'm not so good with openldap schema, usually I used default schemas and that was enough for my needs.
But now I need to use the "sudoers" feature on my openldap server.

I tried to use `LDAP_EXTRA_SCHEMAS`parameters in my `docker-compose.yml` file.
But it seems that this schema is not a part of default schemas available in this docker image.

I tried to find external schema file and import into my container but nothing seems working properly.

So, what is the easiest way to add sudoers schema in my openldap server by using docker-compose file.

### What is the expected behavior?

Be able to add sudoers schema easily in my openldap server (inside my container).

### What do you see instead?

Nothing work

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the ticket! Could you share the documentation on the sudoers schema? I don't recall support tickets in the past about this schema.

**Comment by j-clavoie** [comment]
Hi @javsalgar 

There is a part of information I found about sudo/sudoers schema:

- https://www.sudo.ws/docs/man/1.8.17/sudoers.ldap.man/
- https://manpages.debian.org/testing/sudo-ldap/sudoers.ldap.5.en.html
- https://superuser.com/questions/219077/how-to-use-ldap-to-store-sudoer-information

Like I said before I'm not good with ldap schema but I understand that the sudo/sudoers shema files are not "installed" by default with openldap service.
I took a look inside my bitnami/openldap container to search this schema file and it not seems present in the container, or I missed it.

I guess that the schema file need to be "injected" manually but I don't know how to do that??

And I think that could be interesting and useful to integrate this schema in the docker image or adding procedure or script to add this schema more easily.

Thank you so much!

**Comment by j-clavoie** [comment]
> Hi @j-clavoie,
> 
> Sorry for the delay here. There are [many related issues that you can take a look at](https://github.com/bitnami/containers/issues?q=is%3Aissue+LDAP_EXTRA_SCHEMAS). Checking the tickets there, you have 2 options
> 
>     * Mount your new schema to the `/opt/bitnami/openldap/etc/schema/` directory and add the new schema to the list of schemas to load in the `LDAP_EXTRA_SCHEMAS` env var. More info [here](https://github.com/bitnami/containers/issues/4984#issuecomment-1239807229)
> 
>     * However, you can also mount your schema in the `/schemas` directory that is the directory set in the `LDAP_CUSTOM_SCHEMA_DIR` env var and the container runs [this function](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L450) if the directory is not empty.
> 
> 
> Let us know if these solutions work for you.
> 
> Thanks

Hello!!

I was very occupied and I didn't have time to test information you provided to me, but it seems very useful, and I'll be able to work with that and fix my issue.

Thank you for your answer, it's really appreciated!
