### ISSUE TITLE
[bitnami/phpmyadmin] allow multiple servers

### ISSUE THREAD

**Issue by johnwc** [bitnami/containers#29629]
### Name and Version

bitnami/phpmyadmin:5.2.1

### What is the problem this feature will solve?

Currently the container only supports [setting one server](https://github.com/bitnami/containers/blob/main/bitnami/phpmyadmin/5/debian-11/rootfs/opt/bitnami/scripts/libphpmyadmin.sh#L91). We need to be able to set multiple, to support choosing a server to connect to from the login page. As well as setting [control*](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_controlhost) settings per server, to allow storing phpMyAdmin config settings per server.

### What is the feature you are proposing to solve the problem?

We need the ability to add multiple [`$cfg['Servers'][$i][xxx]`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers) sections to the phpMyAdmin config.

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket! Please note that the container allows adding custom scripts: https://github.com/bitnami/containers/blob/main/bitnami/phpmyadmin/5/debian-11/rootfs/post-init.sh

There you could add a script that adds the custom servers you are missing. Would that work for your use case?

**Comment by johnwc** [comment]
Is there a working example of this? How do you add custom scripts to the container during deployment?

**Comment by johnwc** [comment]
Are you saying that we would have to create a whole new container using this container as the base container? If so, that is not the request at all. We are needing to config this container to use more phpmyadmin options.

**Comment by javsalgar** [comment]
No, the idea is to use the Bitnami container but mounting a volume with the scripts.

**Comment by johnwc** [comment]
Can you describe how you would create a volume, add custom script, and then deploy this container, during deployment in Kubernetes. Versus updating a values.yml file and deploying with your helm chart using this container?

**Comment by CeliaGMqrz** [comment]
Hi @johnwc,

You can add your script using [docker-compose](https://github.com/bitnami/containers/tree/main/bitnami/phpmyadmin#docker-compose). Modify the docker-compose.yaml file and add the volume.  Make sure that the path is correct. Eg:

```.yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./sample_path_to/yourScript.sh:/docker-entrypoint-init.d/yourScript.sh
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
```
Run `docker-compose up -d` to deploy it. This [script](https://github.com/bitnami/containers/blob/main/bitnami/phpmyadmin/5/debian-11/rootfs/post-init.sh) should read the file you added in the `/docker-entrypoint-init.d` path.

If you want to implement this in Kubernetes you can use our [bitnami/phpmyadmin](https://github.com/bitnami/charts/tree/main/bitnami/phpmyadmin) chart. You can open another issue in bitnami/charts if you have any problems.

**Comment by johnwc** [comment]
@CeliaGMqrz wouldn't your chart need you to update this container image in order to support setting multiple servers?

**Comment by CeliaGMqrz** [comment]
Hi @johnwc,

You can customize the image and then use it with our chart. In both (chart and container) you can use custom scripts.  Note that we are a small team and our capacity is not too high. This is currently on our radar, but the priority is not too high. That said, we can't guarantee any ETA's. 

Would you like to contribute by creating a PR to solve the problem? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the guidelines for contributing.
