### ISSUE TITLE
Support API Gateway project - Apache APISIX

### ISSUE THREAD

**Issue by juzhiyuan** [bitnami/containers#29683]
### Name and Version

bitnami/apisix:3.2.0

### What is the problem this feature will solve?

Hi Team,

I would like to request that Bitnami add an official Docker image for Apache APISIX[1]. There is no official Bitnami Docker image for Apache APISIX, and I believe this would be a valuable addition to the Bitnami library.

- [1] https://github.com/apache/apisix

### What is the feature you are proposing to solve the problem?

As Apache APISIX grows in popularity, more developers are looking for an easy and reliable way to deploy it using Docker. By providing an official Bitnami Docker image for Apache APISIX, developers can save time and ensure that their deployments are secure and reliable.

The Apache APISIX team has already created a Docker image[1][2] for Apache APISIX that I believe would be a good fit for the Bitnami library. The Docker image is based on the latest Apache APISIX and includes all necessary dependencies and configurations. We're happy to work with the Bitnami team to make any necessary modifications to the image to ensure that it meets the Bitnami standards.

- [1] https://github.com/apache/apisix-docker/blob/release/apisix-3.2.0/centos/Dockerfile
- [2] https://hub.docker.com/r/apache/apisix

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request! I will forward this to the team for evaluation.

**Comment by juzhiyuan** [comment]
Hi @carrodher @javsalgar, may I know whether you have any updates here? 😊

**Comment by carrodher** [comment]
At this moment there are plans to add this product to the catalog, although we can't provide an ETA about when it will be released. We will update this issue once released so you are notified about the addition and can test it. Thanks!

**Comment by juzhiyuan** [comment]
Thanks for your update!

**Comment by juzhiyuan** [comment]
Just noticed the image has been released: https://hub.docker.com/r/bitnami/apisix

Thanks!!

**Comment by javsalgar** [comment]
Hi!

Yes! We are working on a helm chart right now :D
