### ISSUE TITLE
Container fatal error on M1 Apple Silicon

### ISSUE THREAD

**Issue by glodov** [bitnami/containers#2977]
### Name and Version

bitnami/opencart:3.0.3-8-debian-10-r75
docker version 4.1.1

### What steps will reproduce the bug?

1. Apple M1, MacOS Monterey (version 12.4)
2. Standard documentation [from here](https://github.com/bitnami/bitnami-docker-opencart).
3. Run `docker-compose up -d`
4. Error:
```bash
opencart 18:48:23.02 INFO  ==> ** OpenCart setup finished! **
opencart 18:48:23.14 INFO  ==> ** Starting Apache **

[Fri Aug 12 18:48:23.352710 2022] [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex 
(95)Operation not supported: could not create accept mutex
AH00015: Unable to open logs
```

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
