### ISSUE TITLE
no skywalking image found

### ISSUE THREAD

**Issue by joelzzhang** [bitnami/containers#29962]
### Name and Version

skywalking

### What is the problem this feature will solve?

No skywalking image found

### What is the feature you are proposing to solve the problem?

When will skywalking support mirror images be supported?

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
