### ISSUE TITLE
[bitnami/spark] Support python 3.10

### ISSUE THREAD

**Issue by MartenM** [bitnami/containers#29968]
### Name and Version

bitnami/spark

### What is the problem this feature will solve?

Currently, I am running a pySpark environment that uses Python 3.8. Creating a cluster of Spark using the Bitnami image is very easy and I and my team are loving it. However, when submitting using a driver that uses 3.10 the Spark cluster will not accept the job as the driver is using version 3.10 and the Spark instances are running Python 3.8. Spark doesn't accept minor version differences.

### What is the feature you are proposing to solve the problem?

- Make an image available with Python 3.10
- Make it easier to choose which Spark version the Spark environment is using. Not sure if this is possible (would maybe have to include both versions and use and ENV variable to point to the correct dir.

### What alternatives have you considered?

Downgrading to Python 3.8, but this will break quite a lot of scripts.

PS: If this is not within the scope, or this is not supported for other various reasons, just let me know.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that currently this is not easily supported in our automations, so at the moment we cannot provide different flavors of Spark (with different Python versions). My recommendation is to create a fork of Spark chaging the python installation line with a Python compatible with your scripts.

**Comment by alexeckert** [comment]
You could also try to package your interpreter into a conda-pack on submit
