### ISSUE TITLE
[bitnami/postgresql] Documentation for POSTGRES_CONNECTION_LIMIT doesn't match code

### ISSUE THREAD

**Issue by flexusjan** [bitnami/containers#30028]
### Name and Version

any

### What architecture are you using?

None

### What steps will reproduce the bug?

To increase your max_connections you can set an environment variable described in the readme.md:
'POSTGRESQL_POSTGRES_CONNECTION_LIMIT: Set the connection limit for the postgres user. No defaults.'

But if you set this environment variable and restart your container afterward, the max_connections doesn't change.

In the code the variable POSTGRES_POSTGRES_CONNECTION_LIMIT is used instead. It looks like a typo in the documentation.

### What is the expected behavior?

`-e  POSTGRESQL_POSTGRES_CONNECTION_LIMIT=200`

```
postgres=# show max_connections;
 max_connections 
-----------------
 200
(1 row)
```

### What do you see instead?

`-e  POSTGRESQL_POSTGRES_CONNECTION_LIMIT=200`

```
postgres=# show max_connections;
 max_connections 
-----------------
 100
(1 row)
```

### Additional information

Workaround:

`-e  POSTGRES_POSTGRES_CONNECTION_LIMIT=200`

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting the issue. Would you like to submit a PR fixing it?
