### ISSUE TITLE
[bitnami/mongodb-sharded] local users not created in replicaSet instances

### ISSUE THREAD

**Issue by fortra-cloudops-platform** [bitnami/containers#30050]
### Name and Version

bitnami/mongodb-sharded:6.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With a 2 shard 3 replica configuration
2. the local admin user isn't being created (MONGODB_INITIAL_PRIMARY_ROOT_USER and MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD). 
3. I can login into the cluster through mongos using the credentials I provide through existing secret, but no local user exists in the secondary nodes of each replicaset

### What is the expected behavior?

Same user/password should work on all instances of a replicaSet

### What do you see instead?

local admin user doesn't exist on secondary instances

**Comment by javsalgar** [comment]
HI,

Could you share a docker-compose.yml or values.yaml that reproduces the issue?
