### ISSUE TITLE
[bitnami/wordpress] zend_mm_heap corrupted after running for a while

### ISSUE THREAD

**Issue by Freundschaft** [bitnami/containers#30068]
### Name and Version

bitnami/wordpress:6.2.0-debian-11-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

just upgraded from a previous version to this version

### What is the expected behavior?

wordpress should run

### What do you see instead?

after a while the server crashes with zend_mm_heap corrupted showing up in logs

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket! Could you add more details on the platform you are using to deploy the container?

**Comment by tchernobog** [comment]
I am seeing the same with [[bitnami/dokuwiki] 20220731.1.0-debian-11-r72](https://github.com/bitnami/containers/pull/30074).

20220731.1.0-debian-11-r53 is not affected.

**Comment by ThomasChr** [comment]
Same here.

**Comment by floek** [comment]
Same here

**Comment by jotamartos** [comment]
Hi all, 

I've been trying to obtain more information regarding this issue but got different results from the ones you are running into. Let me explain the issues I found: 

- The bitnami/wordpress chart worked perfectly for me. I installed it using the default values and played with it a bit installing some themes and plugins. I didn't obtain any error and no restarts happened
- However, I found the error in the bitnami/dokuwiki chart and had some restarts. I then deployed the solution with the livenessProbe disabled and got no errors that time. The solution worked, and I requested the site several times with curl and didn't get any error either. I'm thinking about this error being a corner case with the livenessProbe and the PHP configuration.

```
while true; do sleep 1; curl -LI 34.145.233.152:80/doku.php ; done
```

```
diff --git a/bitnami/dokuwiki/values.yaml b/bitnami/dokuwiki/values.yaml
index 2064b734a..09b2a3006 100644
--- a/bitnami/dokuwiki/values.yaml
+++ b/bitnami/dokuwiki/values.yaml
@@ -196,7 +196,7 @@ resources:
 ## @param livenessProbe.successThreshold Minimum consecutive successes to be considered successful
 ##
 livenessProbe:
-  enabled: true
+  enabled: false
   initialDelaySeconds: 120
   periodSeconds: 10
   timeoutSeconds: 5
```

Boths solutions have been running for some time already and got no restarts 

```
$ k get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/jota-dk-dokuwiki-85cdd847c5-pfs6r    1/1     Running   0          48m
pod/jota-wp-mariadb-0                    1/1     Running   0          3h50m
pod/jota-wp-wordpress-546c57b7db-64bpb   1/1     Running   0          3h50m
```

Could you please let me know if you continue running into the same issue to know if it was transient or not? Does the error continue happening when disabling the livenessProbe as I saw? 

Thanks

**Comment by floek** [comment]
Hi, 
I'm using bitnami/wordpress:6.2.0-debian-11-r6 in a docker-compose setup without any healthchecks here and still have this issuse...

Best,
Floek

**Comment by jotamartos** [comment]
Hi @floek,

Are you actively using the application when receiving that error message or do you just leave the container running without doing anything? I've been trying to reproduce the issue using the docker-compose files of Dokuwiki and WordPress, and everything worked as expected 

```
$ docker ps -a
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS          PORTS                                         NAMES
c8ef95b5a71d   bitnami/wordpress:6.2.0-debian-11-r6   "/opt/bitnami/script…"   17 minutes ago   Up 17 minutes   0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   wordpress_wordpress_1
8619b5a0d832   bitnami/mariadb:10.6                   "/opt/bitnami/script…"   17 minutes ago   Up 17 minutes   3306/tcp                                      wordpress_mariadb_1
```

**Comment by floek** [comment]
I think the error pops up when using the wordpress admin pages, so interacting with uncached php. But, I've upgraded to r13 recently and will check if it comes again.

**Comment by tchernobog** [comment]
@jotamartos I updated dokuwiki to docker.io/bitnami/dokuwiki:2023.4.4-debian-11-r1 and it seems so far it is not crashing due to this error anymore. Note however that this also is a new version of dokuwiki, not just a base image refresh.

**Comment by jotamartos** [comment]
Thanks for the update @tchernobog, but I continue getting errors when using the Bitnami Dokuwiki chart with the image you mentioned. Taking all the instability into account I started changing some parameters in the PHP's conf file and found that if I increase the [output_buffering](https://www.php.net/manual/en/outcontrol.configuration.php#ini.output-buffering) parameter the solution doesn't throw any error. 

Could you please test that change on your side? You will need to launch the container, edit the configuration and restart it for the changes to take effect. In the meantime, I'm going to release a new version of the containers with this parameter set to 8196 (it's currently set to 4096).

**Comment by jotamartos** [comment]
Dokuwiki docker images were updated with the change I mentioned above.

https://github.com/bitnami/containers/pull/31605

WordPress is in progress. Please confirm if this change solves the problem.

**Comment by jotamartos** [comment]
Just a quick note to confirm that WordPress was also updated https://github.com/bitnami/containers/pull/31615

**Comment by floek** [comment]
The error has not occurred again here.
