### ISSUE TITLE
[bitnami/postgresql] Better support for adding extensions when using custom database

### ISSUE THREAD

**Issue by liefke** [bitnami/containers#30065]
### Name and Version

bitnami/postgresql:14

### What is the problem this feature will solve?

If I uses a custom database user (with `POSTGRESQL_USERNAME`), it is no longer possible to add an SQL script with `create extension ...` to `/docker-entrypoint-initdb.d/`. The reason is, that the custom user is used for running the init scripts now and that user has no privilege for `create extension` (see issue #16933).

Instead I have to set a `POSTGRESQL_POSTGRES_PASSWORD` and `POSTGRESQL_INITSCRIPTS_PASSWORD` (or build a shell script which makes use of that password to install the extension). Which is quite counterproductive, as my purpose of the less privileged database user is to prevent any login for the `postgres` user.

### What is the feature you are proposing to solve the problem?

I would suggest to provide an additional directory (e.g. `docker-entrypoint-initpostgres.d`) which is executed right before the custom user and database is created (right before the call to `postgresql_create_custom_database`). In that directory I could put my `create extension` scripts and any other script that needs the privileges of the `postgres` user.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by liefke** [comment]
I could provide a PR. Would I need to change the scripts for each PostgreSQL version directory or is there some magic "copying" in place?

**Comment by carrodher** [comment]
Thanks!
There is magic 😄 Although in the PR only one version is changed when our automated test & release pipeline all the versions will be updated

**Comment by liefke** [comment]
Just to be certain: It doesn't matter in which version I change the files? 

Maybe a short remark about that magic in https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md would help.

**Comment by carrodher** [comment]
Well, ideally the PR should contain all the changes in every supported branch of the application, in this way all the information is visible on GitHub. Since you specifically asked for that, I shared with you that hack of just doing the changes in one branch and then they will be automatically applied to the other branches **when a new release is done**, not immediately

**Comment by RoSk0** [comment]
For others like me facing issues when you want to create extension on a custom DB with a custom user - it is possible, but on only for the PostgreSQL 13+ and only for the **trusted extensions**. From the https://www.postgresql.org/docs/13/sql-createextension.html :

> For many extensions this means superuser privileges are needed. However, if the extension is marked trusted in its control file, then it can be installed by any user who has CREATE privilege on the current database.
