### ISSUE TITLE
[bitnami/ghost] lack of update since release 5.39+

### ISSUE THREAD

**Issue by matbgn** [bitnami/containers#30084]
### Name and Version

bitnami/ghost:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

From Docker Hub, pulling bitnami/ghost:latest image

### What do you see instead?

Image pulled will provide Ghost in release v5.39.0 (actual Ghost latest is v5.43.0).

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by CeliaGMqrz** [comment]
Hi @matbgn, 

Thanks for reporting this! The [new version](https://hub.docker.com/r/bitnami/ghost/tags) for Ghost has been released.
