### ISSUE TITLE
Discourse ARM 64

### ISSUE THREAD

**Issue by alf1e** [bitnami/containers#3036]
### Name and Version

bitnami/discourse:latest

### What is the problem this feature will solve?

Allow ARM64 users to use your package of Discourse.

### What is the feature you are proposing to solve the problem?

Build ARM64 images for Discourse

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ManjTi** [comment]
> Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉
> 
> <img alt="Screenshot 2023-02-24 at 08 16 50" width="1293" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">
> 
> This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.
> 
> [Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.
> 
> As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

Seems like bitnami/discourse image still doesn't have arm64 support

**Comment by javsalgar** [comment]
Right now we found issues building this application ARM. As soon as we manage to add ARM support for this application, we will notify the community.

**Comment by noplanman** [comment]
@javsalgar Any update or ETA on this? :crossed_fingers:

**Comment by carrodher** [comment]
Not for now, sorry, we still have on our backlog a task to review the apps not supporting ARM, but due to other priorities, we didn't find the bandwidth to work on it. We'll update this thread once we have more news
