### ISSUE TITLE
[bitnami/metrics-server] The binary file `metrics-server-0.6.3-1-linux-arm64-debian-11.tar.gz` does not work on arm64

### ISSUE THREAD

**Issue by icefery** [bitnami/containers#30402]
### Name and Version

bitnami/metrics-server:0.6.3-debian-11-r7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. With docker

   ```shell
   docker run --name metrics-server bitnami/metrics-server:0.6.3-debian-11-r7
   ```

   ```
   standard_init_linux.go:228: exec user process caused: exec format error
   ```

2. With binary

   ```shell
   # Extract download url from https://github.com/bitnami/containers/blob/main/bitnami/metrics-server/0/debian-11/Dockerfile
   wget https://downloads.bitnami.com/files/stacksmith/metrics-server-0.6.3-1-linux-arm64-debian-11.tar.gz
   tar -zxvf metrics-server-0.6.3-1-linux-arm64-debian-11.tar.gz
   cd metrics-server-0.6.3-linux-arm64-debian-11/files/metrics-server/bin
   ./metrics-server
   ```

   ```
   bash: ./metrics-server: cannot execute binary file: Exec format error
   ```

### What is the expected behavior?

On arm64 it works well.

### What do you see instead?

No

**Comment by migruiz4** [comment]
Hi @icefery, thank you for reporting this issue!

We have just released a new version of the `bitnami/metrics-server` image (`bitnami/metrics-server:0.6.3-debian-11-r9`) fixing this issue.

**Comment by icefery** [comment]
> Hi @icefery, thank you for reporting this issue!
> 
> We have just released a new version of the `bitnami/metrics-server` image (`bitnami/metrics-server:0.6.3-debian-11-r9`) fixing this issue.

It works well, thanks!
