### ISSUE TITLE
Harbor README has bad link.

### ISSUE THREAD

**Issue by scottmando2000** [bitnami/containers#3049]
### Name and Version

harbor-portal

### What steps will reproduce the bug?

The following link in the README goes to a 404 page.
https://github.com/bitnami/containers/blob/main/bitnami/harbor-portal/archive/master.tar.gz

### What is the expected behavior?

Updated download link.

### What do you see instead?

404 page.

### Additional information

https://github.com/bitnami/containers/blob/main/bitnami/harbor-portal/README.md?plain=1#L15

**Comment by carrodher** [comment]
We just sent the above PR fixing the wrong command, now it should work as usual. Please, feel free to reopen this issue if something doesn't work as expected

**Comment by scottmando2000** [comment]
This fix didn't quite work as intended. Now none of the services are able to create files in the `config` directory because a file called `config` is being symlinked to `2/debian-11/config`.

Upon starting, the following error also returns, confirming such.
`Error response from daemon: error while creating mount source path '/home/scott/docker/harbor/config/registry': mkdir /home/scott/docker/harbor/config: file exists`

**Comment by aoterolorenzo** [comment]
@scottmando2000 seems that the problem you mention is beyond the scope of this issue, since the README link is fixed and the working logic hasn’t been affected, so we shouldn’t be reopening it. Would you mind to create a new issue to report the problem? Thank you.

**Comment by scottmando2000** [comment]
> @scottmando2000 seems that the problem you mention is beyond the scope of this issue, since the README link is fixed and the working logic hasn’t been affected, so we shouldn’t be reopening it. Would you mind to create a new issue to report the problem? Thank you.

Thank you for your response, I have gone ahead and created a new issue. Since I have created issue #3584 this one can be set back to solved.
