### ISSUE TITLE
[bitnami/drupal] Unable to upload files >~1MB

### ISSUE THREAD

**Issue by amw5g** [bitnami/containers#30757]
### Name and Version

bitnami/drupal:9.5.7

### What architecture are you using?

None

### What steps will reproduce the bug?

When installing from bitnami docker images on a kubernetes cluster via rancher, using the following environmental vars
```
PHP_POST_MAX_SIZE: 64M
PHP_UPLOAD_MAX_FILESIZE: 64M
```

Create a new basic page, and add an inline image of filesize > 1MB

### What is the expected behavior?

The image uploads to the drupal file system, and the image renders when viewing the basic page content.

### What do you see instead?

Users are unable to add inline images to a body field in an basic page that are > ~1MB.  The specific error returned by Chrome on the edit page is `Couldn't upload file: image_name.png.`

### Additional information

When installing from bitnami docker images on a kubernetes cluster via rancher, using the following environmental vars
```
PHP_POST_MAX_SIZE: 64M
PHP_UPLOAD_MAX_FILESIZE: 64M
```
our users are unable to add inline images to a body field in an article that are > ~1MB.  The specific error returned by Chrome on the edit page is `Couldn't upload file: image_name.png.`  Images _under_ this size are included in the body and drupal file server without error.  We have tried with one of the default content types (Basic page) as well as a custom content type with a body field.

This happens for an admin user as well as a non-admin user.

I can confirm that drupal's `/admin/reports/status/php` page shows 
post_max_size = 64M
upload_max_filesize = 64M

Which is also confirmed by executing `php -i` from the command line on the host itself.

drupal documentation also recommend adding 
```
php_value  upload_max_filesize  64M
php_value  post_max_size  64M
``` 
to .htaccess files so that apache doesn't conflict, which I've done.

I expected to see something useful in drupal's logs, but there are no related errors/messages.  Likewise, no information in the apache web logs.

Clearly *an* image can be added, so it's not permissions or filesystem related.  We have have been able to upload smaller JPG and PNG files. I have confirmed there is sufficient space available in the  (>700GB).

Something appears to be restricting the max upload and/or post size in this image's configuration.

Any advice of what else to check; anyone able to use this drupal image and successfully upload inline images in a body field greater than 1MB?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by amw5g** [comment]
Limitation was not in drupal/apache.  Instead, it was on the ingress controller.
See: https://stackoverflow.com/questions/72480039/kubernetes-nginx-ingress-controller-cannot-upload-size-more-than-1mb
