### ISSUE TITLE
Package curl removed from zookeeper 

### ISSUE THREAD

**Issue by Farfaday** [bitnami/containers#30804]
### Name and Version

bitnami/3.8.1-debian-11

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

In https://github.com/bitnami/containers/blob/main/bitnami/zookeeper/3.8/debian-11/Dockerfile#L40 is curl now removed from the container.
This seems to have been removed in https://github.com/bitnami/containers/commit/caa69778929a2a4257b7d45e642da7cf3446262d

This breaks then the custom Probes defined there: https://github.com/bitnami/charts/tree/main/bitnami/zookeeper#configure-log-level as the curl command is not available.

Thanks!

### What is the expected behavior?

Custom Probes used as defined in the documentation should work out of the box.

### What do you see instead?

Readiness probe failed: /bin/bash: line 1: curl: command not found

**Comment by gongomgra** [comment]
Hi @Farfaday, 

Thanks for reporting this issue. I'm addressing a new internal task to revert the removal of `curl` from our Zookeeper image. We will keep you posted.

**Comment by gongomgra** [comment]
Hi @Farfaday,

We released a new revision of our Zookeeper images including `curl`. The helm chart should be automatically updated in a while, but in the meantime you can manually set the `latest` image when installing the chart.

```
$docker run --rm -it -u root bitnami/zookeeper:latest bash
Unable to find image 'bitnami/zookeeper:latest' locally
latest: Pulling from bitnami/zookeeper
b58a6b4ef2b2: Pull complete
Digest: sha256:869cf3df2bb5f9739f9e569483c36b6566428c92b8daf3bdab92fa457e2f3183
Status: Downloaded newer image for bitnami/zookeeper:latest
zookeeper 14:34:47.06
zookeeper 14:34:47.06 Welcome to the Bitnami zookeeper container
zookeeper 14:34:47.06 Subscribe to project updates by watching https://github.com/bitnami/containers
zookeeper 14:34:47.06 Submit issues and feature requests at https://github.com/bitnami/containers/issues
zookeeper 14:34:47.07

root@3228add563c1:/# curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
root@3228add563c1:/#
```
