### ISSUE TITLE
connection from airflow to an mssql server

### ISSUE THREAD

**Issue by alon050** [bitnami/containers#30806]
### Name and Version

bitnami/airflow:2.5.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

run airflow and try to connect to an mssql server using the airflow mssqlOperator.

### What is the expected behavior?

connection successful

### What do you see instead?

instead, I get the following error:
```
pymssql.OperationalError: (20017, b'DB-Lib error message 20017, severity 9\n Unexpected EOF from the server (server.hostname)\nDB-Lib error message 20002, severity 9: \n Adaptive server connection failed(server.domain)\nDB-Lib error message 20002, severity 9:\n Adaptive:
```
### Additional information

I tried running the following script from the official airflow image:
```bash
function install_mssql_client() {
    # Install MsSQL client from Microsoft repositories
    if [[ ${INSTALL_MSSQL_CLIENT:="true"} != "true" ]]; then
        echo
        echo "${COLOR_BLUE}Skip installing mssql client${COLOR_RESET}"
        echo
        return
    fi
    echo
    echo "${COLOR_BLUE}Installing mssql client${COLOR_RESET}"
    echo
    local distro
    local version
    distro=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
    version=$(lsb_release -rs)
    local driver=msodbcsql18
    curl --silent https://packages.microsoft.com/keys/microsoft.asc | apt-key add - >/dev/null 2>&1
    curl --silent "https://packages.microsoft.com/config/${distro}/${version}/prod.list" > \
        /etc/apt/sources.list.d/mssql-release.list
    apt-get update -yqq
    apt-get upgrade -yqq
    ACCEPT_EULA=Y apt-get -yqq install -y --no-install-recommends "${driver}"
    rm -rf /var/lib/apt/lists/*
    apt-get autoremove -yqq --purge
    apt-get clean && rm -rf /var/lib/apt/lists/*
}

install_mssql_client "${@}"
```
and it didn't work, so I also tried to install the packages: _freetds-dev_ and _freetds-bin_ on the image but still no luck...

**Comment by carrodher** [comment]
Airflow requires access to a PostgreSQL database to store information, at this moment there is no support for other database different than PostgreSQL

**Comment by alon050** [comment]
i dont want the metadata base server to be mssql, im trying to use the airflow mssql operator to execute sql queries in an mssql server.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
