### ISSUE TITLE
Persistent Data Folder and EFS Support for Bitnami Moodle - containers/bitnami/moodle/ 

### ISSUE THREAD

**Issue by cyberheed** [bitnami/containers#30834]
### Name and Version

bitnami/moodle4.1

### What is the problem this feature will solve?

Problem: The data folder in the Bitnami Moodle Docker image gets wiped every time the environment is rebuilt, resulting in data loss, especially in clustered environments where data consistency and availability are crucial.

### What is the feature you are proposing to solve the problem?

Allow ability to configure a persistent data folder for the Bitnami Moodle Docker image and add support for Amazon Elastic File System (EFS). This would enable users to mount an EFS volume and point the data folder to it, ensuring data persistence and sharing across multiple servers in clustered environments.

### What alternatives have you considered?

EFS
Volumes

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
