### ISSUE TITLE
[bitnami/keycloak] Hide db password in debug log

### ISSUE THREAD

**Issue by pckhoi** [bitnami/containers#31067]
### Name and Version

bitnami/keycloak:21

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set environment variable `BITNAMI_DEBUG` to "true"
2. Look at Keycloak logs

### What is the expected behavior?

Should not output the db password at all

### What do you see instead?

Keycloak logs db password: `Setting db-password to '...`

### Additional information

This line is to blame I think: https://github.com/bitnami/containers/blob/01d5e9b62dceaed6e886da469bcaa9b926ea692d/bitnami/keycloak/21/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L138

**Comment by gongomgra** [comment]
Hi @pckhoi,

Thanks for your message and for reporting this. We could improve the method to check if the password is being set and replace it with `_redacted_` in that case. Would you like to contribute by sending a PR?

**Comment by pckhoi** [comment]
Sure, I can do that.
