### ISSUE TITLE
The cassandra arm64 binary for the current Cassandra container Dockerfile doesn't exist. (cassandra-4.1.1-2-linux-arm64-debian-11.tar.gz)

### ISSUE THREAD

**Issue by juliangamble** [bitnami/containers#31076]
### Name and Version

bitnami/cassandra:4.1/debian-11:master

### What architecture are you using?

arm64

### What steps will reproduce the bug?

On a Mac M1 running Ventura 13.3.1

1. Git clone https://github.com/bitnami/containers.git
2. cd containers/bitnami/cassandra/4.1/debian-11
3. export TARGETARCH=arm64
4. docker build .

### What is the expected behavior?

Container builds to completion successfully. 

### What do you see instead?

`------`
`executor failed running [/bin/bash -o pipefail -c mkdir -p /tmp/bitnami/pkg/cache/ && cd /tmp/bitnami/pkg/cache/ &&     COMPONENTS=(       "python-3.9.16-9-linux-${OS_ARCH}-debian-11"       "java-1.8.362-4-linux-${OS_ARCH}-debian-11"       "gosu-1.16.0-5-linux-${OS_ARCH}-debian-11"       "yq-4.33.2-0-linux-${OS_ARCH}-debian-11"       "cassandra-4.1.1-2-linux-${OS_ARCH}-debian-11"     ) &&     for COMPONENT in "${COMPONENTS[@]}"; do       if [ ! -f "${COMPONENT}.tar.gz" ]; then         curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O ;         curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O ;       fi &&       sha256sum -c "${COMPONENT}.tar.gz.sha256" &&       tar -zxf "${COMPONENT}.tar.gz" -C /opt/bitnami --strip-components=2 --no-same-owner --wildcards '*/files' &&       rm -rf "${COMPONENT}".tar.gz{,.sha256} ;     done]: exit code: 1`

### Additional information

It appears to fail because this file does not exist: https://downloads.bitnami.com/files/stacksmith/cassandra-4.1.1-2-linux-arm64-debian-11.tar.gz

**Comment by juliangamble** [comment]
Also worth noting that the docker-library cassandra container builds just fine on an M1 Mac. 
https://github.com/docker-library/cassandra/blob/master/4.1/Dockerfile

**Comment by carrodher** [comment]
Cassandra is not supported in ARM at this moment, see the unsupported apps at https://github.com/bitnami/charts/issues/7305#issuecomment-1443187343

**Comment by smatvienko-tb** [comment]
Hey! The official Cassandra docker image already supports `arm64`. 
Is there an estimated date you plan to release the Bitnami/Cassandra arm64 image?
It's the only image that blocks me from moving all the stack to the arm64.
Thank you!
![image](https://github.com/bitnami/containers/assets/79898499/70b98c0e-c2f7-4352-83c3-1b51add63e93)

**Comment by carrodher** [comment]
At this moment there are no plans to work on the pending assets since ARM support was recently added and it is very likely that the issues we faced in the past are still present. We will revisit the list of exceptions in the future and we will update this issue.
