### ISSUE TITLE
InboundEmail module not loading the IMAP configured INBOX folders in the popup 

### ISSUE THREAD

**Issue by ccarabine** [bitnami/containers#31072]
### Name and Version

docker.io/bitnami/suitecrm:8

### What architecture are you using?

None

### What steps will reproduce the bug?

Using images 
docker.io/bitnami/suitecrm:8
docker.io/bitnami/mariadb:10.6

goto admin, email section, inbound email, new personal account
mail server address imap.gmail.com
protocol imap
mail server port 993
username
password

click on monitored folders select button

### What is the expected behavior?

meant to bring up the folders in your inbox to select the inbox or folder

### What do you see instead?

instead is empty
![image](https://user-images.githubusercontent.com/85298460/233323477-27db1f3c-be05-4dd9-aa23-27c356411e1d.png)

### Additional information

no inbox is displayed in the emails module

**Comment by ccarabine** [comment]
Not sure if this is related to gmail security?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/suitecrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ccarabine** [comment]
Someone said that php-imap and php-zip plugin might not have been installed
