### ISSUE TITLE
PARSE_DASHBOARD_PARSE_HOST default value is parse but should be localhost in the provided docker-compose

### ISSUE THREAD

**Issue by apederse** [bitnami/containers#31167]
### Name and Version

bitnami/parse-dashboard

### What architecture are you using?

amd64

### What steps will reproduce the bug?

To reproduce the bug use the provided example in the readme.
`curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/parse-dashboard/docker-compose.yml > docker-compose.yml docker-compose up -d`

By default the parse server is available on `localhost:1337` and via the docker internal network on `parse:1337`. In the bitnami parse-dashboard container the variable `PARSE_DASHBOARD_PARSE_HOST` is set to `parse`. However since the Docker network is not available outside of the Docker environment using the default config will result in the following error in the Parse-Dashboard UI: `Server not reachable: unable to connect to server`. 

The error can be observer using the console in the browser devtools which `outputs a net::ERR_NAME_NOT_RESOLVED error`. The reason is because the API calls from the Dashboard to Parse is executed in javascript in the browser which does not have access to the docker internal network and the `parse` hostname.

If the container is run manually via docker and not via docker-compose it also makes sense to have the the default value set to `localhost` and not `parse` which is unknown to both the container and the browser.

### What is the expected behavior?

The expected behaviour would be that by default the Dashboard is able to access the parse API.

### What do you see instead?

Proposed solution:

Either the container should have the default value set to `localhost` OR
The provided docker-compose.yaml should by default have the following environment variable set:
- PARSE_DASHBOARD_PARSE_HOST=localhost

Especially for first time users this will be valuable as things will work without changing anything in the provided docker-`compose.yaml` [File](https://github.com/bitnami/containers/blob/main/bitnami/parse-dashboard/docker-compose.yml). After demonstrating that things work by default the user should of course set the appropriate values according to the needs.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
