### ISSUE TITLE
[bitnami/matomo] Matomo misc folder overwritten by a bitnami symlink

### ISSUE THREAD

**Issue by maxplatonov** [bitnami/containers#31197]
### Name and Version

bitnami/matomo:4.13.1-debian-11-r3 and up

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Run bitnami/matomo:4.13.1-debian-11-r3 container 
2. Attach to the container
3. List /opt/bitnami/matomo/misc/ folder content

### What is the expected behavior?

You are expected to have the following content in /opt/bitnami/matomo/misc/
```shell
ls -al /opt/bitnami/matomo/misc/
-rw-rw-r-- 1 daemon root       341 Oct  6  2022 'How to install Matomo.html'
drwxrwxr-x 2 daemon root      4096 Oct  6  2022  cron
drwxrwxr-x 2 daemon root      4096 Oct  6  2022  log-analytics
drwxrwxr-x 2 daemon root      4096 Oct  6  2022  others
drwxrwxr-x 2 daemon root      4096 Oct  6  2022  proxy-hide-piwik-url
lrwxrwxrwx 1   1001 root        25 Feb 22 18:05  user -> /bitnami/matomo/misc/user

```

### What do you see instead?

```shell
ls -al /opt/bitnami/matomo/misc/ 
drwxrwsr-x 2 1001 1001      4096 Sep 29  2022 user

```

### Additional information

Commit to blame: https://github.com/bitnami/containers/pull/21190/files#diff-e19951af332fa558ba9f01b88be684ac524a4cbfb28addfb4bed05a88e5cc1a4R83

Please revert the commit as it disables the Matomo features such as web crons.

**Comment by CeliaGMqrz** [comment]
Hi @maxplatonov, 

Thanks for your comments!

In effect, we have modified this so that misc is a symbolic link. I just ran the container and it works for me. Could you check it again?

`$ docker run --rm -ti bitnami/matomo:4.13.1-debian-11-r3 bash`
```
I have no name!@3fb6a4a285a3:/$ ls -la /opt/bitnami/matomo/misc/
total 32
drwxrwxr-x  7 daemon root 4096 Jan 17 17:01  .
drwxrwxr-x 13 daemon root 4096 Jan 17 17:01  ..
-rw-rw-r--  1 daemon root  341 Jan 17 16:35 'How to install Matomo.html'
drwxrwxr-x  2 daemon root 4096 Jan 17 17:01  cron
drwxrwxr-x  2 daemon root 4096 Jan 17 17:01  log-analytics
drwxrwxr-x  2 daemon root 4096 Jan 17 17:01  others
drwxrwxr-x  2 daemon root 4096 Jan 17 17:01  proxy-hide-piwik-url
drwxrwxr-x  2 daemon root 4096 Jan 17 17:01  user
```
With `docker-compose up` I get the same result. It is possible that there is already an old volume created. Please make sure that an old volume does not exist or rename the volume before running the container.

**Comment by maxplatonov** [comment]
Hi @CeliaGMqrz, 

Thank you for your feedback. In fact my case concerns an update of an existing matomo instance. 
I guess there should be no issue for someone istalling matomo from scratch.

What steps would you suggest to update an existing matomo instance from v4.12 to v4.13.1-debian-11-r3 and up?

Kind regards, 

Maxim

**Comment by CeliaGMqrz** [comment]
Hi @maxplatonov , 

If you are using docker-compose, you can modify the image as : `image: bitnami/matomo:4.13.1-debian-11-r1` in the docker-compose.yaml file and run `docker-compose up -d` again. [This](https://github.com/bitnami/containers/blob/main/bitnami/matomo/4/debian-11/rootfs/opt/bitnami/scripts/libmatomo.sh#L209-L233) should update the container and keep the data. However, we recommend saving all data before upgrading the version.

Thanks for your feedback.
