### ISSUE TITLE
[bitnami/nats] Allow custom CLI args with NATS via ENV

### ISSUE THREAD

**Issue by TroyKomodo** [bitnami/containers#31485]
### Name and Version

bitnami/nats:latest

### What is the problem this feature will solve?

GitHub actions services does not allow for arguments only allows setting environment variables.

### What is the feature you are proposing to solve the problem?

Allow using an environment variable such as 
```
NATS_ARGS=-js
```

To enable jetstream

### What alternatives have you considered?

Making my own docker file.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. I believe this env var should be used in the run.sh script https://github.com/bitnami/containers/blob/main/bitnami/nats/2/debian-11/rootfs/opt/bitnami/scripts/nats/run.sh

Would you like to submit a PR adding support for the var?
