### ISSUE TITLE
[bitnami/logstash] Provided (mouted) configuration not working

### ISSUE THREAD

**Issue by cmahnke** [bitnami/containers#31495]
### Name and Version

bitnami/logstash:8.7.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```
docker run -it -v './conf/logstash.conf:/opt/bitnami/logstash/pipeline/fowi-logs.conf:ro'  --env LOGSTASH_PIPELINE_CONF_FILENAME=fowi-logs.conf  bitnami/logstash:8.7.0
```
**Notice the readonly mount for the configuration file**

### What is the expected behavior?

Logstash should use the provided file and not attempting to change it.

### What do you see instead?

Fails with:
```
8.7.0: Pulling from bitnami/logstash
5931b7a2ed74: Pull complete 
Digest: sha256:ad22bbf251b01877e2d072e799ee50c23bfd946f128ca878ab906927c891b010
Status: Downloaded newer image for bitnami/logstash:8.7.0
logstash 09:37:50.23 
logstash 09:37:50.23 Welcome to the Bitnami logstash container
logstash 09:37:50.23 Subscribe to project updates by watching https://github.com/bitnami/containers
logstash 09:37:50.23 Submit issues and feature requests at https://github.com/bitnami/containers/issues
logstash 09:37:50.24 
logstash 09:37:50.24 INFO  ==> ** Starting Logstash setup **
logstash 09:37:50.25 INFO  ==> Initializing Logstash
logstash 09:37:50.26 INFO  ==> Creating sample config file
/opt/bitnami/scripts/liblogstash.sh: line 142: /opt/bitnami/logstash/pipeline/fowi-logs.conf: Read-only file system
```

Changing the mount to mode read/write doesn't help either since this mangles the file with:
```
input {  
  http {
    ssl => false
    host => "0.0.0.0"
    port => 8080
  }
}

output {  
  stdout { }
}
```

I suspect these could be changed with env vars, but since not every option is available (see below) this won't really help.

### Additional information

There are several options:
* Check if the file is writeable before attempting  and don't fail if it's not (not a good option)
*  Don't even dare to write to the provided configuration
   * If changing the file is required by some configuration magic, hide it behind a flag or env var and _disable_  by default
* Provide more env var to configure the configuration file:
   *  LOGSTASH_BEATS_SSL
   *  LOGSTASH_BEATS_SSL_CERTIFICATE
   *  LOGSTASH_BEATS_SSL_KEY
   *  LOGSTASH_ELASTICSEARCH_INDEX
   *  LOGSTASH_ELASTICSEARCH_PIPELINE

**Comment by migruiz4** [comment]
Hi @cmahnke,

The path to mount Logstash configuration files is `/bitnami/logstash/pipeline/`, while you are using `/opt/bitnami/logstash/pipeline/`.

The following command should fix your issue:
```
docker run -it -v './conf/logstash.conf:/bitnami/logstash/pipeline/fowi-logs.conf:ro'  --env LOGSTASH_PIPELINE_CONF_FILENAME=fowi-logs.conf  bitnami/logstash:8.7.0
```

In case it helps, you can find this example and other use cases in the bitnami/logstash image's README.md: https://github.com/bitnami/containers/blob/main/bitnami/logstash/README.md#using-a-configuration-file
