### ISSUE TITLE
[bitnami/openldap] issues trying to use replication in openldap

### ISSUE THREAD

**Issue by dezmones** [bitnami/containers#31572]
### Name and Version

bitnami/openldap

### What is the problem this feature will solve?

Hi folks, i want to migrate an osixia/openldap because the lack of upgrades to the bitnami, the problem im facing is the replication, right now i got a multi-master replication that was made with env variables, with bitnami i had to do manually, but i cant load syncprov module (i think) im facing a lot of problems, so i will be glad if someone shares your expierences about this.

### What is the feature you are proposing to solve the problem?

replication

**Comment by javsalgar** [comment]
Hi,

I'm afraid the container code does not have this kind of automated support, but let's see if someone from the community can share their insights. Maybe a PR could be created adding that support
