### ISSUE TITLE
[bitnami/discourse] will have a headless display style during the second installation

### ISSUE THREAD

**Issue by zhangjig** [bitnami/containers#31571]
### Name and Version

bitnami/discourse

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. [docker pull  ](https://github.com/bitnami/containers/blob/main/bitnami/discourse/docker-compose.yml)
2. docker-compose up -d
3. docker-compose stop discourse
4. docker-compose rm -v discourse
5. docker-compose up -d

### What is the expected behavior?

when started，After accessing the website, the avatar in the upper right corner shows the name

### What do you see instead?

After the second or multiple installations, when visiting the website, the top right corner shows no images and a single line of text：message bookmarks preferences

**Comment by javsalgar** [comment]
Hi!

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by zhangjig** [comment]
There is no requirement to develop new features, but if I install the same container for the second or more times, the top right corner will appear, and the default avatar display is incorrect. The official course does not have this issue
