### ISSUE TITLE
[Discourse] base_url still example in running container

### ISSUE THREAD

**Issue by di-rect** [bitnami/containers#31597]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

I don't know

### Describe your issue as much as you can

Hi,

Using the Discourse image base_url in e-mail templates is still example.com and I don't see which ENV should be used to set this.

Can anyone describe how base_url is set within Discourse using the Bitnami image ?

Thanks!

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
