### ISSUE TITLE
[bitnami/mysql] Could not use /opt/bitnami/mysql/logs/mysqld.log for logging

### ISSUE THREAD

**Issue by pongpongcn** [bitnami/containers#31596]
### Name and Version

bitnami/mysql:8.0.33

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just run

```shell
docker run --rm -e ALLOW_EMPTY_PASSWORD=yes -e MYSQL_ENABLE_SLOW_QUERY=1 bitnami/mysql:8.0.33
```

### What is the expected behavior?

slow_query_log is on

### What do you see instead?

slow_query_log is off

error log

```
[ERROR] [MY-011263] [Server] Could not use /opt/bitnami/mysql/logs/mysqld.log for logging (error 2 - No such file or directory). Turning logging off for the server process. To turn it on again: fix the cause, then either restart the query logging by using "SET GLOBAL SLOW_QUERY_LOG=ON" or restart the MySQL server.
```

**Comment by headless-kjh** [comment]
I have similar issue
MY-011263
`"Could not use /opt/bitnami/mysql/logs/mysqld.log for logging (error 0 - Success). Turning logging off for the server process. To turn it on again: fix the cause, then either restart the query logging by using ""SET GLOBAL SLOW_QUERY_LOG=ON"" or restart the MySQL server."`

**Comment by mdhont** [comment]
I've reproduced the issue, we will investigate it. Thank you for reporting. We will update this thread with further information.

**Comment by headless-kjh** [comment]
![image](https://github.com/bitnami/containers/assets/108600575/1fea3ef2-dbaa-4547-baf3-bd59141df26c)

It works properly in k8s, Thank you
