### ISSUE TITLE
[bitnami/postgresql-ha] "alter system set archive_command ='....'" The slash\ should not be lost.

### ISSUE THREAD

**Issue by jieguolove** [bitnami/containers#31790]
### Name and Version

bitnami/postgresql-repmgr:latest

### What architecture are you using?

postgresql ha

### What steps will reproduce the bug?

1. centos7.9
2. bitnami/postgresql-repmgr
![image](https://user-images.githubusercontent.com/96612712/234492103-c2a65fc0-a97d-4b43-bd2b-340ddc1e55c5.png)

4. postgres@553df442a0c8:/opt/bitnami/postgresql/bin$ ./psql --version
psql (PostgreSQL) 15.2

My installation process is recorded on this web page：https://www.modb.pro/db/625507
when i set :
`alter system set archive_command = 'test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} \;';
select pg_reload_conf();`

You can reproduce the problem.

when the pg-0 or pg-1 restart，the Slash\  will be lost,just like the image:
![image](https://user-images.githubusercontent.com/96612712/234491887-06fd31ff-1a66-4c2a-8408-5f8e647baf94.png)

### What is the expected behavior?

The conf slash\ should not be lost.

### What do you see instead?

docker logs -f pg-1

`DETAIL: command is:
  /opt/bitnami/repmgr/events/router.sh 1001 standby_promote 1 "2023-04-26 05:24:12.184996+00" "server \"pg-1\" (ID: 1001) was successfully promoted to primary"
DEBUG: clear_node_info_list() - closing open connections
DEBUG: clear_node_info_list() - unlinking
[2023-04-26 05:24:12] [NOTICE] node 1001 has recovered, reconnecting
find: missing argument to `-exec'
2023-04-26 05:24:12.455 GMT [304] LOG:  archive command failed with exit code 1
2023-04-26 05:24:12.455 GMT [304] DETAIL:  The failed archive command was: test ! -f /bitnami/postgresql/arch/0000000A.history && cp --preserve=timestamps pg_wal/0000000A.history /bitnami/postgresql/arch/0000000A.history ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} ;
[2023-04-26 05:24:12] [NOTICE] monitoring cluster primary "pg-1" (ID: 1001)
find: missing argument to `-exec'
2023-04-26 05:24:13.466 GMT [304] LOG:  archive command failed with exit code 1
2023-04-26 05:24:13.466 GMT [304] DETAIL:  The failed archive command was: test ! -f /bitnami/postgresql/arch/0000000A.history && cp --preserve=timestamps pg_wal/0000000A.history /bitnami/postgresql/arch/0000000A.history ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} ;
2023-04-26 05:24:13.467 GMT [304] WARNING:  archiving write-ahead log file "0000000A.history" failed too many times, will try again later
2023-04-26 05:25:03.714 GMT [219] LOG:  received SIGHUP, reloading configuration files`

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket. However, it is not clear to me if the issue has to do with the Bitnami packaging of PostgreSQL or with PostgreSQL itself, as it is running directly a command with the `psql` tool. My advice would be to report the issue to PostgreSQL developers.

**Comment by jieguolove** [comment]
I think the issue has to do with the Bitnami packaging of PostgreSQL

**Comment by javsalgar** [comment]
Could you check if the issue occurs in other PostgreSQL containers so we can confirm that the issue is in the Bitnami packaging?

**Comment by jieguolove** [comment]
> Could you check if the issue occurs in other PostgreSQL containers so we can confirm that the issue is in the Bitnami packaging?
postgres=# select version();
                                              version
---------------------------------------------------------------------------------------------------
 PostgreSQL 14.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
(1 row)

I have test the pg14 version，when “docker stop pg-0”，then "docker start pg-0" become new standby，the same problem looks like:
![image](https://user-images.githubusercontent.com/96612712/236367072-9227cdd5-29ff-4821-abfa-e22bb8f826ef.png)
![image](https://user-images.githubusercontent.com/96612712/236366593-b98a837f-8839-49d7-ac46-74b7493ad01a.png)

**Comment by migruiz4** [comment]
Hi @jieguolove,

I have been able to reproduce the issue, but as my colleague @javsalgar suggested, it does not appear to be an issue with our image, but with PostgreSQL itself.

I would recommend reporting this issue to the PostgreSQL maintainers as they suggest here: https://www.postgresql.org/docs/current/bug-reporting.html

I was able to reproduce this issue using this [docker-compose.yml](https://github.com/bitnami/containers/blob/2482d94ff340ca3b6f7cdba3b10a27b7b3807125/bitnami/pgpool/docker-compose.yml).

The steps to reproduce are the following:
 - Start the docker-compose
 - Previously, create the folder `/bitnami/postgresql/arch` in both `pg-0` and `pg-1` (required by the `archive_command`):
    ```
    $ docker-compose exec pg-0 mkdir /bitnami/postgresql/arch
    $ docker-compose exec pg-1 mkdir /bitnami/postgresql/arch
    ```
 - In node `pg-0`, configure the `archive_command` including the special character `\`.
    ```
    $ docker-compose exec pg-0 bash
    I have no name!@296d35056356:/$ PGPASSWORD=adminpassword psql -U postgres -d postgres
    psql (15.2)
    Type "help" for help.
    
    postgres=# 
    postgres=# alter system set archive_command = 'test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} \;';
    ALTER SYSTEM
    postgres=# select pg_reload_conf();
     pg_reload_conf 
    ----------------
     t
    (1 row)
    
    postgres=# show archive_command;
                                                                                archive_command                           
                                                     
    ----------------------------------------------------------------------------------------------------------------------
    -------------------------------------------------
     test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; find /bitnami/post
    gresql/arch/ -type f -mtime +7 -exec rm -f {} \;
    (1 row)
    
    postgres=# select pg_switch_wal();
     pg_switch_wal 
    ---------------
     0/6039E08
    (1 row)
    postgres=#  exit
    I have no name!@296d35056356:/$ ls /bitnami/postgresql/arch/
    000000010000000000000006
    ```
    As you can see, the command was executed successfully, and the file `/bitnami/postgresql/arch/000000010000000000000006` exists.
    In the logs of node `pg-0` we can see:
    ```
    pgpool-pg-0-1    | 2023-05-05 08:52:44.761 GMT [306] LOG:  parameter "archive_command" changed to "test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} \;"
    ```
 - Restart all the nodes using `docker-compose down`. When the node-0 comes up, the `archive_command` is still correct:
    ```
    I have no name!@7516a67b01fe:/$ PGPASSWORD=adminpassword psql -U postgres -d postgres
    psql (15.2)
    Type "help" for help.
    
    postgres=# show archive_command;
                                                                                archive_command                           
                                                     
    ----------------------------------------------------------------------------------------------------------------------
    -------------------------------------------------
     test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; find /bitnami/post
    gresql/arch/ -type f -mtime +7 -exec rm -f {} \;
    (1 row)
    ```
 - Now, if I stop node` pg-0` and node `pg-1` promotes to primary, the following error messages will start appearing in the logs:
    ```
    pgpool-pg-1-1    | find: missing argument to `-exec'
    pgpool-pg-1-1    | 2023-05-05 09:26:51.924 GMT [343] LOG:  archive command failed with exit code 1
    pgpool-pg-1-1    | 2023-05-05 09:26:51.924 GMT [343] DETAIL:  The failed archive command was: test ! -f /bitnami/postgresql/arch/00000002.history && cp --preserve=timestamps pg_wal/00000002.history /bitnami/postgresql/arch/00000002.history ; find /bitnami/postgresql/arch/ -type f -mtime +7 -exec rm -f {} ;
    ```

I'm not sure what could be the cause, but it is probably caused by how pg-repmgr syncs the `archive_command` and its special character `\`

I would suggest using a command that does not require using `\`.

**Comment by jieguolove** [comment]
Thank you for your answer！
If we do not use bitnami's docker images with slashes, there is no problem with postgresql.
It is suspected that there is a problem with the switching script in the bitnami container.
And without a slash, the command is incomplete. The purpose here is to archive the log deletion policy and keep the archive log for a few days.

**Comment by migruiz4** [comment]
>  It is suspected that there is a problem with the switching script in the bitnami container.
Could you please provide more details about this? I'm sorry but I don't know what you meant by the 'switching script'.

>  And without a slash , the command is incomplete. The purpose here is to archive the log deletion policy and keep the archive log for a few days.

I understand that the command `find -exec \ ;` is incomplete without the slash and would otherwise fail.

My suggestion was aiming that, while I understand that the `find` command is very convenient, other commands could be used with the same purpose without needing the backslash (`\`) character to workaround this issue.

For example:
`
test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; for i in $(find /bitnami/postgresql/arch/ -type f -mtime +7); do rm -f $i; done
`

**Comment by jieguolove** [comment]
Now it can only be solved in this way.
Thanks a lot!

> > It is suspected that there is a problem with the switching script in the bitnami container.
> > Could you please provide more details about this? I'm sorry but I don't know what you meant by the 'switching script'.
> 
> > And without a slash , the command is incomplete. The purpose here is to archive the log deletion policy and keep the archive log for a few days.
> 
> I understand that the command `find -exec \ ;` is incomplete without the slash and would otherwise fail.
> 
> My suggestion was aiming that, while I understand that the `find -exec` command is very convenient, other commands could be used with the same purpose without needing the backslash (`\`) character to workaround this issue.
> 
> For example: `test ! -f /bitnami/postgresql/arch/%f && cp --preserve=timestamps %p /bitnami/postgresql/arch/%f ; for i in $(find /bitnami/postgresql/arch/ -type f -mtime +7); do rm -f $i; done`
