### ISSUE TITLE
[bitnami/solr] Ability to set ZK chroot

### ISSUE THREAD

**Issue by piotrrybicki** [bitnami/containers#31862]
### Name and Version

bitnami/solr:9.2.0

### What is the problem this feature will solve?

ZK chroot is hard-coded as /solr.
When dealing with 2 or more solrCloud instances with the same ZK ensemble, different ZK chroots are required. That is not possible now.

### What is the feature you are proposing to solve the problem?

I'd like to have an ability to specify ZK chroot param for each solr statefullset.
I can work on a PR for that.

will SOLR_ZK_CHROOT var name work for you?
I'd like to introduce this variable (with '/solr' as default). Firstly in this repo, secondly in bitnami solr helm chart repo.

### What alternatives have you considered?

official solr-operator helm chart has this ability:
https://github.com/apache/solr-operator/blob/main/helm/solr/values.yaml#L158

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! I think that `SOLR_ZK_CHROOT` works perfectly. Would you like to submit a PR?

**Comment by piotrrybicki** [comment]
Thanks. Yes I'd like to submit PR and I will start working on it shortly.
