### ISSUE TITLE
[bitnami/cassandra] Docker container bitnami/cassandra does not accept parameters

### ISSUE THREAD

**Issue by dima-online** [bitnami/containers#31885]
### Name and Version

bitnami/cassandra:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have 4 servers with docker. I need 4-node cassandra cluster with 2 seeds and custom user

step1 on first node:
```
docker run  -d --name cassandra \
  --hostname node01 \
  --net=host \
  -e CASSANDRA_HOST=node01 \
  -e CASSANDRA_CLUSTER_NAME=vcloud \
  -e CASSANDRA_PASSWORD_SEEDER=yes \
  -e CASSANDRA_RACK=vcloud \
  -e CASSANDRA_SEEDS=node01,node02 \
  -e CASSANDRA_USER=vcloud \
  -e CASSANDRA_PASSWORD='@QjzHnD!3pV2' \
  -v /opt/cassandra:/bitnami \
  bitnami/cassandra:latest
```
step2 on second node:  
```
docker run  -d --name cassandra \
  --hostname node02 \
  --net=host \
  -e CASSANDRA_HOST=node02 \
  -e CASSANDRA_CLUSTER_NAME=vcloud \
  -e CASSANDRA_RACK=vcloud \
  -e CASSANDRA_SEEDS=node01,node02 \
  -e CASSANDRA_USER=vcloud \
  -e CASSANDRA_PASSWORD='@QjzHnD!3pV2' \
  -v /opt/cassandra:/bitnami \
  bitnami/cassandra:latest
```
I do everything according to the documentation https://hub.docker.com/r/bitnami/cassandra
Maybe I don't understand how to start the cluster correctly

### What is the expected behavior?
```
root@node01:$ docker exec cassandra nodetool status

Datacenter: vcloud
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  172.16.248.7  108.75 KiB  256     100.0%            b1a010cc-d904-4637-bb9c-1a1723f5fe73  vcloud

**Datacenter:  vcloud
Rack:  vcloud
Username/password: vcloud/@QjzHnD!3pV2**
```
### What do you see instead?
```
root@node01:$ docker exec cassandra nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  172.16.248.7  108.75 KiB  256     100.0%            b1a010cc-d904-4637-bb9c-1a1723f5fe73  rack1

In the container operation protocol,
INFO [OptionalTasks:1] 2023-04-27 11:05:41,430 CassandraRoleManager.java:354 - Created default superuser role 'cassandra'

**Datacenter: datacenter1
Rack:rack1
Username/password: cassandra/cassandra**
```

### Additional information

The documentation says "_The default configurations will be populated to the conf/ directory if it's empty._" But
When launching the container, a configuration file is not created along the path **/path/to/cassandra-persistence/cassandra/conf/cassandra.yaml**

**Comment by dima-online** [comment]
INFO  [OptionalTasks:1] 2023-04-27 11:05:41,430 CassandraRoleManager.java:354 - Created default superuser role 'cassandra'

**Comment by javsalgar** [comment]
Hi,

Could you explain what you are mounting from `/opt/cassandra/`?

**Comment by dima-online** [comment]
> Hi,
> 
> Could you explain what you are mounting from `/opt/cassandra/`?

Data for the cluster node is stored there in case
1) reinstalling the cluster node
2) cluster version updates
Initially, this is an empty directory.

**Comment by jotamartos** [comment]
Hi @dima-online

>The documentation says "The default configurations will be populated to the conf/ directory if it's empty." But
When launching the container, a configuration file is not created along the path /path/to/cassandra-persistence/cassandra/conf/cassandra.yaml

You are right, the conf file is not persisted so the README file is wrong. As you can see in [other solutions](https://github.com/bitnami/containers/blob/main/bitnami/dokuwiki/20230404/debian-11/rootfs/opt/bitnami/scripts/dokuwiki-env.sh#L50), there is a DATA_TO_PERSIST env var that sets the files and directories that the container needs to persist in the /bitnami/APP_NAME folder. 

However, in the case of Cassandra, the /bitnami/cassandra directory contains the information that the application generates when executing it.

```
I have no name!@756ab4b5dd21:/$ ls -la /bitnami/cassandra/
total 12
drwxr-xr-x 3 1001 root 4096 May 22 13:40 .
drwx------ 3 1001 1001 4096 May 22 13:40 ..
drwxr-xr-x 6 1001 root 4096 May 22 13:40 data
I have no name!@756ab4b5dd21:/$ ls -la /bitnami/cassandra/data/
total 24
drwxr-xr-x 6 1001 root 4096 May 22 13:40 .
drwxr-xr-x 3 1001 root 4096 May 22 13:40 ..
drwxr-xr-x 2 1001 root 4096 May 22 13:40 commitlog
drwxr-xr-x 7 1001 root 4096 May 22 13:41 data
drwxr-xr-x 2 1001 root 4096 May 22 13:40 hints
drwxr-xr-x 2 1001 root 4096 May 22 13:40 saved_caches
```

That data directory is configured in the cassandra.yaml file 

```
I have no name!@756ab4b5dd21:/$ cat /opt/bitnami/cassandra/conf/cassandra.yaml | grep bitnami
hints_directory: '/bitnami/cassandra/data/hints'
  - /bitnami/cassandra/data/data
commitlog_directory: '/bitnami/cassandra/data/commitlog'
cdc_raw_directory: '/bitnami/cassandra/data/cdc_raw'
saved_caches_directory: '/bitnami/cassandra/data/saved_caches'
  keystore: '/bitnami/cassandra/secrets/keystore'
  truststore: '/bitnami/cassandra/secrets/truststore'
  keystore: '/bitnami/cassandra/secrets/keystore'
        - keystore: '/bitnami/cassandra/secrets/keystore'
```

Please note that the `/bitnami/cassandra/data/data` directory contains all the data Cassandra needs to store according to the conf file.

```
# Directories where Cassandra should store data on disk. If multiple
# directories are specified, Cassandra will spread data evenly across
# them by partitioning the token ranges.
# If not set, the default directory is $CASSANDRA_HOME/data/data.
data_file_directories:
  - /bitnami/cassandra/data/data
```

Is there any specific change in the cassandra.yaml file that you need to persist? Can you try mounting your own cassandra.yaml file at /opt/bitnami/cassandra/conf/cassandra.yaml? 

Finally, as you have found this issue in our documentation, would you like to contribute and update it? You can find all the information related to the contributions [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) and you will appear as a contributor of our project in the future.

Thanks! 😄
