### ISSUE TITLE
[bitnami/spark] connect hive metastore in a databse ro save in a valume

### ISSUE THREAD

**Issue by MammadTavakoli** [bitnami/containers#31972]
### Name and Version

bitnami/spark

### What is the problem this feature will solve?

this container has metastore buildin but ther is not way to save them out side of the containr

### What is the feature you are proposing to solve the problem?

if ther is a way to connet its metastore to a database like a postgres or save it in a volume it can save out side of container and use it for next.

**Comment by OneCricketeer** [comment]
You could mount a hive-site.xml file to configure your own remote metastore
