### ISSUE TITLE
[bitnami/wordpress] HTTPS Configuration tool can't find the bitnami instaltion path for  docker.io/bitnami/wordpress:6

### ISSUE THREAD

**Issue by tp1050** [bitnami/containers#32139]
### Name and Version

 docker.io/bitnami/wordpress:6

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
docker exec -u 0 -it my_wordpress_container bash # to get into the console ( is there any other way?!)


root@9aeee5b4047c:/# /opt/bitnami/bncert-tool  


> ``Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory []: 
```

### What is the expected behavior?

as outlined in the simple guidelines prided by bitnami i.e to ask for my domain name and generate the cert and boom like always I will be on my way to use my site

https://docs.bitnami.com/general/faq/administration/generate-configure-certificate-letsencrypt/

### What do you see instead?

```
Bitnami installation directory []: /opt/bitnami

Warning: The path does not seem to contain a valid Bitnami installation. Make 
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
```

### Additional information

tried the alternative way e.g going down the lego route and I got this instead 
```
cd /tmp
curl -Ls https://api.github.com/repos/xenolf/lego/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -i -
tar xf lego_vX.Y.Z_linux_amd64.tar.gz
sudo mkdir -p /opt/bitnami/letsencrypt
sudo mv lego /opt/bitnami/letsencrypt/lego
 \ /opt/bitnami/ctlscript.sh stop
```
but I got 
```
bash: /opt/bitnami/ctlscript.sh: No such file or directory
```

what is happening?!

**Comment by javsalgar** [comment]
Hi!

Please note that the bncert-tool is not meant to be used in bitnami containers, but in bitnami VMs. For containers and charts we recommend using other solutions like cert-manager.

**Comment by tp1050** [comment]
qhwew

> Hi!
> 
> Please note that the bncert-tool is not meant to be used in bitnami containers, but in bitnami VMs. For containers and charts we recommend using other solutions like cert-manager.
Thanks a million, how does one find the relevant docs?

**Comment by javsalgar** [comment]
Here you can find the docs for cert-manager: https://cert-manager.io/docs/
