### ISSUE TITLE
[bitnami/gitlab-runner-helper] gitlab-runner-helper location

### ISSUE THREAD

**Issue by pl4nty** [bitnami/containers#32156]
### Name and Version

bitnami/gitlab-runner-helper:15.11.0

### What architecture are you using?

amd64 and arm64

### What steps will reproduce the bug?

1. Use `gitlab-runner-helper:15.11.0` as helper image in Kubernetes executor
2. Receive the following error when uploading artifacts:
```
Uploading artifacts for successful job 00:01
Missing /usr/bin/gitlab-runner-helper. Uploading artifacts is disabled.
```
3. Confirm binary location with `docker run --entrypoint sh bitnami/gitlab-runner-helper:15.11.0`:
```
$ whereis gitlab-runner-helper
gitlab-runner-helper: /opt/bitnami/gitlab-runner-helper/bin/gitlab-runner-helper
```

### What is the expected behavior?

Builds and artifact uploads to succeed

### What do you see instead?

Builds succeed, but artifact uploads fail. It appears GitLab expects `gitlab-runner-helper` binary to be in `/usr/bin`

## Additional information

Binary was added in #24153

**Comment by pl4nty** [comment]
I've confirmed [copying to /usr/bin](https://github.com/pl4nty/containers/blob/main/gitlab-runner-helper/Dockerfile) resolves the issue

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Would you like to submit a PR adding a symlink in /usr/bin to the github-runner-helper in /opt/bitnami?
