### ISSUE TITLE
[bitnami/wordpress] Add Brotli support

### ISSUE THREAD

**Issue by kimdre** [bitnami/containers#32283]
### Name and Version

bitnami/wordpress:latest

### What is the problem this feature will solve?

Is it possible to enable brotli compression or could you add support for it in the wordpress image?

### What is the feature you are proposing to solve the problem?

Support for Brotli Compression in addition to Gzip, which will would let us use a more modern and efficient compression algorithm.

### What alternatives have you considered?

Installing it myelf. 
Trying to set it up myself did not work however, because `a2enmod` is missing.

**Comment by carrodher** [comment]
Thanks for your suggestion. At this moment there are no plans to add this extension in the container image by default, however, you can clone this repo and modify the _Dockerfile_ for your needs. For instance, if `a2enmod` is needed you can add it to the list of installable packages at https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/Dockerfile#L23
