### ISSUE TITLE
[bitnami/mariadb-galera] [support request] Galera doesn't seem to be auto evicting dead replicas

### ISSUE THREAD

**Issue by jerrac** [bitnami/containers#3238]
### Name and Version

bitnami/mariadb-galera:10.8

### What steps will reproduce the bug?

This is more a support question, and bug was the closest thing available since the forums are closed...

### What is the expected behavior?

Replicas should replace old, deleted, containers when an update is pushed.

### What do you see instead?

I've managed to get a somewhat working Galera cluster on Docker Swarm (yes, I know that isn't officially supported). After pushing an update to my cluster, something isn't right. First, only 2 of the 3 replicas appear to have been replaced. Second, the logs are getting spammed with messages like: 

```
2022-08-15 23:10:11 0 [Note] WSREP: (b8ce511d-b81f, 'tcp://0.0.0.0:4567') reconnecting to 499435dc-8f34 (tcp://172.20.11.26:4567), attempt 1680
```

Third, my wsrep_cluster_address variable still contains ip addresses from old, now deleted, containers.

Fourth, the new containers can't seem to start a db. When I exec into them and try to start mysql client, I get "Can't connect through socket" message.

Finally, when I check `wsrep_provider_options`, I see that `evs.auto_evict` is set to`0`.

Which makes me think my cluster isn't removing the old containers, and that, somehow, blocks my new containers.

Does that make sense? Any suggestions on how to get eviction working? If that's even my problem. 

### Additional information

My docker swarm is on Docker 20.10.17, Ubuntu 20.04, with 4 managers, and 3 workers. 

I've customized the Galera image with a wrapper entrypoint script that picks the replica that should start up first before calling the bitnami entrypoint script. I'm not customizing any other settings.

Thanks in advance!

**Comment by rafariossaa** [comment]
Hi,
  As you said, this is not supported. We don't test containers in a swarm environment, so I am not sure what could be happening here.
  Maybe, you want to study the behavior of the kubernetes chart and translate it to swarm. To debug this, I would suggest to try to start the process by hand checking the configurations created and if they are appropriate for this environment.
  Regarding `evs.auto_evict=0`, I think that could cause the old not to be removed, but I don't think it would stop other nodes to be added to the cluster.

**Comment by jerrac** [comment]
Thanks for the tips. :)

I did figure out that the initial shutdown of running replicas was due to my memory limits being too low. Right now I'm working on getting things back to where I can try and replicate the issue to see if those weird connection issues pop up again. 

I'll close this issue since I'm pretty sure there's not much sense in leaving it open. 

Thanks again!
