### ISSUE TITLE
[bitnami/discourse] Specify redis database

### ISSUE THREAD

**Issue by ausias-armesto** [bitnami/containers#32602]
### Name and Version

bitnami/discourse 3.0.3

### What is the problem this feature will solve?

As a Kubernetes administrator I would like to share the same redis instance among different apps by specifying a specific database, so the Redis resources are shared and the maintenance effort is reduced.

### What is the feature you are proposing to solve the problem?

For doing so, I'm configuring the [Helm Chart](https://artifacthub.io/packages/helm/bitnami/discourse) with the external Redis configuration and I would like to configure in that helm chart a new variable, for instance `externalRedis.db` and point Redis to use an specific database.

Discourse allows already this kind of configuration as it can be seen [here](https://github.com/discourse/discourse/blob/main/app/models/global_setting.rb#L212) but this container is not exporting that [variable](https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-11/rootfs/opt/bitnami/scripts/libdiscourse.sh#L256) so it can be used by the helm chart

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
