### ISSUE TITLE
How to install plugins? Where is the installation plugin manual

### ISSUE THREAD

**Issue by zhangjig** [bitnami/containers#32632]
### Name and Version

bitnami/discourse

### What is the problem this feature will solve?

How to install plugins? Where is the installation plugin manual

### What is the feature you are proposing to solve the problem?

How to install plugins? Where is the installation plugin manual

### What alternatives have you considered?

How to install plugins? Where is the installation plugin manual

**Comment by prsyahmi** [comment]
https://docs.bitnami.com/general/apps/discourse/configuration/install-plugins/
