### ISSUE TITLE
pgvector in Bitnami Postgres

### ISSUE THREAD

**Issue by nerdeveloper** [bitnami/containers#32677]
### Name and Version

bitnami/postgres:latest

### What architecture are you using?

amd64

### Additional information

Hello Team, I wanted to ask if pgvector is supported in bitnami Postgres https://github.com/pgvector/pgvector

if not, when will this be out, please?

**Comment by jotamartos** [comment]
That extension is not included by default, but you can easily install it in the container (using the root user )

```
install_packages git build-essential
cd /tmp
git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git
cd pgvector
export PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config
make
make install
```


and then connect to the database and load it

```
postgres=# CREATE EXTENSION vector;
CREATE EXTENSION
postgres=# \dx
                        List of installed extensions
  Name   | Version |   Schema   |                Description
---------+---------+------------+--------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 vector  | 0.4.1   | public     | vector data type and ivfflat access method
(2 rows)

postgres=#
```

**Comment by philippemnoel** [comment]
Any suggestions on how to install extensions which aren't TLEs? Specifically that would get the error "ERROR: permission denied for language c"

**Comment by coronabytes** [comment]
For anyone finding this thread and wants the easy solution...
```
FROM pgvector/pgvector:pg16 AS builder

FROM bitnami/postgresql-repmgr:16

COPY --from=builder /usr/lib/postgresql/16/lib/vector.so /opt/bitnami/postgresql/lib/
COPY --from=builder /usr/share/postgresql/16/extension/vector* /opt/bitnami/postgresql/share/extension/
```

**Comment by leejoyful** [comment]
> For anyone finding this thread and wants the easy solution...
> 
> ```dockerfile
> FROM pgvector/pgvector:pg16 AS builder
> 
> FROM bitnami/postgresql-repmgr:16
> 
> COPY --from=builder /usr/lib/postgresql/16/lib/vector.so /opt/bitnami/postgresql/lib/
> COPY --from=builder /usr/share/postgresql/16/extension/vector* /opt/bitnami/postgresql/share/extension/
> ```

After actual verification, the above solution is feasible, thank you very much
