### ISSUE TITLE
[bitnami/cassandra] Add CASSANDRA_AUTOMATIC_SSTABLE_UPGRADE

### ISSUE THREAD

**Issue by uladzimir-shelhunou-v2** [bitnami/containers#3267]
### Name and Version

bitnami/cassandra:4+

### What is the problem this feature will solve?

In Cassandra 4.0, a new configuration property called automatic_sstable_upgrade was added that will instruct Cassandra to upgrade the sstables automatically to the latest version.

Currently, it is not possible to specify it using environment variables.

### What is the feature you are proposing to solve the problem?

Add new environment variable CASSANDRA_AUTOMATIC_SSTABLE_UPGRADE

One important note is that the users of this option should have enough space available on the disk with data. General rule: available space > used disk space*2.

### What alternatives have you considered?

Currently it is only possible to override the whole Cassandra.yaml.

**Comment by fmulero** [comment]
Hi @uladzimir-shelhunou-v2 

Is not easy to cover all configuration properties for each application, for that reason we usually let users set their own configuration files, for example in this case you can mount your own `cassandra.yaml` file in `/bitnami/cassandra/conf/cassandra.yaml`.  To be perfectly blunt, this task will have a very low priority and couldn't give you an ETA. If you would like to contribute adding this feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by uladzimir-shelhunou-v2** [comment]
Hi @fmulero ,

I created a PR:

https://github.com/bitnami/containers/pull/3358

I tested changes locally but will also see if pipelines pass.

Regards,
Uladzimir

**Comment by fmulero** [comment]
Great! thanks a lot, we will review it soon.
