### ISSUE TITLE
[bitnami/rabbitmq] `RABBITMQ_COMMUNITY_PLUGINS` variable not working

### ISSUE THREAD

**Issue by aboutZZ** [bitnami/containers#32878]
### Name and Version

bitnami/rabbitmq:3.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I want to start RabbitMQ with `rabbitmq_delayed_message_exchange` plugin enabled. so I start container with following commands:
```sh
docker run -d --name mq \
  --network app -hmq \
  -e RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez \
  -e RABBITMQ_USERNAME=app \
  -e RABBITMQ_PASSWORD=xxxx \
  -v /path/to/data:/bitnami/rabbitmq/mnesia \
  bitnami/rabbitmq:3.11


docker logs -f -t --tail 50 mq
```

### What is the expected behavior?

The container start normally

### What do you see instead?

The container exit. Here is the container log:
```
2023-05-06T08:05:59.770720378Z rabbitmq 08:05:59.77 
2023-05-06T08:05:59.771836067Z rabbitmq 08:05:59.77 Welcome to the Bitnami rabbitmq container
2023-05-06T08:05:59.772932442Z rabbitmq 08:05:59.77 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-05-06T08:05:59.774041434Z rabbitmq 08:05:59.77 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-05-06T08:05:59.775175283Z rabbitmq 08:05:59.77 
2023-05-06T08:05:59.776400553Z rabbitmq 08:05:59.77 INFO  ==> ** Starting RabbitMQ setup **
2023-05-06T08:05:59.787786674Z rabbitmq 08:05:59.78 INFO  ==> Validating settings in RABBITMQ_* env vars..
2023-05-06T08:05:59.802172719Z rabbitmq 08:05:59.80 INFO  ==> Initializing RabbitMQ...
```

### Additional information

When I remove the `RABBITMQ_COMMUNITY_PLUGINS` variable, the container start normally.

**Comment by NowAnti** [comment]
I seem to have encountered this problem (bitnami/rabbitmq:3.12). Rabbitmq started normally, but the plug-in was not downloaded and installed. How did you solve it?

**Comment by KindBear** [comment]
Does somebody solve this issue?
I've added `RABBITMQ_COMMUNITY_PLUGINS: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez"` to docker-compose file but there is no effect on image.

```
 completed with 3 plugins.
 Server startup complete; 3 plugins started.
  * rabbitmq_management
  * rabbitmq_management_agent
  * rabbitmq_web_dispatch
```

**Comment by nowanti** [comment]
> 有人解决这个问题吗？我已经添加到 `RABBITMQ_COMMUNITY_PLUGINS: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez"` docker 撰写文件，但对图像没有影响。
> 
> ```
>  completed with 3 plugins.
>  Server startup complete; 3 plugins started.
>   * rabbitmq_management
>   * rabbitmq_management_agent
>   * rabbitmq_web_dispatch
> ```

Me, too. The same situation.

**Comment by CeliaGMqrz** [comment]
Hi @KindBear, @nowanti 

Sorry for my late response. 

The variable`RABBITMQ_COMMUNITY_PLUGINS` is to download the plugin and the `RABBITMQ_PLUGINS` is to enable it.  For example, you can try this configuration in docker-compose:

```
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez
      - RABBITMQ_PLUGINS=rabbitmq_delayed_message_exchange
```

Output:

```
I have no name!@04ab1d07093c:/$ rabbitmq-plugins list
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@localhost
 |/
[  ] rabbitmq_amqp1_0                  3.12.6
[  ] rabbitmq_auth_backend_cache       3.12.6
[  ] rabbitmq_auth_backend_http        3.12.6
[  ] rabbitmq_auth_backend_ldap        3.12.6
[  ] rabbitmq_auth_backend_oauth2      3.12.6
[  ] rabbitmq_auth_mechanism_ssl       3.12.6
[  ] rabbitmq_consistent_hash_exchange 3.12.6
[E*] rabbitmq_delayed_message_exchange 3.11.1
.
.
```

Thanks for your feedback!
