### ISSUE TITLE
add git-lfs

### ISSUE THREAD

**Issue by tomaszduda23** [bitnami/containers#33000]
### Name and Version

bitnami/git:2.40.1

### What is the problem this feature will solve?

Add support for LFS.

### What is the feature you are proposing to solve the problem?

Currently git-lfs has to be installed manually to use lfs.

**Comment by mdhont** [comment]
@tomaszduda23, I have created a task for adding it. We will notify you in this thread when it has been added.

**Comment by mdhont** [comment]
Hi @tomaszduda23,

git-lfs has been added in the latest release:

https://github.com/bitnami/containers/tree/main/bitnami/git/2/debian-11
