### ISSUE TITLE
Standardize Environment Variables: Either KC or KEYCLOAK

### ISSUE THREAD

**Issue by jtele2** [bitnami/containers#33282]
### Name and Version

bitnami/keycloak:20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm having to replicate all my environment variables because I don't know which ones are KEYCLOAK_ vs KC_.

For example:
```bash
# All KEYCLOAK_ does not work
environment:
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ENABLE_HTTPS=true
      - KEYCLOAK_HTTPS_USE_PEM=true
      - KEYCLOAK_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/fullchain.pem
      - KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/privkey.pem
      - KEYCLOAK_HTTPS_TRUST_STORE_FILE=/opt/bitnami/keycloak/certs/truststore.p12
      - KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD=test12345
      - KEYCLOAK_HTTPS_TRUST_STORE_TYPE=pkcs12
      - KEYCLOAK_HTTPS_CLIENT_AUTH=required
 ```

```bash
# All KC_ does not work
environment:
      - KC_PRODUCTION=true
      - KC_CREATE_ADMIN_USER=true
      - KC_ENABLE_HTTPS=true
      - KC_HTTPS_USE_PEM=true
      - KC_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/fullchain.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/privkey.pem
      - KC_HTTPS_TRUST_STORE_FILE=/opt/bitnami/keycloak/certs/truststore.p12
      - KC_HTTPS_TRUST_STORE_PASSWORD=test12345
      - KC_HTTPS_TRUST_STORE_TYPE=pkcs12
      - KC_HTTPS_CLIENT_AUTH=required
 ```

```bash
# Some combination of them works... simplest to just dupe everything
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ENABLE_HTTPS=true
      - KEYCLOAK_HTTPS_USE_PEM=true
      - KEYCLOAK_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/fullchain.pem
      - KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/privkey.pem
      - KEYCLOAK_HTTPS_TRUST_STORE_FILE=/opt/bitnami/keycloak/certs/truststore.p12
      - KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD=test12345
      - KEYCLOAK_HTTPS_TRUST_STORE_TYPE=pkcs12
      - KEYCLOAK_HTTPS_CLIENT_AUTH=required
      # KC?
      - KC_PRODUCTION=true
      - KC_CREATE_ADMIN_USER=true
      - KC_ENABLE_HTTPS=true
      - KC_HTTPS_USE_PEM=true
      - KC_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/fullchain.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/privkey.pem
      - KC_HTTPS_TRUST_STORE_FILE=/opt/bitnami/keycloak/certs/truststore.p12
      - KC_HTTPS_TRUST_STORE_PASSWORD=test12345
      - KC_HTTPS_TRUST_STORE_TYPE=pkcs12
      - KC_HTTPS_CLIENT_AUTH=required
```

### What is the expected behavior?

Either KEYCLOAK_* or KC_*

### What do you see instead?

I don't know which are KEYCLOAK vs KC

**Comment by corico44** [comment]
Hello @jtele2,

In the `keycloak-env.sh` file you can see the names of the available environment variables. Usually, keycloak's environment variables start with` KEYCLOAK_` but as you can see, some start with `KC_`. The use of `KC_ `is an alias to refer to the `KEYCLOAK_` variables. For example, `KEYCLOAK_HTTPS_CERTIFICATE_FILE` and `KC_HTTPS_CERTIFICATE_FILE` are the same variable but `KC_HTTPS_CERTIFICATE_FILE` is an alias that refers to `KEYCLOAK_HTTPS_CERTIFICATE_FILE`. So if you see that both exist in the `keycloak-env.sh` file, you can use whichever you want.

**Comment by jtele2** [comment]
> Hello @jtele2,
> 
> 
> 
> In the `keycloak-env.sh` file you can see the names of the available environment variables. Usually, keycloak's environment variables start with` KEYCLOAK_` but as you can see, some start with `KC_`. The use of `KC_ `is an alias to refer to the `KEYCLOAK_` variables. For example, `KEYCLOAK_HTTPS_CERTIFICATE_FILE` and `KC_HTTPS_CERTIFICATE_FILE` are the same variable but `KC_HTTPS_CERTIFICATE_FILE` is an alias that refers to `KEYCLOAK_HTTPS_CERTIFICATE_FILE`. So if you see that both exist in the `keycloak-env.sh` file, you can use whichever you want. 

Thanks @corico44, that helps a lot. 

Did I miss that in the docs? If you'd like me to submit a request for the docs, I can work on that. This knowledge would've saved me a lot of time.

**Comment by corico44** [comment]
There is no documentation about it. You can see the variables declared in the keycloak-env.sh file:
# variable will be overridden with the value specified in that file
```
keycloak_env_vars=(
    ....
    KEYCLOAK_HTTPS_CERTIFICATE_FILE
    ....
    KC_HTTPS_CERTIFICATE_FILE
    ...
)

KEYCLOAK_HTTPS_CERTIFICATE_FILE="${KEYCLOAK_HTTPS_CERTIFICATE_FILE:-"${KC_HTTPS_CERTIFICATE_FILE:-}"}"
export KEYCLOAK_HTTPS_CERTIFICATE_FILE="${KEYCLOAK_HTTPS_CERTIFICATE_FILE:-}"
```

If you open a PR adding documentation about this, we'll review it!

**Comment by jtele2** [comment]
> Shouldn't we default to what `keycloak` expect, a quick review of this document around `config` shows that `KC_` is the default whereas Bitnami have now diverged with `KEYCLOAK_` meaning one has to understand the internal logic of bitnamis scripts alongside the usual config options from keycloak to understand what the final behaviour of the system might be.
> 
> 
> 
> For example, `KC_HOSTNAME` which is actually within the scripts should be KC and KEYCLOAK should be removed https://www.keycloak.org/server/hostname
> 
> 

That's what I would think is best... that's why I opened the issue. It's tricky for new users.

**Comment by corico44** [comment]
Thanks for the info @jack1902. Since you have the concepts so clear, would you like to open a PR with these changes, please?
