### ISSUE TITLE
[bitnami/pgbouncer] Support setting soft file descriptor limit

### ISSUE THREAD

**Issue by nairb774** [bitnami/containers#3333]
### Name and Version

bitnami/pgbouncer:1.17.0

### What is the problem this feature will solve?

Right now the pgbouncer container/process will inherit the soft file descriptor limits set by the container runtime. Depending on the situation this limit could be higher or lower than what might be desired for running pgbouncer.

### What is the feature you are proposing to solve the problem?

It would be nice if the setup scripts (is that the right name) could detect if an environment variable is set, and if so, set the file descriptor ulimit accordingly. Obviously, this could be extended to other limits, but given pgbouncer is most likely to be impacted by fd limits, it seems reasonable to support this out of the box.

Since this generally a missing feature in Kubernetes, there could be an argument to make this a more general feature set for all bitnami containers and more of the limits. I leave that to the project's discretion on scoping.

### What alternatives have you considered?

Right now there is no good way to be able to change ulimits/rlimits for containers running on Kubernetes. There is an outstanding issue to enable configuring this: https://github.com/kubernetes/kubernetes/issues/3595.

An alternative could be configuring this at the node/host level, but that is only available for some setups, and at least for the options I've seen, would apply to all containers running on a node.

**Comment by gongomgra** [comment]
Hi @nairb774 

Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
