### ISSUE TITLE
bitnami/prestashop:latest  apache returns 302 localhost on request from puublic ip 

### ISSUE THREAD

**Issue by c3ph3us** [bitnami/containers#33380]
### Name and Version

bitnami/prestashop:latest 

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
docker run -d --name prestashop   -p 8080:8080 -p 8443:8443   --env ALLOW_EMPTY_PASSWORD=yes   --env PRESTASHOP_DATABASE_USER=bn_prestashop   --env PRESTASHOP_DATABASE_PASSWORD=bitnami   --env PRESTASHOP_DATABASE_NAME=bitnami_prestashop   --env PRESTASHOP_HOST=54.37.130.19 --network prestashop-network   --volume prestashop_data:/bitnami/prestashop    -v /home/debian/apch.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf  bitnami/prestashop:latest 
```
**HTTP**
```
URL żądania: http://54.37.130.195:8080/
Metoda żądania: GET
Kod stanu: 302 Found
Adres zdalny: 54.37.130.195:8080
Zasada dotycząca strony odsyłającej: strict-origin-when-cross-origin
```
**RESPONSE**
```
Connection: close
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Wed, 10 May 2023 21:00:25 GMT
Location: http://localhost/
Server: Apache
```

**REQUEST HEADERS** 
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: 54.37.130.195:8080
Pragma: no-cache
Sec-GPC: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
```
**DOCKER INFO**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 2
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
```

### What is the expected behavior?

to see a presta shop page 

### What do you see instead?

redirected url http://localhost

### Additional information

Linux i-vovmarket-b1 4.19.0-24-cloud-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/prestashop#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by vusallyv** [comment]
> ### Name and Version
> bitnami/prestashop:latest
> 
> ### What architecture are you using?
> amd64
> 
> ### What steps will reproduce the bug?
> ```
> docker run -d --name prestashop   -p 8080:8080 -p 8443:8443   --env ALLOW_EMPTY_PASSWORD=yes   --env PRESTASHOP_DATABASE_USER=bn_prestashop   --env PRESTASHOP_DATABASE_PASSWORD=bitnami   --env PRESTASHOP_DATABASE_NAME=bitnami_prestashop   --env PRESTASHOP_HOST=54.37.130.19 --network prestashop-network   --volume prestashop_data:/bitnami/prestashop    -v /home/debian/apch.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf  bitnami/prestashop:latest 
> ```
> 
> **HTTP**
> 
> ```
> URL żądania: http://54.37.130.195:8080/
> Metoda żądania: GET
> Kod stanu: 302 Found
> Adres zdalny: 54.37.130.195:8080
> Zasada dotycząca strony odsyłającej: strict-origin-when-cross-origin
> ```
> 
> **RESPONSE**
> 
> ```
> Connection: close
> Content-Length: 0
> Content-Type: text/html; charset=utf-8
> Date: Wed, 10 May 2023 21:00:25 GMT
> Location: http://localhost/
> Server: Apache
> ```
> 
> **REQUEST HEADERS**
> 
> ```
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.9
> Cache-Control: no-cache
> Connection: keep-alive
> Host: 54.37.130.195:8080
> Pragma: no-cache
> Sec-GPC: 1
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
> ```
> 
> **DOCKER INFO**
> 
> ```
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.10.4
>     Path:     /usr/libexec/docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.17.3
>     Path:     /usr/libexec/docker/cli-plugins/docker-compose
> 
> Server:
>  Containers: 10
>   Running: 2
>   Paused: 0
>   Stopped: 8
>  Images: 2
>  Server Version: 23.0.5
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Using metacopy: false
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 1
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
>  runc version: v1.1.5-0-gf19387a
>  init version: de40ad0
>  Security Options:
> ```
> 
> ### What is the expected behavior?
> to see a presta shop page
> 
> ### What do you see instead?
> redirected url http://localhost
> 
> ### Additional information
> Linux i-vovmarket-b1 4.19.0-24-cloud-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux

Hi.
```
UPDATE ps_configuration
SET value = <PRESTASHOP_HOST>
WHERE value = 'localhost';
```

```
UPDATE ps_shop_url
SET domain = <PRESTASHOP_HOST>
WHERE domain = 'localhost';
```
