### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by edwh** [bitnami/containers#33444]
### Name and Version

bitnami/discourse

### What is the problem this feature will solve?

Allow Discourse API access.

### What is the feature you are proposing to solve the problem?

I can see by looking in the Postgresql database that the Bitnami Discourse image creates a system API key.  But I don't know what the API key value is, so I can't use it to connect over the API.

It would be good if:

1. There was a fixed API key which was documented, or
2. There were environment variables which allowed the user to specify the system API key.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
