### ISSUE TITLE
[bitnami/airflow] LDAP search filter

### ISSUE THREAD

**Issue by mattholy** [bitnami/containers#33568]
### Name and Version

bitnami/airflow

### What is the problem this feature will solve?

Is there anyway to set the LDAP search filter in the config.py?

### What is the feature you are proposing to solve the problem?

Like a env?

**Comment by javsalgar** [comment]
Hi,

Could you try wit the `AIRFLOW_LDAP_SEARCH` env var?

https://github.com/bitnami/containers/blob/main/bitnami/airflow/2/debian-11/rootfs/opt/bitnami/scripts/libairflow.sh#L277
