### ISSUE TITLE
[bitnami/spark] Request for adding Spark 3.4.0 to Bitnami containers

### ISSUE THREAD

**Issue by goshaQ** [bitnami/containers#33717]
### Name and Version

bitnami/spark

### What is the problem this feature will solve?

The current Spark version (3.3.2) provided by Bitnami in their containers is not outdated yet, but it lacks several important features and bug fixes available in the latest version of Spark (3.4.0). This can cause challenges for developers who need access to these features to make their projects more efficient.

### What is the feature you are proposing to solve the problem?

We are requesting that Bitnami adds the latest version of Spark (3.4.0) to their Spark containers. This will allow developers to take advantage of the latest features and bug fixes in Spark and make their projects more efficient. It will also provide a better user experience for developers who rely on Bitnami containers for their work.

### What alternatives have you considered?

We have considered building our own Spark container with the latest version of Spark, but this requires significant effort and maintenance. Additionally, using a third-party container can be risky as it may not be up-to-date or secure. Therefore, we believe it would be beneficial for Bitnami to add the latest version of Spark to their official containers.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request. I will forward this to the team

**Comment by CeliaGMqrz** [comment]
Hi @goshaQ, 

Thanks for your patience.

[Spark 3.4](https://github.com/bitnami/containers/tree/main/bitnami/spark) is now available!  See [#35359](https://github.com/bitnami/containers/pull/35359)

We welcome your feedback!
