### ISSUE TITLE
[bitnami/kafka] server.properties file not recognized by container

### ISSUE THREAD

**Issue by dotMatthew** [bitnami/containers#33796]
### Name and Version

bitnami/kafka:3.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

If you try to use a config file instead of environment variables it will fail to start the kafka server

This is the server.properties file I am using:

```properties=
# The role of this server. Setting this puts us in KRaft mode
process.roles=broker,controller

# The node id associated with this instance's roles
node.id=1

# The connect string for the controller quorum
controller.quorum.voters=1@localhost:9093

# The address the socket server listens on.
listeners=BROKER://:9092,CONTROLLER://:9093

# Name of listener used for communication between brokers.
inter.broker.listener.name=BROKER

# Listener name, hostname and port the broker will advertise to clients.
# If not set, it uses the value for "listeners".
advertised.listeners=BROKER://192.168.178.75:9092

# A comma-separated list of the names of the listeners used by the controller.
controller.listener.names=CONTROLLER

# Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
listener.security.protocol.map=CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT

# A comma separated list of directories under which to store log files
log.dirs=/tmp/kraft-combined-logs

sasl.enabled.mechanisms=SCRAM-SHA-256
sasl.mechanism.controller.protocol=SCRAM-SHA-256
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-256

listener.name.broker.scram-sha-256.sasl.jaas.config='org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
listener.name.controller.scram-sha-256.sasl.jaas.config='org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
```
 
Im using the following command `docker run --name kafka-test -v ./config/server.properties:/bitnami/kafka/config/kraft/server.properties bitnami/kafka:3.4.0`

### What is the expected behavior?

A container with a running kafka server should be starting

### What do you see instead?

It prints out the following errors regarding some environment variables:

```
16:36:17.18 ERROR ==> The KAFKA_CFG_LISTENERS environment variable does not configure a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
16:36:17.19 ERROR ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure a secure protocol. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
```

### Additional information

Docker & Docker Compose:
```
Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:05:48 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:05:48 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker Compose version v2.17.2
```

**Comment by aoterolorenzo** [comment]
Hi @dotMatthew,

Our container logic could be setting some environment variables that could be at the same time overwritting your configuration if kafka's logic gives it preference.

Coulg you execute an `$:> env` in the container in order to see what's there?

**Comment by aoterolorenzo** [comment]
As you can see, from your error output:

```
16:36:17.18 ERROR ==> The KAFKA_CFG_LISTENERS environment variable does not configure a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
16:36:17.19 ERROR ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure a secure protocol. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
```

after seeing the `env` output, the container has set by default:

```
KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
```

Also, if you check our kafka [composer project](https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose.yml#L11), you will see that `ALLOW_PLAINTEXT_LISTENER` is set to `yes`.

So the solution would pass through both or choosing a different `KAFKA_ZOOKEEPER_PROTOCOL` and setting `KAFKA_CFG_LISTENERS` accordingly, or just setting `ALLOW_PLAINTEXT_LISTENER=yes`.

In any of the cases, I can see the discrepancy here, so I will take it to a discussion with the team in order to find a reason why using several values as a default that actually doesn't work with the exact default values, or update the default values to avoid that discrepancy

**Comment by dotMatthew** [comment]
But why is this necessary? If my server.properties would be loaded the broker would be configured with SASL_PLAINTEXT and SCRAM-SHA-256. Does SSL have to be enabled?

**Comment by dotMatthew** [comment]
Ok I can understand that. You might want to revise [this](https://github.com/bitnami/containers/tree/main/bitnami/kafka#full-configuration) section of the README of the Kafka image then

**Comment by aoterolorenzo** [comment]
Hi @dotMatthew 

Sorry for the delayed response.

I cannot see any exclusion between that section and the fact of kafka having a feature to also read (and in this case priorize) env vars configuration. Would you may want to propose any extra clarifications in the README? The team will be more than welcome to review any PR
