### ISSUE TITLE
[bitnami/pytorch] Reduce image size for PyTorch 1.9?

### ISSUE THREAD

**Issue by urig** [bitnami/containers#34376]
### Name and Version

bitnami/pytorch:1.9.1

### What is the problem this feature will solve?

The problem is that PyTorch v1.9 images are quite large, compared to v2.0 images.

For example, the `bitnami/pytorch:1.9.1` docker image is about [2.26GB compressed](https://hub.docker.com/layers/bitnami/pytorch/1.9.1/images/sha256-a62b11e228411287e24b2f6dfee366339a438d2f18d5bf451ae933bc3fe6057c?context=explore). The `bitnami/pytorch:2.0.1` docker image is significantly smaller, weighing [~350MB compressed](https://hub.docker.com/layers/bitnami/pytorch/2.0.1/images/sha256-152e514d1b3b2bb9e8b49034da4ed2a974e1d475002a6aaf66fe489756bead38?context=explore).

### What is the feature you are proposing to solve the problem?

I'm opening this issue to inquire whether it might be possible to reduce the size of PyTorch v1.9 images that Bitnami maintains, similar to what's been done in v2.0 images? Thank you.

### What alternatives have you considered?

I've considered upgrading my team's PyTorch v1.9 to v2.0 but that would require significant effort in porting existing code.

**Comment by javsalgar** [comment]
Hi

Please note that branch 1.9 is not maintained anymore by Bitnami. Currently we are only supporting branch 2.x.

**Comment by urig** [comment]
@javsalgar thanks. I didn't know that. If it's possible to reduce the size of the 1.9 image in a fashion similar to what's been in done in 2.0 and later I would love to give it a try and submit a PR. Might that be accepted? How can I learn what's been done in 2.0?

**Comment by carrodher** [comment]
Unfortunately, once a branch is deprecated there are no new releases of that specific branch anymore. You can clone this repo, go to the latest commit where 1.9 was an active branch (https://github.com/bitnami/containers/commit/3f9bf9b7ffc08720fc20c7f110df54e24c1aa2a7) and do any change you can consider in order to reduce the size; then build your own image.

**Comment by urig** [comment]
Thank you @carrodher . Much appreciated.
