### ISSUE TITLE
[bitnami/argo-cd] git fetching with "--config-env" option issue in repo server 

### ISSUE THREAD

**Issue by sapcy** [bitnami/containers#34541]
### Name and Version

bitnami/argo-cd:2.6.7-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Test environment
- OS: RHEL 9.1
- Platform: Kubernetes (using helm-chart argo-cd-4.7.2)
2. Step
An error occurred while fetching from the git repository when registering the application in argo-cd GUI.

### What is the expected behavior?

The application to register normally with argocd.

### What do you see instead?

- argo-cd repo-server error-log
```bash
...
time="2023-05-19T02:20:14Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch default: `git --config-env http.extraHeader=ARGOCD_GIT_AUTH_HEADER fetch origin --tags --force --prune` failed exit status 129: unknown option: --config-env

usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]"

grpc.code=Internal grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-05-19T02:20:14Z" grpc.time_ms=150.775 span.kind=server system=grpc
```

### Additional information

I think it was happend because of repository setting with option "Force basic auth".

The following link is commit history about adding "--config-env" option.  
[https://github.com/argoproj/argo-cd/commit/b600da13185a7e83f1c7c290a4a39949fb48416a#diff-58b81ee1c1dd86272a44765f0a12322034b6a7a98b165e67a55d2c1ee936c51f](https://github.com/argoproj/argo-cd/commit/b600da13185a7e83f1c7c290a4a39949fb48416a#diff-58b81ee1c1dd86272a44765f0a12322034b6a7a98b165e67a55d2c1ee936c51f)

But, inside that bitnami/argo-cd:2.6.7-debian-11-r8 container, that option doesn't exist because of the git version. 
In container, git version is 2.30.2
```bash
argo-cd-repo-server:/$ git --version
git version 2.30.2
```

**The git version with that option applied is 2.31.0, so need git version upgrade to at least 2.31.0.**
[https://git-scm.com/docs/git/2.31.0](https://git-scm.com/docs/git/2.31.0)

**Comment by rafariossaa** [comment]
Hi,
  As you could see in the [Dockerfile](https://github.com/bitnami/containers/blob/main/bitnami/argo-cd/2/debian-11/Dockerfile), we are installing the git provided by debian packages. It should be upgraded as soon as Debian upgrades the version in the package repository.

**Comment by sapcy** [comment]
okay. I got it. 
And so far no problems have occurred except for the "Force basic auth" feature.

Thank you. 😌

**Comment by rafariossaa** [comment]
You are welcome. 
I am closing this issue. If you have further questions on this topic, please don't hesitate to reopen it.
