### ISSUE TITLE
[bitnami/kafka] : Container Crashes with Internal & External Clients Setup

### ISSUE THREAD

**Issue by exaucae** [bitnami/containers#34896]
### Name and Version

bitnami/kafka 3.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. 
````sh
 curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/kafka/docker-compose.yml > docker-compose.yml
 docker-compose up -d
````
Observe that container is up and running.

2. [setup internal & external clients](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#accessing-apache-kafka-with-internal-and-external-clients):

```diff
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
+     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
+     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
```

```diff
    ports:
-     - '9092:9092'
+     - '9094:9094'
```

3. Run  `docker-compose up -d` again and Observe container being stuck at KRaft initialization:

### What is the expected behavior?

Container is up and running after internal & external clients setup

### What do you see instead?

````
kafka 01:58:25.94 
2023-05-22T01:58:25.957020200Z kafka 01:58:25.95 Welcome to the Bitnami kafka container
2023-05-22T01:58:25.962081700Z kafka 01:58:25.95 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-05-22T01:58:25.970197300Z kafka 01:58:25.96 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-05-22T01:58:25.975157100Z kafka 01:58:25.97 
2023-05-22T01:58:25.977683200Z kafka 01:58:25.97 INFO  ==> ** Starting Kafka setup **
2023-05-22T01:58:26.082884000Z kafka 01:58:26.08 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
2023-05-22T01:58:26.106421400Z kafka 01:58:26.10 INFO  ==> Initializing Kafka...
2023-05-22T01:58:26.120906200Z kafka 01:58:26.11 INFO  ==> No injected configuration files found, creating default config files
2023-05-22T01:58:26.249807500Z kafka 01:58:26.24 INFO  ==> Initializing KRaft...
2023-05-22T01:58:26.251851600Z kafka 01:58:26.25 INFO  ==> Formatting storage directories to add metadata...
kafka exited with code 1
````

### Additional information

container runs fine without client setup. But that's the setup suggested in the docs. Could it be due to my using KRaft instead of Zookeeper? If so, we'd need to clarify that in the docs.

**Comment by ianmcfall** [comment]
Same issue.

**Comment by exaucae** [comment]
Here's a positive update: the container finally ran.

I added ` BITNAMI_DEBUG=yes`. The logs made it clear that I was missing security protocol map for EXTERNAL & CONTROLLER listeners. I was quite certain they would default to plaintext. If that's an expected behavior, perhaps, the team can make it clear in the docs? If not, there's something to investigate in regards to defaults for `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP`


Meanwhile, here's my full docker-compose.yml file. Hope it helps, @ianmcfall.
I was able to connect from host on `localhost:9004`, and from other containers on `kafka:9092`

````yaml

version: "2"

volumes:
  kafka_data:
    driver: local

networks:
  kafka_net:
    driver: bridge

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    networks:
      - kafka_net
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=9YoavaRpTCOitT3Dm2OQFQ
      # For more details see See https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

````

**Comment by ianmcfall** [comment]
Brilliant! @exaucae 

Thanks for the solution and succinct explanation. Not only did this help me get the bitnami/kafka container up and running, but I was able to connect from other containers on `kafka:9092` and some golang services on `localhost:9094`.

**Comment by exaucae** [comment]
Thanks everyone, this issue is safe to close now. I've seen an update in the docs from this commit: https://github.com/bitnami/containers/commit/c98b4dd66f0f8094850a0c7e1c192ead7d8cd119. Not sure it includes all fixes I've provided, but in any case [my previous comment](https://github.com/bitnami/containers/issues/34896#issuecomment-1557673518) should help anyone moving forward:

**Comment by l0gicgate** [comment]
@exaucae Why can't we connect externally using `localhost:9092`? I'm able to connect via `localhost:9094` but I want to use the main `9092` port as it's the official broker port.
