### ISSUE TITLE
[bitnami/mysql] :8.0 image did not update

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#34891]
### Name and Version

bitnami/mysql:8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

$ docker pull bitnami/mysql:8.0
```
bitnami/mysql         8.0         9621fb4b01f3   17 months ago   729MB
```
the image were updated 17 months ago.

### What do you see instead?

```
docker images | grep -E "^bitnami\/mysql"
bitnami/mysql        8.0.33      393872a7741d   6 hours ago     522MB
bitnami/mysql        8.0         9621fb4b01f3   17 months ago   729MB
```

**Comment by javsalgar** [comment]
Hi, 

It seems that you did not force the image download and it is using a cached one. You can check in the Docker Hub page that the tag was indeed updated.

<img width="467" alt="image" src="https://github.com/bitnami/containers/assets/1133777/1602ed05-c2f5-4cc2-a1fc-013941367c38">
