### ISSUE TITLE
[bitnami/harbor] 2.7.1 startup error

### ISSUE THREAD

**Issue by foreverrice** [bitnami/containers#34903]
### Name and Version

bitnami/harbor:2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

when I use version-2.7.1,nginx cannot found env,but 2.8.1 and 2 can startup

### What is the expected behavior?

I can startup by docker-compose.yml in harbor 2.7.x，I change harbor image version in deocker-compose.yml.

### What do you see instead?

every times can appear

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml file that triggers the error?

**Comment by foreverrice** [comment]
> Hi,
> 
> Could you share the docker-compose.yml file that triggers the error?

When I run docker compose
harbor-jobservice     | harbor-jobservice 07:58:08.54 INFO  ==> No custom certificates were installed in the system
harbor-jobservice     | harbor-jobservice 07:58:08.54 INFO  ==> Waiting for harbor-core to be started and ready
harbor-portal         | nginx 07:58:08.56 INFO  ==> Validating settings in NGINX_* env vars
harbor-portal         | Generating RSA private key, 4096 bit long modulus (2 primes)
harbor-portal         | ..........................................++++
nginx                 | nginx 07:58:08.99 
nginx                 | nginx 07:58:08.99 Welcome to the Bitnami nginx container
nginx                 | nginx 07:58:08.99 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx                 | nginx 07:58:08.99 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx                 | nginx 07:58:08.99 
nginx                 | nginx 07:58:09.00 INFO  ==> ** Starting NGINX setup **
nginx                 | nginx 07:58:09.02 INFO  ==> Validating settings in NGINX_* env vars
nginx                 | nginx 07:58:09.02 WARN  ==> The NGINX configuration file '/opt/bitnami/nginx/conf/nginx.conf' is not writable by current user. Configurations based on environment variables will not be applied.
nginx                 | Generating RSA private key, 4096 bit long modulus (2 primes)
harbor-portal         | ...............................................................................++++
harbor-portal         | e is 65537 (0x010001)
harbor-portal         | Signature ok
harbor-portal         | subject=CN = example.com
harbor-portal         | Getting Private key
harbor-portal         | nginx 07:58:09.21 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
harbor-portal         | nginx 07:58:09.21 INFO  ==> Initializing NGINX
harbor-portal         | realpath: /bitnami/nginx/conf/vhosts: No such file or directory
harbor-portal         | nginx 07:58:09.24 INFO  ==> No custom certificates were installed in the system
harbor-portal         | nginx 07:58:09.24 INFO  ==> ** harbor-portal setup finished! **
harbor-portal         | 
harbor-portal         | nginx 07:58:09.26 INFO  ==> ** Starting NGINX **
nginx                 | ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................++++
nginx                 | ...............++++
nginx                 | e is 65537 (0x010001)
nginx                 | Signature ok
nginx                 | subject=CN = example.com
nginx                 | Getting Private key
nginx                 | nginx 07:58:11.65 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx                 | nginx 07:58:11.66 INFO  ==> Initializing NGINX
nginx                 | realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx                 | nginx 07:58:11.68 INFO  ==> ** NGINX setup finished! **
nginx                 | 
nginx                 | nginx 07:58:11.69 INFO  ==> ** Starting NGINX **
nginx                 | 2023/05/23 07:58:11 [emerg] 1#1: host not found in upstream "core:8080" in /opt/bitnami/nginx/conf/nginx.conf:18
nginx                 | nginx: [emerg] host not found in upstream "core:8080" in /opt/bitnami/nginx/conf/nginx.conf:18
nginx exited with code 1
harbor-jobservice     | harbor-jobservice 07:59:08.84 ERROR ==> Timeout waiting for harbor-core to be available
harbor-jobservice exited with code 1
=======
My docker-compose.yml
version: '2'

services:
  registry:
    image: docker.io/bitnami/harbor-registry:2.7.1
    environment:
      - REGISTRY_HTTP_SECRET=CHANGEME
    volumes:
      - registry_data:/storage
      - ./config/registry/:/etc/registry/:ro
  registryctl:
    image: docker.io/bitnami/harbor-registryctl:2.7.1
    environment:
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
      - REGISTRY_HTTP_SECRET=CHANGEME
    volumes:
      - registry_data:/storage
      - ./config/registry/:/etc/registry/:ro
      - ./config/registryctl/config.yml:/etc/registryctl/config.yml:ro
  postgresql:
    image: docker.io/bitnami/postgresql:13
    container_name: harbor-db
    environment:
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=registry
    volumes:
      - postgresql_data:/bitnami/postgresql
  core:
    image: docker.io/bitnami/harbor-core:2.7.1
    container_name: harbor-core
    depends_on:
      - registry
      - chartmuseum
    environment:
      - CORE_KEY=change-this-key
      - _REDIS_URL_CORE=redis://redis:6379/0
      - SYNC_REGISTRY=false
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_REG=redis://redis:6379/1
      - PORT=8080
      - LOG_LEVEL=info
      - EXT_ENDPOINT=http://xx.xx.xx.xx:80
      - DATABASE_TYPE=postgresql
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_SSLMODE=disable
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://core:8080/service/token
      - HARBOR_ADMIN_PASSWORD=bitnami
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
      - ADMIRAL_URL=
      - WITH_NOTARY=False
      - WITH_CHARTMUSEUM=True
      - CHART_REPOSITORY_URL=http://chartmuseum:8080
      - CORE_URL=http://core:8080
      - JOBSERVICE_URL=http://jobservice:8080
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password
      - READ_ONLY=false
      - RELOAD_KEY=
    volumes:
      - core_data:/data
      - ./config/core/app.conf:/etc/core/app.conf:ro
      - ./config/core/private_key.pem:/etc/core/private_key.pem:ro
  portal:
    image: docker.io/bitnami/harbor-portal:2.7.1
    container_name: harbor-portal
    depends_on:
      - core
  jobservice:
    image: docker.io/bitnami/harbor-jobservice:2.7.1
    container_name: harbor-jobservice
    depends_on:
      - redis
      - core
    environment:
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
      - CORE_URL=http://core:8080
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password
    volumes:
      - jobservice_data:/var/log/jobs
      - ./config/jobservice/config.yml:/etc/jobservice/config.yml:ro
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  harbor-nginx:
    image: docker.io/bitnami/nginx:1.23
    container_name: nginx
    volumes:
      - ./config/proxy/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    ports:
      - '80:8080'
    depends_on:
      - postgresql
      - registry
      - core
      - portal
  chartmuseum:
    container_name: chartmuseum
    image: docker.io/bitnami/chartmuseum:0
    environment:
      - CACHE=redis
      - CACHE_REDIS_ADDR=redis:6379
      - CACHE_REDIS_DB=1
      - DEPTH=1
      - PORT=8080
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/bitnami/data
      - ALLOW_OVERWRITE=true
      - INDEX_LIMIT=0
    volumes:
      - chartmuseum_data:/bitnami/data
volumes:
  registry_data:
    driver: local
  core_data:
    driver: local
  jobservice_data:
    driver: local
  postgresql_data:
    driver: local
  chartmuseum_data:
    driver: local

**Comment by migruiz4** [comment]
Hi @foreverrice,

Could you please share the logs for the `harbor-core` container?

In the logs you shared, I can see both your `nginx` and `jobservice` containers failing because `harbor-core` is not available, but I do not see any logs from the `harbor-core` container. Has it been initialized? Did it fail to start?
