### ISSUE TITLE
ReportServer 4.5.0.6089

### ISSUE THREAD

**Issue by edu-de** [bitnami/containers#34909]
### Name and Version

reportserver-community

### What is the problem this feature will solve?

Hi,

we released the new ReportServer version 4.5.0-6089 in http://www2.datenwerke.net/bitnami/releases/ce/. Just wanted to make sure you got the binaries and there is no issue with them ?

Regards,
Eduardo

### What is the feature you are proposing to solve the problem?

New Release

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by edu-de** [comment]
Hi carrodher,

thanks for your answer. Pls note we also released a new 4.6.0 version today, available here: http://www2.datenwerke.net/bitnami/releases/ce/

Pls let me know if you have any issues releasing these versions.

Regards,
Eduardo

**Comment by edu-de** [comment]
Pls note we had to release a further version: 4.6.1

available here: http://www2.datenwerke.net/bitnami/releases/ce/

Pls let me know if you have any issues releasing these versions.

Regards,
Eduardo

**Comment by carrodher** [comment]
Hi! The new version was just released, see https://github.com/bitnami/containers/pull/35108
