### ISSUE TITLE
[bitnami/kafka] Documetation update

### ISSUE THREAD

**Issue by Sbennett99** [bitnami/containers#34974]
### Name and Version

bitnami/kafka:latest

### What is the problem this feature will solve?

Allow for most up to date ENV config variables to be known, they are currently inconsistently documented.

### What is the feature you are proposing to solve the problem?

Updated documentation to include most recent var names and to include vars necessary for  SSL/mTLS.

### What alternatives have you considered?

using something else because of the inconsistent and poor documentation of this image for docker use

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by OneCricketeer** [comment]
What specific issues are you having with `KAFKA_CFG_` + upper-case + `replace('.', '_')` the [broker configs](https://kafka.apache.org/documentation/#brokerconfigs)?
