### ISSUE TITLE
[bitnami/postgresql-ha] when standby restarted, it cloning data from primary everytime. and it takes long.

### ISSUE THREAD

**Issue by choieujin** [bitnami/containers#34986]
### Name and Version

bitnami/postgresql-repmgr:12.14

### What architecture are you using?

None

### What steps will reproduce the bug?

1. k8s version : v1.24.13-eks-0a21954
   image:  postgresql-repmgr:12.14 
2. replicas: 2
3. when standby pod restarted, it always cloning data from primary using pg_basebackup.
    if data size is big (500Gi), then standby restart takes over 1hour.
    i think this takes too long and this way make pressure to primary.
    when i use postgresql-repmgr:11.9 image, standby doesn't cloning data every restart. 
    in 11.9 image, when standby restarted, it check data directory and if it is empty then cloning from primary.
   I wonder why logic changed like this. 
   and also Is there other way or settings to do not cloning data, when standby restared?

### What is the expected behavior?

Standby restart immediately and start replication

### What do you see instead?

every restart, cloning data from primary 

```
postgresql-repmgr 01:32:20.07 DEBUG ==> Schema repmgr.repmgr exists!
postgresql-repmgr 01:32:20.07 INFO  ==> Rejoining node...
postgresql-repmgr 01:32:20.08 INFO  ==> Cloning data from primary node...
postgresql-repmgr 01:32:20.08 INFO  ==> /opt/bitnami/repmgr/bin/repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf -h v12-postgresql-primary-0.v12-postgresql-headless.zdb-uz.svc.cluster.local -p 5432 -U repmgr -d repmgr -D /bitnami/postgresql/data standby clone --fast-checkpoint --force
WARNING: following problems with command line parameters detected:
  -D/--pgdata will be ignored if a repmgr configuration file is provided
NOTICE: destination directory "/bitnami/postgresql/data" provided
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: data checksums are not enabled and "wal_log_hints" is "off"
DETAIL: pg_rewind requires "wal_log_hints" to be enabled
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
NOTICE: starting backup (using pg_basebackup)...
NOTICE: standby clone (using pg_basebackup) complete
NOTICE: you can now start your PostgreSQL server
HINT: for example: pg_ctl -D /bitnami/postgresql/data start
HINT: after starting the server, you need to re-register this standby with "repmgr standby register --force" to update the existing node record
[REPMGR EVENT] Node id: 1001; Event type: standby_clone; Success [1|0]: 1; Time: 2023-05-24 11:56:25.550464+09;  Details: cloned from host "v12-postgresql-primary-0.v12-postgresql-headless.zdb-uz.svc.cluster.local", port 5432; backup method: pg_basebackup; --force: Y
Looking for the script: /opt/bitnami/repmgr/events/execs/standby_clone.sh
[REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_clone.sh' found. Skipping...
postgresql-repmgr 02:56:25.57 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 02:56:25.58 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
```

**Comment by javsalgar** [comment]
Hi,

We have an experimental flag to use pg_rewind. This would make the process a bit more efficient but it is still experimental. 

https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/12/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh#L660

**Comment by choieujin** [comment]
I tried pg_rewind with flag 'REPMGR_USE_PGREWIND'='yes', but pg_rewind failed. so, it doing pg_basebackup again.
Pod log said  '"/bitnami/postgresql/data/global/pg_control" for reading: No such file or directory'.

```
postgresql-repmgr 05:14:59.90 INFO  ==> Rejoining node...
postgresql-repmgr 05:14:59.90 INFO  ==> Using pg_rewind to primary node...
postgresql-repmgr 05:14:59.90 INFO  ==> Running pg_rewind data to primary node...
pg_rewind: fatal: could not open file "/bitnami/postgresql/data/global/pg_control" for reading: No such file or directory
postgresql-repmgr 05:14:59.91 WARN  ==> pg_rewind failed, resorting to data cloning
postgresql-repmgr 05:14:59.92 INFO  ==> Cloning data from primary node...
WARNING: following problems with command line parameters detected:
  -D/--pgdata will be ignored if a repmgr configuration file is provided
NOTICE: destination directory "/bitnami/postgresql/data" provided
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
NOTICE: starting backup (using pg_basebackup)...

```


```
# in primary
postgres=# show wal_log_hints;
 wal_log_hints
---------------
 on
(1 row)
```

How can i solve it?

**Comment by luhhujbb** [comment]
@choieujin I'm currently fighting with this issue, if it's the first time you applied 'REPMGR_USE_PGREWIND'='yes', maybe the current state of wal does not allow pg_rewind to run directly after the setting is applied.

**Comment by jotamartos** [comment]
Hi @choieujin,

Could you please take a look at @luhhujbb's comment? I also think that your current state doesn't allow you use that env var. You can try with a fresh deployment to check if that works as expected. 

>in 11.9 image, when standby restarted, it check data directory and if it is empty then cloning from primary.

Regarding this, I can see we didn't modify the logic that clones the data from the primary node lately. 

https://github.com/bitnami/containers/blame/main/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh#L605

As you may know, you can always contribute to improve the solution by following the [contributing guide](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md). Our team will review any change you suggest and the whole community will benefit from your changes.

**Comment by snoby** [comment]
When @luhhujbb  says current stat of wal does not allow pg_rewind to run, is that because the database isn't being shutdown correctly?  I am referencing this closed PR
https://github.com/bitnami/containers/pull/23928



These are the messages I get when i restart the replica only.  I'm not running in k8s this is pure docker
```
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: postgresql-repmgr 13:22:44.06 INFO  ==> Running pg_rewind data to primary node...
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: pg_rewind: executing "/opt/bitnami/postgresql/bin/postgres" for target server to complete crash recovery
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: postgres: could not access the server configuration file "/bitnami/postgresql/data/postgresql.conf": No such file or directory
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: pg_rewind: error: postgres single-user mode in target cluster failed
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: pg_rewind: detail: Command was: /opt/bitnami/postgresql/bin/postgres --single -F -D /bitnami/postgresql/data template1 < /dev/null
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: postgresql-repmgr 13:22:44.10 WARN  ==> pg_rewind failed, resorting to data cloning
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: postgresql-repmgr 13:22:44.10 INFO  ==> Cloning data from primary node...
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: WARNING: following problems with command line parameters detected:
Jun 10 13:22:44 alpha-pg-1 postgres[198292]:   -D/--pgdata will be ignored if a repmgr configuration file is provided
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: NOTICE: destination directory "/bitnami/postgresql/data" provided
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: NOTICE: checking for available walsenders on the source node (2 required)
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: NOTICE: checking replication connections can be made to the source server (2 required)
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: WARNING: directory "/bitnami/postgresql/data" exists but is not empty
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
Jun 10 13:22:44 alpha-pg-1 postgres[198292]: NOTICE: starting backup (using pg_basebackup)...
Jun 10 13:22:49 alpha-pg-1 postgres[198292]: NOTICE: standby clone (using pg_basebackup) complete                                                                                                       Jun 10 13:22:49 alpha-pg-1 postgres[198292]: NOTICE: you can now start your PostgreSQL server

```


On the restart of the replica i can't reclone 130GB.

**Comment by snoby** [comment]
i built a new image with the pull request and indeed pg_rewind does stop the replica from doing a complete clone on restart.  Note that if the replica doesn't start from a good state it does a full clone with pgbackup.

**Comment by luhhujbb** [comment]
> When @luhhujbb says current stat of wal does not allow pg_rewind to run, is that because the database isn't being shutdown correctly? I am referencing this closed PR #23928
> 

No, it's because pg_rewind needs `wal_log_hints` to be activated. This setting need postgresql to be restarted before being applied. So If you apply `REPMGR_USE_PGREWIND='true'` on a non fresh installation, current wal doesn't include hint bits and pg_rewind will probably fail.

**Comment by snoby** [comment]
> 

I have a lab setup here all the configs setup with ansible so everything is exactly the same.  
```
   --env REPMGR_USE_PGREWIND=true \
   ```
   is set in the systemd service that starts the container and  in my ansible file that applies changes to the postgresql.conf 
   ```
     - {From: '^#wal_log_hints.+$',To: 'wal_log_hints = on'}
     ```
     i have wal_log_hints set to on.
     
     I restarted the test system several times and it wasn't until i built the docker image with the reference PR did pg_rewind start to function and the system not falling back to pgbackup and cloning the entire db.

**Comment by jotamartos** [comment]
Thanks for the information @snoby. You can add your thoughts to the PR you linked above and confirm everything works as expected. In the meantime, you can build your own docker image applying those changes until a new version is released with them.

**Comment by snoby** [comment]
I've been running this in production for a couple of weeks now with no problems.
