### ISSUE TITLE
[bitnami/mongodb] Is there a way to specify the name of a database to be used for creation scripts?

### ISSUE THREAD

**Issue by guoard** [bitnami/containers#35096]
### Name and Version

bitnami/mongodb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Is there any environment variable to allows us to specify the name of a database to be used for creation scripts in `/docker-entrypoint-initdb.d/*.js`? just like `mongo` image which has `MONGO_INITDB_DATABASE` env.

### What do you see instead?

I set these environment variables but didn't work:

- `MONGODB_DATABASE`
- `MONGODB_EXTRA_DATABASES`

I also saw this [line](https://github.com/bitnami/containers/blob/main/bitnami/mongodb/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh#L1545) but couldn't find out a way to pass database name to `mongodb_execute_print_output` function.

**Comment by guoard** [comment]
Thank you for your time and answer.

> would you like to submit a PR improving libmongodb.sh?

Yes, I open a pull request. please let me know if you have any questions or concerns.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look

**Comment by guoard** [comment]
In case the pull request didn't merge or if you prefer to declare the database initialization in a different way, you have the following options:

1) Declare it at the beginning of your `*.js[gz]` file using the following code:

```js
use database_name
```

2) Modify the `db` variable to your desired custom name using the following code:

```js
db = db.getSiblingDB("database_name")
```
