### ISSUE TITLE
[bitnami/prestashop] Unable to copye file on persistent volume

### ISSUE THREAD

**Issue by Castanea43** [bitnami/containers#35288]
### Name and Version

bitnami/prestashop 8.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi, in first step i make a docker-compose.yml file with : https://pastebin.com/qtxRJNgi
in terminal i run with : docker-compose up (in the same directory than file)

the volume :
```
    volumes:
      - /srv/dev-disk-by-uuid-0155d4af-58f3-41e9-b4f0-ec30c11667ec/shop/data:/bitnami/prestashop
```
is an ssd disk with some container and minecraft server.
dir sql, contain the database in the same disk - no problem with mariadb :
```
volumes:
      - /srv/dev-disk-by-uuid-0155d4af-58f3-41e9-b4f0-ec30c11667ec/shop/sql:/var/lib/mysql
```
How to resolv this ?
Thanks in advance.

### What do you see instead?

what i see : https://pastebin.com/GpDyvY9p

**Comment by javsalgar** [comment]
Hi,

It seems that you have a permission issue with the volume. The container is non-root so the mounted volume should be writable by others.
