### ISSUE TITLE
Unable to add custom SPI in Keycloak

### ISSUE THREAD

**Issue by raspreet-vunet** [bitnami/containers#35330]
### Name and Version

bitnami/keycloak:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Clone custom SPI (https://github.com/mths0x5f/keycloak-proxied-hostname-provider)
2. Run `mvn clean install` to create JAR file
3. Create `standalone.xml` as [mentioned in SPI repo's readme](https://github.com/mths0x5f/keycloak-proxied-hostname-provider)
4. Add volume mapping for jar file in `/opt/bitnami/keycloak/standalone/deployments/`
5. Add volume mapping for `standalone.xml` in `/opt/bitnami/keycloak/standalone/configuration`

### What is the expected behavior?

I expect to see the custom SPI as the default hostname provider

### What do you see instead?

The default hostname provider

![Hostname provider setting in keycloak](https://github.com/bitnami/containers/assets/113003295/225fb108-8cb0-4bdb-a3ad-0ffc47c0358f)

### Additional information

Contents of `standalone.xml` (which should ideally replace the default hostname provided in keycloak`

```xml
<spi name="hostname">
  <default-provider>proxied</default-provider>
</spi>
```

**Note:** I have no experience with Java and followed the steps as mentioned by ChatGPT and SO answers.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami keycloak container image or Helm chart but about how the application or environment is being used/configured. In the same way, it's a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
