### ISSUE TITLE
[bitnami/etcd] 3.5, "--env ALLOW_NONE_AUTHENTICATION=yes" not work by now !

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#35461]
### Name and Version

bitnami/etcd:3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I had defined "--env ALLOW_NONE_AUTHENTICATION=yes".
But when I connect etcd:3.5 without user/password, It prompt `Could not perform operation. Error: Error: 3 INVALID_ARGUMENT: etcdserver: user name is empty`.

But It's work a few days ago, before I pull the newest etcd image.

### What do you see instead?

```
Error: etcdserver: user name is empty
{"level":"warn","ts":"2023-05-28T04:03:48.316+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00039aa80/etcd:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
```

**Comment by migruiz4** [comment]
Hi @ldcsaa,

Could you please provide more details about your issue?
It would be helpful if you could provide steps about how to reproduce your issue:
- What command were you executing when you got this error?
- Was it in a fresh install? If not, could you please provide information about the previous deployment?
- Are you able to reproduce this issue consistently by deploying again? 

I tried to reproduce this using the current latest and [this docker compose](https://github.com/bitnami/containers/blob/main/bitnami/etcd/docker-compose.yml), but I wasn't able to reproduce it:

```
I have no name!@69000ff73fb8:/opt/bitnami/etcd$ etcdctl put test -- "Hello World"
OK
I have no name!@69000ff73fb8:/opt/bitnami/etcd$ etcdctl get test                 
test
Hello World
```

**Comment by ldcsaa** [comment]
> Hi @ldcsaa,
> 
> Could you please provide more details about your issue? It would be helpful if you could provide steps about how to reproduce your issue:
> 
> * What command were you executing when you got this error?
> * Was it in a fresh install? If not, could you please provide information about the previous deployment?
> * Are you able to reproduce this issue consistently by deploying again?
> 
> I tried to reproduce this using the current latest and [this docker compose](https://github.com/bitnami/containers/blob/main/bitnami/etcd/docker-compose.yml), but I wasn't able to reproduce it:
> 
> ```
> I have no name!@69000ff73fb8:/opt/bitnami/etcd$ etcdctl put test -- "Hello World"
> OK
> I have no name!@69000ff73fb8:/opt/bitnami/etcd$ etcdctl get test                 
> test
> Hello World
> ```

My case is set these env variables at the same time:
```
ENV ALLOW_NONE_AUTHENTICATION=yes
ENV ETCD_ROOT_PASSWORD=123456
```
When I remove the `ETCD_ROOT_PASSWORD` env, It's work, otherwise not work.
```
docker run -d --name Etcd-server \
    --network app-tier \
    --publish 2379:2379 \
    --publish 2380:2380 \
    --env ALLOW_NONE_AUTHENTICATION=yes \
    --env ETCD_ROOT_PASSWORD=123456 \
    --env ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379 \
    bitnami/etcd:latest
```

**Comment by ldcsaa** [comment]
And, if not set `ETCD_ROOT_PASSWORD` env, the `healthchek.sh` would fail:
```
I have no name!@df5b65d19ce6:/opt/bitnami/etcd$ /opt/bitnami/scripts/etcd/healthcheck.sh
{"level":"warn","ts":"2023-06-01T00:08:14.724965+0800","logger":"client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00014c000/etcd:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
etcd:2379 is unhealthy: failed to commit proposal: etcdserver: user name is empty
Error: unhealthy cluster
etcd 00:08:14.73 ERROR ==> Unhealthy endpoint!

```
Because it would not set `--user` param:
https://github.com/bitnami/containers/blob/424bff846b2d18010795e08778f43a6a55b19251/bitnami/etcd/3.5/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh#LL285C1-L285C1
