### ISSUE TITLE
[bitnami/postgresql-repmgr] Clarification: is this open on all interfaces?

### ISSUE THREAD

**Issue by jcalfee** [bitnami/containers#35701]
### Name and Version

bitnami/postgresql-repmgr

### What is the problem this feature will solve?

Could you please clarify, is authentication open on all interfaces?  I have an internal docker network working, but a friend is trying to login to postgres via an open port.  Same setup, but he gets an authentication failure and I do not.  I don't see any references to 0.0.0.0 or anything about interfaces.  Thank you..

https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/README.md

### What is the feature you are proposing to solve the problem?

Connection error

**Comment by Hans-van-Velzen** [comment]
This is the error that shows up: error: `password authentication failed for user "postgres"`

**Comment by Hans-van-Velzen** [comment]
This is the docker-compose.yml file we are using
`version: '2'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:15
    #https://hub.docker.com/r/bitnami/postgresql-repmgr/
    #image: test
    ports:
      - 5432:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    networks:
    - private
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:15
    #image: test
    #ports:
    #  - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
    networks:
    - private
  graphql_engine:
    container_name: ${LOCAL_DOMAIN:-graphql.local}

    # https://github.com/hasura/graphql-engine/releases
    #image: hasura/graphql-engine:v2.7.0 # last version nsjs was tested

    # 2.10.0 HASURA_GRAPHQL_METADATA_DATABASE_EXTENSIONS_SCHEMA (probably needed for heroku)
    # 2.10.0 *_update_source API to update configuration of a connected database
    # 2.10.1 Accept HASURA_GRAPHQL_METADATA_DATABASE_EXTENSIONS_SCHEMA on hasura install
    # 2.10.2 security patch
    image: hasura/graphql-engine:v2.21.0

    # .local appears like a regular domain to the browser and its plugins
    #ports:
    #- "8080:8080"
    depends_on:
    - "pg-0"
    restart: unless-stopped
    environment:
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@pg-0:5432/postgres

      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@pg-0:5432/postgres

      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console

      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"

      ## settup authentication
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      # HASURA_GRAPHQL_JWT_SECRET: <json> see v2/hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html

      TIMESCALEDB_TELEMETRY: "off"
    networks:
    - private
    - public

networks:
  private:
    internal: true
  public:
    internal: false

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local`

**Comment by Hans-van-Velzen** [comment]
This is the docker-compose.yml file we are using
`version: '2'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:15
    #https://hub.docker.com/r/bitnami/postgresql-repmgr/
    #image: test
    ports:
      - 5432:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    networks:
    - private
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:15
    #image: test
    #ports:
    #  - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
    networks:
    - private


networks:
  private:
    internal: true
  public:
    internal: false

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local`

**Comment by gongomgra** [comment]
Hi @jcalfee, @Hans-van-Velzen,

According to the docker-compose docs linked below, setting the `internal: true` property for the `private` network will make it an externally isolated network. 

> By default, Compose implementations MUST provides external connectivity to networks. internal, when set to true, allows creating an externally isolated network.

https://docs.docker.com/compose/compose-file/06-networks/#internal

May you try to assign the replica you want to be externally accessible the `public` network as well (as in the `graphql_engine` service)?

**Comment by jcalfee** [comment]
Thank you so much, I apologize I did not see that.   @Hans-van-Velzen you probably want both pg-0 and pg-1 to have:

```yaml
    networks:
    - private
    - public
```

Let us know how it goes.

**Comment by jcalfee** [comment]
Hey, that worked.  Thanks a lot.
