### ISSUE TITLE
[bitnami/pgpool] Invalid config generated when & used in password

### ISSUE THREAD

**Issue by gerethd** [bitnami/containers#35704]
### Name and Version

bitnami/pgpool:4.4.2-debian-11-r34

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using the postgresql-ha helm chart set pgpool.passwords to contain a password with an '&' in it and deploy. Pgpool will fail to start due to invalid config. 

### What is the expected behavior?

i expect valid config specifically the line to look like

`sr_check_password = 'your_password_here_containing_ampersand'`

### What do you see instead?

the above mentioned line comes out 

`sr_check_password = 'your_password_sr_check_password = ''_here_containing_ampersand`

### Additional information

If i had to guess i'm assuming you're using sed to  insert passwords into the config file, and the & is a reserved character in that context.

**Comment by gerethd** [comment]
Not a critical issue per say but at the very least it would be helpful for the docs in both the helm chart and the container image in dockerhub be updated to reflect that this will happen or validation in one or the other to prevent the invalid config. Was not simple to debug on it's own as the only indication that anything was wrong was just that the config file is invalid.

**Comment by Mauraza** [comment]
Hi @gerethd,

We are open to a contribution! 
We are not using sed, you can check the code https://github.com/bitnami/containers/blob/main/bitnami/pgpool/4/debian-11/rootfs/opt/bitnami/scripts/libpgpool.sh

Did you test with the container?

**Comment by Mauraza** [comment]
Hi @gereth,

Could you share your values or some values to reproduce this issue?

**Comment by gerethd** [comment]
providing any password with an '&' reproduces the issue for me
