### ISSUE TITLE
Missing ARM64 images on public ECR

### ISSUE THREAD

**Issue by ben-wilson-peak** [bitnami/containers#35774]
### Name and Version

All

### What architecture are you using?

arm64

### What steps will reproduce the bug?

View https://gallery.ecr.aws/bitnami and confirm there are no arm64 images

### What is the expected behavior?

arm64 images to be available

### What do you see instead?

No arm64 images

### Additional information

I think it's all there 😆

**Comment by carrodher** [comment]
At this moment ARM images are only pushed to DockerHub, see https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html.

In the short term there are no plans to distribute ARM images to a different registry, but if this change at some point, we will announce and notify it.

**Comment by ben-wilson-peak** [comment]
> At this moment ARM images are only pushed to DockerHub, see https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html.
> 
> In the short term there are no plans to distribute ARM images to a different registry, but if this change at some point, we will announce and notify it.

Gotcha thanks for clarifying. I can't see any technical reason not to so I presume there's some kind of relationship for that.

**Comment by martavoi** [comment]
BUMP
@carrodher hi man, we've been using Bitnami images from within ECR for a while and appreciate build quality and support, however nowadays we seek for ARM64-based Grafana image and would greatly appreciate if you could add maintain ARM images in ECR also. I hope that wouldn't be complicated for you guys. Would appreciate your help.

**Comment by carrodher** [comment]
Thanks for using Bitnami containers. Unfortunately, we haven’t been able to give it higher priority in the context of other initiatives we are working on, because of that, for now, multi-arch images are only available in DockerHub.

We cannot give an estimate as to when it might be available at ECR Public Gallery
