### ISSUE TITLE
[bitnami/postgresql-repmgr] synchronous_standby_names is empty when POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS > 0

### ISSUE THREAD

**Issue by Laurianti** [bitnami/containers#35839]
### Name and Version

[bitnami/postgresql-repmgr:15.2.0-debian-11-r13](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-11/Dockerfile)

### What steps will reproduce the bug?

1. Install the [bitnami/postgres-ha](https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha) chart with `.Values.postgresql.syncReplication: true`.
2. Execute the PostgreSQL query `show synchronous_standby_names` to check the current value.

### What is the expected behavior?

The expected behavior is that when `.Values.postgresql.syncReplication` is set to true, which in turn sets `POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS`, the `synchronous_standby_names` variable should be properly configured with the appropriate value.

### What do you see instead?

Currently, `synchronous_standby_names` is empty.

### Additional information

I have analyzed the sequence of scripts executed in the [run.sh](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/postgresql-repmgr/run.sh) file and believe that it might be the cause of the problem.

Specifically, in the execution sequence, the `POSTGRESQL_CLUSTER_APP_NAME` variable appears to be used before it has been properly set.

This issue occurs in the [libpostgresql.sh](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh) file, but the `POSTGRESQL_CLUSTER_APP_NAME` is correctly set later on, in the [librepmgr.sh](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh) file.

In my opinion, simply reversing the execution order of the two scripts may not be enough because there could be a circular dependency between them. However, I would appreciate it if you could verify this.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Laurianti** [comment]
After further testing, I have concluded that this is not a bug, since librepmgr.sh, after modifying POSTGRESQL_CLUSTER_APP_NAME, calls postgresql_configure_synchronous_replication.
