### ISSUE TITLE
[bitnami/harbor] config set to a symlink instead of config folder.

### ISSUE THREAD

**Issue by scottmando2000** [bitnami/containers#3584]
### Name and Version

harbor-portal

### What steps will reproduce the bug?

Follow TL;DR directions in Harbor Portal README.

### What is the expected behavior?

Valid config directory.

### What do you see instead?

The `config` directory, from the second command, is currently a symlink for `2/debian-11/config` and any attempt to run `docker-compose up -d` results in the following error.

`Error response from daemon: error while creating mount source path '/home/scott/docker/harbor/config/registry': mkdir /home/scott/docker/harbor/config: file exists`

**Comment by scottmando2000** [comment]
I have tested PR #4313 and the configs were available, but there is another issue which might need another issue to be made.

With a fresh install, `core` is crashing, which is causing `jobservice` and `nginx` to also crash. Tested on Ubuntu 22.04.

**Comment by aoterolorenzo** [comment]
HI @scottmando2000. Thank you for take the time to testing and sorry for the waiting! I've just merge the PR now.

Regarding to your comment, seems indeed that could be another issue. Feel free to retry and report it if you feel the need. We are more than glad to help you. Thank you!
