### ISSUE TITLE
[bitnami/dotnet-sdk] IPv6 disabled in dotnet-sdk container

### ISSUE THREAD

**Issue by Maxyeah** [bitnami/containers#35994]
### Name and Version

bitnami/dotnet-sdk

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Pull container with .net6 sdk: 

- bitnami/dotnet-sdk:6

run command: 
```
 sysctl -a 2>/dev/null | grep disable_ipv6
```

### What is the expected behavior?

```
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```

### What do you see instead?

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

### Additional information

Why is IPv6 disabled in this docker? How can we activate it via DockerFile or script?

**Comment by javsalgar** [comment]
Hi,

Please note that you are changing Kernel settings, which are not related to the container or the building process. That would depend on the host you are using to run the container and the settings that are allowed to be changed. You may need to use privileged containers for example.

**Comment by Maxyeah** [comment]
Hello @javsalgar, 
thanks for your reply. My host system does support IPv6 

net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.docker0.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.veth6bbd024.disable_ipv6 = 0
net.ipv6.conf.wlan0.disable_ipv6 = 0

Why is it disabled inside the container?

**Comment by Maxyeah** [comment]
Hi, 
maybe there is a misunderstanding. I do not change these settings. I only use the command to see if IPv6 is enabled. 
I just want to know why it is disabled, and if there is a way to enable it. Or maybe there is a container version with IPv6 enabled i have not found yet. 
Thanks Max

**Comment by javsalgar** [comment]
Hi,

Which is the OS you are using as host system? Note that the container is not responsible for that, it is the contianer engine or the underlying host. You can change it inside the container if you run the container as `--privileged`

**Comment by Maxyeah** [comment]
Hi, 
I use a linux host. But i found it. Had to enable Ipv6 in docker daemon.

Thanks for your help.
