### ISSUE TITLE
[bitnami/percona-xtrabackup] Differences in behavior between percona image and bitnami image

### ISSUE THREAD

**Issue by martin-neumann-gurus** [bitnami/containers#35991]
### Name and Version

bitnami/percona-xtrabackup:8.0.32-26

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install a MySQL server using the image  perconalab/percona-server:8.0.33-25.1-multi
Run the following command with your parameter adapted to your instance:
```
docker run --rm -it -v /var/lib/docker/volumes/mysql_data/_data:/var/lib/mysql -v /root/backup/xtrabackup_backupfiles bitnami/percona-xtrabackup:8.0.32-26 xtrabackup --backup --no-defaults --compress=lz4 --host=mysql --user=root --password=secret --target-dir="/xtrabackup_backupfiles/monthly_2023-05"
```

### What is the expected behavior?

If I run the same command with the percona/percona-xtrabackup image it does the backup without any problems.

### What do you see instead?

Using the bitnami image above, i get the following output:
```
2023-05-31T12:45:52.413847-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --host=mysql --user=root --password=* --target-dir=/xtrabackup_backupfiles/monthly_2023-05
2023-05-31T12:45:52.414013-00:00 0 [ERROR] [MY-011825] [Xtrabackup] unknown argument: ‘xtrabackup’
```

### Additional information

This is totally strange since xtrabackup is the command and not an argument. I assume that the bitnami image should behave the same as the official percona image. Please clarify or verify if something is not working right in your image.

**Comment by javsalgar** [comment]
Hi,

In our containers, `xtrabackup` is the entrypoint

https://github.com/bitnami/containers/blob/main/bitnami/percona-xtrabackup/8/debian-11/Dockerfile#L46

Could you try removing `xtrabackup` from the command?

**Comment by martin-neumann-gurus** [comment]
Thanks for clarifying. Would be good if you include that in your documentation, because it is difficult to guess that kind of differences.

Now after making this change I get this error:
Now after correcting that I get the following output:
2023-05-31T14:15:41.996331-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --compress=lz4 --host=localhost --user=root --password=* --incremental-basedir=/xtrabackup_backupfiles/monthly_2023-05 --target-dir=/xtrabackup_backupfiles/daily_2023-05-31
xtrabackup version 8.0.32-26 based on MySQL server 8.0.32 Linux (x86_64) (revision id: 34cf2908)
Can’t locate English.pm in @INC (you may need to install the English module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at - line 3.
BEGIN failed–compilation aborted at - line 3.
2023-05-31T14:15:42.008561-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: localhost, user: root, password: set, port: not set, socket: not set
2023-05-31T14:15:42.008861-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Failed to connect to MySQL server: Can’t connect to local MySQL server through socket ‘/tmp/mysql.sock’ (2)

Same command with the percona image is working fine.

**Comment by aoterolorenzo** [comment]
Hi @martin-neumann-gurus ,

Seems our container uses the xtrabackup command as main entrypoint:

ENTRYPOINT [ "xtrabackup" ]

Could you try...?

`docker run --rm -it -v /var/lib/docker/volumes/mysql_data/_data:/var/lib/mysql -v /root/backup/xtrabackup_backupfiles bitnami/percona-xtrabackup:8.0.32-26 --backup --no-defaults --compress=lz4 --host=mysql --user=root --password=secret --target-dir="/xtrabackup_backupfiles/monthly_2023-05"`
