### ISSUE TITLE
Adding TLS config fails if data directory has been initialized

### ISSUE THREAD

**Issue by aushacker** [bitnami/containers#36613]
### Name and Version

bitnami/openldap:2.6.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is a reactivation of #27792.

Am deploying the openldap:2.6.4 container to OpenShift 4.12 using a StatefuSet to maintain persistent data.

The initial deployment only configured a persistent volume, TLS was ignored. This configuration worked and was able to connect to LDAP using curl.

As a second step I attempted to add TLS configuration to the StatefulSet using the Docker Hub example "Securing OpenLDAP traffic" (LDAP_ENABLE_TLS, LDAP_TLS_CERT_FILE etc.). This resulted in failure. I was not able to connect using either curl or openssl s_client. Debugging indicated the client sending an ssl hello which resulted in the openldap server closing the socket.

I eventually worked out that the reason TLS configuration was not happening was because of the way the ldap_initialize function (in libopenldap.sh) is coded. TLS configuration will occur only once when the data directory is empty. Once data exists TLS configuration will not occur.

Because I had carried data over from my unsecured deployment the TLS settings were always going to be ignored.

### What is the expected behavior?

TLS settings should be evaluated on every container restart.

### What do you see instead?

TLS settings are only evaluated on the first container startup, after that they are ignored.

### Additional information

Are there any other settings that are processed only once but should be processed even if data is present?

**Comment by mindthecap** [comment]
I had the same problem, but I didn't debug it as vigorously as I didn't care about the data and I recreated the system.
As stated, there is a problem when going from non-tls to TLS.
