### ISSUE TITLE
Git is Needed

### ISSUE THREAD

**Issue by mattholy** [bitnami/containers#36735]
### Name and Version

bitnami/airflow-worker:2

### What is the problem this feature will solve?

Container will be killed due to installing python packages using `pip -r requirement.txt` when there is a git line in `requirement.txt`(Such as `git+https://git.mysite.com/pkg/pkg.git#egg=pkg`)
The log :
```
2023-06-07T10:18:55.744674785Z Collecting pkg (from -r /bitnami/python/requirements.txt (line 4))
2023-06-07T10:18:55.745167318Z   Cloning https://git.mysite.com/pkg/pkg.git to /tmp/pip-install-enku8nht/pkg_7897df0dfc17407fb24e56682f51e66d
2023-06-07T10:18:55.748837723Z   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
2023-06-07T10:18:55.749188137Z ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

### What is the feature you are proposing to solve the problem?

Just have git installed.

**Comment by andresbono** [comment]
When do you find this issue? Is it initializing the container or when you do some specific action with your deployment?

**Comment by mattholy** [comment]
> When do you find this issue? Is it initializing the container or when you do some specific action with your deployment?

initializing

**Comment by OneCricketeer** [comment]
Sounds like you are using some customized requirements.txt?

What issues are you running into when using your own image?  E.g.

```
FROM bitnami/airflow
RUN apt-get upgrade && apt-get install -y git
```

**Comment by mattholy** [comment]
> Sounds like you are using some customized requirements.txt?
> 
> 
> 
> What issues are you running into when using your own image?  E.g.
> 
> 
> 
> ```
> 
> FROM bitnami/airflow-worker:2
> 
> RUN apt-get upgrade && apt-get install -y git
> 
> ```
> 
> 
> 
> Related https://github.com/bitnami/containers/issues/36816#issuecomment-1583008017

nothing really, im using a custom image already.
i just thought it might be a very common need,so the issue it is.

**Comment by andresbono** [comment]
Thank you for the clarifications. As @OneCricketeer pointed, the same reasoning than in https://github.com/bitnami/containers/issues/36816#issuecomment-1583008017 applies here.

The recommended approach is that you install any extra required packages as part of your customization as you are already doing.

**Comment by mattholy** [comment]
Yep
