### ISSUE TITLE
[bitnami/keycloak] admin user

### ISSUE THREAD

**Issue by igitcode** [bitnami/containers#36886]
### Name and Version

bitnami/keycloak:21.1.1-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm deploying via HELM chart version 15.1.3.

I'm setting the env vars:
```
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=xyz
```
### What is the expected behavior?

The admin user called `admin` is created

### What do you see instead?

Upon trying to login I get error message:
`type=LOGIN_ERROR, realmId= clientId=security-admin-console, userId=null, ipAddress=127.0.0.1, error=user_not_found, auth_method=openid-connect, redirect_uri=http://localhost:8080/admin/master/console/, code_id=, username=admin`

I also see this message in the logs at startup:
`2023-06-08 17:22:48,583 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists`

Upon querying the `user_entity` table, I only see default user `user`.
<img width="1885" alt="Screenshot 2023-06-08 at 1 00 09 PM" src="https://github.com/bitnami/containers/assets/18669319/bf6c129c-f782-4063-8d56-4b81c2c65d20">

I first deployed with default admin user `user`, then updated my configs to use name `admin`.

from the keycloak pod, I can see both the environment vars are set properly
<img width="489" alt="Screenshot 2023-06-08 at 1 02 58 PM" src="https://github.com/bitnami/containers/assets/18669319/bff1aed1-e698-45ed-a81a-9025cb1c3bc7">

### Additional information

I'm using an external postgresql database. I know this is working as expected because all the keycloak tables got created on first deployment.

I have previously deployed image `quay.io/keycloak/keycloak:21.0.1` to kubernetes setting the same ENV vars and it worked as expected. This deployment was using local database instead of external.

I'm using `kubectl port-forward` to access on localhost.

Trying to add a new admin user called `user1`, I get same error:
`Failed to add user 'user1' to realm 'master': user with username exists`

**Comment by igitcode** [comment]
I ended up deleting my database, re-creating the database, and then redeploying keycloak and everything works. 

I think what happened is on my initial deploy I didn't realize the HELM chart was using `user` as default admin username, and of course the default password is an empty string. Then a redeploy of keycloak with the the ENV vars to override admin user and password doesn't work. 

Not sure if this is a known issue, but I think it would be beneficial to supply some text for the default admin `user` so you don't get locked out of the app.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
