### ISSUE TITLE
curl/wget is missing from postgresql container

### ISSUE THREAD

**Issue by Poundex** [bitnami/containers#37025]
### Name and Version

bitnami/postgresql:15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Attempt to use curl/wget in postgresql container (to diagnose connectivity issues to other pods, to run a custom user script, to kill the Istio sidecar in a Job, etc etc etc)
2. See that these, as well as some other core tools, are missing from the container

### What is the expected behavior?

A small collection of essential tools should be available in every image to make sure custom scripts can run and diagnostics can occour without having to set up, build, publish, maintain forever a custom image

### What do you see instead?

Core utilities missing from images

**Comment by OneCricketeer** [comment]
Related comment https://github.com/bitnami/containers/issues/36816#issuecomment-1583008017
