### ISSUE TITLE
Rabbit not working when securityContext: readOnlyRootFilesystem: true is set

### ISSUE THREAD

**Issue by SnoozeFreddo** [bitnami/containers#37057]
### Name and Version

rabbitmq:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbi
spec:

  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:

      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      securityContext:
        fsGroup: 1001
```
Then add `securityContext: readOnlyRootFilesystem: true` to the container

### What is the expected behavior?

I would expect that write permission isn't necessary.

### What do you see instead?
```
rabbitmq 22:22:14.22 rabbitmq 22:22:14.22 Welcome to the Bitnami rabbitmq containerrabbitmq 22:22:14.23 Subscribe to project updates by watching https://github.com/bitnami/containersrabbitmq 22:22:14.23 Submit issues and feature requests at https://github.com/bitnami/containers/issuesrabbitmq 22:22:14.23 rabbitmq 22:22:14.23 INFO  ==> ** Starting RabbitMQ setup **rabbitmq 22:22:14.27 INFO 

 ==> Validating settings in RABBITMQ_* env vars..rabbitmq 22:22:14.30 INFO  

==> Initializing RabbitMQ.../opt/bitnami/scripts/librabbitmq.sh: line 402: /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf: Read-only file system
```

**Comment by carrodher** [comment]
Why are you changing the `fsGroup` to 1001? Please note non-root containers are based on the fact that the random user (1001 by default) belongs to the root group (GID 0)

**Comment by SnoozeFreddo** [comment]
I am doing it because of the instructions in [dockerhub/bitnami/rabbitmq](https://hub.docker.com/r/bitnami/rabbitmq/)

"NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001."

**Comment by carrodher** [comment]
Helm chart works with the following security context by default:
```yaml
podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
```
