### ISSUE TITLE
Didn't installed Symfony framework

### ISSUE THREAD

**Issue by cleargoal** [bitnami/containers#37095]
### Name and Version

bitnami/symfony latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I just launched commands as described in the doc:

> mkdir ~/myapp && cd ~/myapp
> curl -LO https://raw.githubusercontent.com/bitnami/containers/main/bitnami/symfony/docker-compose.yml

with another app name.
After that, I changed the port for MariaDB to 3315 as I use many running containers at the same time.
Then

> docker-compose up

Containers had been installed normally, but the framework didn't.

### What is the expected behavior?

Expected that framework has to be installed too, as described in the doc:

> The above command creates a container service for Symfony development and bootstraps a new Symfony application, named myapp in working directory.

at the page https://hub.docker.com/r/bitnami/symfony/

### What do you see instead?

I see just an empty folder 'my-project' in the folder I created by the 1st command 'mkdir'

### Additional information

As I'm a newbie in Symfony, I don't understand - what to do.
Do I need to search for framework code somewhere on the disc?
Or, do I need to install the framework manually, using any manual?
If I need installing, what folder install the code to, so with the purpose that the container can see the framework code?

**Comment by carrodher** [comment]
The above command creates a container service for Symfony development and bootstraps a new Symfony application, with the provided name in a working directory. You can use your favorite IDE for developing the application.

After the built-in PHP application server has been started, visit http://localhost:8000 in your favorite web browser and you'll be greeted by the Symfony welcome page.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

**Comment by cleargoal** [comment]
> The above command creates a container service for Symfony development and bootstraps a new Symfony application, with the provided name in a working directory. You can use your favorite IDE for developing the application.

A new Symfony application didn't create, I'm sorry. That is my reason to ask - what to do.

> 
> After the built-in PHP application server has been started, visit http://localhost:8000 in your favorite web browser and you'll be greeted by the Symfony welcome page.
> 
> For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

**Comment by joancafom** [comment]
Hi @cleargoal 

You are right, following the instructions does not lead to an straightforward installation of Symfony. I think this is due to a missing mention to the `$SYMFONY_PROJECT_SKELETON` env var (the project to be created if the folder does not already contain one). Could you please try performing the following modification to the default`docker-compose.yml` file?

```diff
version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/symfony:6.2
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=bn_myapp
      - SYMFONY_DATABASE_NAME=bitnami_myapp
+     - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
```

**Comment by cleargoal** [comment]
> ```diff
> - SYMFONY_PROJECT_SKELETON=symfony/skeleton
> ```

Thank you!

Now it's installed well.

**Comment by cleargoal** [comment]
> Hi @cleargoal
> 
> You are right, following the instructions does not lead to an straightforward installation of Symfony. I think this is due to a missing mention to the `$SYMFONY_PROJECT_SKELETON` env var (the project to be created if the folder does not already contain one). Could you please try performing the following modification to the default`docker-compose.yml` file?
> 
> ```diff
> version: '2'
> 
> services:
>   mariadb:
>     image: docker.io/bitnami/mariadb:10.11
>     environment:
>       # ALLOW_EMPTY_PASSWORD is recommended only for development.
>       - ALLOW_EMPTY_PASSWORD=yes
>       - MARIADB_USER=bn_myapp
>       - MARIADB_DATABASE=bitnami_myapp
>   myapp:
>     image: docker.io/bitnami/symfony:6.2
>     ports:
>       - '8000:8000'
>     environment:
>       # ALLOW_EMPTY_PASSWORD is recommended only for development.
>       - ALLOW_EMPTY_PASSWORD=yes
>       - SYMFONY_DATABASE_HOST=mariadb
>       - SYMFONY_DATABASE_PORT_NUMBER=3306
>       - SYMFONY_DATABASE_USER=bn_myapp
>       - SYMFONY_DATABASE_NAME=bitnami_myapp
> +     - SYMFONY_PROJECT_SKELETON=symfony/skeleton
>     volumes:
>       - './my-project:/app'
>     depends_on:
>       - mariadb
> ```

One more question, what do I have to change for using another port?
For example 8021

**Comment by joancafom** [comment]
> One more question, what do I have to change for using another port?
For example 8021

You can change Symfony's port number using the `SYMFONY_PORT_NUMBER` env var, which defaults to `8000`

**Comment by cleargoal** [comment]
> You can change Symfony's port number using the SYMFONY_PORT_NUMBER env var, which defaults to 8000

I did it and restart containers but that change has no effect.

Help me, please to understand what else I need to do.

**Comment by joancafom** [comment]
As mentioned, the `SYMFONY_PORT_NUMBER` changes the default port number. Of course, you would also need to change the port mapping in your `docker-compose.yml` file to match the value accordingly in order for it to work locally:

```diff
version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/symfony:6.2
    ports:
-     - '8000:8000'
+     - '9876:9876'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=bn_myapp
      - SYMFONY_DATABASE_NAME=bitnami_myapp
+     - SYMFONY_PROJECT_SKELETON=symfony/skeleton
+     - SYMFONY_PORT_NUMBER=9876   
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
```

```console
$ curl --silent localhost:9876 | head
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive,nosnippet,noodp,notranslate,noimageindex" />
    <title>Welcome to Symfony!</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>👋</text></svg>">
    <style>
                                body { background: hsla(288, 20%, 95%, 1); color: hsla(288, 20%, 45%, 1); display: flex; font: 16px/1.5 sans-serif; justify-content: center; margin: 0; }
        h1, h2 { line-height: 1.2; margin: 0 0 .5em; }
```

**Comment by cleargoal** [comment]
It works.
**Thank you very much!**
