### ISSUE TITLE
Couldn't start using offical docker-compose.yml

### ISSUE THREAD

**Issue by minesunny** [bitnami/containers#37336]
### Name and Version

bitnami/kafka:3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/kafka/docker-compose.yml > docker-compose.yml
docker-compose up -d
```
### What do you see instead?
```
kafka 02:58:59.87
kafka 02:58:59.87 Welcome to the Bitnami kafka container
kafka 02:58:59.87 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 02:58:59.88 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 02:58:59.88
kafka 02:58:59.88 INFO  ==> ** Starting Kafka setup **
kafka 02:58:59.96 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 02:58:59.97 INFO  ==> Initializing Kafka...
kafka 02:58:59.98 INFO  ==> No injected configuration files found, creating default config files
kafka 02:59:00.17 INFO  ==> Initializing KRaft...
kafka 02:59:00.17 INFO  ==> Formatting storage directories to add metadata...
```
### Additional information

the kafka container didn't start, and there wasn't error.

**Comment by minesunny** [comment]
It couldn't start on first machine,I tried another machine successfully started.
<img width="1954" alt="image" src="https://github.com/bitnami/containers/assets/98507458/dc20bfbf-f88d-49c1-b297-2480f65f317c">

<img width="1955" alt="image" src="https://github.com/bitnami/containers/assets/98507458/7742d045-4445-4347-9241-084cd77d0eaa">

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Kafka container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by OneCricketeer** [comment]
> how the application or environment is being used/configured.

Shouldn't the provided compose file / readme in the repo be runnable without extra configuration?

**Comment by carrodher** [comment]
>Shouldn't the provided compose file / readme in the repo be runnable without extra configuration?

It should work out of the box without any change, in fact, this docker-compose is tested by our CI/CD. Did you find any issues? Could you provide more details?

**Comment by OneCricketeer** [comment]
In any case, this seems to be a close duplicate of #26882
