### ISSUE TITLE
mkdir: cannot create directory /bitnami/rabbitmq/mnesia: File exists

### ISSUE THREAD

**Issue by ledroide** [bitnami/containers#37448]
### Name and Version

bitnami/rabbitmq:3.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using bitnami/rabbitmq:3.12 in a StatefulSet with mount path /bitnami/rabbitmq to persistent volume. The first pod crashes here :

```
rabbitmq-0 rabbitmq rabbitmq 08:56:47.10 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq-0 rabbitmq + /opt/bitnami/scripts/rabbitmq/setup.sh
rabbitmq-0 rabbitmq rabbitmq 08:56:47.11 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq-0 rabbitmq rabbitmq 08:56:47.13 INFO  ==> Initializing RabbitMQ...
rabbitmq-0 rabbitmq rabbitmq 08:56:47.15 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq-0 rabbitmq mkdir: cannot create directory '/bitnami/rabbitmq/mnesia': File exists
```
```
NAME                        READY   AGE
statefulset.apps/rabbitmq   0/3     9m46s
NAME                                             READY   STATUS             RESTARTS          AGE
pod/rabbitmq-0                                   0/1     CrashLoopBackOff   6 (3m21s ago)    9m35s
```

I found this is the main argument script [/opt/bitnami/scripts/librabbitmq.sh](https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.10/debian-11/rootfs/opt/bitnami/scripts/librabbitmq.sh#L816)

```bash
debug "Ensuring expected directories/files exist..."
for dir in "$RABBITMQ_DATA_DIR" "$RABBITMQ_LIB_DIR" "$RABBITMQ_HOME_DIR"; do
    ensure_dir_exists "$dir"
    am_i_root && chown -R "$RABBITMQ_DAEMON_USER:$RABBITMQ_DAEMON_GROUP" "$dir"
done
```

Digging further, I found that _ensure_dir_exists_ function is in [/opt/bitnami/scripts/libfs.sh](https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.10/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh#L45)

```bash
ensure_dir_exists() {
    local dir="${1:?directory is missing}"
    local owner_user="${2:-}"
    local owner_group="${3:-}"

    mkdir -p "${dir}"
    if [[ -n $owner_user ]]; then
        owned_by "$dir" "$owner_user" "$owner_group"
    fi
}
```

So here is the issue : there is no test that the directory does not exist. If the directory exists, mkdir returns _2_, the script exits, and the container crashes (and kubelet restarts the container continuously).

I have simply added a test [at line 45](https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.10/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh#L45), this way :

```bash
    [ -d "${dir}" ] || mkdir -p "${dir}"
```

This simple test fixes the issue.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ledroide** [comment]
Confirmed fixed with the latest build of container image docker.io/bitnami/rabbitmq:3.12. Thanks !

**Comment by dafinguzman** [comment]
@leebroom-ba Same here, with image docker.io/bitnami/rabbitmq:3.12.12-debian-11-r7

**Comment by kfir-marx-hcl** [comment]
same here

registry: docker.io
repository: bitnami/rabbitmq
tag: 3.12.13

**Comment by gray19950103** [comment]
> same here
> 
> ```yaml
> registry: docker.io
> repository: bitnami/rabbitmq
> tag: 3.12.13
> ```

use `helm install --namespace=rabbitmq rabbitmq --set persistence.existingClaim=**** --set auth.username=**** --set auth.password=**** oci://registry-1.docker.io/bitnamicharts/rabbitmq` without  `-f values.yaml` works fine on me.

**Comment by ikimpriv** [comment]
@leebroom-ba @kfir-marx-hcl @gray19950103 
most probably you have the same issue I had - obsolete values.yaml. Particularly persistence.mountPath (the new default is /opt/bitnami/rabbitmq/.rabbitmq/mnesia)

**Comment by PedemonteGiacomo** [comment]
> @leebroom-ba @kfir-marx-hcl @gray19950103 most probably you have the same issue I had - obsolete values.yaml. Particularly `persistence.mountPath` (the new default is `/opt/bitnami/rabbitmq/.rabbitmq/mnesia`)

This worked for me
