### ISSUE TITLE
[bitnami/pgbouncer] Mount a custom configuration without validating settings in PGBOUNCER_* env vars 

### ISSUE THREAD

**Issue by cobolbaby** [bitnami/containers#37447]
### Name and Version

bitnami/pgbouncer:1.19.1

### What is the problem this feature will solve?

```console
$ docker run --name pgbouncer -e PGBOUNCER_EXTRA_FLAGS="--verbose" bitnami/pgbouncer:1.19.1
pgbouncer 09:13:52.76 
pgbouncer 09:13:52.76 Welcome to the Bitnami pgbouncer container
pgbouncer 09:13:52.76 Subscribe to project updates by watching https://github.com/bitnami/containers
pgbouncer 09:13:52.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgbouncer 09:13:52.76 
pgbouncer 09:13:52.82 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 09:13:52.87 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 09:13:52.87 ERROR ==> POSTGRESQL_PASSWORD must be set
```

### What is the feature you are proposing to solve the problem?

When the pgbouncer.ini file exists, the startup script will not override it and skip verifying environment variables.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
