### ISSUE TITLE
ODOO_ADDONS_DIR should be added to odoo_env_vars

### ISSUE THREAD

**Issue by 7thkey** [bitnami/containers#37494]
### Name and Version

bitnami/odoo:16

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Trying to define ODOO_ADDONS_DIR in .env does not work.

bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo-env.sh
It is a simple fix, just adding ODOO_ADDONS_DIR into the odoo_env_vars line 24

### What is the expected behavior?

ODOO_ADDONS_DIR should define alternative folders for your addons or custom addons.

### What do you see instead?

You can't change the default static path:  /opt/bitnami/odoo/addons

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the issue. Would you like to submit a PR with the fix?
