### ISSUE TITLE
[bitnami/wordpress] customize ImageMagick security policy

### ISSUE THREAD

**Issue by mchobbel** [bitnami/containers#37544]
### Name and Version

bitnami/wordpress-16.1.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```

<?php
  $fn = '/bitnami/wordpress/wp-content/uploads/test.pdf';
try{
  $img = new Imagick($fn);
  $x = $img->identifyImage(true);
  print_r($x);
}catch(ImagickException  $e){
    print_r($e);
}

```
### What is the expected behavior?

We expect to see information about the PDF document.

### What do you see instead?

Exception: Attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421

### Additional information

I already tried with values.yaml
```
extraEnvVars:
    name: MAGICK_CONFIGURE_PATH
       value: /bitnami/wordpress/etc/imagemagick
```

And then provide custom policy.xml in
   /bitnami/wordpress/etc/imagemagick/

and with policy.xml =
```
<policymap>
  <policy domain="coder" rights="read" pattern="PDF" />
</policymap>

```
Unfortunately this doesnt make a difference, we still see the same exception.

**Comment by mchobbel** [comment]
Hi there. The idea of MAGICK_CONFIGURE_PATH is to provide your own xml to override  /etc/ImageMagick-6/policy.xml. This seemed a good idea since the non-root bitnami image doesn't allow changing /etc/ImageMagick-6/policy.xml in the first place.  see https://stackoverflow.com/questions/52703123/override-default-imagemagick-policy-xml

**Comment by javsalgar** [comment]
Hi,

Did you try mounting your own xml in the `/etc/ImageMagick-6/policy.xml` location directly?

**Comment by mchobbel** [comment]
Well, yes, that is a good solution to have my modified policy.xml. Now I'm running into another issue: the ghostscript package is not in the image.  see https://www.php.net/manual/en/imagick.requirements.php

Is there a way to solve that ? Is it possible to include ghostscript ?

**Comment by javsalgar** [comment]
Hi,

In this sense, you could try creating a fork that includes ghostscript in the `install_packages` section. We try to be conservative with the included system packages as it increses the size and the attack vector of the containers.
