### ISSUE TITLE
[Redmine] ARM support

### ISSUE THREAD

**Issue by MTRNord** [bitnami/containers#37586]
### Name and Version

bitnami/redmine:*

### What is the problem this feature will solve?

Currently, redmine has no arm support and due to how bitnami only privdes open core but not open source Dockerfiles it cannot be manually built.

### What is the feature you are proposing to solve the problem?

Adding ARM packages for redmine which is the only component in the image missing arm packages.

**Comment by carrodher** [comment]
Unfortunately due to some technical issues when building Redmine in ARM, this architecture is not supported for this application at this moment. We have an internal task to review unsupported apps
