### ISSUE TITLE
[bitnami/keycloak] Bitnami scripts flip keycloak defaults on their head and provide no way to override

### ISSUE THREAD

**Issue by jack1902** [bitnami/containers#37758]
### Name and Version

bitnami/keycloak

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy the bitnami keycloak chart
2. observe that `kc_hostname_strict` is set to `false`

### What is the expected behavior?

`kc_hostname_strict` to be set to `true` per the keycloak documentation which states that it should be `true` by default in production. 

https://www.keycloak.org/server/hostname

script in question: https://github.com/bitnami/containers/blob/e7cdf92210c83dd38728f5df055c5b784e4bfcbd/bitnami/keycloak/21/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L191

![Screenshot 2023-06-15 at 18 03 53](https://github.com/bitnami/containers/assets/39212456/dfe72c36-f3f3-4342-803e-49c10a0da2bf)

### What do you see instead?

`kc_hostname_strict` is disabled

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the issue. Would you like to add an environment variable that allows configuring this option? This would speed up the fixing of this issue. If not, we will work on it but we cannot guarantee an ETA.
