### ISSUE TITLE
bitnami/suitecrm wrong version

### ISSUE THREAD

**Issue by Querens** [bitnami/containers#37813]
### Name and Version

bitnami/suitecrm:8.3.0-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

docker pull bitnami/suitecrm:8.3.0-debian-11-r8
docker exec -it <container_name> bash
/# cat bitnami/suitecrm/VERSION 

### What is the expected behavior?

8.3.0

### What do you see instead?

8.2.4

**Comment by carrodher** [comment]
I'm not able to reproduce the mentioned issue, I'm just running
```console
$ docker run bitnami/suitecrm:8.3.0-debian-11-r8 cat /opt/bitnami/suitecrm/VERSION
suitecrm 17:45:42.34
suitecrm 17:45:42.34 Welcome to the Bitnami suitecrm container
suitecrm 17:45:42.34 Subscribe to project updates by watching https://github.com/bitnami/containers
suitecrm 17:45:42.34 Submit issues and feature requests at https://github.com/bitnami/containers/issues
suitecrm 17:45:42.34

8.3.0
```
and the returned version is the expected one.

Please note you may be mounting the `bitnami/suitecrm/` directory as a volume so it's reusing the `VERSION` file from a previous installation of SuiteCRM 8.2.4

**Comment by Querens** [comment]
@carrodher yeah, you're right. I haven't noticed that it works like that, my apologies and thank you!
