### ISSUE TITLE
Discourse - Secondary/subsequent container instantiation fails - not happy with existing DB

### ISSUE THREAD

**Issue by lejeczek** [bitnami/containers#37911]
### Name and Version

none

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed the first container successfully then I destroyed/removed the container, having db in pgsql (outside of the container) intact I attempted what I deem as common & trivial - I re-deployed the same container anew but this time container kept restarting with logs stuck at:
```
discourse 15:52:17.79 INFO ==> Populating database
discourse 15:52:24.18 INFO ==> Creating admin user
```
If I drop db & give the container a new, empty one, deployment will succeed.

This reproduces every time. I'm on RHEL/Centos thus 'podman' is being used.

That is not supposed to be failing, right? That would defeat pretty much the whole purpose of a container.
many thanks, L.

### What is the expected behavior?

re-installing/instantiating the "same" container with existing DBS should work

### What do you see instead?

but it fails at least with/for pgSQL.

**Comment by carrodher** [comment]
Could you please add the `BITNAMI_DEBUG=true` env. variable to the discourse container? In this way, we have more info in the logs about the different steps executed during the initialization.

**Comment by lejeczek** [comment]
`...
admin.name = "UserName LastName"
admin.active = true
admin.save
errors = admin.errors.full_messages
unless errors.empty?
  puts errors.join("
")
  exit 1
end
admin.grant_admin!
admin.activate
Password is too short (minimum is 15 characters)
`
So... is it 'deploy VS re-deploy' issue? Former is ok/allowed but not the latter? -> DISCOURSE_PASSWORD
I think there also might be issues with chars such as - # - in env vars.
Having such char in DISCOURSE_DATABASE_PASSWORD regardless of how I quoted it, deployment failed.

**Comment by lejeczek** [comment]
But don't let 'lenght' distract, there probably is more issues:
`
")
  exit 1
end
admin.grant_admin!
admin.activate
Password is the same as your current password.
`

This really should be easily reproducible I believe. I'm not doing anything "special" I'd think - only pgSQL & Redis are external to container, rest is "vanilla-default"

**Comment by lejeczek** [comment]
Hi guys.
I might have to apologise - I am lazy and most of the time try to take the easy way out - as I've been sourcing my ENVs from a file and there seem to be some weirdness, at least in my view, as to how bash/shell (in my case) expands its VARs.
So.. I had
`-e DISCOURSE_SKIP_BOOTSTRAP=yes`
first, in series of:
`-e VAR=THIS \`
and it's either something special about '-e' or expanding those by shell, but that first `-e` was not there, thus DISCOURSE_SKIP_BOOTSTRAP was ignored. I ended up with this - being lazy - working: `$(cat <(echo "$_GLOBAL"))`

So what I originally described as a potential issue was just my bad, but...
If I might ask - as I'm discovering it all while this is my first foray into Discourse/Bitnami - re-instantiating a container on a, say... "standby" node where both pgSQL & Redis are read-only replicas, still fails, even with `DISCOURSE_SKIP_BOOTSTRAP=yes`
Why? What is happening there?
Lastly - do you have a way to deploy such a "standby" Discourse?

many thanks, L.

**Comment by dgomezleon** [comment]
Hi @lejeczek ,

Thanks for letting us know.

About the scenario you mention, I'm not sure if I fully understand it. As you can see in the [README.md](https://github.com/bitnami/containers/blob/main/bitnami/discourse/README.md):

```
In case the database already contains data from a previous Discourse installation, you need to set the variable `DISCOURSE_SKIP_BOOTSTRAP` to `yes`. Otherwise, the container would execute the installation wizard and could\
 modify the existing data in the database. Note that, when setting `DISCOURSE_SKIP_BOOTSTRAP` to `yes`, values for environment variables such as `DISCOURSE_USERNAME`, `DISCOURSE_PASSWORD` or `DISCOURSE_EMAIL` will be igno\
red.
```

Using `DISCOURSE_SKIP_BOOTSTRAP` should work in order to an existing database.

**Comment by lejeczek** [comment]
I'm talking about a setup - which I presumed must be common - where a secondary container is a "stand-by" node, which most of the time means that slave replicas - as I explained in my last message - both pgSQL & Redis, are read-only replicas.
On such as stand-by node, container deployment even with DISCOURSE_SKIP_BOOTSTRAP, fails.
Perhaps it's rather on how Discourse works, but if there is somethink you/Bitnami guys could do something at container's end, in order to make such deployment possible - I'd imagine many would be even more happy & appreciate that.

**Comment by lejeczek** [comment]
But yes, the issue I originally reported here I'm thinking can be closed as not-an-issue.

**Comment by dgomezleon** [comment]
Hi @lejeczek ,

Sorry for the delay (PTO time). 

I consider this more related to how Discourse works. In case you consider any specific feature to be added for the container, feel free to open a new case or even contribute with a PR.

Closing this issue as you suggested.
