### ISSUE TITLE
Install Kong OIDC plugin inside kong

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/containers#38091]
### Name and Version

bitnami/kong:3.3.0

### What is the problem this feature will solve?

I wanna install kong oidc plugin inside bitnami/kong, 
this is base image, But I don't know how to add it??

```Dockerfile
FROM kong:2.8.1-alpine

LABEL description="Alpine + Kong  + kong-oidc plugin"

USER root
RUN apk update && apk add curl git gcc musl-dev
RUN luarocks install luaossl OPENSSL_DIR=/usr/local/kong CRYPTO_DIR=/usr/local/kong
RUN luarocks install --pin lua-resty-jwt
RUN luarocks install kong-oidc

USER kong
```

### What is the feature you are proposing to solve the problem?

I will help us new plugin oidc for kong

**Comment by carrodher** [comment]
Please note the base image you are using is not the Bitnami one, you should ask the maintainers of that image.
