### ISSUE TITLE
pull zookeeper image from dockerhub failed

### ISSUE THREAD

**Issue by lsshaw** [bitnami/containers#38214]
### Name and Version

bitnami/zookeeper:3.8.1-debian-11-r46

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1.user command to pull zk image:
docker  pull bitnami/zookeeper:3.8.1-debian-11-r46 --platform linux/arm64

2.then show the result:
![image](https://github.com/bitnami/containers/assets/118887593/4db7101b-d09a-464f-93df-290f4794387c)

3.my daemon.json config is 
```json
{
          "registry-mirrors": ["https://f9dk003m.mirror.aliyuncs.com"],
          "insecure-registries" : ["hub.aosccs.com.cn:8888","edgehub.acedge.cn:8888"],
          "experimental": true
}
``` 

### What is the expected behavior?

pull images success

### What do you see instead?

```shell
error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/87/8713bc47044a99926e7f975463faee077591af6bc0fb3f70b082200dc817d34d/data?verify=1687228681-3AszD9nYuxzbhFZme6V5FnKztIo%3D": dial tcp 104.18.123.25:443: i/o timeout
```

**Comment by carrodher** [comment]
It seems it's not an issue with the Bitnami container but with the Docker CLI or something like that.

The image is present for ARM and AMD, see
- https://hub.docker.com/layers/bitnami/zookeeper/3.8.1-debian-11-r46/images/sha256-a07f7f8f57bd7d0a972f63b3a55804c547d5838a9974d5990fec9534822397f3?context=explore
- https://hub.docker.com/layers/bitnami/zookeeper/3.8.1-debian-11-r46/images/sha256-bfcb5f608e22bddc23224e259103c69e639080ae90d00b7450ec1ec607d5b561?context=explore
