### ISSUE TITLE
Kafka 3.5.0 release

### ISSUE THREAD

**Issue by OneCricketeer** [bitnami/containers#38626]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Does the automation bot track all versions, or only patch releases?

Kafka 3.5.0 is now available, but I don't see any PRs for it yet - https://kafka.apache.org/downloads.html

### What is the feature you are proposing to solve the problem?

Newest versions available

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by corico44** [comment]
@OneCricketeer The new version 3.5 of kafka is now available #38934. Thank you very much for reporting this case!
