### ISSUE TITLE
[bitnami/redmine] Enable https

### ISSUE THREAD

**Issue by nuclear0077** [bitnami/containers#38722]
### Name and Version

5.0.0-debian-10-r0 release

### What architecture are you using?

arm64

### What steps will reproduce the bug?

run image https://github.com/bitnami/containers/blob/main/bitnami/redmine/docker-compose.yml

### What do you see instead?

I did not find information on how to start support https

### Additional information

Good afternoon, tell me please, I can’t find information on how to start https support and install ssl certificates

**Comment by nuclear0077** [comment]
waiting for an answer

**Comment by CeliaGMqrz** [comment]
Hi @nuclear0077 

First, sorry for the delay.

Thanks for reporting this issue.  Unfortunately, this feature is not currently available. As a workaround, you can use a reverse proxy or a web server (Nginx or Apache) to configure it.

**Comment by nuclear0077** [comment]
okay, thanks
