### ISSUE TITLE
[bitnami/gitea] setup does not have ssh-keygen for configuring access keys

### ISSUE THREAD

**Issue by christhomas** [bitnami/containers#38803]
### Name and Version

bitnami/gitea

### What architecture are you using?

amd64

### What steps will reproduce the bug?

From your local machine, run the following:
- This does not work: `docker run -it bitnami/gitea ssh-keygen`
- This works: `docker run -it gitea/gitea ssh-keygen`

ssh-keygen is important when you need to setup access keys in your profile, so without this tool, gitea seems to fail and I think that should work

### What is the expected behavior?

That I can run ssh-keygen from the console, as given in the above instructions. 

### What do you see instead?

In gitea, when adding my public key, I have the following error
```
Cannot verify your SSH key: SSHKeyGenParsePublicKey: fail to parse public key: exec: "ssh-keygen": executable file not found in $PATH -
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
