### ISSUE TITLE
[bitnami/drupal] Please help upgrade drupal to version 10.1.0

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/containers#38806]
### Name and Version

bitnami/drupal

### What is the problem this feature will solve?

please upgrade to version 10.1.0 from 10.0.9.

### What is the feature you are proposing to solve the problem?

for security and upgrades.

**Comment by ddfiberglass** [comment]
I have tried in the kubernetes pod by running: composer upgrade. It works. 

Another thing I want to mention is there any better way to upgrade drupal modules such as version 3.* to 4.*? As the module files are persistent volume (PV), I use "helm upgrade" won't upgrade the modules version.

**Comment by javsalgar** [comment]
Hi,

In the case of a major version we cannot guarantee an automatic upgrade of the modules. Our advice is to launch the chart with `diagnosticMode.enabled=true`, enter the container and manually adapt the modules.

**Comment by ddfiberglass** [comment]
> Hi,
> 
> In the case of a major version we cannot guarantee an automatic upgrade of the modules. Our advice is to launch the chart with `diagnosticMode.enabled=true`, enter the container and manually adapt the modules.

Thanks for your information. I have downloaded the module files and upgraded.
