### ISSUE TITLE
moodle: Cannot connect to MySQL server after docker images restart

### ISSUE THREAD

**Issue by alfmannew** [bitnami/containers#3900]
### Name and Version

bitnami/moodle:latest bitnami/moodle:4.0.2

### What steps will reproduce the bug?

https://github.com/bitnami/bitnami-docker-moodle/issues/125
I have same issue with semicolon character.

### What do you see instead?

https://github.com/bitnami/bitnami-docker-moodle/issues/125
I have same issue with semicolon character.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by Klemich** [comment]
Hi, 

I have a similar problem. Not exactly the same. 
MariaDB is running perfectly, but bitnami/moodle refuses to connect to any db. I have no more info than this. Can you help ?

**Comment by alfmannew** [comment]
> Hi,
> 
> I have a similar problem. Not exactly the same. MariaDB is running perfectly, but bitnami/moodle refuses to connect to any db. I have no more info than this. Can you help ?

Hi,
Check from another container like Adminer, phpMyAdmin, ... (same network)
- network (name resolving)
- connection to db
- username\password

**Comment by Klemich** [comment]
Hi Alfmannew, 

Phpmyadmin works fine. Connected to the same network, but I don't see any of the db (neither mariaDB nor moodle)
