### ISSUE TITLE
Unable to find airflow-2.6.2-0-linux-arm64-debian-11 component

### ISSUE THREAD

**Issue by DmitryPaulouski** [bitnami/containers#39105]
### Name and Version

[bitnami/airflow] 2.6.2-debian-11-r3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm trying to rebuild docker image with python 3.10. So I'm just building docker file downloaded from the repo. 
I changed python version from python-3.9.17-1 to python-3.10.12-1. 
I've checked it and there is no such file - https://downloads.bitnami.com/files/stacksmith/airflow-2.6.2-0-linux-arm64-debian-11.tar.gz. 

### What is the expected behavior?

Docker build completed succesfully.

### What do you see instead?

When I'm running **docker build -t -airflow-bitnami .** I see the following error:
<img width="878" alt="image" src="https://github.com/bitnami/containers/assets/124574459/54255175-455d-4772-a52d-bd4cdd06ef38">

### Additional information

There is amd64 based image - https://downloads.bitnami.com/files/stacksmith/airflow-2.6.2-0-linux-amd64-debian-11.tar.gz 
And there is no ARM one.

**Comment by javsalgar** [comment]
Hi,

Right now we don't have support for ARM for the airflow container. As soon as we have more news we will notify the community.
