### ISSUE TITLE
Support rdkafka2 plugin in Fluentd image

### ISSUE THREAD

**Issue by yurymalash** [bitnami/containers#39156]
### Name and Version

bitnami/fluentd:1.16.1-debian-11-r21

### What is the problem this feature will solve?

I deploy `bitnami/fluentd:1.16.1-debian-11-r21` image to Azure AKS as a part of the Bitnami Helm release https://github.com/bitnami/charts/tree/main/bitnami/fluentd

Then, I write Kubernetes logs to Kafka (Azure EventHub) using Kafka output plugins from https://github.com/fluent/fluent-plugin-kafka:
- https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka_buffered.rb
- https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka2.rb
Both use the deprecated library https://github.com/zendesk/ruby-kafka (see the Deprecation notice at the top of README).

**Could you please support a newer Kafka output plugin?** https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_rdkafka.rb which uses actively developing library
https://github.com/appsignal/rdkafka-ruby

Currently, Fluentd configuration
```
      <match **>
        @type rdkafka2
```   
fails on error:
```
<internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rdkafka (LoadError)
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.19.0/lib/fluent/plugin/out_rdkafka2.rb:6:in `<top (required)>'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/registry.rb:103:in `block in search'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `search'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/registry.rb:44:in `lookup'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/plugin.rb:169:in `new_impl'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/plugin.rb:114:in `new_output'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/agent.rb:130:in `add_match'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:149:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/supervisor.rb:571:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.16.1/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `<main>'_
```

### What is the feature you are proposing to solve the problem?

The reason for the above failure is that the gem `rdkafka-ruby` is not installed in fluentd docker image.
To verify, login into the image and see installed gems with the below command:
```
I have no name!@fluentd-8swjx:/opt/bitnami/fluentd$ ls -l /opt/bitnami/fluentd/gems/
```
I guess, you can enable `rdkafka-ruby` gem to be installed by adding the following environmental variables to fluentd docker image.
```
USE_RDKAFKA
RDKAFKA_VERSION_MIN_RANGE
RDKAFKA_VERSION_MAX_RANGE
```
Please see https://github.com/fluent/fluent-plugin-kafka/blob/master/Gemfile

**Comment by corico44** [comment]
@yurymalash Thank you so much for opening this issue. I understand what you mention. If you want, you can open a PR with the mentioned changes and we will review it as soon as possible!
