### ISSUE TITLE
In the kubernetes-1.24+ environment, when using helm3 to deploy components such as bitnami/zookeeper kafka

### ISSUE THREAD

**Issue by opencmit2** [bitnami/containers#39280]
### Name and Version

bitnami/zookeeper

### What is the problem this feature will solve?

In the kubernetes-1.24+ environment, when using helm3 to deploy components such as bitnami/zookeeper kafka, the deployment is successful, but the process does not start. The same method is no problem when deployed below kubernetes-1.24. I don't want to install docker to support docker.io based images, can this be resolved。
The error message is as follows:
![image](https://github.com/bitnami/containers/assets/112474703/9e66b2f3-765a-4457-bc27-67785c03d0c4)

The image version used is as follows：
![image](https://github.com/bitnami/containers/assets/112474703/4868f354-da7c-46ae-862e-285b92040b61)

### What is the feature you are proposing to solve the problem?

In the kubernetes-1.24+ environment, when using helm3 to deploy components such as bitnami/zookeeper kafka, the deployment is successful, but the process does not start. The same method is no problem when deployed below kubernetes-1.24. I don't want to install docker to support docker.io based images, can this be resolved。

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami zookeeper container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
