### ISSUE TITLE
Grafana 10 support

### ISSUE THREAD

**Issue by aramperes** [bitnami/containers#39292]
### Name and Version

bitnami/grafana:10.0.1

### What is the problem this feature will solve?

This repository only has support for Grafana 9.

### What is the feature you are proposing to solve the problem?

Please add support for Grafana 10.

### What alternatives have you considered?

Forking it myself.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by carrodher** [comment]
Thanks for creating this issue, finally Grafana 10 was released some days ago, see https://github.com/bitnami/containers/pull/39894
