### ISSUE TITLE
[bitnami/postgresql] show initdb script errors

### ISSUE THREAD

**Issue by jcpunk** [bitnami/containers#39295]
### Name and Version

bitnami/postgresql 15.3.0-debian-11-r17

### What is the problem this feature will solve?

Difficulty isolating if a deployment script is running or has typos

### What is the feature you are proposing to solve the problem?

Have the `libpostgresql.sh` spit out an error message on the script/scripts that fail to run correctly.

### What alternatives have you considered?

Writing my own wrappers around your wrappers.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR adding the feature?

**Comment by jcpunk** [comment]
This is still something I'm interested in.

**Comment by jcpunk** [comment]
I'm not sure I'll have time to work in this within the next month or so...

**Comment by juan131** [comment]
Thank you, we understand it might not be the best time for you to contribute.

Let's keep the issue opened in case any other user volunteers to submit a solution.
