### ISSUE TITLE
[Discourse] Running locally on 127.0.0.1 getting "blocked:csp" errors in browser

### ISSUE THREAD

**Issue by hiramegl** [bitnami/containers#39433]
### Describe your issue as much as you can

Hi,

I hope this is not a silly question. I've installed Discourse with "docker-compose" and instead of using "www.example.com" I'm using "127.0.0.1" as HOST. All 4 containers seem to start fine and I can navigate to "http://localhost" in my browser. All resource files load correctly (*.css, *.png) but for all *.js files I get a "(blocked:csp)" error. The webpage gets stucked in the loading animation.

I wonder how do I do in order to get rid of this "(blocked:csp)" error. Is it something in the "docker-compose.yml" file that I need to change? Or something that I need to configure inside the Discord container?

I'm interested to evaluate Discord locally first, before installing it in a production environment. But cannot manage to run it locally.

Thanks for your help in advance!

Best regards,

/Hiram

**Comment by gongomgra** [comment]
Hi @hiramegl, @cngirwa,

Using port 8080 instead of 80 should not represent any problem. However, Discourse requires accessing using a domain. Did you run `docker compose down -v` to also remove previous volumes after updating the `docker-compose.yml` file?

**Comment by cngirwa** [comment]
Hi @gongomgra 
I tried that and re-run it with no success. Will try hosting it, maybe it will work there. 
Thanks for the help.
