### ISSUE TITLE
[bitnami/mongodb] permit running container as non-root user/group

### ISSUE THREAD

**Issue by jcpunk** [bitnami/containers#39465]
### Name and Version

bitnami/mongodb mongodb:6.0.6-debian-11-r13

### What is the problem this feature will solve?

Security best practices suggest running containers as non-root user/group.  Currently the mongodb config is owned by root:root with a mode of 0640.

### What is the feature you are proposing to solve the problem?

Add a mongodb group to /etc/group and chgrp the config to that gid.  Then update the helm chart to use that group id by default.

### What alternatives have you considered?

building my own container

**Comment by carrodher** [comment]
Bitnami containers are non-root by default, you can find more info about this topic in different blog posts such as
- [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
- [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
- [Bitnami's Best Practices for Securing and Hardening Container Images](https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/)

**Comment by jcpunk** [comment]
In uncovered this in https://github.com/bitnami/charts/pull/17236 where an attempt to set a non-root uid/gid as the default runs into a permission denied error.

**Comment by carrodher** [comment]
In summary and using a vague explanation we can say that the _user_ used in all the Bitnami container images is 1001 by default although it can be any other random UID. This is something required for some k8s cluster technologies like OpenShift where a random UID is assigned when deploying the Helm chart.
In order to be able to operate in any directory without knowing beforehand the UID that will be assigned, the group by default is _root_ (GID=0) and any random user belongs to that _root_ group.

**Comment by gongomgra** [comment]
Hi @jcpunk,

Just a quick note to let you know that we released a new revision of our MongoDB images tagged as `5.0.20-debian-11-r5` and `6.0.9-debian-11-r5` that allows running the MongoDB images as `root` user, which creates a new unprivileged user `mongo` that ends up running the MongoDB server.

```
$ cat docker-compose.yml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    user: root
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local

$ docker-compose up -d
$ docker exec -it -u root d80fd503e137 bash
root@d80fd503e137:/# cat /etc/passwd | grep mongo
mongo:x:1000:1000::/home/mongo:/bin/sh

root@d80fd503e137:/# ps aux | grep -i mongo
mongo          1  3.0  0.3 2599000 126080 ?      Ssl  07:54   0:01 /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf
```

Hope it helps!

**Comment by BenAigan** [comment]
I have this issue when running in Azure as I am not allowed to have containers run as root , when I use the bitnami charts in debug mode and run the startup it fails as the config file is root permissioned.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by BenAigan** [comment]
In my azure environment I cannot get past the location of the keyfile since
the init file /opt/bitnami/scripts/libmongodb.sh is always looking for the
keyfile in the conf directory even though the config in the helm charts
puts this file into /tmp/keyfile.

I put the helm charts into debug mode and can log in and run the entry
point script once I have created the keyfile which works.

**Comment by BenAigan** [comment]
Managed to get past this area by creating key manually and initialising database, now only problem is the security context in the initcontainers on the tls creation.

**Comment by BenAigan** [comment]
I have not progressed any further on this yet but will be back to this issue in a week

**Comment by BenAigan** [comment]
This is my failure on deployment when using tls=true and autoGenerated=true.  In my firm environment, everything locked down tight.

`Events:

  Type     Reason        Age                From                    Message

  ----     ------        ----               ----                    -------

  Warning  FailedCreate  5s (x11 over 10s)  statefulset-controller  create Pod bigid-mongodb-0 in StatefulSet bigid-mongodb failed error: admission webhook "[validation.gatekeeper.sh](http://validation.gatekeeper.sh/)" denied the request: [psp-allowed-users-groups] Container generate-tls-certs is attempting to run without a required securityContext/runAsGroup. Allowed runAsGroup: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}

[psp-allowed-users-groups] Container generate-tls-certs is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0

[psp-seccomp] Seccomp profile 'not configured' is not allowed for container 'generate-tls-certs'. Found at: no explicit profile found. Allowed profiles: {"RuntimeDefault", "docker/default", "runtime/default"}`

**Comment by BenAigan** [comment]
To get the mongo charts to work I had to copy in the init container security context as it was missing, can this be added to the helm charts?

**Comment by javsalgar** [comment]
Hi!

Thanks for the input! Would you like to submit a PR adding that missing context?

**Comment by BenAigan** [comment]
I have been refused permissions to commit and changes to a public repo based off the debugging inside my firm.
