### ISSUE TITLE
[Elastic Search Curator] <Moved to archived image>

### ISSUE THREAD

**Issue by PeterThomasAwen** [bitnami/containers#39796]
### Describe your issue as much as you can

Apologies if this is the wrong place to raise this. 

Recently we see that elastic search curator images have been moved to https://hub.docker.com/r/bitnami/elasticsearch-curator-archived
Are there any plans to reintroduce a http://docker.io/bitnami/elasticsearch-curator repository or is this being deprecated more generally, are their other images/tools which we should be using for this purpose going forward?

Thanks

**Comment by carrodher** [comment]
elasticsearch-curator was deprecated and, according to our retention policy, it will be kept without restriction but in a repo with the `-archived` suffix it is clear to users that they're using a deprecated container image, see https://github.com/bitnami/containers#retention-policy
