### ISSUE TITLE
[bitnami/keycloak] Support healthcheck for helm-charts

### ISSUE THREAD

**Issue by kamontat** [bitnami/containers#39799]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Currently there are no way to enabled health check easy without add additional command argument.
It would be nicer if we can enabled health check using command-line (similar to enabling metrics).

Health check: https://www.keycloak.org/server/health

### What is the feature you are proposing to solve the problem?

Add environment variable to enabled health check  (similar to enabling metrics).

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the engineering team but we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR?

**Comment by dalbani** [comment]
Is #40893 what you had in mind, @kamontat?

**Comment by kamontat** [comment]
> Is #40893 what you had in mind, @kamontat?

Yes, indeed.
