### ISSUE TITLE
[bitnami/kafka] authorizer.class.name

### ISSUE THREAD

**Issue by wqbill** [bitnami/containers#39844]
### Name and Version

bitnami/kafka:latest

### What is the problem this feature will solve?

Need a env to set up authorizer.class.name.

### What is the feature you are proposing to solve the problem?

Need a env to set up authorizer.class.name.

**Comment by javsalgar** [comment]
Hi,

Did you try using the `KAFKA_CFG_*` env vars? Something like `KAFKA_CFG_AUTHORIZER_CLASS_NAME` should work.

**Comment by wqbill** [comment]
> Hi,
> 
> Did you try using the `KAFKA_CFG_*` env vars? Something like `KAFKA_CFG_AUTHORIZER_CLASS_NAME` should work.

It worked,thx.
And I've got another question.How to remove the default user(user/bitnami)?

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/containers/tree/main/bitnami/kafka#configuration) you can see the different env. variables and their default values
