### ISSUE TITLE
bitnami/wordpress-nginx How to switch the version of PHP? I have a project that requires an 8.1 environment.

### ISSUE THREAD

**Issue by himonster1** [bitnami/containers#39846]
### Name and Version

bitnami/wordpress-nginx

### What is the problem this feature will solve?

How to switch the version of PHP? I have a project that requires an 8.1 environment. 

This image defaults to 8.2 php, how can I switch to PHP 8.1?

### What is the feature you are proposing to solve the problem?

no

**Comment by carrodher** [comment]
You can change [this line](https://github.com/bitnami/containers/blob/43a9660c17d5f9a063eff5fab110e994d09c7b22/bitnami/wordpress-nginx/6/debian-11/Dockerfile#L28) in the _Dockerfile_ to use a previous PHP version. Then you can build your own container image. Being said that it is not something tested on our side so we can't guarantee that everything is going to work as expected.

Apart from that, you can use a previous container image. PHP version was bumped in [this PR](https://github.com/bitnami/containers/pull/38440), so using `bitnami/wordpress:6.2.2-debian-11-r17` you will have an image with PHP 8.1 while using `bitnami/wordpress:6.2.2-debian-11-r18` onwards you will images based on PHP 8.2

**Comment by himonster1** [comment]
Thank you very much! But yesterday PHP 8.1.21 was released again, I just need to change "php-8.2.8-0-linux-${OS_ARCH}-debian-11" \ to "php-8.1.21-0-linux-${OS_ARCH}-debian-11" \ in the dockerfile?

**Comment by carrodher** [comment]
The different PHP versions can be seen on the bitnami/php container since this one is updated when a new version is released upstream, see https://github.com/bitnami/containers/blob/main/bitnami/php-fpm/8.1/debian-11/Dockerfile#L27

**Comment by himonster1** [comment]
Hi, is there a PHP 7.4 environment?

**Comment by carrodher** [comment]
PHP 7.4 was deprecated some months ago, see the [official EOL](https://www.php.net/supported-versions.php)
