### ISSUE TITLE
/bitnami/mysql/data': Permission denied --creating a Mysql container in k8s(EKS)

### ISSUE THREAD

**Issue by ingenuityamitabh** [bitnami/containers#39980]
### Name and Version

bitnami/mysql/9.5.0

### What architecture are you using?

None

### What steps will reproduce the bug?
```
mysql 11:04:39.59 INFO  ==> ** Starting MySQL setup **mysql 11:04:39.61 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env varsmysql 11:04:39.61 INFO  ==> Initializing mysql databasemkdir: cannot create directory '/bitnami/mysql/data': Permission denied
```
### What is the expected behavior?

pod should be functional.

### What do you see instead?

error

**Comment by derek-adair** [comment]
I am trying to simply create a local mysql container w/ a mounted host directory and I get this error.  You can reproduce with the following [docker-compose](https://gist.github.com/derek-adair/05ed87ed792ecbc7a3f63b4cd930db7b) or;

```
curl -sSL https://gist.githubusercontent.com/derek-adair/05ed87ed792ecbc7a3f63b4cd930db7b/raw/6300994eb023e78e9d913fe05159267d222564f8/gistfile1.txt > docker-compose.yml && docker-compose up 
```

Is it possible there is an issue w/ multiple images?  This can be replicated by mounting the ghost image to a host directory as well.

**Comment by carrodher** [comment]
Bitnami containers are non-root by default, if you are mounting a local directory you need to ensure the permissions for this local directory are the proper ones. You can find more info about non-root containers at
- https://docs.bitnami.com/tutorials/work-with-non-root-containers
- https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/
- https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/#non-root-containers

You should make your local directory (and any subdir) belong to the _root_ group so any random user (i.e. 1001) running the process will be able to work on those directories.
