### ISSUE TITLE
[bitnami/kaniko] kaniko in a minideb environment

### ISSUE THREAD

**Issue by jxsl13** [bitnami/containers#40139]
### Name and Version

bitnami/kaniko:latest

### What is the problem this feature will solve?

I would like to install additional tools like curl for fetching other tools like mc (minio client) that fetch my static content that is required for building my docker image.

Would be cool if there was an additional kaniko container that allows to install additional tools.

### What is the feature you are proposing to solve the problem?

Additional  container variant that does not use scratch as base image but preferrably minideb.

### What alternatives have you considered?

copy & pasting the kaniko scratch version and changing it so that it uses minideb as base.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! At the moment we do not have plans to release a non-scratch version of kaniko because it is not well supported in our automations (have a scratch and non-scratch version of the same container). If this changes, we will inform the community.

**Comment by jxsl13** [comment]
Hi, 
thanks for the answer.
Seems to be a non trivial task, at least my first test seem to fail copying the kaniko executable.

https://github.com/GoogleContainerTools/kaniko/issues/1757

**Comment by jxsl13** [comment]
the better solution is to install the build tools in your build stage with a multistage build.
You pass credentials in that build stage and them discard your build stage in order not to bake credentials into your images.
