### ISSUE TITLE
[bitnami/moodle] Make moodle reachable behind a custom path

### ISSUE THREAD

**Issue by yibb-y** [bitnami/containers#40131]
### Name and Version

bitnami/moodle:4.1

### What is the problem this feature will solve?

I did not find a way to configure the moodle image to be accessed by a custom path.
For example the installed moodle instance is always reachable under example.com or localhost, but I would like it to be reachable under example.com/moodle123 or localhost/moodle123

### What is the feature you are proposing to solve the problem?

Create an environment variable so that the moodle installation can be directed to a custom path.

If this already exists then the documentation isn't very clear on how to do this. Can someone then give me a hint on how to do this?

### What alternatives have you considered?

Using a nginx to rewrite the urls.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request. I will forward this to the engineering team, but we cannot guarantee an ETA as it is not a critical feature. If you want to speed up the process, you can submit a PR implementing the feature.
