### ISSUE TITLE
[bitnami/postgresql] How to install extentions?

### ISSUE THREAD

**Issue by aboutZZ** [bitnami/containers#4022]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

How to install postgre extensions (e.g. `PostGIS`) in this image?

### What is the feature you are proposing to solve the problem?

——

**Comment by rafariossaa** [comment]
Hi,
  Postgis was added in [this release](https://github.com/bitnami/containers/tree/main/bitnami/postgresql#user-content-9615-r82-9615-ol-7-r92-9615-centos-7-r91-10100-r82-10100-ol-7-r90-10100-centos-7-r91-1150-r80-1150-centos-7-r87-1150-ol-7-r92-1200-r11-1200-centos-7-r17-and-1200-ol-7-r17).

**Comment by aboutZZ** [comment]
> Hi, Postgis was added in [this release](https://github.com/bitnami/containers/tree/main/bitnami/postgresql#user-content-9615-r82-9615-ol-7-r92-9615-centos-7-r91-10100-r82-10100-ol-7-r90-10100-centos-7-r91-1150-r80-1150-centos-7-r87-1150-ol-7-r92-1200-r11-1200-centos-7-r17-and-1200-ol-7-r17).

Thanks for for your reply, but Im using Postgre 14, any plan to build a GIS version on Postgre14?

**Comment by rafariossaa** [comment]
It is included in the container form those versions. So yes, it is already included in v14

**Comment by PatrykKlimowicz** [comment]
@rafariossaa I'm using version `11.18.0-debian-11-r4`. Is it possible to add the `hypopg` extension to the image?
I faced the error:

```bash
could not execute query: ERROR:  could not open extension control file "/opt/bitnami/postgresql/share/extension/hypopg.control": No such file or directory
    Command was: CREATE EXTENSION IF NOT EXISTS hypopg WITH SCHEMA pg_catalog;
```
