### ISSUE TITLE
[bitnami/discourse] Admin account creation fails (Error connecting to Redis)

### ISSUE THREAD

**Issue by chupinmaxime** [bitnami/containers#40644]
### Name and Version

bitnami/discourse:3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Docker image with docker-compose download from the documentation
2. Then `docker run -u root -it bitnami/discourse:3 bash`
3. Then `cd /opt/bitnami/discourse/`
4. Then `RAILS_ENV=production bundle exec rake admin:create`

### What do you see instead?

Couldn't connect to Redis
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)

### Additional information

The redis docker is running and I have a web site working (but I want to get the web administration)

**Comment by javsalgar** [comment]
Hi,

Could it be that redis is in a different network than the discourse container?
