### ISSUE TITLE
[bitnami/cassandra] Enable passing parameter sasi_indexes_enabled to cassandra.yaml by env var CASSANDRA_SASI_INDEXES_ENABLED

### ISSUE THREAD

**Issue by tancho-mihov-1crew** [bitnami/containers#40739]
### Name and Version

bitnami/cassandra

### What is the problem this feature will solve?

Creating a future to pass `sasi_indexes_enabled` to **cassandra.yaml** by environment variable CASSANDRA_SASI_INDEXES_ENABLED.
Your image has many parameters in **cassandra.yaml** that have changed by environment variables.
In our project we have migrated Cassandra from VMs to Kubernetes but we have hit that problem with the parameter `sasi_indexes_enabled`.

### What is the feature you are proposing to solve the problem?

Enable passing value of env var CASSANDRA_SASI_INDEXES_ENABLED to parameter sasi_indexes_enabled on cassandra.yaml file.

**Comment by tancho-mihov-1crew** [comment]
I guess a change should be made in these two files:
[cassandra-env.sh](https://github.com/bitnami/containers/blob/main/bitnami/cassandra/4.1/debian-11/rootfs/opt/bitnami/scripts/cassandra-env.sh)
[libcassandra.sh](https://github.com/bitnami/containers/blob/main/bitnami/cassandra/4.1/debian-11/rootfs/opt/bitnami/scripts/libcassandra.sh)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
