### ISSUE TITLE
[bitnami/spark] License Concern - Clarifying approach for updating Bitnami DockerFile to remove multiple critical CVEs

### ISSUE THREAD

**Issue by JTBS** [bitnami/containers#40845]
### Name and Version

bitnami/spark:3.4.0

### What is the problem this feature will solve?

Even with base Bitnami Spark 3.4.0 image, I noticed multiple Critical CVEs due to JAR files present OR CURL version still detected in security scan.

So I cloned Bitnami Container Dockerfile that is used for spark:3.40
I had to recreate multi-stage build with bitnami/minideb:bullseye, 
- After deleting pkgs, jars that not needed OR upgrading versions as needed

This brought down to 0 Critical CVEs and testing is all good

**Question: more background**
- I borrowed same LABELS that are in original Bitnami Docker file while doing so:
```Dockerfile
LABEL org.opencontainers.image.base.name="docker.io/bitnami/minideb:bullseye" \
      org.opencontainers.image.created="2023-06-08T09:28:06Z" \
      org.opencontainers.image.description="Application packaged by VMware, Inc" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.ref.name="3.4.0-debian-11-r4" \
      org.opencontainers.image.title="spark" \
      org.opencontainers.image.vendor="VMware, Inc." \
      org.opencontainers.image.version="3.4.0"
```

**Questions:**

- Is this right OR because I changed image, I should not use these labels? 
- Is there any license violation?
- If so how I can do this right?
- This image is used purely internally - and I am not sure of importance of those labels in DockerFile

### What is the feature you are proposing to solve the problem?

Clearing out all critical CVEs.
Question is on approach used.. checking if this comes under license violation OR what do I need to do if so?

### What alternatives have you considered?

I have upgraded Software versions including Spark to use bitnami 3.4.0 spark version

**Comment by javsalgar** [comment]
Hi,

There shouldn't be any issue with that. You can check the license (APACHE2) here: https://github.com/bitnami/containers/blob/main/LICENSE.md
