### ISSUE TITLE
[RabbitMQ] Running in FIPS Mode

### ISSUE THREAD

**Issue by zivkapl** [bitnami/containers#40857]
Hi,

I am using your Bitnami/RabbitMQ image in Kubernetes.
I want to run RabbitMQ in FIPS mode, is this possible?
If not, do you maybe provide other images that work in FIPS? 

Thank you

**Comment by gongomgra** [comment]
Hi @zivkapl,

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
PhotonOS is a distro FIPS compliant by default.

Hope it helps!
