### ISSUE TITLE
[bitnami/moodle] Container exits after Running database upgrade

### ISSUE THREAD

**Issue by jujavie** [bitnami/containers#40859]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I cannot run the bndiagnostic because I am not able to run the container

### bndiagnostic output

![image](https://github.com/bitnami/vms/assets/5472611/476e1683-0bc2-47c0-abe5-a1063d0d5904)

![image](https://github.com/bitnami/vms/assets/5472611/a5333eb5-43b5-4b52-b15e-f008d84ebc7b)

### bndiagnostic was not useful. Could you please tell us why?

I cannot run the bndiagnostic because I am not able to run the container

### Describe your issue as much as you can

I am trying to move a Bitnami Moodle Docker Desktop installation to a Virtual Box machine running RHEL 8.7 with Docker Engine v24.0.4. 

Docker Destop: The Docker Desktop installation is working OK. Also, I exported the volumes and I can migrate to other computers with Docker Desktop using the .tar volumes and a docker compose file. 

VBOX with Docker Engine: I already have pulled the images (bitnami/mariadb, bitnami/moodle and bitnami/phpmyadmin) and the exported .tar volumes (moodle and moodledata) imported in Docker and I am using the docker compose command to create and run the containers in the virtual box. 

The docker compose command raise the MariaDB and PHPMyadmin containers well, but the Moodle container exits. 

Looking at the docker logs, the moodle log shows the process until "INFO ==> running database upgrade" and exits. I have checked the services are in the same network, I have changed the variable MOODLE_SKIP_BOOTSTRAP to yes, I have tried using docker run instead of compose. Always the same result, it exits at the same point.

Any idea? Thank you

**Comment by gongomgra** [comment]
Hi @jujavie,

Thanks for using Bitnami. bndiagnostic is only expected to work in vms at this moment. As you are using the container, can you update the `docker-compose` file you are using and set the `BITNAMI_DEBUG=true` environment variable for Moodle? It will give you further details on the issue.

**Comment by Martoxdlol** [comment]
> Hi @jujavie,
> 
> Thanks for using Bitnami. bndiagnostic is only expected to work in vms at this moment. As you are using the container, can you update the `docker-compose` file you are using and set the `BITNAMI_DEBUG=true` environment variable for Moodle? It will give you further details on the issue.

Using `BITNAMI_DEBUG=true` is useful. I couldn't find it in the README. I think it should be included somewhere.

**Comment by jujavie** [comment]
Thank you for your response. I have included the debud parameter. Now my docker-compose.yml file is:

version: '2'
services:
 moodle:
    image: docker.io/bitnami/moodle:4.2
    container_name: moodle
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - BITNAMI_DEBUG=true
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_USERNAME=xxx
      - MOODLE_PASSWORD=xxx
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=xxx
      - MOODLE_DATABASE_PASSWORD=xxx
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_REVERSEPROXY=no
      - MOODLE_SSLPROXY=no
      - PHP_ENABLE_OPCACHE=true
      - PHP_POST_MAX_SIZE=256M
      - PHP_UPLOAD_MAX_FILESIZE=256M
    volumes:
      - 'cfyd_moodle:/bitnami/moodle'
      - 'cfyd_moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - cfyd
 mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: mariadb
    environment:
      - MARIADB_ROOT_USER=xxx
      - MARIADB_ROOT_PASSWORD=xxx
      - MARIADB_USER=xxx
      - MARIADB_PASSWORD=xxx
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'cfyd_mariadb:/bitnami/mariadb'
    networks:
      - cfyd
 phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - '81:8080'
      - '444:8443'
    depends_on:
      - mariadb
    networks:
      - cfyd
volumes:
  cfyd_mariadb:
    external: true
  cfyd_moodle:
    external: true
  cfyd_moodledata:
    external: true
networks:
  cfyd:
    name: red_cfyd

**Comment by jujavie** [comment]
And my volumes are mounted: 
![image](https://github.com/bitnami/containers/assets/5472611/a63d5dfe-4f44-4203-bbef-dedc0c6d7c51)

When I run docker compose with the previous file, the container moodle exits.

This is the debug capture:
![image](https://github.com/bitnami/containers/assets/5472611/c2467226-f61a-4588-8ed5-4ae7b7967177)

Now the problem seems to be that the container is expecting a config.php file y the opt/bitnami/moodle directory, but the is no bitnami moodle directory in the original image docker.io/bitnami/moodle:4.2, because the config.php file creates in the installation process.

I have included the MOODLE_SKIP_BOOTSTRAP=yes parameter to avoid Moodle from initial installation because I am giving the continer a mounted volumen with all the necessary (mounted in /bitnami/moodle in the container)

I don't know why the image is searching for that config.php file.

Thanks again

**Comment by gongomgra** [comment]
Hi @jujavie,

I have been checking our Moodle initialization logic and I'm afraid I can't find any possible explanation for your issue. According to the logic linked below, we are, by default, restoring the Moodle folder.

> # From moodle-env.sh
> # Moodle persistence configuration
export MOODLE_VOLUME_DIR="${BITNAMI_VOLUME_DIR}/moodle"
export MOODLE_DATA_DIR="${MOODLE_DATA_DIR:-${BITNAMI_VOLUME_DIR}/moodledata}"
export MOODLE_DATA_TO_PERSIST="${MOODLE_DATA_TO_PERSIST:-$MOODLE_BASE_DIR}"
>
>
> # From libmoodle.sh
>    else
>        info "Restoring persisted Moodle installation"
>        restore_persisted_app "$app_name" "$MOODLE_DATA_TO_PERSIST"
>
>        info "Trying to connect to the database server"

https://github.com/bitnami/containers/blob/main/bitnami/moodle/4.2/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L200

So I can't find any explanation on why the rest of the logic is not finding the expected `config.php` file. Can you check if the structure on your local folder and also when it is mounted matches the expected structure? Maybe there is an additional directory entry in the middle?

**Comment by guieusebiogaspar** [comment]
I have the exact same issue... With Docker Desktop on Windows/Mac works just fine, but I was going to put the website in production on a VM running CentOS and I'm facing the exact same problem described inittially

**Comment by jujavie** [comment]
I achieved bypassing the running database upgrade problem and finally running moodle changing the owner and permissions for all files and folders. When you create .tar or .tar.gz files saving images or exporting volumes from your docker desktop installation, owner is one, but when you untar the files into the CentOS VM they have probably changed.

I recommend changing owner and permissions for all files and folders in the bitnami/mariadb/data folder of the mariadb container:
chown -R 1001:root *
find . -type d -exec chmod 700 {} +
find . -type f -exec chmod 660 {} + 
chmod 644 mysql_upgrade_info
If 1001 does not work

Also change in moodle container, folder bitnami/moodle:
chown -R bin:bin *
find . -type d -exec chmod 775 {} +
find . -type f -exec chmod 644 {} +

And inside bitnami/moodledata:
chown -R bin:bin *
find . -type d -exec chmod 775 {} +
find . -type f -exec chmod 664 {} +
chmod 644 moodle-cron.log

In this last folder I had to change directories to 777 because moodle said it could not write on them.

Try again to raise the services, for example using docker compose.

I recommend to include the following environmental vars in docker-compose.yml
In mariadb service      - MARIADB_SKIP_TEST_DB=yes
In moodle service       - MOODLE_SKIP_BOOTSTRAP=yes
                                   - MOODLE_SKIP_INSTALL=yes

All of these changes assume that the mariadb service is running and the problem is that moodle cannot connect to the database. 

Good luck!

**Comment by guieusebiogaspar** [comment]
After applying this on mariadb_data/data, the container starts but then doesn't seem it keeps running like before...

chown -R 1001:root *
find . -type d -exec chmod 700 {} +
find . -type f -exec chmod 660 {} +
chmod 644 mysql_upgrade_info

Also, when you said this: "If 1001 does not work" you were refering to which commands?

Another thing that I'm not sure if it affects the file permissions. I'm changing the permissions on the host (CentOS) and then launching the services. I'm not accessing the containers to change the permissions.

As of now I did two tests:
- Applying all the commands you gave me (had to use sudo in all of them except on the chown ones)
- Applying only the mariadb ones

Please help me, you have no idea how much I need this....

**Comment by guieusebiogaspar** [comment]
I did it! I only changed the permissions of moodledata. I had to change the permissions of the parent folder (moodledata) and not only the inside files/dirs. Thank you so much for your help!
