### ISSUE TITLE
[bitnami/elasticsearch] how to wait for elasticsearch to be up (script/bash)

### ISSUE THREAD

**Issue by Just4Dahu** [bitnami/containers#40852]
### Name and Version

bitnami/elasticsearch

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello, 

I'm using the elasticsearch container in the zammad docker-compose stak. I've written a script (shell / bash) to restore the data to zammad when we need to migrate host, for example. However, at the end of my script, I need to reindex the elastic database via another "railsserver" container. 

So at the end I need to do this command: docker exec zammad_zammad-railsserver_1 rake zammad:searchindex:rebuild

In my script I have to down and up the docker-compose. 
however I have an error following my command : 
```
I, [2023-07-12T14:48:08.311596 #8-8260]  INFO -- : Using memcached as Rails cache store.
I, [2023-07-12T14:48:08.311776 #8-8260]  INFO -- : Using Redis as web socket session store.
I, [2023-07-12T14:48:09.730662 #8-8260]  INFO -- : Setting.set('product_logo', "24d8755bfcc894f96d5b4c544e8a60c0.png")
I, [2023-07-12T14:48:12.298663 #8-8260]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "KnowledgeBase::Answer::Translation", "Organization", "Ticket", "User"])
E, [2023-07-12T14:48:12.766371 #8-8260] ERROR -- : Unable to process GET request to elasticsearch URL 'http://zammad-elasticsearch:9200'. Elasticsearch is not reachable. It's possible that it's not running. Please check whether it is installed.

Response:
#<UserAgent::Result:0x000055c2e4671068 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to zammad-elasticsearch:9200 (Connection refused - connect(2) for \"zammad-elasticsearch\" port 9200)>", @header=nil>

Payload:
null

Payload size: 0M
rake aborted!
Unable to process GET request to elasticsearch URL 'http://zammad-elasticsearch:9200'. Elasticsearch is not reachable. It's possible that it's not running. Please check whether it is installed.
```

how can I make my command wait until the elasticsearch container is accessible before running the command? 

PS: I don't want to use sleep.

### What is the expected behavior?

no longer get the error that elasticsearch is unavailable

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by Just4Dahu** [comment]
Thank you, I will continue my research and hope for an answer.

**Comment by Just4Dahu** [comment]
I'll be back with my solution, 

here is the shell code : 

until docker exec zammad_zammad-railsserver_1 curl -s http://zammad-elasticsearch:9200 >/dev/null ; do
        display "Elasticsearch is not yet ready. Waiting..."
        sleep 5
done
display "Elasticsearch is ready to accept connections."
docker exec zammad_zammad-railsserver_1 rake zammad:searchindex:rebuild
