### ISSUE TITLE
[bitnami/matomo] Docker Image matomo:4.15.0 contains version 4.14.2

### ISSUE THREAD

**Issue by dieisraels** [bitnami/containers#41056]
### Name and Version

bitnami/matomo:4.15.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Pull docker image from Docker Hub
2. Boot the image after updating the database to Matomo 4.15.0.

### What do you see instead?

Error Message:

> Your Matomo codebase is running on the old version 4.14.2 and we have detected that your Matomo database has already been updated to the newer version 4.15.0.

### Additional information

Could it be because the CI/CD checks failed during the last commit:
https://github.com/bitnami/containers/actions/runs/5518692824/jobs/10062997560

**Comment by migruiz4** [comment]
Hi @dieisraels,

Thank you for reporting this issue, we are currently working to fix this.

As you mentioned, the CI/CD for matomo 4.15.0 is failing because the version packed does not match: https://github.com/bitnami/containers/actions/runs/5518692824/jobs/10062997560

**Comment by migruiz4** [comment]
Hi @dieisraels,

We have released the image `bitnami/matomo:4.15.0-debian-11-r4` (https://github.com/bitnami/containers/pull/41142) which fixes this issue.

Please let us know if you find any further issues.
