### ISSUE TITLE
How to set correct string in .env?

### ISSUE THREAD

**Issue by cleargoal** [bitnami/containers#41277]
### Name and Version

bitnami/symfony latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I tried to run `php bin/console doctrine:schema:create`

### What is the expected behavior?

Schema creation

### What do you see instead?

error  `An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused`. 

### Additional information

Actually, it's not a real bag, sorry. But, I didn't find a proper place for this question and I can't use the container with its full functionality.

As far as in **docker-compose.yml**, we have 
`ALLOW_EMPTY_PASSWORD=yes`
a DB may work without a password, isn't it?

Actually, do I set the correct next line, in Symfony **.env**?
`DATABASE_URL="mysql://bitnami:''@127.0.0.1:3306/bitnami?serverVersion=10.11.2-MariaDB&charset=utf8mb4"`

My question exists because I tried to run 'php bin/console doctrine:schema:create' and got an error  `An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused`. 
So, I want to understand that this error doesn't produce by a missing password or misconfiguration of mentioned line.

**Comment by carrodher** [comment]
Yes, the testing/development docker-compose that appears in the root of the repository should work as it is, without setting any password for the database

**Comment by cleargoal** [comment]
Thanks for your response!

Maybe, can you help me to create a schema?
The line 'php bin/console doctrine:schema:create' I get from the Symfony tutorial and I suggest that it's correct, but I don't completely sure.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by cleargoal** [comment]
Thank you!
Finally, I passed that error and got a new one.
`An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'bitnami'@'172.25.0.1' (using password: YES) `
It looks like related to password settings in the container. 
What to do, help me, please.
