### ISSUE TITLE
[bitnami/elastic] Adding my_elasticsearch.yml causes the default configration can't be found

### ISSUE THREAD

**Issue by yanqianglu** [bitnami/containers#41281]
### Name and Version

bitnami/elasticsearch:8.8.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

When adding custom Elasticsearch configuration my_elasticsearch.yml as suggested in the documentation, the container failed with `NoSuchFileException`. The default configuration file `/opt/bitnami/elasticsearch/config/elasticsearch.yml` is somehow not being added into the container which can be confirmed by inspecting the container.

Sample dockerfile
```Dockerfile
FROM bitnami/elasticsearch:8.8.2

COPY config/elasticsearch.yml /opt/bitnami/elasticsearch/config/my_elasticsearch.yml
```

### What is the expected behavior?

The container should be ran successfully and the custom configuration should be applied.

### What do you see instead?

```
Exception in thread "main" java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /opt/bitnami/elasticsearch/config/elasticsearch.yml
        at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:119)
        at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:88)
        at org.elasticsearch.server.cli.ServerCli.startServer(ServerCli.java:239)
        at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:100)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.Command.main(Command.java:50)
        at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
Caused by: java.nio.file.NoSuchFileException: /opt/bitnami/elasticsearch/config/elasticsearch.yml
```

### Additional information

A workaround is to copy-paste the default configuration, adding custom configuration to it, and copy the file into `/opt/bitnami/elasticsearch/config/elasticsearch.yml` in the dockerfile

**Comment by yanqianglu** [comment]
ah, I think it's probably due to my setup. this is the actual dockerfile I use

```
FROM bitnami/elasticsearch:8.8.2

COPY config/elasticsearch.yml /opt/bitnami/elasticsearch/config/my_elasticsearch.yml
COPY index_mappings /opt/bitnami/elasticsearch/index_mappings

COPY start_es.sh /opt/bitnami/scripts/start_es.sh
CMD ["/opt/bitnami/scripts/start_es.sh"]
```

```
# start_es.sh
#!/bin/bash

# Start Elasticsearch and send it to the background
/opt/bitnami/scripts/elasticsearch/run.sh &

# Wait for Elasticsearch to start
while ! curl --silent --output /dev/null --write-out '%{http_code}' http://localhost:9200/_cluster/health | grep -q '^2'
do
  sleep 1
done

# Apply index mappings
for file in /opt/bitnami/elasticsearch/index_mappings/*.json; do
  template_name=$(basename "$file" .json)
  curl -X PUT -H 'Content-Type: application/json' --data "@$file" "http://localhost:9200/_index_template/$template_name"
done

# Wait for Elasticsearch to finish
wait
```

I was thinking to create a `start_es.sh` script to apply index template once Elasticsearch starts. I guess that messed up the initialization of bitnami/elasticsearch container?

**Comment by carrodher** [comment]
Glad to see you were able to fix the issue

**Comment by yanqianglu** [comment]
Hi @carrodher , I'm not entirely getting this fixed. May i know why manually running `/opt/bitnami/scripts/elasticsearch/run.sh &` is not good enough? How should I change my setup to use custom script while ensuring bitnami/elastic container gets initialized properly

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
