### ISSUE TITLE
Matomo 4.15 images contain 4.14 code

### ISSUE THREAD

**Issue by koehn** [bitnami/containers#41391]
### Name and Version

bitnami/matomo:4.15.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

From the `bitnami/matomo:4.15.0` image, look in the `/opt/bitnami/matomo/core/Version.php` file:
```php
/opt/bitnami$ cat matomo/core/Version.php 
<?php

/**
 * Matomo - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */

namespace Piwik;

/**
 * Matomo version information.
 *
 * @api
 */
final class Version
{
    /**
     * The current Matomo version.
     * @var string
     */
    const VERSION = '4.14.2';

    const MAJOR_VERSION = 4;

    public function isStableVersion($version)
    {
        return (bool) preg_match('/^(\d+)\.(\d+)\.(\d+)$/', $version);
    }

    public function isVersionNumber($version)
    {
        return $this->isStableVersion($version) || $this->isNonStableVersion($version);
    }

    private function isNonStableVersion($version)
    {
        return (bool) preg_match('/^(\d+)\.(\d+)\.(\d+)-.{1,4}(\d+)$/', $version);
    }
}
```

### What is the expected behavior?

The 4.15 image should contain the 4.15 code. 

### What do you see instead?

It actually contains the 4.14.2 code.

**Comment by carrodher** [comment]
This issue should be solved after changes in https://github.com/bitnami/containers/pull/41142. This was reported in https://github.com/bitnami/containers/issues/41056 and the mentioned PR was created to solve it.

Not sure if you could have cached the `bitnami/matomo:4.15.0` image, could you try using the `4.15.0-debian-11-r4` immutable tag or removing the cached images?

**Comment by koehn** [comment]
Confirmed, I see the changes now. Thanks.
