### ISSUE TITLE
public.ecr.aws/bitnami/golang:1.19 fails

### ISSUE THREAD

**Issue by nnmin-aws** [bitnami/containers#41399]
### Name and Version

bitnami/golang:1.19

### What architecture are you using?

None

### What steps will reproduce the bug?

1. use this image
2.  run `go test -v -race -cover -covermode=atomic ./... -testing.v=5 -args -v=5`
3. got error:
```
Using docker image sha256:107fbb0d829bac50b8f561bb7abe17d1b3aed8dcdb935894a6efffb648d8afec for public.ecr.aws/bitnami/golang:1.19 with digest public.ecr.aws/bitnami/golang@sha256:d47c07fbaf5533222e2b4762645bd1fdde92f69309292fe015b0d4b1a6526165 ...

runtime.mallocgc: relocation target __tsan_malloc not defined
runtime.runfinq: relocation target __tsan_finalizer_goroutine not defined
runtime.(*sweepLocked).sweep: relocation target __tsan_free not defined
runtime.goexit1: relocation target __tsan_go_end not defined
runtime.gfget: relocation target __tsan_malloc not defined
```

### What is the expected behavior?

it used to work with ```Using docker image sha256:5ee4dc3d3b2767238b984ad7703dc4a901c943b428b775b4bb6c96305ee061cd for public.ecr.aws/bitnami/golang:1.19 with digest public.ecr.aws/bitnami/golang@sha256:a189e0057b5a4257d497d400d47111305924b3b848ec62d714b573fb820f2903 ...```

### What do you see instead?

got a lot of errors
```
runtime.mallocgc: relocation target __tsan_malloc not defined
runtime.runfinq: relocation target __tsan_finalizer_goroutine not defined
runtime.(*sweepLocked).sweep: relocation target __tsan_free not defined
runtime.goexit1: relocation target __tsan_go_end not defined
runtime.gfget: relocation target __tsan_malloc not defined
runtime.(*p).init: relocation target __tsan_proc_create not defined
runtime.(*p).destroy: relocation target __tsan_go_end not defined
runtime.(*p).destroy: relocation target __tsan_proc_destroy not defined
runtime.RaceErrors: relocation target __tsan_report_count not defined
runtime.RaceDisable: relocation target __tsan_go_ignore_sync_begin not defined
runtime.RaceEnable: relocation target __tsan_go_ignore_sync_end not defined
runtime.raceinit: relocation target __tsan_init not defined
runtime.raceinit: relocation target __tsan_map_shadow not defined
runtime.racefini: relocation target __tsan_fini not defined
runtime.racemapshadow: relocation target __tsan_map_shadow not defined
runtime.racegostart: relocation target __tsan_go_start not defined
runtime.raceacquireg: relocation target __tsan_acquire not defined
```

### Additional information
it used to work with ```Using docker image sha256:5ee4dc3d3b2767238b984ad7703dc4a901c943b428b775b4bb6c96305ee061cd for public.ecr.aws/bitnami/golang:1.19 with digest public.ecr.aws/bitnami/golang@sha256:a189e0057b5a4257d497d400d47111305924b3b848ec62d714b573fb820f2903 ...```

**Comment by carrodher** [comment]
Could you try using a specific immutable tag such as `1.19.11-debian-11-r8` instead of a rolling tag? In that way, it could be easy to detect when the issue appears, see https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/
