### ISSUE TITLE
Dynamic installation and data path

### ISSUE THREAD

**Issue by InspectorGadget** [bitnami/containers#41419]
### Name and Version

bitnami/moodle:latest

### What is the problem this feature will solve?

Hi,

I'm currently in the midst of trying to change the directories up from `/opt/bitnami` and `/bitnami` to `mnt/moodle/**` as the base dir due to a requirement that the environment I am running this Image on does not have access to write to any other folders except `/mnt/**`.

Maybe it would be good if we can switch up the directory paths through ARG?

### What is the feature you are proposing to solve the problem?

Dynamic path changing by defining ARG within the Dockerfile. 

### What alternatives have you considered?

I have even downloaded the manifest and tried to change it up myself and build it, yet no luck. I am definitely doing the process of changing the directories wrongly, so it would be great if Bitnami Team could assist to enlighten me on where I should change the directory paths if this suggested feature does not make it to production.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by InspectorGadget** [comment]
Hi @carrodher,

I would love to contribute to the Image within this repository. However, I would like some details related to how the Image works;

1. How is the `/bitnami` folder populated automatically
2. If there are any files / folder changes that Bitnami Team anticipates.

For a record, I have tried doing all kinds of techniques to get it working with the directory preference that I wanted, yet no luck. However, these techniques does work with other bitnami related images.

**Comment by InspectorGadget** [comment]
Update:
I have managed to make the Image to populate all the files from `/bitnami` to `/mnt/bitnami/installation` - However, would it also be possible to move the files within `/opt/bitnami` to `/mnt/bitnami/server` too? I did try to use the same method I did for `/bitnami` folder migration, it did not work.

**Comment by carrodher** [comment]
It seems a very specific use case that is not tested on our side so we can't provide confidence that this kind of customization can work without unexpected issues

**Comment by InspectorGadget** [comment]
@carrodher ,
Maybe I could give it a try, if you could explain to me a very high level perspective on the change that is needed. It seems like whenever I try to move the directory out of `opt/bitnami` - The `install.php` file just exits without any error. I am so close to achieve it, since the only thing left is to use `/mnt/bitnami/server` directory instead of `/opt/bitnami`. :(
