### ISSUE TITLE
[bitnami/mariadb] mariadb:10.4 "exec format error"

### ISSUE THREAD

**Issue by SpiralBrad** [bitnami/containers#41464]
### Name and Version

bitnami/mariadb:10.4

### What architecture are you using?

~~amd64~~ (Edit: I was incorrect; it is **aarch64**)

### What steps will reproduce the bug?

1. Use the container as of this issue posting

### What is the expected behavior?

The container runs without issue

### What do you see instead?

An error in the logs: `exec /opt/bitnami/scripts/mariadb/entrypoint.sh: exec format error`

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the platform you are using? It seems that you are using a different architecture (for example, an arm64 container in a amd64 host)

**Comment by SpiralBrad** [comment]
@javsalgar Ahh yep that may be part of the issue - I was using the [10.4 docker compose](https://github.com/bitnami/containers/blob/main/bitnami/mariadb/10.4/debian-11/docker-compose.yml) on a Raspberry Pi OS (Raspbian) aarch64.

Opened the ticket because I tried other versions and they worked as expected, namely [10.5 via docker compose](https://github.com/bitnami/containers/blob/main/bitnami/mariadb/10.5/debian-11/docker-compose.yml) even.

----
Further info: This actually is in an attempt to get the [bitnami magento container](https://github.com/bitnami/containers/blob/main/bitnami/magento/docker-compose.yml) working on this same setup, which explicitly specifies 10.4.  Switching the mariadb version there does not work either, but that's an unrelated issue to this one with exec/entrypoint.sh.

**Comment by javsalgar** [comment]
Hi,

I'm afraid we don't currently have an arm64 version of the mariadb container https://hub.docker.com/layers/bitnami/mariadb/10.4/images/sha256-7631ac662e0c3c59d3c2236b78b92622cfd7c9a8c7e8b1cddb2670c39e175a46?context=explore
