### ISSUE TITLE
Overriding tag image in docker hub plus BC break in patch version

### ISSUE THREAD

**Issue by tjurczak** [bitnami/containers#41461]
### Name and Version

bitnami/pgbouncer

### What is the problem this feature will solve?

1. We noticed that commit https://github.com/bitnami/containers/commit/190481f04144fe8ff1247da6fc7ed605951352b4 triggered rebuilding existing tag image (1.19.1) https://hub.docker.com/layers/bitnami/pgbouncer/1.19.1/images/sha256-f5237aa4478b708b7afacbd7ff7dcb53c20e0fddb2afc3e613e2935e254ea553?context=explore
2. You applied (in my opinion) BC break, because in the above commit changed the default value for `PGBOUNCER_AUTH_TYPE` from `md5` to `scram-sha-256`. This little change **may have a huge impact on the performance**. Establishing connections in high-traffic environments starts requiring more CPU.
3. If we join problem 1 and problem 2, we have a sudden increase in CPU load at random moment (when one container is rescheduled and a new image is retrieved).

### What is the feature you are proposing to solve the problem?

1. I would never override the published docker image tag (`1.19.1` should be immutable). If you would like to have the latest version of the minor version you can publish `1.19` or `1.19-latest` tag image, and update it when you need.
2. Don't change the default configuration in PATCH versions.

**Comment by carrodher** [comment]
Sorry for the breaking changes, unfortunately, the used versioning follows the upstream project versions and internal changes are done by using revisions.

Regarding container image tags, there are different rolling tags (such as 1.19 or 1.19.1) but also immutable tags that are recommended in order to have control over the changes. [Here](https://docs.bitnami.com/kubernetes/infrastructure/postgresql/configuration/understand-rolling-immutable-tags/) you can find more info about this topic

**Comment by tjurczak** [comment]
@carrodher Thanks for the explanations! Very useful (important) information (https://docs.bitnami.com/kubernetes/infrastructure/postgresql/configuration/understand-rolling-immutable-tags/). Good to know it in order to avoid problems in the future. Maybe this information should be more visible for people who use the images (some info in readme.md or image description).

**Comment by carrodher** [comment]
There is a section in the README about this topic, see https://github.com/bitnami/containers/tree/main/bitnami/pgbouncer#supported-tags-and-respective-dockerfile-links. There is a link to an article (similar to the one I shared) about this topic.
