### ISSUE TITLE
performance test scripts that Kafka provides for validation 

### ISSUE THREAD

**Issue by sowjanya007b** [bitnami/containers#41763]
### Name and Version

3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

we have upgraded the Kafka version from 3.2 to 3.3 zookeeper-less now we need to validate the Kafka functionality 
are there any performance test scripts that Kafka provides?

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by OneCricketeer** [comment]
Kafka includes perf test CLI scripts in its bin directory
