### ISSUE TITLE
[bitnami/matomo] Loop of restarting matomo 

### ISSUE THREAD

**Issue by w4rell** [bitnami/containers#41767]
### Name and Version

bitnami/matomo:4.15.0-debian-11-r12 (every after version 4)

### What architecture are you using?

None

### What steps will reproduce the bug?

Originally in tag matomo:4 and mariadb:10.6
Tried to upgrade to latest image changing my docker-compose to latest (only matomo) and docker compose up -d.

### What is the expected behavior?

Upgrade the version and work normally.

### What do you see instead?

```
random-matomo-1  | matomo 13:44:31.61 
random-matomo-1  | matomo 13:44:31.62 Welcome to the Bitnami matomo container
random-matomo-1  | matomo 13:44:31.62 Subscribe to project updates by watching https://github.com/bitnami/containers
random-matomo-1  | matomo 13:44:31.62 Submit issues and feature requests at https://github.com/bitnami/containers/issues
random-matomo-1  | matomo 13:44:31.62 
random-matomo-1  | matomo 13:44:31.63 INFO  ==> ** Starting Matomo setup **
random-matomo-1  | realpath: /bitnami/apache/conf: No such file or directory
random-matomo-1  | matomo 13:44:31.69 INFO  ==> Configuring Apache ServerTokens directive
random-matomo-1  | matomo 13:44:31.72 INFO  ==> Configuring PHP options
random-matomo-1  | matomo 13:44:31.72 INFO  ==> Setting PHP expose_php option
random-matomo-1  | matomo 13:44:31.74 INFO  ==> Setting PHP output_buffering option
random-matomo-1  | matomo 13:44:31.76 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
random-matomo-1  | matomo 13:44:31.80 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
random-matomo-1  | matomo 13:44:31.90 INFO  ==> Persisted Matomo installation detected
random-matomo-1  | matomo 13:44:31.91 INFO  ==> Restoring Matomo installation
random-matomo-1  | matomo 13:44:31.93 INFO  ==> Trying to connect to the database server
random-matomo-1  | matomo 13:44:31.98 INFO  ==> Launching schema update
random-matomo-1  | Could not open input file: /opt/bitnami/matomo/console
random-matomo-1 exited with code 1
```

### Additional information

Thanks for your help !

**Comment by jotamartos** [comment]
From which version to which one are you updating the solution? I just upgraded the container from bitnami/matomo:4.14.2 to bitnami/matomo:4.15.0 and everything worked as expected 

```
matomo-matomo-1  | matomo 10:52:29.64 INFO  ==> Configuring Apache ServerTokens directive
matomo-matomo-1  | matomo 10:52:29.65 INFO  ==> Configuring PHP options
matomo-matomo-1  | matomo 10:52:29.65 INFO  ==> Setting PHP expose_php option
matomo-matomo-1  | matomo 10:52:29.66 INFO  ==> Setting PHP output_buffering option
matomo-matomo-1  | matomo 10:52:29.68 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo-matomo-1  | matomo 10:52:29.69 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo-matomo-1  | matomo 10:52:29.74 INFO  ==> Persisted Matomo installation detected
matomo-matomo-1  | matomo 10:52:29.74 INFO  ==> Restoring Matomo installation
matomo-matomo-1  | matomo 10:52:30.00 INFO  ==> Trying to connect to the database server
matomo-matomo-1  | matomo 10:52:30.03 INFO  ==> Launching schema update
matomo-matomo-1  |
matomo-matomo-1  |
matomo-matomo-1  | Everything is already up to date.
matomo-matomo-1  |
matomo-matomo-1  |
matomo-matomo-1  | Done.
```

**Comment by Micht69** [comment]
Hi,

Same problem here running Matomo on kubernetes using the bitnami chart.

I was on 4.14.1 and running fine, after applying the version 1.1.8 of the chart which result in Matomo 4.15.0, I have the same error and my podis in CrashLoop state.
> matomo 16:04:51.03 INFO  ==> Launching schema update  
> Could not open input file: /opt/bitnami/matomo/console

Launching the pod in debug mode (using sleep), I found that `/opt/bitnami/matomo/console` is not executable ; could this be the issue ?

**Comment by Micht69** [comment]
I rolled back to `4.14.2-debian-11-r0` and the pod is starting fine.

**Comment by jotamartos** [comment]
Hi @Micht69,

I reproduced the issue and will investigate what's wrong with the upgrade process. Will update this ticket once I have more information.

**Comment by jotamartos** [comment]
I just found that we changed the [data to persist/recover in the solution](https://github.com/bitnami/containers/pull/35725/files) some weeks ago but didn't release a new major of the chart. Investigating what's the best approach to upgrade the solution now.

**Comment by jotamartos** [comment]
Hi all, 

We released yesterday a new version of the Matomo container and Chart to fix this issue.

https://github.com/bitnami/containers/pull/42956
https://github.com/bitnami/charts/pull/18064

The solution persists the entire installation directory and it takes care of updating the Matomo files as mentioned in the official documentation.

Please confirm everything works as expected

**Comment by w4rell** [comment]
> Hi all,
> 
> We released yesterday a new version of the Matomo container and Chart to fix this issue.
> 
> #42956 [bitnami/charts#18064](https://github.com/bitnami/charts/pull/18064)
> 
> The solution persists the entire installation directory and it takes care of updating the Matomo files as mentioned in the official documentation.
> 
> Please confirm everything works as expected

Just tried, everything is working fine now !

**Comment by Micht69** [comment]
Hi,

Same here, updated to chart 1.1.11 without issue.

Thanks

**Comment by jotamartos** [comment]
Great! 😄  I'm really happy to hear that! 

Enjoy!
