### ISSUE TITLE
[bitnami/jupyter-base-notebook] Container Startup Failure: Missing Environment Variable $JUPYTERHUB_SERVICE_URL

### ISSUE THREAD

**Issue by JoaZ94** [bitnami/containers#42319]
### Name and Version

bitnami/jupyter-base-notebook:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When executing the command 'docker run --name jupyter-base-notebook bitnami/jupyter-base-notebook:latest' on Windows 10 with WSL(Ubuntu), an error occurred during the startup of the container.

### What is the expected behavior?

The container should start and provide the jupyter notebook service.

### What do you see instead?

An error occurred during the startup of the JupyterHubSingleUser server extension. The error message indicates that the extension failed to load due to a missing required environment variable: $JUPYTERHUB_SERVICE_URL. 

Apparently, this environment variable is essential for the proper functioning of the extension, and its absence prevents the extension from initializing successfully. To resolve this issue, the $JUPYTERHUB_SERVICE_URL environment variable needs to be properly set before running the command to start the Jupyter notebook server within the Docker container.

### Additional information

What is the right docker command or the right docker-compose.yml file to properly start the container and provide the service?

**Comment by javsalgar** [comment]
Hi,

Please note that jupyter-base-notebook is meant to be used with the jupyterhub helm chart in Kubernetes. Could you try deploying the chart? Probably we should update the instructions clarifying it.

**Comment by JoaZ94** [comment]
i.e. the container cannot be used with docker.compose?

> Hola,
> 
> Tenga en cuenta que jupyter-base-notebook está diseñado para usarse con el gráfico de timón de jupyterhub en Kubernetes. ¿Podrías intentar desplegar el gráfico? Probablemente deberíamos actualizar las instrucciones aclarándolo.

i.e. the container cannot be used with docker.compose?

**Comment by javsalgar** [comment]
Hi,

It is possible to use JupyterHub in a docker-compose setup (connecting the notebook to jupyterhub) but this is not supported by default, you would need to check the upstream documentation on how to configure the hub

https://jupyterhub.readthedocs.io/en/latest/tutorial/getting-started/config-basics.html
