### ISSUE TITLE
[bitnami/openldap] Cannot load memberof module

### ISSUE THREAD

**Issue by AshtonKem** [bitnami/containers#42379]
### Name and Version

bitnami/openldap:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Load the following custom ldif file

```
dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModuleLoad: memberof
```

with the following env configuration

```
            - name: LDAP_ROOT
              value: dc=kemerling,dc=homelab
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: LDAP_CUSTOM_LDIF_DIR
              value: /ldifs-custom
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: /opt/openldap/certs/tls.crt
            - name: LDAP_TLS_KEY_FILE
              value: /opt/openldap/certs/tls.key
            - name: LDAP_TLS_CA_FILE
              value: /opt/openldap/certs/ca.crt
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-secret
                  key: adminpassword
```

### What is the expected behavior?

Should ideally load.

### What do you see instead?

segfault.

```
 04:07:37.73 INFO  ==> ** Starting LDAP setup **
 04:07:37.82 INFO  ==> Validating settings in LDAP_* env vars
 04:07:37.84 INFO  ==> Initializing OpenLDAP...
 04:07:37.87 INFO  ==> Creating LDAP online configuration
 04:07:37.87 INFO  ==> Creating slapd.ldif
 04:07:37.94 INFO  ==> Starting OpenLDAP server in background
 04:07:38.96 INFO  ==> Configure LDAP credentials for admin user
 04:07:39.28 INFO  ==> Configuring TLS
 04:07:39.30 INFO  ==> Adding LDAP extra schemas
 04:07:39.38 INFO  ==> Loading custom LDIF files...
 04:07:39.38 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
/opt/bitnami/scripts/libos.sh: line 346:    43 Aborted                 (core dumped) "$@" > /dev/null 2>&1
xargs: bash: exited with status 255; aborting
```

### Additional information

This may relate to #982.

**Comment by AshtonKem** [comment]
It's my understanding that ideally memberof is supposed to be compiled into the openldap binary? But my testing seems to indicate that this is not the case.

**Comment by FraPazGal** [comment]
Hello @AshtonKem, I reviewed https://github.com/bitnami/containers/issues/982 and it seems enabling it at compilation time is not required. Have you tried following my [colleague's recommendation](https://github.com/bitnami/containers/issues/982#issuecomment-1220354408) on that thread? Going by the users' response that should fix the issue

**Comment by AshtonKem** [comment]
It seems like my other ldif file was interacting with the memberof directive in a way that had me confused. Deleting my custom ldif and just running @fmulero's recommendation worked.

Thank you!

**Comment by clayrisser** [comment]
I created a custom build based on the bitnami/openldap image that supports the memberof module.

You can find it at the link below. Feel free to customize and fork.

https://github.com/clayrisser/docker-openldap
