### ISSUE TITLE
[bitnami/openldap] Failure to start when tls enabled

### ISSUE THREAD

**Issue by Horstexplorer** [bitnami/containers#42535]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. create certificates using acme.sh (either ec / rsa)
2. mount and configure certificates through env vars as described in the readme
3. run the container

### What is the expected behavior?

container should initialize successfully and create or update its configurations

### What do you see instead?
```
openldap  |  22:33:48.46 INFO  ==> ** Starting LDAP setup **
openldap  |  22:33:48.48 INFO  ==> Validating settings in LDAP_* env vars
openldap  |  22:33:48.49 INFO  ==> Initializing OpenLDAP...
openldap  |  22:33:48.50 INFO  ==> Creating LDAP online configuration
openldap  |  22:33:48.51 INFO  ==> Starting OpenLDAP server in background
openldap  |  22:33:49.52 INFO  ==> Configure LDAP credentials for admin user
openldap  |  22:33:49.53 INFO  ==> Configuring TLS
openldap exited with code 0
```
### Additional information

the container exits with code 0 and no additional error messages, regardless of the configured protocol level.
after a manual restart of the container it is able to start "successfully", however neither are the configured tls certificates working, nor was any scheme initialized.
this issue may relate to https://github.com/bitnami/containers/issues/36613, https://github.com/bitnami/containers/issues/27792

**Comment by javsalgar** [comment]
Hi!

Thank you for using Bitnami containers. Could you launch the container with `BITNAMI_DEBUG=true` to see what the error is?

**Comment by Horstexplorer** [comment]
Thank you for your response!
Starting the container with the debug flag enabled revealed a permission issue reading the key file. After changing the way the acme.sh container provided the certificates I managed to resolve this behaviour.
OpenLDAP now initializes and runs nicely :)
I assume there is no built in logic to restart slapd once the certificates are being renewed?
