### ISSUE TITLE
[bitnami/discourse] Enable DISCOURSE_CDN_URL for Discourse container

### ISSUE THREAD

**Issue by xgp** [bitnami/containers#42534]
### Name and Version

bitnami/discourse:3.0.5

### What is the problem this feature will solve?

The Bitnami Discourse image doesn't currently support the `DISCOURSE_CDN_URL` variable for specifying the CDN DNS name where assets will be served.

### What is the feature you are proposing to solve the problem?

Per https://meta.discourse.org/t/enable-a-cdn-for-your-discourse/14857 if you want to use a CDN to accelerate the serving of assets with Discourse, you must specify the `DISCOURSE_CDN_URL` variable as the DNS name used by your CDN to serve the assets. This will cause Discourse to prefix the assets with the appropriate DNS name so that they can be served by the CDN.

### What alternatives have you considered?

It would be possible to create CDN rules for the site's domain that pass through everything except `/assets`, `/uploads`, `/stylesheets`, but this is error prone, and assumes the Discourse authors won't change the paths of assets in the future.

**Comment by jotamartos** [comment]
Hi @xgp,

Can you try setting the [cdn_url parameter](https://github.com/discourse/discourse/blob/main/config/discourse_defaults.conf#L122) and any other required one using the `DISCOURSE_EXTRA_CONF_CONTENT` env var in the Bitnami container? As you can see [here](https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-11/rootfs/opt/bitnami/scripts/libdiscourse.sh#L276), that content is added to the discourse.conf file
