### ISSUE TITLE
Mysql load timezone info tables

### ISSUE THREAD

**Issue by aszenz** [bitnami/containers#4273]
### Name and Version

bitnami/mysql

### What is the problem this feature will solve?

On initial start there is no way to specify timezone as `Europe/Amsterdam` or named timzones in the mysql config file without loading the timezone information into the mysql which requires server to be already started.

### What is the feature you are proposing to solve the problem?

The simplest solution is to have the timzone information in the mysql db by default

**Comment by corico44** [comment]
Hi @aszenz

Thanks for reporting it.

Unfortunately we have a lot of things on our plate currently. Would you be open to contributing these changes? We would gladly help with the review and release of such changes, if you were able to.
