### ISSUE TITLE
ctlscript.sh unavailable

### ISSUE THREAD

**Issue by philion** [bitnami/containers#42966]
### Name and Version

bitnami/redmine

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Following directions to configure SMTP in the redmine container:
https://docs.bitnami.com/virtual-machine/apps/redmine/configuration/configure-smtp/
There is a call to "restart the services following [these instructions](https://docs.bitnami.com/virtual-machine/apps/redmine/administration/control-services/).

Those instructions call for `/opt/bitnami/ctlscript.sh`, which I cannot find on the redmine container, anywhere on the Bitnami site or on github.

I cannot tell if this is a documentation problem (there is another, undocumented way to restart the cluster with new SMTP settings), or if the tool was left out by accident. As yet, I've haven't been able to get redmine to send mail, and I'm still trying to track down logs to explain why not.

### What is the expected behavior?

Documentation accurately reflects configuration and restart process, and the tools are available in the documented locations.

### What do you see instead?

There is no ctlscript.sh (anywhere on the container) to restart the container, thus no way to configure STMP services, thus no email sent via SMTP.

**Comment by philion** [comment]
Additional info: I'm using the Bitnami container from https://github.com/bitnami/containers/tree/main/bitnami/redmine#how-to-use-this-image

This calls for SMTP to be configured via ENV. But there are no instructions for restarting the cluster, and various combinations of `docker compose restart/down/up/etc` didn't seem to pick up the changes in docker-compose.yml.

**Comment by carrodher** [comment]
Please note the documentation you refer to is related to VMs and the mentioned script is not present in the container images.
There is not equivalent script for containers since it should be restarted using the regular commands provided by Docker, docker-compose, or the tool used to deploy the containers.

Regarding the issue with SMTP, did you try deploying it from scratch with the required env. vars so no restart should be needed?

**Comment by philion** [comment]
My first attempt was to deploy using only env vars, but I could never see any change reflected in the container, and mail was not sent.

I was able to get SMTP working only with modifying the /bitnami/redmine/confg/configuration.yml directly (which is linked into the redmine volume). 

HOWEVER: There are only 2 files linked like this:
```
lrwxrwxrwx 1 root    root    41 Aug  1 04:55 configuration.yml -> /bitnami/redmine/config/configuration.yml
lrwxrwxrwx 1 root    root    36 Aug  1 04:55 database.yml -> /bitnami/redmine/config/database.yml
```
So there's no way to change any other settings, like those needed to receive email, or setting up parallel rake jobs (see https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Schedule-email-receiving-with-Rufus-Scheduler).

I can't see any way to change these files (anything in config/*) without completely rebuilding the container and removing all of the indirection that the bitnami container is introducing.

Can you suggest any method of POPing or IMAPing email that will work in the bitnami redmine container? Anything I've tried from https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails gets destroyed out by `docker compose down`.

**Comment by philion** [comment]
Further note that bitnami provides documentation for:
https://docs.bitnami.com/general/apps/redmine/configuration/configure-incoming-email/
https://docs.bitnami.com/general/apps/redmine/configuration/configure-scheduler/

But when following these instructions (which seem reasonable on a standard server):
```
root@xyx:/opt/bitnami/redmine# sudo crontab -e
bash: sudo: command not found
root@xyx:/opt/bitnami/redmine# crontab -e
bash: crontab: command not found
```
So even if I want to install, edit, update config (or anything else) on the container directly, it's not possible.
