### ISSUE TITLE
[bitnami/wordpress-nginx] wp-config.php presence is not checked when symlink exists

### ISSUE THREAD

**Issue by timofey-drozhzhin** [bitnami/containers#4314]
### Name and Version

bitnami/wordpress-nginx:6

### What steps will reproduce the bug?

1. Spin up a new container.
2. The system will create `/bitnami/wordpress/wp-config.php` and a symlink in `/opt/bitnami/wordpress/wp-config.php`
3. Delete `/bitnami/wordpress/wp-config.php` and restart the container
4. The container will fail to configure wp-config.php, because it will only check for the dangling symlink.

### What is the expected behavior?

Check for the existence of the actual file in `/bitnami/wordpress/wp-config.php`

### What do you see instead?

The app considers WordPress initialized, when in fact it isn't.

### Additional information

Issue https://github.com/bitnami/bitnami-docker-wordpress-nginx/pull/88 added a function that initializes WordPress upon a missing `/opt/bitnami/wordpress/wp-config.php` (symlink).

Issues #1055 and #1051 may be related, but it's hard to tell if the author's use case is the same.

**Comment by timofey-drozhzhin** [comment]
Hi @Mauraza, our `/bitnami/wordpress/` directory is persisted, while the `/opt/bitnami/wordpress` is part of the container. The persisted directory is shared between several containers.

On deployment, our system deletes the persisted `/bitnami/wordpress/wp-config.php` to allow the wp-config.php to regenerate with the updated settings. But the new `/bitnami/wordpress/wp-config.php` is not generated because all the containers still have the dangling symlink still attached in them `/opt/bitnami/wordpress/wp-config.php`.

I guess it doesn't makes sense to go in and manually delete the symlinks inside each container. Shouldn't the containers be instead watching the persisted directory for changes? Thanks!

**Comment by Mauraza** [comment]
Hi @timofey-drozhzhin,

That is one of the reasons because exist that symlink, if the user changes this file, will be updated. 
In your case, your system deletes the file,  maybe another approach could be to add a script to update the `/bitnami/wordpress/wp-config.php` with the new settings, or regenerate it.

But if you want to create a PR that checks if the symbolic link exists and if it doesn't, regenerate the file. We are more than happy to review it.

**Comment by timofey-drozhzhin** [comment]
Thanks! Closing this issue as we decided to go another route, and I won't be able to test going forward.
