### ISSUE TITLE
[bitnami/redis-cluster] README doesn't mention the overrides file

### ISSUE THREAD

**Issue by jamielinux** [bitnami/containers#4316]
### Name and Version

bitnami/redis-cluster:7.0.4

### What steps will reproduce the bug?

The [README.md](https://github.com/bitnami/containers/blob/196d1962ba8bab955b207e5d0d67c7db79c53437/README.md) for redis-cluster doesn't mention `overrides.conf`, which is mentioned in the [bitnami/redis README.md](https://github.com/bitnami/containers/blob/827737c104b5583c6c1c1226be72f9df101098f4/bitnami/redis/README.md#overriding-configuration).

The entrypoint scripts suggest that redis-cluster uses `overrides.conf` in the same way.

### What is the expected behavior?

The README mentions `overrides.conf`.

### What do you see instead?

No mention of `overrides.conf`.

**Comment by fmulero** [comment]
Thanks a lot @jamielinux, I've seen you also provided a PR. One of our engineers will provide you feedback soon
