### ISSUE TITLE
[bitnami/ghost] lack of update to release 5.8+ 

### ISSUE THREAD

**Issue by papalouf** [bitnami/containers#4320]
### Name and Version

bitnami/ghost:latest

### What steps will reproduce the bug?

From Docker (or with Docker-Compose), try to deploy a container pulling bitnami/ghost:latest image. 
-> image provide Ghost in release v5.7 (actual Ghost latest is v5.11).

### What is the expected behavior?

As Ghost released recently important updates via releases v5.8 and v5.9 , not be able to update to the last Ghost point release can be frustrating (even if I understand that major changes ask for more tests). 

### What do you see instead?

Be able to deploy a Ghost container on v5.8 or v5.9 at least (5.10 and 5.11 releases are more minor releases)

**Comment by fmulero** [comment]
Thanks @papalouf  for reporting it. We have a internal task to review the compilation process for the new Ghost versions. Unfortunately I can't give you an ETA

**Comment by Mauraza** [comment]
Hi @papalouf,

The new version was released:
```
docker pull bitnami/ghost:5.12.2
```

**Comment by matbgn** [comment]
Many thanks

(For me it's deployed and tested you can safely close this issue ;-)

**Comment by papalouf** [comment]
Hi @Mauraza , 

Thanks a lot for the notification ! I deployed and tested too this new version and seems to work perfectly :D 

Many thanks !!
