### ISSUE TITLE
[bitnami/kafka] how to get KAFKA_KRAFT_CLUSTER_ID 

### ISSUE THREAD

**Issue by EzrealerQAQ** [bitnami/containers#4325]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

start a docker with kraft kafka,so how to get KAFKA_KRAFT_CLUSTER_ID  ,thanks

### What is the feature you are proposing to solve the problem?

start a docker with kraft kafka,so how to get KAFKA_KRAFT_CLUSTER_ID  ,thanks

### What alternatives have you considered?

start a docker with kraft kafka,so how to get KAFKA_KRAFT_CLUSTER_ID  ,thanks

**Comment by javsalgar** [comment]
Hi,

How did you launch your Kafka instances? Could you provide more details? Did you try setting the environment variable?
