### ISSUE TITLE
[bitnami/pytorch] Increased image size (2x) for local build of bitnami/pytorch

### ISSUE THREAD

**Issue by mapa17** [bitnami/containers#43318]
### Name and Version

bitnami/pytorch

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Env: Arch Linux 6.2.8 x86_64 host system
- Downloading the bitnami/container registry
- Docker build of the  bitnami/container/pytorch image

The resulting image is double the size (2.6GB) compared to the docker-hub image bitnami/pytorch:2.0.1.

### What is the expected behavior?

I would expect the newly create image to have a similar size like the docker-hub image.

### What do you see instead?

Increase image size

### Additional information

I need to bump the python version used in the image from 3.8.4 to 3.11.X in order to make use of python functionalities available in 3.11.

If possible I want to use the bitnami python package 3.11.4-4.

**Comment by mapa17** [comment]
I think I identified the issue. As part of the pytorch docker build two components/packages are installed.
* "python-3.8.17-4-linux-${OS_ARCH}-debian-11" 
* "pytorch-2.0.1-6-linux-${OS_ARCH}-debian-11" 

I changed the pythion version to 3.11.4-4 but have not toched the other package. The other package will install pytorch libraries for 3.8. Causing the 3.11 to be most likely not working with pytorch.
* "python-3.11.4-4-linux-${OS_ARCH}-debian-11" 

Is there a way to browse the bitname package registry if there is a pytorch version for python 3.11?

**Comment by javsalgar** [comment]
Hi,

Did you squash the image in the docker build process? We are using `--squash`

**Comment by mapa17** [comment]
I tried adding this too, but as I wrote before. The real issue are the pytorch related libraries in the 
* "pytorch-2.0.1-6-linux-${OS_ARCH}-debian-11"

package that are for python 3.8.
Are there newer version of this package available? Is there a way to browse available packages?

**Comment by mapa17** [comment]
Or can i find some instructions on how this package was build? If i try to install pytorch with all its cuda dependencies from a bitnami/python-3.11.4 image the resulting image is 5.8gb in size with only the cuda libraries being several gb big.

I am really curries how bitnami is able to build such a small pytorch image.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that we are currently using python 3.8 at the build process, in which we simply follow the official instructions for building pytorch. Probably, as you are updating the python version, there are some incompatibilities forcing to rebuild some extensions, but this is just a guess.

**Comment by mapa17** [comment]
Thank you for the clarification. Are the scripts used for building the pytorch package public?

**Comment by javsalgar** [comment]
Hi,

I'm afraid that it is currently part of our internal repos, but essentially it is:

```
pip install astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses
python setup.py install
git clone https://github.com/pytorch/vision.git .
pip install torch==<VERSION_HERE>+cpu torchvision torchaudio
```

**Comment by mapa17** [comment]
For anyone finding this in the future. I would recommend to have a look at the docker build process used in TorchServe https://github.com/pytorch/serve/tree/master/docker
They build a toolset to build docker images with cuda for CPU and GPU and different python versions. While keeping the images relatively small.
