### ISSUE TITLE
[bitnam/openldap] Support for pwdUseCheckModule

### ISSUE THREAD

**Issue by ajython** [bitnami/containers#43490]
### Name and Version

bitnami/opendap:2.6.3

### What is the problem this feature will solve?

Support for this module will provide the ability to quality check password using ppm.so module. 

### What is the feature you are proposing to solve the problem?

Since openldap2.6 ppm.so module needs to be loaded in slapd.conf file which bitnami image doesn't support. The ability to load this module somehow would help in enforcing strict password security.

**Comment by javsalgar** [comment]
Hi,

Do you have any instructions on how to add build this module in OpenLDAP?
