### ISSUE TITLE
[bitnami/symfony] SQLSTATE[HY000] [1045] Access denied for user

### ISSUE THREAD

**Issue by cleargoal** [bitnami/containers#43542]
### Name and Version

bitnami/symfony version 2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. clone and install the package.
2. run all commands by installation instructions
3. As a result the folder 'my-project' was created
4. run `php bin/console doctrine:schema: create` as described in Symfony docs

### What is the expected behavior?

Expected a DB schema creation

### What do you see instead?

I see error 

> An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'bitnami'@'172.25.0.1' (using password: YES) 

### Additional information

I think it happened because in docker-compose there is the parameter `ALLOW_EMPTY_PASSWORD=yes` and I started the container without a DB password, like this in Symfony .env
`DATABASE_URL="mysql://bitnami:''@127.0.0.1:3306/bitnami?serverVersion=10.11.2-MariaDB&charset=utf8mb4"`
 Also, one strange thing is that inside the project's folder, there is one more file docker-compose created automatically and it contains DB other than parent docker-compose - Postgres.

My question is only - how to create a DB scheme in this mess. And what DB it will be - Maria or Postgres?
I hope the parent docker-compose may be the main.
Also, I think it will be better for me to use a DB password. 
What do I have to write in docker-compose for the container can know a password for a DB user?

**Comment by joancafom** [comment]
Hi @cleargoal 

I'm sorry but I could not reproduce your issue:

```
$ cat docker-compose.yml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/symfony:6.3
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=bn_myapp
      - SYMFONY_DATABASE_NAME=bitnami_myapp
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb

$ docker-compose up -d
$ docker exec -it myapp_myapp_1 bash
root@c73246219e0a:/app# php bin/console doctrine:schema:create
 [OK] No Metadata Classes to process.

```

**Comment by cleargoal** [comment]
I changed the name of... (I don't know what ) and the server port:
```  
symfo1:
    image: docker.io/bitnami/symfony:6.2
    ports:
      - '8021:8021'
    environment:
```

May it be a cause of error?
