### ISSUE TITLE
[Google Cloud/MediaWiki] Include a default mediawiki logging configuration in the image

### ISSUE THREAD

**Issue by ILikePlayingGames** [bitnami/containers#43916]
### Name and Version

bitnami/mediawiki:1.40.0-3

### What is the problem this feature will solve?

Debug logs are often required when setting up a wiki or installing plugins to diagnose issues. Having a default logging configuration available will reduce the time needed to setup a new instance. This would be especially helpful for people new to MediaWiki and Linux, who might not know how to set up logs.

### What is the feature you are proposing to solve the problem?

Can you please make a folder at `/var/log/mediawiki` that is writable by the `daemon` account mediawiki is running as? After that, can you please add the log groups from the [MediaWiki log groups article](https://www.mediawiki.org/wiki/Manual:How_to_debug#Creating_custom_log_groups) to the `LocalSettings.php`? The settings can be commented out by default since the logs they generate can get quite large over time.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ILikePlayingGames** [comment]
Sorry, I'm currently busy with other projects and I do not have any experience with containers so I can't make a PR.
