### ISSUE TITLE
[bitnami/appsmith] Update to the Latest Version (1.9.31)

### ISSUE THREAD

**Issue by muharihar** [bitnami/containers#43911]
### Name and Version

appsmithorg/appsmith

### What is the problem this feature will solve?

Kindly please update to the Latest Version 1.9.31 so we can get the latest feature

https://github.com/appsmithorg/appsmith/releases/tag/v1.9.31

### What is the feature you are proposing to solve the problem?

a tons of new features, already shiped:

- UI fixes for the Signposting component (https://github.com/appsmithorg/appsmith-ee/pull/1912)
- Fixes an issue with redis connections when deploying appsmith via helm (https://github.com/appsmithorg/appsmith/pull/25689)
- UI fixes for Appsmith AI signposting (https://github.com/appsmithorg/appsmith/pull/25659)
- Fixed missing api call for product alerts (https://github.com/appsmithorg/appsmith-ee/pull/1955)
- Fixes a problem with connecting to Redis that requires authentication. (https://github.com/appsmithorg/appsmith/pull/25828)
- Instance admin can now delete/read users (https://github.com/appsmithorg/appsmith-ee/pull/1943)
- Fusion charts replaced with Echarts (https://github.com/appsmithorg/appsmith/pull/24249)
- Show MongoDB alert only when it is outdated (https://github.com/appsmithorg/appsmith/pull/25611)
- Improved error validation for select widget (https://github.com/appsmithorg/appsmith/pull/25734)
- Improvements to SCIM flow (https://github.com/appsmithorg/appsmith-ee/pull/1940)
- Fixes stale lock file issue with git connected apps (https://github.com/appsmithorg/appsmith/pull/25504)
- Fixes an issue with navigation settings on git import (https://github.com/appsmithorg/appsmith/pull/25709)
- Application name wasn't showing up at times (https://github.com/appsmithorg/appsmith/pull/25672)
- Fixes an app crash while editing an oauth api datasource (https://github.com/appsmithorg/appsmith/pull/25704)
- cUrl import fails when url contains curly brackets around variable names (https://github.com/appsmithorg/appsmith/pull/25522)
- Datasource reauthorisation Required to Authenticate API After Update (https://github.com/appsmithorg/appsmith/pull/25550)
- SCIM ux fixes (https://github.com/appsmithorg/appsmith-ee/pull/1910)

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by muharihar** [comment]
fyi, the latest version already shipped at docker hub,

https://hub.docker.com/r/bitnami/appsmith/tags

`[1.9.32](https://hub.docker.com/layers/bitnami/appsmith/1.9.32/images/sha256-5a3cccb6f2e18ef49588fe20a637ff997d204a5bdd27772340a654b326230c1f?context=explore)
`

I thing we can close this request, thanks a lot team !!!
