### ISSUE TITLE
[bitnami/moodle] Deficient documentation about volumes for Moodle (All versions)

### ISSUE THREAD

**Issue by povserok** [bitnami/containers#43947]
### Name and Version

bitnami/moodle:4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. **Follow instructions in README.MD** to create network, volumes, database, and than a Moodle container (copied from README.MD):
```
docker run -d --name moodle \
  -p 8080:8080 -p 8443:8443 \
  --env ALLOW_EMPTY_PASSWORD=yes \
  --env MOODLE_DATABASE_USER=bn_moodle \
  --env MOODLE_DATABASE_PASSWORD=bitnami \
  --env MOODLE_DATABASE_NAME=bitnami_moodle \
  --network moodle-network \
   --volume moodle_data:/bitnami/moodle \
  bitnami/moodle:latest
```

2. Login to Moodle and upload a picture through UI, i.e. course icon.
 _Image gets saved into moodle data directory - /bitnami/moodledata...)_

3. Delete container for Moodle
4. Start a new container for Moodle using existing volume
5. Picture is not displayed anymore as /bitnami/moodledata was not persisted

### What is the expected behavior?

Recreating container when using volumes should not cause loosing data.

README.MD should be updated to be consistent about using volumes and backup strategy. 

### What do you see instead?

All uploaded files are lost.

### Additional information

Moodle uses two storage directories: `/bitnami/moodle` (for source code) and `/bitnami/moodledata` (for file storage). 
**README.md** on several places (including instruction to backup and restore) incorrectly suggests only to backup /bitnami/moodle. Either volume should point to `/bitnami`, or two volumes should be used - one for each Moodle storage directory.

**Comment by povserok** [comment]
I tested upgrading process and learned more issues with mounting volumes. 

The way scripts in image are written, they check if `/bitnami/moodle` directory is empty. This check serves as an indicator, if installation (copying and preparing files from /opt and initializing database) should proceed. If the directory is not empty, the script skips these steps and restores existing installation. This is a problem itself. For instance, consider a scenario where you initiate a container from version 4.1.3with a volume mounted at `/bitnami`. Next, you want to upgrade to 4.1.4. You remove  the current container and launch a new one while retaining the mounted volume. Moodle starts, but since has already undergone initialization, skips installation and normally starts. Consequently, you end up with a newer image (with newer libraries), yet running on outdated code. At the very least, the scripts should prevent this, stop the container and give you some error that you cannot run old code with newer image.

The only path I found to update the container is:
1. to have empty directory for code (`/bitnami/moodle`), so it triggers initialization and copies new files,
2. pass `MOODLE_SKIP_BOOTSTRAP=true` to skip database initialization.

Conceptually the optimal approach would be to consistently run the latest code. This can be achieved by exclusively mounting `/bitnami/moodledata`, and using `MOODLE_SKIP_BOOTSTRAP=true`. However, that is probably not a good idea for all cases due to Moodle's way of messing with the code (users can upload plugins through UI), there can be other manual steps required in the future, etc. I imagine that this (reconstructing the code with new plugins) is problem even for Moodle administrators even in non-Docker environments.

**Comment by povserok** [comment]
Thanks @joancafom for your feedback. Happy to hear that the logic seems correct.

Sure, I can prepare a PR for that.

> When the MOODLE_SKIP_BOOTSTRAP is provided, the DB schema is upgraded. 
I think this is not correct. My understanding is that this parameter causes to skip database initialization (initial creation of tables etc.). Because `/bitnami/moodle` is empty, container thinks it is a fresh install, but in case of upgrades, it is not, so initialization should be skiped. Updating of database schema happens on each container start. In case of repeated container restarts updating does not do anything-it just figures out that it is already up-to-date. However, in case of first start after updating Moodle code, this causes to update database schema to a new version. 

I am missing one more feedback from my previous comment: What do you think about that the scripts should prevent running containers where a code is older than the one in image? For example, you create a new container from image for Moodle 4.1.4, but you mount an exising volume to `/bitnami/moodle`, containing code for version 4.1.3. Currently scripts do not care, they just run it.

**Comment by joancafom** [comment]
>I think this is not correct. My understanding is that this parameter causes to skip database initialization (initial creation of tables etc.)

Yes, indeed this is the correct interpretation of the parameter. I was just pointing out that when the initialization is skipped, the logic updates the DB schema (but not implying that `MOODLE_SKIP_BOOTSTRAP` was conceived for this matter), sorry for the confusion! 

> What do you think about that the scripts should prevent running containers where a code is older than the one in image?

My thoughts on this is that documentation is the key: these are not just some automatic or arbitrary scenarios, these are scenarios in which the end-user has actively taken action to perform a change (in this case, an upgrade). With the right information on how to proceed, it should be nice and simple 😁 .

Regarding specifically preventing running the container when there is a version mismatch, I think it is a little bit too of an aggressive measure. I would go with something more informative such as printing a warning. Nevertheless, it might be tricky to identify this scenario, so not sure if it is worth it.
