### ISSUE TITLE
[bitnami/laravel] I want to make .htaccess effective

### ISSUE THREAD

**Issue by emura-takashi** [bitnami/containers#44139]
### Name and Version

bitnami/laravel:9.1.1-debian-10-r5

### What is the problem this feature will solve?

Laravel WEB application built with Docker image of bitnami/laravel
Deployed to Google's Cloud Run environment and deployed a website.
Since .htaccess is not enabled in that app, I want to enable it.
Specifically, I want to set Allow-overirde in Apache settings to All to enable .htaccess.

### What is the feature you are proposing to solve the problem?

In bitnami/laravel, even if you look at the official document and GitHub source,
I don't know how to respond because there is no case where Apache is set.

```Dockerfile
# Install node modules
FROM bitnami/laravel:9.1.1-debian-10-r5 as node-modules

WORKDIR /app

COPY ./package.json ./package.json

RUN npm i


# Install composer modules
FROM bitnami/laravel:9.1.1-debian-10-r5 as composer-modules

WORKDIR /app

COPY ./composer.json ./composer.json
COPY ./composer.lock ./composer.lock

RUN composer install --ignore-platform-req=php --no-autoloader


# install cloud_sql_proxy
FROM bitnami/laravel:9.1.1-debian-10-r5 AS cloud-sql-proxy

RUN apt-get update && apt-get install wget -y
RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy


# Laravel container
FROM bitnami/laravel:9.1.1-debian-10-r5 as runner

ARG GCP_SQL_INSTANCE_CONNECTION_NAME=local

ENV SKIP_COMPOSER_UPDATE=true
ENV GCP_SQL_INSTANCE_CONNECTION_NAME $GCP_SQL_INSTANCE_CONNECTION_NAME

ENV PHP_ENABLE_OPCACHE true
ENV PHP_CLI_SERVER_WORKERS=160

WORKDIR /app

COPY --chown=bitnami:bitnami ./ ./

COPY --chown=bitnami:bitnami --from=composer-modules /app ./
RUN composer dump-autoload

# RUN echo "npm run prod" >> /opt/bitnami/scripts/laravel/run.sh

COPY --from=cloud-sql-proxy /usr/local/bin/cloud_sql_proxy /usr/local/bin/cloud_sql_proxy
RUN cat "cloud_sql_proxy_setup.sh" > "/opt/bitnami/scripts/laravel/run.tmp" && \
    cat "/opt/bitnami/scripts/laravel/run.sh" >> "/opt/bitnami/scripts/laravel/run.tmp" && \
    cat "/opt/bitnami/scripts/laravel/run.tmp" > "/opt/bitnami/scripts/laravel/run.sh"

COPY --chown=bitnami:bitnami --from=node-modules /app ./

RUN sed -i "/chown -R bitnami:bitnami \/app/d" "/opt/bitnami/scripts/laravel/setup.sh"
```

### What alternatives have you considered?

Add ENV APACHE_ALLOW_OVERRIDE ALL in Dockerfile or I added in .htaccess directly under /app/public and tried AllowOverride All, but it didn't work.

**Comment by rafariossaa** [comment]
Hi,
  There is not apache in laravel container. You could check that in `run.sh` php is started serving on the configured port.
  If you need an apache, for example you could launch one container configured as reverse proxy to the laravel container.

**Comment by emura-takashi** [comment]
@rafariossaa 
Thank you for answering.

I was able to confirm that this Laravel container is running on port 8000.

>If you need an apache, for example you could launch one container configured as reverse proxy to the laravel container.

What exactly do you want this to do? What I want to achieve is to know how to configure Apache. I want to configure a file like httpd.conf.

**Comment by rafariossaa** [comment]
Hi,
  I am not sure what you need to configure on Apache, but for example, if you need to add redirection rules or things like that, you could use an apache container with your configuration and add also rules to act as a reverse proxy to a laravel container too.

**Comment by emura-takashi** [comment]
Hi,
I would like to set Allowoverride in Apache configuration to All.

> you could use an apache container with your configuration and add also rules to act as a reverse proxy to a laravel container too.

I would like to know the specific method for setting this.

**Comment by rafariossaa** [comment]
Sorry for the delay.

What you would need to do is something similar to what was done here #27525, but you would need too to add `ProxyPass` and `ProxyPassReverse` directives to the apache configuration.
I am not completely sure if it is going to work in you case, as it depends on the directives in the `.htaccess`. Have into account that in other deployments where apache + mod_php is used, the architecture is different to the one I am proposing.

**Comment by emura-takashi** [comment]
Thank you for answering. I understand the content. From the answers, it seems that .htaccess cannot be used with bitnami/laravel, so I will use DockerImage like bitnami/apache.

**Comment by rafariossaa** [comment]
You are welcome.
I am closing this issue, if you have further issues/questions don't hesitate to open one github issue.
