### ISSUE TITLE
[bitnami/wordpress-nginx] Problem with wordpress-nginx image with Kubernetes Ingress + SSL.

### ISSUE THREAD

**Issue by r4m-mikhailt** [bitnami/containers#44197]
### Name and Version

registry.hub.docker.com/bitnami/wordpress-nginx:*

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy deployment in Kubernetes with this docker image.
2. Deploy simple service resource.
3. Deploy ingress resource with correct TLS section (now I use self-signed cert). Ingress looks at the HTTP port in the container.
4. Try to visit https://mycite.com

### What is the expected behavior?

Cite works correctly with HTTPS. 

### What do you see instead?

Next, you can see errors like this in your console:
```
Mixed Content: The page at 'https://mycite.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://mycite.com/wp-includes/blocks/navigation/style.min.css?ver=6.2.2'. This request has been blocked; the content must be served over HTTPS.
```

### Additional information

All settings like WORDPRESS_ENABLE_HTTPS or WORDPRESS_SCHEME don't work. But all normal with Apache image and same configuration: registry.hub.docker.com/bitnami/wordpress:*

WP_SITEUR and WP_HOME also don't work.

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami WP NGINX container image, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by corico44** [comment]
I'm glad you could solve it. If you think the bug can be fixed, we encourage you to open a PR and we will be happy to review it!

**Comment by tim-hub** [comment]
I got the same issue as well.

Have to change to official wordpress-apache image to make it work

**Comment by corico44** [comment]
Did you try this workaround @tim-hub?
> Have you tried adding WORDPRESS_ENABLE_REVERSE_PROXY=yes? WORDPRESS_ENABLE_HTTPS=yes should also be present if you expect HTTPS.

**Comment by tim-hub** [comment]
> Did you try this workaround @tim-hub?
> 
> > Have you tried adding WORDPRESS_ENABLE_REVERSE_PROXY=yes? WORDPRESS_ENABLE_HTTPS=yes should also be present if you expect HTTPS.

I did, but it did not help.

**Comment by rafariossaa** [comment]
Hi,
  One detail, when you tried with the suggested environment variables, did you start it all from scratch (aka removing the persisted volumes) ?
  I am asking because if data is detected the containers won't be configured again. WP stores the references to the content in the database, so even if you change it to https some of the content would be still served as http.

**Comment by jonesy16** [comment]
Same issue for me.

**Comment by rafariossaa** [comment]
Could you share the yamls you are using for the deployment ? 
I would like to try to reproduce this on my side.

**Comment by namkazt** [comment]
the problem is `wp-config.php` only generated for first time, so if it ran first time with wrong setup it stay the same.

the setup should be used on initialize

```php
WORDPRESS_ENABLE_HTTPS: "yes"
WORDPRESS_SCHEME: "https"
WORDPRESS_ENABLE_REVERSE_PROXY: "yes"
```

if you acidentially initialized then you need to manually edit `wp-config.php` file by `kubectl cp` command

1, copy your wp-config.php to local and start edit
2, copy this after line `define( 'FS_METHOD', 'direct' );`
```php
/**
 * Handle potential reverse proxy headers. Ref:
 *  - https://wordpress.org/support/article/faq-installation/#how-can-i-get-wordpress-working-when-im-behind-a-reverse-proxy
 *  - https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
 */
if ( ! empty( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
	$_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}
if ( ! empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
	$_SERVER['HTTPS'] = 'on';
}
```
3, change HOME AND SITEURL to https
```php
define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/' );
define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/' );
```
4, copy back modified `wp-config.php` to pod to override one in pvc

restart deployment
