### ISSUE TITLE
[bitnami/redis-cluster] is failing

### ISSUE THREAD

**Issue by skyckp123** [bitnami/containers#44253]
### Name and Version

bitnami/redis-cluser:6.2

### What architecture are you using?

None

### What steps will reproduce the bug?

We are running redis cluster in kubernetes environment.

In some cases, when VM is rebooted, we are seeing that redis is not starting with the error "Un recoverable error: corru pted cluster config file."

When this happens, we see that nodes .conf file is empty in the mounted directory.
This issue is happening very rarely.

We are not sure whether nodes .conf file is emptied by the redis_cluster_update_ips method or the file is emptied during the VM restart process.

### What is the expected behavior?

Redis-cluster should be up and running.

### What do you see instead?

Redis cluster is continuously restarting with the error message "Unr ecoverable error: corru pted cluster config file."

**Comment by carrodher** [comment]
This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
