### ISSUE TITLE
Can I install the extension "pgroonga" under the postgresql-repmgr container

### ISSUE THREAD

**Issue by jadestoner** [bitnami/containers#44280]
### Name and Version

bitnami/postgresql-repmgr

### What is the problem this feature will solve?

 I want to install the extension "pgroonga" under the postgresql-repmgr container

### What is the feature you are proposing to solve the problem?

 I want to install the extension "pgroonga" under the postgresql-repmgr container

**Comment by jadestoner** [comment]
When I install the pgroonga extension，prompt ” postgresql-14-pgdg-pgroonga : Depends: postgresql-14 but it is not installable“. 

But I have build the postgresql-repmgr and make it run normally. I want to know there is no postgresql-14  is our container?

Thanks for your time.
Best Wishes.

**Comment by aoterolorenzo** [comment]
Hi @jadestoner 

Could you provide the commands and outputs of steps you are following?
