### ISSUE TITLE
Cannot setup elasticsearch with SSL in docker compose

### ISSUE THREAD

**Issue by nailgoksel** [bitnami/containers#44295]
### Name and Version

bitnami/elasticsearch:8.9.0

### What architecture are you using?

None

### What steps will reproduce the bug?

In docker desktop

When I want to start a docker container within a multi-node cluster with following xpack configuration:
```
xpack.security.enabled=true
xpack.security.http.ssl.enabled=true
xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
xpack.security.transport.ssl.enabled=true
xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
xpack.security.transport.ssl.verification_mode=certificate
xpack.license.self_generated.type=${LICENSE}
```
It does not start elastic instance with SSL enabled.

Above config is tested with original elasticsearch image but fails with bitnami image

What is wrong with my configuration?

Are you using any custom parameters 

### What is the expected behavior?

I need to see all docker containers within elastic cluster to communicate with TLS

### What do you see instead?

Cluster members still communicate with HTTP

**Comment by mdhont** [comment]
Do the logs mention any error? Could you check it? Where are you adding the xpack configuration options?

**Comment by nailgoksel** [comment]
Hi,

I am adding this configuration to my docker-compose.yml file like I did with original elasticsearch environment like below:

  es01:
    depends_on:
      setup:
        condition: service_healthy
    **image: bitnami/elasticsearch:8.9.0**
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=es01,es02,es03
      - ELASTICSEARCH_NODE_NAME=es01
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      **- xpack.security.enabled=true**
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

Above configuration with elasticsearch original images works well as I said.

When I run same docker compose with bitnami images, in the container logs I see following:

[2023-08-11T11:52:13,049][INFO ][o.e.p.PluginsService     ] [es01] loaded module [x-pack-security]

which is normal. after above log I see:

[2023-08-11T11:52:20,717][INFO ][o.e.x.s.Security         ] [es01] Security is disabled 

which was shown as "enabled" when I use original elastic image.

Thank you

Best

**Comment by nailgoksel** [comment]
Additional information:

When I go /opt/bitnami/elasticsearch/config/elasticsearch.yml under container, xpack security is disabled even I configure as true in docker.compose file

![image](https://github.com/bitnami/containers/assets/50969561/79042be5-3361-488b-b671-dc01bf16bda4)

**Comment by nailgoksel** [comment]
I also tried to override configuration file like defined here:
https://github.com/bitnami/containers/tree/main/bitnami/elasticsearch#configuration%20file
But I get "ERROR: Elasticsearch exited unexpectedly" error 
Any thoughts how to configure SSL/TLS with bitnami containers using xpack?

Best

**Comment by mdhont** [comment]
Could you share a docker-compose file that reproduces the issue so I can try to reproduce it on my side?
