### ISSUE TITLE
SonarQube not starting (from compose up)

### ISSUE THREAD

**Issue by jstafford5380** [bitnami/containers#44306]
### Name and Version

bitnami/sonarqube

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use compose file which is provided [on docker hub](https://raw.githubusercontent.com/bitnami/containers/main/bitnami/sonarqube/docker-compose.yml)
2. `docker-compose up -d`

### What is the expected behavior?

When browsing to `http://localhost` or `http://127.0.0.1`, SonarQube should load

### What do you see instead?

'Empty http response'

## Container Log
```
docker logs 26b513fd9680
sonarqube 16:09:54.60 
sonarqube 16:09:54.60 Welcome to the Bitnami sonarqube container
sonarqube 16:09:54.60 Subscribe to project updates by watching https://github.com/bitnami/containers
sonarqube 16:09:54.60 Submit issues and feature requests at https://github.com/bitnami/containers/issues
sonarqube 16:09:54.60 
sonarqube 16:09:54.61 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 16:09:54.63 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sonarqube 16:09:54.63 INFO  ==> Creating SonarQube configuration
sonarqube 16:09:54.66 INFO  ==> Trying to connect to the database server
sonarqube 16:09:54.67 INFO  ==> Ensuring SonarQube directories exist
sonarqube 16:09:54.68 INFO  ==> Starting SonarQube in background
sonarqube 16:09:54.69 INFO  ==> Waiting for SonarQube to start...
grep: /opt/bitnami/sonarqube/logs/sonar.log: No such file or directory
sonarqube 16:14:55.29 ERROR ==> Could not find entry "SonarQube is (up|operational)" in /opt/bitnami/sonarqube/logs/sonar.log after 300 retries
```
## SonarQube Log
```
sonarqube@26b513fd9680:/opt/bitnami/sonarqube/logs$ cat sonar.log
2023.08.11 16:09:54 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/bitnami/sonarqube/temp
2023.08.11 16:09:54 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:38337]
2023.08.11 16:09:54 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [/opt/bitnami/sonarqube/elasticsearch]: /opt/bitnami/java/bin/java -Xms4m -Xmx64m -XX:+UseSerialGC -Dcli.name=server -Dcli.script=./bin/elasticsearch -Dcli.libs=lib/tools/server-cli -Des.path.home=/opt/bitnami/sonarqube/elasticsearch -Des.path.conf=/opt/bitnami/sonarqube/temp/conf/es -Des.distribution.type=tar -cp /opt/bitnami/sonarqube/elasticsearch/lib/*:/opt/bitnami/sonarqube/elasticsearch/lib/cli-launcher/* org.elasticsearch.launcher.CliToolLauncher
2023.08.11 16:09:54 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2023.08.11 16:10:00 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 78
2023.08.11 16:10:00 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
2023.08.11 16:10:00 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```
### Additional information

The log seems to suggest that ElasticSearch is missing so it shuts down. I'm not sure if that's bundled with or built-in to SonarQube or if a service is missing from the compose file.

**Comment by jkessel** [comment]
Exactly the behavior that I am experiencing myself, currently.
I've used the following command:
`curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/sonarqube/docker-compose.yml > docker-compose.yml
docker-compose up -d`

**Comment by migruiz4** [comment]
Hi there!

Could you please check the content of `/opt/bitnami/sonarqube/logs/es.log` inside the container?

There you should be able to find any issues with Elasticsearch initialization.

**Comment by jkessel** [comment]
Ist more or less repeats this block:

2023.08.16 12:02:14 INFO  es[][o.e.n.Node] version[8.7.0], pid[281], build[tar/09520b59b6bc1057340b55750186466ea715e30e/2023-03-27T16:31:09.816451435Z], OS[Linux/5.15.90.1-microsoft-standard-WSL2/amd64], JVM[BellSoft/OpenJDK 64-Bit Server VM/17.0.8/17.0.8+7-LTS]
2023.08.16 12:02:14 INFO  es[][o.e.n.Node] JVM home [/opt/bitnami/java], using bundled JDK [false]
2023.08.16 12:02:14 INFO  es[][o.e.n.Node] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/opt/bitnami/sonarqube/temp, -XX:ErrorFile=/opt/bitnami/sonarqube/logs/es_hs_err_pid%p.log, -Xlog:disable, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djna.tmpdir=/opt/bitnami/sonarqube/temp, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=COMPAT, -Dcom.redhat.fips=false, -Des.enforce.bootstrap.checks=true, -Xmx512m, -Xms512m, -XX:MaxDirectMemorySize=256m, -XX:+HeapDumpOnOutOfMemoryError, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.distribution.type=tar, --module-path=/opt/bitnami/sonarqube/elasticsearch/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [aggregations]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [analysis-common]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [apm]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [blob-cache]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [lang-painless]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [old-lucene-versions]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [parent-join]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [reindex]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [x-pack-aggregate-metric]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [x-pack-core]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [x-pack-profiling]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] loaded module [x-pack-security]
2023.08.16 12:02:15 INFO  es[][o.e.p.PluginsService] no plugins loaded
2023.08.16 12:02:16 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/ (overlay)]], net usable_space [897.4gb], net total_space [1006.8gb], types [overlay]
2023.08.16 12:02:16 INFO  es[][o.e.e.NodeEnvironment] heap size [512mb], compressed ordinary object pointers [true]
2023.08.16 12:02:16 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [Qv02DZ4_QXW6QxEdMTmpKA], cluster name [sonarqube], roles [data_cold, data, remote_cluster_client, master, data_warm, data_content, transform, data_hot, ml, data_frozen, ingest]
2023.08.16 12:02:17 INFO  es[][o.e.x.p.ProfilingPlugin] Profiling is enabled
2023.08.16 12:02:17 INFO  es[][o.e.x.s.Security] Security is disabled
2023.08.16 12:02:17 INFO  es[][o.e.t.n.NettyAllocator] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=512mb}]
2023.08.16 12:02:17 INFO  es[][o.e.i.r.RecoverySettings] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
2023.08.16 12:02:17 INFO  es[][o.e.d.DiscoveryModule] using discovery type [single-node] and seed hosts providers [settings]
2023.08.16 12:02:17 INFO  es[][o.e.n.Node] initialized
2023.08.16 12:02:17 INFO  es[][o.e.n.Node] starting ...
2023.08.16 12:02:17 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:40075}, bound_addresses {127.0.0.1:40075}
2023.08.16 12:02:18 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2023.08.16 12:02:18 ERROR es[][o.e.b.Elasticsearch] node validation exception
[1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
2023.08.16 12:02:18 INFO  es[][o.e.n.Node] stopping ...
2023.08.16 12:02:18 INFO  es[][o.e.n.Node] stopped
2023.08.16 12:02:18 INFO  es[][o.e.n.Node] closing ...
2023.08.16 12:02:18 INFO  es[][o.e.n.Node] closed

**Comment by migruiz4** [comment]
Hi @jkessel,

The error message in Elasticsearch logs points out that the Kernel value for `vm.max_map_count` is too low.

Elasticsearch requires the setting `vm.max_map_count=262144` in order to run.

You can either modify the kernel setting temporarily `sysctl -w vm.max_map_count=262144` or permanently, by modifying its value at `/etc/sysctl.conf`.

**Comment by jkessel** [comment]
Hi @migruiz4 , thanks for the hint!
I'm using Docker Desktop on Windows 10 and setting the vm.max_map_count did not work in the container (permission denied).
What did work for me is the following (given WSL is installed and integrated with Docker Desktop for Windows):
`wsl -d docker-desktop`
`sysctl -w vm.max_map_count=262144`

Thank you for your support, much appreciated!

@jstafford5380 , does this work for you, as well?

**Comment by migruiz4** [comment]
Thanks for the feedback @jkessel!

Two things regarding your message that I forgot to mention in my previous comment:
1. Yes, the configuration has to be set in the host, not inside the container.
2. The method will vary in Windows/Linux/Mac, you can find more information in [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144) in case it helps.

**Comment by jstafford5380** [comment]
Yes that setting that did work for me and I'm in. Just for anyone else making it to this thread, I'm not using docker-desktop I'm using rancher desktop but the process was virtually identical

`wsl -d rancher-desktop`
`sysctl -w vm.max_map_count=262144`

Thanks
