### ISSUE TITLE
SuiteCRM v7 Fails to work due to incorrect group ownership in `postunpack.sh`

### ISSUE THREAD

**Issue by chris001** [bitnami/containers#44313]
### Name and Version

bitnami/suitecrm:7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. in a linux debian 12 server
2. run the provided two line `docker compose` example commands, to get suitecrm 7 running
3. `mariadb` runs fine, however `suitecrm` exits after a few seconds.
4.  When you read the error logs, you see `access denied` error.
5. When you browse to the home page of the `suitecrm` web app, you get an `http` error code.

### What is the expected behavior?

You should be able to access the home page of the `suitecrm` web app.

### What do you see instead?

`Access denied`, and an `http` error code.

### Additional information

When I browse the suitecrm app directory inside the container, I notice most files are set to `daemon` owner, and `root` group.
**_When I set all files and directories to `daemon` owner and `daemon` group, this issue is resolved, `suitecrm` runs correctly!_**
I notice the owner and group for all files, is set inside `postunpack.sh`.
I'll make a PR to update `postunpack.sh`.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
