### ISSUE TITLE
Add hadoop support

### ISSUE THREAD

**Issue by Xuanwo** [bitnami/containers#44619]
### Name and Version

bitnami/hadoop:3

### What is the problem this feature will solve?

Do you think it's a good idea to provide hadoop/hdfs/yarn support in bitnami ecosystem?

### What is the feature you are proposing to solve the problem?

By adding hadoop in bitnami, I expect to make it easier to start a hadoop cluster in local or K8s more easier.

### What alternatives have you considered?

- https://github.com/big-data-europe/docker-hadoop works but not well-maintained, last updated at 2020.
- Upstream provides https://registry.hub.docker.com/r/apache/hadoop but not easy to use, not actively updated and only latest version supported.
- Uber has a blog on hadoop container: https://www.uber.com/blog/hadoop-container-blog/, but not open sourced.

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. To ensure that your idea receives the attention it deserves, we will apply the 'on-hold' label. This will prevent our automated system from prematurely closing the issue.

We will keep you updated on any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by OneCricketeer** [comment]
While I think it'd be useful, Hadoop Ozone or Minio are already suitable replacements for HDFS image; you don't need a namenode or datanode.

YARN within a container isn't really useful (you'd be running small JVM containers in Docker containers). Spark, Flink, etc already natively support starting Kubernetes pods, for example

**Comment by Xuanwo** [comment]
> While I think it'd be useful, Hadoop Ozone or Minio are already suitable replacements for HDFS image; you don't need a namenode or datanode.

Thank you for the ideas. As you mentioned, there are many alternatives to HDFS itself. However, these alternatives may not be suitable for use cases that specifically require HDFS or HADOOP setup, such as the [OpenDAL HDFS](https://opendal.apache.org/docs/rust/opendal/services/struct.Hdfs.html) Integration tests.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
