### ISSUE TITLE
Unable to Connect to other Databases

### ISSUE THREAD

**Issue by qops1981** [bitnami/containers#4468]
### Name and Version

bitnami/pgbouncer:1.17.0-debian-11-r32

### What steps will reproduce the bug?

1. Have a Postgres Docker Container Running
2. Launch the pgbouncer container as follows
```
docker run \
  -e 'POSTGRESQL_HOST=localhost' \
  -e 'POSTGRESQL_USERNAME=postgres' \
  -e 'POSTGRESQL_PASSWORD=password' \
  -e 'POSTGRESQL_DATABASE=<any database on the server>' \
  -e 'PGBOUNCER_POOL_MODE=transaction' \
  -e 'PGBOUNCER_PORT=6432' \
  --network=host \
  --name=pgbouncer --rm \
  bitnami/pgbouncer
```
3. `psql` into pgbouncer using any database other than `postgres`
4.  get following behavior:
```
2022-08-29 18:02:36.734 UTC [1] LOG C-0x563bf58a5160: (nodb)/postgres@127.0.0.1:52504 login attempt: db=iamatest user=postgres tls=no
2022-08-29 18:02:36.734 UTC [1] LOG C-0x563bf58a5160: (nodb)/postgres@127.0.0.1:52504 login failed: db=iamatest user=postgres
2022-08-29 18:02:36.734 UTC [1] LOG C-0x563bf58a5160: (nodb)/postgres@127.0.0.1:52504 closing because: no such database: iamatest (age=0s)
2022-08-29 18:02:36.734 UTC [1] WARNING C-0x563bf58a5160: (nodb)/postgres@127.0.0.1:52504 pooler error: no such database: iamatest
```  

### What is the expected behavior?

Should be able to connect to the DB that was called out in `-e 'POSTGRESQL_DATABASE=<any database on the server>` at a minimum

### What do you see instead?

I am only able to connect to the `postgres` database. 

### Additional information

Using `psql` and connecting directly to the DB ( not pgbouncer ) and I can connect to the database that pgbouncer targets as well as any other DB I like.

Database as listed from the pgbouncer connection

```
                                   List of databases
      Name      |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
----------------+----------+----------+------------+------------+-----------------------
 iamatest       | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 postgres       | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
                |          |          |            |            | postgres=CTc/postgres
 template1      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
                |          |          |            |            | postgres=CTc/postgres
```
So the DB is there, but pgbouncer says "no its not"

**Comment by qops1981** [comment]
It was because I did not "expose" the DP I wanted. Here is a link to that: https://github.com/bitnami/bitnami-docker-pgbouncer/blob/master/README.md#exposed-database
Note this is not very clear.

**Comment by edwardzjl** [comment]
> It was because I did not "expose" the DB I wanted. Here is a link to that: https://github.com/bitnami/bitnami-docker-pgbouncer/blob/master/README.md#exposed-database Note: this is not very clear.

According to the document it seems I can only expose one database? Have you tried expose all databases?
