### ISSUE TITLE
[bitnami/spark] generate bitnami/spark with python 3.10.x

### ISSUE THREAD

**Issue by amenezes** [bitnami/containers#4474]
### Name and Version

bitnami/spark:3.2.2

### What is the problem this feature will solve?

Added support to use python 3.10.x - pyspark driver 3.10.

### What is the feature you are proposing to solve the problem?

Without python 3.10.x the following error is raised: "Python in worker has different version 3.8 than that in driver 3.10".

### What alternatives have you considered?

First, build my own docker image.

Or, generate a new bitname/spark support to python 3.10.x. For this it's just necessary add the following line in the Dockerfile:

```txt
# current version 3.2
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.8.13-166" --checksum 9a5fba755f6c8d60eacc80f366f3fbaa57d003913e48c31ba337037bb69e37b3

# proposal for the new tag
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.10.6-7" --checksum 02e5a66908664141ad80a1d40b390a71e8cec13771cb38600c322d36747fb298
```

**Comment by javsalgar** [comment]
Hi,

> Without python 3.10.x the following error is raised: "Python in worker has different version 3.8 than that in driver 3.10".


Could you specify the steps that make this message appear?

**Comment by chris-aeviator** [comment]
I'm facing the same issue when spark-submitt'ing a job from a recent python 3.10 environment (developer's laptop) to spark running inside this container

**Comment by javsalgar** [comment]
Could you provide an environment for us to consistently reproducing the issue?

**Comment by chris-aeviator** [comment]
> Could you provide an environment for us to consistently reproducing the issue?

`conda create -n spark38 python=3.10 && conda install pyspark && spark-submit …`

**Comment by javsalgar** [comment]
Ok,

I will create a task for updating the python version to 3.10. I cannot guarantee an ETA but as soon as there are news, I will update the ticket

**Comment by j-adamczyk** [comment]
@javsalgar any news on this? I also get this error

**Comment by j-adamczyk** [comment]
Request to reopen, Python 3.8 is really outdated now, and building a 3.10 image ourselves is a considerable operational burden

**Comment by carrodher** [comment]
Please note at this moment the Python version used in the Bitnami Spark container is 3.9, no 3.8.

About using 3.10, we found some issues in some of the distros supported as part of the VMware Application Catalog (Debian 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9). We'll review if it's possible to bump the version but note none of the Python versions (3.8, 3.9 or 3.10) are close to reaching the [EOL](https://endoflife.date/python).
