### ISSUE TITLE
[bitnami/keycloak] How Keycloak binary artifact are builds ?

### ISSUE THREAD

**Issue by Damien-GERANTON-Orange** [bitnami/containers#44899]
### Name and Version

bitnami/keycloak:22

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Open the Dockerfile to understand how the image is built: https://github.com/bitnami/containers/blob/main/bitnami/keycloak/22/debian-11/Dockerfile
2. From lines 30 to 37 discover that the Keycloak, Java and Wait for port comes bitnami local server: https://downloads.bitnami.com/files/stacksmith/
```
  COMPONENTS=( \
      "**wait-for-port-1.0.6-11-linux-${OS_ARCH}-debian-11**" \
      "**java-17.0.8-7-2-linux-${OS_ARCH}-debian-11**" \
      "**keycloak-22.0.1-3-linux-${OS_ARCH}-debian-11**" \
    ) && \
    for COMPONENT in "${COMPONENTS[@]}"; do \
      if [ ! -f "${COMPONENT}.tar.gz" ]; then \
        curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O ; \
        curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O ; \
      fi && \
```
3. Question: How that binaries are built?

### What is the expected behavior?

I am expecting to have access to the build script of binary artifacts running into the docker image.

### What do you see instead?

I see that the docker image is built using direct binary artifacts, but I am not able to understand how it is built itself.

**Comment by javsalgar** [comment]
Hi!

I'm afraid that currently our build scripts are in our internal repositories. However, in the case of keycloak, we are not performing any build, we are re-using the upstream binary .jar files.

**Comment by Damien-GERANTON-Orange** [comment]
Ok, thanks for the feedback.
Can you confirm me that the upstream source URL is https://www.keycloak.org/downloads
And what does mean the -3 sub release into the component name : keycloak-22.0.1-3-linux-${OS_ARCH}-debian-11
Does it refer to your internal build script version ?

**Comment by javsalgar** [comment]
Hi,

Yes, the `-3` has to do with an internal build script
