### ISSUE TITLE
Please provide clarification, examples, or docs on how to install Drupal profiles or existing site, composer.

### ISSUE THREAD

**Issue by bluepresleycom** [bitnami/containers#44929]
### Name and Version

bitnami/drupal

### What is the problem this feature will solve?

The request is for bitnami/drupal:10+ but info for versions 7 and 9 would also be helpful while those continue to be officially maintained. In the README.md documentation, it's not clear what the steps are to properly use bitnami/drupal images with official installation profiles like OpenSocial, Thunder, CommerceKickstart or with existing, private codebases. 

Could you provide examples on how to use the images in these situations?

For example, I see symlinks for `/bitnami/drupal/{**profiles**,modules,sites,themes}`.  I've tried to extend the image per the official docs and  remove the /opt/bitnami/drupal code, then download Thunder (for example) and follow their install instructions which requires composer, git, patch, a different docroot, and a folder structure where composer, vendor, and config files are above webroot. This led down a rabbit hole trying to figure out if I needed to re-execute `prebuildfs` and `rootfs` script, edit apache .conf root directory files,  re-establish the symlinks, etc.

I then tried to copy the Thunder project into a temp directory and copy over its `profiles` directory contents to then either run `drupal si thunder` or set `DRUPAL_PROFILE=thunder` and rebuild / restart. Problem is the former causes errors because the bitnami hosted drupal code doesn't contain that profile, of course, and restarting doesn't do anything since it's already installed. If I exec into the drupal container, manually delete what bitnami installed then manually try to install thunder, I get the error that I cannot recreate the theme registry, even after I first delete the drupal database.

I'm getting too many errors to list them here. I'm sure I'm just doing it wrong, and I'm sure there is a preferred set of steps to do this correctly. I don't want to jeopardize the integrity of the image with the number of changes I'm implementing in my attempts.

What are those steps? To properly use the DRUPAL_PROFILE env variable or use an existing codebase that follows standard composer install instructions and recommend folder structure?

Finally, I see composer is installed, but don't see any indication of its use in any of the scripts. How is it (should it) being used?

### What is the feature you are proposing to solve the problem?

Add more detailed documentation in the readme file that demonstrates what env variables to use and what steps to take to to use bitnami/drupal images in the following scenarios:
- with popular profiles like Thunder, OpenSocial, CommerceKickstart (and not just with standard and minimal)
- when working with an existing repo / codebase

I don't mind modifying the docs and submitting a pull request, but I want to understand the best workflow steps first.

### What alternatives have you considered?

Please see "what problem will this solve" section

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by bluepresleycom** [comment]
Thank you, but first this issue is about collaborating to find out the correct steps. Then I'm happy write up what we discover to contribute.

Right now, there doesn't seem to be a way to install a custom profile. As well, there doesn't seem to be a way to install any drupal project where composer files are outside of webroot. Actually, there doesn't seem to be a way to use composer at all based on the base image.

I've tried 100 different ways, each experiencing its own errors. Rather than discuss those, here is the code I feel is closest to achieving the goal

```
RUN mkdir -p /tmp/project && cd /tmp/project && \
	export COMPOSER_HOME=$(mktemp -d) && \
	export COMPOSER_ALLOW_SUPERUSER=1 && \
	composer create-project --no-interaction --no-install "thunder/thunder-project" drupal && \
	cd drupal && \
	sed -i -e 's/docroot/\./g' composer.json && \ # normalize directory structure to match bitnami's /opt/bitnami/drupal
	composer config --no-plugins allow-plugins.drupal/core-composer-scaffold true && \
	composer config --no-plugins allow-plugins.phpstan/extension-installer true && \
	composer config --no-plugins allow-plugins.composer/installers true && \
	composer config --no-plugins allow-plugins.cweagans/composer-patches true && \
	composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true && \
	composer config --no-plugins allow-plugins.oomphinc/composer-installers-extender true && \
	rm -r -f /opt/bitnami/drupal/* && \
	cp /tmp/project/drupal/composer.json /opt/bitnami/drupal/ && \
	cp /tmp/project/drupal/load.environment.php /opt/bitnami/drupal/ && \
	cd /opt/bitnami/drupal

RUN cd /opt/bitnami/drupal && composer install

# USER 1001
# ENTRYPOINT [ "/opt/bitnami/scripts/drupal/entrypoint.sh" ]
# CMD [ "/opt/bitnami/scripts/apache/run.sh" ]
```
The code is rough, but it'll execute. It's an example of trying to install the Drupal Thunder project and profile. When I uncomment # USER 1001 to return to rootless, I get the error "The Drupal configuration file settings.php is not writable. Configurations based on environment variables will not be applied for this file."

If I keep USER 0, I get no error, nothing happens.

In my docker-compose.yml file I have `DRUPAL_PROFILE=thunder`. 

What I'm expecting to happen is when I return control to user 1001 and the ENTRYPOINT / CMD scripts, bitnami will set the permissions on the /drupal directory and continue to install the site based on the `drupal_site_install()` in the libdrupal.sh file.  In otherwords, because the DRUPAL_PROFILE env variable is set, I'm expecting the code in libdrupal.sh line 286 to execute:

```
 drush_execute "site:install" \
            "--db-url=mysql://${DRUPAL_DATABASE_USER}:${DRUPAL_DATABASE_PASSWORD}@${DRUPAL_DATABASE_HOST}:${DRUPAL_DATABASE_PORT_NUMBER}/${DRUPAL_DATABASE_NAME}" \
            "--account-name=${DRUPAL_USERNAME}" \
            "--account-mail=${DRUPAL_EMAIL}" \
            "--account-pass=${DRUPAL_PASSWORD}" \
            "--site-name=${DRUPAL_SITE_NAME}" \
            "--site-mail=${DRUPAL_EMAIL}" \
            "-y" "$DRUPAL_PROFILE" # <== thunder
```

But neither of these is happening.

What is the correct way to install a custom composer project, or what steps do I need to modify above for it to work?

Note, I cannot use any approach that mounts host volumes. The project's full build process has to happen in the Dockerfile itself.

**Comment by rafariossaa** [comment]
Hi, 
  Sorry for the delay.

  Let me check this, I am not familiar with details of using drupal profiles. At first sight I think this is related to permissions, but let me check.

  Regarding your question: `Do you change anything in the original drupal code before archiving it?` we don't change anything in the original code. The code is just packaged to have a common way for all our assets to be included later in the image building step.

**Comment by rafariossaa** [comment]
When I run the default docker-compose with an image built on the Dockerfile you provided, and enabling `BITNAMI_DEBUG=yes` I got this:
```
drupal_1   | drupal 10:16:50.57 INFO  ==> Configuring file permissions for Drupal
drupal_1   | drupal 10:16:50.59 INFO  ==> Installing Drupal site
drupal_1   |  You are about to:
drupal_1   |  * Create a sites/default/settings.php file
drupal_1   |  * DROP all tables in your 'bitnami_drupal' database.
drupal_1   | 
drupal_1   |  // Do you want to continue?: yes.                                              
drupal_1   | 
drupal_1   |  [warning] copy(sites/default/settings.php): Failed to open stream: Permission denied drush.inc:128
drupal_1   | 
drupal_1   | In SiteInstallCommands.php line 359:
drupal_1   |                                                                                
drupal_1   |   Failed to copy sites/default/default.settings.php to sites/default/settings  
drupal_1   |   .php                                                                         
drupal_1   |                                                                                
drupal_1   | 
```
 Not sure if you found this.
 In the original Dockerfile, you [will find](https://github.com/bitnami/containers/blob/40f3caf4d1bac67deecc0c0fabe360f4b14d5c5f/bitnami/drupal/10/debian-11/Dockerfile#L54) that `postunpack.sh` is run. [This script](https://github.com/bitnami/containers/blob/main/bitnami/drupal/10/debian-11/rootfs/opt/bitnami/scripts/drupal/postunpack.sh) set permissions (and does more things). 
 I think you would need to do something similar. Sorry for not being more precise on this point, but as we don't develop using Drupal we are not familiar with the use case and the details here.
