### ISSUE TITLE
Enhance Kafka clustering configuration with three important missing settings

### ISSUE THREAD

**Issue by ArminShoeibi** [bitnami/containers#45043]
### Name and Version

bitnami/kafka:3.x.

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In the current configuration provided,  specifically when using the Docker Compose configuration available at [bitnami/kafka/docker-compose-cluster.yml](https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose-cluster.yml), we've identified an issue with the replication factor of the ```__consumer_offsets``` and `__transaction_state` topics.

The issue stems from the fact that the replication factor of the `__consumer_offsets ` topic is initially set to just 1 replica in the provided Docker Compose configuration. This configuration can lead to problems related to data availability, fault tolerance, and resilience, especially in scenarios where high availability and data integrity are critical.

### What is the expected behavior?

The anticipated behavior involves setting the replication factor of the `__consumer_offsets ` topic to match the number of nodes within the Kafka cluster. This alignment ensures optimal fault tolerance, data availability, and reliability.

For example:

In a cluster with 3 nodes, the `__consumer_offsets` topic should ideally have a replication factor of 3.
Similarly, in a cluster comprising 5 nodes, the replication factor for the `__consumer_offsets` topic should be adjusted to 5.

### What do you see instead?

To address the issue related to the `__consumer_offsets` and `__transaction_state` topics replication factor, it's recommended to incorporate the following configuration adjustments into the provided Docker Compose file from Bitnami:

```
 - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3 
 - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
 - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
```
Source: 
[KIP-115](https://cwiki.apache.org/confluence/display/KAFKA/KIP-115%3A+Enforce+offsets.topic.replication.factor+upon+__consumer_offsets+auto+topic+creation)

If you folks are okay, I can make a PR for these configs and add them to the docker-compose file and the docs.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
