### ISSUE TITLE
[bitnami/wildfly] Wildfly container roadmap

### ISSUE THREAD

**Issue by ssill2** [bitnami/containers#45086]
### Name and Version

bitnami/wildfly:28

### What is the problem this feature will solve?

This is more of a question than a feature request.  With Wildfly going back to a more frequent release schedule with 29.   Will the bitnami team that maintains the wildfly container match those releases, or pick every other, or every nth release.

I currently use the the 28 version and it's great, I'm just trying to plan for when the next version comes out.

### What is the feature you are proposing to solve the problem?

I'm proposing outlining the strategy the bitnami team intends to follow with future versions of the bitnami/wildfly container so we can plan which versions we'll have to test with.

### What alternatives have you considered?

None at this time, just curious about the path forward at this point.

**Comment by javsalgar** [comment]
Hi,

In bitnami containers we follow the exact scheduling plan as upstream. As soon as they release a new version, our automated system will package and release it.

**Comment by ssill2** [comment]
cool.   I've been checking hub.docker.com periodically to watch for when a new 29-based tag appears so I was curious cine I see updates to 26.x and 28.x based images but not something like 27.   Thanks for the clarification.
