### ISSUE TITLE
[bitnami/kubectl] CI/CD do not generate new version of bitnami/kubectl v1.28.0

### ISSUE THREAD

**Issue by gawsoftpl** [bitnami/containers#45692]
### Name and Version

bitnami/kubectl v1.28.0

### What is the problem this feature will solve?

You CI/CD do not generate new version of bitnami/kubectl

### What is the feature you are proposing to solve the problem?

Cant use most utils on new version of kubernetes v1.28.0 include: velero

**Comment by oscrx** [comment]
I noticed the same issue in my cluster. Velero uses helm to detect the cluster version and download a compatible Kubectl version based on that. 

I started making a PR, but I found out that the Bitnami bot generates the files automatically
https://github.com/bitnami/containers/pull/39042

The file https://downloads.bitnami.com/files/stacksmith/kubectl-1.28.0-1-linux-amd64-debian-11.tar.gz
doesn't seem to exist as well..

Hope the version can be bumped in the [internal repo](https://github.com/bitnami/containers/issues/44899#issuecomment-1687723701) soon 😁

**Comment by gawsoftpl** [comment]
I have made PR for this issue, but it has been closed. We have to wait for bitnami internal PR. Propably this issue stuck in queue for repair.

**Comment by javsalgar** [comment]
Hi!

I'm afraid that the new major version is currently in our backlog, but as soon as we add support for the new branch we will notify the community.

**Comment by oscrx** [comment]
For people encountering this issue in Valero: [It can be (temporarily) overruled.](https://github.com/vmware-tanzu/helm-charts/blob/7564a60a891199aff32dc4f34ca9f1e882e18e59/charts/velero/values.yaml#L245)

**Comment by gawsoftpl** [comment]
This issue is not solved

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.
