### ISSUE TITLE
[bitnami/nginx]: Allow specifying example cert domain name

### ISSUE THREAD

**Issue by jpruciak** [bitnami/containers#45791]
### Name and Version

bitnami/nginx:1.25.2-debian-11-r3

### What is the problem this feature will solve?

Allow easy generation of self-signed certs with custom domain without writing custom init scripts.

### What is the feature you are proposing to solve the problem?

Env var with domain name(s) defaulting to example.com and www.example.com like now.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR adding that support in the bash logic?
