### ISSUE TITLE
[bitnami/minio] Minio version is not updated

### ISSUE THREAD

**Issue by ArFnds** [bitnami/containers#45839]
### Name and Version

bitnami/minio

### What architecture are you using?

None

### What steps will reproduce the bug?

The version of the bitnami/minio image is month old.

### What is the expected behavior?

The minio version should be updated.

### What do you see instead?

The minio version is not updated, we can see there that there are updates : https://hub.docker.com/r/minio/minio/tags

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.
