### ISSUE TITLE
[bitnami/pgbouncer] passwords containing double quotes (") broken

### ISSUE THREAD

**Issue by schwebke** [bitnami/containers#46094]
### Name and Version

bitnami/pgbouncer:1.20.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. configure a password containing a double quote (") via environment variable `POSTGRESQL_PASSWORD`

### What is the expected behavior?

password can be used as configured

### What do you see instead?

- connection fails with auth error
- double quote is written unescaped to generated user list
- escaping the double quote with two double quotes as described in http://www.pgbouncer.org/config.html#authentication-file-format can be used as workaround

#### Possible solutions

- add hint to documentation
- escape " with "" generating the user list

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue! I will forward this to the engineering team. If you want to speed up the process, would you like to submit a PR in `libpgbouncer.sh`? https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L192

**Comment by schwebke** [comment]
Hi,

sure -- PR created.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
