### ISSUE TITLE
Docker Secrets support

### ISSUE THREAD

**Issue by tyteen4a03** [bitnami/containers#46152]
### Name and Version

bitnami/pgbouncer:latest

### What is the problem this feature will solve?

There doesn't seem to be a way for bitnami/pgbouncer to read POSTGRESQL_PASSWORD from a secret files.

### What is the feature you are proposing to solve the problem?

Create _FILE counterparts for POSTGRESQL_PASSWORD (and other secrets) so that they can be read from files.

**Comment by javsalgar** [comment]
Hi,

In the `pgbouncer-env.sh` file you can see that all variables have a `_FILE` version

https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/pgbouncer-env.sh#L90


Could you try using it?

**Comment by tyteen4a03** [comment]
@javsalgar Thanks - would like to see this documented if possible!
