### ISSUE TITLE
[bitnami/postgresql-repmgr] can't find synchronous_standby_names configuration in env variables

### ISSUE THREAD

**Issue by sinawic** [bitnami/containers#46389]
### Name and Version

postgresql-repmgr:latest

### What is the problem this feature will solve?

hopefully by configuring the synchronous_standby_names
in an env var we can set the standby nodes we desire to have
synchronous replication with

### What is the feature you are proposing to solve the problem?

like the `bitnami/postgresql` has `POSTGRESQL_SYNCHRONOUS_COMMIT_MODE`
also postgres itself has `synchronous_standby_names = 'replica2'`
so by setting this we get to have sync replication between some nodes
and async with the rest of the nodes.

is it possible to have features like this in `postgresql-repmgr`

**Comment by fmulero** [comment]
Hi @sinawic 

The `bitnami/postgresql-repmgr`container is an extension of the `bitnami/postgresql` container with the repmgr tools. You should be able to use the same env vars as in `bitnami/postgrsql` container.

**Comment by sinawic** [comment]
Hi @fmulero 
thanks for the response

my need is that
in a 5 node cluster
with repmgr and pgpool
which of course will have the failover configuration to elect a master node among replica nodes whenever the master is marked as down
i want to have 2 sync replicas. instead having all replicas as async

if i hard code the sync nodes. on a fail over incident if one of the sync nodes become the new master as a result I'll have 1 sync node
which is not my desired state which is 2.

**Comment by sinawic** [comment]
I actually added these lines to `libpostgresql.sh` file

and kinda solved my problem.

```
replace_in_file $POSTGRESQL_CONF_FILE "#synchronous_commit = on" "synchronous_commit = on" false
replace_in_file $POSTGRESQL_CONF_FILE "#synchronous_standby_names = ''" "synchronous_standby_names = 'ANY 1 (*)'" false
```
