### ISSUE TITLE
[bitnami/prestashop] Can't access PrestaShop docker Bitnami from LAN (vmware)

### ISSUE THREAD

**Issue by BettyNutz** [bitnami/containers#4649]
### Name and Version

bitnami-docker-prestashop

### What steps will reproduce the bug?

I use vmware on a bridged network in windows 10 to run the .yml file to build stack via portainer. Everything deploys. Click on the published ports link in containers and receive:
  
Unable to connect
Firefox can’t establish a connection to the server at 0.0.0.0

Tried changing ports in yml file. no good. The only way to even access the server (FROM MY LAN) is to create a new network in portainer/dorcker compose with new subnet, gateway and ip range - then i get prestashop 500 server error.

### What is the expected behavior?

that it takes me to my ps default homepage

### What do you see instead?

Unable to connect
Firefox can’t establish a connection to the server at 0.0.0.0

### Additional information

i have no problem accessing the ps webserver from with in the virtual machine but when i bridge the connection i get the issue using localhost

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
