### ISSUE TITLE
[bitnami/postgresql-repmgr] Docker PostgreSQL Replication and Failover without Docker Swarm or Kubernetes

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [bitnami/containers#46506]
### Name and Version

 bitnami/postgresql-repmgr:14 

### What is the problem this feature will solve?

Actually I have achieved the replication and Failover in  **bitnami/postgresql-repmgr:14**  using the Swarm Environment.
Now Can I Achieve the same replication and Failover without Swarm/Kubernetes Concept ?
I have only Two PCs.  Each pc runs this image **bitnami/postgresql-repmgr:14** as a container . In this situation, I am not enabled the swarm/kubernetes Environment. 
**My Requirement is one PC Act as primary node and and another PC acts as Standby node.**
How to I achieve the replication and Failover?

### What is the feature you are proposing to solve the problem?

How to I achieve the replication and Failover without using the Swarm/Kubernetes Concept ?
I mean not using the Any Orchestration tool.

**Comment by javsalgar** [comment]
Hi,

You could try adding pgpool so it is able to redirect the traffic to the proper primary instance. I'm afraid that we do not provide support for this kind of custom installations I'm afraid. Our recommendation is to use Kubernetes and the bitnami/postgresql-ha helm chart.

**Comment by Sardonyxtechsupport** [comment]
Do you mean ,  I cannot use the bitnami/postgresql-repmgr:14 without Swarm or Kubernetes ?

My Requirement is  **I have only two PCs to achieve the replication and failover**.  When using the Swarm, I need to use minimum 3 PCs. My Hardware cost is increased. that's I why I am asking this question?

**Comment by Sardonyxtechsupport** [comment]
If i am choosing the Kubernetes, can i achieve the replication and failover with Two PC's only ?

**Comment by carrodher** [comment]
This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by muhakmalfadh** [comment]
Could you please explain how you did it using Docker Swarm? I’m unable to deploy it in Swarm mode using the [docker-compose.yml](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/docker-compose.yml) file. For example, I can’t add replicas for the replicated database.

**Comment by muhakmalfadh** [comment]
> ### Name and Version
> bitnami/postgresql-repmgr:14
> 
> ### What is the problem this feature will solve?
> Actually I have achieved the replication and Failover in **bitnami/postgresql-repmgr:14** using the Swarm Environment. Now Can I Achieve the same replication and Failover without Swarm/Kubernetes Concept ? I have only Two PCs. Each pc runs this image **bitnami/postgresql-repmgr:14** as a container . In this situation, I am not enabled the swarm/kubernetes Environment. **My Requirement is one PC Act as primary node and and another PC acts as Standby node.** How to I achieve the replication and Failover?
> 
> ### What is the feature you are proposing to solve the problem?
> How to I achieve the replication and Failover without using the Swarm/Kubernetes Concept ? I mean not using the Any Orchestration tool.
> 
> ### What alternatives have you considered?
> _No response_

Could you please explain how you did it using Docker Swarm? I’m unable to deploy it in Swarm mode using the [docker-compose.yml](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/docker-compose.yml) file. For example, I can’t add replicas for the replicated database.
