### ISSUE TITLE
[bitnami/openldap] slapd.conf not getting generated inside container image

### ISSUE THREAD

**Issue by rohan-97** [bitnami/containers#4650]
### Name and Version

bitnami/openldap:2.6.3-debian-11-r16

### What steps will reproduce the bug?

Hello,
I wanted to run an LDAP server within the container.  

I tried to create bitnami openldap container using command specified in the [readme](https://github.com/bitnami/containers/blob/main/README.md) 

I executed following steps to create ldap container

```
root@ip-10-31-2-117:~# docker run --detach --rm --name openldap-test \
  --env LDAP_ADMIN_USERNAME=admin \
  --env LDAP_ADMIN_PASSWORD=adminpassword \
  --env LDAP_USERS=customuser \
  --env LDAP_PASSWORDS=custompassword \
  bitnami/openldap:latest
cd052095ccba4acae8ff53dc19c55fa28e020b5ce1fafa4fc31296673e69e6eb
```
The container is created with the id
`cd052095ccba4acae8ff53dc19c55fa28e020b5ce1fafa4fc31296673e69e6eb`

In order to see the ldap schema I tried to execute slapcat using following steps
```
root@ip-10-31-2-117:~# docker exec -it cd052095ccba4acae8ff53dc19c55fa28e020b5ce1fafa4fc31296673e69e6eb bash
```
```
I have no name!@cd052095ccba:/$ slapcat
could not stat config file "/opt/bitnami/openldap/etc/openldap/slapd.conf": No such file or directory (2)
slapcat: bad configuration file!
```

### What is the expected behavior?

I am expecting default openldap slapcat configuration should be present in the container.

If it is not expected then can you please share the exact steps how I can generate slapd.conf and mount it on it's respective directory.

### What do you see instead?

No slapd.conf present in container

### Additional information

I tried to add a slapd.conf with following contents
```
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE   dc=example,dc=com
#URI    ldap://ldap.example.com ldap://ldap-provider.example.com:666

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never
```

and the slapcat failed with following output
```
I have no name!@cf83b5284ca2:/$ slapcat
Available database(s) do not allow slapcat
```

Can you share the steps to generate slapd.conf
Thanks!

**Comment by tatankat** [comment]
As openldap uses the "dynamic runtime configuration engine" it does not need a slapd.conf
What it need is an LDIF database, which is located at /opt/bitnami/openldap/etc/slapd.d
So if you run `slapcat -F /opt/bitnami/openldap/etc/slapd.d`, you will get the desired result.

**Comment by rohan-97** [comment]
Thanks @tatankat for sharing the command instantly!
It worked for me :)
