### ISSUE TITLE
[bitnami/moodle] Moodle Image should support connect options for pg_connect (sslmode in particular)

### ISSUE THREAD

**Issue by jpommerening** [bitnami/containers#4651]
### Name and Version

bitnami/moodle:4

### What is the problem this feature will solve?

Hi!

At the company I work at, we have a bit of standard infrastructure and we usually provision our databases to only accept SSL connections.

For Postgres clients, that means we usually have to pass `sslmode=require`. As far as I know, there is currently no way to do that with this image.

PS: thanks for your great work on _all_ of those images!

### What is the feature you are proposing to solve the problem?

1. There could be an option to pass database specific `dboptions` via an environment variable eg. `MOODLE_DATABASE_OPTIONS`.
2. The libpostgresqlclient and libmysqlclient already supports extra additional options, if I read them correctly, 
4. [`moodle_wait_for_postgresql_connection()`](https://github.com/bitnami/containers/blob/6b0581771bf13be39df66a372508d195b6367464/bitnami/moodle/4/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L294) should pass options to `postgresql_remote_execute()`, same probably with mysql to be consistent
5. Additional database options should be stored in `$CFG->dboptions` (I went through the moodle source code and it looks a bit like you can just pass any database specific option there and it gets passed along when connecting to the database, see [connect](https://github.com/moodle/moodle/blob/master/lib/dml/moodle_read_slave_trait.php), [raw_connect](https://github.com/moodle/moodle/blob/master/lib/dml/pgsql_native_moodle_database.php)). But someone with more experience should check :)

### What alternatives have you considered?

Trying to build a custom Moodle image `FROM bitnami/moodle` and patching all the necessary points. But that's quite a hassle …

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by javsalgar** [comment]
Hi,

If you create a PR with the proposal the team will take a look and can discuss different solutions. My advice would be to do something similar to what we can see in WordPress, for example:

https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/rootfs/opt/bitnami/scripts/libwordpress.sh
