### ISSUE TITLE
[bitnami/redis] support username+password auth

### ISSUE THREAD

**Issue by 51yu** [bitnami/containers#46536]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

Redis support [username+password auth](https://redis.io/commands/auth/) in addition to password only auth
Enable same capability in chart https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#L133
For now, only `password` is configurable through chart

### What is the feature you are proposing to solve the problem?

Enable username+password auth

**Comment by andresbono** [comment]
Hi @51yu, thank you for opening this issue.

Your feature request makes sense. Have you, by any chance, done some preliminary testing of this feature with our container or chart? Any additional details you may have will be helpful. Even more, would you like to contribute with a PR addressing this issue?

If that is not possible, we will try to find room to incorporate this feature to bitnami/redis.

**Comment by andresbono** [comment]
Hi, please check if [Enabling Access Control List](https://github.com/bitnami/containers/tree/main/bitnami/redis#enabling-access-control-list) would cover your use-case.
