### ISSUE TITLE
[bitnami/kafka]  ERROR ==> KRaft mode requires an unique node.id, please set the environment variable KAFKA_CFG_NODE_ID

### ISSUE THREAD

**Issue by sowjanya007b** [bitnami/containers#46564]
### Name and Version

3.3

### What architecture are you using?

None

### What steps will reproduce the bug?

We are using the 3 on-prem ubuntu VMs to run a container bitnami/kafka:3.3 on each node. We are using the kraft mode and enabled SSL on broker listener (used for clients and producers as well) and controller SSL

### What do you see instead?

I'm trying to install kafka 3.3 version and it asking node_id variable as per the release notes for 3.3 broker_id will work but in my case it is not working 
```
ERROR ==> KRaft mode requires an unique node.id, please set the environment variable KAFKA_CFG_NODE_ID
```

**Comment by juan131** [comment]
Hi @sowjanya007b 

What specific _3.3_ version are you using? Please note _3.3_ is a [rolling tag](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers) and it's hard for us to reproduce the issue unless we know the exact image revision.

Please note that providing `KAFKA_CFG_NODE_ID` is mandatory when enabling Kraft mode, see: 

- https://github.com/bitnami/containers/tree/main/bitnami/kafka#configuration
- https://github.com/bitnami/containers/tree/main/bitnami/kafka#apache-kafka-kraft-mode-configuration

I also recommend you to give it a try to this step-by-step guide:

- https://github.com/bitnami/containers/tree/main/bitnami/kafka#setting-up-a-apache-kafka-cluster
