### ISSUE TITLE
REDIS_SENTINEL_ANNOUNCE_IP set but redis-sentinel continue to provide docker container IP

### ISSUE THREAD

**Issue by kminhtri** [bitnami/containers#46594]
### Name and Version

bitnami/redis-sentinel:7.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Declare docker variable `REDIS_SENTINEL_ANNOUNCE_IP` to override docker IP for redis-sentinel
Declare docker variable `REDIS_SENTINEL_ANNOUNCE_PORT` to override docker PORT for redis-sentinel

Ex :
```
REDIS_SENTINEL_ANNOUNCE_IP = 10.10.1.2
REDIS_SENTINEL_ANNOUNCE_PORT = 6379
```

### What is the expected behavior?

Redis sentinel has to provide the `REDIS_SENTINEL_ANNOUNCE_IP` but instead we have the docker container ip.

### What do you see instead?

We have Redis master container IP : 172.19.0.2

Logs from redis-sentinel container :
`1:X 30 Aug 2023 00:06:18.689 # +monitor master redis-master 172.19.0.2 6379 quorum 1`

But if we check inside the container in `bitnami/redis-sentinel/conf/sentinel.conf`:
We have :
`sentinel monitor redis-master 172.19.0.2 6379 1`
and also
```
sentinel announce-ip "10.10.1.2"
sentinel announce-port 6379
```

But it seems it does not take into account the announce-ip, instead we continue to get 172.19.0.2

**Comment by andresbono** [comment]
Hi, I can reproduce the issue. However, according to the redis documentation, the config file seems to be correct, right?

```
sentinel announce-ip "10.10.1.2"
sentinel announce-port 6379
```

Can you confirm that you face the same issue if you restart the container?

**Comment by kminhtri** [comment]
Yes exact, the config looks to be ok. But the announce ip is not propagate to other sentinel.

I use a workaround, bypass docker network and set a real network (through ipvlan).

**Comment by andresbono** [comment]
I see. Thank you for confirming and sharing your workaround. Could it be then an issue in the redis-sentinel project itself? Did you find any references to your issue in the upstream redis projects?

**Comment by andresbono** [comment]
Hi again. In fact the, the configuration is being applied, maybe it is just that it is not working as you would expect. This is a command to check it:

```bash
$ docker exec <YOUR_REDIS_SENTINEL_CONTAINER> redis-cli -p 26379 SENTINEL CONFIG GET announce-ip announce-port
announce-ip
10.10.1.2
announce-port
6379
```

Please check: https://redis.io/docs/management/sentinel/#sentinel-docker-nat-and-possible-issues
