### ISSUE TITLE
[bitnami/discourse] Enable DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER in single site mode.

### ISSUE THREAD

**Issue by anylots** [bitnami/containers#46640]
### Name and Version

bitnami/discourse:3.0.4

### What is the problem this feature will solve?

Problem:
Users can access it normally https://www.test.com . But after logging in, the redirect address changed to http://www.test.com (starts with http). The link in the activation email for new users also starts with http. 
Discourse Docker is deployed on a single server and uses a '80:3000' configuration, followed by separate use of nginx to provide HTTPS services.
The above situation prevents users from further accessing the discovery page.

### What is the feature you are proposing to solve the problem?

According to https://hub.docker.com/r/bitnami/discourse/ The description inside, DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER seems to be able to solve this problem, but it needs to be run in unnecessary multisite mode. Can we generalize this configuration or have other solutions to solve this problem?

**Comment by andresbono** [comment]
Hi, I'm not really sure if that would work. Have you tried the `force_https` option? In the site settings (or `site_settings.yml`). Maybe that one can do the trick.
