### ISSUE TITLE
MongoDB Version 4.0.28

### ISSUE THREAD

**Issue by SamLue** [bitnami/containers#46649]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

Is it possible to share an image of the Mongodb Version 4.0.28 in your bitnami repository?

We use an application that only supports the DB-Version 4.0.28.
In the bitnami repo (hub.docker.com) there is only version 4.0.27 available.
But in the official mongo repo, there is also a [4.0.28](https://hub.docker.com/layers/library/mongo/4.0.28/images/sha256-f68f07e0c0ee86b1d848a30b27e5573e9c960748a02f7c288e28282297117644?context=explore).
https://hub.docker.com/layers/library/mongo/4.0.28/images/sha256-f68f07e0c0ee86b1d848a30b27e5573e9c960748a02f7c288e28282297117644?context=explore

Thanks and best regards,
Samuel

### What is the feature you are proposing to solve the problem?

Application Support

### What alternatives have you considered?

I use the previous Version 4.0.27, which is not supported.

**Comment by carrodher** [comment]
MongoDB 4.x is not released upstream for Debian 11 which is the underlying distro used in the Bitnami catalog, see
![Screenshot 2023-09-04 at 13 52 55](https://github.com/bitnami/containers/assets/13216600/ce54c606-d475-4b7c-9bac-cbb2747b4f95)
versus MongoDB 6.x
![Screenshot 2023-09-04 at 13 53 04](https://github.com/bitnami/containers/assets/13216600/0b12d2c5-1d0c-46fb-bd6f-67e25b72e6ff)

**Comment by SamLue** [comment]
OK,

means you are not able to create an image in Version 4.0.28?

**Comment by carrodher** [comment]
Right, at this moment the supported versions for MongoDB in the Bitnami Application Catalog are 5.0.x and 6.0.x

**Comment by SamLue** [comment]
OK, thanks anyway.
