### ISSUE TITLE
[bitnami/jasperreports] Docker SMTP Configuration

### ISSUE THREAD

**Issue by cbldn** [bitnami/containers#4677]
### Name and Version

docker.io/bitnami/jasperreports:8

### What steps will reproduce the bug?

I am trying to configure the SMTP service through the environment variables in docker-compose.
![image](https://user-images.githubusercontent.com/112388758/187628260-d9fb6593-56af-4d0f-9565-61a933b5a04e.png)

### What do you see instead?

But when I schedule a send, I get the following error 
![image](https://user-images.githubusercontent.com/112388758/187628701-5b1efa8b-1ee9-427f-aec6-4323d200b216.png)

**Comment by fmulero** [comment]
Hi @cbldn  Have you taken a look to the [SMTP Configuration](https://github.com/bitnami/containers/tree/main/bitnami/jasperreports#smtp-configuration) ?

**Comment by fmulero** [comment]
This is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

**Comment by grantemsley** [comment]
Please reopen this. It is still an issue. A pull request is pending approval to fix it.
