### ISSUE TITLE
[bitnami/fluentd] Problem installing plugins in fluentd

### ISSUE THREAD

**Issue by Drupi** [bitnami/containers#4687]
### Name and Version

bitnami/fluentd:1.15.2-debian-11-r0

### What steps will reproduce the bug?

According to the docs, I should be able to install additional plugins using this container as the base one.
Unfortunately, it isn't working because Permission was Denied. 

Reproduce:

Create Dockerfile with:
```
FROM bitnami/fluentd:1.15.2-debian-11-r0

RUN fluent-gem install 'fluent-plugin-splunk-hec'
```

### What is the expected behavior?

The plugin is installed :) 

### What do you see instead?

![image](https://user-images.githubusercontent.com/18419080/187681094-7da7d1a0-f644-4cd8-87bc-c6b87e7e999e.png)

**Comment by javsalgar** [comment]
Hi,

Could you adding USER root before executing the `gem install` command? Then turn it back to the regular user `1001`

```
USER root
RUN gem install ...
USER 1001

**Comment by Drupi** [comment]
Thanks, @javsalgar. 
Solved.
