### ISSUE TITLE
[bitnami/keycloak] import setttings in json file

### ISSUE THREAD

**Issue by dafik** [bitnami/containers#4761]
### Name and Version

bitnami/keycloak:18.0.2-debian-11-r26

### What steps will reproduce the bug?

on docker

When using KEYCLOAK_EXTRA_ARGS: --import-realm
and mount volume eg. - ./import:/opt/bitnami/keycloak/data/import

https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup

docker creates path `/opt/bitnami/keycloak/data` with owner `root:root` because it does not exist in the image.
After starting and importing data when you try to log in to keycloak you got error:
```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.RuntimeException: Temporary directory /opt/bitnami/keycloak/bin/../data/tmp does not exist and it was not possible to create it.
```

### What is the expected behavior?

 /opt/bitnami/keycloak/bin/data

should exist in the image with ownership keycloak

### What do you see instead?

data directory exists but has wrong ownership (caused docker mount root:root)

```
keycloak@b018b7aadeda:/opt/bitnami/keycloak$ ls -lha
total 80K
drwxrwxr-x 1 keycloak root 4.0K Sep  1 07:54 .
drwxrwxr-x 1 root     root 4.0K Aug 29 22:39 ..
-rw-rw-r-- 1 keycloak root    0 Aug 24 18:51 .buildcomplete
drwxrwxr-x 2 keycloak root 4.0K Aug 29 22:41 .installation
-rw-rw-r-- 1 keycloak root  12K Aug 24 18:51 LICENSE.txt
-rw-rw-r-- 1 keycloak root  492 Aug 24 18:51 README.md
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 bin
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 conf
drwxr-xr-x 3 root     root 4.0K Sep  1 07:53 data
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 lib
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 licenses
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 modules
drwxrwxr-x 1 keycloak root 4.0K Sep  1 07:53 providers
drwxrwxr-x 1 keycloak root 4.0K Aug 26 05:02 themes
-rw-rw-r-- 1 keycloak root   26 Aug 24 18:51 version.txt
```

### Additional information

my current workaround is extending the image:

```Dockerfile
FROM bitnami/keycloak:18.0.2-debian-11-r26

RUN mkdir /opt/bitnami/keycloak/data
```

**Comment by aoterolorenzo** [comment]
Hey @dafik,

I think it has pretty much sense to add this directory to the container since it seems a standardized directory for Keycloak imports. I'm on it.

**Comment by aoterolorenzo** [comment]
@dafik a new release is out and it includes the feature. Thank you for contributing!
