### ISSUE TITLE
[mongodb] Upgrade to MongoDB 7.0

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/containers#47695]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

MongoDB 7.0 is released (https://www.mongodb.com/docs/v7.0/release-notes/7.0/), would it be possible to upgrade bitnami image ?

### What is the feature you are proposing to solve the problem?

Just be in sync with upstream releases :)

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by carrodher** [comment]
Hi! MongoDB 7.0 was released some days ago at https://github.com/bitnami/containers/pull/49498. From now on you can use this new major version.
