### ISSUE TITLE
[image] bun.sh

### ISSUE THREAD

**Issue by rafalohaki** [bitnami/containers#47826]
### Name and Version

bitnami/bun

### What is the problem this feature will solve?

Bun.sh is growing day by day, its framework like yarn/node
need this as docker container, it would be awesome

### What is the feature you are proposing to solve the problem?

please add [bunb](https://bun.sh/) to image of bitnami <3 please

**Comment by rafalohaki** [comment]
link to repo with dockerfile:
https://github.com/oven-sh/bun

bitnami images have 50% memory less consumption as i could see so i wish it could be supported

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. To ensure that your idea receives the attention it deserves, we will apply the 'on-hold' label. This will prevent our automated system from prematurely closing the issue.

We will keep you updated on any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.
