### ISSUE TITLE
[bitnami/minio] Bitnami minio no longer wants to mount volumes on newer version

### ISSUE THREAD

**Issue by tommyhabibe** [bitnami/containers#48235]
### Name and Version

Bitnami/minio:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Running bitnami/minio on docker with -v D:/minio (local volume) and it doesnt write to this directory. It was working fine until I pulled the latest image from bitnami/minio. Thanks for the help!!

### Are you using any custom parameters or values?
```
docker run --name minio --publish 9000:9000 --publish 9001:9001 --env MINIO_ROOT_USER="easywireless" --env MINIO_ROOT_PASSWORD="easywireless" --volume D:/minio:/data bitnami/minio:latest
```
### What is the expected behavior?

All system data should be save to D:/minio but it is creating a docker temp volume instead.

### What do you see instead?

Minio isnt writitng to the mounted volume

**Comment by javsalgar** [comment]
Hi!

Looking at the environment variables, we see the following

```
export MINIO_DATA_DIR="/bitnami/minio/data"
```

Could you try changing the mount point from `/data` to `/bitnami/minio/data`?

**Comment by galkinrost** [comment]
The same problem for me. Have to downgrade to 2023.7.18. This version works fine

**Comment by MyWay** [comment]
> Hi!
> 
> Looking at the environment variables, we see the following
> 
> ```
> export MINIO_DATA_DIR="/bitnami/minio/data"
> ```
> 
> Could you try changing the mount point from `/data` to `/bitnami/minio/data`?

that worked for me.

**Comment by lmb-djaquier** [comment]
@MyWay is right.

The change has been introduced there:
https://github.com/bitnami/containers/commit/144831bb8e8b4029206e6c356cb18d95148c03d1#r128404508
