### ISSUE TITLE
Add libpq-dev python3-dev gcc to images

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/containers#48237]
### Name and Version

bitnami/airflow-worker

### What is the problem this feature will solve?

psycopg2 could be installed from requirements.txt. Currently, if we try to install it in airflow as a dependency we will get: 
 ```
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
```

### What is the feature you are proposing to solve the problem?

It will solve the problem of adding psycopg2 as a dependency in airflow

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
