### ISSUE TITLE
Kibana 8.4.0 image availability

### ISSUE THREAD

**Issue by metalshanked** [bitnami/containers#4824]
### Name and Version

bitnami/kibana

### What steps will reproduce the bug?

1. Search for btinami/kibana:8.4.0 on docker hub

### What is the expected behavior?

1. btinami/kibana:8.4.0 release should be available on docker hub

### What do you see instead?

no results found

**Comment by carrodher** [comment]
The image is already present in DockerHub, [here](https://hub.docker.com/layers/bitnami/kibana/8.4.1-debian-11-r0/images/sha256-740a2e9def8b1dd8d822a36fc39597f8bcbf80eab4446e92f4f83843bf47d4cf?context=repo) you can find it.

In the same way, you should be able to pull it by running:
```console
$ docker pull bitnami/kibana:8.4.1
8.4.1: Pulling from bitnami/kibana
3b5e91f25ce6: Already exists
c5df2ba6a6a8: Pull complete
d41d9ab0318e: Pull complete
3efb5d496352: Pull complete
a36110ac72a0: Pull complete
3f58b6ccbdc3: Pull complete
4ef6f4c8aec3: Pull complete
a9b06b8f36e4: Pull complete
ee293971d9da: Pull complete
15322167ea27: Pull complete
Digest: sha256:740a2e9def8b1dd8d822a36fc39597f8bcbf80eab4446e92f4f83843bf47d4cf
Status: Downloaded newer image for bitnami/kibana:8.4.1
docker.io/bitnami/kibana:8.4.1
```
