### ISSUE TITLE
[bitnami/openldap] cn=module,cn=config missing

### ISSUE THREAD

**Issue by jonnoss1** [bitnami/containers#48256]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Docker Desktop 4.21.0
2. The sample/example docker-compose.yml [ bitnami/openldap/docker-compose.yml]
with these additional environment variables:
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_PASSWORD=adminpass 
      - 

```
$ docker compose up -d

$ ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b "cn=module*"  
No such object (32)
$ ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b "cn=module"       
No such object (32)
$ ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b "cn=module{0}"
No such object (32)
```
### What is the expected behavior?

I expect to be able to find a valid directory entry for cn=module,cn=config.

### What do you see instead?

I do not see an entry for cn=module,cn=config, or similar.

**Comment by radokristof** [comment]
I think I experience the same. Admin user is not created

**Comment by radokristof** [comment]
I have the same problem. Config admin user is not created automatically on fresh startup

**Comment by jonnoss1** [comment]
Hi @CeliaGMqrz,

I have attached the outputs.
[ldapsearch.txt](https://github.com/bitnami/containers/files/12608905/ldapsearch.txt)
[ldapwhoami.txt](https://github.com/bitnami/containers/files/12608906/ldapwhoami.txt)

I had a look in libopenldap.sh and saw that the ldap_load_module() function was only called when env LDAP_CONFIGURE_PPOLICY=true.

Based on this I tested extending libopenldap.sh with support for the **Sync Provider** overlay which I wanted to use.
This worked successfully so I'm actually happy to close as libopenldap.sh appears to be working as intended; only creating a **cn=module** entry when a supported module is enabled.

J

**Comment by CeliaGMqrz** [comment]
Hi @jonnoss1,

Thanks for your feedback!

It's great to hear that you were able to use `libopenldap.sh` to support the Sync Provider overlay successfully. Indeed, according to the logic, when the `ppolicy` module is activated, it calls the function [ldap_load_module](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L738) which activates this.  Just as we added this module you could add any other module as a new feature request.  Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

Also, you can add custom configuration through ldif files, in this [comment](https://github.com/bitnami/containers/issues/982#issuecomment-1220354408) my colleague explains an example for it. I hope you find it helpful. If you have other questions do not hesitate to let us know.

**Comment by jonnoss1** [comment]
Hi @CeliaGMqrz,

Thanks for the confirmation.
I would be happy to contribute the changes I have have made.
I will reference the PR here once created.

**Comment by jonnoss1** [comment]
Hi @CeliaGMqrz,

[PR](https://github.com/bitnami/containers/pull/49281) created. 

Support for the `accesslog` overlay is included as I had already implemented it for my requirement.
