### ISSUE TITLE
PHP logs wont display

### ISSUE THREAD

**Issue by kale1d0code** [bitnami/containers#48408]
### Name and Version

bitnami/suitecrm:7.11.22

### What architecture are you using?

amd64

### What steps will reproduce the bug?

setup with docker-compose or just docker

### What is the expected behavior?

PHP error logs to display in stderr

### What do you see instead?

Apache access log only

**Comment by Mauraza** [comment]
Hi @kale1d0code,

To access the logs of PHP, you need to exec to the container.

**Comment by kale1d0code** [comment]
Hi @Mauraza 

Thanks for confirming.
I've looked into how to show the error messages in a bitnami container.
I found the following page https://docs.bitnami.com/aws/infrastructure/lamp/troubleshooting/debug-errors-apache/
this points to the file /opt/bitnami/apache/logs/error_log
As the CRM container runs apache I thought the errors may show there but I didn't see anything printing when tailing the file.

I also looked into /opt/bitnami/php/var/log (didn't contain a file)
and /opt/bitnami/php/logs (contained php-fpm.log which is empty)

can you explain how to get the files to populate with error messages?

**Comment by kale1d0code** [comment]
Hi @Mauraza 
I can't find any log files within the container which contain php error messages.

I was wondering if there is a way to direct the error messages to stdout, so they can be picked up by observability platforms

**Comment by Mauraza** [comment]
Hi @kale1d0code,

If you check the php.ini appears:
```
; Log errors to specified file. PHP's default behavior is to leave this value
; empty.
; https://php.net/error-log
; Example:
error_log = /dev/stderr
; Log errors to syslog (Event Log on Windows).
error_log = /dev/stderr
```
It should be shown in the docker logs of the container.

Could you share more about your issue?

**Comment by bohdan-shulha** [comment]
For anyone who'd be reaching this post in the future, you have to turn on the `catch_workers_output` property in your php-fpm.d/www.conf (or any other you use).

```
; Redirect worker stdout and stderr into main error log. If not set, stdout and
; stderr will be redirected to /dev/null according to FastCGI specs.
; Note: on highloaded environment, this can cause some delay in the page
; process time (several ms).
; Default Value: no
```
