### ISSUE TITLE
/opt/bitnami/scripts/libsymfony.sh: line 39: !1: unbound variable

### ISSUE THREAD

**Issue by ivan23kor** [bitnami/containers#48437]
### Name and Version

bitnami/symfony:6.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```bash
mkdir ~/myapp && cd ~/myapp
curl -LO https://raw.githubusercontent.com/bitnami/containers/main/bitnami/symfony/docker-compose.yml
docker-compose up
```

### What is the expected behavior?

Running image.

### What do you see instead?
```
symfony-myapp-1    | /opt/bitnami/scripts/libsymfony.sh: line 39: !1: unbound variable
symfony-myapp-1 exited with code 1
```

**Comment by joancafom** [comment]
Hi @ivan23kor 

Thanks for reporting! It seems it is an issue with one of the variables not being set. Could you please try performing the following changes to the `docker-compose.yml` file and see if that resolves the issue?

```diff
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/symfony:6.3
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=bn_myapp
      - SYMFONY_DATABASE_NAME=bitnami_myapp
+     - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
```

**Comment by JefvdA** [comment]
@joancafom I was running into the same issue, and found this github ticket. I tested locally, and updating the `docker-compose.yml` for symfony with your suggested change does the trick! :+1: 

I created a [MR](https://github.com/bitnami/containers/pull/51190) with this change while I was at it. 

Thanks for the solution, and hope the MR does the trick.

Cheers! :smile:

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by joancafom** [comment]
Hey all! Just mentioning that this was recently resolved in https://github.com/bitnami/containers/pull/51190. Thanks for reporting 🚀
