### ISSUE TITLE
Adding certificate authorities to Kibana

### ISSUE THREAD

**Issue by muhammeddanish** [bitnami/containers#48519]
### Name and Version

bitnami/kibana:8.7.1-debian-11-r7

### What architecture are you using?

None

### What steps will reproduce the bug?

I attempted to utilize the environment variable `ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES` to pass the certificate authority to the Kibana configuration, and it was functioning effectively with the Elastic Kibana image. Is there an alternative environment variable provided in the Kibana Bitnami image for this purpose? 

### What do you see instead?

Kibana pod is not coming up.

**Comment by andresbono** [comment]
Hi, sorry for the delay in my response here.

I assume that by setting `ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES` (or an equivalent one) you would expect `elasticsearch.ssl.certificateAuthorities` in `kibana.yml` to be configured with the value provided in the env-var. Is that correct?

> Kibana pod is not coming up.

Could you please share any error messages that you see?

**Comment by muhammeddanish** [comment]
This was the error I seen in kibana pod logs:
```
In order to connect to Elasticsearch via HTTPS, a valid CA certificate is required
```
However, I found a workaround to this problem by adding the env variable: KIBANA_ELASTICSEARCH_CA_CERT_LOCATION
That is adding below values to helm:
```
extraEnvVars:
      - name: KIBANA_ELASTICSEARCH_CA_CERT_LOCATION
        value: /opt/bitnami/kibana/config/certs/elasticsearch/elasticsearch-ca.pem
```
This was missing from your helmchart documentation.

**Comment by andresbono** [comment]
Thank you @muhammeddanish for sharing how you could solve the issue 🎉 . No issue on the container side, right?

I still don't have a complete view of how are you deploying the chart. But if you feel like the chart is missing some feature that may be useful for others, feel free to open an issue or send a PR in https://github.com/bitnami/charts.
