### ISSUE TITLE
[bitnami/rabbitmq] rabbitmqctl: 191: exec: erl: not found 

### ISSUE THREAD

**Issue by clcc2019** [bitnami/containers#48529]
### Name and Version

bitnami/rabbitmq:3.9.29

### What architecture are you using?

None

### What steps will reproduce the bug?

```
arm64 run rabbitmqv3.9.29 【erl: not found】rabbitmqctl: 191: exec: erl: not found

env:
kernel 4.19
arch: arm64
kubernetes:v1.24.16
runtime: containerdv1.7.6
```

### What do you see instead?

<img width="653" alt="image" src="https://github.com/bitnami/containers/assets/46099295/1563e6dd-5eab-42e7-b63a-3d65e0935e21">

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the platform you are using to run the containers?

**Comment by ganeddact** [comment]
I have the same issue, running it on Mac Silicon M2 Pro, specifying linux/arm64 in a docker-compose file, minimal settings:
    rabbitmq:
        image: 'docker.io/bitnami/rabbitmq:3.9'
        platform: linux/arm64
        volumes:
            - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

@cicc2019 how did you resolve?
