### ISSUE TITLE
[bitnami/moodle] Support /var/local/cache for $CFG->localcachedir

### ISSUE THREAD

**Issue by cgrycki** [bitnami/containers#4854]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

This feature request was previously requested under the bitnami-docker-moodle repository here: [https://github.com/bitnami/bitnami-docker-moodle/issues/101](https://github.com/bitnami/bitnami-docker-moodle/issues/101)
I intend to submit a PR to implement the solution proposed by @ceefour.

Moodle's documentation on server clustering recommends setting `$CFG->localcachedir` to a location on the local file system. This improves performance in environments where Moodle is clustered.
(https://docs.moodle.org/400/en/Server_cluster#.24CFG-.3Elocalcachedir)

This is difficult to configure in the current image because:
- There isn't an environment variable for this setting
- A local folder with the proper permissions needs to be created

### What is the feature you are proposing to solve the problem?

I plan to submit a PR that will support this feature by adding an environment variable `MOODLE_LOCAL_CACHE_DIR`.
If this variable is set to "yes", then:
- a directory with the appropriate permissions will be created at `/var/local/cache`. 
- `$CFG->localcachedir = '/var/local/cache';` will be appended to `config.php`
If this variable is set to "no" or is not defined, then the directory is not created and the _localcachedir_ setting will not be added to `config.php`.

### What alternatives have you considered?

Extending the image by implementing a custom entry point script that will create the directory, set permissions, and add the _localcachedir_ setting to `config.php`.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR. Once ready, the team will review it and provide feedback
