### ISSUE TITLE
[bitnami/pgbouncer] pooler error: SASL authentication failed

### ISSUE THREAD

**Issue by juliengz** [bitnami/containers#48636]
### Name and Version

bitnami/pgbouncer:1-debian-11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**Environment:**
Issue append in Kubernetes (with 3 services: php-fpm in a pod, pgbouncer and posgres in another pod) service  environment when launching operation that required posgres interactions from a php-fpm service using helm deployment. 

**config:**
```yaml
pgbouncer:
    host: pgbouncer
    port: 5432
    image: bitnami/pgbouncer
    imageTag: 1-debian-11
```

**Credential values used for connection come from env variables.**
    
**How it happen:**
_when_
	A process from php-fpm service that require DB interaction is launched (in our case some db migrations)
_Then_
	We get the following sequence
          -  (nodb)/(nouser)@x.x.x.x:xxx no such user: <user>
          -  (nodb)/<user>@x.x.x.x:xxx password authentication failed
          -  (nodb)/<user>@x.x.x.x:xxx pooler error: SASL authentication failed
           

### What is the expected behavior?

Every thing work as expected without any error output with [1.20.1-debian-11-r24](https://hub.docker.com/layers/bitnami/pgbouncer/1.20.1-debian-11-r24/images/sha256-a01054dbac62d5abd99b3299ed50bc598863329911c0d50c530c109fbe6496ca?context=explore)

**expected log:**
UTC [1] LOG stats: 0 xacts/s, 0 queries/s, in 89 B/s, out 98 B/s, xact 2687 us, query 2687 us, wait 46 us

### What do you see instead?

**We observe this sequence:**
-  (nodb)/(nouser)@x.x.x.x:xxx no such user: <user>
-  (nodb)/<user>@x.x.x.x:xxx password authentication failed
-  (nodb)/<user>@x.x.x.x:xxx pooler error: SASL authentication failed

**Comment by jdepp** [comment]
Also experiencing this. Previous pgbouncer version of 1.20.0 worked, and then now 1.20.1 seems to break the auth with the above error. Also other errors that the user in our userlist.txt can't be found.

Our userlist.txt on 1.20.0 had this syntax:
```
"USER" "PASSWORD"
```

And now with 1.20.1 it's like this:
```
pgbouncer_escape_auth USER pgbouncer_escape_auth PASSWORD
```

**Comment by Hazmi35** [comment]
Can confirm, probably related to https://github.com/pgbouncer/pgbouncer/issues/944

**Comment by dustinrue** [comment]
Hopping in to say I ran into this recently and it is caused by this line https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L206. It is not calling that function correctly. As a test I created this:

```
#!/bin/sh

POSTGRESQL_USERNAME="postgres"
POSTGRESQL_PASSWORD="password"
pgbouncer_escape_auth() {
    # shellcheck disable=SC2001
    # replace each " with ""
    echo "$1" | sed 's/"/""/g'
}

echo \"$(pgbouncer_escape_auth $POSTGRESQL_USERNAME)\" \"$(pgbouncer_escape_auth $POSTGRESQL_PASSWORD)\"
```

Which outputs:

```
"postgres" "password"
```

I don't know of that is necessarily correct either but how it is currently written definitely does not work.

**Comment by juliengz** [comment]
Indeed @dustinrue here is the specific commit -> https://github.com/bitnami/containers/commit/d384b3e9ad02875e8a6fde3fbc52618d7aae9874.

**Comment by mdhont** [comment]
Hi @juliengz , feel free to create a PR to fix the issue.

**Comment by MB175** [comment]
I'm also facing this issue
