### ISSUE TITLE
traps: nginx trap invalid opcode in ngx_http_brotli_filter_module.so

### ISSUE THREAD

**Issue by rwasef1830** [bitnami/containers#48663]
### Name and Version

bitnami/nginx:936a3904a07d

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just start it with brotli module loaded and enabled, and try to open a webpage, it will core dump.

### What is the expected behavior?

It works.

### What do you see instead?
```
[  120.497566] traps: nginx[1700] trap invalid opcode ip:7fe308e4275b sp:7ffc1c089160 error:0 in ngx_http_brotli_filter_module.so[7fe308e34000+99000]
[  122.344020] traps: nginx[1701] trap invalid opcode ip:7fe308e4275b sp:7ffc1c0890c0 error:0 in ngx_http_brotli_filter_module.so[7fe308e34000+99000]
[  128.373348] traps: nginx[2344] trap invalid opcode ip:7fe308e4275b sp:7ffc1c089120 error:0 in ngx_http_brotli_filter_module.so[7fe308e34000+99000]
```

**Comment by rwasef1830** [comment]
Rollback to 1.25.2-debian-11-r25 fixes crash. 1.25.2-debian-11-r27 is broken.

**Comment by mdhont** [comment]
Could you share a docker-compose file that reproduces the issue, so I can try to reproduce it on my side?

**Comment by rwasef1830** [comment]
@mdhont  Here you go, unzip this somewhere, then `docker compose up`, then hit http://localhost:48080/ in your browser.

You will get worker process exited due to signal 4 and the trap messages I posted in the first comment in dmesg.

[repro-48663.zip](https://github.com/bitnami/containers/files/12703979/repro-48663.zip)

**Comment by mdhont** [comment]
I can't reproduce the error, http://localhost:48080/ shows a page with the text:

Repro bug 48663
Hello world.

> Did nginx get compiled to use AVX512 instructions ?

We don't specifically compile nginx to use AVX512 instructions

**Comment by rwasef1830** [comment]
@mdhont It repros 100% on my CPU AMD Ryzen 5950x. It also repros on an OVH Linux VPS:

Here's its /proc/cpuinfo:
```
processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel Core Processor (Haswell, no TSX)
stepping        : 1
microcode       : 0x1
cpu MHz         : 2599.994
cache size      : 16384 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid pml
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_unknown
bogomips        : 5199.98
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```


Could you check what is the CPU of the machine you ran the image on, and compare its capabilities to the list I posted from my /proc/cpuinfo and the one above ?

It's 100% a compiler CPU flags issue or assembly optimizations issue in the brotli module, something which changed between r25 and r27. It could even be related to a compiler issue. Did the compiler version change between r25 and r27 ?

Somehow the brotli module is using CPU instructions not available in the x86_64 CPUs whose cpuinfos I mentioned.

**Comment by rwasef1830** [comment]
Don't use curl you have to send accept header that tells the server your
client understands brotli. Navigate with a real browser.

**Comment by rwasef1830** [comment]
@mdhont this will trigger the issue with curl:

`curl -H 'Accept-Encoding: br' http://localhost:48080`
