### ISSUE TITLE
the command in Minio【Persisting your database】 may be wrong

### ISSUE THREAD

**Issue by Ginorva** [bitnami/containers#48737]
### Name and Version

bitnami/minio:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

docker run --name minio \
    --publish 9000:9000 \
    --publish 9001:9001 \
    --volume /path/to/minio-persistence:/data \
    bitnami/minio:latest

### What is the expected behavior?

--volume /path/to/minio-persistence:/data must change to --volume /path/to/minio-persistence:/bitnami/minio/data

### What do you see instead?

#

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
