### ISSUE TITLE
[bitnami/kubectl] kubectl 1.28 image missing

### ISSUE THREAD

**Issue by jnoordsij** [bitnami/containers#48989]
### Name and Version

bitnami/kubectl:1.28

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker pull bitnami/kubectl:1.28`

### What is the expected behavior?

The image to be pulled succesfully

### What do you see instead?

```
Error response from daemon: failed to resolve reference "docker.io/bitnami/kubectl:1.28": docker.io/bitnami/kubectl:1.28: not found
```

### Additional information

Kubernetes 1.28 (and thus `kubectl`) has been [released on August 15th](https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/). However, there is no image variant for this release. Since all tags are automatically added by a bot, I cannot find the precise cause for this.

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by CeliaGMqrz** [comment]
Hi @jnoordsij ,

Thanks for your patience. [Kubectl v1.28 is now available](https://github.com/bitnami/containers/tree/main/bitnami/kubectl/1.28/debian-11). See #49285

**Comment by jnoordsij** [comment]
Thanks for fixing this!
