### ISSUE TITLE
MultiArch support

### ISSUE THREAD

**Issue by choubacha** [bitnami/containers#490]
### Name and Version

bitnami/redis-cluster:6.2

### What is the problem this feature will solve?

My work laptop is an m1 macbook and running the cluster with the amd64 architecture causes timeouts when running tests locally with the image. Providing both amd64 and arm64 would alleviate this problem.

### What is the feature you are proposing to solve the problem?

Build and push at least arm64 and amd64 via the multiarch build support:
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

### What alternatives have you considered?

I'm considering forking and building them myself.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
