### ISSUE TITLE
[bitnami/mongodb] mongodb 7.0.0/7.0.1 images missing

### ISSUE THREAD

**Issue by nadav13** [bitnami/containers#49133]
### Name and Version

bitnami/mongodb:7.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

docker pull bitnami/mongodb:7.0.0

### What is the expected behavior?

The image to be pulled successfully

### What do you see instead?

```
Error response from daemon: manifest for bitnami/mongodb:7.0.1 not found: manifest unknown: manifest unknown
```

### Additional information

MongoDB version [7.0.0](https://hub.docker.com/layers/library/mongo/7.0.0/images/sha256-19b2e5c91f92c7b18113a1501c5a5fe52b71a6c6d2a5232eeebb4f2abacae04a?context=explore) and [7.0.1](https://hub.docker.com/layers/library/mongo/7.0.1/images/sha256-1ff65169cc24bbf2966a8b451cc15fd32104cba1e4e57ade389216c47da7c77e?context=explore) were released on [August 15th](https://www.mongodb.com/docs/v7.0/release-notes/7.0/#7.0.0---aug-15--2023) and [September 5th](https://www.mongodb.com/docs/v7.0/release-notes/7.0/#7.0.1---sep-5--2023) respectively, but have not been created as Bitnami images despite the automatic process in place.
Is there a timeline for the release of these images?

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by carrodher** [comment]
Hi! MongoDB 7.0 was released some days ago at https://github.com/bitnami/containers/pull/49498. From now on you can use this new major version.
