### ISSUE TITLE
Add the option to DISABLE_AOF

### ISSUE THREAD

**Issue by d0zingcat** [bitnami/containers#49267]
### Name and Version

bitnami/redis-cluster:7.2

### What is the problem this feature will solve?

AOF write cause performance loss

### What is the feature you are proposing to solve the problem?

In the image, the REDIS_RDB_POLICY parameter has already been provided to control the persistence behavior of RDB. For example, setting it to '' can prevent RDB from persisting data. However, I'm wondering if the intention is to disable persistence, even if RDB is turned off, AOF will still be automatically written. Won't there still be a performance loss due to disk writes in this case?

**Comment by andresbono** [comment]
Hi thank you for opening this issue. Maybe `REDIS_AOF_ENABLED=no` is the env-var that you are looking for?

https://github.com/bitnami/containers/blob/b3cd7969723cc1f29cf076d199ac80c1f6adab63/bitnami/redis-cluster/7.2/debian-11/rootfs/opt/bitnami/scripts/libredis.sh#L406-L408

Please, let us know!

**Comment by Zgreatgatsby** [comment]
Got it, thanks a lot!
