### ISSUE TITLE
PIP not working on Spark VENV

### ISSUE THREAD

**Issue by djpirra** [bitnami/containers#49313]
### Name and Version

bitnami/spark 3.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

If you activate Spark VENV environment and try to run PIP, it gives the below error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem'
```
### What is the expected behavior?

PIP should work as expected.

### What do you see instead?
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem'
```

**Comment by Mauraza** [comment]
Hi @djpirra,

Could you test with the last revision of 3.2?
```bash
$ docker images
REPOSITORY      TAG       IMAGE ID       CREATED        SIZE
bitnami/spark   3.2       61045d010dec   29 hours ago   1.35GB
```

**Comment by djpirra** [comment]
I was using this one:
docker.io/bitnami/spark:3.2.1

Which one is it now?

**Comment by Mauraza** [comment]
Hi @djpirra,

The last revision:
`docker pull bitnami/spark:3.2.4-debian-11-r141`

**Comment by djpirra** [comment]
Hi Ibone,

I am bounded to 3.2.1 since that is the latest runtime that Oracle
Dataflows supports.

Thank you

**Comment by Mauraza** [comment]
Hi @djpirra,

You can check if exits any revision that works. Check https://hub.docker.com/r/bitnami/spark/tags?page=1&name=3.2.1
