### ISSUE TITLE
Cannot do ldapbind with a regular user

### ISSUE THREAD

**Issue by hueyvle** [bitnami/containers#4931]
### Name and Version

bitnami/openldap

### What is the problem this feature will solve?

Some applications I'm working with doesn't have the option to specify bind user and bind password.  It would default to use whatever user/pass entered for bind operation. 

### What is the feature you are proposing to solve the problem?

Allow all users to bind

### What alternatives have you considered?

make everyone admin?

**Comment by Mauraza** [comment]
Hi @hueyvle,

Did you try to follow the [official documentation of OpenLDAP](https://www.openldap.org/doc/admin26/guide.html) with `llow bind_anon_cred`?

**Comment by hueyvle** [comment]
hi @Mauraza ,
anon binding wont works because the application by default issue bind with ldap name and password.  
anon binding requires empty password. 

But this issue has been resolved because I've made a mistake is setting basedn, (missing an ou), and that is why it doesn't work. 
By default, openldap puts everyone in ou=users. 

This is resolved.  Thanks!

**Comment by Mauraza** [comment]
Hi @hueyvle,

I am happy to know you solved the issue! Closing this out now, do not hesitate to write us back if you have any other questions.
