### ISSUE TITLE
Redis SSL env variable not working as expected

### ISSUE THREAD

**Issue by mrveera** [bitnami/containers#49325]
### Name and Version

bitnami/airflow:2.7.1-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.export AIRFLOW_REDIS_USE_SSL=yes 
2. Start airflow worker with external SSL enabled redis

### What is the expected behavior?

Ideally broker url of redis connection should have prefix of `rediss://`

### What do you see instead?

`redis://` prefix is being used to connect to ssl enabled redis cluster.

### Additional information

We are setting a flag called `redis_backend_use_ssl` in celery config as per below code

https://github.com/bitnami/containers/blob/bd776aa27af13af73f511c32a1cfaecd77b040c7/bitnami/airflow-scheduler/2/debian-11/rootfs/opt/bitnami/scripts/libairflow.sh#L405

But same flag is not being used in airflow codebase anywhere
https://github.com/search?q=repo%3Aapache%2Fairflow+redis_backend_use_ssl&type=code

**Comment by mrveera** [comment]
```bash
is_boolean_yes "$AIRFLOW_REDIS_USE_SSL" && airflow_conf_set "celery" "broker_url" "rediss://${redis_user}:${redis_password}@${REDIS_HOST}:${REDIS_PORT_NUMBER}/${REDIS_DATABASE}"
```

Adding this to libairflow.sh should solve this issue. 

@javsalgar  do you want me to raise PR with above change?

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
