### ISSUE TITLE
【bitnami/mysql:5.7】After MySQL deployment, it cannot be used

### ISSUE THREAD

**Issue by taoxiaoyin** [bitnami/containers#49350]
### Name and Version

bitnami/mysql:5.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1.执行进入容器命令，docker exec -it mysql-server1 bash
2.执行mysql命令，报如下错误
Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (111)

### What do you see instead?

Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (111)

### Additional information

1

**Comment by javsalgar** [comment]
Hi,

Do you mind changing the title to English?
