### ISSUE TITLE
[bitnami/openldap] Regression: Commit 817f66a prevents configuring custom LDIFs with LDAP_REQUIRE_TLS=yes

### ISSUE THREAD

**Issue by spresse1** [bitnami/containers#49575]
### Name and Version

bitnami/openldap:2.6.6-debian-11-r49

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure the container with LDAP_REQUIRE_TLS=yes (and with TLS configuration)
2. Configure the container with custom LDIFs in /ldifs
3. Attempt to start the container

### What is the expected behavior?

I expect that custom LDIFs are properly merged into the database.

### What do you see instead?
```
 17:52:31.02 INFO  ==> Loading custom LDIF files...
 17:52:31.13 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
650dd45f.375acd5e 0x7f139ffff700 conn=1002 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
650dd45f.3766329b 0x7f139ffff700 conn=1002 op=0 BIND dn="cn=admin,dc=my,dc=domain" method=128
650dd45f.37702c73 0x7f139ffff700 conn=1002 op=0 RESULT tag=97 err=13 qtime=0.000078 etime=0.000799 text=TLS confidentiality required
ldap_bind: Confidentiality required (13)
        additional info: TLS confidentiality required
650dd45f.3798e4ce 0x7f139f7fe700 conn=1002 op=1 UNBIND
650dd45f.379e2fe4 0x7f139f7fe700 conn=1002 fd=12 closed
```

**Comment by javsalgar** [comment]
Hi,

Do you have a sample custom LDIF that triggers the issue?

**Comment by spresse1** [comment]
Any ldif will do; I happen to be using this one from SAMBA: https://github.com/samba-team/samba/blob/master/examples/LDAP/samba.ldif

As far as I can tell, the problem is that this commit moves the ldif insertion to after encryption is required, then does not use encryption to upload it.

**Comment by aoterolorenzo** [comment]
Hi @spresse1,

Probably moving the ldif insertion between the `additional configuration` and right before `enable tls` would solve the issue preventing #49157 from happening again.

Would you like to contribute yourself with the fix in a Pull Request?

**Comment by Horstexplorer** [comment]
Hey, while addressing this issue, it would be nice that we might also tackle another slight inconsistency within the tls initialization.
It looks like that commit f7498e88758050180aba8042c87f1f7c202e1ef3 re-added the tls initialization into [line 600](https://github.com/bitnami/containers/blob/999554379234717cbd3cc52e4a70ee03a36a919a/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L600) while also being present in [line 621](https://github.com/bitnami/containers/blob/999554379234717cbd3cc52e4a70ee03a36a919a/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L621) for both the 2.5 and 2.6 version of the libopenldap.sh script.
While this likely will be ignored by openldap, it seems reasonable to only keep it at which location the initialization is actually desired.

**Comment by spresse1** [comment]
Pull request created to move the code.

**Comment by aoterolorenzo** [comment]
Not stale. @spresse1 sorry for the delay. I will take a look before the end of the week.
