### ISSUE TITLE
[bitnami/pgbouncer] When i use custom configure file to start pgbouncer container,but it's can not startup

### ISSUE THREAD

**Issue by goosby** [bitnami/containers#49836]
### Name and Version

bitnami/pgbouncer:1.20.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. 
```
docker version 
`[root@SCM-gitlab01 pgbouncer-config]# docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
3.  pgbouncer configure file
```
[databases]
  gitlab=host=***.***.***.*** port=5432 dbname=gitlab auth_user=gitlab connect_query='SELECT 1' timezone='Asia/Shanghai'
[pgbouncer]
  pool_mode = transaction
  ignore_startup_parameters = extra_float_digits
  logfile = /tmp/pgbouncer.log
  pidfile = /tmp/pgbouncer.pid
  listen_addr = *
  listen_port = 6432
  auth_type = md5
  auth_file = /opt/bitnami/pgbouncer/conf/userlist.txt
  max_client_conn = 100
  default_pool_size = 20
  min_pool_size = 5
  reserve_pool_size = 5
  reserve_pool_timeout = 5
```

4. userlist.txt
```
"gitlab" "****************"
"gitlab" "*****************************************"
```

5. exec command
```
docker run -it -e TZ=Asia/Shanghai -v /opt/pgbouncer-config/:/bitnami/pgbouncer/conf/ -p 6433:6432 --name=pgbouncer -d bitnami/pgbouncer:1.20.1`
when i run start command ,bitnami/pgbouncer:1.20.1 console out put
`pgbouncer 14:19:05.72 
pgbouncer 14:19:05.73 Welcome to the Bitnami pgbouncer container
pgbouncer 14:19:05.73 Subscribe to project updates by watching https://github.com/bitnami/containers
pgbouncer 14:19:05.74 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgbouncer 14:19:05.74 
pgbouncer 14:19:05.78 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 14:19:05.82 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 14:19:05.83 ERROR ==> POSTGRESQL_PASSWORD must be set
```

why ?

### What do you see instead?

![image](https://github.com/bitnami/containers/assets/5524762/d9073981-b7a6-49bb-8c49-4da628642286)
![image](https://github.com/bitnami/containers/assets/5524762/c09242a2-ccc9-4f5e-857d-c309483e8ac9)

**Comment by jotamartos** [comment]
Hi @goosby,

Thank you for reporting this issue. I do not have full details of the different env vars you are using but I think you can solve this issue by following these instructions:

- You set the POSTGRESQL_USERNAME and POSTGRESQL_PASSWORD to access the database as well as the POSTGRESQL_HOST parameter. 
- You include extra user/password configuration in the PGBOUNCER_USERLIST env var

>Note: Use the rest of env vars you are using right now when deploying the solution

This will build the the userlist.txt file with the different user/password configuration 

https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L205

and you will not get the error you mentioned above. 

However, we welcome you to contribute and create a Pull Request to update the code if needed. The error is generated in [this section](https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L60) of the libpgbouncer.sh script. The team will be more than happy to review the changes and propose any changes as well. 

Thanks
