### ISSUE TITLE
[bitnami/openldap] Unable to create ldap users/groups using custom ldif files

### ISSUE THREAD

**Issue by rohan-97** [bitnami/containers#4984]
### Name and Version

bitnami/openldap:2.6.3-debian-11-r16

### What steps will reproduce the bug?

I have written following LDIF file in order to create a group

```
dn: dc=testdomain, dc=com
objectClass: top
objectClass: domain


dn: ou=groups,dc=testdomain,dc=com
objectClass: organizationalUnit

dn: cn=testgroup,ou=groups,dc=testdomain,dc=com
description: A sample group for testing purpose
objectClass: posixGroup
objectClass: top
gidNumber: 202
memberUid: testgroup
```

1. add above file under /boostrap/ldif directory inside container by creating directory structure under [containers/bitnami/openldap/2.6/debian-11/rootfs](https://github.com/bitnami/containers/tree/main/bitnami/openldap/2.6/debian-11/rootfs)

2. Build docker image from [this](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/Dockerfile) docker file using following command
```
docker build -t test-ldap .
```

3. run the docker image using following command

```
docker run --detach --rm --name test-openldap22   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env "LDAP_ROOT=dc=testdomain,dc=com" --env "LDAP_SKIP_DEFAULT_TREE=yes"  test-ldap
```

4. connect to the docker container using following command
```
docker exec -it <container-id> /bin/bash
```

5.  Check database contents using slapcat comand
```
slapcat -F /opt/bitnami/openldap/etc/slapd.d
```
Note: I am using -F flag as without -F it dosen't work refer issue : https://github.com/bitnami/containers/issues/4650

```
I have no name!@cb4041c308e1:/$ slapcat -F /opt/bitnami/openldap/etc/slapd.d
The first database does not allow slapcat; using the first available one (2)
```

### What is the expected behavior?

I was expecting to see group testgroup as an output of slapcat command.

### What do you see instead?

instead I got this output

The first database does not allow slapcat; using the first available one (2).

If I don't set `LDAP_SKIP_DEFAULT_TREE=yes` then I see the default entries in LDAP but still I don't see entries generated by custom LDIF file.

### Additional information

I don't have much experience in LDAP and my questions might be basic.

However it would be great if there would be a documentation or `example` directory where we see steps/examples of how we can add custom users using ldif files to LDAP or add csutom schema to LDAP.

Thanks in advance :)

**Comment by Mauraza** [comment]
Hi @rohan-97, 

Did you check the environment variables related to ldif in the [README.md](https://github.com/bitnami/containers/tree/main/bitnami/openldap#configuration)?

> You can bootstrap the contents of your database by putting LDIF files in the directory /ldifs (or the one you define in LDAP_CUSTOM_LDIF_DIR). Those may only contain content underneath your base DN (set by LDAP_ROOT). You can not set configuration for e.g. cn=config in those files.

**Comment by rohan-97** [comment]
Hi @Mauraza,   
Thanks for the response!
Somehow I missed the LDAP_CUSTOM_LDIF_DIR env variable.   
After adding the LDAP_CUSTOM_LDIF_DIR  env variable, the LDIF changes were applied successfully.

**Comment by Mauraza** [comment]
Hi @rohan-97,

I'm glad that the env variable works! Closing this out now, do not hesitate to write us back if you have any other questions.

**Comment by rohan-97** [comment]
I have one more doubt.

I have a custom LDAP schema file which is as follows

```
objectidentifier customBusinessRolePermissionSchema 1.3.6.1.4.1.920.002
objectidentifier customBusinessRolePermissionAttrs customBusinessRolePermissionSchema:3
objectidentifier customBusinessRolePermissionOCs customBusinessRolePermissionSchema:4

attributetype ( customBusinessRolePermissionAttrs:1
          NAME 'permissionInfo'
          DESC 'description of permission'
          EQUALITY caseIgnoreMatch
          SUBSTR caseIgnoreSubstringsMatch
          SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{32} )
attributetype ( customBusinessRolePermissionAttrs:2
          NAME 'permissionName'
          DESC 'Name of permission'
          EQUALITY caseIgnoreMatch
          SUBSTR caseIgnoreSubstringsMatch
          SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{32} )
attributetype ( customBusinessRolePermissionAttrs:3
          NAME 'attribute'
          DESC 'This holds key/value pair of ldif attributes separated by = which will be applied to user'
          EQUALITY caseIgnoreMatch
          SUBSTR caseIgnoreSubstringsMatch
          SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{255} )
attributetype ( customBusinessRolePermissionAttrs:4
          NAME 'group'
          DESC 'Colon separated group value group_name:attribute_name:user_attribute'
          EQUALITY caseIgnoreMatch
          SUBSTR caseIgnoreSubstringsMatch
          SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{255} )
attributetype ( customBusinessRolePermissionAttrs:5
          NAME 'command'
          DESC 'command to execute'
          EQUALITY caseIgnoreMatch
          SUBSTR caseIgnoreSubstringsMatch
          SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{255} )
objectClass ( customBusinessRolePermissionOCs:1
            NAME 'customBusinessRolePermissions'
        DESC 'Describe a Group Object Policy'
        SUP ( top ) AUXILIARY
        MAY ( attribute $ group $ command )
        MUST ( permissionInfo $ permissionName ) )objectidentifier customBusinessRoleSchema 1.3.6.1.4.1.920.001
```

I  have saved this file custom.ldif under following path
`/containers/bitnami/openldap/2.6/debian-11/rootfs/schema`

However when I build docker image with this file and try to create a docker instance, the docker container crashes.

with docker logs, I found the following logs
```
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# docker logs -f  $(docker run --detach --rm --name test-openldap39   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env "LDAP_ROOT=dc=protegrity,dc=com" --env "LDAP_SKIP_DEFAULT_TREE=yes" --env "LDAP_CUSTOM_LDIF_DIR=/bootstrap/ldif"  nusta-ldap) 
 09:59:53.41 INFO  ==> ** Starting LDAP setup **
 09:59:53.46 INFO  ==> Validating settings in LDAP_* env vars
 09:59:53.47 INFO  ==> Initializing OpenLDAP...
 09:59:53.48 INFO  ==> Creating LDAP online configuration
 09:59:53.51 INFO  ==> Starting OpenLDAP server in background
 09:59:53.54 INFO  ==> Configure LDAP credentials for admin user
 09:59:53.55 INFO  ==> Adding LDAP extra schemas
 09:59:53.57 INFO  ==> Adding custom Schema : /schema/custom.ldif ...
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# 
```

I believe the variable `LDAP_CUSTOM_SCHEMA_FILE` expects the file to be in ldif format and does not support LDAP schema files.
Is there any provision to add LDAP schema files as well?
Thanks in advance

**Comment by Mauraza** [comment]
Hi @rohan-97,

Did you try it with `LDAP_CUSTOM_SCHEMA_FILE`? Did you get any errors?

**Comment by rohan-97** [comment]
Hi @Mauraza ,  

I tried it with `LDAP_CUSTOM_SCHEMA_FILE`

following is the command that I tried
```
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# docker run --detach --rm --name test-openldap40   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env "LDAP_ROOT=dc=protegrity,dc=com" --env "LDAP_SKIP_DEFAULT_TREE=yes" --env "LDAP_CUSTOM_LDIF_DIR=/bootstrap/ldif" --env "LDAP_CUSTOM_SCHEMA_FILE=/bootstrap/schema/pty-permissions.schema"  nusta-ldap
0572b7c2803d2eed47ff77c87fbcb246c611b9f7e107963cf4239cf9a66fadb6
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# docker exec -it 0572b7c2803d2eed47ff77c87fbcb246c611b9f7e107963cf4239cf9a66fadb6 bash
Error: No such container: 0572b7c2803d2eed47ff77c87fbcb246c611b9f7e107963cf4239cf9a66fadb6
```

Also to catch errors, I tried to wrap above command with docker logs -f comand which is as follows

```
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# docker logs -f  $(docker run --detach --rm --name test-openldap40   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env "LDAP_ROOT=dc=protegrity,dc=com" --env "LDAP_SKIP_DEFAULT_TREE=yes" --env "LDAP_CUSTOM_LDIF_DIR=/bootstrap/ldif" --env "LDAP_CUSTOM_SCHEMA_FILE=/bootstrap/schema/pty-permissions.schema"  nusta-ldap) 
 15:00:11.31 INFO  ==> ** Starting LDAP setup **
 15:00:11.36 INFO  ==> Validating settings in LDAP_* env vars
 15:00:11.38 INFO  ==> Initializing OpenLDAP...
 15:00:11.40 INFO  ==> Creating LDAP online configuration
 15:00:11.42 INFO  ==> Starting OpenLDAP server in background
 15:00:11.44 INFO  ==> Configure LDAP credentials for admin user
 15:00:11.45 INFO  ==> Adding LDAP extra schemas
 15:00:11.47 INFO  ==> Adding custom Schema : /bootstrap/schema/pty-permissions.schema ...
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# 
```

when I remove LDAP_CUSTOM_SCHEMA_FILE environment variable, the container works fine as follows

```
root@ip-10-31-2-117:~/containers/bitnami/openldap/2.6/debian-11# docker logs -f  $(docker run --detach --rm --name test-openldap40   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env "LDAP_ROOT=dc=protegrity,dc=com" --env "LDAP_SKIP_DEFAULT_TREE=yes" --env "LDAP_CUSTOM_LDIF_DIR=/bootstrap/ldif"  nusta-ldap) 
 15:00:49.28 INFO  ==> ** Starting LDAP setup **
 15:00:49.32 INFO  ==> Validating settings in LDAP_* env vars
 15:00:49.33 INFO  ==> Initializing OpenLDAP...
 15:00:49.35 INFO  ==> Creating LDAP online configuration
 15:00:49.37 INFO  ==> Starting OpenLDAP server in background
 15:00:49.39 INFO  ==> Configure LDAP credentials for admin user
 15:00:49.40 INFO  ==> Adding LDAP extra schemas
 15:00:49.42 INFO  ==> Loading custom LDIF files...
 15:00:49.43 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
 15:00:49.52 WARN  ==> 
 15:00:50.53 INFO  ==> ** LDAP setup finished! **

 15:00:50.56 INFO  ==> ** Starting slapd **
631760a2.22194d68 0x7fd642afc740 @(#) $OpenLDAP: slapd 2.6.3 (Aug 18 2022 11:04:07) $
        @08fcc76769c1:/bitnami/blacksmith-sandox/openldap-2.6.3/servers/slapd
631760a2.22c00b5a 0x7fd642afc740 slapd starting
```

I am also looking for exact openldap error,
Is there any other effective way to catch errors which I can try out?

Thanks

**Comment by rohan-97** [comment]
I was looking at the script which adds custom schema into ldap and I ended up in [here](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L364)

the command which was being executed was as follows

```
debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l  "$LDAP_CUSTOM_SCHEMA_FILE"
```
where
LDAP_ONLINE_CONF_DIR = /bitnami/openldap/slapd.d
and
LDAP_CUSTOM_SCHEMA_FILE is path of custom schema file.


when I tried to execute same command in bitnami openldap container I got following output

```
I have no name!@59b445c57358:/$ slapadd -F /bitnami/openldap/slapd.d -n 0 -l /bootstrap/schema/pty-permissions.schema 
str2entry: entry -1 has no dn
slapadd: could not parse entry (line=1)
Closing DB...
```

as it is looking for dn,
does it mean that LDAP_CUSTOM_SCHEMA_FILE environment variable supports schema files with LDIF format and not the [openldap schema specs](https://www.openldap.org/doc/admin23/schema.html#Extending%20Schema)?

**Comment by rohan-97** [comment]
In order to add custom schema file via slapd.conf I added following slapd.conf file in the container

```
I have no name!@59b445c57358:/$ cat /opt/bitnami/openldap/etc/openldap/slapd.conf 
# This is the main slapd configuration file. See slapd.conf(5) for more
# info on the configuration options.

#######################################################################
# Global Directives:

# Schema and objectClass definitions
include         /bootstrap/schema/pty-permissions.schema
```

the full path of slapd.conf file inside container is 
```
/opt/bitnami/openldap/etc/openldap/slapd.conf
```

then I tried to addd an entry which uses `customBusinessRolePermissions` object class.
and tried to add following ldif file using slapadd command

```
dn: cn=test_perm,ou=permissions,dc=testdomain,dc=com
objectClass: customBusinessRolePermissions
objectClass: device
permissionName: "test_permisssion"
permissionInfo: "Sample test permission"
attribute: key=value
cn: test_perm
```

I got following output

```
I have no name!@59b445c57358:/$ ldapadd -H ldap://localhost:1389  -D "cn=admin,dc=testdomain,dc=com" -w adminpassword -f /rohan/test.ldif 
adding new entry "cn=test_perm,ou=permissions,dc=testdomain,dc=com"
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #0 invalid per syntax
```

**Comment by gutmensch** [comment]
@rohan-97 FWIW I would suggest to just use the ldif schema format one time in a container and then store the ldif somewhere, short "how to" that I noted myself
```
mkdir ldif
slaptest -f new.schema -F ldif/
config file testing succeeded
```

1. replace dn: cn=config with `dn: cn=new,cn=schema,cn=config`

2. keep only the following kv, followed by olcAttributeTypes and olcObjectClasses

```
dn: cn=new,cn=schema,cn=config
cn: new
objectClass: olcSchemaConfig
...
```

Then for your resulting container, mount the ldif file as new schema file in your container, e.g. `-v ./new.ldif:/opt/bitnami/openldap/etc/schema/new.ldif` and provide the env variable including all schemas that you want to use during init, for instance

```
LDAP_EXTRA_SCHEMAS="inetorgperson,cosine,new"
```

**Comment by Mauraza** [comment]
Hi @rohan-97, did you check the comment of @gutmensch?

**Comment by rohan-97** [comment]
Hi @gutmensch and @Mauraza ,

Apologies for the delayed response.

I tried the steps provided and was able to add my custom schema to the OpenLDAP.
I appreciate the quick support!

Thanks a lot for helping me out 🙂
