### ISSUE TITLE
[bitnami/postgresql] Add postgresql 16 image

### ISSUE THREAD

**Issue by jonesbusy** [bitnami/containers#49856]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Just add support for Postgres 16 that's is available since some weeks ago (https://hub.docker.com/_/postgres or https://www.postgresql.org/about/news/postgresql-16-released-2715/)

### What is the feature you are proposing to solve the problem?

I know the bitnami system track upstream changes, but I don't know if there is such thing in place for postgres major version

### What alternatives have you considered?

Well.. Use 15, but I would like to directly deploy my chart using 16

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by AntonOfTheWoods** [comment]
@carrodher , as a matter of interest, are there any web-visible links to these issues (like a failed job, whatever)? Thanks!

**Comment by jonesbusy** [comment]
Is there (apparently): https://hub.docker.com/r/bitnami/postgresql/tags?page=1&name=16.0.0

**Comment by carrodher** [comment]
Yes, the container image was released a couple of days ago at https://github.com/bitnami/containers/pull/50017; now we're working on the Helm chart. We'll close this issue once all deployment kinds are available, but if you are only interested in the container, it is already published! Enjoy it 😉
