### ISSUE TITLE
Images published to ecr-public are not multi-arch, while docker hub are

### ISSUE THREAD

**Issue by bsmedberg-xometry** [bitnami/containers#49895]
### Name and Version

public.ecr.aws/bitnami/python:3.11.5-debian-11-r28

### What is the problem this feature will solve?

bitnami already publishes multi-arch amd64/arm64 images on docker hub. However the images on ECR-public are amd64-only.

This appears to be true "across the board" in ECR-public: I've at least spot-checked node, python, and nginx containers.

I asked our AWS support rep whether this was something that would be fixed by AWS or by bitnami, and they indicated that this was bitnami's responsibility.

### What is the feature you are proposing to solve the problem?

I would like the same multi-arch images that are pushed to docker-hub to also go to ECR-public.

I am happy to help out with this if this is work that can be done by outside people, although a brief search of the repository didn't find any automation scripts which actually perform the uploads.

**Comment by carrodher** [comment]
Thanks for using Bitnami containers. Unfortunately, we haven’t been able to give it higher priority in the context of other initiatives we are working on, because of that, for now, multi-arch images are only available in DockerHub.

We cannot give an estimate as to when it might be available at ECR Public Gallery

**Comment by ku524** [comment]
This is crucial from a cost perspective. Your consideration would be greatly appreciated.

**Comment by carrodher** [comment]
We understand that point, but unfortunately, we cannot give an estimate as to when it might be available at the ECR Public Gallery at this moment.
