### ISSUE TITLE
[bitnami/redis-cluster] Unable to connect to Redis Cluster from Host Machine using Python 

### ISSUE THREAD

**Issue by rbharad27** [bitnami/containers#49893]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

Running RedisCluster on Docker in Windows

Redis Cluster is running and accessible from within 1 of the nodes
But not from the host machine via Python script (outside Docker)

**ERROR:** 
raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.

**RUN steps (cmds):**
**_Approach 1:_** 
```
curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/redis-cluster/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

**_Approach 2:_** 

```
docker network create redis-cluster-network --driver bridge


docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis1 --network redis-cluster-network -p 6379:6379 -d bitnami/redis-cluster:latest																								
docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis2 --network redis-cluster-network -p 6380:6379 -d bitnami/redis-cluster:latest																												
docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis3 --network redis-cluster-network -p 6381:6379 -d bitnami/redis-cluster:latest																									
docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis4 --network redis-cluster-network -p 6382:6379 -d bitnami/redis-cluster:latest																														
docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis5 --network redis-cluster-network -p 6383:6379 -d bitnami/redis-cluster:latest																														
docker run -e ALLOW_EMPTY_PASSWORD=yes -e REDIS_NODES=redis1,redis2,redis3,redis4,redis5,redis6 --name redis6 --network redis-cluster-network -p 6384:6379 -d bitnami/redis-cluster:latest

docker exec -it redis1 redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379 --cluster-replicas 1 --cluster-yes
```

### What is the expected behavior?

Able to connect from outside docker (Host Machine)

### What do you see instead?

raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.

### Additional information

Python connection script:
```

from rediscluster import RedisCluster

startup_nodes = [{"host": "localhost", "port": "6379"}]

# Change SSL iif needed
ssl = True
password = "bitnami"
if ssl:
    #rds_cls = RedisCluster(startup_nodes=startup_nodes, ssl=True, ssl_cert_reqs=False, password=password, decode_responses=True, skip_full_coverage_check=True, read_from_replicas=True)
    rds_cls = RedisCluster(startup_nodes=startup_nodes, ssl=True, ssl_cert_reqs=False, password=password, decode_responses=True, skip_full_coverage_check=True)
else:
    #rds_cls = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=True, read_from_replicas=True)
    rds_cls = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=True)

#print(rds_cls.get_nodes())
rds_cls.ping()
print(rds_cls.ping()) 
```

**Comment by rbharad27** [comment]
Docker Desktop 4.23.0 (120376)
Python3.7 (redis-py-cluster==2.1.3)
Windows 10

**Comment by rbharad27** [comment]
**_For Approach 2_** (docker run cmds) error received is 

    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10060 connecting to 172.19.0.2:6379. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by javsalgar** [comment]
Hi,

I'm afraid this is due to a limitation on how docker networking works in Docker for Windows. In order to connect from outside, you need to have all redis nodes externally available. In solutions like Docker for Linux it is possible to access to all nodes externally but that may not be the case with Docker for Windows. My advice would be to check with Docker for Windows developers or use the bitnami/redis-cluster helm chart with the `externalAccess` section enabled.

**Comment by Tuki277** [comment]
HI @rbharad27 Has the issue been fixed yet? I'm also having the same error
