### ISSUE TITLE
[bitnami/redis-sentinel] REDIS_SENTINEL_USER environment

### ISSUE THREAD

**Issue by Cronist** [bitnami/containers#50027]
### Name and Version

bitnami/redis-sentinel

### What is the problem this feature will solve?

adding username to sentinel AUTH additionally to password.

### What is the feature you are proposing to solve the problem?

adding username to sentinel AUTH additionally to password.

### What alternatives have you considered?

there is no.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team for evaluation. If you want to speed up the process, would you like to submit a PR?
