### ISSUE TITLE
[bitnami/elasticsearch] 8.10.2 health check fail 

### ISSUE THREAD

**Issue by hpsocket** [bitnami/containers#50113]
### Name and Version

bitnami/elasticsearch:8.10.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I upgrade elasticsearch from 8.8.1 to 8.10.2 today, but found that health check fail.
Then I login the container and run `/opt/bitnami/scripts/elasticsearch/healthcheck.sh` manually, get the following output:
```
I have no name!@e14d5b4da1ac:/$ /opt/bitnami/scripts/elasticsearch/healthcheck.sh
elasticsearch 16:28:47.27 INFO  ==> Checking Elasticsearch health...
I have no name!@e14d5b4da1ac:/$ echo $?
35
I have no name!@e14d5b4da1ac:/$ 
I have no name!@e14d5b4da1ac:/$ curl http://localhost:9200/_cluster/health?local=true
{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":141,"active_shards":141,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":15,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":90.38461538461539}
```

As the above show,  execute `curl http://localhost:9200/_cluster/health?local=true` manually is OK .

### What is the expected behavior?

heal check succ

### What do you see instead?

health check fail, and the cmd exit code is 35

**Comment by hpsocket** [comment]
I work around this issue by defined 2 env:
```
ELASTICSEARCH_ENABLE_SECURITY=false
ELASTICSEARCH_ENABLE_REST_TLS=false
```

`ELASTICSEARCH_ENABLE_REST_TLS` default value is `true`, then uses https, and make health check fail .

**Comment by javsalgar** [comment]
Hi,

This may be because in the new version, we enable security by default, so in the case of an existing installation you may need to use this workaround and change the settings in order to allow security and TLS

**Comment by migruiz4** [comment]
Hi there!

We released a new version that would fix this issue, could you please try using the latest tag `8.10.2-debian-11-r7`?

**Comment by yelnyleenew** [comment]
where is elasticsearch_healthcheck？
