### ISSUE TITLE
Unable to modify a vcard imported lead

### ISSUE THREAD

**Issue by pnwbob** [bitnami/containers#50112]
### Name and Version

bitnami/suitecrm

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Running as a docker container
2. Using a separate mariadb install which is 11.0.3
3. Run the compose files shown below

[docker-compose_files.zip](https://github.com/bitnami/containers/files/12735556/docker-compose_files.zip)

### What is the expected behavior?

It should produce a functioning suitecrm application. I imported a lead from a vcard and I should be able to edit the lead and save the changes.

### What do you see instead?

Every time I edit an imported lead and I hit save I get the message: "There are validation errors, unable to perform action."
![image](https://github.com/bitnami/containers/assets/88961717/fe86f26d-8e66-4a06-b8e7-c19969ae9fd1)

### Additional information

It works with created leads, but not imported vcard leads

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami SuiteCRM container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
