### ISSUE TITLE
[<Spring Cloud Data Flow>] <Docker Image Version 2.11.0>

### ISSUE THREAD

**Issue by rallepalle** [bitnami/containers#50249]
### Describe your suggestion as much as you can

Hi Bitnami-Team,
when can we expect the latest Docker Image version 2.11.0 for Spring Cloud Data Flow ? 
https://github.com/spring-cloud/spring-cloud-dataflow/releases/tag/v2.11.0

regards,
Ralph

**Comment by carrodher** [comment]
This new version was released yesterday at https://github.com/bitnami/containers/pull/50157.
You can find the container image in [DockerHub](https://hub.docker.com/layers/bitnami/spring-cloud-dataflow/2.11.0-debian-11-r0/images/sha256-a2f549d82ddbf9852ee49c9ef0fbd2ca4b15753058d023fb1ddde2f25eea9386?context=explore).
