### ISSUE TITLE
[bitnami/symfony] Ho to Install PHP EXT

### ISSUE THREAD

**Issue by Hubert9311** [bitnami/containers#50300]
### Name and Version

bitnami/symfony:6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

How to Install php ext in container ?

### What do you see instead?

php ext  not working

**Comment by javsalgar** [comment]
Hi,

Could you elaborate more your use case? Which extension do you want to install?

**Comment by Hubert9311** [comment]
Hi I want to install PHP Imagick. I use docker desktop on windows wsl2  integration

**Comment by javsalgar** [comment]
Hi,

In this case, I'm afraid that you'll need to create your own fork of the container. This guide for php-fpm could be useful for this use case https://docs.bitnami.com/tutorials/create-custom-php-fpm-container-mongodb-support/
