### ISSUE TITLE
[bitnami/kafka] Do not reload config when restart container, while KAFKA_MOUNTED_CONF_DIR mounted.

### ISSUE THREAD

**Issue by itshikanov** [bitnami/containers#50377]
### Name and Version

bitnami/kafka:3.5.1-debian-11-r64

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello. 

Config dir mounted in /bitnami/kafka/config/
If change config and restart container, the new config does not apply.
example
```yaml
    volumes:
      - "{{ kafka_conf_dir }}:/bitnami/kafka/config"
      - "{{ kafka_data_dir }}:/bitnami/kafka/data"
```
I.m update bitnami image from bitnami/kafka:2.7.0-debian-10-r0. In old image all work well.

The problem in file /opt/bitnami/scripts/kafka/setup.sh in line 42 and condition.
```bash
[[ ! -f "$KAFKA_CONF_FILE" ]] && kafka_initialize
```
After kafka_initialize, the config file is copied to `/opt/bitnami/kafka/config/server.properties` and after restarting the container this condition is not satisfying.

### What is the expected behavior?

Apply config after restart container

### What do you see instead?

The config is not applying after restart container

**Comment by itshikanov** [comment]
found the workaround

```
    entrypoint: /bin/bash
    command: -c "rm -f /opt/bitnami/kafka/config/server.properties; exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh"

```

**Comment by andresbono** [comment]
Hi @itshikanov, it's great that you found a workaround! Please also note that an alternative would be to remove the container, not only to stop/start it. `/opt/bitnami/kafka/config/server.properties` is not persisted by default, so `kafka_initialize` would run again.
