### ISSUE TITLE
[bitnami/supabase-postgres] Postgres: ARM support

### ISSUE THREAD

**Issue by J4NS-R** [bitnami/containers#50419]
### Name and Version

bitnami/supabase-postgres, bitnami/supabase-postgres-meta

### What is the problem this feature will solve?

Running the [Supabase helm chart](https://bitnami.com/stack/supabase/helm) on a cluster running on ARM CPUs. 

### What is the feature you are proposing to solve the problem?

Build the supabase-postgres and supabase-postgres-meta images on ARM and push it.

### What alternatives have you considered?

I could run the `bitnami/postgresql` (which does support ARM), but it doesn't have all the plugins required for supabase.

**Comment by javsalgar** [comment]
Hi,

I'm afraid we were unable to build it in our systems with ARM support, so right now we don't have support for it. We may revisit this in the future (maybe the supabase-postgres get more ARM support in the future), but for the time being we do not have immediate plans to work on it.
