### ISSUE TITLE
KAFKA_MOUNTED_CONF_DIR can't be overridden

### ISSUE THREAD

**Issue by nosammai** [bitnami/containers#50747]
### Name and Version

bitnami/kafka:3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
❯ docker run -it -e KAFKA_MOUNTED_CONF_DIR=/test bitnami/kafka:latest env | grep MOUNTED
KAFKA_MOUNTED_CONF_DIR=/bitnami/kafka/config
```

### What is the expected behavior?

The readme states that you can override KAFKA_MOUNTED_CONF_DIR to a different directory. I would expect that I can set this to a different directory and my configuration will be read from that directory.

https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#full-configuration

### What do you see instead?

Configuration is read from the default directory `/bitnami/kafka/config`

### Additional information

It looks like the value for the env var is hardcoded and won't be overridden by setting it in docker:
https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.5/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh#L71

**Comment by migruiz4** [comment]
Hi @nosammai,

Thank you for your suggestion! I have implemented the change internally and a new version of the `bitnami/kafka` image for all branches should be available soon making the KAFKA_MOUNTED_CONF_DIR env variable customizable.
