### ISSUE TITLE
[bitnami/moodle] Allow to install Moodle with the customized config.php

### ISSUE THREAD

**Issue by nohattee** [bitnami/containers#50749]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

I cannot install Moodle with my customized config.php

### What is the feature you are proposing to solve the problem?

The problem:
- When I mapped the existing config.php to the container and ran it, the container was exited with code 1. After investigating, I found that you are using the `admin/cli/install.php` to install Moodle. That command would ignore and not install if we had the existing config.php. I suggest adding another installation when we have the existing config.php with this command `admin/cli/install_database.php`.
Ref issue: https://github.com/bitnami/containers/blob/main/bitnami/moodle/4.2/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L324

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the suggestion. Would you like to contribute with a PR to `libmoodle.sh`?
