### ISSUE TITLE
[bitnami/wordpress] Add env var to disable XML-RPC 

### ISSUE THREAD

**Issue by kimdre** [bitnami/containers#50755]
### Name and Version

bitnami/wordpress:latest

### What is the problem this feature will solve?

Since XML-RPC is a known vulnerability and only kept for backward compatibility, you should be able to disable it straight away for new wordpress instances.

### What is the feature you are proposing to solve the problem?

It would be great to have the option to set this directly as a env var, that then maybe will add a rule to the .htaccess file:
```
# Block WordPress xmlrpc.php requests
<Files xmlrpc.php>
order deny,allow
 deny from all
#allow from 123.123.123.123
</Files>
```

### What alternatives have you considered?

There are also alternative solutions like installing a plugin that blocks these requests or adding a filter in a child theme. But I think these solutions are pretty overkill.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
