### ISSUE TITLE
Expose mastodon build steps.

### ISSUE THREAD

**Issue by robermar23** [bitnami/containers#50764]
### Name and Version

bitnami/mastodon:4.2.0

### What is the problem this feature will solve?

I deploy Mastodon in Kubernetes using the Bitnami Matodon Helm Chart which uses the mastodon container image that is based off of the Dockerfile in this repo. 

`bitnami/mastodon:4.2.0`

Right now, the dockerfile for mastodon in this repo doesn't build Mastodon, but downloads what seems to be a custom mastodon build located, currently, here:
`https://downloads.bitnami.com/files/stacksmith/mastodon-4.2.0-0-linux-amd64-debian-11.tar.gz`

I was wondering if you would be willing to share the steps bitnami takes to build that tar file?

### What is the feature you are proposing to solve the problem?

I have forked Mastodon for some personal customizations and would like to use that as my source for putting together an image I can effectively use with the Bitnami Mastodon Helm Chart (which I love).

**Comment by robermar23** [comment]
Thanks for the reply @carrodher 

I believe I was able to reconstruct the critical pieces in your initialization logic by extracting the contents and reviewing `BUILD.txt`.

I created a "build" stage in my dockerfile that applies the same logic and then merges in my forked mastodon source.

I was able to successfully deploy this new image with the Helm chart Bitnami has created for Mastodon.

It is working great so far.

If you are willing to reply with your exact initialization logic, I'd feel more confident in my solution, of course, but I certainly don't expect it.

**Comment by carrodher** [comment]
Thank you for your understanding, there are some pieces of that logic or compilation instruction that are not totally public.
Publicly available you can find the bash scripts with the container logic at https://github.com/bitnami/containers/tree/main/bitnami/mastodon, the Helm chart templates at https://github.com/bitnami/charts/tree/main/bitnami/mastodon and any other resulting file of extracting the mentioned "stacksmith" tarball.

**Comment by robermar23** [comment]
Closing.  The custom dockerfile I put in place is working well enough for us to continue to use the Bitnami Mastodon Helm Chart.

Thanks for getting back to me.
