### ISSUE TITLE
[bitnami/magento] Changing character set for mysql connection doesn't work

### ISSUE THREAD

**Issue by mottolini** [bitnami/containers#51001]
### Name and Version

bitnami/magento:2.4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The environment variables `MYSQL_CLIENT_CREATE_DATABASE_CHARACTER_SET` and `MYSQL_CLIENT_CREATE_DATABASE_COLLATE` are used during the creation of the database, which is correctly created with what is specified, but they don't change the way the mysql client of Magento "deal" with the system afterwards. This means that all tables are always created with character set `utf8`, because this is hardcoded in the file **/bitnami/magento/app/etc/env.php**. 

### What is the expected behavior?

Those env variables, or a new one, should also modify the `initStatements` property in the `db` section of the /opt/bitnami/magento/app/etc/env.php file, like in this example:

```
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => 'eligo-mariadb:3306',
                'dbname' => 'magento',
                'username' => 'magento',
                'password' => '',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8mb4;',
                'active' => '1',
                'driver_options' => [
                    1014 => false
                ]
            ]
        ]
    ],
```

### What do you see instead?

The `initStatements` property in the `db` section of the /opt/bitnami/magento/app/etc/env.php file is always set to `'SET NAMES utf8'`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by mottolini** [comment]
It seems, base on documentation at https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/advanced.html, that there is the magento option `--db-init-statements` (by default set to `SET NAMES utf8;`). 

I would try to change the `magento_initialize` function in libmagento.sh to support it
