### ISSUE TITLE
[bitnami/kubectl] GKE authentication plugin

### ISSUE THREAD

**Issue by todorspg** [bitnami/containers#51039]
### Name and Version

bitnami/kubectl

### What is the problem this feature will solve?

I need a way to install or use the GKE authentication plugin.

### What is the feature you are proposing to solve the problem?

maybe have gke auth plugin  preinstalled in the image

### What alternatives have you considered?

I tried to manually install it but to no success

**Comment by javsalgar** [comment]
Hi,

Did you try creating a fork of the container? Which error did you find?
