### ISSUE TITLE
[bitnami/moodle] using (local) volume for local plugin is not possible

### ISSUE THREAD

**Issue by rroblik** [bitnami/containers#51052]
### Name and Version

bitnami/moodle:4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

(existing moodle installation, database bootstraped)

1. Run moodle with following volumes:
```yaml
# ...
    volumes:
      - ./moodledata:/bitnami/moodledata:Z
      - ./local:/bitnami/moodle/local
```
2. Start the container `docker compose up`
3. The container won't start, log bellow :
```
lms-moodle-1  | realpath: /bitnami/apache/conf: No such file or directory
lms-moodle-1  | moodle 12:07:50.04 INFO  ==> Configuring Apache ServerTokens directive
lms-moodle-1  | moodle 12:07:50.14 INFO  ==> Configuring PHP options
lms-moodle-1  | moodle 12:07:50.14 INFO  ==> Setting PHP expose_php option
lms-moodle-1  | moodle 12:07:50.16 INFO  ==> Setting PHP output_buffering option
lms-moodle-1  | moodle 12:07:50.22 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
lms-moodle-1  | moodle 12:07:50.24 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
lms-moodle-1  | moodle 12:07:50.44 INFO  ==> Restoring persisted Moodle installation
lms-moodle-1  | moodle 12:07:50.49 INFO  ==> Trying to connect to the database server
lms-moodle-1  | grep: /opt/bitnami/moodle/config.php: No such file or directory
lms-moodle-1 exited with code 2
```

### What is the expected behavior?

The container start, with `/bitnami/moodle/local` mounted in, so I can easily develop my custom plugins without rebuild all the app in Dockerfile during dev.

### What do you see instead?

Container won't start

### Additional information

With the [recommended way to use persistence](https://github.com/bitnami/containers/blob/main/bitnami/moodle/README.md#persisting-your-application) my volumes must look like : 
```yaml
  volumes:
    - ./moodledata:/bitnami/moodle
```

But with this way of volume mounting, all the moodle "core" files are local, so upgrading moodle using update of the Dockerfile (or through the docker compose file) will not succeed, as the `moodledata` will not be populated by the image data since it's not empty.

This way of mouting application core volume is Docker antipattern, I'm surprised of such way of doing !

To my mind with moodle we only need to mount 2 dinstincts folder : 
      - `/bitnami/moodledata`
      - `/bitnami/moodle/local`

All the rest should not be edited and must remain in the image; as part of core.

**Comment by fmulero** [comment]
Hi @rroblik, thanks for using bitnami containers.

About the persisted volumes in moodle container I got your point and I agree with your approach. I'll open an internal discussion to get more information, please feel free to open a PR in the meantime. We will be happy to review it.

In the other hand, about your concrete issue, it seems you are sharing the `bitnami/moodle` volume with other containers (I am assuming it due to the `z` flag) and probably is not empty and it doesn't have the expected content (the log shows that the container is trying to restore existing content), Could it be possible? does the volume have the moodle installation?

**Comment by rroblik** [comment]
Thanks for the internal discussion !

In fact, sorry for my bad english, that what I said : 
With a fresh new stack, my volumes are like that : 

```yml
    volumes:
      - ./moodledata:/bitnami/moodledata # uploads, cache, ...
      - ./data:/bitnami/moodle # Moodle full core
```

With this setup, (especially) second volume is populated once, then never updated (for example if I update the Moodle version using my related Dockerfile), except if I delete all the `./data` folder before, **BUT** in this case, that the main point of this isue, I loose any local plugin dev (`/bitnami/moodle/local`)

**Comment by rroblik** [comment]
@fmulero I think I made a wrong assumption : moodle doesn't allow to easily use docker / volumes because of sparing modules in a lot of differents (and non empty) directory, depending on theirs type : `local` for local, `mod`for activity module ... 😭 

Verry bad way of doing, but the point is in Moodle itself, not bitnami packaging. Tel me if I'm right ?

The workaround (at least during dev) is to mount each custom module folder is theirs respectiv target like that : 
```yaml
    volumes:
      - ./plugins/myplugin1:/bitnami/moodle/local/myplugin1
      - ./plugins/myplugin2:/bitnami/moodle/mod/myplugin2
```

**Comment by fmulero** [comment]
Sorry for my very late response.

I think your workaround is the best approach possible. I was checking it and the moodle layout doesn't allow us anything simpler.

**Comment by renne** [comment]
@fmulero 
```
volumes:
  - moodle:/bitnami/moodledata:rw
  - $CI_WORK_DIR/../moodle-local_backup_courses:/bitnami/moodle/local/backup_courses:ro
  - $CI_WORK_DIR/../moodle-local_laenderadmin_groupsync:/bitnami/moodle/local/laenderadmin_groupsync:ro
```
causes `grep: /opt/bitnami/moodle/config.php: No such file or directory`. The same happens when using `rw` instead of `ro` for the bind mounts.

Moodle startup complains it cannot delete `/bitnami/moodle/local/<plugin_name>` and exits with `/opt/bitnami/moodle` instead of `/bitnami/moodle`.

How to bind mount Moodle plugins for development testing on Bitnami Moodle Docker container 4.5.2?
