### ISSUE TITLE
airflow container - allow changing of api auth_method

### ISSUE THREAD

**Issue by ITJamie** [bitnami/containers#51274]
### Name and Version

airflow:latest

### What is the problem this feature will solve?

allow enabling of the airflow api in airflow.cfg

### What is the feature you are proposing to solve the problem?

add another environmental variable that will allow replacing the auth_backends parameter under the [api] section in airflow.cfg

https://airflow.apache.org/docs/apache-airflow/stable/security/api.html#basic-authentication

### What alternatives have you considered?

replacing the template file manually before the container starts.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
