### ISSUE TITLE
[bitnami/keycloak] Content-Security-Policy issue on console admin

### ISSUE THREAD

**Issue by loicguillois** [bitnami/containers#51498]
### Name and Version

bitnami/keycloak

### What architecture are you using?

None

### What steps will reproduce the bug?

Configured my container as follow

```
FROM bitnami/keycloak

ENV KEYCLOAK_DATABASE_NAME=xxx
ENV KEYCLOAK_DATABASE_USER=xxx
ENV KEYCLOAK_DATABASE_PASSWORD=xxx
ENV KEYCLOAK_DATABASE_PORT=xxx
ENV KEYCLOAK_DATABASE_HOST=xxx

ENV KEYCLOAK_ADMIN_USER=xxx
ENV KEYCLOAK_ADMIN_PASSWORD=xxx

ENV KC_HOSTNAME=xxx.fr
ENV KC_HOSTNAME_ADMIN=xxx.fr

ENV KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
ENV KEYCLOAK_HTTP_PORT=8080
ENV KEYCLOAK_BIND_ADDRESS=0.0.0.0
```

### What do you see instead?

I got the issue when I try to access `/admin/master/console/`

![image](https://github.com/bitnami/containers/assets/55890/97a72099-85a4-4ac5-809c-0a87bd915a4b)

**Comment by javsalgar** [comment]
Hi,

From the information above. Are you creating a fork of the container or you are just using the docker-compose.yml file?

**Comment by P-n-I** [comment]
Hi, we're also seeing this using a compose with `image: bitnami/keycloak:latest` behind Traefik which is terminating TLS.
Pretty sure it's some config we've missed, we've tried setting `KEYCLOAK_HOSTNAME` to the correct value in our env.  Running the same image locally on `localhost` works fine.

**Comment by P-n-I** [comment]
I managed to fix it, it _appears_ the `KEYCLOAK_HOSTNAME` gets written to the Db, once, on first init so we had too drop the Db and re-create it.

**Comment by javsalgar** [comment]
Thanks for letting us know!
