### ISSUE TITLE
[bitnami/keycloak] Redirected to /auth with a 404 error

### ISSUE THREAD

**Issue by loicguillois** [bitnami/containers#51497]
### Name and Version

bitnami/keycloak

### What architecture are you using?

None

### What steps will reproduce the bug?

Configured my container as follow 

```
FROM bitnami/keycloak

ENV KEYCLOAK_DATABASE_NAME=xxx
ENV KEYCLOAK_DATABASE_USER=xxx
ENV KEYCLOAK_DATABASE_PASSWORD=xxx
ENV KEYCLOAK_DATABASE_PORT=xxx
ENV KEYCLOAK_DATABASE_HOST=xxx

ENV KEYCLOAK_ADMIN_USER=xxx
ENV KEYCLOAK_ADMIN_PASSWORD=xxx

ENV KC_HOSTNAME=xxx.fr
ENV KC_HOSTNAME_ADMIN=xxx.fr

ENV KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
ENV KEYCLOAK_HTTP_PORT=8080
ENV KEYCLOAK_BIND_ADDRESS=0.0.0.0
```

### What do you see instead?

I was hoping not to get a 404 error.

### Additional information

This behavior occurs only on Google Chrome.

![image](https://github.com/bitnami/containers/assets/55890/88a0dc72-65ef-46da-bace-fde4cc33e382)

**Comment by javsalgar** [comment]
Do you have a sample docker-compose.yml that reproduces the issue?
