### ISSUE TITLE
[bitnami/redis-cluster] Logging: Not all logs have a severity

### ISSUE THREAD

**Issue by Christine-Schneidenwind** [bitnami/containers#51496]
### Name and Version

bitnami/redis-cluster:7.2.1-debian-11-r0 

### What is the problem this feature will solve?

We are collecting our logs via open telemetry. I have seen that there are log entries without severity.
e.g.
```
redis-cluster 09:09:59.12 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 09:09:59.12 Submit issues and feature requests at https://github.com/bitnami/containers/issues 
Changing old IP x.x.x.x by the new one x.x.x.x 
```

### What is the feature you are proposing to solve the problem?

Is it possible to add severity for that logs?
e.g.

redis-cluster 09:09:59.12 **INFO** Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 09:09:59.12 **INFO** Submit issues and feature requests at https://github.com/bitnami/containers/issues 
**09:09:59.12 INFO** Changing old IP x.x.x.x by the new one x.x.x.x

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. We may need to perform changes in libbitnami.sh

```
########################
# Print the welcome page for a Bitnami Docker image
# Globals:
#   BITNAMI_APP_NAME
# Arguments:
#   None
# Returns:
#   None
#########################
print_image_welcome_page() {
    local github_url="https://github.com/bitnami/containers"

    log ""
    log "${BOLD}Welcome to the Bitnami ${BITNAMI_APP_NAME} container${RESET}"
    log "Subscribe to project updates by watching ${BOLD}${github_url}${RESET}"
    log "Submit issues and feature requests at ${BOLD}${github_url}/issues${RESET}"
    log ""
}

```

Changing `log` with the function `info`. Would you like to submit a PR with the change?

**Comment by Christine-Schneidenwind** [comment]
Yes I can make a PR

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
