### ISSUE TITLE
Security Issue Curl <= 8.4

### ISSUE THREAD

**Issue by FelixKleineBoesing** [bitnami/containers#51500]
### Name and Version

all which use curl

### What is the problem this feature will solve?

Hey everyone, 
are you aware of the security issue that has been announced by curl, which will be fixed with the update 8.4 that will be released on 11th Ocotober (https://github.com/curl/curl/discussions/12026)?

### What is the feature you are proposing to solve the problem?

Updating all container images which includes curl to version 8.4 on 11th Oct.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the notice. As soon as the distros make curl available in their repos, the container images will be updated as well.

**Comment by vikramramasahayam** [comment]
Any ETA when container images will be available ?

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
