### ISSUE TITLE
[bitnami/wordpress-nginx] WORDPRESS_DATA_TO_PERSIST not working?

### ISSUE THREAD

**Issue by ManuelReschke** [bitnami/containers#51516]
### Name and Version

bitnami/wordpress-nginx:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The ENV WORDPRESS_DATA_TO_PERSIST has no impact

### What is the expected behavior?

if i set

    environment:
      - WORDPRESS_DATA_TO_PERSIST="index.php wp-config.php wp-content wp-admin"

index.php and wp-admin folder should be accessible in the docker volume under /var/lib/docker/volumes/*

### What do you see instead?

I see only the default files

**Comment by javsalgar** [comment]
Hi,

Are you using a clean installation of WordPress?

**Comment by ManuelReschke** [comment]
> Hi,
> 
> Are you using a clean installation of WordPress?

I deployed it with portainer and default values. Then i added the new ENV settings and redeployed the container.

**Comment by javsalgar** [comment]
Hi,

You may need to deploy it the first time with the exact values you want to use in WORDPRESS_DATA_TO_PERSIST, as this is done on first boot.
