### ISSUE TITLE
[bitnami/wordpress] Plugin Installation failed: Download failed. cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MartinBrian-Asurion** [bitnami/containers#51861]
### Name and Version

bitnami/wordpress@latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Followed the compose guide to deploy the environment.
2. Download the Importer Plugin
3. Download Failure error...

### What do you see instead?

Installation failed: Download failed. cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by andresbono** [comment]
Hi, can you elaborate a bit more on how are you downloading and installing the plugin?

If I try setting the `WORDPRESS_PLUGINS` env-var with the following docker-compose, the plugin is correctly downloaded and installed:

```patch
       - WORDPRESS_DATABASE_USER=bn_wordpress
       - WORDPRESS_DATABASE_NAME=bitnami_wordpress
+      - WORDPRESS_PLUGINS=wordpress-importer
```

Container logs and `wp plugin list` output:

```
debian-11-wordpress-1  | wordpress 10:37:20.08 INFO  ==> Installing and activating plugins: wordpress-importer
```

```
$ docker-compose exec wordpress wp plugin list --status=active
+--------------------+--------+--------+---------+
| name               | status | update | version |
+--------------------+--------+--------+---------+
| wordpress-importer | active | none   | 0.8.1   |
+--------------------+--------+--------+---------+
```
