### ISSUE TITLE
[bitnami/kafka] Liveness and Readiness Probe Unhealthy

### ISSUE THREAD

**Issue by priyanshiagarg** [bitnami/containers#51885]
### Name and Version

helm/bitnami/kafka/21.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

install the helm chart of kafka-v21.4.6 on aks environment
wait for the few minutes
check for the events where the liveness and readiness of zookeeper pod is giving error with no specific reason

### What is the expected behavior?

It shouldnt fail and be healthy

### What do you see instead?

Giving unhealthy error with failed result of connection refused
<img width="706" alt="image" src="https://github.com/bitnami/containers/assets/109510020/6dfb7543-29cc-4051-9ac2-5688f81c242d">

**Comment by priyanshiagarg** [comment]
kubenetes version- 1.27.3
Network type- Azure CNI
Size- Standard_DS2_v2
Cluster type- Public
<img width="698" alt="MicrosoftTeams-image (3)" src="https://github.com/bitnami/containers/assets/109510020/294d7801-e3da-49dd-919c-3c9ec74a95df">

**Comment by priyanshiagarg** [comment]
Readiness probe failed: dial tcp 10.x.x.x:9092: connect: connection refused is intermittently coming in kafka pod as well.

Also tried changing network type to kubenet as well, and still getting the same probe failed error.

**Comment by priyanshiagarg** [comment]
@javsalgar please help in fixing the same as its a prod issue coming repeatedly, and since liveness/readiness probe is getting failed it is in turn, not flowing the traffic to the aks because of the failure of the verification.

**Comment by priyanshiagarg** [comment]
@javsalgar Im getting this error in the kafka pod. Can you please share any idea on why is this coming.
<img width="843" alt="image" src="https://github.com/bitnami/containers/assets/109510020/be593f32-3629-434f-b537-4f26e76ff4e7">

**Comment by javsalgar** [comment]
Hi,

We would need to understand whether this is something of the cluster or not. Does it happen in other kubernetes clusters? We are unable to reproduce the issue

**Comment by priyanshiagarg** [comment]
@javsalgar yes, i tried it in a new azure subscription which has no restriction by creating a new aks cluster and just installing the same version of kafka helm chart (21.4.6) is giving me the same liveness/readiness probe connection error.

**Comment by priyanshiagarg** [comment]
for reproducing: 
1. Create an AKS cluster.
2. run the commands using cloudshell to install the helm chart for kafka 21.4.6:
helm repo add my-repo https://charts.bitnami.com/bitnami
helm install my-release my-repo/kafka --version 21.4.6
3. check after 5 minutes with commands:
kubectl get all
kubectl describe <pod of zookeeper>

**Comment by priyanshiagarg** [comment]
@CeliaGMqrz this error is coming up just after pulling the helm chart of kafka 21.4.6 in any aks cluster. No specific/custom settings are being done for this as of now. Kindly help in this.

**Comment by CeliaGMqrz** [comment]
Hi @priyanshiagarg,

Thanks for your comments. 

Sorry, I have not been able to reproduce the error. It seems that your environment is more specific. Do you need this specific version for any particular reason? Can you try the latest available version of the chart, which is `26.0.0`?

**Comment by priyanshiagarg** [comment]
WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /10.x.x.x (channelId=10.x.x.y:9
092-10.x.x.x:53294-4147); closing connection (org.apache.kafka.common.network.Selector)

 

 

This part of the message indicates that the broker (10.x.x.x) received an unexpected error while communicating with another node (10.x.x.y) on port 9092. The error occurred in the context of a specific network channel (channelId=10.x.x.y:9092-10.x.x.x:53280-4146) due to the unexpected error, the connection between the brokers is being closed

@CeliaGMqrz I'm getting this error for connectivity. Is this a normal thing to come up regularly or there is any specific configuration needs to be done to resolve this? and can this be related to liveness/readiness probe issue?


Using this version 21.4.6, because zookeeper is required in the application and the latest version is not supporting that.

**Comment by CeliaGMqrz** [comment]
Hi @priyanshiagarg,

> Using this version 21.4.6, because zookeeper is required in the application and the latest version is not supporting that.

Although Zookeeper mode is not the default in the latest version, it is still possible to configure a Kafka deployment using Zookeeper using the following values:

```.yaml
controller:
  replicaCount: 0
broker:
  replicaCount: 1
kraft:
  enabled: false
zookeeper:
  enabled: true
```

We highly encourage you to try the latest version because, although we found an issue with the chart version `21.4.6`, it would not be possible for us to release a fix for an older major.

In case the issue does not persist in the latest version, the chart [README.md](https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md) includes a guide on how to upgrade from previous versions, since it received a major refactor in version `24.x.x`

Thanks for your feedback!
