### ISSUE TITLE
[bitnami/postgresql-repmgr] Wrong USER command in postgres-repmgr Dockerfile

### ISSUE THREAD

**Issue by roncemer** [bitnami/containers#51914]
### Name and Version

bitnami/postgresql-repmgr:16.0.0-debian-11-r11

### What architecture are you using?

None

### What steps will reproduce the bug?

Try to run the docker image.

### What is the expected behavior?

Should work.

### What do you see instead?

FATAL:  could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied

### Additional information

This is because the service is trying to run as user 1001 (which doesn't exist) instead of the correct user 101 (which is the postgres user in /etc/passwd).

Please change "USER 1001" to "USER 101" at the bottom of the Dockerfile, and issue a new release of the image and Helm chart.

**Comment by javsalgar** [comment]
Hi,

The user 1001 is intended. Could you share the steps to reproduce the issue?

**Comment by roncemer** [comment]
It turned out to be an issue with my configuration.  Sorry for the trouble.
