### ISSUE TITLE
[Gitea] Deprecated Config Option [mailer] Host use [mailer] SMTP_ADDR instead

### ISSUE THREAD

**Issue by NighthawlkF117** [bitnami/containers#51923]
### Name and Version

bitnami/gitea:1:20.5

### What is the problem this feature will solve?

The Gitea Application gives this visible Warning:
>Deprecated config option `[mailer]` `HOST` present. Use `[mailer]` `SMTP_ADDR` instead. This fallback will be/has been removed in v1.19.0.

According to the gitea docs:
https://docs.gitea.com/administration/config-cheat-sheet?_highlight=deprecated&_highlight=host#mailer-mailer

> SMTP_ADDR: empty: Mail server address. e.g. smtp.gmail.com. For smtp+unix, this should be a path to a unix socket instead. Before 1.18, this was combined with SMTP_PORT under the name HOST.
> SMTP_PORT: empty: Mail server port. If no protocol is specified, it will be inferred by this setting. Common ports are listed below. Before 1.18, this was combined with SMTP_ADDR under the name HOST.

### What is the feature you are proposing to solve the problem?

Add an environment variable:
`GITEA_SMTP_PORT` in `bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/gitea-env.sh` + `bitnami/gitea/1/debian-11/rootfs/opt/bitnami/scripts/libgitea.sh` (it is possibly I missed a point, but I found a reference in these 2 files to the `GITEA_SMTP_HOST`).

Update the Line:
```bash
    is_empty_value "$GITEA_SMTP_HOST" || gitea_conf_set "mailer" "HOST" "$GITEA_SMTP_HOST"
```
to
```bash
    is_empty_value "$GITEA_SMTP_HOST" || gitea_conf_set "mailer" "SMTP_ADDR" "$GITEA_SMTP_HOST"
```
and add:
```bash
    is_empty_value "$GITEA_SMTP_PORT" || gitea_conf_set "mailer" "SMTP_PORT" "$GITEA_SMTP_HOST"
```

this should fix the error in gitea 1.19 and future versions

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
