### ISSUE TITLE
[bitnami/kafka] The example of kafka runs an error

### ISSUE THREAD

**Issue by wedreamer** [bitnami/containers#51943]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. [example](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security)
2. docker compose up -d

```yml
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=controller_user
      - KAFKA_INTER_BROKER_PASSWORD=controller_password
      - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123
      - KAFKA_TLS_TYPE=JKS # or PEM
    volumes:
      # Both .jks and .pem files are supported
      # - './kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      # - './kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      # - './kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      - './keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
```

```bash
kafka-console-producer.sh --bootstrap-server 127.0.0.1:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties

kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --consumer.config /opt/bitnami/kafka/config/consumer.properties
```

3. An error occurred，not producer and consumer message

```log
I have no name!@kafka-dev:/$ kafka-console-producer.sh --bootstrap-server kafka:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties
>[2023-10-18 06:42:55,581] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:42:55,726] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:42:55,917] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:42:56,210] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```

```log
I have no name!@kafka-dev:/$ kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --consumer.config /opt/bitnami/kafka/config/consumer.propertieses
[2023-10-18 06:43:16,138] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:43:16,280] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:43:16,471] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:43:16,762] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:43:17,154] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-10-18 06:43:18,097] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```

### What do you see instead?

Why is this situation and how to solve it

**Comment by wedreamer** [comment]
> ### Name and Version
> 
> bitnami/kafka:latest
> ### What architecture are you using?
> 
> amd64
> ### What steps will reproduce the bug?
> 
>     1. [example](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security)
> 
>     2. docker compose up -d
> 
> 
> ```yaml
> version: '2'
> 
> services:
>   kafka:
>     image: 'bitnami/kafka:latest'
>     hostname: kafka.example.com
>     ports:
>       - '9092'
>     environment:
>       - KAFKA_CFG_NODE_ID=0
>       - KAFKA_CFG_PROCESS_ROLES=controller,broker
>       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
>       - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
>       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
>       - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
>       - KAFKA_CLIENT_USERS=user
>       - KAFKA_CLIENT_PASSWORDS=password
>       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
>       - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
>       - KAFKA_CONTROLLER_USER=controller_user
>       - KAFKA_CONTROLLER_PASSWORD=controller_password
>       - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
>       - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
>       - KAFKA_INTER_BROKER_USER=controller_user
>       - KAFKA_INTER_BROKER_PASSWORD=controller_password
>       - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123
>       - KAFKA_TLS_TYPE=JKS # or PEM
>     volumes:
>       # Both .jks and .pem files are supported
>       # - './kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
>       # - './kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
>       # - './kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
>       - './keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
>       - './truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
> ```
> 
> ```shell
> kafka-console-producer.sh --bootstrap-server 127.0.0.1:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties
> 
> kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --consumer.config /opt/bitnami/kafka/config/consumer.properties
> ```
> 
>     3. An error occurred，not producer and consumer message
> 
> 
> ```
> I have no name!@kafka-dev:/$ kafka-console-producer.sh --bootstrap-server kafka:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties
> >[2023-10-18 06:42:55,581] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:42:55,726] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:42:55,917] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:42:56,210] WARN [Producer clientId=console-producer] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> ```
> 
> ```
> I have no name!@kafka-dev:/$ kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --consumer.config /opt/bitnami/kafka/config/consumer.propertieses
> [2023-10-18 06:43:16,138] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:43:16,280] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:43:16,471] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:43:16,762] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:43:17,154] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> [2023-10-18 06:43:18,097] WARN [Consumer clientId=console-consumer, groupId=test-consumer-group] Bootstrap broker kafka:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
> ```
> 
> ### What is the expected behavior?
> 
> _No response_
> ### What do you see instead?
> 
> Why is this situation and how to solve it
> ### Additional information
> 
> _No response_

info of kafka image

```json
{
  "Id": "sha256:508d6de0d0a16102fbbada1e15ec3a952f3dc0c4e81671e921c9c3482b96f149",
    "RepoTags": [
        "bitnami/kafka:latest"
    ],
    "RepoDigests": [
        "bitnami/kafka@sha256:2d065103d482dd0b985e15e39eaf17dc7627a755321952be807335d7ae67533c"
    ],
}
```

**Comment by javsalgar** [comment]
Hi,

Does this issue occur with the default configuration?

**Comment by wedreamer** [comment]
> Hi,
> 
> Does this issue occur with the default configuration?

Yes, I didn't do anything else, just change the local key path

**Comment by wedreamer** [comment]
> Hi,
> 
> Does this issue occur with the default configuration?

![image](https://github.com/bitnami/containers/assets/43949542/b1e10b8d-f9a9-4858-ab2e-512d2f051467)

[doc](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security)

**Comment by rafariossaa** [comment]
Hi,
  Could you try what @migruiz4 indicated [here](https://github.com/bitnami/containers/issues/43226#issuecomment-1667833409) ?
