### ISSUE TITLE
[bitnami/consul] fails to start when using custom gossip encryption key

### ISSUE THREAD

**Issue by daanknoope** [bitnami/containers#51959]
### Name and Version

bitnami/consul:1.16.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a new gossip encryption key using Consul: `docker run -it bitnami/consul:1.16.2 consul keygen`. For example: `b2zSzU+mNwB9RdsHLbLWsWqH/GkWeVjLmfm7MnJqOzM=`. 
2. Start a new consul container using this new encryption key: `docker run -it -e CONSUL_GOSSIP_ENCRYPTION='yes' -e CONSUL_GOSSIP_ENCRYPTION_KEY='b2zSzU+mNwB9RdsHLbLWsWqH/GkWeVjLmfm7MnJqOzM='  bitnami/consul:1.16.2`

### What is the expected behavior?

The expected behaviour is for the container to start up and show that it is using Gossip Encryption. 

### What do you see instead?

The container fails when trying to use the gossip encryption key: `"Failed to configure keyring: Invalid key: key size must be 16, 24 or 32 bytes"`.

The full error trace:

```bash
consul 15:22:19.15
consul 15:22:19.15 Welcome to the Bitnami consul container
consul 15:22:19.16 Subscribe to project updates by watching https://github.com/bitnami/containers
consul 15:22:19.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
consul 15:22:19.16
consul 15:22:19.16 INFO  ==> ** Starting Consul setup **
consul 15:22:19.16 INFO  ==> Validating settings in CONSUL_* env vars..
consul 15:22:19.17 INFO  ==> Initializing Consul...
consul 15:22:19.17 WARN  ==> The variable CONSUL_NODE_NAME was not set, defaulting it to the machine ip
consul 15:22:19.17 INFO  ==> Deploying consul from scratch...
consul 15:22:19.17 INFO  ==> No injected configuration files found. Creating default config files...
consul 15:22:19.17 INFO  ==> Configuring encryption key...
find: '/docker-entrypoint-initdb.d/': No such file or directory
consul 15:22:19.18 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
consul 15:22:19.18 INFO  ==> ** Consul setup finished! **

consul 15:22:19.18 INFO  ==> ** Starting Consul **
==> Starting Consul agent...
               Version: '1.16.2'
            Build Date: '2023-09-19 19:29:18 +0000 UTC'
               Node ID: '748e6e97-869f-a7bb-dd96-324afe3c295c'
             Node name: '172.17.0.2'
            Datacenter: 'dc1' (Segment: '<all>')
                Server: true (Bootstrap: true)
           Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, gRPC-TLS: 8503, DNS: 8600)
          Cluster Addr: 172.17.0.2 (LAN: 8301, WAN: 8302)
     Gossip Encryption: true
      Auto-Encrypt-TLS: false
           ACL Enabled: false
     Reporting Enabled: false
    ACL Default Policy: allow
             HTTPS TLS: Verify Incoming: false, Verify Outgoing: false, Min Version: TLSv1_2
              gRPC TLS: Verify Incoming: false, Min Version: TLSv1_2
      Internal RPC TLS: Verify Incoming: false, Verify Outgoing: false (Verify Hostname: false), Min Version: TLSv1_2

==> Log data will now stream in as it occurs:

2023-10-18T15:22:19.215Z [WARN]  agent: The 'ui' field is deprecated. Use the 'ui_config.enabled' field instead.
2023-10-18T15:22:19.215Z [WARN]  agent: BootstrapExpect is set to 1; this is the same as Bootstrap mode.
2023-10-18T15:22:19.215Z [WARN]  agent: Node name "172.17.0.2" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
2023-10-18T15:22:19.215Z [WARN]  agent: bootstrap = true: do not enable unless necessary
2023-10-18T15:22:19.218Z [WARN]  agent.auto_config: The 'ui' field is deprecated. Use the 'ui_config.enabled' field instead.
2023-10-18T15:22:19.218Z [WARN]  agent.auto_config: BootstrapExpect is set to 1; this is the same as Bootstrap mode.
2023-10-18T15:22:19.218Z [WARN]  agent.auto_config: Node name "172.17.0.2" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
2023-10-18T15:22:19.218Z [WARN]  agent.auto_config: bootstrap = true: do not enable unless necessary
2023-10-18T15:22:19.218Z [ERROR] agent: Error starting agent: error="Failed to configure keyring: Invalid key: key size must be 16, 24 or 32 bytes"
2023-10-18T15:22:19.218Z [INFO]  agent: Exit code: code
```

### Additional information

The problem seems to be caused by double base64 encoding. 

The [consul website ](https://developer.hashicorp.com/consul/tutorials/security/gossip-encryption-secure#gossip-encryption)explains that creating a new gossip key can be done by running `consul keygen`. This utility generates a key, and encodes it using base64: [`c.UI.Output(base64.StdEncoding.EncodeToString(key))`](https://github.com/hashicorp/consul/blob/f45be222bbb454b6165989f0ab133eb3b2263f50/command/keygen/keygen.go#L49).

The bitnami consul container then re-encodes the already base64-encoded string again during the setup of the container: [  `CONSUL_GOSSIP_ENCRYPTION_KEY=$(base64 <<<"${CONSUL_GOSSIP_ENCRYPTION_KEY}")` ](https://github.com/bitnami/containers/blob/ef7ca1588139670f198569f72d064e96018c0474/bitnami/consul/1/debian-11/rootfs/opt/bitnami/scripts/libconsul.sh#L112).

Since the gossip encryption key is now _double-encoded_, it is no longer a valid key and consul throws the error mentioned above.

I tested this by overwriting the `/opt/bitnami/consul/conf/encrypt.json` file, which stores the double-encoded encryption key with the original key, and running the `/opt/bitnami/scripts/consul/run.sh` manually. This seems to work completely fine.

My suggested fix for this problem would be to remove the additional base64-encoding step from the setup script of the container, and add a link to `consul keygen` in the container readme for added clarity. 

If anybody would be willing to validate and review this bug report, I could implement the suggested fix and submit it as a PR.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the bug report. I believe that what you mention makes sense, so if you want to participate with the PR we will greatly appreciate it
