### ISSUE TITLE
When i change the password the old one is still functional

### ISSUE THREAD

**Issue by shilky69** [bitnami/containers#52040]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

When i change the password the old one is still functional, I changed it a third time and the first two are still functional. I left it several hours, several days and still functional...

### What do you see instead?

 the old password is still functional

**Comment by jotamartos** [comment]
Hi @shilky69,

I understand you are following an external guide to change the configured password. If that's the case, I suggest you reeview the OpenLDAP documentation to know if there is any extra step needed to remove the old password and only accept the new one. I also suggest you check the OpenLDAP forums to know if users ran into that issue before. 

Thanks
