### ISSUE TITLE
postgresql-repmgr: POSTGRESQL_EXTRA_FLAGS ignored

### ISSUE THREAD

**Issue by dcamarenaAZO** [bitnami/containers#52130]
### Name and Version

bitnami/postgresql-repmgr:15.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run container with env `POSTGRESQL_EXTRA_FLAGS`: `"-c max_connections=200"`
2. connect to the container and start `psql postgres`
3. run `show max_connections;`
4. It will return the default value 100

### What is the expected behavior?

`-c max_connections=200` should be passed to start of postgres deamon. This extra start parameter for postgres changes `max_connections` from default 100 to 200. 
env variable is loaded in `/opt/bitnami/scripts/postgresql-env.sh` but not passed to postgres deamon. I think this is because repmgr is starting postgres deamon. 

### What do you see instead?

extra start parameter for postgres is NOT passed and max_connections is default value 100. 

### Additional information

I would have loved it to fix it and to create a PR, but I don't even know how repmgr is starting postgres deamon.

**Comment by dcamarenaAZO** [comment]
POSTGRESQL_EXTRA_FLAGS works in bitnami/postgresql because of [run.sh](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql/11/debian-11/rootfs/opt/bitnami/scripts/postgresql/run.sh#L21C21-L21C21)

This behaviour could be transfered to bitnami/postgresql-repmgr into [librepmgr.sh](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/11/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh#L512C25-L512C25)

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out.
  Would you like to contribute and send a PR ? We will be glad to review and merge it

**Comment by dcamarenaAZO** [comment]
Hi,

I’ll try 😊

Cheers, Daniel


AZO GmbH & Co. KG
Rosenberger Str. 28
D-74706 
Osterburken
Tel.: +49 6291 92-6449
Mob.: +49 162 9919448
Fax: +49 6291 9290449
Mail: ***@***.***
Web: www.azo.com
AZO. We Love Ingredients.
KG: Sitz Osterburken, Register-Gericht Mannheim HRA 450086, Persönlich haftende Gesellschafterin: AZO Beteiligungs GmbH, Sitz Osterburken, Register-Gericht Mannheim HRB 450261
​Geschäftsführer: Rainer Zimmermann | Daniel Auerhammer | Dr. Matthias Fechner | Jan-Wilko Helms | Dennis Künkel

Diese E-Mail einschließlich ihrer Anhänge ist vertraulich. Wir bitten Sie, eine fehlgeleitete E-Mail zu löschen und uns eine Nachricht zukommen zu lassen. Wir haben die E-Mail vor dem Versenden auf Virenfreiheit geprüft. Eine Haftung für Virenfreiheit schließen wir jedoch aus.

This e-mail and its attachments are confidential. If you are not the intended recipient of this e-mail message, please delete it and inform us accordingly. This e-mail was checked for viruses when sent, however we are not liable for any virus contamination.
Von: Rafael Ríos Saavedra ***@***.***>
Gesendet: Donnerstag, 26. Oktober 2023 10:15
An: bitnami/containers ***@***.***>
Cc: Camarena Daniel ***@***.***>; Author ***@***.***>
Betreff: Re: [bitnami/containers] postgresql-repmgr: POSTGRESQL_EXTRA_FLAGS ignored (Issue #52130)


Hi,
Thanks for spotting this out.
Would you like to contribute and send a PR ? We will be glad to review and merge it

**Comment by dcamarenaAZO** [comment]
Hi, I was looking at the code and I found the variable to change the `max_connections`, which was my main target now. I've added it to the documentation and created a pull request. The here mentioned gap is still pending. I couldn't make it and therefore I left it. Up to you to keep the issue open or close it.

**Comment by rafariossaa** [comment]
Cold you indicate which is the PR you sent ? (or refer to this issue in the PR) so it is possible to relate them.

**Comment by dcamarenaAZO** [comment]
Hi Rafael, 

I mentioned this issue from the PR last week before I responded: [Here the link to the PR](https://github.com/bitnami/containers/pull/52254) 

Cheers, Daniel

**Comment by rafariossaa** [comment]
Hi,
  Thanks.
  Let's wait until it gets reviewed and merged.

**Comment by hendrytjen** [comment]
I guess there is few limitation in the startup script and conflicting with parameter with spaces.

The easiest and most convenient way to add this parameter in docker is to create a folder+file like below and mount to conf.d like below example. i guess this conf.d was intended for this very purposes :-)

- make a folder in your local host, for example: conf.local.d
- make a simple file (extension .conf is mandatory) in your local host, example: conf.local.d/my_own_config.conf
- my_own_config.conf consist your desired postgre config, like 
  shared_buffers = 256MB
  max_connections = 200

- mount the folder to /opt/bitnami/postgresql/conf/conf.d/ (as long as your file ends with .conf, postgres will load)
example docker-compose.yml:
```yaml
services:
  postgres:
    image: docker.io/bitnami/postgresql-repmgr:16.3.0
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/bitnami/postgresql
      - ./conf.d/:/opt/bitnami/postgresql/conf/conf.d/
```

example of docker run:
```bash
docker run -dit -p 5432:5432 -v ./conf.d/:/opt/bitnami/postgresql/conf/conf.d/ docker.io/bitnami/postgresql-repmgr:16.3.0
```

cheers!
