### ISSUE TITLE
jasperreports: SMTP authentication and encryption should be optional

### ISSUE THREAD

**Issue by alamp1360** [bitnami/containers#52235]
### Name and Version

bitnami/jasperreports:latest

### What is the problem this feature will solve?

When you specify an SMTP host via `JASPERREPORTS_SMTP_HOST`, then SMTP authentication and encryption are enabled automatically. If the SMTP server does not support authentication or encryption, then sending emails out of JasperReports does not work.

### What is the feature you are proposing to solve the problem?

I would suggest that both options should be made optional using additional environment variables.
The necessary changes need to be done in file _scripts/libjasperreports.sh_ after line 396

### What alternatives have you considered?

I have created my own version of _entrypoint.sh_ which, after the initialization of the container is finished, calls xmlstarlet to set the `mail.smtp.auth` and `mail.smtp.starttls.enable` properties in file applicationContext-report-scheduling.xml to "false".

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
