### ISSUE TITLE
[bitnami/grafana] Running grafana image with user init script causes error

### ISSUE THREAD

**Issue by bpfoster** [bitnami/containers#52238]
### Name and Version

grafana:10.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a shell script
2. Run the image, mounting the shell script to the `/docker-entrypoint-init.d/` directory

For example:
```
$ docker run --rm -v $(pwd)/foo.sh:/docker-entrypoint-init.d/foo.sh -ti docker.io/bitnami/grafana:10.2.0-debian-11-r0
```

### What is the expected behavior?

The script runs, and the container starts

### What do you see instead?

```
grafana 14:28:54.37 
grafana 14:28:54.37 Welcome to the Bitnami grafana container
grafana 14:28:54.37 Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 14:28:54.38 Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 14:28:54.38 
mkdir: cannot create directory '/bitnami': Permission denied
```

### Additional information

Presumably from here:  https://github.com/bitnami/containers/blob/8bb5534a6c4b6562ba3f6fa7191f6d96d214b83d/bitnami/grafana/10/debian-11/rootfs/post-init.sh#L16

**Comment by javsalgar** [comment]
Hi! 

Could you check if the permissions of the mounted folder are writable by `others`?

**Comment by bpfoster** [comment]
I verified it was not a permissions issue on the script volume mount.
```
docker run --rm -v $(pwd):/docker-entrypoint-init.d:Z -ti docker.io/bitnami/grafana:10.2.0-debian-11-r0 ls -ald /docker-entrypoint-init.d
grafana 11:27:20.16 
grafana 11:27:20.17 Welcome to the Bitnami grafana container
grafana 11:27:20.17 Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 11:27:20.17 Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 11:27:20.17 

drwxrwxrwx. 2 root root 50 Oct 31 11:26 /docker-entrypoint-init.d
```

Not surprising because the error does not relate to the mount.

It looks like the entrypoint tries to create `/bitnami/grafana` if init.d scripts are present.  This is run as user `1001` but this user doesn't have permissions in the image to create `/bitnami`, hence the error.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by bpfoster** [comment]
Un-stale

**Comment by bpfoster** [comment]
Un-stale

**Comment by javsalgar** [comment]
Hi!

Could you try mounting a volume in `/bitnami/grafana` ?
