### ISSUE TITLE
[bitnami/memcached] Adding ObservedGeneration to memcached CRD

### ISSUE THREAD

**Issue by Shashankft9** [bitnami/containers#52231]
### Name and Version

bitnami/memcached:6.6.7

### What is the problem this feature will solve?

Visibility into the operations that the memcached operator is performing, its success/failure whenever the memcached CR is updated - right now, there is no way to tell that the operator is done changing the memcached db once I have done some change in the CR.

### What is the feature you are proposing to solve the problem?

Adding something like observed generation in the status of CR which will only increment once the operator has done all the changes to the DB.

### What alternatives have you considered?

Tried checking the option of comparing the `deployedRelease` key in status, but that'd be much more complex than just checking the `observedGeneration`

**Comment by javsalgar** [comment]
Hi!

You were mentioning about a memcached-operator component, but we are not packaging any operator for memcached, only a helm chart for regular memcached. Could you double check which project you are using?
