### ISSUE TITLE
github.com/emicklei/go-restful/v3 -  compliance vulnerability found in kubectl - 1.28.3 

### ISSUE THREAD

**Issue by Skyapip** [bitnami/containers#52249]
### Name and Version

bitnami/kubectl:1.28.3

### What architecture are you using?

None

### What steps will reproduce the bug?

On scanning the bitnami/kubectl:1.28.3 docker image, found the below vulnerability in it.

### What do you see instead?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ANANDJ~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ANANDJ~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Type | Severity | CVSS | CVE | Package Name | Package Version | Fix Status
-- | -- | -- | -- | -- | -- | --
Compliance | High |   | PRISMA-2022-0227 | github.com/emicklei/go-restful/v3 | v3.9.0 | fixed   in: v3.10.0

</body>

</html>

Full description: github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system.

Can we fix this as soon as possible?

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

When running Trivy with the `--ignore-unfixed` flag, there are no CVEs reported:
```console
$ trivy image --ignore-unfixed bitnami/kubectl:1.28.3
2023-10-31T18:00:17.634+0100	INFO	Need to update DB
2023-10-31T18:00:17.634+0100	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-10-31T18:00:17.634+0100	INFO	Downloading DB...
40.48 MiB / 40.48 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 25.94 MiB p/s 1.8s
2023-10-31T18:00:22.048+0100	INFO	Vulnerability scanning is enabled
2023-10-31T18:00:22.048+0100	INFO	Secret scanning is enabled
2023-10-31T18:00:22.048+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-10-31T18:00:22.048+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.46/docs/scanner/secret/#recommendation for faster secret detection
2023-10-31T18:00:26.622+0100	INFO	Detected OS: debian
2023-10-31T18:00:26.622+0100	INFO	Detecting Debian vulnerabilities...
2023-10-31T18:00:26.631+0100	INFO	Number of language-specific files: 2
2023-10-31T18:00:26.631+0100	INFO	Detecting bitnami vulnerabilities...
2023-10-31T18:00:26.631+0100	INFO	Detecting gobinary vulnerabilities...

bitnami/kubectl:1.28.3 (debian 11.8)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
