### ISSUE TITLE
Why does docker.io/bitnami/minideb:bullseye have so many unfixed vulnerabilities

### ISSUE THREAD

**Issue by raoganeshr** [bitnami/containers#52299]
### Name and Version

docker.io/bitnami/minideb:bullseye

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Ran a trivy scan with 'show only fixed vulnerabilities' to false. Seems there a lot of unfixed issues. Any reason for the same?

![image](https://github.com/bitnami/containers/assets/88204915/3b125650-4517-456d-8255-dbf5c844dd3e)

### What is the expected behavior?

Ideally since this is a small package it should not have any Criticals or Highs.

### What do you see instead?

NA

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS packages or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.

**Comment by javsalgar** [comment]
The packages we use in the base image are those that are mandatory by the debian system together with runtime deps detected at compilation time. If the packages are there it's because one of the two reasons.
