### ISSUE TITLE
Bug Report: SuiteCRM Crontab not working for schedualer

### ISSUE THREAD

**Issue by Mrs-Feathers** [bitnami/containers#52365]
### Name and Version

bitnami/suitecrm:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

scheduler isn't running

Code you have now: `*/1 * * * * daemon cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php > /dev/null 2>&1`

### What do you see instead?

I fixed it.

`* * * * * daemon cd /bitnami/suitecrm/public/legacy && /opt/bitnami/php/bin/php -f cron.php > /dev/null 2>&1`

### Additional information

the `;` causes the operation to end on top of it being in the wrong folder.. so I changed the folder and added the && to keep it all "technically one command" to make cron happy.

my fix works perfectly on my end, consider patching that up in the code.

**Comment by Mrs-Feathers** [comment]
also just pointing out the */1 isn't nessesary either in your original cron. */1 means "every 1 minute" which is technically the same as just * which means "every minute".. thats why i changed that in my fix as well. cheers.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by JoshMcCullough** [comment]
Fixed with PR: https://github.com/bitnami/containers/pull/73549
