### ISSUE TITLE
[bitnami/jenkins] when stating volume in jenkins image creation , the path is built wrong 

### ISSUE THREAD

**Issue by idubi** [bitnami/containers#52376]
### Name and Version

bitnami/jenkins:latest (2.414.3-debian  ???? )

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. in windows 64 env, docker cli, in git bash env (I use Docker version 24.0.6, build ed223bc ) 
when I use the `docker run` command with the `--version` variable, the path is built wrong. 
 I did several tests : 
 expected:       `docker run -v C:\path\on\host\:C:\path\in\container`
 
 actual: 

all of the times I userd this command with each time the volume is different : 
```console
$ docker run -d -p 8080:8080  -p 8000:80 -p 50000:50000 -p4430:443 --name jenkins --network jenkins-network
 -v <--VOLUME-->  --env JENKINS_USERNAME=idubi --env JENKINS_PASSWORD=bitnami --env JENKINS_EMAIL=<my-email@gmail.com> bitnami/jenkins:latest

volume value                                                          created path / error log 
./bitnami/jenkins/data:/bitnami/jenins         
                ..... host :    D:\projects\WorldOfGame\bitnami\jenkins\data;C⁠
                ..... container : \Program Files\Git\bitnami\jenins

/d/program files/WorldOfGame/bitnami/jenkins/data:/bitnami/jenkins  
               ..... error :   docker: invalid reference format: repository name must be lowercase.

'/d/program files/WorldOfGame/bitnami/jenkins/data':/bitnami/jenkins    
                ..... host : D:\program files\WorldOfGame\bitnami\jenkins\data;C⁠                                                                       
                ..... container : \Program Files\Git\bitnami\jenkins 

 -v /d/:/bitnami/jenkins                 
                ..... host :   D:\;C                
                ..... container : \Program Files\Git\bitnami\jenkins

-v /bitnami/jenkins:/d/    (tried with oposite way .... )
               ..... error :   docker: Error response from daemon: mkdir C:\Program Files\Git\bitnami: Access is denied.                  
```

conclusion:
al of the time, the host path was generated on the container when c was created at the host path, at the end of the string 

### What is the expected behavior?

the expected behavior is that the absolute path would be created properly on the container and on host, like volume regular behaviour and not as a scrambled concatenation of strings 

### Additional information

![Screenshot_1](https://github.com/bitnami/containers/assets/24396718/504f20ae-b54c-4e54-9a90-e7e5acd9ccd2)
![Screenshot_2](https://github.com/bitnami/containers/assets/24396718/cd22fac0-5e3c-4029-80e4-79f984805dcd)

**Comment by javsalgar** [comment]
Hi!

Could you elaborate the reason of using windows path inside the jenkins (linux) container? This may cause issues with the expected paths inside the container logic. Did you check the README.md file?

**Comment by idubi** [comment]
Hi 
I wanted to use a volume to be able to use persistancy on my host 
I am using windows docker and want a jenkins container inside 

the perisstant is importent to allow backing up data 

I use -v like normally use in container creation 
to allow files from host to client (for backups)

but the path is not building correctly 



I dont want to use "program files' 
I am actually in another diectory 

but it looks like the image is taking the docker home as reference path 

I dont need this 

the image is actually build in d disk , but it is referensing to the program files where the docker home is 
see : 

I use like this : 


./bitnami/jenkins/data:**/bitnami/jenins** 

./bitnami/jenkins/data --> this should be the path in the host (created properly , but added ";C" to the end of path )
/bitnami/jenins  --> this should be the path in the container , but insdtead it takes the **git** home (don't know why , we are using docker, not git... ) and add this path to the container path ..  

git home is : C:/program files/git

it  take apart the c from it and add it to the host path (;C)
and the end of the path is added to the container path ( \Program Files\Git)

  ..... host :    D:\projects\WorldOfGame\bitnami\jenkins\data;C⁠
  ..... container : \Program Files\Git\\**bitnami\jenins** 




![image](https://github.com/bitnami/containers/assets/24396718/003effeb-6f2f-4055-ab08-88552f35cf5f)

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
