### ISSUE TITLE
nfs-utils Install 

### ISSUE THREAD

**Issue by pomland-94** [bitnami/containers#52375]
### Name and Version

bitnami/all

### What is the problem this feature will solve?

It would be great if nfs-utils is installed per default on Kubernetes Clusters which uses nfs mounts there are some errors and the Container didn‘t come up.

### What is the feature you are proposing to solve the problem?

Install nfs-utils per default in all Containers.

**Comment by carrodher** [comment]
Could you please elaborate more on what kind of errors and under what circumstances? We try to keep the containers as simple as possible to reduce the possibility of any potential vulnerability so, by default, the packages included in the container images are the minimal and required ones

**Comment by pomland-94** [comment]
I get the following error when i use the rook-nfs storageclass inside my Wordpress deployment:
``` shell

Output: mount: /var/lib/kubelet/pods/415b73b5-03ef-4c9f-9a5c-67797e85f47b/volumes/kubernetes.io~csi/pvc-1bb496f4-3db3-4dbc-836e-2f420b0e1fe0/mount: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
 stderr: ""
```

**Comment by pomland-94** [comment]
Are there any Progress on this error here?
