### ISSUE TITLE
[bitnami/wordpress] Enable additional apache modules and add custom config

### ISSUE THREAD

**Issue by RobReus** [bitnami/containers#52422]
### Name and Version

bitnami/wordpress:6.3.2

### What is the problem this feature will solve?

Currently it is not possible to enable additional modules (e.g. by providing a list of modules to be enabled via an environment variable) or to provide additional apache config to be loaded (e.g. via a volume mount). 

### What is the feature you are proposing to solve the problem?

It seems that there is currently no way to enable additional apache modules while using the WordPress container. For example, I would want to enable mod_remoteip and mod_expires but I have no way of doing that right now. 

Creating my own docker image based on the bitnami image is also not an option since I am using TrueNAS apps which give no option to provide a custom image. It would also not provide a good user experience when you are forced to resort to such solution for something this trivial.

Additionally, it should be possible to provide additional apache configuration that is persistent (for example via env vars, or a volume mount) which is included in the main http config when set. There seemingly is no way to add custom config to it right now.

**Comment by fevisera** [comment]
Hi @RobReus,

Thank you for reaching out. Have you review the [Customize this image](https://github.com/bitnami/containers/tree/main/bitnami/wordpress#customize-this-image) section in our documentation? Could any of the listed options be an alternative for you?

**Comment by RobReus** [comment]
Hi @fevisera

Thanks for your reply. The only viable option for me from the linked page would be to replace the entire `httpd.conf` file, which is something I would like to prevent. When replacing that entire file, maintenance becomes more difficult as in the event that file is ever changed upstream at bitnami, it could cause problems when updating to newer image files since the custom `httpd.conf` would be missing those changes.

What would be a better option in my opinion is to include something like the following in `httpd.conf`:
`IncludeOptional "/opt/bitnami/apache/conf/extra/httpd-custom.conf"`
Then the user of the image has the option to mount a custom config file in that location (just like how you would replace `httpd.conf`) without missing out on upstream config changes whenever the image is updated. The `IncludeOptional` would prevent issues in the event that file does not exist, and the user did not mount anything there.

Additionally, it would be nice to be able to use environment variables for certain mundane config changes, like uncommenting a `LoadModule` line in `httpd.conf`. That alone would cover my entire use-case for this feature request.

If you then combine the changes to the install scripts to make more things configurable via environment variables, together with the proposed `IncludeOptional` above, you got yourself a very easy to customize image for whomever needs to make customizations.

Let me know what you think.

**Comment by fevisera** [comment]
Hi @RobReus,

Sorry for the delay, and I appreciate your additional details. It appears that there is already an `IncludeOption` in the `httpd.conf` file:
```
$ docker run --rm -it bitnami/wordpress cat /opt/bitnami/apache/conf/httpd.conf | grep IncludeOptional
IncludeOptional "/opt/bitnami/apache/conf/vhosts/*.conf"
```

Would this address the scenario you mentioned?

**Comment by RobReus** [comment]
@fevisera,

No worries. There already is an `IncludeOptional` in the config, but it is for vhosts. Although technically, I see no reason why putting normal httpd config (like including modules and other httpd specific config) would not work within that include folder, it would be highly counter intuitive to do so.

I am also not entirely sure whether or not the include order is of any importance to apache, but if it is, then it would be another reason not to use that existing `IncludeOptional`.

A better option would then be to insert something like `IncludeOptional "/opt/bitnami/apache/conf/extra/httpd-custom.conf"` to be higher up in the config file than the include for vhosts. Alternatively, it could also be a directory like `IncludeOptional "/opt/bitnami/apache/conf/extra/user/*.conf"`.

**Comment by fevisera** [comment]
Hi @RobReus,

Currently, there are no plans to introduce an alternative method for customizing the Apache configuration. However, we encourage you to actively contribute to enhancing our solution by following the [contributing guide](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md). Our team will review any change you suggest and the whole community will benefit from your changes.

It is worth noting that certain modules are already included in the `httpd.conf` file but are disabled by default, as shown below:
```
docker run --rm -it --entrypoint "" bitnami/wordpress grep -E "mod_expires|mod_remoteip" /opt/bitnami/apache/conf/httpd.conf
#LoadModule expires_module modules/mod_expires.so
#LoadModule remoteip_module modules/mod_remoteip.so
```

To activate these modules, please refer to the customization section mentioned earlier at https://github.com/bitnami/containers/issues/52422#issuecomment-1812112689. 

Your cooperation is greatly appreciated.

Thank you.

**Comment by weeix** [comment]
This issue makes sense. I believe most people would prefer using environment variables or mounting additional httpd config files instead of maintaining another pipeline.

In my case, I installed Bitnami's WordPress using Helm chart. To override the command, I had to add the `command` field in the `values.yaml` file as follows:

```yaml
...
command:
  - /bin/sh
  - -c
  - |
    sed -i -r 's/#LoadModule remoteip_module/LoadModule remoteip_module/' /opt/bitnami/apache/conf/httpd.conf
    printf \"\n<IfModule remoteip_module>\n    RemoteIPHeader X-Real-IP\n    RemoteIPInternalProxy 10.42.0.0/16\n</IfModule>\n\" >> /opt/bitnami/apache/conf/httpd.conf
    /opt/bitnami/scripts/wordpress/entrypoint.sh /opt/bitnami/scripts/apache/run.sh
```

Which seems like a hack and might break in the future.

**Comment by fevisera** [comment]
Hi @weeix,

In addition to adding those commands, you can also use `apacheConfiguration` to specify the content of your `httpd.conf`, which eliminates the need of executing commands manually.

**Comment by RobReus** [comment]
> Hi @weeix,
> 
> In addition to adding those commands, you can also use `apacheConfiguration` to specify the content of your `httpd.conf`, which eliminates the need of executing commands manually.

But this will put you at the risk of breaking the container when upstream changes happen. Since you overwrite the whole httpd.conf that way, you are responsible for maintaining that whole file just to have a single module enabled. That does not make sense to me.

What makes most sense to me is to either modify the bash scripts to make it possible to accept additional modules to enable and enable them that way, or by simply adding an extra line to `httpd.conf`:
`IncludeOptional "/opt/bitnami/apache/conf/extra/httpd-custom.conf"`

The second option would be by far the easiest option, and also the most versatile, as it could be used to enable extra modules but also to configure any other config values. It would be important however to include that file as late as possible so you could optionally overwrite any previously configured settings (assuming you can declare the same variable/setting twice and apache just uses the one most recently set).

**Comment by fevisera** [comment]
Hi @RobReus,

I still do not see why the `IncludeOptional` in `/opt/bitnami/apache/conf/httpd.conf` would not work for you. Could you give some more details?

Thanks.

**Comment by RobReus** [comment]
> Hi @RobReus,
> 
> I still do not see why the `IncludeOptional` in `/opt/bitnami/apache/conf/httpd.conf` would not work for you. Could you give some more details?
> 
> Thanks.

When you overwrite the entire `httpd.conf` file that is packaged inside the container, you become responsible for any and all upstream changes that happen to it and make sure those changes are applied any time they happen. For example: lets say I overwrite the entire `httpd.conf` file to manually add the `IncludeOptional` part, or to enable a simple module. Now an upstream change happens that upgrades the container image to for example have an new apache version. Lets imagine this new apache version deprecates some config value that is in `httpd.conf`. The `httpd.conf` is nicely updated in the container image you publish to reflect this change. When I then update my installation to use the newest container version, I can no longer just bump the version and be done with it, I now additionally need to ensure (for example by doing a `diff`) that any upstream changes in `httpd.conf` are also applied to my copied version of `httpd.conf` if applicable. If I don't do that, I run the risk of my `httpd.conf` being out of sync that could problems in case settings are deprecated or any other breaking changes are applied.

It is bad practice to overwrite complete config files in order to make 1 very tiny change. That is why things that could differ from install to install are configurable via environment variables in containers, like the listening port and other simple settings.

The proposed change of this issue is to add 1 line to the upstream `httpd.conf` file to include an `IncludeOptional` that points to a by default non-existing file. Users of this image can then place any custom config in that file by a container mount, and they only need to maintain their custom config. So instead of having to maintain a 500 line `httpd.conf` file just to enable 1 module, they only need to maintain a 1 line custom config file that is included by `httpd.conf` via the `IncludeOptional` statement. Just like how its already possible to add custom vhost config files.

This very trivial change would make this container very easily customizable for everyone who wishes to make custom config changes, without having to jump through hoops and increasing the maintenance workload. Alternatively, the entrypoint scripts should be updated to allow more customizations but that requires more development effort. This change can be accomplished by doing a simple append to `httpd.conf` in the `Dockerfile`. Let me know if its still not clear so I can elaborate further.

**Comment by fevisera** [comment]
Hi @RobReus,

Thank you so much for providing such a detailed explanation. Would you like to contribute by creating a PR to implement this feature? The Bitnami team will be happy to review it and provide feedback. You can refer to our contribution guidelines, which can be found [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

**Comment by masterkain** [comment]
too bad this is closed, I have the same need and the proposed solution doesn't work for me.
did something changed in the meantime? I'd really like to enable the remoteip_module on bitnami wordpress without resorting to a custom image.
