### ISSUE TITLE
Recent versions of bitnami/mongodb:4.4 are missing

### ISSUE THREAD

**Issue by vfiset** [bitnami/containers#52437]
### Name and Version

bitnami/mongodb:4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. List [bitnami/mongodb:4.4 versions](https://hub.docker.com/r/bitnami/mongodb/tags?page=1&name=4.4) on Docker Hub.
2. Notice that the latest is 4.4.15.
3. Notice that 4.4.16-4.4.25 are missing.

### What is the expected behavior?

Versions 4.4.16-4.4.25 would be offered on [Docker Hub](https://hub.docker.com/r/bitnami/mongodb/tags?page=1&name=4.4).

### What do you see instead?

The latest is 4.4.15.

### Additional information

The image bitnami/mongodb:4.4 most recent version is [4.4.15-debian-10-r8](https://hub.docker.com/layers/bitnami/mongodb/4.4.15-debian-10-r8/images/sha256-916202d7af766dd88c2fff63bf711162c9d708ac7a3ffccd2aa812e3f03ae209?context=explore) and is 1 year old. Since then the MongoDB team released several [4.4 versions](https://www.mongodb.com/docs/manual/release-notes/4.4/).

**Comment by carrodher** [comment]
Version 4.4.25 is not supported for Debian 11 (the distro used by default in Bitnami Application Catalog) by the upstream project itself, see
![Screenshot 2023-11-09 at 10 53 49](https://github.com/bitnami/containers/assets/13216600/756e4405-f65d-49f7-8393-e3fcf41974f6)

We support the same versions supported by upstream in the different distros, although the Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
