### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by codan84** [bitnami/containers#5247]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Performance on ARM processors (mainly Mac M1).

The issue has been there in the old repo (now archived) since Jan 2021 (https://github.com/bitnami/bitnami-docker-kafka/issues/141). The performance of `bitnami/kafka` on Mac M1 is extremely poor rendering it unusable (the container freezes or crashes up to 70% of the time on startup)

### What is the feature you are proposing to solve the problem?

Build of kafka image for ARM arch.

### What alternatives have you considered?

Kafka docker images from another source:
ubuntu/kafka
wurstmeister/kafka

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by maslow** [comment]
> Hi, we have created this issue [bitnami/charts#7305](https://github.com/bitnami/charts/issues/7305) that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.
> 
> We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

But where is the plan?

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
