### ISSUE TITLE
Please provide healthcheck.sh for Mongodb

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#52789]
### Name and Version

bitnami/mongodb:7.0

### What is the problem this feature will solve?

Start apps which depends on mongodb

### What is the feature you are proposing to solve the problem?

Provide `healthcheck.sh` for Mongodb

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
