### ISSUE TITLE
Please provide healthcheck.sh for Kafka

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#52790]
### Name and Version

bitnami/kafka:3.6

### What is the problem this feature will solve?

Start apps which depends on kafka

### What is the feature you are proposing to solve the problem?

Provide healthcheck.sh for kafka

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
