### ISSUE TITLE
[bitnami/moodle] Missing USER in Dockerfile

### ISSUE THREAD

**Issue by d4rklynk** [bitnami/containers#52979]
### Name and Version

bitnami/moodle:4.3

### What is the problem this feature will solve?

I don't see the layer USER in Dockerfile while it is recommended by OWASP in [Rule 2](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user).

### What is the feature you are proposing to solve the problem?

I understand you can extend the image and do as you wish, but wouldn't be better to set a USER by default in the Dockerfile ?
Thanks in advance for your time.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Would you like to submit a PR updating the Dockerfile?

**Comment by d4rklynk** [comment]
Hi, I could add the USER line indeed.
But it seems there's a cron job who needs root, I guess you should add a specific permission for user 1001 so he can run cron jobs as expected.

I only partially understand the Dockerfile, so one of your collegues should change that line if possible.
Thanks in advance.

```bash
root@localhost:~/debian-11# docker logs moodle
moodle 12:46:58.71
moodle 12:46:58.73 Welcome to the Bitnami moodle container
moodle 12:46:58.73 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 12:46:58.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 12:46:58.73
moodle 12:46:58.74 INFO  ==> ** Starting Moodle setup **
moodle 12:46:58.92 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
....................++++
..................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
moodle 12:46:59.35 INFO  ==> Configuring Apache ServerTokens directive
moodle 12:46:59.37 INFO  ==> Configuring PHP options
moodle 12:46:59.37 INFO  ==> Setting PHP expose_php option
moodle 12:46:59.39 INFO  ==> Setting PHP output_buffering option
moodle 12:46:59.42 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 12:46:59.43 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 12:46:59.47 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle 12:46:59.55 INFO  ==> Restoring persisted Moodle installation
moodle 12:47:02.59 INFO  ==> Trying to connect to the database server
moodle 12:47:02.67 INFO  ==> Running database upgrade
moodle 12:47:03.70 WARN  ==> Skipping cron configuration for Moodle because of running as a non-root user
moodle 12:47:03.71 INFO  ==> ** Moodle setup finished! **

moodle 12:47:03.72 WARN  ==> Cron will not be started because of running as a non-root user
moodle 12:47:03.73 INFO  ==> ** Starting Apache **
[Mon Nov 20 12:47:03.920042 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.58 (Unix) OpenSSL/1.1.1w configured -- resuming normal operations
[Mon Nov 20 12:47:03.920369 2023] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

**Comment by FraPazGal** [comment]
Hello @d4rklynk, our `bitnami/moodle` Dockerfile does miss the `USER` directive because it needs to run with the `root` by default, which would make setting `USER root` as redundant.

> I guess you should add a specific permission for user 1001 so he can run cron jobs as expected

The issue here is that Moodle expects this cron to be run by the `daemon` user, what do you propose here?

**Comment by d4rklynk** [comment]
Indeed, if the problem is Moodle-side and not Dockerfile-side, I guess you can't do anything.

I'm not sure I understand correctly though, could it be at least fixable by setting up a user deamon with some high privileges in the host and link it to the container ?

**Comment by FraPazGal** [comment]
Hi @d4rklynk, AFAIK you can only manage crons of specific users by using `crontab` and this requires root access. It would be possible to give an user root privileges, but that would defeat the purpose and identical to the current setup.

**Comment by d4rklynk** [comment]
What about we change the owner of the scripts that are runned from cron.
So the scrips are owned by 1001, and cron run the scripts as 1001 user. Would it work ?
