### ISSUE TITLE
Adding metrics to wordpress-nginx

### ISSUE THREAD

**Issue by webdz9r** [bitnami/containers#53016]
### Name and Version

bitnami/wordpress-nginx

### What is the problem this feature will solve?

Metrics are yummy

### What is the feature you are proposing to solve the problem?

added metrics from a sidecar?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
