### ISSUE TITLE
[bitnami/tomcat] image: build fails due to amazon rate limit?

### ISSUE THREAD

**Issue by Zappelphilipp** [bitnami/containers#53021]
### Name and Version

bitnami/tomcat:9.0.83

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. clone repo
2. build image with shipped Dockerfile (with fast internet?)
3. get broken docker image without error

### What is the expected behavior?

fail docker build process if one of the curl-downloads fail.

### What do you see instead?

the docker build process finishes without error and you get a broken image with missing parts (missing java in my case)

### Additional information

there are two problems:

1. the curl command in https://github.com/bitnami/containers/blob/5bb0b1f4712fd182accfcfd16599d839727d933f/bitnami/tomcat/9.0/debian-11/Dockerfile is not validated regarding its exit code. if the curl command fails the build process will go on and finish without any errors but with missing parts. 

2. The download of the java environment does fail now and then after ~65MB of download with the error code: 

```
#8 0.584 > GET /files/stacksmith/java-17.0.9-11-1-linux-amd64-debian-11.tar.gz HTTP/1.1
#8 0.584 > Host: downloads.bitnami.com
#8 0.584 > User-Agent: curl/7.74.0
#8 0.584 > Accept: */*
#8 0.584 >
#8 0.587 { [5 bytes data]
#8 0.587 * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
#8 0.587 { [124 bytes data]
#8 1.145 * Mark bundle as not supporting multiuse
#8 1.145 < HTTP/1.1 200 OK
#8 1.145 < Content-Type: application/x-tar
#8 1.145 < Content-Length: 207215026
#8 1.145 < Connection: keep-alive
#8 1.145 < Date: Mon, 20 Nov 2023 09:58:19 GMT
#8 1.145 < Last-Modified: Mon, 23 Oct 2023 16:39:55 GMT
#8 1.145 < ETag: "2eaeea86002e6e6919b6825d6e8620f7-14"
#8 1.145 < x-amz-server-side-encryption: AES256
#8 1.145 < Accept-Ranges: bytes
#8 1.145 < Server: AmazonS3
#8 1.145 < X-Cache: Miss from cloudfront
#8 1.145 < Via: 1.1 75373f3f77c169166bbce98d302dff7c.cloudfront.net (CloudFront)
#8 1.145 < X-Amz-Cf-Pop: VIE50-P1
#8 1.145 < X-Amz-Cf-Id: cKw1jnbfbTelpJp_8RLM1PZvw16DG0AI9pJeztZTwEbcz32-75tvSg==
#8 1.145 <
#8 1.145 { [15878 bytes data]
#8 12.79 * OpenSSL SSL_read: Connection reset by peer, errno 104
#8 12.79 * Closing connection 0
```

it seems like it does have something to do with my (fast) bandwith because if i add ` --limit-rate 4M` the download suceeds.

**Comment by andresbono** [comment]
Hi @Zappelphilipp, thank you for opening this issue.

Let's focus first on the first problem you mention:

> the curl command in https://github.com/bitnami/containers/blob/5bb0b1f4712fd182accfcfd16599d839727d933f/bitnami/tomcat/9.0/debian-11/Dockerfile is not validated regarding its exit code. if the curl command fails the build process will go on and finish without any errors but with missing parts.

The `curl` commands in the Dockerfile run with the `-f` (`--fail`) option, that is a first measure to take into account server side errors and exit early on the build. In addition to that, the integrity of the downloaded artifacts is checked with `sha256sum`, another command that stop the build on failures. As the [RUN](https://docs.docker.com/engine/reference/builder/#run) directive works as a `/bin/sh -c` shell, all the commands are chained with `&&` so if any of them fails, the execution should be stopped.

However, the problem is that those commands are executed in a loop. So in practice, the build will only fail based on the last iteration of the `for` loop.

A simple Dockerfile that illustrates the issue (the build should fail but it doesn't) would be:

```Dockerfile
FROM bitnami/minideb
# fails on first iteration, does nothing on the last iteration
RUN for i in 1 2; do          \
        if [ $i -eq 1 ]; then \
            echo "Big crash"; \
            false;            \
        fi;                   \
    done                      \
```

```shell
$ docker build --no-cache --progress=plain .
...
#5 [2/2] RUN for i in 1 2; do if [ $i -eq 1 ]; then echo "Big crash"; false; fi; done
#5 0.156 Big crash
#5 DONE 0.2s
...
```

We are going to investigate possible fixes and will share any updates here.

**Comment by andresbono** [comment]
Hi @Zappelphilipp, we have released a new version of [bitnami/tomcat (9.0.83-debian-11-r3, #53155)](https://github.com/bitnami/containers/pull/53155) that addresses the first problem you are mentioning in this issue. Could you please try to build it again and share what you see now?

- [bitnami/tomcat/9.0/debian-11](https://github.com/bitnami/containers/tree/fc333507b8eba731c090ef5e9943c516a3fb0dce/bitnami/tomcat/9.0/debian-11)

**Comment by Zappelphilipp** [comment]
> Hi @Zappelphilipp, we have released a new version of [bitnami/tomcat (9.0.83-debian-11-r3, #53155)](https://github.com/bitnami/containers/pull/53155) that addresses the first problem you are mentioning in this issue. Could you please try to build it again and share what you see now?
> 
thank you @andresbono. I rebuilt the image but unfortunately all downloads are working smooth today so i am not sure how to test the exact problem of curl not downloading the whole file. The build iteself works however.

**Comment by andresbono** [comment]
Thank you for checking it, @Zappelphilipp. It is in fact very strange that you had to rate limit the download to fix it. Could it be a transient issue only at that time?

**Comment by Zappelphilipp** [comment]
> Thank you for checking it, @Zappelphilipp. It is in fact very strange that you had to rate limit the download to fix it. Could it be a transient issue only at that time?

i hadn't hat the problem again since then so maybe. How did you test this kind of connection problem on your side?
