### ISSUE TITLE
[bitnami/etcd] Latest etcd image does not work

### ISSUE THREAD

**Issue by Kunamatata** [bitnami/containers#53068]
### Name and Version

bitnami/etcd:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Run `docker-compose up etcd` with the following snippet of `docker-compose.yml`
```yaml
  etcd:
    image: bitnami/etcd:3.5.9
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: "root"
    ports:
      - "2379:2379"
      - "2380:2380"
```

### What is the expected behavior?

It should be able to start. Seems like `MY_STS_NAME` might be the issue?

### What do you see instead?

Output of `docker-compose up etcd`
```
etcd-1  | etcd 01:15:49.42 INFO  ==> 
etcd-1  | etcd 01:15:49.42 INFO  ==> Welcome to the Bitnami etcd container
etcd-1  | etcd 01:15:49.42 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd-1  | etcd 01:15:49.43 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd-1  | etcd 01:15:49.43 INFO  ==> 
etcd-1  | etcd 01:15:49.43 INFO  ==> ** Starting etcd setup **
etcd-1  | etcd 01:15:49.44 INFO  ==> Validating settings in ETCD_* env vars..
etcd-1  | etcd 01:15:49.44 INFO  ==> Initializing etcd
etcd-1  | etcd 01:15:49.44 INFO  ==> Generating etcd config file using env variables
etcd-1  | etcd 01:15:49.45 INFO  ==> There is no data from previous deployments
etcd-1  | etcd 01:15:49.46 INFO  ==> Obtaining cluster member ID
etcd-1  | etcd 01:15:49.46 INFO  ==> Starting etcd in background
etcd-1  | {"level":"warn","ts":"2023-11-21T01:15:52.533989Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x40003ca700/127.0.0.1:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
etcd-1  | etcd 01:15:52.54 INFO  ==> Stored member ID: 8e9e05c52164694d
etcd-1  | etcd 01:15:52.54 INFO  ==> Stopping etcd
etcd-1  | Terminated
etcd-1  | etcd 01:15:53.58 INFO  ==> Starting etcd in background
etcd-1  | {"level":"warn","ts":"2023-11-21T01:15:56.680409Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000394a80/127.0.0.1:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
etcd-1  | etcd 01:15:56.68 INFO  ==> Enabling etcd authentication
etcd-1  | /opt/bitnami/scripts/libetcd.sh: line 269: MY_STS_NAME: unbound variable
etcd-1  | etcd 01:15:56.69 INFO  ==> Stopping etcd
etcd-1  | Terminated
etcd-1 exited with code 1
```

**Comment by Xuanwo** [comment]
This same, we workaround this by adding an empty: `MY_STS_NAME: ""`.

**Comment by jotamartos** [comment]
That variable is set for the chart, but it seems the container doesn't set a default value

https://github.com/bitnami/charts/blob/2a20db9eeda710df536ef3d5479e1c4c2e0e5a4d/bitnami/etcd/templates/statefulset.yaml#L143

Could you please set a random value to that env var? 

```
...
    environment:
      - ALLOW_NONE_AUTHENTICATION=no
      - ETCD_ROOT_PASSWORD=password
      - MY_STS_NAME=etcd
 ...
```

You can create a PR setting a default value for that variable in the [env.sh file](https://github.com/bitnami/containers/blob/main/bitnami/etcd/3.5/debian-11/rootfs/opt/bitnami/scripts/etcd-env.sh) or set a default value if the env var is empty in the script. The [CONTRIBUTING](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) guidelines explains how to create that PR.

```
            pod_name="${MY_STS_NAME:-etcd}-${i}"
```

**Comment by neverains** [comment]
have the same issue

**Comment by jotamartos** [comment]
Hi @neverains,

As I mentioned above, the fix is simple and you can generate a PR and contribute to this repository. Could you please do it? You can also add any other extra change you think we should add to the solution. A team member will review the changes and validate them.

Thanks

**Comment by andresbono** [comment]
As mentioned in the associated PRs, the next release of the etcd container will address this issue. We will post a message when the latest version is available.

**Comment by andresbono** [comment]
Hi, please, pull the latest release of the containers to get this issue fixed. Find the details of the fix below:

- https://github.com/bitnami/containers/pull/53968
- https://github.com/bitnami/containers/pull/53966
