### ISSUE TITLE
TOMCAT_EXTRA_JAVA_OPTS

### ISSUE THREAD

**Issue by christian-scheible** [bitnami/containers#53082]
### Name and Version

bitnami/tomcat:10.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setting `TOMCAT_EXTRA_JAVA_OPTS` to: `"-agentlib:jdwp=transport=dt_socket,address=*:9543,suspend=n,server=y"` using docker-compose.
2. Restarting the container using docker-compose restart

### What is the expected behavior?

The container should restart without an error.

### What do you see instead?

Tomcat is not starting because the jwdp option is set twice. This is the error log:
```
tomcat 11:46:01.30 INFO  ==> ** Starting Tomcat **
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
Error occurred during initialization of VM
agent library failed to init: jdwp
```

### Additional information

The reason why this happens is because the `TOMCAT_EXTRA_JAVA_OPTS` seems to be appended every time the container is restarted. So if you have that: `TOMCAT_EXTRA_JAVA_OPTS: "-Xms256m"` and restart the container 5 times you can see the property `-Xms256m` 6 times in the command that started Tomcat.

You can verify this using `ps -aux`.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
