### ISSUE TITLE
[bitnami/openldap] How to modify the user's modifytimestamp attribute

### ISSUE THREAD

**Issue by kenzero3** [bitnami/containers#53134]
### Name and Version

bitnami/openldap:2.5.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have 2 openldap services.
B to A service is a one-way network.
B's synchronization configuration is refreshOnly.
I found that the failed login operation of the user in service B will affect the synchronization of the operation in service A to B.
I hope there is a way to modify the modifytimestamp attribute value when service A is operating, and change the modifytimestamp attribute value to 10 minutes in the future, so that B can be perfectly synchronized.
I know that the openldap service synchronization configuration refreshAndPersist mode can solve this problem, but my network environment does not support this mode.
I can't find any information about this problem on the Internet.
I hope you guys can help me solve this problem.
Thank you from the bottom of my heart！

### What is the expected behavior?

Thank you from the bottom of my heart！

### What do you see instead?

I hope you guys can help me solve this problem.
Thank you from the bottom of my heart！

**Comment by javsalgar** [comment]
Hi!

Thank you for using Bitnami containers. It seems to me that the issue is in the configuration of openldap itself rather than the Bitnami packaging of OpenLDAP, did you check with the upstream devs? https://github.com/openldap/openldap

**Comment by kenzero3** [comment]
> Hi!
> 
> Thank you for using Bitnami containers. It seems to me that the issue is in the configuration of openldap itself rather than the Bitnami packaging of OpenLDAP, did you check with the upstream devs? https://github.com/openldap/openldap


I will try to report this issue with the upstream developers.
Thank you from the bottom of my heart.
