### ISSUE TITLE
[wordpress-nginx] Version mismatch mysql-client

### ISSUE THREAD

**Issue by gerardbosch** [bitnami/containers#53146]
### Name and Version

bitnami/wordpress-nginx:6.4.1-debian-11-r5

### What architecture are you using?

None

### What steps will reproduce the bug?

Comparing the Dockerfile of `wordpress` and `wordpress-nginx` I observed that the version of `mysql-client` does not match. I don't know if this is intended or not. Here is the diff of both Dockerfiles:

![image](https://github.com/bitnami/containers/assets/30733556/8287a153-d19b-4d1e-ae08-7cbb30841fb7)

- wordpress image is using mysql-client 11.1.3-0
- wordpress-nginx image is using mysql-client 10.11.6-0

In the diff I also see that `libphp` package is present in `wordpress` while not in `wordpress-nginx`, maybe this is fine too, I point it just in case.

Here are the permalinks to the files I mention:
- https://github.com/bitnami/containers/blob/ad58819c0e96a00e9470fa0d8a0dc7743a579db1/bitnami/wordpress/6/debian-11/Dockerfile#L31
- https://github.com/bitnami/containers/blob/ad58819c0e96a00e9470fa0d8a0dc7743a579db1/bitnami/wordpress-nginx/6/debian-11/Dockerfile#L31

### What do you see instead?

A version mismatch for mysql-client (maybe it's intended).

**Comment by Mauraza** [comment]
Hi @gerardbosch ,

The version on mysql-client in WordPress Nginx was updated. 
Thanks for reporting!!

**Comment by gerardbosch** [comment]
I see, thanks for answering @Mauraza. But the commit https://github.com/bitnami/containers/pull/53163/commits/bc03b8b3a1adb554ece2e41759de4fbecd9dc9c2 introduced a few more changes than just updating the `mysql-client`, so now the `diff` between `wordpress` and `wordpress-nginx` is bigger —mostly (but not only) for replacing `&&` by `;`.

Probably the `wordpress` Dockerfile should be updated accordingly to keep them consistent. What do you think?

- `wordpress` https://github.com/bitnami/containers/blob/d5af591e278d7f763bc24b0ee9a2851f9fa2832f/bitnami/wordpress/6/debian-11/Dockerfile
- `wordpress-nginx` https://github.com/bitnami/containers/blob/d5af591e278d7f763bc24b0ee9a2851f9fa2832f/bitnami/wordpress-nginx/6/debian-11/Dockerfile

**Comment by Mauraza** [comment]
Hi @gerardbosch, 

WordPress is in the process of updating, they will be similar.
