### ISSUE TITLE
Incorrect variable checking logic

### ISSUE THREAD

**Issue by Amfiass** [bitnami/containers#53152]
### Name and Version

bitnami/airflow:2.7.2-debian-11-r1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We use the helm chart for airflow.
If you do not import the `airflow.cfg` configuration file and import the `webserver_config.py` file and run the pod as a nonroot-user, you will receive the error `cp: cannot create regular file '/opt/bitnami/airflow/webserver_config.py': Permission denied`
The problem is that the `libairflow.sh` script incorrectly checks for the presence of the `webserver_config.py` file.
The `-n` operator returns true if the `webserver_config.py` file exists, however, after this, the file is replaced with the default one.
It is more correct to use the `-z` operator in this case.

### What is the expected behavior?

If the webserver_config.py file exists, it is not overwritten by the default

### What do you see instead?

The script tries to overwrite an existing file

**Comment by Amfiass** [comment]
https://github.com/bitnami/containers/blob/main/bitnami/airflow/2/debian-11/rootfs/opt/bitnami/scripts/libairflow.sh#L189

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Amfiass** [comment]
This problem was resolved in 4 days.

https://github.com/bitnami/containers/commit/bbc504ad640e3ea87c6d14513e60d6d95b4ee7ec

I'm closing this thread. Thank you
