### ISSUE TITLE
Openldap 2.6.6-debian-11-r60 introduces extra cn=module entry, breaking automation

### ISSUE THREAD

**Issue by mrvanes** [bitnami/containers#53160]
### Name and Version

Openldap 2.6.6-debian-11-r60

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create image and container based on bitnami/openldap:2.6
2. Run automation that enables modules like memberof (for cn=module{0},cn=config)

### What is the expected behavior?

Enabled memberof module in cn=module{0},cn=config

### What do you see instead?

Slapd refuses, because module memberof can't be found

### Additional information

The problem is, that since r60, there are now two cn=module entries in cn=config, both with a different olcModulePath of which cn=module{1} now contains the Path to the generic slapd modules (/opt/bitnami/openldap/lib/openldap) and cn=module{0} is a path that only contains pw-pbkdf2.so and pw-sha2.so (/opt/bitnami/openldap/libexec/openldap).

The problem now is that most (if not all) module enabling automation expects cn=module to be the first one (cn=module{0}) and therefor now breaks.

The best solution would be to install  pw-pbkdf2.so and pw-sha2.so in /opt/bitnami/openldap/lib/openldap and only have one cn=module{0} entry, but if it needs to be separated, please make /opt/bitnami/openldap/libexec/openldap cn=module{1} and leave cn=module{0} alone with olcModulePath=/opt/bitnami/openldap/lib/openldap.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
