### ISSUE TITLE
[bitnami/wordpress-nginx] Best practice to setup Let's Encrypt in Wordpress Docker container

### ISSUE THREAD

**Issue by gerardbosch** [bitnami/containers#53183]
### Name and Version

bitnami/wordpress-nginx:6.4.1-debian-11-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi there,

I'd like to deploy a site to my own VPS by using docker-compose and enable SSL (TLS?) with Let's Encrypt and auto-renewal.

After starting to play with Bitnami's `wordpress-nginx` container and following this guide: https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/ to enable SSL, I realized that neither `sudo` nor `/opt/bitnami/bncert-tool` is available. Then I realized that the guide is for AWS and not for Docker itself.

So, I'm wondering now what's the best or easiest way to enable HTTPS on the site (no Kubernetes here, only a single self-managed VPS). I'd like to use CloudFlare as DNS and CDN.

I was not able to find any guide for this with Bitnami's image. Could you provide some tip or guide? Maybe there's one and I missed it 😅

Thanks!

**EDIT:** `crontab` is not present either. To connect to the container I'm doing: `docker-compose exec -it wordpress bash`

### What do you see instead?

Missing toolbox to setup certificates via Let's Encrypt.

### Additional information

Related issue: https://github.com/bitnami/containers/issues/24870

**Comment by gerardbosch** [comment]
I'm not sure if I'm going the right direction...

Is it strictly necessary that I create a derived Docker image to include a Let's Encrypt client like Lego and use my own image for that?

I'm not very sure this is the way to go, as enabling https and installing the SSL cert, looks a very general use case.

Some references I followed:
- https://go-acme.github.io/lego/dns/cloudflare/
- https://charbelnemnom.com/renew-lets-encrypt-certificate-cloudflare/

**Comment by carrodher** [comment]
If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by gerardbosch** [comment]
> we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

Hi! Thanks for your answer. What forums do you refer? Is there a community forum for Bitnami? Didn't find anything on https://bitnami.com/

Cheers!

**Comment by luthis1124** [comment]
I have the same question.

What is the correct process for generating certs using the wordpress-nginx image?

**Comment by luthis1124** [comment]
And also where are the forums mentioned earlier?

**Comment by javsalgar** [comment]
Hi,

The guide you were using is related to the Bitnami WordPress cloud image, not the container. When using containers we recommend using Kubernetes in production, where you can use already existing tools like cert-manager or similar. For the container standalone, I'm not entirely sure what the best option would be. In the past I mounted the generated certificates.

**Comment by gerardbosch** [comment]
Hi!

@javsalgar, I'm interested in container standalone in a single VPS, as deploy a Kubernetes cluster for a small site looks an overkill, doesn't it?

@kimdre This sounds pretty interesting! Could you give some more hints about the setup? Could the NGINX instance that is already used in this bitnami/wordpress-nginx do the job? In case it is, any tip, guide or reference to setup the Let's Encrypt with it? 

Thank you both!

**Comment by luthis1124** [comment]
My method to solve this was just to add certbot to the wordpress-nginx image using a Dockerfile:

`
cat Dockerfile 
FROM bitnami/wordpress-nginx

## Change user to perform privileged actions
USER 0
## Install 'vim'
RUN install_packages certbot
RUN install_packages vim
## Revert to the original non-root user
USER 1001
`

and then persist the cert directories.

**Comment by gerardbosch** [comment]
> My method to solve this was just to add certbot to the wordpress-nginx image using a Dockerfile:
> 
> ` cat Dockerfile FROM bitnami/wordpress-nginx
> 
> USER 0 RUN install_packages certbot RUN install_packages vim USER 1001 `
> 
> and then persist the cert directories.

Thanks! Yep, certbot seems an easy way.
