### ISSUE TITLE
mysql初始化的时候libos.sh脚本执行过程中被kill

### ISSUE THREAD

**Issue by XCN12345** [bitnami/containers#53225]
### Name and Version

bitnami/mysql:5.7.43-debian-11-r4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

重新安装之后依然这个错误，目前使用的k8s版本是1.19.0

`debug_execute() {
    if is_boolean_yes "${BITNAMI_DEBUG:-false}"; then
        "$@"
    else
        "$@" >/dev/null 2>&1
    fi
}`

就是这个函数不通过

### What do you see instead?

1，尝试去掉此函数，服务无法启动
2，注释报错的这行，服务无法启动
3，修改所取值的环境变量之后，依然报错，目前两个步骤都执行不下去

**Comment by carrodher** [comment]
Unfortunately, we don't understand what is your specific issue. In order to be able to help, could you please edit the description so the explanation is provided in English? Thanks
