### ISSUE TITLE
Unable to register the broker because the RPC got timed out

### ISSUE THREAD

**Issue by slominskir** [bitnami/containers#53255]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On Windows 11 (10.0.22621 Build 22621)
On Docker Desktop Version 4.25.2

Using PowerShell download bitnami compose file and run it:
```
PS C:\Users\ryans> wget https://raw.githubusercontent.com/bitnami/containers/main/bitnami/kafka/docker-compose-cluster.yml -O docker-compose-cluster.yml
PS C:\Users\ryans> docker compose -f docker-compose-cluster.yml up
```

### What is the expected behavior?

Kafka cluster of containers should start up

### What do you see instead?

There appears to be a network issue blocking the containers from executing RAFT voting communications.

I see a lot of repeated log messages of the form:
```
initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet.
```

Container logs attached:
[docker-logs.txt](https://github.com/bitnami/containers/files/13479470/docker-logs.txt)

### Additional information

This was working in the past though with older versions of everything.  I just got a completely new Windows PC and am setting up from scratch.   I am behind a corporate firewall with intercepting TLS proxy and I had odd DNS issues that I suspect may be the culprit here too.  So it may be related to: https://github.com/JeffersonLab/wildfly/issues/4.   Or it could be a desktop firewall?   Or maybe the latest version of everything just doesn't work well together.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
