### ISSUE TITLE
Build keycloak 23.0.0 image

### ISSUE THREAD

**Issue by pkeuter** [bitnami/containers#53268]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Keycloak 23.0.0 has been released last week containing some important fixes and updates. It would be great if bitnami could release the 23.0.0 version of the binami/keycloak-image.

### What is the feature you are proposing to solve the problem?

Add support for keycloak 23.0.0

**Comment by carrodher** [comment]
Unfortunately, it's still in the oven. Given the number of applications we have in our catalog, we were not able to onboard yet this major version. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by carrodher** [comment]
The new version has been already released, see the changes
- in the container image: https://github.com/bitnami/containers/pull/54244
- in the Helm chart: https://github.com/bitnami/charts/pull/21762

Thanks for your patience, feel free ping us if you find any issue
