### ISSUE TITLE
Wordpress mu-plugins folder

### ISSUE THREAD

**Issue by natanoelk** [bitnami/containers#53295]
### Name and Version

bitnami/wordpress:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Colleagues,

I'm trying to add mu-plugins under wp-content, plugins are loaded, but when trying to get the configuration it's getting 404 as it's trying to locate files under `/opt/bitnami/wordpress/wp-content/plugins/bitnami/wordpress/wp-content/mu-plugins`.

It's adding another path `plugins/bitnami/wordpress/wp-content/`, is this the expected behavior?
Log:
```
"GET /wp-content/plugins/bitnami/wordpress/wp-content/plugins/bitnami/wordpress/wp-content/mu-plugins/amazon-s3-and-cloudfront/assets/css/settings.css?ver=3.2.5 HTTP/1.1" 404 47364
```

I just want to create a base image where I have some plugins been activate and user are not able to disable it

### What is the expected behavior?

Load plugins as expected

### What do you see instead?

A redirect to another path

**Comment by carrodher** [comment]
Is there any reason to not add them using the `WORDPRESS_PLUGINS` env. variable?
> `WORDPRESS_PLUGINS`: List of WordPress plugins to install and activate, separated via commas. Can also be set to all to activate all currently installed plugins, or none to skip. Default: none

**Comment by natanoelk** [comment]
Is there any news about how to use mu-plugins wordpress folder on bitnami?
