### ISSUE TITLE
Critical and High Vulnerabilities found in bitnami/magento:2.4.6

### ISSUE THREAD

**Issue by apatwal72** [bitnami/containers#53297]
### Name and Version

bitnami/magento:2.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Ran the following command `trivy image bitnami/magento:2.4.6` which produced the vulnerabilities in the attached log file. 

### What is the expected behavior?

No critical/high vulnerabilities

### What do you see instead?

[log.txt](https://github.com/bitnami/containers/files/13504052/log.txt)

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
