### ISSUE TITLE
SASL gssapi

### ISSUE THREAD

**Issue by Sarevok933219** [bitnami/containers#53345]
### Name and Version

bitnami/ldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Good day. We are using ldap service from your image. And It is necessary to add gssapi support in supportedSASLmechanisms to the container to authenticate using kerberos. By default this method is not accepted. Command: 
`ldapsearch -H ldaps://fqdn:636 -D cn=config -w <passwd> -x -b "" -LLL -s "base" supportedSASLMechanisms`
returns:
```
supportedSASLMechanisms: PLAIN
supportedSASLMechanisms: ANONYMOUS
```
Please give any working example how we can add this feature in container. Is it even possible? We also try to use python libs (ldap3)  to operate with ldap server, but also have no idea.  Thank you in advance!!!

### What is the expected behavior?

```
supportedSASLMechanisms: gssapi
supportedSASLMechanisms: PLAIN
supportedSASLMechanisms: ANONYMOUS
```

### What do you see instead?

```
supportedSASLMechanisms: PLAIN
supportedSASLMechanisms: ANONYMOUS
```

**Comment by rafariossaa** [comment]
Hi,
  I am not an openldap/kerberos expert. The provided openldap server is a basic one, so you would need to enabled the desired modules and set the configuration accordingly. If you have a configuration procedure for this maybe I could provide some guidance on how to use it with this container image.
  Do you have any instructions on how to configure this in a regular openldap service ?
