### ISSUE TITLE
[bitnami/mongodb] Constant restarting, mongodb container

### ISSUE THREAD

**Issue by SRT392** [bitnami/containers#53353]
### Name and Version

bitnami/mongodb:5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I was using Rocketchat container for a long time, after doing a image update to 6.4.2 the bitnami/mongodb container is on a constant restart loop. 

### What is the expected behavior?

The container is supposed to start and run. Then Rocketchat can connect and use the database.

### What do you see instead?

I see restarting in ... seconds, and it never runs just restart loop. Because the database is restarting the rocketchat container cannot work properly either. There seems to be an issue with the libos.sh script but I do not know what that means/does as it was working perfectly fine just a day ago before I updated the rocket.chat container.

![Screenshot 2023-12-01 094644](https://github.com/bitnami/containers/assets/68977071/65ba52be-b9c6-4e16-885b-eb1e56787899)
![Screenshot 2023-12-01 094716](https://github.com/bitnami/containers/assets/68977071/40870a4d-6be5-45fe-8352-1bb9c6f83cb0)

**Comment by frame-fF** [comment]
I have the same problem now is there a solution?
