### ISSUE TITLE
[bitnami/mariadb] Unable to get persistent volume working with mariadb container

### ISSUE THREAD

**Issue by hexclann** [bitnami/containers#53505]
### Name and Version

bitnami/mariadb:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Create a maria db container with latest tag using:
`
docker run --restart always --name mariadb -p 127.0.0.1:15000:3306 -e MARIADB_ROOT_USER=root -e MARIADB_ROOT_PASSWORD=myrootpass -e MARIADB_EXTRA_FLAGS='--max-connect-errors=1000 --max_connections=600 --max_heap_table_size=64M --tmp_table_size=64M --query_cache_size=64M --wait_timeout=60 --innodb_file_per_table=1 --innodb_buffer_pool_size=1G' -v /opt/dbvolume:/bitnami/mariadb -d bitnami/mariadb:latest
`
2. Create few databases
3. Remove the existing container using `docker rm -f mariadb`
4. Create a new container using the same name and volume but with different tag:
`
docker run --restart always --name mariadb -p 127.0.0.1:15000:3306 -e MARIADB_ROOT_USER=root -e MARIADB_ROOT_PASSWORD=myrootpass -e MARIADB_EXTRA_FLAGS='--max-connect-errors=1000 --max_connections=600 --max_heap_table_size=64M --tmp_table_size=64M --query_cache_size=64M --wait_timeout=60 --innodb_file_per_table=1 --innodb_buffer_pool_size=1G' -v /opt/dbvolume:/bitnami/mariadb -d bitnami/mariadb:10.6.16-debian-11-r1
`

### What is the expected behavior?

The mariadb should work since it is launched using the same persistent volume.

### What do you see instead?

All the databases created using the first run will be lost and i cannot run `mariadb` command cannot be accessed from inside the container:
```
I have no name!@3a0d2725aac7:/$ mariadb
ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
```

If I remove this container and spinup a container with `latest` tag, everything works including the old databases.

```
I have no name!@63b98fb6afba:/$ mariadb -uroot -pmyrootpass
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 11.1.3-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```

How can I make sure my databases will be saved during mariadb upgrade process when there is a new image?

**Comment by carrodher** [comment]
Are you facing the same issue but using the same tag in the second attempt? Please note at this moment `latest` points to `11.1.3`, while the second deployment is using `10.6.16`, there can be major changes because you're using totally different MySQL branches, for instance the database schema could be a different one

**Comment by hexclann** [comment]
No, when I use the latest tag again everything works. But how do I make sure that my volume is compatible with future version of mariadb if there's any major changes?

**Comment by javsalgar** [comment]
Hi!

That's something to be answered by the upstream mariadb devs: https://mariadb.com/kb/en/upgrading/

However, it should be safe to assume that if you're upgrading between major versions it will not be straightforward, requiring manual intervention.

**Comment by hexclann** [comment]
Thanks for the info. I'm now using mysqldump to backup all the databases before changing the mariadb versions and it seems to be working on versions released since 2014.

I'm copying the backup file to /tmp inside the mariadb container using docker cp command. However after restoring the database I cannot delete the file from /tmp, it's throwing an error - operation not permitted. Any idea on how to fix this?

**Comment by javsalgar** [comment]
Hi,

You mention that the database is successfully restored but the tmp file is still there, right? You can try removing the pod and the redeployed pod should not have the tmp file.

**Comment by hexclann** [comment]
Thanks
