### ISSUE TITLE
is_dir_empty did not ignore lost+found directory

### ISSUE THREAD

**Issue by philipwu-matroid** [bitnami/containers#53696]
### Name and Version

5.0/debian-11

### What architecture are you using?

None

### What steps will reproduce the bug?

When attaching an empty disk to /bitnami/mongodb/data/db directory on AWS, a lost+found directory is automatically generated. is_dir_empty function should ignore this directory

### What do you see instead?

Mongodb authentication failed

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
