### ISSUE TITLE
[Drupal] What is the expected development scenario using the docker image?

### ISSUE THREAD

**Issue by datawench** [bitnami/containers#53714]
### Name and Version

bitnami/drupal:10.1

### What is the problem this feature will solve?

I've done quite a bit of searching, especially in these issues, and I have yet to come across the definitive recipe for what should be a straightforward process.

In short: if one follows the provided instruction to get the drupal docker-compose.yml and execute it, how then are you supposed to do normal development with it? 

By normal I mean using an IDE to access the code, create custom modules, modify composer to apply patches, and so on... and then ultimately to commit your work to a git repository which can be deployed and used in a CI/CD process to build the final application at some endpoint, specifically using bitnami's kubernetes helm implementation for drupal.

Since the bitnami installation actually installs drupal itself, along with the composer file that built it, any upstream build will overwrite any changes you figure out how to make inside the container, losing your custom work entirely.

### What is the feature you are proposing to solve the problem?

This isn't really a feature request, but the provided issue template makes this required. One might consider it a request for better documentation, however.

### What alternatives have you considered?

Our current approach involves working with a code base outside the bitnami containers for local development, using ddev to provide the LAMP services. The code is in a normal directory, treated as a git repo, and accessible to our IDE. The repo is housed in a gitlab instance, with pipelines set up to deploy the project to an AWS-hosted kubernetes cluster.

To get around the issue described, we have a Dockerfile that, after the bitnami containers are rebuilt and running, copies all our work from the git-managed directories into the bitnami-created directories (opt/bitnami/etc), and reruns composer, effectively reinstalling the entire application, but now with all our custom work intact.

It works. But it strikes one as naive (if clever), and I'm convinced that there's some fundamental aspect of all this that we don't fully grok, and which is not made crystal clear by available documentation.

I know the "team" doesn't monitor these issues closely, but I find no other way to ask for support on this. If anyone can provide something definitive and lucid, it would greatly be appreciated.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by datawench** [comment]
I'm afraid I don't have a solution to contribute, because it's not a question of altering bitnami's code in some way, it's a question of how to properly work with it.

I have to believe that someone, somewhere is using this to do "normal" Drupal development and deployment. My question is _how_?

I'm currently working on a less bizarre workaround, involving mounting our custom work as volumes targeting the /bitnami/drupal/... directories. It's a bit less hair-raising than the big "copy all this stuff into the container" script we're currently using in the Dockerfile. It still feels... weird.
