### ISSUE TITLE
[bitnami/kibana] Kibana support Environment variable KIBANA_I18N_LOCALE

### ISSUE THREAD

**Issue by leshalv** [bitnami/containers#53710]
### Name and Version

bitnami/kibana:8

### What is the problem this feature will solve?

Supports the configuration of internationalization languages required by users

### What is the feature you are proposing to solve the problem?

Add the environment variable

**Comment by leshalv** [comment]
> Hi,
> 
> Is this env var directly consumed by kibana? What error did you see when setting it?

yes kibana currently has this variable

**Comment by im-jinxinwang** [comment]
hi @javsalgar 
Is there any documentation that explains the correspondence between parameters and variables? I have looked at the official Kibana documentation, but I did not find similar variables as shown in the screenshot. I would like to know how the variables of bitnami/kibana are recognized by Kibana.
![image](https://github.com/bitnami/containers/assets/39941928/3b3188bb-2e20-49c4-9e99-a17e1c9787b3)

**Comment by leshalv** [comment]
> 你好@javsalgar 有没有文档解释参数和变量之间的对应关系？我查看了 Kibana 官方文档，但没有找到类似截图所示的变量。我想知道Kibana是如何识别bitnami/kibana的变量的。 ![图像](https://private-user-images.githubusercontent.com/39941928/289798834-3b3188bb-2e20-49c4-9e99-a17e1c9787b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzEzNTEsIm5iZiI6MTcwMjM3MTA1MSwicGF0aCI6Ii8zOTk0MTkyOC8yODk3OTg4MzQtM2IzMTg4YmItMmUyMC00OWM0LTllOTktYTE3ZTFjOTc4N2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNTVlYzNhMDQ0YzE3NWVkOGI2ODY3ZWZjYjgzYzQ2MTIyZmE4ZDExZTNjOTA1NDI2MDYxMWIyMjc4OTFjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dFjqFn5mvAGpB4Kk6MdZCFvwAhL4oIJT7IlpvX883TM)

bitnami has its own script, and you can check out the source code if you're interested

**Comment by leshalv** [comment]
1

**Comment by leshalv** [comment]
1

**Comment by leshalv** [comment]
1

**Comment by leshalv** [comment]
1
