### ISSUE TITLE
[bitnami/rabbitmq] RABBITMQ_NODE_PORT_NUMBER and RABBITMQ_MANAGEMENT_PORT_NUMBER making too long for boot.

### ISSUE THREAD

**Issue by saytesnake** [bitnami/containers#53774]
### Name and Version

bitnami/rabbitmq:3.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just easy test,
```
docker run -it --rm \
  -e RABBITMQ_USERNAME=admin \
  -e RABBITMQ_PASSWORD=admin \
  -e RABBITMQ_VHOST=ESB \
  -e RABBITMQ_NODE_PORT_NUMBER=35672 \
  -e RABBITMQ_MANAGEMENT_PORT_NUMBER=45672 \
  -e RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=2GB \
  -e RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=yes \
  bitnami/rabbitmq:3.12
```
And it well be 100%  (for my PC and Server) output like,
```
rabbitmq 18:11:59.07 
rabbitmq 18:11:59.07 Welcome to the Bitnami rabbitmq container
rabbitmq 18:11:59.07 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 18:11:59.07 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 18:11:59.07 
rabbitmq 18:11:59.07 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 18:11:59.08 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 18:11:59.09 INFO  ==> Initializing RabbitMQ...
realpath: /bitnami/rabbitmq/conf: No such file or directory
rabbitmq 18:11:59.10 INFO  ==> Generating random cookie
rabbitmq 18:11:59.12 INFO  ==> Starting RabbitMQ in background...
rabbitmq 18:13:46.39 ERROR ==> Couldn't start RabbitMQ in background.
```
timeout maybe?

So I need to add `--restart always`, and create a persistence something like `-v /opt/rabbitmq_data:/bitnami`,
and `docker run` again.

After first boot fail, it will restart, and then the next startup will be faster (or so call normal), probably because the persistence file has been generated.

Through elimination, it was found that the problem was with `RABBITMQ_NODE_PORT_NUMBER` and `RABBITMQ_MANAGEMENT_PORT_NUMBER` env.

### What do you see instead?

When set `RABBITMQ_NODE_PORT_NUMBER` and `RABBITMQ_MANAGEMENT_PORT_NUMBER` to change that ports inside, It well cost boot failed in first time.

**Comment by mdhont** [comment]
I'm not sure what the cause is but choosing different number RABBITMQ_NODE_PORT_NUMBER works. Could you confirm that?

```
docker run -it --rm \
  -e RABBITMQ_USERNAME=admin \
  -e RABBITMQ_PASSWORD=admin \
  -e RABBITMQ_VHOST=ESB \
  -e RABBITMQ_NODE_PORT_NUMBER=35671 \
  -e RABBITMQ_MANAGEMENT_PORT_NUMBER=45672 \
  -e RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=2GB \
  -e RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=yes \
  bitnami/rabbitmq:3.12
```

**Comment by saytesnake** [comment]
@mdhont 

I've confirmed that you're right, and I also try,

`RABBITMQ_NODE_PORT_NUMBER=15672`
`RABBITMQ_NODE_PORT_NUMBER=25672`
`RABBITMQ_NODE_PORT_NUMBER=35672`
`RABBITMQ_NODE_PORT_NUMBER=45672`
`RABBITMQ_NODE_PORT_NUMBER=55672`
`RABBITMQ_NODE_PORT_NUMBER=65672`

Some issues, and don't know what happened, only work with `RABBITMQ_NODE_PORT_NUMBER=5672` and it's default value.

Maybe something wrong with the `RABBITMQ_NODE_PORT_NUMBER` variable with `*5672` ?
