### ISSUE TITLE
Add JMX to Prometheus exporter to Kafka image

### ISSUE THREAD

**Issue by janvanbesien-ngdata** [bitnami/containers#53816]
### Name and Version

bitnami/kafka 26.0.0

### What is the problem this feature will solve?

See https://github.com/bitnami/charts/issues/21309

### What is the feature you are proposing to solve the problem?

I am working on a PR for https://github.com/bitnami/charts/issues/21309 for which I need to include the jmx exporter in the Kafka image.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
