### ISSUE TITLE
[bitnami/pgbouncer] allow passing server_round_robin.

### ISSUE THREAD

**Issue by Tomburgs** [bitnami/containers#53923]
### Name and Version

bitnami/pgbouncer:1.21.0

### What is the problem this feature will solve?

it'll allow using server connections in round robin fashion.

from pg bouncer docs:
> By default, PgBouncer reuses server connections in LIFO (last-in, first-out) manner, so that few connections get the most load. This gives best performance if you have a single server serving a database. But if there is a round-robin system behind a database address (TCP, DNS, or host list), then it is better if PgBouncer also uses connections in that manner, thus achieving uniform load.

### What is the feature you are proposing to solve the problem?

allow passing `PGBOUNCER_SERVER_ROUND_ROBIN` environment variable to the container.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the request. I will folward this to the engineering team. However, if you want to speed up the process, would you like to submit a PR adding the env var?

**Comment by mehdithreem** [comment]
@javsalgar 
I've created a pull request which I believe is straightforward, but I wasn't able to test it. Could you please review it when you have a chance?

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
