### ISSUE TITLE
Torchaudio not importing

### ISSUE THREAD

**Issue by cemoody** [bitnami/containers#53931]
### Name and Version

pytorch

### What architecture are you using?

None

### What steps will reproduce the bug?

Just run `python -c 'import torchadio'` within the pytorch docker image.

### What is the expected behavior?

It should correctly import. 

### What do you see instead?

For versions 2.1.2 and 2.1.1 I get `undefined symbol` errors indicating a bad install environment. Version 2.1.0 works fine.

### Additional information

V2.1.2:
<img width="814" alt="image" src="https://github.com/bitnami/containers/assets/3419930/f748e9ed-20d7-4dea-bca4-0a48094f79de">

V2.1.1:
<img width="805" alt="image" src="https://github.com/bitnami/containers/assets/3419930/5802f181-03c0-4f9e-aeb5-2d90693278e6">

V2.1.0:
<img width="702" alt="image" src="https://github.com/bitnami/containers/assets/3419930/320a3529-4a89-42a4-8824-0d0112326cfd">

**Comment by cemoody** [comment]
Oh hurray! Glad I could help

**Comment by rafariossaa** [comment]
Hi,
  Could you give release `2.2.0-debian-11-r1` a try ? it should fix this issue.

**Comment by rafariossaa** [comment]
I am closing this issue. Please, don't hesitate to reopen it if needed.
