### ISSUE TITLE
[bitnami/matomo] Will the version 5 be available soon?

### ISSUE THREAD

**Issue by fredimitchel** [bitnami/containers#53962]
### Name and Version

bitnami/matomo:5

### What is the problem this feature will solve?

I'd just see Matomo 5 is available since June 2023 and I would like to switch to the new version.

### What is the feature you are proposing to solve the problem?

I would like to get the docker image to make the upgrade, can you share with me if there is a plan for providing a version for ?

**Comment by fredimitchel** [comment]
My bad, I can update the version directly from the application.

That's said, I'm questioning me if new installation will install the latest major version of Matoto (the 5th one) ?

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible.

**Comment by viceice** [comment]
Should this issue be reopened until the new version is published?

**Comment by andtii** [comment]
@carrodher Any progress on this? When do you think it will be ready to use?

**Comment by carrodher** [comment]
Since it is a major version it requires some manual changes on our side, unfortunately, we can't provide an ETA

**Comment by PhilippeVienne** [comment]
@carrodher do you have details on the issue about what is bugging? One of our clients need the new version and we want to correct it

**Comment by SOFSPEEL** [comment]
Please note that latest version of bitnami helm chart 4.0.1 fails as follows:

- install the following on your cluster (in my case AKS) https://artifacthub.io/packages/helm/bitnami/matomo/4.0.1. The k8s deployment and pods install successfully.
- From the admin web page: click the **NEW UPDATE: MATOMO 5.0.0**, and update fully, this succeeds.
- Delete the PODs
- PODs don't restart successfully

The POD doesn't start for the following reason:

Your Matomo codebase is running the old version **4.16.0** and we have detected that your Matomo Database has already been upgraded to the newer version **5.0.1.** Maybe your Matomo administrators are currently finishing the upgrade process. Please try again in a few minutes. If you still have this issue please contact your Matomo administrator for assistance.

So this is another reason add support for 5.0. But also isn't there a way to prevent the  **NEW UPDATE: MATOMO 5.0.0** button from showing up if the associated app is not updated.

**Comment by viceice** [comment]
updating matomo via web admin is not supported for docker images.

**Comment by aurelhann** [comment]
But we can overwrite the image base on helm values to migrate for real to 5.0.

But for that we need to pull the bitnami image with the 5.0 tag.

Could I done that with a PR ?

**Comment by JoshuaSmeda** [comment]
+1 for the V5 release. 🚀

**Comment by aurelhann** [comment]
I could'nt push a PR because of the bitnami stacksmith artefactory...
too bad

We will need the v5 please :pray: :)

**Comment by kevin-shelaga** [comment]
im getting crashloops running v5 in kubernetes `rm: cannot remove '/opt/bitnami/matomo': Permission denied`

Anyone else having this issue? This wasnt a problem in v4

**Comment by JoshuaSmeda** [comment]
Yup, I have the same issue.

**Comment by aurelhann** [comment]
Ooh... v5 finally released :champagne: 

I'll go to test it for confirming the issue ;)

**Comment by carrodher** [comment]
The new major version was released 🎉 

Here you can find the container image
* https://github.com/bitnami/containers/tree/main/bitnami/matomo
* https://hub.docker.com/r/bitnami/matomo

About the Helm chart, you can find it at
* https://github.com/bitnami/charts/tree/main/bitnami/matomo
* https://hub.docker.com/r/bitnamicharts/matomo

**Comment by kevin-shelaga** [comment]
fixed by running the pod with root and then hit https://forum.matomo.org/t/update-matomo-4-16-0-5-0-0-error/54668
The fix listed there addressed all issues and the pods started
