### ISSUE TITLE
Being able to inject custom configs to pgpool

### ISSUE THREAD

**Issue by mhkarimi1383** [bitnami/containers#53982]
### Name and Version

bitnami/pgpool:4

### What is the problem this feature will solve?

Adding custom configs to pgpool image (e.g. Caching options)

### What is the feature you are proposing to solve the problem?

Having a directory (something like `conf.d`) that is included in the main configuration file (Just like what we have postgresql and postgresql-repmgr) 

or

adding an ENV that adds/injects custom content into pgpool config

### What alternatives have you considered?

Overriding generated config file by using a readonly volume (but we will lost that configuration generation from ENVs)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
