### ISSUE TITLE
MySQL replica when missing master binary logs

### ISSUE THREAD

**Issue by michel-silva** [bitnami/containers#54028]
### Name and Version

bitnami/mysql:8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1 - Master server with data but without all binary files;
2 - Building a slave container;

### What is the expected behavior?

The replication would be fail, but the passwords should working 

### What do you see instead?

After create container the replication fail and I tried to log to MySQL slave to run MySQL dump extract from master, but the passwords doesn’t work.

### Additional information

I don’t be certain that is a bug. But I need create a slave server and didn't it work

**Comment by michel-silva** [comment]
This other issue describe exactly what occur in my slave.

https://github.com/bitnami/containers/issues/34145

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
