### ISSUE TITLE
Redmine Cannot Connect to Database

### ISSUE THREAD

**Issue by max1e6** [bitnami/containers#54223]
### Name and Version

docker.io/bitnami/redmine:5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Ubuntu 22.04
Docker version 24.0.7, build afdd53b
Downloaded the docker-compose.yml
docker-compose up

### What is the expected behavior?

Expected redmine to connect to database.

### What do you see instead?

redmine-redmine-1  | redmine 19:04:28.84 ERROR ==> Could not connect to the database
redmine-redmine-1 exited with code 1

**Comment by max1e6** [comment]
I just added this issue again with more information. If that is helpful.

**Comment by carrodher** [comment]
Closed as duplicated of https://github.com/bitnami/containers/issues/54298
