### ISSUE TITLE
openldap NETBIOS name

### ISSUE THREAD

**Issue by sergiobaiao** [bitnami/containers#54305]
### Name and Version

bitname/openldap

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to run a web app that only supports logins as a netbios alias, like DOMAIN\Username

### What is the expected behavior?

Openldap is not accepting it

### What do you see instead?

do_bind: invalid dn (domain\username)

### Additional information

How can i fix this?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
