### ISSUE TITLE
Multiple Organizations at Root Level

### ISSUE THREAD

**Issue by netlander** [bitnami/containers#54381]
### Name and Version

docker.io/bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Add custom ldif file to create another organization at the root level prevents the server from starting.

### What is the expected behavior?

Expect to be able to create different and distinct organizations (not under LDAP_ROOT).

### What do you see instead?

Server crash and burn.

### Additional information

Organizations can be created uder LDAP_ROOT but what's needed is independent orgs, OpenLDAP can handle this (not a limitation of OpenLDAP).

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
