### ISSUE TITLE
[bitnami/ejbca] docker-compose up / http://host.domain.box:8080 returns 404

### ISSUE THREAD

**Issue by d3vopz-net** [bitnami/containers#54412]
### Name and Version

bitnami/ejbca:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/ejbca/docker-compose.yml > docker-compose.yml
docker compose up
```

### What is the expected behavior?

The UI becomes available on http://host.domain.box:8080

### What do you see instead?

redirection to http://host.domain.box:8080/ejbca and 404

### Additional information

[ejbca.log](https://github.com/bitnami/containers/files/13844038/ejbca.log)

**Comment by rafariossaa** [comment]
Hi,
  You should go to `https://localhost:8443/ejbca/ra/enrollwithudername.xhtml?username=superadmin`  (this link is in [ejbca documentation](https://doc.primekey.com/ejbca/tutorials-and-guides/quick-start-guide-start-ejbca-container-with-client-certificate-authenticated-access#QuickStartGuideStartEJBCAContainerwithClientCertificateAuthenticatedAccess-Step2-StartEJBCACommunitycontainer)) and download the .p12 cert using the [default password](https://github.com/bitnami/containers/tree/main/bitnami/ejbca#user-content-configuration): `Bitnami1234`. Then you need to add the cert to the browser cert manager as user certificates. The password for the .p12 file is the same (`Bitnami1234`) .
  Now you should be able to login using the imported certificate.

**Comment by d3vopz-net** [comment]
Using the provided link: `https://localhost:8443/ejbca/ra/enrollwithudername.xhtml?username=superadmin`
![image](https://github.com/bitnami/containers/assets/48279634/dd4409fc-4868-43fb-b50d-907e50498461)
