### ISSUE TITLE
[bitnami/discourse] build fails due to missing packages

### ISSUE THREAD

**Issue by attalbialami** [bitnami/containers#54478]
### Name and Version

bitnami/discourse:3.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to build Discourse image version 3.0.4 (3.0.4-debian-11-r5)

The build fails due to missing packages (error log message: `curl: (22) The requested URL returned error: 404 Not Found`)

Below are the packages required to build this version (missing packages are written in bold with their links)
- python-3.9.17-1-linux-amd64-debian-11.tar.gz
- wait-for-port-1.0.6-9-linux-amd64-debian-11.tar.gz
- **ruby-3.2.2-2-linux-amd64-debian-11.tar.gz** [link to test](https://downloads.bitnami.com/files/stacksmith/ruby-3.2.2-2-linux-amd64-debian-11.tar.gz)
- **postgresql-client-15.3.0-1-linux-amd64-debian-11.tar.gz** [link to test](https://downloads.bitnami.com/files/stacksmith/postgresql-client-15.3.0-1-linux-amd64-debian-11.tar.gz)
- node-18.16.1-0-linux-amd64-debian-11.tar.gz
- **brotli-1.0.9-161-linux-amd64-debian-11.tar.gz** [link to test](https://downloads.bitnami.com/files/stacksmith/brotli-1.0.9-161-linux-amd64-debian-11.tar.gz)
- discourse-3.0.4-0-linux-amd64-debian-11.tar.gz

If I try to manually download one of those missing packages, i.e. https://downloads.bitnami.com/files/stacksmith/ruby-3.2.2-2-linux-amd64-debian-11.tar.gz; then I am just redirected back to https://bitnami.com/.

### What is the expected behavior?

The image should build successfully when following the specified instructions.

### What do you see instead?
```
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by carrodher** [comment]
Thanks for letting us know, those intermediate tarballs should be now available.

**Comment by attalbialami** [comment]
Thank you for providing the missing tarballs; it will help us build the image and work on the upgrade to a newer release. Much appreciated!
