### ISSUE TITLE
Smbk5pwd missing

### ISSUE THREAD

**Issue by jalphad** [bitnami/containers#54483]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create an `smbk5pwd.ldif` with the following content:
```
dn: cn=module,cn=config
cn: module
objectClass: olcModuleList
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: smbk5pwd.so

dn: olcOverlay=smbk5pwd,olcDatabase={2}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcSmbK5PwdConfig
olcOverlay: smbk5pwd
olcSmbK5PwdEnable: samba
olcSmbK5PwdMustChange: 0
```
2. Place in some local ldifs folder and mount that in `/ldifs` when starting the container

### What is the expected behavior?

Honestly, seeing as there is no `/opt/bitnami/openldap/lib/openldap/smbk5pwd.so` in the container the failure to load this module is expected but the file not being there is unexpected given the comment from @aoterolorenzo mentioned in the additional information. The file also does not exist in `/opt/bitnami/openldap/libexec/openldap`.

### What do you see instead?

The `smbk5pwd.so` file is nowhere to be found in the container and the message `lt_dlopenext failed: (smbk5pwd.so) file not found` is logged to the console when trying to load the above ldif.

### Additional information

Per _@aoterolorenzo in https://github.com/bitnami/containers/issues/37521#issuecomment-1667862887_ the `smbk5pwd` module should be available in the Bitnami OpenLDAP image

**Comment by vincentDcmps** [comment]
Same issue, maybe something wrong or missing in ldif file

**Comment by aoterolorenzo** [comment]
Hi @jalphad @vincentDcmps,

I just ensured the module is already being compiled during the Bitnami's openldap compilation, but in fact seems not being correctly included in the resulting image. I will reopen the task for the team to dig in the issue and work in a fix. We will reach you back here.

**Comment by CrnTeam** [comment]
Hi, I need also smbk5pwd, is there any progress on this issue ?

Thank you

**Comment by aoterolorenzo** [comment]
Hi @CrnTeam,

Unfortunately our team still has not manage to take the task due to workload and prioritization. We will reach you back here once done.

**Comment by sundaramsrini** [comment]
Any update on this, dear people?

**Comment by jotamartos** [comment]
Hi all, 

As you can see in this other post, we updated the compilation recipe and the library is now included in the /opt/bitnami/openldap/libexec/openldap/ folder.

https://github.com/bitnami/containers/issues/68075#issuecomment-2243246727

There is a new revision of the container that is being built and tested. It should be available soon.
