### ISSUE TITLE
[bitnami/redis-cluster] redis-6.2.11-3 binary is missing in downloads section.

### ISSUE THREAD

**Issue by skyckp123** [bitnami/containers#54534]
### Name and Version

bitnami/redis-cluster:6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
curl -SsLf https://downloads.bitnami.com/files/stacksmith/redis-6.2.11-3-linux-amd64-debian-11.tar.gz -O
curl: (22) The requested URL returned error: 404
```
### What is the expected behavior?

Expecting 200 status and file download.

### What do you see instead?

Seeing 404 not found.

**Comment by skyckp123** [comment]
Its working now.. Thanks a lot.

Facing issue with one more link. 
curl -SsLf https://downloads.bitnami.com/files/stacksmith/gosu-1.16.0-5-linux-amd64-debian-11.tar.gz -O
curl: (22) The requested URL returned error: 404

**Comment by carrodher** [comment]
Thanks for confirming.

That new package (gosu-1.6.0-5) should be already available. To help us define our retention policy for those intermediate artifacts, could you please share with us your use case using those old packages instead of the recent versions?

**Comment by skyckp123** [comment]
We have our own base docker image which we want to use instead of using "FROM docker.io/bitnami/minideb:bullseye".

**Comment by skyckp123** [comment]
Could you please help with recovering this URL - 

curl -Sslf https://downloads.bitnami.com/files/stacksmith/redis-exporter-1.49.0-0-linux-amd64-debian-11.tar.gz -O
curl: (22) The requested URL returned error: 404

**Comment by carrodher** [comment]
> Could you please help with recovering this URL -
> 
> ```
> curl -Sslf https://downloads.bitnami.com/files/stacksmith/redis-exporter-1.49.0-0-linux-amd64-debian-11.tar.gz -O
> curl: (22) The requested URL returned error: 404
> ```

Files restored
