### ISSUE TITLE
[bitnami/jenkins] Provide jenkins based on mindeb bookworm

### ISSUE THREAD

**Issue by baedorf** [bitnami/containers#54567]
### Name and Version

 bitnami/jenkins:latest

### What is the problem this feature will solve?

Inside the docker container, a maven build using hosts as DOCKER_HOST is performed:

```
docker: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by docker)
```

The host system is based on Debian bookworm. The GLIBC seems not to be compatable.

Update glibc to be compatible with a Debian bookworm host

### What is the feature you are proposing to solve the problem?

Provide an image based on minideb bookworm

### What alternatives have you considered?

1. I'm no linux expert so I don't know if it is possible to update to a compatable version with
`RUN install_packages XXXX` in a custom Dockerfile
2. make from variable using an ARG parameter like 
```
ARG MINIDEB_IMAGE=docker.io/bitnami/minideb:bullseye
FROM $MINIDEB_IMAGE
```

**Comment by javsalgar** [comment]
Hi,

We have plans to move to the new version of Debian, but I cannot guarantee an exact ETA. As soon as there are news, we will notify the community.

**Comment by carrodher** [comment]
Hi, Jenkins based on Debian 12 is already available, see https://github.com/bitnami/containers/pull/62338.
The different tags are already present in [DockerHub](https://hub.docker.com/r/bitnami/jenkins/tags).
