### ISSUE TITLE
[bitnami/milvus] Upgrade to milvus 2.3.4

### ISSUE THREAD

**Issue by Uijeong97** [bitnami/containers#54577]
### Name and Version

bitnami/milvus:2.3.4

### What is the problem this feature will solve?

milvus 2.3.4 is released (https://github.com/milvus-io/milvus/releases/tag/v2.3.4), would it be possible to upgrade bitnami image ?

### What is the feature you are proposing to solve the problem?

Just be in sync with upstream releases :)

### What alternatives have you considered?

No response

**Comment by javsalgar** [comment]
Hi,

It seems that this version requires manual intervention from the team. We are currently working on it.

**Comment by Uijeong97** [comment]
@javsalgar 

Thank you for answer.
I'll take care of this issue quickly.

**Comment by SametOzenc** [comment]
We're really looking forward to the release of the new version :)

**Comment by carrodher** [comment]
We're finding some technical issues with those new versions, the team is working on it and this GH issue will be updated once the new version is released on our side. Thanks

**Comment by rafariossaa** [comment]
We have just released v2.3.7, could you give it a try ?
