### ISSUE TITLE
[bitnami/sonarqube] Add ability to configure proxy settings for sonar.properties

### ISSUE THREAD

**Issue by Natgho** [bitnami/containers#54720]
### Name and Version

bitnami/sonarqube:latest

### What is the problem this feature will solve?

Reference issue: https://github.com/bitnami/containers/issues/1036
Currently one hast to mount the conf file and edit it manually. Since other options of this file can already be configured, this would make life easier.

### What is the feature you are proposing to solve the problem?

Add environment variables and do replacements accordingly.

The sonar.properties currently includes the following proxy settings:

```
# HTTP proxy (default none)
#http.proxyHost=
#http.proxyPort=
# HTTPS proxy (defaults are values of http.proxyHost and http.proxyPort)
#https.proxyHost=
#https.proxyPort=

# NT domain name if NTLM proxy is used
#http.auth.ntlm.domain=

# SOCKS proxy (default none)
#socksProxyHost=
#socksProxyPort=

# Proxy authentication (used for HTTP, HTTPS and SOCKS proxies)
#http.proxyUser=
#http.proxyPassword=

# Proxy exceptions: list of hosts that can be accessed without going through the proxy
#                   separated by the '|' character, wildcard character '*' can be used for pattern matching
#                   used for HTTP and HTTPS (default none)
#                   (note: localhost and its literal notations (127.0.0.1, ...) are always excluded)
http.nonProxyHosts=
```

**Comment by adrianmusante** [comment]
I don't know if all the properties can be set from JAVA_OPTS but I used the proxy properties and this works for me. For example:

```
SONARQUBE_CE_JAVA_ADD_OPTS=-Dhttp.proxyHost=my-proxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=my-proxy -Dhttps.proxyPort=3128 -Djava.net.useSystemProxies=true -Dhttp.nonProxyHosts=localhost|127.*|[::1]|sonarqube|sonarqube_db
SONARQUBE_WEB_JAVA_ADD_OPTS=-Dhttp.proxyHost=my-proxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=my-proxy -Dhttps.proxyPort=3128 -Djava.net.useSystemProxies=true -Dhttp.nonProxyHosts=localhost|127.*|[::1]|sonarqube|sonarqube_db
HTTP_PROXY=http://my-proxy:3128
HTTPS_PROXY=http://my-proxy:3128
NO_PROXY=localhost,127.0.0.1,sonarqube,sonarqube_db
```
> **Note:** The variables `HTTP_PROXY`,`HTTPS_PROXY` and `NO_PROXY` are optionals for your case.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the engineering team, but as this is not a critical feature we cannot guarantee an ETA. However, if you want to speed up the process, would you like to submit a PR?
