### ISSUE TITLE
[bitnami/openldap] Execute custom LDIF files with privileged user for config DB

### ISSUE THREAD

**Issue by guillelb** [bitnami/containers#54741]
### What is the problem this feature will solve?

The bootstrap function [ldap_add_custom_ldifs()](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.5/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L576C1-L576C24) executes **ldapadd** with the **LDAP_ADMIN_DN** user, this user only can modify the admin user tree but not the **config** DB with the command:
`ldapadd -f {} -H 'ldapi:///' -D \"$LDAP_ADMIN_DN\" -w \"$LDAP_ADMIN_PASSWORD\""`.
Because of this, you cannot automate, for example, the creation of **syncrepl** config at bootstrap:

```
dn: cn=config
changetype: modify
add: olcServerID
olcServerID: 0 ldap://ldap-0.local
olcServerID: 1 ldap://ldap-1.local

dn: olcOverlay=syncprov,olcDatabase={0}config,cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcSyncProvConfig
olcOverlay: syncprov
.
.
.
```

If you insert these LDIF files in **LDAP_CUSTOM_LDIF_DIR** path, you get permission error:
`ldap_modify: Insufficient access (50)`

It would be very easy to include the possibility to run your custom LDIF files with privileges just like you do for other internal configurations like TLS certificate loading or [module load](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.5/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh#L777), among others, with the privileged command **-Y EXTERNAL**:
`ldapadd -Y EXTERNAL -H "ldapi:///" -f "...ldif"`

_Is there currently a way to do this without modifying the code?_

### What is the feature you are proposing to solve the problem?

Include the possibility to import your custom LDIF files for the **config** DB.

### What alternatives have you considered?

Execute the function **ldap_add_custom_ldifs()** with privilege:
`-Y EXTERNAL`

Or create a new function **ldap_add_custom_config_ldifs()** to execute custom LDIF files for **config** DB.
```bash
ldap_add_custom_config_ldifs() {
    info "Loading custom config LDIF files..."
    find "$LDAP_CUSTOM_CONFIG_LDIF_DIR" -maxdepth 1 \( -type f -o -type l \) -iname '*.ldif' -print0 | sort -z | xargs --null -I{} bash -c ". /opt/bitnami/scripts/libos.sh && debug_execute ldapadd -Q -Y EXTERNAL -f {} -H 'ldapi:///'
}
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input! Right now, you can run your custom init scripts to complete the initialization. Would that work for your use case? 

https://github.com/bitnami/containers/tree/main/bitnami/openldap#initializing-a-new-instance

**Comment by zerowebcorp** [comment]
Would this mean we can execute custom ldif to setup master-master replication? 
Would it create the initial tree in this case or is that something we should do part of the custom setup?

**Comment by zerowebcorp** [comment]
> Hi,
> 
> Thank you so much for the input! Right now, you can run your custom init scripts to complete the initialization. Would that work for your use case?
> 
> https://github.com/bitnami/containers/tree/main/bitnami/openldap#initializing-a-new-instance

I just tried this. It won't work for this use case. The scripts are executed before the program starts so it cannot be used to execute replication setup.

**Comment by fmulero** [comment]
Hi @zerowebcorp 

I think [this workaround](https://github.com/bitnami/containers/issues/982#issuecomment-1220354408) could help you. Files under `/opt/bitnami/openldap/etc/schema/` and configured as `LDAP_EXTRA_SCHEMAS` are loaded with `ldapadd -Y EXTERNAL -H "ldapi:///" -f` during initialization phase. Could you give it a try?
