### ISSUE TITLE
[bitnami/minio] "Unable to configure server grid RPC services: grid: local host not found" error appears when deploying distributed MinIO on a Docker Swarm cluster.

### ISSUE THREAD

**Issue by thuongvovan** [bitnami/containers#54798]
### Name and Version

bitnami/minio:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enviroment: docker swarm
I have modified the docker-compose.yml file to deploy it to a Docker Swarm cluster with 5 nodes (1 manager and 4 workers).
There are 4 minio services, each with only one replica and running on a single node.
The master node also serves as a load balancer.

2. Configure
This is docker-compose.yml file that I used:
[docker-compose.txt](https://github.com/bitnami/containers/files/13947726/docker-compose.txt)
And I used the docker stack deploy command to deploy it.

3. Error
Distributed MinIO cannot be initialized with the following error:
```
API: SYSTEM()
Time: 09:07:48 UTC 01/16/2024

Error: WARNING: Expected number of all hosts (4) to be remote +1 (4) (*errors.errorString)
7: internal/logger/logger.go:259:logger.LogIf()
6: cmd/peer-rest-client.go:812:cmd.newPeerRestClients()
5: cmd/notification.go:1122:cmd.NewNotificationSys()
4: cmd/server-main.go:376:cmd.initAllSubsystems()
3: cmd/server-main.go:690:cmd.serverMain.func4()
2: cmd/server-main.go:489:cmd.bootstrapTrace()
1: cmd/server-main.go:689:cmd.serverMain()
ERROR Unable to configure server grid RPC services: grid: local host not found
```

### What is the expected behavior?

I think that this deployment is similar to the deployment on a single node (docker compose up), so it should be able to initialize a distributed minio on a docker swarm cluster.

### What do you see instead?

But, it cannot initialize a distributed minio and the error appears as described above.

![CleanShot 2024-01-16 at 16 19 48@2x](https://github.com/bitnami/containers/assets/54501918/beeff076-7756-4bc8-9f14-c917a7bf2c90)

**Comment by javsalgar** [comment]
Hi,

Does this error happen when using docker-compose instead of docker swarm?

**Comment by thuongvovan** [comment]
Hi,

I'm very happy to receive such early support.

This error only occurs when using Docker Swarm, everything with Docker Compose still works fine however if Docker Compose then it's not really a distributed Minio.

Can you please help me to investigate this issue?

Thanks,
Thuong Vo

On 16 Jan 2024, at 16:31, Javier J. Salmerón-García ***@***.***> wrote:



Hi,

Does this error happen when using docker-compose instead of docker swarm?

**Comment by jimrobinson** [comment]
The source of the issue is that the [github.com/minio/minio/internal/grid/manager.go](https://github.com/minio/minio/blob/dd2542e96c826e404d89a9c4eeb5b4f2ce44286b/internal/grid/manager.go#L98-L119) assumes each container hostname will resolve to one of the hostnames it expands from the pattern specified for the `server <protocol>://<hostname>/<path>` argument passed to minio.

To correct this use the docker service `--hostname <hostname>` option on each minio service you start, so that each container has an internal hostname matching one of the hostnames that minio expects given the `server <protocol>://<hostname>/<path>` pattern.

**Comment by thuongvovan** [comment]
Hi,

Thank you for your advice!

I added the hostname parameter for each Minio service. As a result, the error "ERROR Unable to configure server grid RPC services: grid: local host not found" no longer appeared and the Minio services were able to start.

However, another error appeared. The connection between the nodes is still unstable and the state of each node is completely different.

Perhaps I should switch to deploying it on Kubernetes.

**Comment by jimrobinson** [comment]
You haven't shared your docker-compose.yml so I can only offer a guess for the latest issue: MinIO was programmed with the assumption that there will be a one to one mapping of a given hostname to a drive once it has been initialized, and that the drives are mounted in the same order per host.

For my testing I pin a given container name (e.g., minio-container-1) to a given host (e.g., vm-host-1) and I ensure the same disks are always assigned in the same order.

**Comment by thuongvovan** [comment]
[docker-compose.txt](https://github.com/bitnami/containers/files/13984166/docker-compose.txt)

I would like to share the docker-compose.yml file that I used to deploy. Although the disk is ready, there is still one machine that has a problem with the disk.

Perhaps I should really switch to k8s, a platform that has been officially tested by the developers and is recommended for use in production.

**Comment by jimrobinson** [comment]
Switching to a supported deployment platform is certainly a solid choice, it'll make things easier if anything else goes wrong in the future.

Am I understanding your latest comment correctly if I think you are saying 3 of the nodes are up but the 4th is failing?  If that's correct I'd be curious what would happen if you wiped the .minio.sys and data from the failing volume, to see if minio can heal the one disk.

**Comment by thuongvovan** [comment]
I really appreciate your great support.

But unfortunately, I have already deleted the VPSs running the Docker Swarm cluster.

Deploying on Docker Swarm is unstable, there is no support from developers and the community is very small, so I decided not to continue deploying my product on this platform, instead deploying with k8s.

Thank you again!!
