### ISSUE TITLE
Have bitnami images be supported for podman

### ISSUE THREAD

**Issue by trymeouteh** [bitnami/containers#54825]
### Name and Version

Bitnami/all

### What is the problem this feature will solve?

No documentation on getting images to work in podman

### What is the feature you are proposing to solve the problem?

For images that do not work, please add additional documentation on how to get them images to work in podman.

**Comment by carrodher** [comment]
It's not something supported out of the box in the sense that our automated test and release pipeline is not using Podman to ensure the container images work using this tool. Having said that, the container images should be agnostic to this technology so not sure if the issue you're facing is related to Podman or any other situation.

Could you please provide more info about the specific issues you're facing?
