### ISSUE TITLE
Unable to change Python version in bitnami/pytorch

### ISSUE THREAD

**Issue by alejopaullier96** [bitnami/containers#54841]
### Name and Version

bitnami/pytorch:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I am building a Docker container based on `bitnami/pytorch:latest`. The Python version it executes is `3.11` which has a conflict with a `gunicorn` library I also use inside my container. I tried changing the Python version using this command:
```dockerfile
FROM bitnami/pytorch:2.1.1

# These command is set because python3-opencv prompts the user a couple questions which can be ignored.
ENV DEBIAN_FRONTEND=noninteractive

USER root
# Install htop, Python3, wget
RUN apt update \
    && apt install -y htop python3.9-dev wget \
    && apt install -y python3-opencv \
    && apt install -y nginx \
    && apt install -y git

# Create symbolic links
RUN ln -s /usr/bin/python3.9 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
```

However, when the Docker container is run it still uses Python `3.11` despite stating in the `Dockerfile` to use `3.9`. Is it because the symbolic link is pointing to a wrong path?

### What is the expected behavior?

Container should use `3.9` instead of `3.11`

### What do you see instead?

I see the container using `3.11`

**Comment by jotamartos** [comment]
Hi @alejopaullier96,

We do not use system packages to install the different components. As you can see in the [Pytorch's Dockerfile](https://github.com/bitnami/containers/blob/main/bitnami/pytorch/2/debian-11/Dockerfile#L29), it downloads a Python package with the version to install. You can change it with [the version Python 3.9 uses](https://github.com/bitnami/containers/blob/main/bitnami/python/3.9/debian-11/Dockerfile#L28) and rebuild the container.
