### ISSUE TITLE
[bitnami/kafka] Why not use JRE to reduce image size

### ISSUE THREAD

**Issue by liuruibin** [bitnami/containers#54869]
### Name and Version

bitnami/kafka:3.6.1

### What is the problem this feature will solve?

https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.6/debian-11/Dockerfile

### What is the feature you are proposing to solve the problem?

Install JRE instead of JDK

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input! I will forward this to the team, but if I recall correctly Oracle discontinued JRE and only provides JDK, for example.
