### ISSUE TITLE
[bitnami/pgbouncer] Release 1.21.0-debian-11-r8 crashes after start with: invalid value "**0**" for parameter server_fast_close in configuration

### ISSUE THREAD

**Issue by takicichy** [bitnami/containers#54877]
### Name and Version

bitnami/pgbouncer:1.21.0-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Start pgbouncer container with not configured environment variable `PGBOUNCER_SERVER_FAST_CLOSE`.

### What is the expected behavior?

Use the default value of plain 0 in pgbouncer configuration for server_fast_close.

### What do you see instead?
```
ERROR invalid value "**0**" for parameter server_fast_close in configuration (/opt/bitnami/pgbouncer/conf/pgbouncer.ini:20)
FATAL cannot load config file
```

**Comment by bnmnetp** [comment]
For those of you ending up here,  using the image from dockerhub with docker or in a docker-compose'd app.  The quick fix is to set the `PGBOUNCER_SERVER_FAST_CLOSE` in your `docker-compose.yml` file or your docker environment.
