### ISSUE TITLE
[bitnami/prometheus] Unable to set tolerations for the daemon set

### ISSUE THREAD

**Issue by edvinas31** [bitnami/containers#54876]
### Name and Version

bitnami/prometheus:2.44.0-debian-11-r2

### What architecture are you using?

None

### What steps will reproduce the bug?

1) Kubernetes 1.27
2) Change the toleration for daemonset

### What is the expected behavior?

toleration is set through values.yaml file

### What do you see instead?

Impossible to set toleration using values.yaml file

**Comment by javsalgar** [comment]
Hi!

Could you confirm that you are using the bitnami/prometheus chart? I don't see a DaemonSet declaration there

**Comment by edvinas31** [comment]
Hi, thank you for the answer. We found out that kube-prometheus chart has a subchart called node-exporter. So we solved the issue by setting following block in values-dev.yaml file:

node-exporter:
  tolerations:
  - key: "onlyES"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
