### ISSUE TITLE
Invalid default value for PGBOUNCER_SERVER_FAST_CLOSE being set

### ISSUE THREAD

**Issue by mydimension** [bitnami/containers#54879]
### Name and Version

bitnami/pgbouncer:1.21.0-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. run container without specifying an value for `PGBOUNCER_SERVER_FAST_CLOSE`

### What is the expected behavior?

container runs without startup error or config parse errors

### What do you see instead?

```
pgbouncer 15:00:39.00 INFO  ==> ** Starting PgBouncer **
2024-01-18 15:00:39.002 UTC [9] ERROR invalid value "**0**" for parameter server_fast_close in configuration (/opt/bitnami/pgbouncer/conf/pgbouncer.ini:20)
2024-01-18 15:00:39.003 UTC [9] FATAL cannot load config file
```

### Additional information

issue introduced in https://github.com/bitnami/containers/blame/36d48e6c5f6c494da83bd1242fe1964cced3c4f8/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/pgbouncer-env.sh#L130

**Comment by mohammad-matini** [comment]
Confirmed, we're hitting this in our cluster.  A workaround is to define the environment variable `PGBOUNCER_SERVER_FAST_CLOSE` to `0` (which is the default value).

**Comment by carrodher** [comment]
Thanks! It was already reported at https://github.com/bitnami/containers/issues/54877, let's continue the conversations there to unify the support.
