### ISSUE TITLE
[bitnami/openldap] Failure to apply custom LDIFs when LDAP_REQUIRE_TLS=yes

### ISSUE THREAD

**Issue by guillelb** [bitnami/containers#54880]
### Name and Version

bitnami/openldap:2.5.16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Put LDIF files in a volume and set the variable LDAP_CUSTOM_LDIF_DIR.
2. Set variables LDAP_ENABLE_TLS=yes and LDAP_REQUIRE_TLS=yes.
3. Launch the container

### What is the expected behavior?

Apply the initial  LDAP_ROOT directory and the LDIF files without problems.

### What do you see instead?

The container fails and stop, and it has not apply the custom LDIF files.
It shows the log:
```
15:21:34.98 INFO  ==> Loading custom LDIF files...
conn=1008 op=0 RESULT tag=97 err=13 qtime=0.000010 etime=0.000114 text=TLS confidentiality required
ldap_bind: Confidentiality required (13)
	additional info: TLS confidentiality required
```

### Additional information

It seems that is not creating the LDAP_ROOT directory.

**Comment by rafariossaa** [comment]
When you enabled `LDAP_ENABLE_TLS` were you also setting `LDAP_TLS_xxxx_FILE` env vars ? 
(I mean properly configuring the TLS with all the needed cert files)

**Comment by guillelb** [comment]
Of course, everything configured to work with TLS.
It actually works fine, but when you activate `LDAP_REQUIRE_TLS=yes`, that's when we have the problem.

**Comment by rafariossaa** [comment]
Hi, I was able to reproduce the issue and we are working to produce a fix for it.

**Comment by rafariossaa** [comment]
Hi, 
  I made a new release fixing this, could you give `2.6.6-debian-11-r64` or `2.5.16-debian-11-r63` a try ?

**Comment by rafariossaa** [comment]
I am closing this issue. 
Please feel free to reopen it if needed.
