### ISSUE TITLE
[bitnami/laravel] Documentation for Bitnami/Laravel image have the wrong url for the image.

### ISSUE THREAD

**Issue by WassimYazbekk** [bitnami/containers#54886]
### Name and Version

bitnami/laravel

### What architecture are you using?

None

### What steps will reproduce the bug?

1. mkdir ~/myapp && cd ~/myapp
2. curl -LO https://raw.githubusercontent.com/bitnami/containers/main/bitnami/laravel/docker-compose.yml
3. docker-compose up
docker-compose.yml will be empty with 404 error

### What is the expected behavior?

get the docker-compose.yml file

### What do you see instead?

404 Error

### Additional information

I went to github and copied the file. I think this happened because of the addition of a new debian version file. an easy fast fix is to add a default docker-compose.yml to the root of bitnami/containers/laravel/

**Comment by javsalgar** [comment]
Hi!

We recently removed the docker-compose files. We will update the README.md file. Thank you so much for reporting!

**Comment by carrodher** [comment]
Those references to docker-compose were already removed and a note was added to the notable changes section, see https://github.com/bitnami/containers/tree/main/bitnami/laravel#starting-january-16-2024

**Comment by neoacevedo** [comment]
2024 and the README isn't yet updated: https://github.com/bitnami/containers?tab=readme-ov-file#run-the-application-using-docker-compose
