### ISSUE TITLE
Setting `REDIS_IO_THREADS_DO_READS=true` crashes the Redis Container

### ISSUE THREAD

**Issue by Jarmos-san** [bitnami/containers#54907]
### Name and Version

bitnami/redis:7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I ran the following the commands where I stumbled upon the error:

```sh
docker run --name redis --rm \
        -p 6379:6379 \
        -e REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG \
        -e REDIS_PASSWORD=admin \
        -e REDIS_IO_THREADS=4 \
        bitnami/redis:7.2
```

But a more minimal reproducible command would be:

```sh
docker run --rm \
        -e ALLOW_EMPTY_PASSWORD=yes \
        -e REDIS_IO_THREADS_DO_READS=true \
        bitnami/redis:7.2
```

### What is the expected behavior?

Redis should run normally with multithreading options enabled.

### What do you see instead?

The following error message before Redis crashes:

```console
redis 09:09:03.62 INFO  ==>
redis 09:09:03.62 INFO  ==> Welcome to the Bitnami redis container
redis 09:09:03.62 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis 09:09:03.63 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 09:09:03.63 INFO  ==>
redis 09:09:03.63 INFO  ==> ** Starting Redis setup **
redis 09:09:03.64 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 09:09:03.64 INFO  ==> Initializing Redis
redis 09:09:03.66 INFO  ==> Setting Redis config file
redis 09:09:03.76 INFO  ==> ** Redis setup finished! **

redis 09:09:03.78 INFO  ==> ** Starting Redis **

*** FATAL CONFIG FILE ERROR (Redis 7.2.4) ***
Reading the configuration file, at line 1310
>>> 'io-threads-do-reads true'
argument must be 'yes' or 'no'
```

### Additional information

I basically followed the instructions laid down in the ["multithreading"](https://github.com/bitnami/containers/blob/main/bitnami/redis/README.md#enablingsetting-multithreading) section of the docs word-to-word. And I noticed Redis works perfectly fine if set the environment values to `REDIS_IO_THREADS_DO_READS=yes` instead of `REDIS_IO_THREADS_DO_READS=true`.

Here is an example command which is working for me:

```sh
docker run --name redis --rm \
        -p 6379:6379 \
        -e REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG \
        -e REDIS_PASSWORD=admin \
        -e REDIS_IO_THREADS=4 \
        # -e REDIS_IO_THREADS_DO_READS=true \  # Won't work!
        -e REDIS_IO_THREADS_DO_READS=yes \
        bitnami/redis:7.2
```

**Comment by dgomezleon** [comment]
Hi @Jarmos-san,

We have applied a fix for that typo that should be released in the next few minutes. Thanks for reporting

**Comment by Jarmos-san** [comment]
@dgomezleon thanks for the heads up and it appears the documentation is updated so I am going to close this issue.
