### ISSUE TITLE
[bitnami/jasperreports] JasperReports - Set Psotgresql Schema

### ISSUE THREAD

**Issue by stefan-gut** [bitnami/containers#55270]
### Name and Version

bitnami/jasperreports:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

We use Postgresql as our database. Is there a way to set the database schema e.g. as an environment variable?

### What do you see instead?

Database Schema cant be set over the env variable

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Could you let us know which JasperReports setting we would need to change to set the schema?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input. I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding the support for this variable and we will review it.

**Comment by stefan-gut** [comment]
Hi Javier,

Thank you very much for your quick reply.
There is no hurry ;) But will this feature request be implemented? If not, then we would make the change ourselves if necessary

**Comment by javsalgar** [comment]
Hi again,

This would need to be evaluated depending on priorities. I'm afraid that's beyond my grasp :(

**Comment by mdhont** [comment]
Hi @stefan-gut,

Just notifying you that JasperReports has been deprecated from our catalog as it is no longer maintained upstream.
