### ISSUE TITLE
[bitnami/airflow] worker image extending doesn't work

### ISSUE THREAD

**Issue by vincentzhou2013** [bitnami/containers#55281]
### Name and Version

airflow-worker:2.8.0-debian-11-r1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Is there a easy to extend the worker images?
issue:
1. dependency is big, don't want to install every time workflow runs.
2.  some dependency, like oracle database client, need copy file, set environment variables, cannot be implemented use volumeMount
Below custom worker image doesn't work. when dag runs, it cannot find the installed dependencies.
`FROM repo.corp.cox.com/docker/bitnami/airflow-worker:2.8.0-debian-11-r1
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt`

### What is the expected behavior?

dag able to use the dependencies installed 

### What do you see instead?

dag cannot see  the dependencies installed

**Comment by Mauraza** [comment]
Hi @vincentzhou2013,

Could you share the error? I tried with:
```yaml
FROM docker.io/bitnami/airflow-worker:2.8.0-debian-11-r1 
COPY requirements.txt /requirements.txt 
RUN pip3 install -r /requirements.txt
```
and works perfectly.

**Comment by vincentzhou2013** [comment]
Thanks you for the quick response. it's caused by the python version. (the worker has only one version python 3.11, but  the dependencies file is for python 3.6)
I switched to airflow community helm and solved this issue.
