### ISSUE TITLE
[bitnami/kafka] Last update to bitnami/kafka:3.6-debian-11 not working - Invalid value for configuration message.max.bytes

### ISSUE THREAD

**Issue by fracasula** [bitnami/containers#55307]
### Name and Version

bitnami/kafka:3.6-debian-11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm bringing up the container programmatically in an integration test written in Go.

I'm **NOT** passing a configuration setting for `message.max.bytes`.

These are the only environment variables that I'm passing:

```
KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
ALLOW_PLAINTEXT_LISTENER=yes
BOOTSTRAP_SERVERS=kafka1:9090,kafka2:9090,kafka3:9090
KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
```

If I downgrade to [3.6.1-debian-11-r1](https://hub.docker.com/layers/bitnami/kafka/3.6.1-debian-11-r1/images/sha256-7871418aae69e6c7ac87de387af207eb198ea5bac5deda2e93b6c7473bfa8a6a?context=explore) it works.

### What do you see instead?

```
kafka 08:47:32.27 INFO  ==> 
kafka 08:47:32.27 INFO  ==> Welcome to the Bitnami kafka container
kafka 08:47:32.27 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 08:47:32.27 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 08:47:32.27 INFO  ==> 
kafka 08:47:32.27 INFO  ==> ** Starting Kafka setup **
kafka 08:47:32.32 WARN  ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure SASL and/or SSL, this setting is not recommended for production environments.
kafka 08:47:32.33 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.
kafka 08:47:32.34 INFO  ==> Initializing Kafka...
kafka 08:47:32.34 INFO  ==> No injected configuration files found, creating default config files
kafka 08:47:32.44 INFO  ==> ** Kafka setup finished! **

kafka 08:47:32.45 INFO  ==> ** Starting Kafka **
[2024-01-23 08:47:32,823] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2024-01-23 08:47:32,959] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:745)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:493)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:486)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:145)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1601)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1604)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1527)
	at kafka.Kafka$.buildServer(Kafka.scala:72)
	at kafka.Kafka$.main(Kafka.scala:91)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by ipreina** [comment]
The same issue for me, also with 3.3 and 3.4, but 3.6.1-debian-11-r1 works fine for me.
     ` - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT`

**Comment by louisth** [comment]
https://github.com/bitnami/containers/pull/55248/files
The change to bitnami/kafka/3.6/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh added KAFKA_CFG_MAX_REQUEST_SIZE, KAFKA_CFG_MESSAGE_MAX_BYTES, KAFKA_CFG_MAX_PARTITION_FETCH_BYTES to a list which now sets them to then empty string (which is not a valid value) rather than leaving them unset.

**Comment by sudhindra-xage** [comment]
This issue is also there in latest kafka image 3.5

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by fevisera** [comment]
The latest versions containing the implemented fix have been released as part of the PR https://github.com/bitnami/containers/pull/55276. Also mentioned in https://github.com/bitnami/charts/issues/22552#issuecomment-1909854232.

Thank you for reporting the issue. Since it has already been addressed, we are closing it.
