### ISSUE TITLE
Issue with Kafka container: Invalid value for configuration message.max.bytes

### ISSUE THREAD

**Issue by samarthasthan** [bitnami/containers#55340]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Build and run a Docker image using the provided Dockerfile.
2. Observe the container logs for any errors or warnings.

### What is the expected behavior?

The Kafka container should start without any errors, and the specified configurations in the Dockerfile should be applied successfully.

### What do you see instead?

The Kafka container fails to start, and the following error is observed in the logs:
`Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value for configuration message.max.bytes: Not a number of type INT
`

### Additional information

Dockerfile:

`FROM bitnami/kafka:latest

WORKDIR /opt/bitnami/kafka/bin

USER root

RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get -y install build-essential libssl-dev libffi-dev libblas3 libc6 liblapack3 gcc
RUN apt install -y netcat

ENV KAFKA_ENABLE_KRAFT=yes
ENV ALLOW_PLAINTEXT_LISTENER=yes

# Node-specific configurations
ENV KAFKA_CFG_NODE_ID=1
ENV KAFKA_CFG_PROCESS_ROLES=broker,controller

# Listener configurations
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
ENV KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:9092,CONTROLLER://:9093
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
ENV KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:29092,EXTERNAL://localhost:9092

# Controller quorum voters
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093

COPY --chmod=755 kafka_setup.sh ./
COPY --chmod=755 wait-for.sh ./
`

**Comment by jotamartos** [comment]
Hi @samarthasthan,

This issue was reported [here](https://github.com/bitnami/containers/pull/55276) and a new version of Kafka was just released with the fix. Could you please try using the latest tag? 

Thanks

**Comment by samarthasthan** [comment]
Ya its working fine, between i was using latest version 🙂

Thank you!
