### ISSUE TITLE
[bitnami/phpmyadmin] PHPMYADMIN_URL_PREFIX has no effect

### ISSUE THREAD

**Issue by FlorentPoinsaut** [bitnami/containers#55367]
### Name and Version

bitnami/phpmyadmin:5.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set a value to the PHPMYADMIN_URL_PREFIX env var
2. Call phpMyAdmin with the sub path 

### What is the expected behavior?

phpMyAdmin must reply the homepage on the sub path store in the PHPMYADMIN_URL_PREFIX env var

### What do you see instead?

phpMyAdmin reply a 404 Not Found.

### Additional information

The function [phpmyadmin_ensure_web_server_prefix_configuration_exists](https://github.com/bitnami/containers/blob/main/bitnami/phpmyadmin/5/debian-11/rootfs/opt/bitnami/scripts/libphpmyadmin.sh#L195) is never called

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
