### ISSUE TITLE
There is a problem with the readme description of the redis-cluster project

### ISSUE THREAD

**Issue by huangjc7** [bitnami/containers#55903]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello, in the redis-cluster image, the REDIS_RDB_POLICY_DISABLED parameter was provided by me through pr, and the readme file was also written by me. However, I recently received feedback from a friend that the RDB function does not take effect when enabled. Then I read the readme file, and it only wrote the default values, not how to enable it. The format for turning on REDIS_RDB_POLICY_DISABLED is quite special. It doesn’t need to be yes or no. Is it necessary to explain it separately?

### What do you see instead?

Here is the description of the REDIS_RDB_POLICY_DISABLED parameter in the readme file of the previous version
| `REDIS_RDB_POLICY`                      | Set this variable to enable RDB persistent storage RDB data synchronization strategy configuration example `900#1 300#10 60#1000` Defaults to disable RDB persistent storage. |

**Comment by carrodher** [comment]
Thanks for the information. The format of the table was modified so it's automatically populated, if there are special considerations around that specific environment variable, probably we should add a separate paragraph outside of the table. Would you like to contribute by creating a PR?

**Comment by huangjc7** [comment]
ok

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
