### ISSUE TITLE
[bitnami/cassandra] Customize Dockerfile for the old Cassandra 3.X version

### ISSUE THREAD

**Issue by dpavlov-smartling** [bitnami/containers#56343]
### Name and Version

bitnami/cassandra

### What is the problem this feature will solve?

This is more question about getting access to source code of Cassandra 3.X docker images. I can see 3.X Docker tags on the Docker hub - like [here](https://hub.docker.com/layers/bitnami/cassandra/3.11.2/images/sha256-12b4c3728417e6c62999f0ae70f29fa658ffd92397d706731c12ad836a4b87b5?context=explore), but we definitely will need to customize that image according to our needs.
I didn't find any branches or tags/releases related to Cassandra 3.X in the repo. Is the only way to find the source code  to search for a related commit like [this one](https://github.com/bitnami/containers/commit/3e51d90e40e7e08a8335e18fbff3b07563cb13fd) ?

Thanks,

### What is the feature you are proposing to solve the problem?

question

**Comment by javsalgar** [comment]
Hi!

I'm afraid that, the only way to look for the branch you're looking for is to go through the bitnami/cassandra folder history.

```
git log --oneline  . | grep "3."
```
