### ISSUE TITLE
[bitnami/redis] Support SSL certificates from a public CA by making reading ca-certificates from os configurable

### ISSUE THREAD

**Issue by nebed** [bitnami/containers#56361]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

redis supports these configurations for CA certificates in redis.conf
```
# tls-ca-cert-file ca.crt
# tls-ca-cert-dir /etc/ssl/certs
```
currently there is an environment variable for `tls-ca-cert-file` (REDIS_TLS_CA_FILE) but not `tls-ca-cert-dir`
https://redis.io/docs/management/config-file/
if `tls-ca-cert-dir` can be set as an environment variable, it can be pointed to the OS directory that holds ca-certificates
eg  -` /usr/share/ca-certificates/mozilla/`
and public certificates like letsencrypt can be used for redis when `tls-auth-clients no`

### What is the feature you are proposing to solve the problem?

add a new environment variable REDIS_TLS_CA_DIR that is the equivalent of `tls-ca-cert-dir` in redis.conf

### What alternatives have you considered?

It is possible to supply a custom config to redis and set this directly in redis.conf

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward it to the engineering team, but as it is not a critical feature, we cannot guarantee an ETA. However, if you want to speed up the process, you could submit a PR adding the env var functionality

**Comment by nebed** [comment]
Hey @javsalgar  here is a PR - https://github.com/bitnami/containers/pull/56375/files

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
