### ISSUE TITLE
[bitnami/postgresql-repmgr] has wrong custom configuration detection function (postgresql_is_file_external)

### ISSUE THREAD

**Issue by VasilevMaksim** [bitnami/containers#56371]
### Name and Version

bitnami/postgresql-repmgr:15.4.0-debian-11-r36

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Function postgresql_is_file_external(): https://github.com/bitnami/containers/blob/f324f50b6d94018ab390ebd320b128fcd860250f/bitnami/postgresql-repmgr/14/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L545
always exit with 0

Reason:
Configuration files copyed  in the repmgr_inject_postgresql_configuration() function: https://github.com/bitnami/containers/blob/f324f50b6d94018ab390ebd320b128fcd860250f/bitnami/postgresql-repmgr/14/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh#L358

### What is the expected behavior?

We need to use repmgr_is_file_external() function instead of postgresql_is_file_external(), because our custom configuration for repmgr should be provided in ${REPMGR_MOUNTED_CONF_DIR}

### What do you see instead?

postgresql_is_file_external() check custom configuration in the ${POSTGRESQL_MOUNTED_CONF_DIR}, but this configurations files generated by initial scripts (e.g. repmgr_inject_postgresql_configuration()

**Comment by VasilevMaksim** [comment]
I sugest proposed fix #56371

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
