### ISSUE TITLE
[bitnami/wordpress-nginx] When will come the WordPress latest version 6.4.3 update ?

### ISSUE THREAD

**Issue by CodeExplore** [bitnami/containers#56471]
### Name and Version

bitnami/wordpress-nginx

### What is the problem this feature will solve?

WordPress released a new version 6.4.3 and there is some fixes about **security**.

So, **bitnami/wordpress** is updated, but still we waiting to update for **bitnami/wordpress-ngnix**.

### What is the feature you are proposing to solve the problem?

Just update latest version v6.4.3

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by carrodher** [comment]
The new version was released at https://github.com/bitnami/containers/pull/63737
