### ISSUE TITLE
Unable to restart SuiteCRM if using MariaDB

### ISSUE THREAD

**Issue by RaviRJoshi** [bitnami/containers#56594]
### Name and Version

Bitnami:SuiteCRM

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Use MariaDB:latest in place of Bitnami/MariaDB, and use docker-compose provided by bitnami, making necessary changes to image:   
Start the app. Make some changes in suitecrm app (like adding an account).
Stop the app using docker-compose down.
Start the app again using docker compos. Notice the logs.

### What is the expected behavior?

App should be up and running.

### What do you see instead?

I notice that the mariadb creates third unnamed volume - so in total we have three volumes now. 
Notice the logs with App complaining that it can not connect to database. App exits

### Additional information

However when using bitnami's mariadb version, I don't see a third volume created, so the docker-compose up and down and then up again goes well.
So, is it a must that we need to use bitnami mariadb?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
