### ISSUE TITLE
***MAJOR - nginx container - volume ownership is wrong

### ISSUE THREAD

**Issue by helvetia007** [bitnami/containers#56660]
### Name and Version

bitnami/nginx:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

with podman, with limiteduser1
launch nginx container and mount -v mydata:/mydata
exec in to container. do ls -lah /mydata
shows root:nogroup

### What is the expected behavior?

shoud show owned by 1001:1001 . as inside container it is USER 1001 and nginx is running with 1001
so NO way to write to the mounted volume

### What do you see instead?

shows root:nogroup for the mounted dir

### Additional information

Tried all sorts. Running this on rootless podman. Impossible to mount a directory where user 1001 could write. Impossible mission

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by helvetia007** [comment]
@carrodher I run few other bitnami containers - and they work fine. This one however doesn't. Local files can be owned by 999 or 1001 - when I launch container, it still sees them as user >65K. See below, my data mount. No matter what I own the files with, container sees it like that or similar. Just tried chown -R 999:999 and also with 1001:1001 . And of course full container restart with stop and rm.
65534 65534  X0 Feb  9 08:30 data
