### ISSUE TITLE
[bitnami/minio] Provisioning policies does not recognise "kms:*" and "s3:*"

### ISSUE THREAD

**Issue by Mo0rBy** [bitnami/containers#58175]
### Name and Version

bitnami/minio v2024.2.6-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the MinIO Helm chart and originally posted the issue [here](https://github.com/bitnami/charts/issues/23378).

1. Enabled provisioning within the Helm chart
2. Added 1 policy definition to the provisioning section
3. The `admin:*` within the `actions` section works fine and can correctly provision the policy
4. Both `kms:*` and `s3:*` within the `actions` section do not work and result in errors within the provisioning container.

These actions should be available to use according to the [MinIO access management docs](https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html)

### What is the expected behavior?

I would expect that the policy options defined in the docs are applicable by the MinIO provisioning pod within the Helm chart.

Interestingly, I can still use these policies within the MinIO webapp UI policy editors, but they don't work when they are being applied by the provisioning container.

### What do you see instead?

Instead I get the following errors:

`mc: <ERROR> Unable to create new policy: unsupported admin action 's3:*'.`

`mc: <ERROR> Unable to create new policy: unsupported admin action 'kms:*'.`

Only 1 at a time, depending on which lines I have commented out.

**Comment by Mo0rBy** [comment]
Ah I think the issue is that when you define a wildcard for the policies, you must define them, as separated `Effect`, `Allow`, `Resource` combinations.

So within the MinIO IU, this does NOT work and results in this error at the top of the page: `There was an error creating a Policy: unsupported admin action 'kms:*'. Please check Policy syntax.`
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*",
                "s3:*",
                "kms:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

But the this DOES work (this is the default policy for `consoleAdmin`)
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

Could someone confirm that my logic is correct before closing this issue please? I would like to know if I'm on the right track and why the wildcard policies need to be defined like this. Thanks!

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by Mo0rBy** [comment]
Thanks @carrodher , I will close this issue myself as this was definitely user error by me and therefore it is not a problem with how MinIO operates. I was hoping to get some clarification on why the default `consoleAdmin` role policy is set out the way that it is, but I already understand my mistake.
