### ISSUE TITLE
owncloud arm64v8

### ISSUE THREAD

**Issue by rafalohaki** [bitnami/containers#5857]
### Name and Version

bitnami/owncloud

### What is the problem this feature will solve?

it seems installation fail on arm64

### What is the feature you are proposing to solve the problem?

add arm64 support

### What alternatives have you considered?
using official image which has arm64 support

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by rafalohaki** [comment]
thank you
