### ISSUE TITLE
[bitnami/rabbitmq] not working on ARM arch

### ISSUE THREAD

**Issue by kvokka** [bitnami/containers#5978]
### Name and Version

3.10.7-debian-11-r13

### What steps will reproduce the bug?

```bash
$docker run --platform linux/amd64  -it --rm docker.io/bitnami/rabbitmq:3.10.7-debian-11-r13
# Also tried (same result)
# docker run --rm  docker.io/bitnami/rabbitmq:3.9.22-debian-11-r14
```

### What do you see instead?

```
Digest: sha256:db423d8ea7aa9c076c43a3a6d92cbfa6f771151a0341a3183f49fb990786510b
Status: Downloaded newer image for bitnami/rabbitmq:3.10.7-debian-11-r13
rabbitmq 09:30:04.43
rabbitmq 09:30:04.46 Welcome to the Bitnami rabbitmq container
rabbitmq 09:30:04.49 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 09:30:04.51 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 09:30:04.53
rabbitmq 09:30:04.55 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 09:30:04.70 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 09:30:04.91 INFO  ==> Initializing RabbitMQ...
rabbitmq 09:30:05.11 INFO  ==> Generating random cookie
rabbitmq 09:30:05.36 INFO  ==> Starting RabbitMQ in background...
/opt/bitnami/scripts/libos.sh: line 336:   150 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   248 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   297 Segmentation fault      "$@" > /dev/null 2>&1
```

### Additional information

Using Macbook on M1 chip and the latest Docker Desktop (4.12.0 (85629) is currently the newest version available.)

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by kvokka** [comment]
It's awesome news, thank you for the support and for sharing!
