### ISSUE TITLE
Limit number of components packed

### ISSUE THREAD

**Issue by mulder999** [bitnami/containers#5979]
### Name and Version

bitnami/wordpress:6.0.2

### What is the problem this feature will solve?

The container packs too many useless library which increase vulnerability risk and potential surface attack. It makes the vulnerability analysis auditing more cumbersome (false positive) while also making the image larger than it should.

Some examples of obviously useless components included in the image: git, sqlite3, ...

### What is the feature you are proposing to solve the problem?

Cure the Dockerfile using a minimalistic approach OR shift to a 2 stages approach if those components are required during the build stage only.

**Comment by marcosbc** [comment]
Hi @mulder999, thanks for reporting this. We have removed `git` and `sqlite3` packages from this container image in [[bitnami/wordpress] Release 6.0.2-debian-11-r5](https://github.com/bitnami/containers/commit/d13a62edf0a265ada812285b9892038f74aff581) (#6286).
