### ISSUE TITLE
Improve performance of permission changes

### ISSUE THREAD

**Issue by jfut** [bitnami/containers#5989]
### Name and Version

bitnami/moodle:4.0.3

### What is the problem this feature will solve?

When updating Moodle, the [configure_permissions_ownership](https://github.com/bitnami/containers/blob/7f8887f25baafd4ef28dfad6f905d6ec1545eceb/bitnami/moodle/4/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh#L173-L178) in `prebuildfs/opt/bitnami/scripts/libfs.sh` changes permissions on existing data (moodle/data).

This process takes a lot of time depending on the number of existing data.
For example, it took 1m10s and 6m29 for our Moodle data below. The file system cache is discarded beforehand by `sync && sysctl -w vm.drop_caches=3`.

```bash
root@moodle:/# find -L /bitnami/moodledata -type d | wc -l
68331

root@moodle:/# find -L /bitnami/moodledata -type f | wc -l
411470

root@moodle:/# time find -L /bitnami/moodledata -type d -exec chmod 775 {} \;

real    1m10.496s
user    0m24.789s
sys     0m39.433s

root@moodle:/# time find -L /bitnami/moodledata -type f -exec chmod 664 {} \;

real    6m29.147s
user    2m17.214s
sys     3m52.311s
```

### What is the feature you are proposing to solve the problem?

Using -exec with a semicolon (`find -L /bitnami/moodledata -type d -exec chmod 775 {} \;`), will execute

```bash
chmod 775 /bitnami/moodledata
chmod 775 /bitnami/moodledata/cache
chmod 775 /bitnami/moodledata/cache/cachestore_file
...
```

But if we use a plus sign instead (`find -L /bitnami/moodledata -type d -exec chmod 775 {} +`), will execute as arguments to a single command:

```bash
chmod 775 /bitnami/moodledata /bitnami/moodledata/cache /bitnami/moodledata/cache/cachestore_file ...
```

If more than the maximum number of arguments, the command will be split and executed multiple times.

> The size of any set of two or more pathnames shall be limited such that execution of the utility does not cause the system's {ARG_MAX} limit to be exceeded.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html

This problem applies not only to bitnami/moodle but also to other bitnami containers.

All containers use similar scripts for `prebuildfs`, but I could not locate the base source repository.
If it is publicly available, I would like to send a PR there. If it is private, feel free to take it in.

Or, if there are no problems, I would like to send a PR for moodle only or for all containers.

https://github.com/jfut/bitnami-containers/tree/find-tuning-moodle
https://github.com/jfut/bitnami-containers/tree/find-tuning

This made the permission change process for our Moodle data about 20 times faster for directories and 38 times faster for files.

```
# before: 1m10.496s
root@moodle:/# time find -L /bitnami/moodledata -type d -exec chmod 775 {} +

real    0m3.530s
user    0m0.504s
sys     0m1.913s

# before: 6m29.147s
root@moodle:/# time find -L /bitnami/moodledata -type f -exec chmod 664 {} +

real    0m10.158s
user    0m1.149s
sys     0m6.438s
```

Total results:

```bash
# before: 
# docker compose logs -f
...
moodle-moodle-1   | moodle 11:48:04.40 INFO  ==> Ensuring Moodle directories exist
moodle-moodle-1   | moodle 11:56:20.49 INFO  ==> Trying to connect to the database server
...

# after: about 38 times faster
# docker compose logs -f
...
moodle-moodle-1   | moodle 12:03:13.21 INFO  ==> Ensuring Moodle directories exist
moodle-moodle-1   | moodle 12:03:26.03 INFO  ==> Trying to connect to the database server
...
```

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/moodle#user-content-community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by jfut** [comment]
It seems that my PR is no longer necessary as it seems to have been fixed in your private repository, which are probably internally maintained, and more improved code are being released one after another.

- https://github.com/bitnami/containers/commit/d0570efb6d2e89e1caa43ffb2cb7bac31fbdb4ea
- https://github.com/bitnami/containers/commit/d13a62edf0a265ada812285b9892038f74aff581
- and others

I imagine that the next release of these containers will reflect this, even for containers that have not yet been fixed. Thanks for the improvements.

As a further improvement, at least most directories of the bitnami/moodledata are set up with 2755, so it would be more faster if it could be made equivalent to the following.

```
find -L "$p" -type d \( ! -perm "$dir_mode" -and ! -perm "2$dir_mode" \) -print0 | xargs -r -0 chmod "$dir_mode"
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the suggestion. We will take a look to it and if it fits, as this is in a function used by almost all of our containers I guess it won't fit all the usage cases.

**Comment by jfut** [comment]
Thanks for your reply. If so, it is no problem as the code is fast enough as it is now.
