### ISSUE TITLE
[bitnami/kubectl] yaml/yml file not recognized

### ISSUE THREAD

**Issue by JophielV** [bitnami/containers#60099]
### Name and Version

bitnami/kubectl:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Run:
`docker run --rm --name kubectl --user $(id -u):$(id -g) --net=host -v <masked - path to my config>:/.kube/config -v /test.yaml:/test.yaml bitnami/kubectl:latest apply -f test.yaml`

### What is the expected behavior?

Should be able to create deployment to my minikube.

### What do you see instead?

Getting error:
**error: error reading [test.yaml]: recognized file extensions are [.json .yaml .yml]**

### Additional information

So, I have a test yaml file that I like to deploy to my local minikube k8 cluster. Minikube is already running on my local, I've tried yaml or yml files, tried with:
1. an empty yaml file 
2. a one liner yaml file with value: apiVersion: v1
3.  with the my original yaml 

but for some reason I'm getting this error. What could be the reason?

Additional context, I also have kubectl installed on my pc, I'm able to run and deploy to minikube using the command below:
`
kubectl apply -f test.yaml`

Get deployments is working using the image (just to test my connection to minikube):
`docker run --rm --name kubectl --user $(id -u):$(id -g) --net=host -v <masked - path to my config>:/.kube/config -v /test.yaml:/test.yaml bitnami/kubectl:latest get deployments`

I'm trying to make a CI/CD pipeline that will make use of this image so that I won't be needing to install kubectl when I transfer my pipeline to a remote server.

Thank you.

**Comment by JophielV** [comment]
Hello, any update?

**Comment by joancafom** [comment]
Hi @JophielV 

It seems to me that the file might not be properly mounted on the container. The output you are obtaining is also produced if, for instance, a directory is passed instead of a regular file. Could you please ensure the file is properly mounted and readable from within the container? You can do something like this:

```console
$ cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: bitnami/nginx
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

$ docker run -it --rm --name kubectl --user $(id -u):$(id -g) --net=host -v $(pwd)/test.yaml:/test.yaml --entrypoint bash bitnami/kubectl -c 'ls -la /test.yaml && stat /test.yaml && cat /test.yaml'
-rw-r--r-- 1 root root 237 Feb 16 15:27 /test.yaml
  File: /test.yaml
  Size: 237       	Blocks: 8          IO Block: 4096   regular file
Device: 83h/131d	Inode: 28119802    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-02-16 15:27:04.444515957 +0000
Modify: 2024-02-16 15:27:02.500663487 +0000
Change: 2024-02-16 15:27:02.507100076 +0000
 Birth: -
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: bitnami/nginx
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

**Comment by JophielV** [comment]
Hello @joancafom , thanks for the response. It worked when I used the absolute path for the volume:
`-v /test.yaml:/test.yaml //host path must be absolute`

It also works for this too:
`-v $(pwd)/test.yaml:/test.yaml`

It's resolved now, thank you.

**Comment by joancafom** [comment]
Glad it worked! You have to be very careful when working with volumes in docker. Always use the absolute path 😁
