### ISSUE TITLE
[bitnami/magento] build fails due to missing packages

### ISSUE THREAD

**Issue by GiuseppeScherillo** [bitnami/containers#60100]
### Name and Version

bitnami/magento:2.4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to build Magento image version 2.4.5

The build fails due to missing packages (error log message: `curl: (22) The requested URL returned error: 404 Not Found`)

Below are the components in the dockerfile required to build this version
```
COMPONENTS=( \
      "php-8.1.11-4-linux-${OS_ARCH}-debian-11" \
      "apache-2.4.54-157-linux-${OS_ARCH}-debian-11" \
      "wait-for-port-1.0.3-155-linux-${OS_ARCH}-debian-11" \
      "mysql-client-10.6.10-1-linux-${OS_ARCH}-debian-11" \
      "libphp-8.1.11-1-linux-${OS_ARCH}-debian-11" \
      "render-template-1.0.3-154-linux-${OS_ARCH}-debian-11" \
      "magento-2.4.5-p1-14-linux-${OS_ARCH}-debian-11" \
      "gosu-1.14.0-155-linux-${OS_ARCH}-debian-11" \
    )
```
If I try to manually download one of those missing packages, then I am just redirected back to https://bitnami.com/.

### What is the expected behavior?

The image should build successfully when following the specified instructions.

### What do you see instead?
```
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by carrodher** [comment]
Hi, we recently added a policy to remove those intermediate packages after some months. What's your use case for rebuilding the container? The preferred way to work with old container images is to create a Dockerfile using the old container as the base and then add any customization on top of it if needed:
```Dockerfile
FROM bitnami/magento:2.4.5-p1-debian-11-r14
...
```

**Comment by GiuseppeScherillo** [comment]
Hi,

thank you for your quick reply. In our case we need to edit the libmagento.sh script and add some customizations and it worked till the 404 error on that packages. So you are saying that packages will not be available again on that urls?

**Comment by carrodher** [comment]
We can restore them on-demand. The ones failing in your case are being restored, they should be back in some time.

**Comment by carrodher** [comment]
Hi, all the packages should be available right now.

**Comment by GiuseppeScherillo** [comment]
thank you very much! Now it is working!
