### ISSUE TITLE
bitnami/minideb:buster fails due to missing files

### ISSUE THREAD

**Issue by thrichardson-twist** [bitnami/containers#60447]
### Name and Version

docker.io/bitnami/minideb:buster

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Within our package there is a script `prebuildfs/opt/bitnami/scripts/libcomponent.sh` that tries to get these files from within the package while building the docker image (that does not exist) with a download fallback at this location: DOWNLOAD_URL="https://downloads.bitnami.com/files/stacksmith"

### What is the expected behavior?

Download these files when the Dockerfile is being built:

java-1.8.322-8-linux-amd64-debian-10.tar.gz
python-3.8.12-38-linux-amd64-debian-10.tar.gz
spark-3.2.1-7-linux-amd64-debian-10.tar.gz
gosu-1.14.0-7-linux-amd64-debian-10.tar.gz

### What do you see instead?

Errors like this:
```
Downloading gosu-1.14.0-7-linux-amd64-debian-10 package
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by thrichardson-twist** [comment]
Basically I'm just hoping to get the files restored.  I see other people who have made tickets for similar reasons and the files were restored.

**Comment by thrichardson-twist** [comment]
This is the code in the Dockerfile that interacts with the bitnami script:

RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.8.12-38" --checksum 54bdd2c14565f9c0d5409717e25f8f007d0a003d3c3cc53a999841aef8c8ab50
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "1.8.322-8" --checksum d5670d09ac0e679ae28306e417e77e91b44051908ca3a82259efcd70764b996f
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "spark" "3.2.1-7" --checksum 2a743f7c6e04db3e1db62479add901067b5b99b692973d6ecf98cc3c2b9e4ec7
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.14.0-7" --checksum d6280b6f647a62bf6edc74dc8e526bfff63ddd8067dcb8540843f47203d9ccf1

I understand that the checksum portion may not be required but as-is it just can't even download them.

**Comment by thrichardson-twist** [comment]
Advice for the future would be appreciated as well.  We may want to bump these files but I'm not able to list https://downloads.bitnami.com/files/stacksmith (even if logged in) to see what's there.  It redirects to your main page instead.

**Comment by thrichardson-twist** [comment]
maybe helpful:

{
    "gosu": {
        "arch": "amd64",
        "digest": "d6280b6f647a62bf6edc74dc8e526bfff63ddd8067dcb8540843f47203d9ccf1",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "1.14.0-7"
    },
    "java": {
        "arch": "amd64",
        "digest": "d5670d09ac0e679ae28306e417e77e91b44051908ca3a82259efcd70764b996f",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "1.8.322-8"
    },
    "python": {
        "arch": "amd64",
        "digest": "54bdd2c14565f9c0d5409717e25f8f007d0a003d3c3cc53a999841aef8c8ab50",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "3.8.12-38"
    },
    "spark": {
        "arch": "amd64",
        "digest": "2a743f7c6e04db3e1db62479add901067b5b99b692973d6ecf98cc3c2b9e4ec7",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "3.2.1-7"
    }
}

**Comment by carrodher** [comment]
Hi, we recently added a policy to remove those intermediate packages after some months. What's your use case for rebuilding the container? The preferred way to work with old container images is to create a Dockerfile using the old container as the base and then add any customization on top of it if needed:
```Dockerfile
FROM bitnami/spark:3.2.1
...
```

**Comment by thrichardson-twist** [comment]
Thanks for the quick reply.  Yes, after more investigating yesterday I did find: FROM bitnami/spark:3.2.2

That has essentially everything we were installing manually baked-in.  I was running an integration test last night but killed it as it was taking too long with plans to restart on a different machine today.  It does seem that this is going to work fabulously so you can close the ticket.

**Comment by carrodher** [comment]
Thanks for confirming! Yes, that should be the way to go rather than rebuilding the container from scratch.
