### ISSUE TITLE
[bitnami/openldap] Load access control files at startup

### ISSUE THREAD

**Issue by dirkweil** [bitnami/containers#60802]
### Name and Version

bitnami/openldap:2.6.3

### What is the problem this feature will solve?

I'm trying to allow self write access. It works, if I run the following command after container start
`ldapmodify -Y EXTERNAL -H "ldapi:///" -f selfwrite.ldif`

`selfwrite.ldif` contains the following text:
```
dn: olcDatabase={2}mdb,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by self write by * read
```

Unfortunately I find no configuration option to load this file at container start.

### What is the feature you are proposing to solve the problem?

It would be nice to have a directory like the one referenced by LDAP_CUSTOM_LDIF_DIR, where LDIFs for ldapmodify could be placed.

**Comment by migruiz4** [comment]
Thank you for your suggestion @dirkweil!

The `bitnami/openldap` has support for initScripts mounted at `/docker-entrypoint-initdb.d`, but only `.sh` files are supported.

As a workaround, you could use a `*.sh` that executed the `*.ldif` files mounted elsewhere, but I think it could be a nice feature for the image to support and run `*.ldif` files, would you like to contribute by sending a pull request?

**Comment by heinebold** [comment]
I can't make above ldapmodify command work in those sh scripts, getting "ldap_sasl_interactive_bind: Can't contact LDAP server (-1)". What is the correct host?

**Comment by javsalgar** [comment]
The host should be localhost AFAIK, maybe there were issues in the startup

**Comment by TontonJambon** [comment]
The readme says:

> The allowed script extension is .sh, all scripts are executed in alphabetical order and need to reside in /docker-entrypoint-initdb.d/.
> 
> Scripts are executed are after the initilization and before the startup of the OpenLDAP service.

I don't think this is suitable to run ldapmodify as-is
