### ISSUE TITLE
Add SeaweedFS to the catalog

### ISSUE THREAD

**Issue by soniqua** [bitnami/containers#60961]
### Name and Version

New image (seaweedfs)

### What is the problem this feature will solve?

Provide an open source Apache 2.0 Licensed object store/S3 compatible backend: https://github.com/seaweedfs/seaweedfs

### What is the feature you are proposing to solve the problem?

Add a bitnami image for seaweedfs, with a view to also integrate into bitnami/charts Helm repository.

### What alternatives have you considered?

MinIO, however: 

>MinIO(R) is licensed under GNU AGPL v3.0.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the product request! I will forward it to the team for evaluation.

**Comment by carrodher** [comment]
We're happy to announce that SeaweedFS is now part of the catalog, see
* https://github.com/bitnami/containers/tree/main/bitnami/seaweedfs
* https://github.com/bitnami/charts/tree/main/bitnami/seaweedfs

Enjoy it! 🎉
