### ISSUE TITLE
[bitnami/mongodb] Pod crashes on startup caused by typo

### ISSUE THREAD

**Issue by MSuter6** [bitnami/containers#61882]
### Name and Version

bitnami/mongodb:5.0.24

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Provision MongoDB instance from Bitnami helm chart with version 5.0.24 (https://github.com/bitnami/charts/tree/main/bitnami/mongodb)
2. Pod crashes immediately during execution of startup entrypoint.sh script with an `unbound variable` error.

### What is the expected behavior?

Pod should not crash.

### What do you see instead?

This is the log being printed on startup:
```
mongodb 17:39:38.35 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 17:39:38.35 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 17:39:38.35 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 17:39:38.35 INFO  ==> 
/opt/bitnami/scripts/mongodb/entrypoint.sh: line 24: MONOGODB_CONF_DIR: unbound variable
```

### Additional information

It seems like this PR introduced a commit with a typo: https://github.com/bitnami/containers/pull/61788. 
A debug log has the env variable name `MONGODB_CONF_DIR` misspelled as `MONOGODB_CONF_DIR:`  (https://github.com/bitnami/containers/pull/61788/files#diff-b1b40bf64c66ff65720ecd35f393532147ae62a08f9320d03c5550d8d7793093R24).

Other versions of MongoDB might be affected as well.

**Comment by Sh3nron** [comment]
bitnami/mongodb:6.0.13 is also affected

**Comment by ar124official2019** [comment]
Same issue, I believe recent builds (~7h ago) have the issue, it was working fine before. I tried `5.0` and `6.0`. Pls resolve asap.

**Comment by marklin-latte** [comment]
Same issue +1

**Comment by TanjinAlam** [comment]
> Not affected. Use it docker.io/bitnami/mongodb:6.0.13-debian-11-r17

platform : Apple M2 Pro
this version stuck on following error 
mongodb 06:59:36.46 INFO  ==> Validating settings in MONGODB_* env vars...

**Comment by WhoAmI0501** [comment]
Found our RocketChat instance down today - research showed, that the outage was also caused by this issue.

MongoDB failed to start with the following log messages:
```
mongo-1  | mongodb 09:58:06.06 INFO  ==> 
mongo-1  | mongodb 09:58:06.06 INFO  ==> Welcome to the Bitnami mongodb container
mongo-1  | mongodb 09:58:06.06 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongo-1  | mongodb 09:58:06.06 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongo-1  | mongodb 09:58:06.06 INFO  ==> 
mongo-1  | /opt/bitnami/scripts/mongodb/entrypoint.sh: line 24: MONOGODB_CONF_DIR: unbound variable
```

Renovate brought us `docker.io/bitnami/mongodb:6.0.13@sha256:85709dd493f5d6ba04d596efeeb33cc4ad88d4162415bca0be2d2f0aa1530b6b` via automerge tonight. After rolling back to `docker.io/bitnami/mongodb:6.0.13@sha256:2a8f4610f02c2f39c7608981d2895253206897c49dcd957c78b0a26956361e50`, it was working again...

Seems like this was caused by this commit: https://github.com/bitnami/containers/commit/158ec788aa3

**Comment by o-** [comment]
Tried being clever and defined that typoed variable myself only to get the next error:

> cp: cannot stat '/opt/bitnami/mongodb/conf.default/.': Not a directory

Now also rolled back to "2a8f4610f02c2f39c7608981d2895253206897c49dcd957c78b0a26956361e50" as suggested by @WhoAmI0501 and that works. Thanks!

**Comment by CXwudi** [comment]
For mongo 7 use [`7.0.5-debian-11-r22`](https://github.com/bitnami/containers/pull/61788/files#diff-4a993bac4ccad612f1cc2724e29d6328d92d707e62b2b682f9d6b41b6236b657L13)

**Comment by aviorma** [comment]
same issue

**Comment by michaelkorofiverr** [comment]
anyone has a working image for 5.0.24?

**Comment by alex1702** [comment]
> anyone has a working image for 5.0.24?

I have taken the 5.0.23

**Comment by javsalgar** [comment]
Hi!

We're very sorry for the inconvenience. Commit https://github.com/bitnami/containers/commit/07043d36a51c2838ef3c215f3e2b09206b186a78 should have fixed the issue.
