### ISSUE TITLE
Same Docker image, different PHP versions?

### ISSUE THREAD

**Issue by nbennett25** [bitnami/containers#62097]
### Name and Version

bitnami/symfony

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Different machines, using the same docker container image, getting different versions of php

### What is the expected behavior?

1. Different machines, using the same docker container image, getting the same version of php

### What do you see instead?

PHP 8.1 on one machine, PHP 8. 2 on the other

### Additional information

I understand this is an EOL'd container image, but hoping some one can point me in the right direction:  I'm working with a colleague, we're using the same docker compose file, the same `bitnami/symfony` container image - when they start the container, `php -v` shows 8.1, when I start mine, `php -v` shows 8.2 - we're both using Apple Silicon and Docker Desktop 4.27.1

**Comment by carrodher** [comment]
Yes, as you rightly say Symfony was recently deprecated from our catalog so the provided support is limited. Having said that, could you check if the image is cached in the docker engine or something like that?

**Comment by nbennett25** [comment]
We sorted it out @carrodher so no immediate need for a solution, but we do have different images:

My co worker has `bitnami/symfony 869673d3ed09` and I have `bitnami/symfony 2e243c0eda32` - is there a way to pull a specific image so we're in sync? 

Thx!

**Comment by carrodher** [comment]
Yes, you should by able to pull the image by digest, see https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-by-digest-immutable-identifier
