### ISSUE TITLE
GET https://xxxxxxxxxx/wp-admin/ 403 (Forbidden)

### ISSUE THREAD

**Issue by imdmahajankanika** [bitnami/containers#62535]
### Name and Version

bitnami/wordpress-nginx:6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using docker compose with wordpress-nginx and mariadb over port 80, running inside a VM.

Now when we are accessing the application with the HTTPS URL, I am unable to access wp-admin dashboard, although I can log in.

Getting below error:
```
GET https://xxxxxxxxxxxxxxxxxxx/wp-admin/ 403 (Forbidden)
wp-admin/:1 Mixed Content: The page at 'https://xxxxxxxxxxxxxxxxxxxxxxxxxr/wp-admin/' was loaded over HTTPS, but requested an insecure favicon 'http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/favicon.ico/'. This request has been blocked; the content must be served over HTTPS.
```
For Http->HTTPS redirection, I added `$_SERVER['HTTPS']='on';` in **wp-config.php** and also added `add_header 'Content-Security-Policy' 'upgrade-insecure-requests';` in nginx configuration file.

Also, for some other pages, I am getting 

https://xxxxxxxxxxxxxxxxxxxxxxx/wp-admin/customize.php?url=https%3A%2F%2Fxxxxxxxxxxxxxxxxxxxxxxxxxx%2F **302 document / Redirection**	

### What is the expected behavior?

/Wp-admin  should work.

### What do you see instead?

403 Access Denied and 302 Document Redirection

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
