### ISSUE TITLE
Documentation pages links to github don't reference monorepo

### ISSUE THREAD

**Issue by grooverdan** [bitnami/containers#6307]
### Name and Version

bitnami/any_container:x

### What steps will reproduce the bug?

1. From https://bitnami.com/stack/mariadb-galera/containers
2. scroll down
3. click on github right-hand-side links

### What is the expected behavior?

4. arrive https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera

### What do you see instead?

4. arrive https://github.com/bitnami/bitnami-docker-mariadb-galera

**Comment by fmulero** [comment]
Hi @grooverdan, thanks a lot for reporting this issue. We'll try to fix it as soon as possible

**Comment by carlossm** [comment]
Hi @grooverdan, we have fixed the links and verified that there are no other applications affected. Thanks again for reporting the issue.
