### ISSUE TITLE
[bitnami/apache-hive] hive image 

### ISSUE THREAD

**Issue by ahmedredahussien** [bitnami/containers#6324]
### Name and Version

containers/bitnami/apache-hive

### What is the problem this feature will solve?

Building a new image for apache-hive under bitnami containers stack "containers/bitnami/apache-hive"

### What is the feature you are proposing to solve the problem?

Any usage for apache-hive as database engine for Hadoop HDFS

### What alternatives have you considered?

Presto Database

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request. I will forward it to the team for evaluation.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
