### ISSUE TITLE
[bitnami/mariadb] non-root image but directories and files owned by root?

### ISSUE THREAD

**Issue by CyberDomovoy** [bitnami/containers#63330]
### Name and Version

bitnami/mariadb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
docker compose up -d
docker compose down -v
ls -l ./volumes/data
```

### What is the expected behavior?

list the local volume, files and directories being owned by the container user (uid 1001) and a group the _host_ user running the container can decently be a part of.

### What do you see instead?

directories are owned by `root:root`, permissions `rwxrwxr-x`
files are owned by `1001:root`, permissions `rw-rw----`

This forbids a _host_ non root user to manipulate the data in the volume (apart for reading those) since he is neither `root`, `1001` or a member of the `root` group

### Additional information

compose.yaml
```yaml
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - data:/bitnami/mariadb

volumes:
  data:
    driver: local
    driver_opts:
      device: ./volumes/data
      type: none
      o: bind
```

```
$ docker compose exec mariadb id
uid=1001 gid=0(root) groups=0(root)
```

In `/opt/bitnami/scripts/mariadb/run.sh` we find:
```sh
if am_i_root; then
    exec_as_user "$DB_DAEMON_USER" "$EXEC" "${flags[@]}"
else
    exec "$EXEC" "${flags[@]}"
fi
```

In `/opt/bitnami/scripts/mariadb-env.sh` we find:
```sh
export DB_DAEMON_USER="mysql"
export DB_DAEMON_GROUP="mysql"
```

But those don't actually exists:
```
$ docker compose exec mariadb grep mysql /etc/passwd /etc/group
$
```

In `/opt/bitnami/scripts/mariadb/postunpack.sh` we find:
```sh
info "Configuring default MariaDB options"
ensure_dir_exists "$DB_CONF_DIR"
mysql_create_default_config

for dir in "$DB_TMP_DIR" "$DB_LOGS_DIR" "$DB_CONF_DIR" "$DB_DEFAULT_CONF_DIR" "${DB_CONF_DIR}/bitnami" "$DB_VOLUME_DIR" "$DB_DATA_DIR"; do
    ensure_dir_exists "$dir"
    chmod -R g+rwX "$dir"
done
```

In my opinion, those lines should be something like:
```sh
info "Configuring default MariaDB options"
groupadd --system --gid 1001 "$DB_DAEMON_GROUP"
useradd --system --uid 1001 --gid 1001 --home "$DB_CONF_DIR" "$DB_DAEMON_USER"
ensure_dir_exists "$DB_CONF_DIR" "$DB_DAEMON_USER" "$DB_DAEMON_GROUP"
mysql_create_default_config

for dir in "$DB_TMP_DIR" "$DB_LOGS_DIR" "$DB_CONF_DIR" "$DB_DEFAULT_CONF_DIR" "${DB_CONF_DIR}/bitnami" "$DB_VOLUME_DIR" "$DB_DATA_DIR"; do
    ensure_dir_exists "$dir"  "$DB_DAEMON_USER" "$DB_DAEMON_GROUP"
    chmod -R g+rwX "$dir"
done
```

The docker file should also reflect that user and group in the `USER` directive:
```
USER 1001:1001
```

Personal opinions:
- Having the default user a member of the `root` group defeats the idea of a non-root image
- Using a default uid in the range 1000-59999 is not great, since many _hosts_ have actual users using these. 100-999 is not much better, since who knows what _system_ users the host will have. Maybe above 100000?

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by CyberDomovoy** [comment]
Just tested the following Dockerfile, everything seems to work fine.

```Dockerfile
FROM bitnami/mariadb:latest

USER 0:0

RUN groupadd --system --gid 100001 "mariadb"
RUN useradd --system --uid 100001 --gid 100001 --home "/opt/bitnami/mariadb" "mariadb"

RUN chown -R mariadb:mariadb "/opt/bitnami/mariadb"
RUN chmod -R u=rwX,g=rwX,o=rX "/opt/bitnami/mariadb"

RUN chown -R mariadb:mariadb "/bitnami/mariadb"
RUN chmod -R u=rwX,g=rwX,o=rX "/bitnami/mariadb"

USER 100001:100001
```

**Comment by CyberDomovoy** [comment]
> Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group.

That's where i must be missing something, because i don't see much increase in security if the application, even if not the root _user_, is a member of the root _group_.
That still leaves a _massive_ amount of root owned files in the container accessible by anyone who accesses it.

> To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.
Im gonna look further on that, but from what i saw, starting the container changes ownership and permissions of the _host_ directory to whatever is set _in the container_

**Comment by CyberDomovoy** [comment]
In regard to the `Principle of Least Privilege`, imho, the following permissions would ensure much less exposure, while still be enough to ensure the application runs correctly:
```Dockerfile
FROM bitnami/mariadb:latest

USER 0:0

RUN groupadd --system --gid 100001 "mariadb"
RUN useradd --system --uid 100001 --gid 100001 --home "/opt/bitnami/mariadb" "mariadb"

RUN chown -R mariadb:mariadb "/opt/bitnami/mariadb"
RUN chmod -R u=rX,g-rwx,o-rwx "/opt/bitnami/mariadb"
RUN chmod -R u=rwX,g-rwx,o-rwx "/opt/bitnami/mariadb/logs"
RUN chmod -R u=rwX,g-rwx,o-rwx "/opt/bitnami/mariadb/tmp"

RUN chown -R mariadb:mariadb "/bitnami/mariadb"
RUN chmod -R u=rwX,g=rwX,o-rwx "/bitnami/mariadb"

USER 100001:100001
```

In regard to `Docker mounts host volumes preserving the host UUID and GUID`, this is true for _anonymous_ volumes, as far as i tested, but not for a specific bind mount as i did.
I recall doing those specific bind mounts because with anonymous volumes i ended up with a lot of those as dangling on my system. I just tried again, that problem seems to have gone... So on that side i guess this issue is actually solved.

Still, i believe the `Principle of Least Privilege` could be enforced better, maybe rename this issue, or should i open a new one?

**Comment by javsalgar** [comment]
Hi,

In our helm charts we're working on changing from 1001:root to 1001:1001. This PR allows the feature (but did not make it default, we plan to do it in a major bump). https://github.com/bitnami/charts/pull/23566

**Comment by CyberDomovoy** [comment]
> In our helm charts we're working on changing from 1001:root to 1001:1001

Hi, does this mean that this change will make its way to the Dockerfile?

**Comment by javsalgar** [comment]
Hi,

I'm afraid we don't have plans to move user 1001:1001 to the Dockerfile for the time being. For production workloads our recommendation is to use our helm charts.

**Comment by CyberDomovoy** [comment]
I see, thanks for the info.

Since this is not particular to mariadb, but afaik an issue concerning every non-root Dockerfile, should this issue be renamed, or another one opened?
I'm asking because i'd like to follow progress on this, so that i know if and when i should update my own Dockerfiles.

**Comment by carrodher** [comment]
It's fine to keep it as it is, thanks for the suggestion anyway.

**Comment by CyberDomovoy** [comment]
Solved label?
