### ISSUE TITLE
[bitnami/keycloak] Incorrect validation error printed in keycloak container when KEYCLOAK_BIND_ADDRESS is invalid

### ISSUE THREAD

**Issue by i-jae** [bitnami/containers#63356]
### Name and Version

bitnami/keycloak:23.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When starting the container with an invalid KEYCLOAK_BIND_ADDRESS configured, the error message printed is "print_validation_error" instead of an actual error. 

### What is the expected behavior?

I expect an error message that explains the issue.

### What do you see instead?

print_validation_error 

### Additional information

This is caused by the extra `print_validation_error ` in this line: https://github.com/bitnami/containers/blob/b13569b07a3ffb4f8a43cca19a85040830715ca3/bitnami/keycloak/23/debian-12/rootfs/opt/bitnami/scripts/libkeycloak.sh#L77

**Comment by javsalgar** [comment]
Hi!

Thank you so much for spotting the issue. Would you like to to submit a PR fixing it?

**Comment by i-jae** [comment]
I'm fine, but thank you for offering :)
