### ISSUE TITLE
[bitnami/wordpress-nginx] when 6.4.3 version is planned in docker hub ?

### ISSUE THREAD

**Issue by dejwsz** [bitnami/containers#63394]
### Name and Version

bitnami/wordpress-nginx:6.4.3

### What is the problem this feature will solve?

Do you know when version 6.4.3 of bitnami/wordpress-nginx will be available in docker hub?

### What is the feature you are proposing to solve the problem?

Should I build it by ourself?

### What alternatives have you considered?

Building by ourself

**Comment by carrodher** [comment]
Unfortunately, we are facing some issues with this new version, we'll update an already existing Issue once fixed the problem. Duplicate of #56471
