### ISSUE TITLE
[bitnami/kafka] Issue with Configuring Kafka Authorizer in Bitnami Kafka Image

### ISSUE THREAD

**Issue by zeeshan018** [bitnami/containers#63407]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I hope this message finds you well. I'm reaching out to seek assistance with an issue I'm encountering while trying to configure the Kafka authorizer in the Bitnami Kafka image.

I'm currently using the Bitnami Kafka image in my environment, and I need to set up access control lists (ACLs) for my Kafka topics using an authorizer. However, I've found that the Bitnami Kafka image does not seem to provide a straightforward way to configure the Kafka authorizer, such as through environment variables or configuration files.

I've attempted to use the kafka-acls.sh script to manage ACLs, but it requires an authorizer to be configured, and I'm unable to provide the necessary authorizer properties.

Could you please provide guidance on how I can properly configure the Kafka authorizer in the Bitnami Kafka image? Specifically, I need assistance with:

Enabling and configuring the Kafka authorizer.
Providing the necessary authorizer properties for ACL management.
Any recommended best practices or documentation for managing ACLs in the Bitnami Kafka image.
Any assistance or insights you can provide would be greatly appreciated. If there are specific configuration settings or workarounds that I need to implement, please kindly provide detailed instructions.

### What is the expected behavior?

.

### What do you see instead?

.

**Comment by zeeshan018** [comment]
@carrodher  please reply ASAP

**Comment by Mauraza** [comment]
Hi @zeeshan018, 

Did you check this issue https://github.com/bitnami/containers/issues/23237?
