### ISSUE TITLE
[bitnami/tensorflow-serving] I want to know how to use the api to access

### ISSUE THREAD

**Issue by crash-zwt** [bitnami/containers#63420]
### Name and Version

bitnami/tensorflow-serving:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. I run the docker through the following command:
docker run -d -p 8501:8501 --name tensorflow-serving \
--volume /Users/mima0000/Desktop/model:/bitnami/model-data \          
-e MODEL_NAME=model \
bitnami/tensorflow-serving:2.14.1
2. I use the post to access the serve

I follow the official instructions, but it did not work out 
```
curl -d '{"instances": [1.0, 2.0, 5.0]}' \
    -X POST http://localhost:8501/v1/bitnami/model-data/model/:predict

{
    "error": "Malformed request: POST /v1/bitnami/model-data/model/:predict"
}% 
```
### What is the expected behavior?

I want to know how to use it

### What do you see instead?
```
mima0000@MacBook-Air Desktop % curl -d '{"instances": [1.0, 2.0, 5.0]}' \
    -X POST http://localhost:8501/v1/bitnami/model-data/model/:predict
{
    "error": "Malformed request: POST /v1/bitnami/model-data/model/:predict"
}%   
```

**Comment by crash-zwt** [comment]
I might add that what the correct Post address is and the how  the post method of use differ from the official one. Thank you for answering my question

**Comment by javsalgar** [comment]
Hi,

Could you share which instructions you followed? It seems to me that the issue is not related with the Bitnami packaging of Tensorflow but with the usage of Tensorflow itself. Did yo check with the upstream developers? Maybe their documentation is not updated.

**Comment by crash-zwt** [comment]
I followed the [https://github.com/tensorflow/serving](url) 
![image](https://github.com/bitnami/containers/assets/96490044/7eb389ec-01c1-47d5-aa2f-2164388afa6f)
what's more, the tensorflow website [https://tensorflow.google.cn/tfx/serving/api_rest](url)  also provides the predict api format. this is POST http://host:port/v1/models/${MODEL_NAME}[/versions/${VERSION}|/labels/${LABEL}]:predict，I can run successfully through the mirror image given by the tensorflow authorities, so I want to know about in arm64 in your docker, the he predict api format is  changed？

**Comment by juan131** [comment]
Hi @crash-zwt 

As you can see the Bitnami image is indeed exposing by default Tensorflow REST API in the port 8501:

- https://github.com/bitnami/containers/tree/main/bitnami/tensorflow-serving#customizable-environment-variables

However, the error you're obtaining seems to be a problem with your POST request. Why are you using this endoint `http://localhost:8501/v1/bitnami/model-data/model/:predict`? Shouldn't it be `http://localhost:8501/v1/models/model:predict`?

**Comment by crash-zwt** [comment]
I have already tried the url  http://localhost:8501/v1/models/model:predict, but it is still an error

**Comment by juan131** [comment]
Hi @crash-zwt 

Could you please follow these steps?

```console
$ git clone git@github.com:tensorflow/serving.git
$ export TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"
$ docker run -d -p 8501:8501 \
  --name tensorflow-serving \
  --volume "$TESTDATA/saved_model_half_plus_two_cpu:/bitnami/model-data/half_plus_two" \
  -e MODEL_NAME=half_plus_two \
  bitnami/tensorflow-serving:2.14.1
$ curl -d '{"instances": [1.0, 2.0, 5.0]}' -X POST http://localhost:8501/v1/models/half_plus_two:predict
{
    "predictions": [2.5, 3.0, 4.5
    ]
}
```

**Comment by crash-zwt** [comment]
H! @juan131 
I have followed your steps and it had this error:
![image](https://github.com/bitnami/containers/assets/96490044/1cc41f31-edb2-4b0d-a44b-4036fa819a47)
This is the logs
![image](https://github.com/bitnami/containers/assets/96490044/a0f7afae-864d-4c4f-a1d0-9e4822cd39cf)

**Comment by crash-zwt** [comment]
It still don't work 
![image](https://github.com/bitnami/containers/assets/96490044/555f30ee-debd-4466-869d-4a010800ddbe)

**Comment by juan131** [comment]
Please ensure the `--volume` flag has this value: `"$TESTDATA/saved_model_half_plus_two_cpu:/bitnami/model-data"`

**Comment by crash-zwt** [comment]
![image](https://github.com/bitnami/containers/assets/96490044/c2af555b-1023-4aae-a700-5e856fcafaa8)

yes, the model has be copied to the  /bitnami/model-data

**Comment by crash-zwt** [comment]
Thank you, it did work!
