### ISSUE TITLE
[bitnami/redis] didn't write on aof files and fails when restart any pod

### ISSUE THREAD

**Issue by antonios94** [bitnami/containers#63438]
### Name and Version

bitnami/redis:18.17.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
helm install redis bitnami/redis -n redis --create-namespace  \
   --set global.redis.password=redis-password,volumePermissions.enabled=true  \
   --set replica.replicaCount=3 \
   --set master.persistence.enabled=true,replica.persistence.enabled=true \
    --set sysctl.enabled=true,sysctl.command[0]='/bin/sh',sysctl.enabled=true,sysctl.command[1]='-c' \
    --set sysctl.command[2]='sysctl -w net.core.somaxconn=10000',sysctl.enabled=true \
    --set sysctl.command[3]='echo never > /host-sys/kernel/mm/transparent_hugepage/enabled' 
```
### What is the expected behavior?

redis create appendonly.aof.1.base.rdb  appendonly.aof.1.incr.aof  appendonly.aof.manifest on nfs pvc under appendonlydir and write data on these files to can restore when restart

### What do you see instead?

all files created with permissions user:root and all are empty and when any redis pod restart it fail it gives error Found an empty AOF manifest

### Additional information

k8s version 1.26.14
i tried to deploy with & without volumePermissions.enabled=true and same output and find that it's not affecting any permissions on the created dir and files
can't see any errors related to write permissions inside redis pod or in nfs provisioner ,
when exec to any pod i can read and write in /data dir so i can't find out the issue related to which layer
i tried to change uid , gid , fsGroup but with same error and try to change permissions from worker node but still same issue

**Comment by javsalgar** [comment]
Hi!

Which is the storage provider you are using?

**Comment by antonios94** [comment]
> Hi!
> 
> Which is the storage provider you are using?

iam using  [kubernetes-sigs/nfs-subdir-external-provisioner] and tried kubernetes-csi/csi-driver-nfs and same result with both

**Comment by antonios94** [comment]
@FraPazGal  @javsalgar any feedback please ??
