### ISSUE TITLE
[bitnami/laravel] updates

### ISSUE THREAD

**Issue by gabrielrbarbosa** [bitnami/containers#63430]
### Name and Version

bitnami/laravel10

### What is the problem this feature will solve?

Can't use PHP 8.3 new features with bitnami/laravel10 due to fixed php 8.2 in dockerfile.
Also Laravel 11 is releasing in Q1 2024 could be also released here please?

### What is the feature you are proposing to solve the problem?

Any feature in php 8.3 cant be used with this docker image

**Comment by javsalgar** [comment]
Hi,

As soon as there are new releases the team will package them. About the php version, did you try creating a fork in the meantime?

**Comment by gabrielrbarbosa** [comment]
I was using this image on bitbucket-pipeline but replaced to install directly from php:8.3-cli image and then composer, extensions, etc.

L11 will be released in next weeks so we can wait for it

**Comment by gabrielrbarbosa** [comment]
https://blog.laravel.com/laravel-11-now-available

**Comment by lloricode** [comment]
also please support php8.3

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, since it's a major version some manual work is needed so the team needs to prioritize it alongside the rest of the tasks. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by gabrielrbarbosa** [comment]
Any estimate on this release?

**Comment by carrodher** [comment]
Unfortunately, the task is still in progress, given the number of applications in our catalog and the team's bandwidth, new major versions could take some weeks. We will update this GH Issue once it is ready.

**Comment by carrodher** [comment]
Finally, the new major version was released. You can find Laravel 11 as usual in [GitHub](https://github.com/bitnami/containers/tree/main/bitnami/laravel/11/debian-12) and [DockerHub](https://hub.docker.com/r/bitnami/laravel/tags?page=1&name=11).

Thanks for your patience.

**Comment by gabrielrbarbosa** [comment]
https://github.com/bitnami/containers/blob/c27f37e2f43b78bcab53b45d316f0c369151b528/bitnami/laravel/11/debian-12/Dockerfile#L30

Couldn't it use php 8.3 and node 20?

**Comment by carrodher** [comment]
A new version bundling PHP 8.3 and NodeJS 20 was released at https://github.com/bitnami/containers/pull/64570
