### ISSUE TITLE
[bitnami/kafka] CrashLoopBackOff: No injected configuration files found

### ISSUE THREAD

**Issue by Arul-Devan** [bitnami/containers#63435]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

Environment: EKS
Chart version: 26.11.3
Kafka version: 3.4.0 (3.4.0-debian-11-r6)
Download the helm chart offline
Create new values.yaml to use a private registry to install the chart.

Issue: controller-0, controller-1, controller-2 pods are in CrashLoopBackOff status
Pod logs show an info message as below:
```
No injected configuration files found, creating default config files
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/kafka/config/producer.properties: Read-only file system
```
Thanks.

### What is the expected behavior?

Scheduled pods

### What do you see instead?

CrashLoopBackOff pods

**Comment by javsalgar** [comment]
which exact version of the chart are you using? We are unable to reproduce the issue

**Comment by Arul-Devan** [comment]
> which exact version of the chart are you using? We are unable to reproduce the issue

I'm using the latest charts: (pulled using command: helm pull oci://registry-1.docker.io/bitnamicharts/kafka) which downloaded kafka-26.11.3.tgz
Thanks.

**Comment by Arul-Devan** [comment]
> Which values did you change?

I have updated imageRegistry to use my private image registry and extraEnvVars to ALLOW_PLAINTEXT_LISTENER
Thanks.

**Comment by Arul-Devan** [comment]
This thread can be closed:
Resolution: Used proper charts based on required version.
Ref: https://github.com/bitnami/charts/issues/10833
Thanks.

**Comment by Arul-Devan** [comment]
Closing with above resolution

**Comment by alanperius** [comment]
Hey @Arul-Devan how did u solve it? Facing the same issue. 
kafkaVersion: bitnami/kafka:3.4.0

**Comment by Arul-Devan** [comment]
Hi @alanperius : Using right chart version helped to resolve my issue.
Please see details here to get the required chart version for your kafka.
https://github.com/bitnami/charts/issues/10833
Thanks.

**Comment by alanperius** [comment]
Thanks @Arul-Devan. I just moved to bitnami/kafka:3.4.1 and all worked
