### ISSUE TITLE
[bitnami/rabbitmq] In need of bitnami/rabbitmq:3.13

### ISSUE THREAD

**Issue by anksinghal** [bitnami/containers#63436]
### Name and Version

bitnami/rabbitmq 3.13

### What is the problem this feature will solve?

In need of latest docker image for 3.13 of rabbitmq

### What is the feature you are proposing to solve the problem?

This will help in getting latest fixes provided by rabbitmq

### What alternatives have you considered?

3.12 i tried using

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by anksinghal** [comment]
@carrodher Do we have any update on this?

**Comment by carrodher** [comment]
> @carrodher Do we have any update on this?

Not yet, the team is working on this new major version, given the large catalog we maintain, new major versions could take some time. This thread will be updated once released the new version.

**Comment by anksinghal** [comment]
@carrodher Do we have some timeline for this? We are dependent on this image to be pushed.

**Comment by javsalgar** [comment]
Hi! I'm afraid we're still on working on this, as soon as there are updates, we will update the ticket.

**Comment by anksinghal** [comment]
Hi! any updates on this? Posted this a month back. Any tentative timeline for this to be fixed?

**Comment by carrodher** [comment]
Unfortunately, it's still on our backlog since major versions need manual work on our side. Given the number of assets in our catalog we can't provide an ETA. We'll update this ticket once released.

**Comment by dgomezleon** [comment]
Hi @anksinghal ,

We have just released RabbitMQ 3.13 ([PR](https://github.com/bitnami/containers/pull/65041)).

**Comment by anksinghal** [comment]
Thanks a lot team. This will help us.
