### ISSUE TITLE
Cassandra docker  - add the possibility to set up additional cassandra.yaml properties via docker env variables

### ISSUE THREAD

**Issue by nlescure-pictet** [bitnami/containers#63452]
### Name and Version

bitmani/cassandra

### What is the problem this feature will solve?

Makes it easier to use the image without having to mount a custom config file

### What is the feature you are proposing to solve the problem?

It would be nice to be able to configure additional _cassandra.yaml_ properties via docker env variables such as `read_request_timeout_in_ms`. 
It should be made generic like for the `CASSANDRA_CFG_ENV_*`, `CASSANDRA_CFG_RACKDC_*` and `CASSANDRA_CFG_COMMITLOG_*` approach described here: https://hub.docker.com/r/bitnami/cassandra/

Thanks a lot

### What alternatives have you considered?

Mounting a _cassandra.yaml_ file but it's cumbersome

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by nlescure-pictet** [comment]
Hi there - any comment on the issue ?

**Comment by nlescure-pictet** [comment]
Apparently in version 4.1.4 it is now possible to add CASSANDRA_CFG_YAML_* to configure cassandra.yaml properties - thanks a lot to the person who made it possible !!!

Cheers
