### ISSUE TITLE
[bitnami/consul] Add latest minor x.y tag for consul containers ?

### ISSUE THREAD

**Issue by ednxzu** [bitnami/containers#63470]
### Name and Version

bitnami/consul

### What is the problem this feature will solve?

Enabling those tags would allow to only fix the minor version to stick to, and allow patch versions to be pulled automatically

### What is the feature you are proposing to solve the problem?

tag the latest patch `x.y.z` of each minor with an minor `x.y` tag

### What alternatives have you considered?

Well the alternative would be to update the tags manually which is doable but something I would like to not have to worry about :)

**Comment by javsalgar** [comment]
Hi!

I'm afraid that our current automations do not allow this. I will forward it to the engineering team for evaluation.

**Comment by carrodher** [comment]
As announced at https://github.com/bitnami/containers/issues/75671, only one branch of Consul will be available in Bitnami, the rest of the branches will be only available as part of [Bitnami Premium](https://www.arrow.com/globalecs/na/vendors/bitnami?utm_source=GitHub&utm_medium=containers).
