### ISSUE TITLE
[bitnami/elasticsearch] Support customizing Elasticsearch config file path

### ISSUE THREAD

**Issue by aabouzaid** [bitnami/containers#63477]
### Name and Version

docker.io/bitnami/elasticsearch (all versions)

### What is the problem this feature will solve?

I'm using [bitnami/elasticsearch](https://artifacthub.io/packages/helm/bitnami/elasticsearch) Helm chart and I want to configure [readOnlyRootFilesystem](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for security. To do so, any dir that needs write access should be mounted as an empty dir volume.

The issue is that the dir `/opt/bitnami/elasticsearch/config` has files shipped with the image in addition to ES config file `/opt/bitnami/elasticsearch/config/elasticsearch.yml` which auto-generated at the startup.

For that reason, the config file path should be customizable to set it to a writable dir.

### What is the feature you are proposing to solve the problem?

Allow to set the value of the var `ELASTICSEARCH_CONF_FILE` here:
https://github.com/bitnami/containers/blob/4a21bf3/bitnami/elasticsearch/8/debian-12/rootfs/opt/bitnami/scripts/elasticsearch-env.sh#L127

From:
```
export ELASTICSEARCH_CONF_FILE="${DB_CONF_DIR}/elasticsearch.yml"
```

To:
```
export ELASTICSEARCH_CONF_FILE="${ELASTICSEARCH_CONF_FILE:-$DB_CONF_DIR/elasticsearch.yml}"
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR changing that default?

**Comment by aabouzaid** [comment]
Sure, I will make a PR for it this week :+1:

**Comment by sephiroth-j** [comment]
Hello @aabouzaid ,

take a look at [`extraConfig`](https://artifacthub.io/packages/helm/bitnami/elasticsearch?modal=values&path=extraConfig). It allows you to append extra configuration to the elasticsearch configuration.

```yml
extraConfig:
  s3:
    client:
      default:
        endpoint: "my.host.domain.tld:port"
        region: "my-region"
        path_style_access: true
```

**Comment by aabouzaid** [comment]
@sephiroth-j that's not what I'm looking for.

I want to set the default `elasticsearch.yml` path so it can be customized to something different than `/opt/bitnami/elasticsearch/config`.

**Comment by aabouzaid** [comment]
Using Helm chart [bitnami/elasticsearch v20.0.0](https://artifacthub.io/packages/helm/bitnami/elasticsearch/20.0.0) supports this by default.
