### ISSUE TITLE
KEYCLOAK_ADMIN_USER and KEYCLOAK_ADMIN_PASSWORD are always set

### ISSUE THREAD

**Issue by trajchelazovski** [bitnami/containers#6348]
### Name and Version

bitnami/keycloak:19.0.1

### What steps will reproduce the bug?

1. Precondition: Have an already initialized Keycloak instance
2. Either not set any KEYCLOAK_ADMIN_USER and KEYCLOAK_ADMIN_PASSWORD or set KEYCLOAK_CREATE_ADMIN_USER to false
3. Start the keycloak image
4. Error in logs KC-SERVICES0010: Failed to add user 'user' to realm 'master': user with username exists

### What is the expected behavior?

We should have an option to not set the user and password.
As far as I could see currently is not used at all and there is not option to set empty values to KEYCLOAK_ADMIN_USER and KEYCLOAK_ADMIN_PASSWORD.

### What do you see instead?

Possibility to create a Keycloak instance without default user and password.

### Additional information

I assume the easiest fix would be to remove the default values from [keycloak-env.sh](https://github.com/bitnami/containers/blob/main/bitnami/keycloak/19/debian-11/rootfs/opt/bitnami/scripts/keycloak-env.sh).

Or reintroduce the usage of KEYCLOAK_CREATE_ADMIN_USER .

~~Unless I am missing something with the current behavior when the Keycloak image is started against some persistent storage I am running into the issue described in the related [Keycloak issue](https://github.com/keycloak/keycloak/issues/12169) which unfortunately is not resolved.~~
While the error is indeed shown it doesn't prevent the Keycloak image from starting.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
