### ISSUE TITLE
Run without root

### ISSUE THREAD

**Issue by JBlaschke** [bitnami/containers#63508]
### Name and Version

bitnami/discourse:latest

### What is the problem this feature will solve?

I am trying to run bitnami/discourse:latest on a shared kubernetes cluster.  `chroot` is not allowed on that system due to security policy. Currently, I cannot launch discourse without getting: `chroot: cannot change root directory to '/': Operation not permitted`

### What is the feature you are proposing to solve the problem?

To run discourse in non-privileged mode

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by JBlaschke** [comment]
@carrodher thanks for the resources. I am looking for advice how to solve the `chroot: cannot change root directory to '/': Operation not permitted` problem.

Since security policy does not permit me to set the `sys_chroot` capability. Additionally, I need a solution that allows me to run the discourse container in non-privileged mode.

**Comment by carrodher** [comment]
The specific case of Discourse is one of the exceptions we need to maintain in our catalog. Given the nature of the application itself, the bitnami/discourse container doesn't support non-root. You can double-check this by taking a look at the Dockerfile, there is not a `USER 1001` directive so the container is built and executed as root.
