### ISSUE TITLE
[bitnami/postgresql-repmgr] - cannot execute "install_packages"  postunpack.sh

### ISSUE THREAD

**Issue by da-baranov** [bitnami/containers#63510]
### Name and Version

bitnami/postgresql-repmgr:16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Docker Desktop for Windows
2. Default Dockerfile is used
3. Run `docker build --no-cache -t mypg .`

### What is the expected behavior?

I expect to have a ready-to-use image

### What do you see instead?

The build ends up with the following error: 
```
ERROR: failed to solve: process "/bin/bash -o errexit -o nounset -o pipefail -c install_packages ca-certificates curl libbsd0 libedit2 libffi8 libgcc-s1 libgmp10 libgnutls30 libhogweed6 libicu72 libidn2-0 libldap-2.5-0 liblz4-1 liblzma5 libmd0 libnettle8 libp11-kit0 libpcre3 libreadline8 libsasl2-2 libsqlite3-0 libssl3 libstdc++6 libtasn1-6 libtinfo6 libunistring2 libuuid1 libxml2 libxslt1.1 locales procps zlib1g pgagent" did not complete successfully: exit code: 127
```

If I modify line 26 as follows:
```diff
 - RUN install_packages ca-certificates curl libbsd0 libedit2 libffi8...
 + RUN apt-get update
 + RUN apt-get install -y ca-certificates curl libbsd0 libedit2 libffi8...
```

The process ends up with these errors:
```
RUN /opt/bitnami/scripts/postgresql-repmgr/postunpack.sh:
0.495 /bin/bash: line 1: /opt/bitnami/scripts/postgresql-repmgr/postunpack.sh: cannot execute: required file not found
```

**Comment by da-baranov** [comment]
Update 1: it is declared that minideb image already includes the [install_packages](https://github.com/bitnami/minideb) script. 
I suppose that content of the `bitnami/postgresql-repmgr/16/debian-12/prebuildfs/usr/sbin` directory conflicts with same files included in the minideb image. If I delete the `bitnami/postgresql-repmgr/16/debian-12/prebuildfs/usr/sbin` directory and run `docker build..` again I see that the `install_packages` script works.

**Comment by carrodher** [comment]
Thanks for the explanation, it could be something related to Docker Desktop for Windows and how it implements virtualization. In other environments, it shouldn't be needed to perform those extra actions.

**Comment by liquid8796** [comment]
I have simpler one for this issue, just add package `dos2unix` and convert your newline crlf (windows) within .sh file to newline lf (unix)
RUN apt-get update ; apt-get install -y dos2unix

COPY prebuildfs /

RUN dos2unix /usr/sbin/install_packages
RUN install_packages ...
