### ISSUE TITLE
[feature] Provides OpenJDK image for Eclipse Temurin distributions

### ISSUE THREAD

**Issue by fangzhengjin** [bitnami/containers#63549]
### Name and Version

bitnami/java

### What is the problem this feature will solve?

Provides OpenJDK image for Eclipse Temurin distributions

### What is the feature you are proposing to solve the problem?

Provides OpenJDK image for Eclipse Temurin distributions

**Comment by carrodher** [comment]
What's exactly the version/flavor you're missing at https://github.com/bitnami/containers/tree/main/bitnami/java?

**Comment by fangzhengjin** [comment]
https://github.com/bitnami/containers/tree/main/bitnami/java

The version currently in use is https://openjdk.org
Hope to provide Eclipse Temurin version at the same time: https://adoptium.net

**Comment by carrodher** [comment]
Thanks for the info, unfortunately, in the short term there are no plans to support other Java flavors.
