### ISSUE TITLE
[bitnami/keycloak] upgrade to 24.0.0

### ISSUE THREAD

**Issue by Jojoooo1** [bitnami/containers#63545]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Upgrade to last Keycloak version 24.0.0

### What is the feature you are proposing to solve the problem?

Latest features and fixes from keycloak

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by tanadeau** [comment]
See also https://github.com/adorsys/keycloak-config-cli/issues/996, as that not-yet-released version of `keycloak-config-cli` will need to be brought in as well.

**Comment by tanadeau** [comment]
Are there any updates on this? We'd like to upgrade to Keycloak 24 for some CVE fixes among other reasons.

**Comment by carrodher** [comment]
Thanks for your patience. Container images for Keycloak 24 (24.0.2) were released some hours ago, see https://hub.docker.com/r/bitnami/keycloak/tags

**Comment by tanadeau** [comment]
Are images pushed to https://gallery.ecr.aws/bitnami/keycloak automatically? It looks like the new tag isn't available there yet.

**Comment by carrodher** [comment]
There was a pending step which already succeeded, the image is now present in AWS Public Gallery and DockerHub
