### ISSUE TITLE
(feature): how to use jq within etcd container

### ISSUE THREAD

**Issue by buraksekili** [bitnami/containers#63542]
### Name and Version

bitnami/etcd:3.5.12

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```bash
$ docker network create app-tier --driver bridge
$ docker run -d --name etcd-server \
    --network app-tier \
    --publish 2379:2379 \
    --publish 2380:2380 \
    --env ALLOW_NONE_AUTHENTICATION=yes \
    --env ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379 \
    bitnami/etcd:latest
```
Then, connect to etcd container
```bash
$ docker exec -it etcd-server bash
```

Run any command by using etcdctl which will fail as `jq` does not exist

```bash
I have no name!@467f96a0866c:/opt/bitnami/etcd$ etcdctl get . -w json | jq .
bash: jq: command not found
```

## Some methods that i tried

I tried to install `jq` by using `install_packages` but faced with errors
```bash
$ install_packages jq
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```

I also tried building my own image by using following Dockerfile but no luck; container exists with an error:
```bash
$ cat ./Dockerfile
FROM bitnami/etcd:latest
USER root
RUN install_packages jq
```
Container logs look as follows:
```bash
$ docker build -t my-etcd-server . &&  docker run -d --name etcd-server \
    --network app-tier \
    --publish 2379:2379 \
    --publish 2380:2380 \
    --env ALLOW_NONE_AUTHENTICATION=yes \
    --env ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379 \
    my-etcd-server
[+] Building 0.0s (6/6) FINISHED                                                                            docker:orbstack
 => [internal] load build definition from Dockerfile                                                                   0.0s
 => => transferring dockerfile: 193B                                                                                   0.0s
 => [internal] load metadata for docker.io/bitnami/etcd:latest                                                         0.0s
 => [internal] load .dockerignore                                                                                      0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [1/2] FROM docker.io/bitnami/etcd:latest                                                                           0.0s
 => CACHED [2/2] RUN install_packages jq                                                                               0.0s
 => exporting to image                                                                                                 0.0s
 => => exporting layers                                                                                                0.0s
 => => writing image sha256:4151bf712282934cf5bd516d33a0b39d21303a2825a3451d1d971b5bf4339587                           0.0s
 => => naming to docker.io/library/my-etcd-server                                                                      0.0s
391be261abaf9a53fdfa89d85e1f751f23cbb9fb0a514b03649f09c7bf6a9d9b


$ docker logs etcd-server
etcd 12:44:06.35 INFO  ==>
etcd 12:44:06.35 INFO  ==> Welcome to the Bitnami etcd container
etcd 12:44:06.35 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 12:44:06.35 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 12:44:06.35 INFO  ==>
etcd 12:44:06.35 INFO  ==> ** Starting etcd setup **
etcd 12:44:06.36 INFO  ==> Validating settings in ETCD_* env vars..
etcd 12:44:06.36 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 12:44:06.39 INFO  ==> Initializing etcd
etcd 12:44:06.39 INFO  ==> Generating etcd config file using env variables
chown: cannot access '/opt/bitnami/etcd/conf/etcd.yaml': No such file or directory
```

### What do you see instead?

I might miss simple steps to access jq but it would be great to have access to jq within etcd as it will help for simple debugging sessions

**Comment by da-baranov** [comment]
Yesterday I experimented a lot and got a good experience with customizing Bitnami dockerfile-s. General recommendations are:
- You can safely make changes to the original Dockerfile
- Make sure that all .sh files use LF as a line break character
- Make sure the install_packages (as well as other .sh files) script is executable: `RUN chmod +x /usr/sbin/install_packages`

**Comment by buraksekili** [comment]
As suggested by @da-baranov, I cloned the repository and added `jq` to installation steps defined in Dockerfile.

For future reference, you can find the steps here:

```bash
git clone https://github.com/bitnami/containers.git
cd ./containers/bitnami/etcd/3.5/debian-12/Dockerfile
```
Then I added `jq` to `install_packages` step, you can see the git diff output
```bash
$ git diff --color-words Dockerfile
diff --git a/bitnami/etcd/3.5/debian-12/Dockerfile b/bitnami/etcd/3.5/debian-12/Dockerfile
index d4d4ddc..1ae66c1 100644
--- a/bitnami/etcd/3.5/debian-12/Dockerfile
+++ b/bitnami/etcd/3.5/debian-12/Dockerfile
@@ -23,7 +23,7 @@ ENV HOME="/" \
 COPY prebuildfs /
 SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]
 # Install required system packages and dependencies
-RUN install_packages ca-certificates curl procps
+RUN install_packages ca-certificates curl procps jq
 RUN mkdir -p /tmp/bitnami/pkg/cache/ ; cd /tmp/bitnami/pkg/cache/ ; \
     COMPONENTS=( \
       "yq-4.42.1-0-linux-${OS_ARCH}-debian-12" \
```

As far as i remember, curl was part of etcd container. It seems like it is deleted from Dockerfile.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

`curl` is used during the build process but then removed to reduce the attack surface and the number of potential CVEs. As you mention, it could be installed following the above tips.

**Comment by buraksekili** [comment]
thanks @carrodher for clarification. I am closing this issue as it is expected. Thanks again
