### ISSUE TITLE
[bitnami/postgresql] Bitnami postgresql permissions on mac m1

### ISSUE THREAD

**Issue by ledaithangdn** [bitnami/containers#63548]
### Name and Version

bitnami/postgresql:16.0.0-debian-11-r10

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. On Mac M1 docker sonoma 14.2
2. Start container with docker-compose

### What is the expected behavior?
```
postgresql 18:07:45.33 INFO  ==>
postgresql 18:07:45.33 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 18:07:45.33 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 18:07:45.33 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 18:07:45.33 INFO  ==>
postgresql 18:07:45.35 INFO  ==> ** Starting PostgreSQL setup **
postgresql 18:07:45.36 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 18:07:45.36 INFO  ==> Loading custom pre-init scripts...
postgresql 18:07:45.36 INFO  ==> Initializing PostgreSQL database...
postgresql 18:07:45.37 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 18:07:45.37 INFO  ==> Generating local authentication configuration
```
and then the container just exit with no further log

### What do you see instead?

this is the command I use to create mount volume folder. I do as this issues but it does not work, my container still stop [[bitnami/postgresql] Bitnami postgresql permissions](https://github.com/bitnami/containers/issues/42194#issuecomment-1762957961)
I see no logs error here but my container still stop
```
mkdir postgresql
sudo chown -R $USER:1001 postgresql
```

### Additional information

this is `ls -la`
```
total 196744
drwxr-xr-x   9 macos  staff       288 Mar  6 01:04 .
drwxr-xr-x   7 macos  staff       224 Mar  5 23:44 ..
drwxr-xr-x   3 macos  staff        96 Mar  5 23:57 airflow
-rw-r--r--   1 macos  staff      1718 Mar  6 01:06 docker-compose.yml
drwxrwxrwx   7 1001   1001        224 Mar  6 01:07 elasticsearch
drwxrwxrwx  10 1001   1001        320 Mar  6 01:08 kibana
-rw-r--r--   1 macos  staff  91824146 Mar  5 23:52 minikube-darwin-arm64
drwx------@  2 macos  1001         64 Mar  6 01:07 postgresql
drwxrwxrwx   2 1001   1001         64 Mar  6 00:24 redis
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by nttq1sub** [comment]
> Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.
> 
> For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
> 
> * [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
> * [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
> * [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
> * [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
> 
> These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
> 
> In the same way, please note Debian 11 was deprecated in favor of Debian 12, could you try using a more updated image? i.e `16.2.0-debian-12-r5`

@carrodher so this is the right command I should use in this case
`
sudo chown -R root:1001 docker-postgresql
`

**Comment by ledaithangdn** [comment]
@carrodher I change the tag of the image that I'm using to your propose but it still not work

**Comment by carrodher** [comment]
The group should be `0` and the user belongs to that group, by default this is how user `1001` or other random users work.
