### ISSUE TITLE
Remove deprecated node type feature

### ISSUE THREAD

**Issue by Zerpet** [bitnami/containers#63563]
### Name and Version

bitnami/rabbitmq 3.12+

### What is the problem this feature will solve?

RabbitMQ deprecated RAM nodes ([blog post announcement](https://www.rabbitmq.com/blog/2021/08/21/4.0-deprecation-announcements#removal-of-ram-nodes)). RAM nodes are removed from the codebase for RabbitMQ 4.0 https://github.com/rabbitmq/rabbitmq-server/pull/8667

### What is the feature you are proposing to solve the problem?

I propose to remove `RABBITMQ_NODE_TYPE` and related logic from `bitnami/rabbitmq` container. We could also remove "stats" node type from the container. I'm not sure I fully understood the purpose of stats nodes, since they are not clustered, and they cannot collect stats from "queue disc" or "queue ram" nodes. The only node type should be `disc`.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
