### ISSUE TITLE
OpenLDAP containers have password hashing modules outside normal library directory, leading to inability to use modern hashing

### ISSUE THREAD

**Issue by denefoster** [bitnami/containers#63605]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run container, attempt to enable pw-sha2 module:
```
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: pw-sha2
```

### What is the expected behavior?

The module loads, and SSHA-256 and onwards is available for use

### What do you see instead?

The module fails to load, meaning users are stuck with SSHA, which is a long deprecated and insecure hashing algorithm.

### Additional information

the hashing libraries are in the image, in `/opt/bitnami/openldap/libexec` while all of the in-use library files live in `/opt/bitnami/openldap/lib`. Just need to copy the hashing libs into the same folder.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by mistial-dev** [comment]
@denefoster My pull request #70398 handles this in a different way that's a bit more compatible, and doesn't require the pw-sha2 module.
