### ISSUE TITLE
Discrepancy between Amazon ECR Public Gallery and Docker Hub

### ISSUE THREAD

**Issue by artursmolarek** [bitnami/containers#63705]
### Name and Version

bitnami/redis:6.2.14-debian-11-r22

### What architecture are you using?

None

### What steps will reproduce the bug?

Run:

```
docker pull bitnami/redis:6.2.14-debian-11-r22
```

and:

```
docker pull public.ecr.aws/bitnami/redis:6.2.14-debian-11-r22
```

### What is the expected behavior?

Both commands pulls the Docker image without any issues.

### What do you see instead?

```
docker pull bitnami/redis:6.2.14-debian-11-r22
Error response from daemon: manifest for bitnami/redis:6.2.14-debian-11-r22 not found: manifest unknown: manifest unknown
```

```
docker pull public.ecr.aws/bitnami/redis:6.2.14-debian-11-r22
6.2.14-debian-11-r22: Pulling from bitnami/redis
c568130f253e: Pull complete
Digest: sha256:2a0712ac779879f96a60c2d8414351f5841de72ddcd79ba617a821de1a71f6c1
Status: Downloaded newer image for public.ecr.aws/bitnami/redis:6.2.14-debian-11-r22
public.ecr.aws/bitnami/redis:6.2.14-debian-11-r22
```

### Additional information

Which repository should be used for production deployments?

Helm chart [refers](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#L101) to `docker.io`, but as you can see it doesn't contain the newest version of the docker image (comparing to the AWS ECR).

**Comment by jkotiuk** [comment]
Another example for redis-cluster:

```
docker pull bitnami/redis-cluster:6.2.14-debian-11-r25
Error response from daemon: manifest for bitnami/redis-cluster:6.2.14-debian-11-r25 not found: manifest unknown: manifest unknown
```


```
docker pull public.ecr.aws/bitnami/redis-cluster:6.2.14-debian-11-r25
6.2.14-debian-11-r25: Pulling from bitnami/redis-cluster
```

**Comment by carrodher** [comment]
Revisions could differ between registries, please note a container image is composed of a registry, repository and tag. Changing one of them (i.e. the registry) doesn't guarantee the image will be present there using the same tag.

Having said that, I checked the container image used by the latest Helm chart and the same tag is present in both registries:
```console
$ docker pull docker.io/bitnami/redis:7.2.4-debian-12-r9
7.2.4-debian-12-r9: Pulling from bitnami/redis
f7b061e2cdcc: Pull complete
Digest: sha256:c1843bcdb2f413d2aff67adbaf482082673cd40ec602fa9fefad74ec685cb813
Status: Downloaded newer image for bitnami/redis:7.2.4-debian-12-r9
docker.io/bitnami/redis:7.2.4-debian-12-r9

$ docker pull public.ecr.aws/bitnami/redis:7.2.4-debian-12-r9
7.2.4-debian-12-r9: Pulling from bitnami/redis
3ac4b43d1374: Pull complete
Digest: sha256:413ba6ab7104ced40c1047451680f0679b235684a14a7db4a05a5990ff4e1e67
Status: Downloaded newer image for public.ecr.aws/bitnami/redis:7.2.4-debian-12-r9
public.ecr.aws/bitnami/redis:7.2.4-debian-12-r9
```

**Comment by artursmolarek** [comment]
Thanks for the quick reply @carrodher. 

What is your recommendation regarding staying up to date with Docker images? I assumed that newer versions of the images are better because they contain security fixes, but I'm not sure if the Helm chart follows every update of the Docker image. What would you suggest?

I can see three options here:
* use the version defined in Heml chart (even if there is a newer version available in Registry),
* rely on Docker Hub latest version
* rely on ECR latest version

**Comment by carrodher** [comment]
Helm chart and container images are released under certain circumstances (new upstream app version, security vulnerabilities, changes in container logic, changes in Helm chart logic, etc). Some circumstances will trigger a new Helm chart release bundling the latest container image, i.e. a new upstream app version or security vulnerabilities.

Replacing the `image.tag` of a specific Helm chart with a different one will produce a different Helm chart from the one published by our automated CI/CD pipeline; therefore you will end up with a Helm chart that has not been tested. It will probably work without issues, but we can't guarantee that.

Another option is to use rolling tags instead of immutable tags, but in that case, you will need to evaluate the pros and cons of having the latest versions versus a reproducible environment, see https://docs.bitnami.com/tutorials/understand-rolling-tags-containers.

**Comment by artursmolarek** [comment]
Based on what you've explained, it sounds like we should use the version specified in the helm chart for production, even if there are newer versions available in a docker registry. Thank you so much for your help.
