### ISSUE TITLE
Discourse: wrong URL when using DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER

### ISSUE THREAD

**Issue by frafra** [bitnami/containers#6370]
### Name and Version

bitnami/discourse:2

### What steps will reproduce the bug?

1. Set `DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER` to a port different 80 (for example: 3000)
2. Open Discourse
3. Favicons are not loading

### What is the expected behavior?

All the URLs should be correct

### What do you see instead?

This URL is generated `http://localhost:3000/svg-sprite/localhost:3000/svg-1-30b1f89de080fd055033ae114fdf69742a9bcc68.js` instead of `http://localhost:3000/svg-sprite/localhost/svg-1-30b1f89de080fd055033ae114fdf69742a9bcc68.js`

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#user-content-community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by xn3cr0nx** [comment]
Hey @frafra, did you manage to find a solution?

**Comment by frafra** [comment]
@xn3cr0nx I would have written here already :)
I am just trying to use the official tool to build the images, which is rather problematic, but better than have no support at all.
