### ISSUE TITLE
[bitnami/cassandra] Cassandra broadcast_rpc_address via ENV Settings

### ISSUE THREAD

**Issue by tobiasbhn** [bitnami/containers#63704]
### Name and Version

bitnami/cassandra:4.1.3

### What is the problem this feature will solve?

Currently I can configure many settings using the environment variables. This does work fine. But this is not possible for all Cassandra settings. One of them is the `broadcast_rpc_address`, which ist not included in the environmental setup.

### What is the feature you are proposing to solve the problem?

Currently, the `broadcast_rpc_address` will be automatically set to the content of the `host ` variable
https://github.com/bitnami/containers/blob/65e6858935df67a71fe056538476e42abf405cbf/bitnami/cassandra/4.1/debian-12/rootfs/opt/bitnami/scripts/libcassandra.sh#L405
which in turn will be 127.0.0.1 or the docker containers ip, depending on the state of the `CASSANDRA_ENABLE_REMOTE_CONNECTIONS` environment variable. I would like to set this value manually to reflect the public ip of the host machine.

I cannot use the `CASSANDRA_HOST` variable, as this value will also be used for the cassandra setting `listen_address`, which should not be the hosts public ip but the container ip. 

### What alternatives have you considered?

My Configuration does work fine if I use the configuration file `cassandra.yaml` as described in the containers readme. Nevertheless, I would prefer the way of configuring the container using environmental variables, including the `broadcast_rpc_address`.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
