### ISSUE TITLE
[bitnami/redis-exporter] not detailed documentation about environment variables

### ISSUE THREAD

**Issue by sinawic** [bitnami/containers#63747]
### Name and Version

bitnami/redis-exporter

### What architecture are you using?

amd64

### What steps will reproduce the bug?

for bitnami/redis-exporter container
i could fine no info about the env vars that i can pass to the container
which port would be exposed
i mean i can detect some info using docker inspect but not really enough

### What is the expected behavior?

best option would be to put a docker compose file or snippet
with available env vars and ports and ..
like most of your other great containers

### What do you see instead?

i can see the docker run command
but there is no docs about how should i define my redis instance info (host address, port, password) ..

**Comment by migruiz4** [comment]
Hi @sinawic,

As mentioned in the [README](https://github.com/bitnami/containers/blob/main/bitnami/redis-exporter/README.md#what-is-redis-exporter), the redis-exported packaged at `bitnami/redis-exporter` is a compiled binary using https://github.com/oliver006/redis_exporter as source.

This image does not include any additional logic from our side, so configuration is performed using the same methods as the upstream binary. You can either provide configuration via env variables or CLI args using the upstream documentation: https://github.com/oliver006/redis_exporter?tab=readme-ov-file#command-line-flags

**Comment by sinawic** [comment]
hey thanks for the reply
sorry but I have to let you know that I could not find any documentation stating the image is using oliver006/redis_exporter
in the mentioned readme file

**Comment by migruiz4** [comment]
Hi @sinawic,

Sorry for the misunderstanding, I mean that the same environment variables depicted in [this table](https://github.com/oliver006/redis_exporter?tab=readme-ov-file#command-line-flags) can be used with `bitnami/redis_exporter` image.

Here is an example using docker to run the redis_exporter container:
`docker run --rm -it -e REDIS_ADDR=1.2.3.4 -e REDIS_USER=username -e REDIS_PASSWORD=pass bitnami/redis_exporter`

All the environment variables in the upstream project are allowed, similar to how you would use the redis_exporter binary in your local machine.

**Comment by sinawic** [comment]
thanks!
I can confirm that the env variables in the mentioned table is working just fine
ideally i think it's better if u can state the same table in the related readme file or at least state that the image is somehow related to the oliver006/redis_exporter project

**Comment by migruiz4** [comment]
I'm glad my comment helped you solve this issue.

You may have overlooked it, but the upstream table is already linked in the README under the '[Configuration](https://github.com/bitnami/containers/tree/main/bitnami/redis-exporter#configuration)' section.

>## Configuration
> Find all the configuration flags in [the redis_exporter official documentation](https://github.com/oliver006/redis_exporter#flags).

Regarding the relation between our images and the upstream project, you can find this in the header of README.md for all of our images. Usually, we document aspects that are specific to our images, such as environment variables that are exclusive to the logic we add and execution examples, and we reference upstream for application-specific settings to make sure they are always up-to-date.

># Bitnami package for Redis Exporter
>
>## What is Redis Exporter?
>
>> Redis Exporter gathers Redis&reg; metrics for Prometheus consumption.
>
> [Overview of Redis Exporter](https://github.com/oliver006/redis_exporter)
Trademarks: This software listing is packaged by Bitnami. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
