### ISSUE TITLE
 unable to execute Describe\nDETAIL in pgpool

### ISSUE THREAD

**Issue by fatjoni** [bitnami/containers#63807]
### Name and Version

bitnami/pgpool:4.4.0 && bitnami/pgpool:4.5.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Setup and add two instances replicating with rpmgr image from bitnami in primary secondary modality.
I connect hasura backend to the pgpool

### What is the expected behavior?

everything from the backend works as expected, with no errors in the pgpool

### What do you see instead?

These errors in pgpool
```
2024-03-13 16:20:47.646: [unknown] pid 145: FATAL:  unable to execute Describe
2024-03-13 16:20:47.646: [unknown] pid 145: DETAIL:  unable to get the parse message
2024-03-13 16:20:47.647: main pid 1: LOG:  reaper handler
2024-03-13 16:20:47.648: main pid 1: LOG:  reaper handler: exiting normally
2024-03-13 16:20:47.751: [unknown] pid 130: FATAL:  unable to execute Describe
2024-03-13 16:20:47.751: [unknown] pid 130: DETAIL:  unable to get the parse message
```

### Additional information

From Google search, I found this: https://www.pgpool.net/docs/latest/en/html/release-4-3-8.html which supposedly solves the problem but it seems to not be working

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
