### ISSUE TITLE
Add a primary_visibility_consensus flag to postgresql-repmgr

### ISSUE THREAD

**Issue by hillout** [bitnami/containers#63819]
### Name and Version

postgresql-repmgr:16

### What is the problem this feature will solve?

Using the configuration with two pg-0 (master), pg-1(standby) and one witness pgw-0 in the middle doesn't solve the split brain problem.

If pg-0 and pg-1 are located at different DC(1,2), while pgw-0 located at DC3. In the case of network outage between dc1 and dc2, and whilst pgw-0 can still observe both pg-0 and pg-1, it won't help. pg-1 stands to Master role, and it doesn't consider any information from the witness. 

### What is the feature you are proposing to solve the problem?

In order to change it, we can config repmgr on all node with -  `primary_visibility_consensus=true` flag [(repmgrd manual),](https://www.repmgr.org/docs/4.4/repmgrd-primary-visibility-consensus.html). And add a few `reconnect_attempts='3'` on all nodes, so pg-1 will get the info from pgw-0 before it decide to promote itself to master. In this case pg-1 will show logs: 
```
[2024-03-14 11:38:05] [NOTICE] cancelling failover as some nodes can still see the primary
[2024-03-14 11:38:05] [NOTICE] election cancelled
```
And will wait for primary.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
