### ISSUE TITLE
[bitnami/keycloak] Environment variables are being written to Java properties file which is confusing for special characters handling

### ISSUE THREAD

**Issue by PierreBeucher** [bitnami/containers#63823]
### Name and Version

bitnami/keycloak:23.0.7-debian-12-r1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Trying to run `bitnami/keycloak:23.0.7-debian-12-r1` with environment variable `KEYCLOAK_DATABASE_PASSWORD` containing special characters like

```
#very3Secret!
```

Will eventually cause the value to be plainly written in `/opt/bitnami/keycloak/conf/keycloak.conf` as:

```
db-password = #very3secret!
```

Which won't work since the value [should be escaped](https://www.keycloak.org/server/configuration#_using_special_characters_in_values). 

The bug is that _a user setting an environment variable should not have to worry about special characters_. It's expected to escape variables when using config file or bash/linux commands, but not when using environment variables. (that's actually one of the reason environment variables are used to pass such values). The hidden indirection _env var > config file > process_ breaks this assumption. 

Maybe the image could use built-in [environment variables `KC_xxx`](https://www.keycloak.org/server/configuration) instead for passwords and other related configs ?

### What is the expected behavior?

By setting environment variable `KEYCLOAK_DATABASE_PASSWORD` I expect it will be passed as-is to Keycloak process. 

### What do you see instead?

Variable is written to Keycloak config file with potentially unescaped characters.

### Additional information

For context I met this problem using the [Keycloak Helm charts](https://bitnami.com/stack/keycloak/helm) with values such as:

```yaml
externalDatabase:
  existingSecret: keycloak-config
  existingSecretPasswordKey: databasePassword
```

And a secret containing my password. Though it does not appear to be a Helm chart issue but a container image issue so I posted it here.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by dalbani** [comment]
Unstale
