### ISSUE TITLE
Link to the helm chart not working

### ISSUE THREAD

**Issue by charithakaluhendiwala** [bitnami/containers#6385]
### Name and Version

jmx-exporter:latest

### What steps will reproduce the bug?

1. go to [https://bitnami.com/stack/jmx-exporter/containers](url).
2. click the link in "Do you want to move your container to a Kubernetes infrastructure? Check out our [Helm charts](https://bitnami.com/stack/jmx-exporter/helm)."

### What is the expected behavior?

I think this link there to forward us to  jmx-exporter helm chart or how to create an one.

### What do you see instead?

redirect to the jmx-exporter main page.

### Additional information

How to find a way to install JMX-exporter with Node port.. [sorry I'm new to this.]

**Comment by rafariossaa** [comment]
Hi, I am sorry for the noise.
You can find information on the `jmx-exporter` container [here](https://github.com/bitnami/containers/tree/main/bitnami/jmx-exporter).
This container, as it is a exporter, doesn't have a chart of its own. 
However, it is used in several charts of [our chart catalog](https://github.com/bitnami/charts/tree/master/bitnami) (tomcat, kafka, sonarqube).
If  you are new to this, I would suggest you to look to the code of those charts and see you can use it in you use case.
