### ISSUE TITLE
/opt/bitnami/scripts/openldap/entrypoint.sh: line 23: exec: --: invalid option exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]

### ISSUE THREAD

**Issue by Deepakganigerupgrad** [bitnami/containers#63862]
### Name and Version

bitnami/openldap

### What architecture are you using?

None

### What steps will reproduce the bug?

entrypoint.sh
```bash
#!/bin/bash
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

# Load libraries
. /opt/bitnami/scripts/liblog.sh

if [[ "$1" = "/opt/bitnami/scripts/openldap/run.sh" ]]; then
    info "** Starting LDAP setup **"
    /opt/bitnami/scripts/openldap/setup.sh
    info "** LDAP setup finished! **"
fi

echo ""
echo "Received command: $@"
echo "Executing command: exec $@"
exec "$@"
```

### What do you see instead?
```
/opt/bitnami/scripts/openldap/entrypoint.sh: line 23: exec: --: invalid option exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]
```

**Comment by Deepakganigerupgrad** [comment]
Received command: --copy-service
Executing command: exec --copy-service
/opt/bitnami/scripts/openldap/entrypoint.sh: line 23: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]

**Comment by Deepakganigerupgrad** [comment]
any update?

**Comment by juan131** [comment]
Hi @Deepakganigerupgrad 

I'm afraid I'm not sure what's your issue, I'm assuming that you're passing some ARGS (see [docker run reference](https://docs.docker.com/reference/cli/docker/container/run)) while executing the OpenLDAP container but I'd like you to confirm so. Could you please share the excat command you're using to deploy the OpenLDAP container? 

Did you try following the "get started" guide below?

- https://github.com/bitnami/containers/tree/main/bitnami/openldap#using-the-command-line

**Comment by Deepakganigerupgrad** [comment]
Hi @juan131 ,
Above issue is resolved but i am getting below error message in pod, when i am passing       
securityContext:
        runAsNonRoot: true ,in my deployment.yaml file. i am passing this value because pod should use user assigned by ocp not default user which is 1001. could you please help me here

error:
05:40:47.90 INFO ==> ** Starting LDAP setup **
/opt/bitnami/scripts/openldap/setup.sh: line 102: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/setup.sh: line 103: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/setup.sh: line 104: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
05:40:47.92 INFO ==> Validating settings in LDAP_* env vars
05:40:47.93 INFO ==> Initializing OpenLDAP...
05:40:48.00 INFO ==> Creating LDAP online configuration
05:40:48.00 INFO ==> Creating slapd.ldif

**Comment by juan131** [comment]
Hi @Deepakganigerupgrad 

I'm glad you were able to solve the issue.

Could you please open a new issue describing the problem with the security context? We should stick to the original issue topic to avoid confusion for other users that may use it as a reference. Thanks in advance.
