### ISSUE TITLE
Failures writing to mounted Azure file share

### ISSUE THREAD

**Issue by dlynch33** [bitnami/containers#63877]
### Name and Version

bitnami/drupal:10.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm attempting to run Bitnami Drupal 10.2.4 Docker container on Azure Containers Apps.  I've mounted an Azure storage account file share as a volume, in order to persist the `sites`, `modules`, `themes`, and `profiles` directories, as suggested by the `DRUPAL_DATA_TO_PERSIST` env var.
The deployment completes successfully and the Drupal site comes up, with files having been written successfully to the `sites` directory in the Azure file share.  However, post-deployment it seems that Drupal can read but not write to the Azure file share.  I see errors like this in the Drupal logs:

    The file permissions could not be set on assets://css/css_vLZKA5reEsk2zLZRp346p9930aWddLyoyqjrCqWJBZE.css.gz.

And, when I try to add a new module to via Drupal Admin/Extend page, I get errors like this:

    Warning: chmod(): Operation not permitted in Drupal\Component\PhpStorage\MTimeProtectedFastFileStorage->save() (line 76 of core/lib/Drupal/Component/PhpStorage/MTimeProtectedFastFileStorage.php).
    Warning: chmod(): Operation not permitted in Drupal\Component\PhpStorage\FileStorage->createDirectory() (line 117 of core/lib/Drupal/Component/PhpStorage/FileStorage.php).
    Warning: touch(): Utime failed: Operation not permitted in Drupal\Component\PhpStorage\MTimeProtectedFastFileStorage->save() (line 100 of core/lib/Drupal/Component/PhpStorage/MTimeProtectedFastFileStorage.php).

This is what the `/opt/bitnami/drupal` directory looks like:

    total 304
    -rw-rw-r--  1 root root     87 Mar  9 15:14 INSTALL.txt
    -rw-rw-r--  1 root root  18092 Mar  9 15:14 LICENSE.txt
    -rw-rw-r--  1 root root   3205 Mar  9 15:14 README.md
    -rw-rw-r--  1 root root    312 Mar 15 19:46 autoload.php
    -rw-rw-r--  1 root root   3701 Mar 15 19:46 composer.json
    -rw-rw-r--  1 root root 241111 Mar 15 19:46 composer.lock
    drwxrwxr-x 12 root root   4096 Mar  9 15:50 core
    -rw-rw-r--  1 root root   1495 Mar  9 15:14 example.gitignore
    -rw-rw-r--  1 root root    549 Mar  9 15:14 index.php
    drwxrwxr-x  2 root root   4096 Mar  9 15:50 licenses
    lrwxrwxrwx  1 1001 root     23 Mar 15 21:01 modules -> /bitnami/drupal/modules
    lrwxrwxrwx  1 1001 root     24 Mar 15 21:01 profiles -> /bitnami/drupal/profiles
    -rw-rw-r--  1 root root   2027 Mar  9 15:14 robots.txt
    lrwxrwxrwx  1 1001 root     21 Mar 15 21:01 sites -> /bitnami/drupal/sites
    lrwxrwxrwx  1 1001 root     22 Mar 15 21:01 themes -> /bitnami/drupal/themes
    -rw-rw-r--  1 root root    804 Mar  9 15:14 update.php
    drwxrwxr-x  1 root root   4096 Mar 15 19:46 vendor
    -rw-rw-r--  1 root root   4039 Mar  9 15:14 web.config

Do I need to run this container as root in order for it to have write access to the Azure file shares?  Or, might there be other/better options available?  Appreciate any advice, suggestions.

### What is the expected behavior?

Drupal admin user can install Drupal modules.

### What do you see instead?

Module install fails - see errors above.

**Comment by dlynch33** [comment]
Poking around a bit, if I SSH into the running Docker container and attempt to execute the "postunpack.sh" script, which creates directories, etc. on the Azure-host /bitnami/drupal mount, I see permissions errors:

    $ /opt/bitnami/scripts/drupal/postunpack.sh
    drupal 20:06:46.99 INFO  ==> Configuring file permissions for Drupal
    chmod: changing permissions of '/opt/bitnami/drupal/modules': Operation not permitted
    chmod: changing permissions of '/opt/bitnami/drupal/modules/contrib': Operation not permitted
    chmod: changing permissions of '/opt/bitnami/drupal/modules/contrib/devel': Operation not permitted
    chmod: changing permissions of '/opt/bitnami/drupal/modules/contrib/devel/.ddev': Operation not permitted
    chmod: changing permissions of '/opt/bitnami/drupal/modules/contrib/devel/config': Operation not permitted
    chmod: changing permissions of '/opt/bitnami/drupal/modules/contrib/devel/config/install': Operation not permitted
    ...

I suppose this is not too significant since this script is run by at build time (via Dockerfile RUN entry), so it's running on the local filesystem within the container, before the Azure volume is mounted.

The `/opt/bitnami/scripts/drupal/setup.sh` script, called via entrypoint.sh seems to be what copies the files to the Azure volume (via persist_app).  If I run this directly from the container shell, it completes without logging any errors to the console, but does not copy any files to a new/empty Azure file share:

    $ /opt/bitnami/scripts/drupal/setup.sh
    drupal 20:43:53.37 WARN  ==> The Drupal configuration file '/opt/bitnami/drupal/sites/default/settings.php' is not writable. Configurations based on environment variables will not be applied for this file.
    drupal 20:43:53.50 INFO  ==> Trying to connect to the database server
    drupal 20:43:53.56 INFO  ==> Configuring file permissions for Drupal
    drupal 20:43:53.57 INFO  ==> Installing Drupal site
   $

Finally, if I extend the Docker image and set the "USER 0" (root), then the Azure file-system does appear to get set up correctly.  But, I still get the same permissions-realted errors while attempting to add a module on the Drupal Admin/Extend page.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by dlynch33** [comment]
Hi Carlos, Thanks for your notes - appreciate your help.  The links on use of non-root containers are helpful, and I am definitely hoping to be able get my Drupal instance running as non-root user.

I'm struggling with the specifics though.  It seems that all of the local files, and files on the mounted Azure file share are owned by either root or 1001 user, and root group:

    $ ls -l /opt/bitnami/drupal
    total 296
    -rw-rw-r--  1 root root     87 Mar 18 18:15 INSTALL.txt
    -rw-rw-r--  1 root root  18092 Mar 18 18:15 LICENSE.txt
    -rw-rw-r--  1 root root   3205 Mar 18 18:15 README.md
    -rw-rw-r--  1 root root    312 Mar 18 18:15 autoload.php
    -rw-rw-r--  1 root root   3625 Mar 18 18:15 composer.json
    -rw-rw-r--  1 root root 229768 Mar 18 18:15 composer.lock
    drwxrwxr-x 12 root root   4096 Mar 18 19:30 core
    -rw-rw-r--  1 root root   1495 Mar 18 18:15 example.gitignore
    -rw-rw-r--  1 root root    549 Mar 18 18:15 index.php
    drwxrwxr-x  2 root root   4096 Mar 18 19:30 licenses
    lrwxrwxrwx  1 1001 root     23 Mar 19 15:26 modules -> /bitnami/drupal/modules
    lrwxrwxrwx  1 1001 root     24 Mar 19 15:26 profiles -> /bitnami/drupal/profiles
    -rw-rw-r--  1 root root   2027 Mar 18 18:15 robots.txt
    lrwxrwxrwx  1 1001 root     21 Mar 19 15:26 sites -> /bitnami/drupal/sites
    lrwxrwxrwx  1 1001 root     22 Mar 19 15:26 themes -> /bitnami/drupal/themes
    -rw-rw-r--  1 root root    804 Mar 18 18:15 update.php
    drwxrwxr-x 29 root root   4096 Mar 18 19:30 vendor
    -rw-rw-r--  1 root root   4039 Mar 18 18:15 web.config

    $ ls -l /bitnami
    total 0
    drwxrwxrwx 2 root root 0 Mar 18 20:41 drupal

    $ ls -l /bitnami/drupal
    total 0
    drwxrwxrwx 2 root root 0 Mar 19 13:58 sites

    $ ls -l /bitnami/drupal/sites
    total 10
    -rwxrwxrwx 1 root root  515 Mar 19 13:58 README.txt
    drwxrwxrwx 2 root root    0 Mar 19 13:58 default
    -rwxrwxrwx 1 root root  310 Mar 19 13:58 development.services.yml
    -rwxrwxrwx 1 root root 5586 Mar 19 13:58 example.settings.local.php
    -rwxrwxrwx 1 root root 2358 Mar 19 13:58 example.sites.php

    $ ls -l /bitnami/drupal/sites/default
    total 81
    -rwxrwxrwx 1 root root  9180 Mar 19 13:58 default.services.yml
    -rwxrwxrwx 1 root root 36101 Mar 19 13:58 default.settings.php
    drwxrwxrwx 2 root root     0 Mar 19 13:58 files
    -rwxrwxrwx 1 root root 36754 Mar 19 13:58 settings.php

Files under the share (i.e. under /bitnami/drupal) were added by the entrypoint.sh script, after the volume is mounted, and the user has been switched to 1001.  But, they're still owned by root/root - I'm not sure how that happens (I'm not a Linux SME).  Is this an issue?  I'm guessing that root owning these directories and files is causing issues such as the chmod command failing when a Drupal admin user attempts to add a module.

Can you point me to any guidance on how these file-system permissions should be set to allow running the site, including administrative operations, under user 1001?

I'm not sure if attempting to run this using Azure Container Apps (which doesn't support docker-compose) and Azure file share is adding to the difficulties here.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by benen** [comment]
Hi @dlynch33, were you able to solve this issue? I'm just after encountering it also even though I'm not using the bitnami containers.

**Comment by dlynch33** [comment]
Hi @benen, Apologies for the delay getting back to you - probably too late now.  But, for what its worth, we were able to solve this by setting some mount options on the Azure file share in our container app:

    mountOptions = "dir_mode=0777,file_mode=0777,uid=1001,gid=1001,mfsymlinks"

References:
* https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-terraform
* https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/storage/mountoptions-settings-azure-files?source=recommendations
