### ISSUE TITLE
Multi-platform `kubectl` in public.ecr repository

### ISSUE THREAD

**Issue by dumitraand** [bitnami/containers#63876]
### Name and Version

bitnami/kubectl

### What is the problem this feature will solve?

The [public ECR repository](https://gallery.ecr.aws/bitnami/kubectl) storing bitnami/kubectl image does not currently support ARM images. 

Only docker hub repository seem to have the multi-platform image available.

This will allow being able to pull this image through an `AWS Private Link` inside the VPC, on private machines, and not have to go through the NAT Gateway to connect to docker-hub and pull the image, which would result in an increased bill for data transfer.

### What is the feature you are proposing to solve the problem?

Publish the ARM-version of kubectl to the public ECR repository as well, if possible. 

This is purely a **convenience** request.

Thank you very much!

### What alternatives have you considered?

- Having a pull-through cache to pull the docker-hub image
- Building my own image based on bitnami/kubectl to be able to use it inside private machines

**Comment by carrodher** [comment]
Unfortunately, at this moment, multi-arch containers are only available in DockerHub.
In the short term, there are no plans to distribute them in any other public place apart from DockerHub and the enterprise version of Bitnami, the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
