### ISSUE TITLE
[bitnami/openldap] root user issue

### ISSUE THREAD

**Issue by Deepakganigerupgrad** [bitnami/containers#63893]
### Name and Version

bitnami/openldap

### What architecture are you using?

None

### What steps will reproduce the bug?

I was able to deploy an OpenLDAP pod using the Bitnami OpenLDAP image https://bitnami.com/stack/openldap/containers. The deployment created a non-root user with the ID 1001 to perform tasks. However, upon adding `securityContext: runAsNonRoot: true` to the deployment YAML file, the /opt/bitnami/openldap/sbin/slappasswd command is showing a permission denied error. This command is accessible only to the non-root user 1001 and root. The non-root user assigned by OpenShift Container Platform (OCP) cannot access or modify permissions.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by Deepakganigerupgrad** [comment]
Hi @carrodher 
Above issue is resolved but i am getting below error message in pod, when i am passing       
securityContext:
        runAsNonRoot: true ,in my deployment.yaml file. i am passing this value because pod should use user assigned by ocp not default user which is 1001. could you please help me here

error:
05:40:47.90 INFO ==> ** Starting LDAP setup **
/opt/bitnami/scripts/openldap/setup.sh: line 102: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/setup.sh: line 103: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/setup.sh: line 104: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
05:40:47.92 INFO ==> Validating settings in LDAP_* env vars
05:40:47.93 INFO ==> Initializing OpenLDAP...
05:40:48.00 INFO ==> Creating LDAP online configuration
05:40:48.00 INFO ==> Creating slapd.ldif

**Comment by javsalgar** [comment]
Hi,

Could you check if the container has group root? If that's the case it should be able to execute the command

**Comment by Deepakganigerupgrad** [comment]
in my case, pod should use non root user which is assigned by ocp runAsNonRoot: true.

**Comment by rafariossaa** [comment]
Could you check which group is using ? `runAsNonRoot: true` sets a random user ID but should not change the group.

You can emulate this using docker

Using user and group `5000` (a random one)
```
$ docker run --rm  -it --user 5000:5000 bitnami/openldap
 13:07:37.68 INFO  ==> ** Starting LDAP setup **
 13:07:37.74 INFO  ==> Validating settings in LDAP_* env vars
 13:07:37.76 INFO  ==> Initializing OpenLDAP...
 13:07:37.77 INFO  ==> Creating LDAP online configuration
 13:07:37.78 INFO  ==> Creating slapd.ldif
/opt/bitnami/scripts/libopenldap.sh: line 271: /opt/bitnami/openldap/share/slapd.ldif: Permission denied
```
Just changing the user ID to `5000` it starts.
```

15:07 $ docker run --rm  -it --user 5000 bitnami/openldap
 13:08:15.29 INFO  ==> ** Starting LDAP setup **
 13:08:15.35 INFO  ==> Validating settings in LDAP_* env vars
 13:08:15.36 INFO  ==> Initializing OpenLDAP...
 13:08:15.37 INFO  ==> Creating LDAP online configuration
 13:08:15.38 INFO  ==> Creating slapd.ldif
 13:08:15.42 INFO  ==> Starting OpenLDAP server in background
 13:08:16.43 INFO  ==> Configure LDAP credentials for admin user
 13:08:16.45 INFO  ==> Adding LDAP extra schemas
 13:08:16.49 INFO  ==> Creating LDAP default tree
 13:08:17.58 INFO  ==> ** LDAP setup finished! **

 13:08:17.64 INFO  ==> ** Starting slapd **
66290441.270c7242 0x7f001064f740 @(#) $OpenLDAP: slapd 2.6.7 (Apr  4 2024 09:59:11) $
        @b9a1751ddd11:/bitnami/blacksmith-sandox/openldap-2.6.7/servers/slapd
66290441.2805d490 0x7f001064f740 slapd starting
^C66290443.23fa5fd5 0x7effd00b96c0 daemon: shutdown requested and initiated.
66290443.23fe6e51 0x7effd00b96c0 slapd shutdown: waiting for 0 operations/tasks to finish
66290443.249b0dd3 0x7f001064f740 slapd stopped.
```
