### ISSUE TITLE
support opensearch as magento search engine option

### ISSUE THREAD

**Issue by vtkstef** [bitnami/containers#63907]
### Name and Version

bitnami/magento:2.4.6

### What is the problem this feature will solve?

provision Magento with OpenSearch specific setup options

### What is the feature you are proposing to solve the problem?

I have a PR to support it but I am not allowed to push it
```console
$ git push origin --set-upstream magento-add-opensearch-as-a-search-engine-option
ERROR: Permission to bitnami/containers.git denied to vtkstef.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### What alternatives have you considered?

elasticsearch but its licensing change makes it a problematic choice

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, following the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) should be enough. Could you please try again following that process?

**Comment by vtkstef** [comment]
just to get an idea what is the usual turn around time on PR reviews?

**Comment by vtkstef** [comment]
i hope you all had a restful easter vacation. when will the two week old PR be reviewed

**Comment by vtkstef** [comment]
@carrodher any updates on the PR review timeline?

**Comment by carrodher** [comment]
It should be reviewed soon, sorry for the delay

**Comment by vtkstef** [comment]
Ping @carrodher
