### ISSUE TITLE
bitnami/elasticsearch:8.12.2 arm64 image failed to run

### ISSUE THREAD

**Issue by hanlu109** [bitnami/containers#63916]
### Name and Version

bitnami/elasticsearch:8.12.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. `docker pull bitnami/elasticsearch:8.12.2`
2. `docker run -itd bitnami/elasticsearch:8.12.2`
3. container exited with error message: "could not find java in ES_JAVA_HOME at /opt/bitnami/java/bin/java"

### What do you see instead?
```
elasticsearch 09:56:16.70 INFO  ==> 
elasticsearch 09:56:16.71 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 09:56:16.71 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 09:56:16.71 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
elasticsearch 09:56:16.71 INFO  ==> 
elasticsearch 09:56:16.72 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 09:56:16.75 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch 09:56:16.75 WARN  ==> ELASTICSEARCH_NODE_ROLES will be ignored and Elasticsearch will asume all different roles.
elasticsearch 09:56:16.76 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 09:56:16.77 INFO  ==> Setting default configuration
elasticsearch 09:56:16.80 INFO  ==> Configuring Elasticsearch cluster settings...
could not find java in ES_JAVA_HOME at /opt/bitnami/java/bin/java
```

**Comment by carrodher** [comment]
We're not able to reproduce the issue, everything works as expected by running `docker run -itd bitnami/elasticsearch:8.12.2`

**Comment by hanlu109** [comment]
Your container runs on arm64 platform, right? My amd64 version 8.12.2 has no issue.  Only arm64 version has this issue. If you could not reproduce the issue, I will try to to find another arm64 system to try again. Thanks.

**Comment by hanlu109** [comment]
Thanks very much. I got another arm system and tried again. The image works normally. So the issue is caused by previous arm system.
