### ISSUE TITLE
Add multi master replication

### ISSUE THREAD

**Issue by tibz7** [bitnami/containers#63943]
### Name and Version

bitnami/percona-mysql:latest

### What is the problem this feature will solve?

It would be good to have multi-master replication, right now only the master/slave replication seems to work

### What is the feature you are proposing to solve the problem?

having an other switch or tweaking the image in order to have master-master replication working

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
