### ISSUE TITLE
Rotate credentials database

### ISSUE THREAD

**Issue by morganbasset** [bitnami/containers#63969]
### Name and Version

bitnami/redmine:5.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy Redmine on K8S with database credentials from secret
2. Change password to connect to the database
3. Update password in K8S secret

### What is the expected behavior?

I would like that the database password be updated

### What do you see instead?

Initial password is in the database.yml file, even if the env var is set to the new password.

Is it possible to refresh database connection from env var at each start ?
Thanks in advance

**Comment by jotamartos** [comment]
Hi @morganbasset,

As you can see in this script, if the /bitnami/redmine directory exists, it will use the existing information/configuration file instead of creating a new database and initializing the app from scratch

https://github.com/bitnami/containers/blob/main/bitnami/redmine/5/debian-12/rootfs/opt/bitnami/scripts/libredmine.sh#L133

If you want to use new credentials, you will need to edit this file manually.

**Comment by morganbasset** [comment]
Hi, I came with a cleaner solution by using init-container

`  initContainers:
    - name: db-creds-refresh
      image: registry.in.ac-lille.fr/dockerhub-proxy/mikefarah/yq:4.43.1
      imagePullPolicy: Always
      command: ['/bin/sh', '-c', '/pre-init.sh']
      volumeMounts:
        - name: "redmine-configmap"
          mountPath: "/pre-init.sh"
          subPath: pre-init.sh
        - name: redmine-data
          mountPath: /bitnami/redmine
      env:
      - name: REDMINE_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: vault-db-secret`

`apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-configmap
data:
  pre-init.sh: |-
    # REPLACE DATABASE PASSWORD
    if [ -f "/bitnami/redmine/config/database.yml" ]; then
      yq e -i ".production.password = \"${REDMINE_DATABASE_PASSWORD}\"" /bitnami/redmine/config/database.yml
    else
      echo "Persistent volume not initialized"
    fi
`

**Comment by andresbono** [comment]
Thank you so much for sharing your solution ❤️. Other users will benefit from your contribution.
