### ISSUE TITLE
[bitnami/postgresql] include timescaledb extension

### ISSUE THREAD

**Issue by jcpunk** [bitnami/containers#64050]
### Name and Version

bitnami/postgresql:16

### What is the problem this feature will solve?

Folks looking to manage time series information along side traditional RDBMs data will have a simple way to do this.

### What is the feature you are proposing to solve the problem?

Include the timescaledb extension for postgresql.

### What alternatives have you considered?

Spinning my own container.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kellenanker7** [comment]
@carrodher commenting here not specifically about `timescaledb`, but about extensions in general. Are there official docs anywhere for adding extensions, specifically when using the `postresql` helm chart? I'm having difficulty adding the `ip4r` extension, for example, to the chart (don't need to solve for that specific use case in this issue, but figured an example may help).

I will happily open a new issue if you'd prefer to discuss there.
