### ISSUE TITLE
[pgpool] How to assign weights to  PGPOOL_BACKEND_NODES

### ISSUE THREAD

**Issue by LRagji** [bitnami/containers#64116]
### Name and Version

bitname

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using ` PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432` i am not able to set weights to individual backends ? is there a specific format?

### What do you see instead?

I should be able to assign weights to my backend servers

### Additional information

Maybe this is missing documentation bug then real code defect

**Comment by LRagji** [comment]
ok found it after little experimenting use the same env variable separated by ':' `PGPOOL_BACKEND_NODES=0:postgres_primary:5432:0,1:pg-readers:5432:1` primary is assigned weight of 0 and readers assigned weight of 1

**Comment by XiangyuZhang-G** [comment]
You saved me! Thank you!
