### ISSUE TITLE
ldif_read_record: include file:///opt/bitnami/openldap/etc/openldap/schema/core.ldif failed

### ISSUE THREAD

**Issue by janekmichalik** [bitnami/containers#64120]
### Name and Version

bitnami/openldap:2.6.7-debian-11-r19

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Its happening within k8s pod, I don't have 1:1 reproduction steps.

### What is the expected behavior?

The startup is working.

### What do you see instead?

```console
$ kubectl logs openldap-7b7778dfb-dd7hm
 14:04:15.22 INFO  ==> ** Starting LDAP setup **
 14:04:15.44 INFO  ==> Validating settings in LDAP_* env vars
 14:04:15.62 INFO  ==> Initializing OpenLDAP...
 14:04:15.63 DEBUG ==> Ensuring expected directories/files exist...
 14:04:15.73 INFO  ==> Creating LDAP online configuration
ldif_read_record: include file:///opt/bitnami/openldap/etc/openldap/schema/core.ldif failed
```

The last working version in my case is `bitnami/openldap:2.6.3-debian-11-r63`, each next version fails for me.

### Additional information

Its using path `file:///opt/bitnami/openldap/etc/openldap/schema/core.ldif`, while the `core.ldif` file is located under `file:///opt/bitnami/openldap/etc/schema/core.ldif`, the extra subdirectory `openldap` is being added to the path.

From container:
```
I have no name!@d803123ea910:/$ cat /opt/bitnami/scripts/libopenldap.sh
...
########################
# Create slapd.ldif
# Globals:
#   LDAP_*
# Arguments:
#   None
# Returns:
#   None
#########################
ldap_create_slapd_file() {
    info "Creating slapd.ldif"
    cat > "${LDAP_SHARE_DIR}/slapd.ldif" << EOF
#
# See slapd-config(5) for details on configuration options.
# This file should NOT be world readable.
#

...

#
# Schema settings
#

dn: cn=schema,cn=config
objectClass: olcSchemaConfig
cn: schema

include: file:///opt/bitnami/openldap/etc/schema/core.ldif
...
```
here the location is set properly, but going to `${LDAP_SHARE_DIR}/slapd.ldif` gives:

```
I have no name!@d803123ea910:/$ cat /opt/bitnami/openldap/share/slapd.ldif
#
# See slapd-config(5) for details on configuration options.
# This file should NOT be world readable.
#
dn: cn=config
objectClass: olcGlobal
cn: config
#
#
...
include: file:///opt/bitnami/openldap/etc/openldap/schema/core.ldif
...
```
here the extra `openldap` subdirectory is present

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
