### ISSUE TITLE
cassandra-exporter Security Vulnerabilities found by Microsoft Defender

### ISSUE THREAD

**Issue by khshah6** [bitnami/containers#64121]
### Name and Version

bitnami/cassandra-exporter:2.3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Upload image to ACR with [Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/container-registry/scan-images-defender) enabled.

### What is the expected behavior?

no vulnerabilities detected

### What do you see instead?

Many vulnerabilities (with recommended remediations) were detected. Listed in attached [spreadsheet](https://docs.google.com/spreadsheets/d/1Qyjr11vXH-d9hytTzk7h6Zj5AIPKyiSpU_6TGCeAd9M/edit#gid=121298627).

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
