### ISSUE TITLE
Update Keycloak version to 24

### ISSUE THREAD

**Issue by clickersmudge** [bitnami/containers#64198]
### Name and Version

bitnami/keycloak:23.0.7-debian-12-r4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Hi,
If possible we would like to request an update to version 24.

### What do you see instead?

Update to version 24.

**Comment by tanadeau** [comment]
See #63545. The 24 image is available on Docker Hub but isn't yet available on AWS ECR (strangely).

**Comment by carrodher** [comment]
There was a pending step that already succeeded, the image is now present in the AWS Public Gallery and DockerHub
