### ISSUE TITLE
Etcd Pod Crashes Due to Unreleased Memory Allocation 

### ISSUE THREAD

**Issue by NeethithevanR** [bitnami/containers#64210]
### Name and Version

bitnami/etcd:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Runing Etcd pod with this image
bitnami/etcd:latest
etcdctl version: 3.5.12
API version: 3.5

### What is the expected behavior?

Etcd need to run continuously without rapid increase in RAM usage.

### What do you see instead?

We are running an etcd pod with PVC storage. While the application is running, heap memory allocation continuously increases, and the allocated memory is not being released. This continuous increase in RAM usage causes the pod to crash when it runs out of RAM. Any guidance to fix this issue would be greatly appreciated.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
