### ISSUE TITLE
[bitnami/mariadb] the latest containers are too large compared to the previous ones (520 MB vs. 125 MB).

### ISSUE THREAD

**Issue by jurykor** [bitnami/containers#64594]
### Name and Version

bitnami/mariadb:10.6.17-debian-12-r9

### What architecture are you using?

None

### What steps will reproduce the bug?

the latest containers are too large compared to the previous ones (520 MB vs. 125 MB).

component `https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz` 10 times more than the previous ones.
For example mariadb-10.6.17-1-linux-amd64-debian-12.tar.gz - 58 MB, and mariadb-10.6.17-2-linux-amd64-debian-12.tar.gz - 488 MB.

and it looks like a non-release build.

for what?

**Comment by jurykor** [comment]
It's the same story with apache.

apache:2.4.58-debian-11-r28 - 56MB
apache-2.4.58-7-linux-amd64-debian-11.tar.gz - 9MB
(unpacked 35 MB)

starting with
apache:2.4.58-debian-11-r29 - 125MB
apache-2.4.58-7-linux-amd64-debian-11.tar.gz - 78MB
(unpacked 356 MB)

What has changed?

**Comment by carrodher** [comment]
Thanks for letting us know, we just identified an issue when stripping binary files causing the tarballs to be larger than expected. A fix was implemented and new revisions of the containers are being released.

I.e
🔴 [10.6.17-debian-12-r9](https://hub.docker.com/layers/bitnami/mariadb/10.6.17-debian-12-r9/images/sha256-7679d8e424ccd3d001f3de23167b10c8eb7f4c61ec3c97f61d0a80c5fccf9be7?context=explore) 557.04 MB
✅ [10.6.17-debian-12-r10](https://hub.docker.com/layers/bitnami/mariadb/10.6.17-debian-12-r10/images/sha256-2e16cd7af7278f041d17f0d369aaa2e3693c224df537c465e10506ccac576788?context=explore) 120.05 MB

Sorry for the inconveniences!

**Comment by jurykor** [comment]
Thanks!
Yes, it looks like it was a systemic problem. I use `wordpress`. It affects the `mysql-client` and `apache` components. Accordingly, all the images on which they depend. Such as `drupal`, `joomla`, etc. It seems that you need to check all the components and rebuild if necessary.

**Comment by carrodher** [comment]
Yes, everything is going to be released in the following days so we are sure the issue is gone

**Comment by jurykor** [comment]
could you please rebuild the packages `mysql-client-x.y.z-linux-amd64-debian-12.tar.gz` ?

**Comment by carrodher** [comment]
Hi, it should be already released.
