### ISSUE TITLE
[Request] new Bitnami container ScyllaDB

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#64641]
### Name and Version

bitnami/scylla

### What is the problem this feature will solve?

Currently, Birnami offers containers for databases like MongoDB and Cassandra, but notably absent is a container for Scylla, another high-performance NoSQL database. This gap limits options for developers aiming to utilize Scylla within containerized environments.

### What is the feature you are proposing to solve the problem?

Introducing a Scylla container into Birnami's offerings would facilitate the migration away from Java-based setups typically associated with Cassandra. As Scylla is implemented in C++, offering a containerized version would enable users to leverage the database's performance benefits while bypassing the need for Java dependencies.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team.
