### ISSUE TITLE
bitnami/laravel is slower than non-docker Laravel

### ISSUE THREAD

**Issue by drice82** [bitnami/containers#64956]
### Name and Version

bitnami/laravel:10 (laravel 11 doen't test)

### What is the problem this feature will solve?

bitnami/laravel is slower than non-docker Laravel

### What is the feature you are proposing to solve the problem?

My testing process is as follows:
- Bitnami/laravel + Bitnami/mariadb: slow
- Bitnami/laravel + AWS light sail RDS: slow
- Bitnami/laravel + Mariadb(by Cloudpanel): slow
- Laravel in Cloudpanel(LNMP) + Bitnami/mariadb: normal
- Laravel in Cloudpanel(LNMP) + AWS lightsail RDS: normal

Definition of slow: 3-5s to open a new page. 
Definition of normal: 1s to open a new page. 

Build my own docker image, based on Bitnami/laravel,  copy my web into the image, but the result is still slow.

**Comment by drice82** [comment]
For a fairer test, I created the following environment: 
DB: AWS lightsail RDS,  MySQL database (8.0.36), 1 GB RAM, 2 vCPUs, 40 GB SSD, all the test connect to this DB.
And create a lightsail instances to install Cloudpanel(LNMP) and Docker to run Laravel. run on the same server. 
The instance is 2 GB RAM, 2 vCPUs, 60 GB SSD, OS is Debian11
The laravel is my own project, it is laravel+Adminlte.
I click the page from page1 to page 15, and record the page 15 result as below:
this is LNMP:
![f1](https://github.com/bitnami/containers/assets/17443832/b49a7edb-63d1-461d-8343-f38c20ad9546)
This is Bitnami/Laravel
![s1](https://github.com/bitnami/containers/assets/17443832/c316912d-f80f-4c0c-921e-cb68b6184307)
I only post 2 results, but actually when i click other pages, the result are similar, LNMP takes about 1s to open a new page, and Bitnami/Laravel takes about 4s. 

I did similar test in other environment, like Linode server, and tried use Bitnami/Laravel on Lightsail container. But the result was similar. 
I tried other Laravel application, also design by myself, the result also similar.

**Comment by drice82** [comment]
@gongomgra 
I tried other nginx-php-fpm docker image, it works well with my application. I think the difference is that the nginx-php-fpm image uses nginx as the HTTP server, and bitnami/Laravel uses PHP’s built-in development server as HTTP server.

**Comment by gongomgra** [comment]
Hi @drice82,

Thanks for your message. I agree the performance differences may be related to the Bitnami Laravel container not including a web server like Apache or NGINX but relying on Laravel's HTTP server.
