### ISSUE TITLE
[bitnami/redis] boot failed on arm64

### ISSUE THREAD

**Issue by SchoIsles** [bitnami/containers#64979]
### Name and Version

bitnami/redis:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. arm64 debian11
2. ..
3. docker run --name redis -e ALLOW_EMPTY_PASSWORD=yes bitnami/redis:latest
4. `<jemalloc>: Unsupported system page size`

### What do you see instead?

<jemalloc>: Unsupported system page size

### Additional information

The official library redis has fixed this problem
https://github.com/docker-library/redis/issues/208

**Comment by carrodher** [comment]
Thanks for creating this issue, in fact, it is something already reported at https://github.com/bitnami/containers/issues/26062. The team will look into it. Please take a look at the already existing GH issue for more news.
