### ISSUE TITLE
[bitnami/wordpress-nginx] Wordpress startup is broken in 6.4.3 wordpress-nginx

### ISSUE THREAD

**Issue by MichalP574** [bitnami/containers#65057]
### Name and Version

docker.io/bitnami/wordpress-nginx:6.4.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Environment: AWS ECS Fargate
Task definition:
```
"mountPoints": [
                {
                    "sourceVolume": "wordpress",
                    "containerPath": "/bitnami/wordpress"
                }
            ],
"volumes": [
        {
            "name": "wordpress",
            "efsVolumeConfiguration": {
                "fileSystemId": "fs-xxxxxx",
                "rootDirectory": "/",
                "transitEncryption": "ENABLED",
                "authorizationConfig": {
                    "accessPointId": "fsap-xxxxxxxxxx",
                    "iam": "DISABLED"
                }
            }
        }
    ],
```

### What is the expected behavior?

** WordPress setup finished! **

### What do you see instead?
```
mkdir: cannot create directory '/bitnami/wordpress-nginx': Permission denied
```
### Additional information

The bitnami/wordpress v6.4.3 release requires a separate folder named /bitnami/wordpress-nginx in the root directory to create a file called .user_scripts_initialized. This was not required in previous versions, up to v6.4.2, where the bitnami/wordpress path alone (the mount point in AWS EFS) was sufficient. The current workaround is to mount an additional volume and create a mount point, but we would like to avoid this because it introduces an unnecessary layer of complexity.

There is a similar thread here: https://github.com/bitnami/containers/issues/64951, but the infrastructure discussed there involves a standalone Docker setup, unlike in this case, where deployment is done using AWS ECS Fargate.

**Comment by javsalgar** [comment]
Hi! 

Does the answer here help you with your use case? https://github.com/bitnami/containers/issues/64951#issuecomment-2051199321
