### ISSUE TITLE
[bitnami/postgresql-repmgr] Request for pg_vector aka vector plugin integrations.

### ISSUE THREAD

**Issue by qurikuduo** [bitnami/containers#65093]
### Name and Version

bitnami/postgresql-repmgr

### What is the problem this feature will solve?

I want to build a HA cluster using postgresql-repmgr with pgvector: https://github.com/pgvector/pgvector/ integrated.
But I couldn't find any document to do this, I'm trying to do it myself. But I don't find where to modify in Dockerfile.
Any suggestion will be a great help, thank you very much.
PS:
pgvector needs build-essential and will do make and make install during docker build.

### What is the feature you are proposing to solve the problem?

integrate pgvector and postgresql-repmgr

### What alternatives have you considered?

I plan to run postgresql-repmgr container first, then install pgvector manually, at last package the container as a new docker image. 
But I’m not sure whether it is workable.

**Comment by javsalgar** [comment]
Hi,

Could you try doing something similar as this comment? https://github.com/bitnami/charts/issues/8713#issuecomment-1203879607

**Comment by qurikuduo** [comment]
> Hi,
> 
> Could you try doing something similar as this comment? [bitnami/charts#8713 (comment)](https://github.com/bitnami/charts/issues/8713#issuecomment-1203879607)

I'll check it out. Thank you for your reply.
