### ISSUE TITLE
[bitnami/rabbitmq] vm_memory_high_watermark.relative uses the host memory instead of K8s memory limit (so Docker)

### ISSUE THREAD

**Issue by luarx** [bitnami/containers#65100]
### Name and Version

bitnami/rabbitmq:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run rabbitmq image specifying `/bitnami/rabbitmq/conf/rabbitmq.conf` with this content:
`    vm_memory_high_watermark.relative = 0.7`

### What is the expected behavior?

I run the container in a `Kubernetes node with 16Gi`
The container has configured a `memory limit: 1000Mi`

I expect to see this watermark log: 
_Memory high watermark setting: 0.7 of available memory, computed to: 700 mi_

### What do you see instead?

_Memory high watermark setting: 0.7 of available memory, computed to: 11.4611 gb_

**Comment by javsalgar** [comment]
Hi!

I'm afraid that is how the container engine currently runs. The fact that you set a memory limit to 1000Mi does not mean that the container only sees that amount of memory at runtime. This means that the container will get killed if the consumed memory goes over that limit.

**Comment by luarx** [comment]
Thanks for clarifying! 🙏 
Will close this issue 😄
