### ISSUE TITLE
[bitnami/mysql] questions on using 3rd party audit plugin, custom audit log path, specify validate_password.dictionary_file

### ISSUE THREAD

**Issue by cwrx777** [bitnami/containers#65178]
### Name and Version

bitnami/mysql:8.0.36

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is not a bug report. I want to ask how to perform the following using MySQL bitnami helm chart.

1. using 3rd party audit plugin, such as one from percona server
2. mount log path (error, slow log, audit) to host local storage.
3. specify password dictionary file

### What do you see instead?

see above

**Comment by javsalgar** [comment]
Hi,

If you want to use a third party plugin, you may need to create your own fork of the bitnami/mysql container, where you add the plugins and the configuration tweaks (by editing the /opt/bitnami/mysql/etc.default/my.cnf file) required
