### ISSUE TITLE
[bitnami/moodle] Moodle 4.3.3 - 4.1.6

### ISSUE THREAD

**Issue by coffseducation** [bitnami/containers#65184]
### Name and Version

bitnami/moodle:4.3.3

### What architecture are you using?

None

### What steps will reproduce the bug?

I tried installing Moodle 4.3.3
The configs state my version is 4.1.6.

### What is the expected behavior?

Install Moodle 4.3.3 - have Moodle 4.3.3 installed.

### What do you see instead?

Installation of version 4.1.6.

### Additional information

I am using Caprover One-click App with 4.3.3 entered as the version.
Ubuntu server 22.04.

**Comment by VieiraHenrique** [comment]
Hello @coffseducation 
I am trying to deploy moodle on caprover, but I am not getting any success. It's not able to connect to the db.
I created a MariaDB database in caprover as well. But I am not able to connect them.
Could you give me a little help if you have time ? Thanks so much !

**Comment by coffseducation** [comment]
> Hi!
> 
> I'm afraid that, because of limitations of the persistence, Moodle upgrades need to be done via its administration panel.

Thanks for the reply. I found this bitnami [documentation](https://docs.bitnami.com/aws/apps/moodle/administration/upgrade/) and could then upgrade.

**Comment by coffseducation** [comment]
> Hello @coffseducation I am trying to deploy moodle on caprover, but I am not getting any success. It's not able to connect to the db. I created a MariaDB database in caprover as well. But I am not able to connect them. Could you give me a little help if you have time ? Thanks so much !

I am no expert sorry -far from it! Also I did not use the default mariadb setup. I have another mariadb instance I used and imported a previous db. Install Phpmyadmin (if you have not already done so) and investigate that way.
Do you have correct permissions set?
