### ISSUE TITLE
[bitnami/apache] Increase message size

### ISSUE THREAD

**Issue by YarochkinMichael** [bitnami/containers#65186]
### Name and Version

bitnami/apache:2.4

### What is the problem this feature will solve?

We are using it as a forward proxy.
And facing issues when trying to send messages larger than 32Kb.

 HTTP response '413: Request Entity Too Large'

### What is the feature you are proposing to solve the problem?

Is it possible to configure it using .config files or environment variables?

[forward-proxy docker image.zip](https://github.com/bitnami/containers/files/14976265/forward-proxy.docker.image.zip)
[forward-proxy OpenShift Config.zip](https://github.com/bitnami/containers/files/14976268/forward-proxy.OpenShift.Config.zip)

**Comment by javsalgar** [comment]
Hi,

I think that right now the option would be to mount a custom configuration file that sets the proper value for your use case.

**Comment by YarochkinMichael** [comment]
Hello

Thank you for the answer. Can you help me with it, please?

Mikl

**Comment by javsalgar** [comment]
This is an  example command to mount a custom httpd.conf file

```
docker run --name apache \
  -v /path/to/httpd.conf:/opt/bitnami/apache/conf.default/httpd.conf \
  bitnami/apache:latest
```

**Comment by YarochkinMichael** [comment]
Thank you for the reply.

Ok. And what do I need to set in httpd.conf to extend the message size?

Mikl

**Comment by YarochkinMichael** [comment]
Inside of the [forward-proxy docker image.zip](https://github.com/bitnami/containers/files/14976265/forward-proxy.docker.image.zip), attached to the original post, there is the config i am using now: conf/c-b2b-vhosts.conf

**Comment by carrodher** [comment]
Yes, it seems the same issue. Let's continue the conversation there since the issue is the same and related to the chart

**Comment by YarochkinMichael** [comment]
Ok. I get it. Wasn't it just easier to say "Sorry, man, I don't know" :)

Can you please identify what "technology" Bitnami uses? Then, I'll know where to ask.

Mikl
