### ISSUE TITLE
[bitnami/airflow] Airflow container errors out if `AIRFLOW_FERNET_KEY` or `AIRFLOW_SECRET_KEY` start with a dash

### ISSUE THREAD

**Issue by zanecodes** [bitnami/containers#65197]
### Name and Version

bitnami/airflow:latest (currently 2.9.0-debian-12-r1)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run `docker run -e 'AIRFLOW_SECRET_KEY=--PjzohgYFtiYCQjlyDNdeQdAIhXWgIAsE7Z-cMt7mg=' bitnami/airflow:2.7.3-debian-11-r2`

### What is the expected behavior?

The container should correctly populate the `secret_key` configuration key under the `[webserver]` section in `/opt/bitnami/airflow/airflow.cfg` with the value provided in the `AIRFLOW_SECRET_KEY` environment variable.

### What do you see instead?

The container setup script throws the error `expected argument for flag '-v, --value', but got option '--PjzohgYFtiYCQjlyDNdeQdAIhXWgIAsE7Z-cMt7mg='` while creating the default configuration file.

### Additional information

This happens because the [`airflow_conf_set` function in `/opt/bitnami/scripts/libairflow.sh` passes the configuration value to `ini-file` as a separate argument](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L236).

The issue can be fixed by changing the above-linked line to `ini-file set "--section=$section" "--key=$key" "--value=$value" -- "$file"`.

This affects all configuration values that are written using `airflow_conf_set`, namely:
- [`AIRFLOW_HOSTNAME_CALLABLE`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L194)
- [`AIRFLOW_WEBSERVER_PORT_NUMBER`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L207)
- [`AIRFLOW_FERNET_KEY`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L212)
- [`AIRFLOW_SECRET_KEY`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L213)
- [`AIRFLOW_EXECUTOR`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L216)
- [`AIRFLOW_BASE_URL`](https://github.com/bitnami/containers/blob/9dfe0b6070e38a57829b879e0b870cf7c94095ed/bitnami/airflow/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L252)

Values starting with dashes are not valid for most of these anyway, but are valid for `AIRFLOW_FERNET_KEY` and `AIRFLOW_SECRET_KEY`, and are indeed somewhat likely to occur since these are both URL-safe base64 encoded random byte sequences.

**Comment by jotamartos** [comment]
Hi @zanecodes,

Thank you for taking the time to create this ticket. If you have tried the change you proposed, would you like to contribute? You can follow our (contributing guidelines)[https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md] and the whole community will benefit from your change. 

Thanks
