### ISSUE TITLE
[bitnami/keycloak] Adapt scripts to proxy related changes in Keycloak 24

### ISSUE THREAD

**Issue by dalbani** [bitnami/containers#65190]
### Name and Version

bitnami/keycloak:24

### What is the problem this feature will solve?

Keycloak 24 introduces changes when it comes to proxy configuration.
See in particular:
- https://www.keycloak.org/server/reverseproxy#_proxy_modes
    > The support for setting proxy modes is deprecated and will be removed in a future Keycloak release. Consider configuring accepted reverse proxy headers instead as described in the chapter above. For migration instructions consult the [Upgrading Guide](https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option).
- https://github.com/keycloak/keycloak/pull/25178
   It looks like `--proxy-headers` is the only option supported now, isn't it?

How to reproduce:
1. Run Docker container with `KEYCLOAK_PROXY=edge` for example.
2. See the following warning in the container logs:
    ```
    WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
    ```

### What is the feature you are proposing to solve the problem?

This Docker image should probably swap the `KEYCLOAK_PROXY` environment variable for a new one called `KEYCLOAK_PROXY_HEADERS`, mapping to the `proxy-headers` setting in Keycloak.

Note: this change will affect the Keycloak chart at https://github.com/bitnami/charts/tree/main/bitnami/keycloak.

### What alternatives have you considered?

Not really an "alternative", but in the meantime, I used `KEYCLOAK_EXTRA_ARGS: --proxy-headers xforwarded` to run Keycloak 24 (on Kubernetes).

**Comment by jotamartos** [comment]
Hi @dalbani,

Thanks for taking the time to create this ticket and report this change. I just created a ticket on our side to take care of the changes. However, I can't provide you with an ETA on when this change will be ready. We will notify you when having more information. 

Thanks

**Comment by dalbani** [comment]
Note that Keycloak introduced even more changes when it comes to hostnames: https://www.keycloak.org/2024/06/keycloak-2500-released.html#_new_hostname_options.
