### ISSUE TITLE
[bitnami/logstash] custom plugin installation issue

### ISSUE THREAD

**Issue by knpshkn** [bitnami/containers#65208]
### Name and Version

bitnami/logstash:8.13.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i'm trying to install plugins with [Helm chart: bitnami/charts/tree/main/bitnami/logstash](https://github.com/bitnami/charts/tree/main/bitnami/logstash) 
Config is:
```yaml
extraEnvVars:
  - name: LOGSTASH_PLUGINS
    value: logstash-output-opensearch
```
And it throws error:
```
logstash 15:58:30.30 DEBUG ==> Installing plugin: logstash-output-opensearch
Using system java: /opt/bitnami/java/bin/java
ERROR: File /opt/bitnami/logstash/Gemfile does not exist or is not writable, aborting
```
I tried `logstash-filter-json_encode`, it throws the same error

Perhaps this is due to the fact that Gemfile (and bundle folder) permissions are set with the `root` group instead of a predefined variable `LOGSTASH_DAEMON_GROUP` [here](https://github.com/bitnami/containers/blob/main/bitnami/logstash/8/debian-12/rootfs/opt/bitnami/scripts/logstash/postunpack.sh#L27) ?

### What is the expected behavior?

it should work

### What do you see instead?

It throws error

**Comment by javsalgar** [comment]
Hi,

Could you try setting `containerSecurityContext.readOnlyRootFilesystem=false` and `containerSecurityContext.runAsGroup=0`?

**Comment by knpshkn** [comment]
Hi @javsalgar 

Yes, I have tried and it causes such errors:
```
logstash 11:44:13.41 INFO  ==> Installing plugins: logstash-filter-json_encode
logstash 11:44:13.41 DEBUG ==> Installing plugin: logstash-filter-json_encode
Using system java: /opt/bitnami/java/bin/java
Validating logstash-filter-json_encode
Resolving mixin dependencies
Installing logstash-filter-json_encode
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
............
Error ArgumentError, retrying 10/10
could not find a temporary directory
`/` is not writable.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/bitnami/logstash
Too many retries, aborting, caused by ArgumentError
ERROR: Installation Aborted, message: could not find a temporary directory
```

**Comment by knpshkn** [comment]
It seems to be the same problem as in the issue: https://github.com/bitnami/charts/issues/24403

**Comment by carrodher** [comment]
Yes, it seems the same issue. Let's continue the conversation there since the issue is the same and related to the chart
