### ISSUE TITLE
rabbitmq needs privileged mode in kubernetes

### ISSUE THREAD

**Issue by dr4Ke** [bitnami/containers#65235]
### Name and Version

bitnami/rabbitmq:3.13.1-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In a kubernetes cluster (version v1.24.17), I deploy rabbitmq using the bitnami helm chart (version 14.0.1)
2. Configuration:
```
  auth:
    tls:
      enabled: true
      failIfNoPeerCert: false
```
4. The pod initialization fails with
```
ERROR ==> The variable RABBITMQ_COMBINED_CERT_PATH must be set to either an existant file or a non-existant file in a writable directory.
```
5. If I add `privileged: true` in the securityContext, the error disappears

### What is the expected behavior?

rabbitmq should start

### What do you see instead?

The pod fails with error
```
ERROR ==> The variable RABBITMQ_COMBINED_CERT_PATH must be set to either an existant file or a non-existant file in a writable directory.
```

### Additional information

In this configuration, if I run a shell, I can test myself:
```
$ test -w /tmp; echo $?
1
$ /usr/bin/test -w /tmp; echo $?
0
$ which test
$
```
After activating `privileged: true`:
```
$ test -w /tmp; echo $?
1
$ /usr/bin/test -w /tmp; echo $?
0
$ which test
/usr/bin/test
$
```

I don't understand why this issue occurs.

This issue could be mitigated if the initialization scripts used `/usr/bin/test` instead of `test`.

EDIT: The `test` command is behaving like the `[[ ]]` command used in the scripts.

**Comment by dr4Ke** [comment]
It was limited to an old node, something about the kernel or docker. I'm closing this issue.
Sorry for the noise.

**Comment by myysophia** [comment]
modify rabbitmq image tag resolve this issue.
