### ISSUE TITLE
[bitnami/keycloak] `KEYCLOAK_CACHE_CONFIG_FILE` env is being ignored

### ISSUE THREAD

**Issue by Bolodya1997** [bitnami/containers#65249]
### Name and Version

bitnami/keycloak:23.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

0. Using chart for keycloak - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
1. Set value `cache.stackFile` to something with `cache.enabled=true`.
2. Deploy chart.
3. Go to keycloak container and run `cat /opt/bitnami/keycloak/conf/keycloak.conf`

### What is the expected behavior?

`cache-config-file` should be configured with the given value.

### What do you see instead?

No `cache-config-file` entry.

### Additional information

It looks like `KEYCLOAK_CACHE_CONFIG_FILE` env from chart is being ignored.

**Comment by rafariossaa** [comment]
Hi, Could you try latest chart version ?
