### ISSUE TITLE
[bitnami/moodle] MOODLE_SSLPROXY environment variable has no effect

### ISSUE THREAD

**Issue by vlk-charles** [bitnami/containers#6534]
### Name and Version

bitnami/moodle:4.0.4-debian-11-r2

### What steps will reproduce the bug?

Assuming I have an initialized Moodle DB in Docker volume `moodle-db`:
```
$ docker network create moodle
$ docker run -d --network moodle --name moodle-db -v moodle-db:/var/lib/mysql mariadb
$ docker run -d --network moodle --name moodle \
 -e ALLOW_EMPTY_PASSWORD=yes \
 -e MARIADB_HOST=moodle-db \
 -e MOODLE_DATABASE_USER=root \
 -e MOODLE_SKIP_INSTALL=yes \
 -e MOODLE_SSLPROXY=yes \
 bitnami/moodle
```

### What is the expected behavior?

I would expect the `MOODLE_SSLPROXY`environment variable to cause `$CFG->sslproxy = true;` to be put in `/bitnami/moodle/config.php` **before** the line calling `setup.php`.

### What do you see instead?

```
$ docker exec moodle cat bitnami/moodle/config.php
<?php  // Moodle configuration file

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'moodle-db';
$CFG->dbname    = 'bitnami_moodle';
$CFG->dbuser    = 'root';
$CFG->dbpass    = '';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => 3306,
  'dbsocket' => '',
  'dbcollation' => 'utf8mb4_general_ci',
);

if (empty($_SERVER['HTTP_HOST'])) {
  $_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
}
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  $CFG->wwwroot   = 'https://' . $_SERVER['HTTP_HOST'];
} else {
  $CFG->wwwroot   = 'http://' . $_SERVER['HTTP_HOST'];
}
$CFG->dataroot  = '/bitnami/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 02775;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
$CFG->sslproxy = true;
```
`setup.php` does not see the variable as set so it has no effect. I still get an infinite redirect loop when trying to access Moodle through my TLS reverse proxy. I access through HTTPS, but Moodle thinks I am accessing through HTTP and redirects me to the same HTTPS address I am already using. This can be fixed by moving the last line at least 4 lines higher.

**Comment by vlk-charles** [comment]
Just to clarify, the infinite redirect loop I mentioned only happens if I set `$CFG->wwwroot` statically to HTTPS (not shown in example output above, as explained in #6535). Without it, I get "mixed content" errors (HTTPS page referencing other resources using HTTP). If `MOODLE_SSLPROXY` actually worked, instead of "mixed content", I should be getting the error:
"Must use https address in wwwroot when ssl proxy enabled!"

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/moodle#user-content-community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by vlk-charles** [comment]
The problem is here:
https://github.com/bitnami/containers/blob/37fb9a6d256525024c544cdeb2f45ff1c2674c1c/bitnami/moodle/4/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L411
The `moodle_configure_reverseproxy` function simply appends (`>>`) the options to the file.

**Comment by vlk-charles** [comment]
I confirm this has been fixed. Tested on `bitnami/moodle:4.0.4-debian-11-r7`.
