### ISSUE TITLE
[bitnami/kubectl] git no longer available in container image.

### ISSUE THREAD

**Issue by BenB196** [bitnami/containers#6536]
### Name and Version

bitnami/kubectl:1.23.10

### What steps will reproduce the bug?

1. Pull bitnami/kubectl:1.23.10
2. Run `which git`
3. See no git installed

### What is the expected behavior?

I expect git to be installed.

Running the same steps on `bitnami/kubectl:1.23.9`

1. Pull bitnami/kubectl:1.23.9
2. Run `which git`
3. See git installed at `/usr/bin/git`

### What do you see instead?

I don't see git installed.

### Additional information

Git is useful/needed in this container image when using kubectl with `-k` (kustomize). If you run `kubectl apply -k "<some_git_url>"` on `1.23.10` you get the error:

```
error: no 'git' program on path: exec: "git": executable file not found in $PATH
```

**Comment by Mauraza** [comment]
Hi @BenB196,

In the next revision of the kubectl container, `git` will be included. When this happens we will update this thread.

**Comment by corico44** [comment]
The new version with the included git package is now available. Thank you very much for the contribution @BenB196!
