### ISSUE TITLE
[bitnami/wordpress-nginx] The bitnami/wordpress-nginx:6.3.2-debian-11-r8 image is upgraded to bitnami/wordpress-nginx:6.5.2-debian-12-r3, but the container cannot be started.

### ISSUE THREAD

**Issue by jiangning1021** [bitnami/containers#65649]
### Name and Version

bitnami/wordpress-nginx:6.5.2-debian-12-r3

### What architecture are you using?

None

### What steps will reproduce the bug?

The bitnami/wordpress-nginx:6.3.2-debian-11-r8 image is upgraded to bitnami/wordpress-nginx:6.5.2-debian-12-r3, but the container cannot be started.Container error
![image](https://github.com/bitnami/containers/assets/160723107/151572e1-88b3-438e-aecc-c5a5dd1da06d)
![image](https://github.com/bitnami/containers/assets/160723107/5cf359da-ea41-4bae-aa8f-4759b9dd3ddb)
![img_v3_02a8_cbdc25fb-6945-442c-a5dc-ca86f4f6d4ag](https://github.com/bitnami/containers/assets/160723107/c3e847ab-5acf-4003-8bb7-8353b7572e0a)
![img_v3_02a8_19a1a949-c7b2-4170-b552-065a1abe041g](https://github.com/bitnami/containers/assets/160723107/a37e97aa-d709-478e-9d98-94a22f315fed)

**Comment by carrodher** [comment]
Could you provide more info about how are you deploying the container?

**Comment by jiangning1021** [comment]
> 您能否提供有关如何部署容器的更多信息？
This is the parameter configuration of my container
![image](https://github.com/bitnami/containers/assets/160723107/7f83f08d-08a2-4ce5-9121-c6be16c5a6f3)
![image](https://github.com/bitnami/containers/assets/160723107/ed8385a0-097f-4b00-bfc5-8603bb0a8c39)

**Comment by carrodher** [comment]
Thanks for sharing the env. vars, that could help to reproduce the issue on our side. Could you please share how are you deploying the container? Just with `docker run`, using compose, as part of a Helm chart, etc

**Comment by jiangning1021** [comment]
> 这可能有助于在我们这边重现该问题。您能分享一下您是如何部署容器的吗？

I used the bitnami/wordpress-nginx:6.5.2-debian-12-r3 image package generated by the Dockerfile file, then uploaded it to aws ecr, and replaced the image in the ecs task definition with the image in ecr.
![image](https://github.com/bitnami/containers/assets/160723107/2d095411-7eed-427a-aeb6-f8be24c9a9e0)

**Comment by carrodher** [comment]
It seems the issue appears when trying to connect to the database. How is this database deployed? Can you access it using another client?

**Comment by jiangning1021** [comment]
> 尝试连接数据库时似乎出现了问题。这个数据库是如何部署的？您可以使用其他客户端访问它吗？

My database uses aws rds, other users can connect to the database

**Comment by jiangning1021** [comment]
> 尝试连接数据库时似乎出现了问题。该数据库是如何配置的？您可以使用其他客户端访问它吗？
There is no problem with the database connection. I use the bitnami/wordpress-nginx:6.3.2-debian-11-r8 version image. There is no problem when creating the container. I package the bitnami/wordpress-nginx:6.5.2-debian-12-r3 image. Uploading ecr and using a new image package to install the container does not work

**Comment by jiangning1021** [comment]
> 你能用 启动容器吗`BITNAMI_DEBUG=true`？这可能会添加有关该问题的更多信息。

![image](https://github.com/bitnami/containers/assets/160723107/34c175de-cf9c-47ed-b1a3-4e585ccdb34d)
Fatal error: Cannot declare class WP_Plugin_Dependencies, because the name is already in use in /bitnami/wordpress/wp-content/mu-plugins/wp-plugin-dependencies/wp-admin/includes/class-wp-plugin-dependencies.php on line 16

**Comment by jiangning1021** [comment]
> Could you launch the container with `BITNAMI_DEBUG=true`? This may add more information on the issue.

Thank you very much for your answers. The problem has been solved.
