### ISSUE TITLE
[bitnami/keycloak] Typo is_empty_valye in /opt/bitnami/scripts/libkeycloak.sh [Keycloak]

### ISSUE THREAD

**Issue by mbecca** [bitnami/containers#65684]
### Name and Version

bitnami/keycloak:24.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Run docker image bitnami/keycloak:24.0.3

### What is the expected behavior?

! is_empty_value "$KEYCLOAK_CACHE_CONFIG_FILE" && keycloak_conf_set "cache-config-file" "${KEYCLOAK_CACHE_CONFIG_FILE}"

### What do you see instead?

! is_empty_valye "$KEYCLOAK_CACHE_CONFIG_FILE" && keycloak_conf_set "cache-config-file" "${KEYCLOAK_CACHE_CONFIG_FILE}"

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
