### ISSUE TITLE
[bitnami/nginx] Nginx not shutting down gracefully by-default

### ISSUE THREAD

**Issue by sztanpet** [bitnami/containers#65691]
### Name and Version

bitnami/nginx:1.25.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- docker stop the container while serving a request, before nginx had time to serve the response
- observe that the container stopped immediately, the response was never returned

### What is the expected behavior?

`STOPSIGNAL SIGQUIT`

### What do you see instead?

docker stop first sends a SIGTERM (by default) expecting the container to gracefully shut down, and if that did not happen, it sends a SIGKILL to forcefully shut it down
SIGTERM for nginx is not the graceful exit signal, SIGQUIT is, but STOPSIGNAL is not configured to SIGQUIT correctly

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by sztanpet** [comment]
Not interested, sorry.
