### ISSUE TITLE
[bitnami/mediawiki] Unable to use $wgAllowImageTag in LocalSettings.php

### ISSUE THREAD

**Issue by iain-ilearner** [bitnami/containers#65721]
### Name and Version

bitnami/mediawiki:1.41.1-debian-12-r3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I originally reported this issue in bitnami/charts#25394 but realise it probably belongs here.

Having `$wgAllowImageTag = true;` in LocalSettings.php causes container to fail to start.

### What do you see instead?

Container logs up to the point of failure:

    mediawiki 15:29:12.53 INFO  ==> Restoring persisted MediaWiki installation
    mediawiki 15:29:12.85 INFO  ==> Trying to connect to the database server
    mediawiki 15:29:12.89 DEBUG ==> Getting $wgDBserver from MediaWiki configuration
    mediawiki 15:29:12.92 DEBUG ==> ^\s*(//\s*)?\$wgDBserver\s*=([^;]+);
    mediawiki 15:29:13.01 DEBUG ==> Getting $wgDBname from MediaWiki configuration
    mediawiki 15:29:13.04 DEBUG ==> ^\s*(//\s*)?\$wgDBname\s*=([^;]+);
    mediawiki 15:29:13.10 DEBUG ==> Getting $wgDBuser from MediaWiki configuration
    mediawiki 15:29:13.10 DEBUG ==> ^\s*(//\s*)?\$wgDBuser\s*=([^;]+);
    mediawiki 15:29:13.11 DEBUG ==> Getting $wgDBpassword from MediaWiki configuration
    mediawiki 15:29:13.29 DEBUG ==> ^\s*(//\s*)?\$wgDBpassword\s*=([^;]+);
    mediawiki 15:29:13.30 DEBUG ==> Executing SQL command:
    SELECT 1
    /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
    1
    Some of your configuration settings caused a warning:
    
    * AllowImageTag is deprecated: since 1.35; register an extension tag named
      <img> instead.
    
    Please correct the issue before running update.php again.
    If you know what you are doing, you can bypass this check
    using --skip-config-validation.

When running with `BITNAMI_DEBUG=false`, there are no log messages after "Trying to connect to the database server". So I initially went down the rabbit hole of debugging networking issues. A success message after connecting might be useful.

### Additional information

https://github.com/bitnami/containers/blob/fd72ab98db5af75b53de1a463f5fa14a047a8548/bitnami/mediawiki/1/debian-12/rootfs/opt/bitnami/scripts/libmediawiki.sh#L154

This line runs the update script after establishing a database connection. However, it can fail silently unless `BITNAMI_DEBUG` is set to true. (In which case it still fails, but at least it's not silent)

Although `$wgAllowImageTag` has been deprecated by MediaWiki, it shouldn't cause the update script to fail. The update script should probably be run with `--skip-config-validation`, or at least make the output visible in logs.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Maybe it makes sense adding an env var that sets the `--skip-config-validation` flag. Would you like to submit a PR adding this value? If not we will work on it, but as it is not a critical feature, we cannot guarantee an ETA.
