### ISSUE TITLE
[bitnami/magento] Extension only working after container restart -or- when not opening website before installing extension

### ISSUE THREAD

**Issue by SaturnusDJ** [bitnami/containers#65746]
### Name and Version

bitnami/magento:2.4.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have an issue where the only way to get an extension working, is to restart the container. UNLESS the extension is installed before opening the Magento website (directly after the container is finished starting up).

This issue contains a specific extension to describe the problem, however, this problem also applies to language packs like https://github.com/magento-l10n. The issue is experienced on two completely different systems (hardware, base OS, etc.)

**Problem**
After adding the repos and credentials to composer, these ways (either daemon or root user) are tried to get an extension working:
* Bitnami instructions (https://github.com/bitnami/containers/blob/main/bitnami/magento/README.md#step-4-follow-the-installation-instructions-for-the-extension-the-magento-standard-is-to-use-composer)
* Extension seller instructions (https://support.mageworx.com/genext/repo/)
* Executing Magento commands related to installing, upgrading, compiling, etc:
```
apt update
apt install unzip -y #advised by a warning to not use PHP's built-in zip
rm -rf ./vendor
composer clear-cache
composer require
composer install
composer update
php bin/magento maintenance:enable
php bin/magento deploy:mode:set developer
php bin/magento module:enable <extension name>
php bin/magento setup:install
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento setup:static-content:deploy nl_NL -f
php bin/magento indexer:reset
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
(php bin/magento deploy:mode:set production)
(php bin/magento maintenance:disable)
```

None of these, whenever executed, in whatever order executed, result in a working extension.

### What do you see instead?

*Result*
When opening the admin panel, in the top the text 
>Class "MageWorx\OptionHealthChecker\Model\System\Message\IsValidTablesDataSystemMessage" not found

can be seen.

Sometimes more in the middle 
> A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

can be read.

When opening the store configuration, a submenu of the extension can be seen but opening it renders an empty page with an error. The extension's menus are nowhere to be found. A lot of the admin panel is broken and type 500 errors are seen in the container logging.

A part of debug logging:
> main.CRITICAL: Error: Class "MageWorx\OptionFeatures\Model\Config\Source\ProductPriceDisplayMode" not found in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php:60
From the container logging:

The only thing that works is to restart the container. This can be done as early as after the `composer require` command completes successfully. The extension will show up and work correctly after the restart.

Why is the normal way not working?

**Comment by gongomgra** [comment]
Hi @SaturnusDJ,

Thanks for reporting this issue. I have reproduce it with one of the free plugins available in Magento store (`taxjar/module-taxjar`). However, I have not found yet why the restart action properly enables the extension and adds it to the web interface. Checking our [initialization logic](https://github.com/bitnami/containers/blob/0475fb22f69718000322f6cce87ad78d30cdbf24/bitnami/magento/2/debian-12/rootfs/opt/bitnami/scripts/libmagento.sh#L327) for persisted installations, I don't see any extra command that is run there and not in our guide. Unfortunately, I don't have enough knowledge on how Magento works internally, can you ask in the official Magento forums for further help on this?

**Comment by SaturnusDJ** [comment]
@gongomgra Thanks for looking into this. I might ask in their community. If so, then I will update here.

**Comment by gongomgra** [comment]
@SaturnusDJ thanks for letting us know. We hope you can get an answer from Magento developers!
