### ISSUE TITLE
[Magento] How to set Magento's admin username and password in docker-compose.yaml ?

### ISSUE THREAD

**Issue by sheep0lata** [bitnami/containers#65781]
### Describe your issue as much as you can

# Context
Hello, I'm currently runnig a magento/mariadb stack using docker-compose and bitnami's official image and I would like to change the admin username and password of my Magento app.

I tried to use the "MAGENTO_USERNAME" and "MAGENTO_PASSWORD" environment variables but it seems like the container just won't take these in consideration.

On top of that, when I use the "MAGENTO_PASSWORD" environment variable the bitnami/magento container executes the same tasks over and over again, which leads to magento not being installed at all.

I attached the result of ```docker compose up``` to this issue (in the "docker-compose-up.txt" file) so you  can see the "Running Magento install script" step (and every steps before) repeat. I also attached my docker-compose.yaml and .env files.

What can I do to fix this problem ?

# Environment
OS : Oracle Linux Server 8.9
Docker version : Docker version 26.0.1, build d260a54
Magento image used : bitnami/magento:2.4.7
MariaDB image used : mariadb:10.5.9

# Steps to reproduce
1. create a docker-compose.yaml file with the content of the "docker-compose.yaml.txt" file attached to this issue
2. create a .env file with the content of the "dotenv_example.txt"file attached to this issue
3. create two networks (```docker network create app_network``` and ```docker network create  --internal=true db_network```)
4. start containers with ```docker compose up (-d)```
5. wait for containers to start and check the binami/magento container logs

[docker-compose.yaml.txt](https://github.com/bitnami/vms/files/15163029/docker-compose.yaml.txt)
[docker-compose-up.txt](https://github.com/bitnami/vms/files/15163093/docker-compose-up.txt)
[dotenv_example.txt](https://github.com/bitnami/vms/files/15163031/dotenv_example.txt)

**Comment by carrodher** [comment]
Are you able to mimic the instructions from https://github.com/bitnami/containers/tree/main/bitnami/magento#using-the-docker-command-line but using docker-compose?

In the same way, please note there are different env. variables related to passwords:

* Magento

|Name | Description | Default Value|
-- | -- | --
| MAGENTO_PASSWORD | Magento user password. | `bitnami1` |
| MAGENTO_DATABASE_PASSWORD | Database user password. | `nil`|

* MariaDB

|Name | Description | Default Value|
-- | -- | --
|MARIADB_ROOT_PASSWORD | MariaDB database root user password. | `nil`|
|MARIADB_PASSWORD | Password for the MariaDB database user to create during the first initialization. | `nil`|

**Comment by sheep0lata** [comment]
Hello, thanks for your answer.

I understand the difference between the different env variable you displayed above, and as you can see in the example docker compose file and .env files I think I'm already trying to use them as it is described in the different documentation I read (mostly from the docker hub page of this container). And if I don't, my mistake and I would be pretty happy of you could point out what I did wrong with those env variables.

Also, note that I'm not using a bitnami/mariadb container, I just use the classic mariadb container. Maybe that's why it doesn't work? But I tried without the "MAGENTO_USERNAME" and "MAGENTO_PASSWORD" variables, and magento managed to connect to the database...

Anyways, I won't be able to test it right now but I'll be on it tomorrow for sure.

Again, thanks for the answer.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by sheep0lata** [comment]
Hello,

I tried editing multiple things in my compose and .env files, and I finaly managed to find a solution.

It seems that Magento only accepts a "strong password" that matches the security standards of the app, which are "Please enter 7 or more characters, using both numeric and alphabetic." (When you try to update your password through the admin web interface).

This means that the app won't start unless a password that matches those standards is provided, so the installation script just restarts waiting for a valid password.

I feel a bit silly now that I have the solution, but I didn't find that information in any documentation and had to randomly find that solution...

So I added a number to my password and it works ! The app starts with the credentials I set in my .env file.

I'm closing this issue myself,

Thanks for the time you spent on my request !
