### ISSUE TITLE
[bitnami/postgressql] Allow to configure the uid of non-root postgres user

### ISSUE THREAD

**Issue by brpaz** [bitnami/containers#65827]
### Name and Version

bitnami/postgressql:16

### What is the problem this feature will solve?

Right now, the image has the non-root user with id 1001. This is a very low number (considering, Linux usually starts creating users at 1000). I have 3 users in my system, so 1001 id is taken.

### What is the feature you are proposing to solve the problem?

 It would be nice to be able to configure the uid. or at least change the default, to a higher number to reduce the chances of conflicts.

### What alternatives have you considered?

The workaround was for me to hardcode the uids for the users in the system, and let 1001 free for Postgres, but this is not ideal.

**Comment by st1111th** [comment]
Can we get updated links please? Less than a year after posting, they are already invalid.

[Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
[Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
[Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
