### ISSUE TITLE
Support for bitnami/cliclhouse on s390x

### ISSUE THREAD

**Issue by SantiagoOrtegaBrcm** [bitnami/containers#65859]
### Name and Version

bitnami/cliclhouse

### What is the problem this feature will solve?

Missing s390x support for ClickHouse

### What is the feature you are proposing to solve the problem?

Add s390x support for ClickHouse

### What alternatives have you considered?

Using other brand (e.g. Altinity)

**Comment by carrodher** [comment]
Hi, thank you for your suggestion. Unfortunately, at this moment the only supported architectures are ARM and AMD. In the short/mid-term there are no plans for supporting other architectures. If that changes at some point in the future, we will reopen this Issue to let you know.
