### ISSUE TITLE
Image SHA changed for bitnami/kubectl:1.30.0

### ISSUE THREAD

**Issue by medyagh** [bitnami/containers#66293]
### Name and Version

bitnami/kubectl:1.30.0

### What architecture are you using?

None

### What steps will reproduce the bug?

in minikube automation, we noticed the SHA for bitnami/kubectl:1.30.0 was changed

		"Kubectl": "bitnami/kubectl:1.30.0@sha256:b909f3a93813f25192bcb57f5c1e482d53ba01413db69c8143fca882e6e930e5",
		"Kubectl": "bitnami/kubectl:1.30.0@sha256:b3304501336a48b5f845d0897d6c5252c7b2e4f98a9a6fe1a94a96f92a3a2dc9",

This is not a good practice, if there is a change in an image there should be a new version of it, and this breaks miinikube too, because minikube verifies the expected SHA for the image, to ensure someone did not tamper with the image or push a different image ...

is there a valid reason that you had to do this ? is there a way to not do this in the future?

### What do you see instead?

not change image SHA after it is published, and instead publish the updates to a new image tag 

### Additional information

minikube PR https://github.com/kubernetes/minikube/pull/18806/files

**Comment by carrodher** [comment]
Bitnami uses **rolling tags** for its container images. To understand how this works, let's look at the tags for the Bitnami Kubectl container image:
- `1.27`, `1.27-debian-12`, `1.27.13`
- `1.28`, ...
- `1.29`, ...
- `1.30`, `1.30-debian-12`, `1.30.0`, `latest`

Focusing on the branch 1.30:
- The `latest` tag always points to the latest revision of the kubectl image.
- The `1.30-debian-12` tag points to the latest revision of Kubectl 1.30.z for Debian 12.
- The `1.30`<sup>1</sup> tag is a rolling tag that always points to the latest revision of Kubectl 1.30.z.
- The `1.30.0`<sup>1</sup> tag is a rolling tag that points to the latest revision of Kubectl 1.30.0. It will be updated with different revisions but only for Kubectl 1.30.0.

When Bitnami revises container images, typically to upgrade system packages, fix bugs, or improve system configuration, it also updates the container tags to point to the latest revision of the image. Therefore, the rolling tags above are dynamic; they will always point to the latest revision for the corresponding image.

For example, the 1.30.0 tag might point to Kubectl 1.30.0 revision 1 now but will refer to Kubectl 1.30.0 revision 2 when Bitnami next updates the container image. The suffix revision number (`-rX`) is incremented every time Bitnami releases an updated image version for the same application version.

What if you depend on a specific revision of an image? For these scenarios, Bitnami also attaches a **static (immutable) tag** to each revision. In this example, the `1.30.0-debian-12-r1` tag refers to Kubectl 1.30.0 revision 1, and using this tag ensures that users always get the same image every time.

Based on that, users need to choose the proper tag for each use case, some generic guidelines are:
- If you are using containers in a production environment (such as Kubernetes), Bitnami recommends using immutable tags. This ensures that your deployment is not affected if a new revision inadvertently breaks existing functionality.
- If you are using containers for development, Bitnami suggests using rolling tags. This ensures that you are always using the latest version. Rolling tags also make it easier to use a specific version of a development tool (such as bitnami/node:18 for Node.js 18).

<sup>1</sup> It is worth noting that any tags that do not explicitly specify a distribution should be assumed to refer to the base image used in the Bitnami Application Catalog, at this moment, Debian 12.
