### ISSUE TITLE
[mongodb-sharded] primary node can't be restarted

### ISSUE THREAD

**Issue by cten** [bitnami/containers#6635]
### Name and Version

bitnami/mongodb-sharded

### What steps will reproduce the bug?

1. Deploy mongodb-sharded helm chart
2. Restart (delete)/update the primary node

### What is the expected behavior?

mongodb process starts as expected. Secondary nodes work as expected.

### What do you see instead?

Secondary nodes start as expected but the primary node never actually starts the mongodb process. 
Logs look like this:
```
 16:19:29.00 INFO  ==> Setting node as primary
mongodb 16:19:29.02
mongodb 16:19:29.02 Welcome to the Bitnami mongodb-sharded container
mongodb 16:19:29.02 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 16:19:29.02 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 16:19:29.02
mongodb 16:19:29.03 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 16:19:29.05 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 16:19:29.08 INFO  ==> Initializing MongoDB Sharded...
mongodb 16:19:29.11 INFO  ==> Writing keyfile for replica set authentication...
mongodb 16:19:29.14 INFO  ==> Enabling authentication...
mongodb 16:19:29.15 INFO  ==> Deploying MongoDB Sharded with persisted data...
mongodb 16:19:29.19 DEBUG ==> Waiting for primary node...
mongodb 16:19:29.19 INFO  ==> Trying to connect to MongoDB server mongodb...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
```

processes running inside the pod are: 
```
I have no name!@mongodb-shard0-data-0:/$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
1001         1     0  0 16:19 ?        00:00:00 /bin/bash /entrypoint.sh /run.sh
1001        14     1  0 16:19 ?        00:00:00 /bin/bash /opt/bitnami/scripts/mongodb-sharded/setup.sh
1001       112     0  0 16:20 pts/0    00:00:00 bash
1001       119    14  0 16:20 ?        00:00:00 wait-for-port --host mongodb --timeout 10 27017
1001       124   112  0 16:21 pts/0    00:00:00 ps -ef
```

### Additional information

I found where I believe the issue is located: https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/5.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L43-L93

The function referenced in the link starts the mongo process on initial start but after turning the process [off](https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/5.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L72) it appears to [never](https://github.com/bitnami/containers/blob/main/bitnami/mongodb-sharded/5.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L73-L82) start it again. This causes the `mongodb_wait_for_node` function to timeout indefinitely.

**Comment by cten** [comment]
Apparently I needed to set MONGODB_SHELL_EXTRA_FLAGS, as the flags added with `mongodbExtraFlags` aren't picked up by mongosh nor liveness/readinessProbes.

**Comment by zhaileilei123** [comment]
@cten  I am also facing the same issue. I didn't understand what actions I should take to resolve this problem. Can you help me with the steps to address this issue?
