### ISSUE TITLE
Container not starting '/opt/bitnami/mysql/conf/my.cnf' is not writable'

### ISSUE THREAD

**Issue by anatol06** [bitnami/containers#66594]
### Name and Version

bitnami/mysql:8.1.0-debian-11-r57

### What architecture are you using?

amd64

### What steps will reproduce the bug?

saving the settings in starting the container in Plesk Obsidian.
The mapping is set in this way:
```
/bitnami/mysql/data			/var/docker/mysql81
/opt/bitnami/mysql/conf		/var/docker/mysql81_config
```
### What is the expected behavior?

the container does not start

### What do you see instead?

The log in Plesk:

Container does not start: The log:
```
[38;5;6mmysql [38;5;5m10:26:04.61 [0m
[38;5;6mmysql [38;5;5m10:26:04.61 [0m[1mWelcome to the Bitnami mysql container[0m
[38;5;6mmysql [38;5;5m10:26:04.61 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mmysql [38;5;5m10:26:04.61 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mmysql [38;5;5m10:26:04.61 [0m
[38;5;6mmysql [38;5;5m10:26:04.62 [0m[38;5;2mINFO [0m ==> ** Starting MySQL setup **
[38;5;6mmysql [38;5;5m10:26:04.63 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_*/MARIADB_* env vars
[38;5;6mmysql [38;5;5m10:26:04.63 [0m[38;5;2mINFO [0m ==> Initializing mysql database
[38;5;6mmysql [38;5;5m10:26:04.64 [0m[38;5;3mWARN [0m ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
[38;5;6mmysql [38;5;5m10:26:04.64 [0m[38;5;2mINFO [0m ==> Installing database
[38;5;6mmysql [38;5;5m10:26:05.07 [0m
[38;5;6mmysql [38;5;5m10:26:05.08 [0m[1mWelcome to the Bitnami mysql container[0m
[38;5;6mmysql [38;5;5m10:26:05.08 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mmysql [38;5;5m10:26:05.08 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mmysql [38;5;5m10:26:05.08 [0m
[38;5;6mmysql [38;5;5m10:26:05.08 [0m[38;5;2mINFO [0m ==> ** Starting MySQL setup **
[38;5;6mmysql [38;5;5m10:26:05.09 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_*/MARIADB_* env vars
```
### Additional information

Ubuntu 20.04.6 LTS
Plesk Obsidian Version 18.0.60

**Comment by anatol06** [comment]
These are settings in Plesk:

![image](https://github.com/bitnami/containers/assets/9899389/238263b4-e0ff-416b-bf89-0392a075f03e)

I have set the permissions for /var/docker/mysql81 and /var/docker/mysql81_config on ubuntu to 755 and now the container starts but just in background, the DBs are not avaiable.

There are the settings for a MySQL 8.0 container from MySQL which works perfectly but there are some strange warnings in logs and for this reason I would like to switch to bitnami:

![image](https://github.com/bitnami/containers/assets/9899389/691ff960-95f4-44db-811d-9a412443e916)

**Comment by carrodher** [comment]
Could you increase the logs' verbosity by setting the `BITNAMI_DEBUG` environment variable to `true`? Just in case it helps to detect the source of the issue.

**Comment by anatol06** [comment]
After much research, I discovered that Bitnami containers are non-root containers, started by default with a non-root user.
The mounted files and directories must have the proper permissions for the UID 1001. 
To make everything working properly I did in this way (if there are better solutions, please share):

Image: bitnami/mysql:8.0.36-debian-11-r20

Create directories on Ubuntu and set the rights:

```
cd /var/docker
mkdir mysql80 mysql80_config
sudo chmod -R 775 mysql80 mysql80_config
```
Container settings in Plesk Obsidian:

![image](https://github.com/bitnami/containers/assets/9899389/bff6025a-a236-41e9-9477-e4d3f5f1f71c)

Timezone: 'Europe/Berlin' is not accepted in my.cnf in this way:


```
[mysqld]
default_time_zone='Europe/Berlin'
```
When is set like this, the container starts in bakground and the quotes ('Europe/Berlin') are lost after container restart. 
So I found another way -  to set it as variable in Plesk, see the screenshot.

In container I created a custom file for MySQL Settings "my_custom.cnf". This should be the name according to Bitnami documentation. The path to this file I specified in mapping settings, in Plesk.


```
docker exec -it --user=0 mysql80 /bin/bash
touch /opt/bitnami/mysql/conf/my_custom.cnf
```

Is there any way to run the container as "root" using environment variable as I did for timezone?

**Comment by carrodher** [comment]
Yes, as you rightly said, Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
