### ISSUE TITLE
[RabbitMQ] Admin user creation only works if user is "guest"

### ISSUE THREAD

**Issue by claireleray-poclain** [bitnami/containers#6665]
### Name and Version

bitnami/rabbitmq:3.10.7-debian-11-r11

### What steps will reproduce the bug?

I'm installing the 10.3.5 Helm release with the values.yaml file pasted below.

### What is the expected behavior?

RabbitMQ should start, with a created admin user with login 'user' and password 'password'.

### What do you see instead?

The user created is guest/guest. If I use "guest" as the login in my values.yaml file, then the user created is guest/password. I have tried deleted the PVC associated with RabbitMQ, to no avail.

### Additional information

**values.yaml**
```
auth:
  username: user 
  password: password

service:
  type: LoadBalancer
  
replicaCount: 1

image:
  debug: true

ingress:
  enabled: true
  hostname: ${INGRESS_HOST_ADMIN}
  path: /rabbitmq(/|$)(.*)
  pathType: Prefix
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: "/$$2" # $ is escaped with $$

configuration: |-
  ## Delivery acknowledgment timeout set to 2 hours
  consumer_timeout = 7200000

```

**Comment by dgomezleon** [comment]
Hi @claireleray-poclain ,

The error is due to the `configuration` part. Try with this values.yaml:

```
auth:
  username: user 
  password: password

service:
  type: LoadBalancer
  
replicaCount: 1

image:
  debug: true

ingress:
  enabled: true
  hostname: ${INGRESS_HOST_ADMIN}
  path: /rabbitmq(/|$)(.*)
  pathType: Prefix
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: "/$$2" # $ is escaped with $$
```

**Comment by claireleray-poclain** [comment]
Hi @dgomezleon,

It does work without the `configuration` part. How can I still handle the consumer_timeout modification then ?

Best,
Claire

**Comment by dgomezleon** [comment]
As explained [here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#common-parameters), you should use:

```
extraConfiguration: |-
  ## Delivery acknowledgment timeout set to 2 hours
  consumer_timeout = 7200000
```
