### ISSUE TITLE
[bitnami/memcached] Docker build fails /bin/bash: line 1: /opt/bitnami/scripts/libcomponent.sh: No such file or directory

### ISSUE THREAD

**Issue by kadursandy** [bitnami/containers#6673]
### Name and Version

bitnami/memcached:1.6.15

### What steps will reproduce the bug?

I was trying to build bitnami/memcached:1.6.15 version, not the latest. Getting below error 
```
Error:
Step 6/18 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "memcached" "1.6.15-151" --checksum 5b2da0b4738d665f34b6617a56cd6daf1d555ea7e63cb5bdc9be6ba2113d2c7e
 ---> Running in 83d0618864c8
/bin/bash: line 1: /opt/bitnami/scripts/libcomponent.sh: No such file or directory
```
Please add libcomponent.sh file to https://github.com/bitnami/containers/tree/main/bitnami/memcached/1/debian-11/prebuildfs/opt/bitnami/scripts which is currently missing to build 1.6.15. 
No issue with building the 1.6.17 version.

steps to reproduce:
1. git clone https://github.com/bitnami/containers.git
2. cd containers/bitnami/memcached/1/debian-11
3. open file Dockerfile
4. search replace 1.6.17 to 1.6.15
5. `docker build -t bitnami:v1.6.15`
6. You get the error `no such file or dicrectory. /opt/bitnami/scripts/libcomponent.sh`

### What is the expected behavior?
memcached:v1.6.15 should be built without any issues

File missing libcomponent.sh file under containers/bitnami/memcached/1/debian-11/prebuildfs/opt/bitnami/scripts.
Please add this file to bitname repo under https://github.com/bitnami/containers/tree/main/bitnami/memcached/1/debian-11/prebuildfs/opt/bitnami/scripts

### What do you see instead?

Error while building the image version 1.6.15
```
/bin/bash: line 1: /opt/bitnami/scripts/libcomponent.sh: No such file or directory
```

**Comment by javsalgar** [comment]
Hi,

This is weird. We performed changes in the container Dockerfiles and now they don't include any reference to libcomponent.sh

https://github.com/bitnami/containers/blob/main/bitnami/memcached/1/debian-11/Dockerfile

Could you confirm that you are using the very latest version of the Dockerfile?

**Comment by brsolomon-deloitte** [comment]
It appears that `libcomponent.sh` was removed around the time that Bitnami switched to a mono-repo for image Dockerfiles.

Example for spark:

- Old: https://github.com/bitnami/bitnami-docker-spark/tree/master/3.3/debian-11/prebuildfs/opt/bitnami/scripts
- New: https://github.com/bitnami/containers/tree/main/bitnami/spark/3.3/debian-11/prebuildfs/opt/bitnami/scripts (script is absent)

We're also running into a build error related to this file being missing, though in our case slightly different cause.

In our case we are building a custom Spark image on top of the Bitnami image. To show a snippet of that,

```
FROM bitnami/spark:3.3.0-debian-11-r34
RUN set -eux \
    && . /opt/bitnami/scripts/libcomponent.sh \
    && component_unpack "python" "$PYTHON_VERSION" --checksum "$PYTHON_SHA256SUM" \
    && rm -f "${SPARK_JARS_BASEDIR}/aws-java-sdk-bundle-*.jar" \
```

This replaces the Python version used in the Spark image.

Now, I realize fully libcomponent.sh might be considered an "implementation detail" and was never guaranteed to be there in the first place, but it contained `component_unpack` which was useful for putting any arbitrary binaries into a custom image built on top of the Bitnami images.

**Comment by brsolomon-deloitte** [comment]
It looks like `component_unpack` only survived in one image in the new monorepo: https://github.com/bitnami/containers/search?q=component_unpack

**Comment by brsolomon-deloitte** [comment]
It looks like `component_unpack` has been replaced by repetitively calling `curl` in the [new monorepo version](https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/Dockerfile).

**Comment by brsolomon-deloitte** [comment]
Here is a commit where `libcomponent.sh` went bye-bye:

https://github.com/bitnami/containers/commit/95a94992cb26f4b1ef70e70c2f073840b4b4aed9

**Comment by javsalgar** [comment]
Hi,

Yes, we removed `component_unpack` in favour of the new approach. This is because we had different approaches between scratch and non-scratch containers. We wanted to unify it.

**Comment by brsolomon-deloitte** [comment]
Related to https://github.com/bitnami/containers/issues/10124

**Comment by kadursandy** [comment]
> Hi,
> 
> This is weird. We performed changes in the container Dockerfiles and now they don't include any reference to libcomponent.sh
> 
> https://github.com/bitnami/containers/blob/main/bitnami/memcached/1/debian-11/Dockerfile
> 
> Could you confirm that you are using the very latest version of the Dockerfile?

We are supposed to use this version only. If you suggest to use new/latest version then delete the old version and why do you support old version?

**Comment by javsalgar** [comment]
Hi!

I think I didn't understand the question correctly

> We are supposed to use this version only. If you suggest to use new/latest version then delete the old version and why do you support old version?

We are supporting the latest version of the branch, we don't support old versions of the container.

**Comment by kadursandy** [comment]
Ok, But if some users are using the old version then the issue will still persist. My suggestion is to add the missing file . Else someone using this version will unnecessarily waste time to troubleshoot.

**Comment by javsalgar** [comment]
Hi,

Could you please share with us the exact Dockerfile that triggers the error?
