### ISSUE TITLE
[bitnami/postgresql] requested WAL segment already removed

### ISSUE THREAD

**Issue by ql-isaac** [bitnami/containers#67054]
### Name and Version

bitnami/postgresql:16.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Based on the readme, I successfully created a replication cluster having one master and one slave. Recently, my slave node did not start properly due to some reason. After I fixed this issue, I restarted the slave node, and the log shows requested WAL segment has already been removed. How can I fix this issue?

### What do you see instead?

```
2024-05-07 07:29:53.786 CST [25682] LOG:  started streaming WAL from primary at 4/7E000000 on timeline 1
2024-05-07 07:29:53.786 CST [25682] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000001000000040000007E has already been removed
2024-05-07 07:29:53.786 CST [98] LOG:  waiting for WAL to become available at 4/7E002000
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
