### ISSUE TITLE
[bitnami/sealed-secrets-kubeseal] sealed-secrets-kubeseal container start not possible

### ISSUE THREAD

**Issue by gimler** [bitnami/containers#67059]
### Name and Version

bitnami/sealed-secrets-kubeseal:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using the docs https://github.com/bitnami/containers/tree/main/bitnami/sealed-secrets-kubeseal

```
docker run --rm --name sealed-secrets-kubeseal bitnami/sealed-secrets-kubeseal:latest
```

output
```
error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### What is the expected behavior?

runnable cli

### What do you see instead?

error

**Comment by javsalgar** [comment]
Hi,

Please note that this container is meant to be run on a Kubernetes installation, as it requires accessing a kube-apiserver. If you run it via a docker installation you need to ensure that a kube-apiserver instance is available and set the KUBERNETES_MASTER env var.
