### ISSUE TITLE
[bitnami/elasticsearch] SingleNode healthcheck failing on IPv6 environments

### ISSUE THREAD

**Issue by rgaduput** [bitnami/containers#67081]
### Name and Version

bitnami/elasticsearch:8.8.1-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure deployment with masterOnly set to true
2. Disable data, ingest and coordinating roles deployment
3. Deploy bitnami elastic chart on pure IPv6 cluster
4. Healthceck of readiness probe will fail

### What is the expected behavior?

Healthcheck passes and container comes up.

### What do you see instead?

`  Warning  Unhealthy  26m                    kubelet            Readiness probe failed: ^[[38;5;6melasticsearch ^[[38;5;5m07:30:53.29 ^[`

### Additional information

Originally raised at https://github.com/bitnami/charts/issues/22880

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
