### ISSUE TITLE
NginxProxyManager (Let's Encrypt) + Moodle

### ISSUE THREAD

**Issue by ezeik** [bitnami/containers#67106]
### Name and Version

bitnami/moodle:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When going to this address, the error ERR_SSL_UNRECOGNIZED_NAME_ALERT is displayed

### What do you see instead?

Help me solve the problem) Installed Moodle+MariaDB in Docker. Everything worked, but I can’t change the certificate; during installation, a certificate is issued for example.com. In NPM I created a ProxyHost with the address moodle.mice.com. When going to this address, the error ERR_SSL_UNRECOGNIZED_NAME_ALERT is displayed

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
