### ISSUE TITLE
mongodb:5.0.X images not updated to 5.0.25 and 5.0.26 any more

### ISSUE THREAD

**Issue by weber-d** [bitnami/containers#67122]
### Name and Version

 bitnami/mongodb:5.0.24

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm searching in the docker registry for the latest 5.0.X image: https://hub.docker.com/r/bitnami/mongodb/tags?page=&page_size=&ordering=&name=5.0.

### What is the expected behavior?

Having 5.0.25 and 5.0.26 available, since 5.0.25 was released in feb and 5.0.26 in mar 2024: https://www.mongodb.com/docs/manual/release-notes/5.0/#5.0.26---mar-26--2024

### What do you see instead?

The latest version is 5.0.24. When searching for newer versions like 5.0.25, it seems that there is no tag for this release.

### Additional information

I had a look in the source repo and the Mongodb folder https://github.com/bitnami/containers/tree/main/bitnami/mongodb only contains a Mongodb 7 version? https://github.com/bitnami/containers/tree/main/bitnami/mongodb/7.0/debian-12

Mongodb 5.0 is still officially supported, also 6.0: https://www.mongodb.com/legal/support-policy/lifecycles
Since Bitnami has tags for 5.0 and 6.0, it looks like you're following a supported version, which makes sense. But it looks like updating 5.0 and 6.0 had stopped since the latest Bitnami tag for 6.0 also is 6.0.13, where 6.0.15 is available: https://www.mongodb.com/docs/manual/release-notes/6.0/#6.0.15---apr-18--2024

**Comment by carrodher** [comment]
Please note MongoDB doesn't provide binaries for Debian 12 which is the OS used by Bitnami Application Catalog, see https://www.mongodb.com/try/download/community:
![Screenshot 2024-05-18 at 18 32 21](https://github.com/bitnami/containers/assets/13216600/edfcab95-1a1c-4761-8bfd-1063526dfdad)

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by SerPenTargo** [comment]
Same problem. There is no docker image of mongodb version 5.0.26. Same as 5.0.25.

[rocket@rocket ~]$ docker compose up -d
[+] Running 1/1
 ✘ mongodb Error manifest for bitnami/mongodb:5.0.26 not found: manifest unknown: manifest unknown                                                                                             Error response from daemon: manifest for bitnami/mongodb:5.0.26 not found: manifest unknown: manifest unknown

**Comment by weber-d** [comment]
When Bitnami offers Debian 11 images too, why not simply keeping Debian 11 instead of Debian 12 as base image? At least for those MongoDB versions who doesn't support Debian 12. So users could get upgrades from you like before. Now users are waiting for applied patches, also security fixes, to finally finding out that Bitnami just doesn't support all versions supported by MongoDB any more.

The only way for us users now is either upgrading MongoDB 5 & 6 to 7, if supported by the application. Or creating a custom k8s helm chart based on [the official MongoDB images](https://hub.docker.com/_/mongo)...

**Comment by carrodher** [comment]
The Bitnami catalog is based on a single distro version which we update according to the EOL policies of Debian, unfortunately in Bitnami there is no support for multiple distro versions. The catalog based on various base images, such as Debian 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images is provided via [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
