### ISSUE TITLE
[bitnami/postgresql-repmgr] Run postgres without repmgr

### ISSUE THREAD

**Issue by Floppy012** [bitnami/containers#67215]
### Name and Version

bitnami/postgresql-repmgr:16

### What is the problem this feature will solve?

In case something went wrong with the dbms itself. A flag or environment variable that allows to just start postgres would be helpful, because if started with repmgr it constantly restarts the container when it cannot connect to postgres.

### What is the feature you are proposing to solve the problem?

If a CLI flag or environment variable is present then the init script starts just postgres without repmgr.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! We have PostgreSQL container with repmgr, in case this covers your use case better. About adding a flag to start without repmgr, I will forward it to the team but, as it is not a critical feature, we cannot guarantee an ETA. However, contributions are welcome in case you want to submit a PR adding the env vars.

**Comment by Floppy012** [comment]
> We have PostgreSQL container with repmgr, in case this covers your use case better

Which one is it? I'm currently using `bitnami/postgresql-repmgr:16`.

> we cannot guarantee an ETA

No worries. I was just testing and changed the domain names of the pg nodes which caused repmgr no longer to find its local DB so it just kept restarting. Is there a recommended recovery procedure for such a case? (I guess setting the old hostname in hosts would've fixed the issue) I've noticed that repmgr uses the postgres instance to store information about the cluster. But lets say for example I wanted to change the password of the repmgr user. I'd have to update that in the config and as it looks these values are also written to the `repmgr.nodes` table. Causing a chicken-egg problem if I've not missed anything.

**Comment by javsalgar** [comment]
Sorry, I meant a PostgreSQL without repmgr, which is bitnami/postgresql. 

> No worries. I was just testing and changed the domain names of the pg nodes which caused repmgr no longer to find its local DB so it just kept restarting. Is there a recommended recovery procedure for such a case?

For situations where you need to perform a manual adjustment the helm chart has a diagnosticMode.enabled=true value that will deploy all pods with a sleep infinity, so you can enter and perform any adjustments required.

**Comment by Floppy012** [comment]
Not stale

**Comment by Floppy012** [comment]
Welp. That bot seems to work great. @javsalgar since this would still be useful to see. Even if it does not have priority, can you please reopen this?
