### ISSUE TITLE
bitnami/pgpool：How to backup database data?

### ISSUE THREAD

**Issue by Wj-creat** [bitnami/containers#67219]
### Name and Version

bitnami/pgpool

### What architecture are you using?

arm64

### What steps will reproduce the bug?

How to backup database data?
When I use pg_dump, it shows：`pg_dump: command not found`.
Can't pgpool use pg_dump？

### What do you see instead?
```
pg_dump: command not found
```

**Comment by alemorcuq** [comment]
What version are you using? `pg_dump` should be located under `/opt/bitnami/postgresql/bin`:

```
$ ls -la /opt/bitnami/postgresql/bin
total 1512
drwxr-xr-x 2 root root   4096 May 13 16:52 .
drwxr-xr-x 5 root root   4096 May 13 20:18 ..
-rwxr-xr-x 1 root root 464176 May 13 16:40 pg_dump
-rwxr-xr-x 1 root root 135512 May 13 16:40 pg_dumpall
-rwxr-xr-x 1 root root 201312 May 13 16:40 pg_restore
-rwxr-xr-x 1 root root 725704 May 13 16:40 psql
```

And that directory should be present in the PATH environment variable:

```
$ echo $PATH
/opt/bitnami/pgpool/bin:/opt/bitnami/common/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/common/sbin:/opt/bitnami/pgpool/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
