### ISSUE TITLE
[bitnami/postgresql] How to Install postgresql-16-pgrouting Based on an Image

### ISSUE THREAD

**Issue by zhaoquan-lin** [bitnami/containers#67228]
### Name and Version

bitnami/postgresql-repmgr:16

### What is the problem this feature will solve?

How to Install postgresql-16-pgrouting Based on an Image

### What is the feature you are proposing to solve the problem?

no

**Comment by javsalgar** [comment]
Hi,

For this situation you may need to fork the postgresql image and build the extension on your own following the upstream pgrouting compilation instructions.

**Comment by zhaoquan-lin** [comment]
> Hi,
> 
> For this situation you may need to fork the postgresql image and build the extension on your own following the upstream pgrouting compilation instructions.

Hello, thank you very much for your help, but this might be a bit challenging for a beginner like me. Could you provide me with more in-depth assistance to resolve this issue?

**Comment by javsalgar** [comment]
Hi,

This comment may help you with the steps. https://github.com/bitnami/containers/issues/32677#issuecomment-1537857717
