### ISSUE TITLE
[bitnami/suitecrm] SuiteCRM container upgrade from 8.3 to 8.6 shows no changes

### ISSUE THREAD

**Issue by Sharp404** [bitnami/containers#67222]
### Name and Version

bitnami/suitecrm:8.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Updated the Docker Compose file to use the new image version `bitnami/suitecrm:8.6.0` from `bitnami/suitecrm:8.3.0`.
2. Executed the following commands to update and redeploy the stack :
```
docker stack rm <STACK_NAME>
docker stack deploy -c <file.yml> <STACK_NAME>
```
3. Observed the running containers using docker ps to confirm they are using the new image version `bitnami/suitecrm:8.6.0`.
Then launched the web app and enter the container to see if the VERSION file changed.

### What is the expected behavior?

After updating the container image from version 8.3.0 to 8.6.0, the SuiteCRM application should reflect the changes and display the updated version 8.6.0. This includes any new features, improvements, and bug fixes that are part of the release.

### What do you see instead?

Despite the stack restarting and the container showing the correct image version `bitnami/suitecrm:8.6.0`, there are no visible changes in the application. The application version displayed is still `8.3.0`, and I don't see new features or improvements from version 8.6.0 are observed.

### Additional information

I tried to clear the app cache `rm -rf cache/*` but this didn't resolve the issue.
I also checked the container logs and nothing indicate a problem with the upgrade process.

**Comment by carrodher** [comment]
Are you mounting any volume where the configuration from the previous installation/version is persisted?

**Comment by Sharp404** [comment]
Yes, I have a volume with pre-existing data and custom configurations

**Comment by carrodher** [comment]
If you deploy the new version from scratch (without that volume), are you also facing that issue?

**Comment by Sharp404** [comment]
I just did, and I have no issue. The version 8.6.0 is displayed.

<img width="954" alt="suitecrm_8_6" src="https://github.com/bitnami/containers/assets/73996767/e75134d5-fbac-4d14-99d4-8f3aef9d1880">

**Comment by carrodher** [comment]
Since the entire directory of the SuiteCRM application is persisted. To update the application, you will need to do it manually. SuiteCRM does not offer any out-of-the-box tool to upgrade the database schema after an upgrade, so it will not be done automatically.

**Comment by Sharp404** [comment]
That explain a lot, thanks for your answer ! I'll upgrade it manually then
