### ISSUE TITLE
[bitnami/odoo] Odoo should have list_db set to False (or --no-database-list)

### ISSUE THREAD

**Issue by OdyX** [bitnami/containers#67349]
### Name and Version

bitnami/odoo:16.0.20240315-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When deploying an odoo with https://github.com/bitnami/charts/tree/main/bitnami/odoo, the `/web/database/manager` endpoint will be accessible and allow new databases' setup.

### What is the expected behavior?

According to https://www.odoo.com/documentation/16.0/administration/on_premise/deploy.html?highlight=list_db%20no-database-list#security :
> Once your db_name and db_filter are configured and only match a single database per hostname, you should set list_db configuration option to False, to prevent listing databases entirely, and to block access to the database management screens (this is also exposed as the [--no-database-list](https://www.odoo.com/documentation/16.0/developer/reference/cli.html#cmdoption-odoo-bin-no-database-list) command-line option)

This is precisely the state post-initial configuration.

### What do you see instead?

The `/web/database/manager` is accessible, and shouldn't.

### Additional information

It's possible to "fix" this by setting:
```helm
odoo:
  command:
    - "/opt/bitnami/scripts/odoo/entrypoint.sh"
    - "/opt/bitnami/scripts/odoo/run.sh"
    - --no-database-list
```

It would be better if an environment variable `ODOO_LIST_DB` could be set to True (with a default to False).

**Comment by jotamartos** [comment]
Hi @OdyX,

You are right, you can overwrite the command in the container to add any flag you want 

```
  odoo:
    image: docker.io/bitnami/odoo:17
    command:
      - "/opt/bitnami/scripts/odoo/run.sh"
      - --no-database-list
...
```

>Note: You do not need to add the entrypoint line there

However, adding a new env var to configure that is a great idea, would you like to contribute? You can follow [our guidelines](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) to do so and the whole community will benefit from that. You will need to make the following changes:

- Add the new env var in the odoo-env.sh file: https://github.com/bitnami/containers/blob/main/bitnami/odoo/17/debian-12/rootfs/opt/bitnami/scripts/odoo-env.sh
- Use the odoo_conf_set method to edit the [list_db parameter in the configuration file](https://github.com/bitnami/containers/blob/main/bitnami/odoo/17/debian-12/rootfs/opt/bitnami/scripts/odoo/bitnami-templates/odoo.conf.tpl#L25). You will need to edit the libodoo.sh file around here: https://github.com/bitnami/containers/blob/main/bitnami/odoo/17/debian-12/rootfs/opt/bitnami/scripts/libodoo.sh#L139
- Please add some validations as well to confirm that the env var contains valid values

**Comment by OdyX** [comment]
That's really not cool @github-actions… I proposed a PR, and it had no review so far.

**Comment by jotamartos** [comment]
Sorry for the delay in reviewing the PR and thanks for your contribution. We will review it soon and will get back to you.
