### ISSUE TITLE
[bitnami/apache] mod_session_crypto.so missing in the apache2 image

### ISSUE THREAD

**Issue by topfer** [bitnami/containers#67365]
### Name and Version

bitnami/apache:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Apache2 image is missing /opt/bitnami/apache/modules/mod_session_crypto.so
Any attempt to enable this module fails.
As far as I can see the mod_session_crypto.so is by default included in the latest apache2 distro

### What is the expected behavior?

LoadModule session_crypto_module modules/mod_session_crypto.so in httpd.conf should succeed

### What do you see instead?

Apache2 service fails to start if module is neabled in config

### Additional information

Nothing else

**Comment by rafariossaa** [comment]
Hi,
  We are studying this case, we will be back as soon as we have an answer.
  We select what to include on several factors. Could you provide further information in you use case ?
