### ISSUE TITLE
[bitnami/postgresql-repmgr]  After a 3-node cluster, simultaneous restart of all nodes resulted in failure to start properly.

### ISSUE THREAD

**Issue by kwenzh** [bitnami/containers#67372]
### Name and Version

bitnami/postgresql-repmgr:15.5.0-debian-11-r15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy a 3 node postgres cluster  in k8s v1.23, deploy in static pod mode
2. check it work right, there are one primary and two standby
3. stop postgres in each node, almost at the same time
4. check each postgres has stop
5. start each postgres, almost at the same time
6. check each postgres status 

### What is the expected behavior?

The postgres cluster can recover into healthz

### What do you see instead?

each pg pod in crash, can not election the primary

pg pod exit log
```
[2024-05-31 18:54:06] [ERROR] unable connect to upstream node (ID: 2337678), terminating
[2024-05-31 18:54:06] [HINT] upstream node must be running before repmgrd can start
[2024-05-31 18:54:06] [INFO] repmgrd terminating...
```

### Additional information

```
wal_log_hints = 'on'

reconnect_attempts='24'
reconnect_interval='5'

node_rejoin_timeout=300
```

**Comment by kwenzh** [comment]
For example, there are ABC nodes.   Before they are all shut down, C is the master node.   After they are pulled up at the same time, C is not running right.   After B is started, it cannot find the master node.   repmgr directly runs the postgres process in B,    After C is started in this short period of time, it connects to B's 5432 service and finds that the master is C. The unfiltered IP address is C itslef, which causes an attempt to connect but fails to connect, resulting in a circular dependency between B and C.

**Comment by kwenzh** [comment]
only check primary node is itself  in https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh#L224
![image](https://github.com/bitnami/containers/assets/38367518/43882c4e-b511-4b1a-8e41-8f879d823150)

but no check itself in https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh#L240

when repmgr get primary node is itself, from other nodes postgres service, it retry connect self postgres serivce, but itself is not running ready

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kwenzh** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

look at this  https://github.com/bitnami/containers/pull/67370

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by kwenzh** [comment]
> Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.
> 
> Your contribution is greatly appreciated!

Feel free to reach out if you have any questions or need assistance.
