### ISSUE TITLE
[bitnami/postgresql-repmgr] set env  REPMGR_PRIMARY_HOST equal value  in a three cluster, seems crash

### ISSUE THREAD

**Issue by kwenzh** [bitnami/containers#67391]
### Name and Version

bitnami/postgresql-repmgr:15.5.0-debian-11-r15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In k8s, we want get a ha postgres cluster with repmgr, deplot static pod, use hostnetork
1.  create 3 single pg node, for example : pg-pod-A  , pg-pod-B, pg-pod-C, In the Beginning， echo pg pod set env `REPMGR_PRIMARY_HOST` is itself ip,
2.   Select one of them as the genesis, for example A,  A also is primary node, 
3.  update  B, C  env `REPMGR_PRIMARY_HOST` value to pg-pod-A ip
4.  update  A, B, C  env `REPMGR_PARTNER_NODES` value  is "pg-pod-A-ip, pg-pod-B-ip, pg-pod-C-ip"
5.  Add B and C to the A, 
6.  now we get a 3 node postgres cluster, a primary  and to standby
7.  Triggering active/standby switchover。 let  primary from pg-pod-A to pg-pod-B
8.  go on make a change，   Restart the machine almost at the same time, and then pull up the recovery
9.  

### What is the expected behavior?

the postgres cluster is work healthz

### What do you see instead?

1.  in pg-pod-B:  also try to connect pg-pod-A, B get primary ip from env `REPMGR_PRIMARY_HOST`. the run code with function librepmgr.sh `repmgr_wait_primary_node`
2.  in pg-pod-A:  env primary ip is itself, A running goahead, but crash after repmgr starting, then postgres process crash.  i check exit code1  in repmgr-physica.c  function `monitor_streaming_standby`,  error log:
```
	close_connection(&upstream_conn);
		log_error(_("unable connect to upstream node (ID: %i), terminating"),
				  local_node_info.upstream_node_id);
		log_hint(_("upstream node must be running before repmgrd can start"));

		terminate(ERR_DB_CONN);
```
3.  in pg-pod-C, I saw something similar to the pg-pod-B

### Additional information

i make a test , set each pod env `REPMGR_PRIMARY_HOST` value is itself, like `REPMGR_NODE_NETWORK_NAME`, such as

```
pg-pod A :  REPMGR_PRIMARY_HOST=A-ip
pg-pod B:    REPMGR_PRIMARY_HOST=B-ip
pg-pod C:    REPMGR_PRIMARY_HOST=C-ip
```

After making the changes, they were clustered and restarted at the same time, and it worked normally. 

Does this tell me？do not change env `REPMGR_PRIMARY_HOST` value, when i create a cluster with 3 single node ?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
