### ISSUE TITLE
[Discourse] Issues with Adminstrative Reports (Docker)

### ISSUE THREAD

**Issue by givanhoe** [bitnami/containers#67395]
### Describe your issue as much as you can

I am facing issues with creating Administrative Reports (Admin > Reports).
Currently, Discourse is run via Docker in Bitnami Image bitnami/discourse:3 (sha256:cd08d44916aa10d5aea8f35067dccb359c8e3ffe59ebeef95c79ae72d8e169ef) with Discourse Version 3.2.2 (747ecc1f8c)

Creating the report via Admin > Reports (e.g. report type "Admin Logins", but same for all other report types) > Export, I get 

`Export initiated, you will be notified via message when the process is complete.`

and receive a notification with the download link in my inbox in Discourse.

The link is like [HOST]/uploads/short-url/xjX8AIIuhBIbT73ZS3Ku5mphZ1S.zip but just leads to an error message

>Oops
>
>The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.
>
>Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.
>
>No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.

Log shows 
```
discourse-1   | Started GET "/uploads/short-url/xjX8AIIuhBIbT73ZS3Ku5mphZ1S.zip" for 10.233.214.12 at 2024-05-30 08:41:07 +0000
discourse-1   | Processing by UploadsController#show_short as ZIP
discourse-1   |   Parameters: {"base62"=>"xjX8AIIuhBIbT73ZS3Ku5mphZ1S", "extension"=>"zip"}
discourse-1   | Sent file /opt/bitnami/discourse/public/uploads/default/original/1X/e9892bd4ad84e88b96657da66761e362b34f5ff0.zip (0.2ms)
discourse-1   | Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms | Allocations: 2108)
discourse-1   | ActionController::MissingFile (Cannot read file /opt/bitnami/discourse/public/uploads/default/original/1X/e9892bd4ad84e88b96657da66761e362b34f5ff0.zip)
discourse-1   | app/controllers/uploads_controller.rb:350:in `send_file_local_upload'
discourse-1   | app/controllers/uploads_controller.rb:132:in `show_short'
discourse-1   | app/controllers/application_controller.rb:423:in `block in with_resolved_locale'
discourse-1   | app/controllers/application_controller.rb:423:in `with_resolved_locale'
discourse-1   | lib/middleware/omniauth_bypass_middleware.rb:64:in `call'
discourse-1   | lib/content_security_policy/middleware.rb:12:in `call'
discourse-1   | lib/middleware/anonymous_cache.rb:393:in `call'
discourse-1   | lib/middleware/gtm_script_nonce_injector.rb:10:in `call'
discourse-1   | config/initializers/008-rack-cors.rb:14:in `call'
discourse-1   | config/initializers/100-quiet_logger.rb:20:in `call'
discourse-1   | config/initializers/100-silence_logger.rb:29:in `call'
discourse-1   | lib/middleware/enforce_hostname.rb:24:in `call'
discourse-1   | lib/middleware/request_tracker.rb:236:in `call'
discourse-1   | Started POST "/presence/update" for 10.233.214.12 at 2024-05-30 08:41:07 +0000
discourse-1   | Processing by PresenceController#update as */*
discourse-1   |   Parameters: {"client_id"=>"b1f2ca4adacf46019368beeee7f94dfb", "leave_channels"=>["/chat-user/core/1"], "authenticity_token"=>"562p6Ud_0IexZlKK-zfuqQTl3y8O5Qaz8Q_9wJWXFBTmu1PA6MIheyhJZBNoA3uuoDZuTtAHlAbQp5Gw1kDv-A"}
discourse-1   | Completed 200 OK in 557ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 125014)
```

I checked the volume and no file got created, so at least the issue, that no file can be send is understood.
But why no file got created?

Attachments to post can be found in the respective mounted volumes (/bitnami/discourse/public/uploads/default/original/1X).

I checked the discourse docker version and there Admin Reports work fine.

So I assume there is an issue either with the Bitnami image or my deployment.

Part of my docker-compose.yml
```yaml
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      # - '80:3000'
      - '9080:3000'
    volumes:
      # - 'discourse_data:/bitnami/discourse'
      - ./persistence/discourse:/bitnami/discourse'
...
  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
      # - ./persistence/sidekiq:/bitnami/discourse'
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by givanhoe** [comment]
Thank you,
I'll try to find another solution.
