### ISSUE TITLE
[bitnami/php-fpm] AWS public ECR image has explicity platform in manifest breaking arm64 compatibility

### ISSUE THREAD

**Issue by bzanchettin** [bitnami/containers#67400]
### Name and Version

bitnami/php-fpm:8.3.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

pull image without explicit arch from public.ecr.aws repository from a mac (arm)

### What is the expected behavior?

Since bitnami does not support arm64 on public.ecr.aws it should pull the amd64 one letting mac user use rosetta compatibility layer

### What do you see instead?

fail saying platform is not supported by manifest

### Additional information

I compared 8.3.6 and 8.3.7 manifest and here are the differences:
```console
$ docker manifest inspect public.ecr.aws/bitnami/php-fpm:8.3.6
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 6933,
		"digest": "sha256:a8ee99d2f197c0c08cc9a6b28a013a6649e27ac8f419b0ee7c08abd009e20686"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 110330821,
			"digest": "sha256:26cb6a2e87974a84a4d9e82f74cc9f38b941da5f3875ea053c321cba42252125"
		}
	]
}
```

```console
$ docker manifest inspect public.ecr.aws/bitnami/php-fpm:8.3.7
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 430,
         "digest": "sha256:82447ad70bcb755415adc23f43d9b0a955f9063d4bf0816b1976699e20fba6e7",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

I suspect that the 8.3.7 manifest should not have a `platform` section and it confuses docker pulls on arm64.
8.3.6 works as expected.

**Comment by javsalgar** [comment]
Hi,

I asked the team and it seems it's because we moved to the manifest version v2, which requires you to specify the arch when pulling an image different from the host target arch.

**Comment by bzanchettin** [comment]
Consider that this will break macOS users/automations on AWS ECR repository.
One easy solution would be to provide arm support on AWS ECR repository 😄 
Anyway, is not a big deal to specify the arch.
