### ISSUE TITLE
[bitnami/milvus] run in docker

### ISSUE THREAD

**Issue by 12341234-yangboran** [bitnami/containers#67542]
### Name and Version

bitnami/milvus:latest

### What is the problem this feature will solve?

![image](https://github.com/bitnami/containers/assets/74187378/7992ac5c-2e47-4d64-8104-2150ff7b0bb8)

### What is the feature you are proposing to solve the problem?

Immediate start command

**Comment by javsalgar** [comment]
Currently, we did not set any default milvus subcommand, so you would need to set `run` in your docker run command. Would you like to submit a PR setting a CMD by default in the Dockerfile?
