### ISSUE TITLE
[bitnami/ejbca] Clarification on Default EJBCA Version and Selection Process

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#67726]
### Name and Version

bitnami/ejbca:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I hope this message finds you well.

I am reaching out to seek clarification regarding the default version of EJBCA that is available for download and use. Specifically, I would like to know:

1. Is the default version of EJBCA the commercial version or the community version?
1. How can one select between the commercial and community versions of EJBCA?

Understanding this will help us in making an informed decision about which version to implement for our project.

### What do you see instead?

N/A

**Comment by javsalgar** [comment]
Hi,

We are only distributing the community version of EJBCA, as we cannot distribute commercial EJBCA for license reasons.
