### ISSUE TITLE
[bitnami/keycloak] Reporting vulnerability in Keycloak container

### ISSUE THREAD

**Issue by anshulgangrade** [bitnami/containers#67740]
### Name and Version

bitnami/keycloak:24.0.5-debian-12-r0

### What is the problem this feature will solve?

We are running trivy scan to find out vulnerabilities in keycloak container. we want it to fix it. 

[bitnami_keycloak_24.0.5-debian-12-r0.pdf](https://github.com/user-attachments/files/15760048/bitnami_keycloak_24.0.5-debian-12-r0.pdf)

### What is the feature you are proposing to solve the problem?

remediating the CVEs reported.

**Comment by anshulgangrade** [comment]
If I have to send this report to any email id, then let me know the email IDs. I can send the instructions how I have scanned the reports

**Comment by javsalgar** [comment]
Hi,

These are dependencies that are managed by the upstream keycloak project. As soon as they release a new version updating these components, we will release them as well. Did you report the upstream keycloak project?
