### ISSUE TITLE
[bitnami/keycloak] upgrade to 25.0.0

### ISSUE THREAD

**Issue by afgarcia86** [bitnami/containers#67751]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Latest features and fixes from Keycloak

### What is the feature you are proposing to solve the problem?

Building an image using the latest version of Keycloak

**Comment by javsalgar** [comment]
Hi!

Thank you for the request! As this is a new major, it normally takes a bit more time from our side to have it released. As soon as it is released we will notify the community.

**Comment by tanadeau** [comment]
FYI: Keycloak-config-cli just merged support for Keycloak 25 (see https://github.com/adorsys/keycloak-config-cli/issues/1050). I believe that's a blocker for the helm chart at least.

**Comment by paltaa** [comment]
For tracking the helm chart merge, is it in this issue or should another issue be created in the helm charts repo?

**Comment by carrodher** [comment]
It does not need a different issue for the Helm chart, we will notify you here since both processes are very coupled.

**Comment by tanadeau** [comment]
Any updates on the upgrade?

**Comment by greyarch** [comment]
Hey guys, do you have an idea, when approximately will this release?

**Comment by antikalk** [comment]
A new helm chart version 22.0.0 and also an image for keycloak 25.0.2 appeared. At least for the image the code in the `bitnami/containers` repository is not yet updated on main even though the image seems to be available.

**Comment by alemorcuq** [comment]
Closing this as Keycloak 25 containers and chart have been released
