### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by careybaird** [bitnami/containers#67772]
### Name and Version

bitnami/debian

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to build a debian image. The build fails due to missing packages (error log message: curl: (22) The requested URL returned error: 404 Not Found)

The package missing is: https://downloads.bitnami.com/files/stacksmith/php-8.1.4-10-linux-amd64-debian-10.tar.gz

This link is redirected, but previously allowed download of the image.

### What is the expected behavior?

Download link works.

### What do you see instead?

A redirect to bitnami homepage

**Comment by careybaird** [comment]
This is also missing:

https://downloads.bitnami.com/files/stacksmith/libphp-8.1.4-0-linux-amd64-debian-10.tar.gz

**Comment by javsalgar** [comment]
Thank you so much for reporting! I contacted our internal team to recover that tarball.

**Comment by careybaird** [comment]
Thank you @javsalgar , that link is now working again.

These ones are also missing:

https://downloads.bitnami.com/files/stacksmith/apache-2.4.51-7-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/mysql-client-10.3.32-0-linux-amd64-debian-10.tar.gz

**Comment by carrodher** [comment]
Hi, both files should be now restored.
