### ISSUE TITLE
Bitnami image , Failed to send email - How to fix - ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-495) Failed to send email   java.lang.NullPointerException "

### ISSUE THREAD

**Issue by richduvatti** [bitnami/containers#67817]
### Describe your issue as much as you can

ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-495) Failed to send email
  java.lang.NullPointerException "

The connection is the ERROR we are getting - it shows   "  2024-06-06 18:35:55,774 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-495) Failed to send email
  java.lang.NullPointerException "

**Comment by gongomgra** [comment]
Hi @richduvatti, @ejbest,

If you are having issues sending emails from the web UI only, I understand it is an issue of Keycloak itself. Can you open a new question in their official forums? Apart from that, can you share the way you are starting/configuring SMTP settings on your side and more lines of the error trace? Are you using the container directly or via the Helm chart?

**Comment by ejbest** [comment]
Here was the fix - needed to our cert to our trusted keystore in the Dockerfile and has been working solid - thank you everyone  

#copy it into the java keystore
RUN /opt/bitnami/java/bin/keytool \
    -keystore /opt/bitnami/java/lib/security/cacerts \
    -storepass ${KEYSTORE_PASS} \
    -trustcacerts \
    -noprompt \
    -importcert \
    -alias mycert 
    -file /usr/local/share/ca-certificates/myRootCA.crt


This is SOLVED - thank you
