### ISSUE TITLE
[bitnami/logstash] Where can I find the dockerfile for version 7.10.2

### ISSUE THREAD

**Issue by matchseller** [bitnami/containers#67944]
### Name and Version

bitnami/logstash:7.10.2

### What architecture are you using?

None

### What steps will reproduce the bug?

As title

### What do you see instead?

nothing

**Comment by javsalgar** [comment]
Hi,

You may need to go through the history of the repository and find the version you are looking for. 

```
git log --oneline bitnami/logstash/ | grep 7.10
```

Then you can execute git checkout to the proper commit ID.

**Comment by matchseller** [comment]
> Hi,
> 
> You may need to go through the history of the repository and find the version you are looking for.
> 
> ```
> git log --oneline bitnami/logstash/ | grep 7.10
> ```
> 
> Then you can execute git checkout to the proper commit ID.

So,where can I find the dockerfile for kibana version 7.10.2

**Comment by matchseller** [comment]
> Hi,
> 
> You may need to go through the history of the repository and find the version you are looking for.
> 
> ```
> git log --oneline bitnami/logstash/ | grep 7.10
> ```
> 
> Then you can execute git checkout to the proper commit ID.

Thank you very much

**Comment by matchseller** [comment]
![image](https://github.com/bitnami/containers/assets/30618552/e4c05dff-8e4b-4aa6-aee7-019ea86daab5)
Hi,where can i find this package?

**Comment by javsalgar** [comment]
Looking at the script, I believe it gets it from downloads.bitnami.com

**Comment by matchseller** [comment]
> Looking at the script, I believe it gets it from downloads.bitnami.com


I have read it and the download address in the script is wrong and will redirect to the bitnami homepage. The download address I got is this: https://downloads.bitnami.com/files/stacksmith/java-11.0.10-0-linux-amd64-debian-10.tar.gz

**Comment by carrodher** [comment]
That tarball should be now available, can you retry?

**Comment by matchseller** [comment]
> That tarball should be now available, can you retry?
The java compressed package can be downloaded, but logstash and  still cannot be downloaded.
https://downloads.bitnami.com/files/stacksmith/logstash-7.10.2-0-linux-amd64-debian-10.tar.gz

**Comment by matchseller** [comment]
Hi,can anyone answer this question? I would be very grateful.

**Comment by carrodher** [comment]
Those files should be already available.

**Comment by matchseller** [comment]
> Those files should be already available.

Yes, it works now, thank you very much

**Comment by matchseller** [comment]
Hi,The following resource files related to kibana 7.10.2 were not found
https://downloads.bitnami.com/files/stacksmith/yq-4.18.1-0-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/gosu-1.14.0-3-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/kibana-7.10.2-6-linux-amd64-debian-10.tar.gz

**Comment by carrodher** [comment]
Restored!

**Comment by matchseller** [comment]
> Restored!

Yes,Thanks again
