### ISSUE TITLE
[bitnami/rabbitmq] Bitnami RabbitMQ image cannot be pulled in EKS Singapore Region

### ISSUE THREAD

**Issue by dextercrypt** [bitnami/containers#67946]
### Name and Version

bitnami/rabbitmq:3.8.9-debian-10-r37

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Images cannot be pulled In the Singapore region, taking forever to be pulled.

Also throwing the following error: 
```
Failed to pull image "docker.io/bitnami/rabbitmq:3.8.9-debian-10-r37": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/rabbitmq:3.8.9-debian-10-r37": failed to copy: httpReadSeeker: failed open: server message: invalid_token: authorization failed
```
### What is the expected behavior?

The image should be pulled instantly.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image, but rather to a specific scenario that is not easy to reproduce on our side.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
