### ISSUE TITLE
mongodb arm64 supports?

### ISSUE THREAD

**Issue by GF-Huang** [bitnami/containers#67962]
### Name and Version

bitnami/mongodb:5.0

### What is the problem this feature will solve?

For run mongodb on raspberry pi.

### What is the feature you are proposing to solve the problem?

Make this image (https://hub.docker.com/r/bitnami/mongodb) supports arm64.

**Comment by carrodher** [comment]
ARM is not officially supported upstream. The latest version of MongoDB does not yet support ARM for Debian 12, see https://www.mongodb.com/try/download/community. ARM is only supported on Ubuntu and MacOS while our catalog is based on Debian.

Closing this issue as duplicated of https://github.com/bitnami/containers/issues/40947
