### ISSUE TITLE
bitnami/jasperreports build fails due to missing packages

### ISSUE THREAD

**Issue by expvit** [bitnami/containers#68005]
### Name and Version

bitnami/jasperreports

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to build jasperreports

The build fails due to missing packages (error log message: curl: (22) The requested URL returned error: 404 Not Found)

Below are the packages required to build this version (missing packages are written in bold with their links)
```
      "java-11.0.18-10-0-linux-${OS_ARCH}-debian-11"
      "tomcat-9.0.70-1-linux-${OS_ARCH}-debian-11" 
      "postgresql-client-11.18.0-0-linux-${OS_ARCH}-debian-11" 
      "mysql-client-10.6.11-1-linux-${OS_ARCH}-debian-11" 
      "render-template-1.0.4-1-linux-${OS_ARCH}-debian-11" 
      "jasperreports-8.1.0-2-linux-${OS_ARCH}-debian-11" 
      "gosu-1.16.0-0-linux-${OS_ARCH}-debian-11"
```
If I try to manually download one of those missing packages, i.e. https://downloads.bitnami.com/files/stacksmith/jasperreports-8.1.0-2-linux-amd64-debian-12.tar.gz then I am just redirected back to https://bitnami.com/.

### What is the expected behavior?

The image should build successfully when following the specified instructions.

### What do you see instead?
```
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by carrodher** [comment]
All files should be republished, could you please try again?

**Comment by expvit** [comment]
Thanks, now it builds
