### ISSUE TITLE
Mariadb unable to grant all privileges after upgrade

### ISSUE THREAD

**Issue by hexclann** [bitnami/containers#68002]
### Name and Version

bitnami/mariadb:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm using the following version:
```
"OS_ARCH=arm64",
"OS_FLAVOUR=debian-12",
"OS_NAME=linux",
"APP_VERSION=11.3.2",
"BITNAMI_APP_NAME=mariadb"
"Image": "bitnami/mariadb:latest"
```
Steps I did:

1. My database was created using:
```
docker run --restart always --name mariadb --network mynetwork --ip 10.69.0.5 -p 127.0.0.1:30000:3306 -e MARIADB_ROOT_USER=root -e MARIADB_ROOT_PASSWORD=myrootpass -v /opt/dbvolume:/bitnami/mariadb -d bitnami/mariadb:latest
```
2. It is an old mariadb docker container where I took a backup of my entire db using the command `mariadb-dump -uroot -pmyrootpass --all-databases > /bitnami/mariadb/data/mydbbackup.sql`.
3. I upgraded the mariadb by removing the old container and deploying a new container with the latest image mentioned above. I used the same root password and other parameters mentioned in the first point.
4. I restored the old backup using the command `mariadb -u root -pmyrootpass < "/tmp/mydbbackup.sql". All my services relying on db came online and working fine.
5. However when I create a new database I get the following error:
```
create database testdb;
CREATE USER 'testuser'@'%' IDENTIFIED BY 'testpass';
GRANT ALL ON testdb.* TO 'testuser'@'%';
ERROR 1044 (42000): Access denied for user 'root'@'%' to database 'testdb'
```

I checked the root user grant permission:
 
<img width="1057" alt="Screenshot 2024-06-21 at 3 27 41 PM" src="https://github.com/bitnami/containers/assets/59732888/ca9ff9b8-acc0-435e-b6dd-88a3f8c884ae">

<img width="1446" alt="Screenshot 2024-06-21 at 3 28 12 PM" src="https://github.com/bitnami/containers/assets/59732888/be101aa4-7acb-446d-b534-64d00622ae68">

I'm using the mysql_native_password plugin:

<img width="1095" alt="Screenshot 2024-06-21 at 3 29 12 PM" src="https://github.com/bitnami/containers/assets/59732888/c9f6273d-c4c2-4f18-90e4-9358b063c1f0">

### What is the expected behavior?
```
GRANT ALL ON testdb.* TO 'testuser'@'%';
```
should grant permission.

### What do you see instead?
```
ERROR 1044 (42000): Access denied for user 'root'@'%' to database 'testdb'
```
### Additional information

I created a new container and ran `SHOW GRANTS FOR 'root'@'%';`. The output is:

<img width="1196" alt="Screenshot 2024-06-21 at 3 43 25 PM" src="https://github.com/bitnami/containers/assets/59732888/b28cfaed-99bd-448b-92b0-06099207b219">

which is different than the other problematic containers:

<img width="1446" alt="Screenshot 2024-06-21 at 3 28 12 PM" src="https://github.com/bitnami/containers/assets/59732888/a3e5aaab-2111-41a2-99b7-195bd60802c1">

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by hexclann** [comment]
@carrodher understood. 

I had multiple wordpress sites. I fixed the issue by taking individual DB backup of each site using wp-cli and removing the old container including its volume. And I created a new container and created all the previous users and databases, restored wordpress site database using wp-cli.

If there is any better way to handle database upgrades in docker environment, please let me know.
