### ISSUE TITLE
bitnami/drupal: 10.3.0  is recommended to upgrade to PHP version 8.3, now it is 8.2.20.

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/containers#68035]
### Name and Version

bitnami/drupal: 10.3.0

### What is the problem this feature will solve?

bitnami/drupal: 10.3.0  is recommended to upgrade to PHP version 8.3, please help upgrade.

### What is the feature you are proposing to solve the problem?

bitnami/drupal: 10.3.0 is recommended to upgrade to PHP version 8.3, please help upgrade.

**Comment by carrodher** [comment]
Are facing any issues related to the PHP version? According to the official docs at https://www.drupal.org/docs/getting-started/system-requirements/php-requirements PHP 8.2 is supported for all Drupal 10 versions

**Comment by ddfiberglass** [comment]
> Are facing any issues related to the PHP version? According to the official docs at https://www.drupal.org/docs/getting-started/system-requirements/php-requirements PHP 8.2 is supported for all Drupal 10 versions

No issues. Just drupal 10.3 recommended, for the best ongoing support.

**Comment by carrodher** [comment]
I just created an internal task to bump the PHP version but given that PHP 8.2 is supported until Drupal 11 (https://www.drupal.org/docs/getting-started/system-requirements/php-requirements#versions) the task will not be prioritized relative to other topics the team is working on

**Comment by ddfiberglass** [comment]
> I just created an internal task to bump the PHP version but given that PHP 8.2 is supported until Drupal 11 (https://www.drupal.org/docs/getting-started/system-requirements/php-requirements#versions) the task will not be prioritized relative to other topics the team is working on

Thanks.
