### ISSUE TITLE
cluster-autoscaler:1.29.3 not yet present

### ISSUE THREAD

**Issue by nhumphreys** [bitnami/containers#68047]
### Name and Version

bitnami/cluster-autoscaler

### What architecture are you using?

None

### What steps will reproduce the bug?

I wish to run the latest 1.29 series cluster-autoscaler on my 1.29 kubernetes cluster

### What is the expected behavior?

Expect to find 1.29.3 available

### What do you see instead?

1.29.2 is the latest at this time

**Comment by carrodher** [comment]
Unfortunately, 1.29.3 was not released on our side given that it was released upstream close to the new minor version. Our automated test & release pipeline released 1.30.0 right after 1.29.2.

**Comment by nhumphreys** [comment]
thanks, does that mean that the automated pipeline will be instructed to release 1.29.3?

**Comment by carrodher** [comment]
> thanks, does that mean that the automated pipeline will be instructed to release 1.29.3?

No, we don't release versions retroactively. The last version of 1.29.x will be 1.29.2. From that moment, new versions will appear sequentially, but not previous ones. That version in the upstream won't be present in Bitnami.
