### ISSUE TITLE
MARIADB_RANDOM_ROOT_PASSWORD Not Working

### ISSUE THREAD

**Issue by malcalevak** [bitnami/containers#68053]
### Name and Version

bitnami/mariadb:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Adding the environment variable MARIADB_RANDOM_ROOT_PASSWORD set to anything

### What is the expected behavior?

The container runs, and a random root password is created and output in the container logs, e.g.:
```
2024-06-24 17:46:16 2024-06-24 21:46:16+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: `[A_beL5!?IY?3GnHV|H5.^VX#mM7$Ir
```
### What do you see instead?
```
2024-06-24 17:50:05 mariadb 21:50:05.49 ERROR ==> The MARIADB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```
### Additional information

The official mariadb image works as expected.

**Comment by malcalevak** [comment]
> Please note this env. variable is not available, see https://github.com/bitnami/containers/tree/main/bitnami/mariadb#environment-variables. By default, a random password is generated if you don't specify anything else

Thanks for pointing me to that, I'm not sure how I missed it. That said, you seem to be mistaken (or I'm misunderstanding), if no password is specified, a random password is not generated, or at least, the container fails to run and says` "The MARIADB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development."`

**Comment by carrodher** [comment]
Yes, you're right, the logic to generate a random password is implemented in the Helm chart itself but not in the container.

If you're interested in contributing a solution at container level, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
