### ISSUE TITLE
[bitnami/scylladb] Add --smp and --memory options for ScyllaDB Docker configuration

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#68051]
### Name and Version

bitnami/scylladb:6.0-debian-12

### What architecture are you using?

None

### What steps will reproduce the bug?

We are planning to deploy ScyllaDB in a production environment using Docker via Bitnami. However, we require the --smp and --memory options to properly configure the Docker environment. Currently, these options are not available in the configuration provided by Bitnami.

According to the official ScyllaDB documentation, these options are crucial for optimizing performance and managing resources in a production Docker environment. You can find detailed information in the [Best Practices for ScyllaDB on Docker](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/tips/best-practices-scylla-on-docker) documentation.

1. Attempt to deploy ScyllaDB using Bitnami's Docker configuration.
2. Notice that options --smp and --memory are not available.

### What is the expected behavior?

Bitnami should include the --smp and --memory options in their Docker configuration for ScyllaDB to align with best practices and ensure optimal performance and resource utilization.

### What do you see instead?

None

**Comment by siddjellali** [comment]
I have tried to include `scylla_cpuset_setup` and `scylla_memory_setup` in the Dockerfile, but encountered issues. It seems that these parameters are being overridden by the Bitnami script, and these commands require root privileges to execute.

```
RUN sudo scylla_cpuset_setup 2 && \
    sudo scylla_memory_setup 4G
```

**Comment by siddjellali** [comment]
Hello everyone,
I've identified the missing configuration: it appears that when you run the scyllab binary, some flags are omitted.

```
#/opt/bitnami/scripts/scylladb/run.sh line 35
exec "$EXEC" "${flags[@]}" --cpuset 0-1 --smp 2 --memory 8G --io-properties-file /opt/bitnami/scylladb/etc/scylla.d/io_properties.yaml
```

More, 
**scylla_io_setup** needs to be executed at least once to create the io-properties file and necessary directories. 
Otherwise, the command won't run. Personally, I run this binary on every boot (I've added it to setup.sh, before the run.sh execution).

```
# /opt/bitnami/scripts/scylladb/setup.sh 
mkdir -p /bitnami/scylladb/data/data && \
mkdir -p /bitnami/scylladb/data/commitlog &&  \
mkdir -p /bitnami/scylladb/data/hints && \
mkdir -p /bitnami/scylladb/data/view_hints
scylla_io_setup
```

Please find below DOCKERFILE to reproduce issue and workarroud.

```
FROM bitnami/scylladb:6.0-debian-12
ENV SCYLLADB_DEVELOPER_MODE no
ENV BITNAMI_DEBUG true
COPY run.sh /opt/bitnami/scripts/scylladb/run.sh
COPY setup.sh /opt/bitnami/scripts/scylladb/setup.sh
```

#setup.sh 

```
#!/bin/bash
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
#
# Bitnami ScyllaDB setup

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

# Load Generic Libraries
. /opt/bitnami/scripts/libvalidations.sh
. /opt/bitnami/scripts/libos.sh
. /opt/bitnami/scripts/libscylladb.sh

# Load ScyllaDB environment variables
. /opt/bitnami/scripts/scylladb-env.sh

# Ensure ScyllaDB is stopped when this script ends.
trap "cassandra_stop" EXIT

# FIX
mkdir -p /bitnami/scylladb/data/data && \
mkdir -p /bitnami/scylladb/data/commitlog &&  \
mkdir -p /bitnami/scylladb/data/hints && \
mkdir -p /bitnami/scylladb/data/view_hints
scylla_io_setup

# Set default ScyllaDB host environment variable
cassandra_set_default_host
# Ensure ScyllaDB environment variables settings are valid
cassandra_validate
cassandra_validate_tls
# Ensure 'daemon' user exists when running as 'root'
am_i_root && ensure_user_exists "$DB_DAEMON_USER" --group "$DB_DAEMON_GROUP"
# Ensure ScyllaDB is initialized
cassandra_initialize

# Allow running custom initialization scripts
if ! is_boolean_yes "$DB_IGNORE_INITDB_SCRIPTS"; then
    cassandra_custom_init_scripts
fi
```

# run.sh 

```
#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace # Uncomment this line for debugging purposes

# Load libraries
. /opt/bitnami/scripts/liblog.sh
. /opt/bitnami/scripts/libscylladb.sh
. /opt/bitnami/scripts/libos.sh

# Load ScyllaDB environment variables
. /opt/bitnami/scripts/scylladb-env.sh

info "** Starting ScyllaDB **"

EXEC="${DB_BIN_DIR}/scylla"

flags=("--options-file" "$DB_CONF_FILE")
if is_boolean_yes "$SCYLLADB_DEVELOPER_MODE"; then
    flags+=("--developer-mode" "true")
fi

# Add flags passed to this script
flags+=("$@")


info "** Starting $DB_FLAVOR **"
if am_i_root; then
    exec_as_user "$DB_DAEMON_USER" "$EXEC" "${flags[@]}"
else
    exec "$EXEC" "${flags[@]}" --cpuset 0-1 --smp 2 --memory 8G --io-properties-file /opt/bitnami/scylladb/etc/scylla.d/io_properties.yaml
fi
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the insight. Would you like to contribute with a PR including these settings?

**Comment by siddjellali** [comment]
I would love to, but I'm a novice when it comes to Bitnami container scripting and related tasks. The Scylla Bitnami container seems to be a duplicate of the Cassandra container, and I'm not fully proficient in how the functions should be orchestrated and implemented.

Do you know who created it? Perhaps they can provide assistance and help with testing for the community.

**Comment by siddjellali** [comment]
I do my best :)
