### ISSUE TITLE
[bitnami/zookeeper] zookeeper arm64 docker images(3.9.x) in hub.docker.com is invalid!

### ISSUE THREAD

**Issue by zhengchaoken** [bitnami/containers#68070]
### Name and Version

bitnami/zookeeper:3.9.x

### What architecture are you using?

arm64

### What steps will reproduce the bug?

environment: aarch64 GNU/Linux

**step 1. pull arm image and load** 
```console
$ docker pull docker.io/bitnami/zookeeper@sha256:2400471e90db04c88ce0a132b9bbc0fa189e495a3c0f49062c156d41e7a3889b
$ docker tag 651dcbb70079 docker.io/bitnami/zookeeper:3.9.1.arm
$ docker save -o arm-zookeeper3.9.1.arm.tar docker.io/bitnami/zookeeper:3.9.1.arm
$ docker load -i /opt/arm-zookeeper3.9.1.arm.tar
```
**step 2. startup** 
```
$ docker run -d --restart=always \
 --name zookeeper \
 --net=host \
 -v /opt/zookeeper/volume/data:/bitnami/zookeeper \
 -e ZOO_ENABLE_ADMIN_SERVER=false \
 -e JMXDISABLE=true \
 -e ALLOW_ANONYMOUS_LOGIN=yes \
 -e ZOO_PORT_NUMBER=9500 \
 docker.io/bitnami/zookeeper:3.9.1.arm
```
**step 3. check** 
```console
$ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS                                  PORTS               NAMES
c7e415492a89        docker.io/bitnami/zookeeper:3.9.1.arm   "/opt/bitnami/script…"   6 seconds ago       Restarting (1) Less than a second ago                       zookeeper
```
**check log**
```console
$ docker logs -f --tail 100 zookeeper

 /opt/bitnami/java/bin/java
 ....
 zookeeper 18:02:08.09 INFO  ==> ** Starting ZooKeeper **
 /opt/bitnami/java/bin/java
 JMX disabled by user request
 Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
 Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
 Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.quorum.QuorumPeerMain
 zookeeper 18:02:12.04 INFO  ==> 
 zookeeper 18:02:12.05 INFO  ==> Welcome to the Bitnami zookeeper container
 zookeeper 18:02:12.05 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 zookeeper 18:02:12.05 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 zookeeper 18:02:12.05 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-onfigured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), VE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
 zookeeper 18:02:12.05 INFO  ==> 
 zookeeper 18:02:12.06 INFO  ==> ** Starting ZooKeeper setup **
 zookeeper 18:02:12.09 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
 zookeeper 18:02:12.09 INFO  ==> Initializing ZooKeeper...
 zookeeper 18:02:12.10 INFO  ==> User injected custom configuration detected!
 zookeeper 18:02:12.10 INFO  ==> Deploying ZooKeeper with persisted data...
 zookeeper 18:02:12.10 INFO  ==> ** ZooKeeper setup finished! **
 
 zookeeper 18:02:12.13 INFO  ==> ** Starting ZooKeeper **
 /opt/bitnami/java/bin/java
 JMX disabled by user request
 Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
 Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
 Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.quorum.QuorumPeerMain
```

however QuorumPeerMain is in the file ， usr jar tf to check 

```Dockerfile
FROM docker.io/bitnami/zookeeper:3.9.1.arm

RUN jar tf /opt/bitnami/zookeeper/lib/zookeeper-3.9.1.jar | grep java 
``` 

docker build check
```console
$ docker build -t zookeeper:391test -f Dockerfile .

Step 7/11 : RUN jar tf /opt/bitnami/zookeeper/lib/zookeeper-3.9.1.jar | grep QuorumPeerMain
 ---> Running in 5425d4bbe8e0
org/apache/zookeeper/server/quorum/QuorumPeerMain.class
```
### What is the expected behavior?
```
docker run bitnami/zookeeper:3.9.2(3.9,latest) , 3.9.1  ok  
```
### What do you see instead?
```
Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.quorum.QuorumPeerMain
```
### Additional information

1.  x86 docker images is ok 
1. install zk in local vm(with openjdk-11 , without docker) runs ok . using tar: https://downloads.bitnami.com/files/stacksmith/zookeeper-3.9.2-2-linux-arm64-debian-12.tar.gz or https://dlcdn.apache.org/zookeeper/zookeeper-3.9.2/apache-zookeeper-3.9.2-bin.tar.gz

**Comment by gongomgra** [comment]
Hi @zhengchaoken,

Thanks for using Bitnami. We have not being able to reproduce your issue with the same 3.9.1 image you mentioned. We started with an empty volume, started the container, stopped it, and then started it again without issues (we also see the `Deploying ZooKeeper with persisted data...` message). We tried to stop and start it several times and it worked fine every single time.

I also see in dockerhub that the most recent image for the 3.9.1 version is from 4 months ago. Do you also reproduce your issue with the latest 3.9.2 version? Can it be related somehow to the persisted data you are using?

**Comment by zhengchaoken** [comment]
> Hi @zhengchaoken,
> 
> Thanks for using Bitnami. We have not being able to reproduce your issue with the same 3.9.1 image you mentioned. We started with an empty volume, started the container, stopped it, and then started it again without issues (we also see the `Deploying ZooKeeper with persisted data...` message). We tried to stop and start it several times and it worked fine every single time.
> 
> I also see in dockerhub that the most recent image for the 3.9.1 version is from 4 months ago. Do you also reproduce your issue with the latest 3.9.2 version? Can it be related somehow to the persisted data you are using?

I have tried both 3.9.1 & 3.9.2 
eg , 3.9.1 arm docker commond was : docker pull docker.io/bitnami/zookeeper@sha256:2400471e90db04c88ce0a132b9bbc0fa189e495a3c0f49062c156d41e7a3889b

start docker common was 
 docker run -d --restart=always \
 --name zookeeper \
 --net=host \
 -v /opt/zookeeper/volume/data:/bitnami/zookeeper \
 -e ZOO_ENABLE_ADMIN_SERVER=false \
 -e JMXDISABLE=true \
 -e ALLOW_ANONYMOUS_LOGIN=yes \
 -e ZOO_PORT_NUMBER=9500 \
 docker.io/bitnami/zookeeper:3.9.1.arm

can you provide your  docker pulll command , docker run command  and linux ‘uname -a ’ result

I will try your commonds and check my useage to find the problem

Thanks very much !

**Comment by gongomgra** [comment]
Hi @zhengchaoken,

We used the commands you shared on your first post to pull the Zookeeper image and to run it with a mounted volume.
