### ISSUE TITLE
[bitnami/pgbouncer] Add ENV variable for application_name_add_host

### ISSUE THREAD

**Issue by rbojan** [bitnami/containers#68089]
### Name and Version

bitnami/pgbouncer:1.22.1

### What is the problem this feature will solve?

It would be helpful if we could add an ENV variable for `application_name_add_host`:

> Add the client host address and port to the application name setting set on connection start. This helps in identifying the source of bad queries etc. This logic applies only at the start of a connection. If application_name is later changed with SET, PgBouncer does not change it again.

Source: https://www.pgbouncer.org/config.html#generic-settings

### What is the feature you are proposing to solve the problem?

N/A

### What alternatives have you considered?

N/A

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR editing libpgbouncer.sh and the team will check it.

**Comment by rbojan** [comment]
Hi!

Thanks for the fast response. I submitted a PR.
