### ISSUE TITLE
mongodb supports arm

### ISSUE THREAD

**Issue by monlor** [bitnami/containers#68152]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

Make mongodb run on an arm server

### What is the feature you are proposing to solve the problem?

Build a multi-architecture mongodb image

**Comment by carrodher** [comment]
ARM is not officially supported upstream. The latest version of MongoDB does not yet support ARM for Debian 12, see https://www.mongodb.com/try/download/community. ARM is only supported on Ubuntu and MacOS while our catalog is based on Debian.

Closing this issue as duplicated of https://github.com/bitnami/containers/issues/40947
