### ISSUE TITLE
The pcp_attach_node command is not available inside the pgpool container

### ISSUE THREAD

**Issue by Wj-creat** [bitnami/containers#68503]
### Name and Version

bitnami/pgpool

### What architecture are you using?

None

### What steps will reproduce the bug?

When there is a node in pgpool whose status is down and I use the command: `pcp_attach_node -h localhost -U admin 2` in the pgpool container, it reports the error:
```
connection to host "localhost" failed with the error "Connection refused", 
```
why?

### What is the expected behavior?

Node status changes to up

### What do you see instead?
```
connection to host "localhost" failed with error "Connection refused"
```

**Comment by Wj-creat** [comment]
detailed steps
```
[root@prod-db1 ~]# docker exec -it pgpool bash
I have no name!@0c5a79dc9e6f:/$ pcp_attach_node -h localhost -U admin 2
Error: connection to host "localhost" failed with error "Connection refused"
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by andresbono** [comment]
Hi, the container [entrypoint.sh](https://github.com/bitnami/containers/blob/main/bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/pgpool/entrypoint.sh) generates the configuration file on each start of the container, as you can see in the logs:

```
INFO  ==> Generating pgpool.conf file...
```

If you want to add configuration customizations not directly supported by env-vars, please check this section in the readme: [Configuration file](https://github.com/bitnami/containers/tree/main/bitnami/pgpool#configuration-file).

**Comment by yukha-dw** [comment]
I've experiencing similar issue when one of my postgresql node is down. Pgpool's healthcheck should've reattached the node, but for some reason it can't make any connection with pcp
https://github.com/bitnami/containers/blob/3f4183e3d2c40a1e1abb9785111e250915b1e138/bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh#L279-L288

I'll open new issue after I found reliable way to reproduce this
