### ISSUE TITLE
[bitnami/opencart] All uploaded catalog media is lost on container restart (image folder is not mapped as a volume)

### ISSUE THREAD

**Issue by doublehelix** [bitnami/containers#68552]
### Name and Version

bitnami/opencart:4.0.2-3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run the latest bitnami/opencart (and MariaDB etc.)
1. Ensure the persistent volumes are configured as per https://hub.docker.com/r/bitnami/opencart
   - `--volume /path/to/opencart_data:/bitnami/opencart`
1. log into the administration console
1. Upload a new product image to the media manager
1. Stop the stack
1. Start the stack

### What is the expected behavior?

Images uploaded to the opencart volume are persisted

### What do you see instead?

All images are gone.
It seems OpenCart 4.x stores images in `/opt/bitnami/opencart/images` which is NOT mounted as a volume. All catalog images (as well as the store logo etc.) are lost if the container restarts or is updated.

**Comment by gongomgra** [comment]
Hi @doublehelix 

Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by doublehelix** [comment]
Just bumping to keep this issue open until I have a chance to investigate further and see if there's a simple update to the Docker config or mappings.

**Comment by gongomgra** [comment]
@doublehelix I'm adding the `on-hold` tag to avoid the stale bot from automatically closing this ticket.

**Comment by javsalgar** [comment]
Hi,

Just a note to inform that we are going to deprecate this solution. All open issues will be closed.
