### ISSUE TITLE
SuiteCRM Docker Compose issue with MariaDB

### ISSUE THREAD

**Issue by RavHilton** [bitnami/containers#68550]
### Name and Version

bitnami/suitecrm:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Docker Compose
2. Download and run as per the docs
3. MariaDB more often than not will not start, and when it does SuiteCRM cannot see it

### What is the expected behavior?

I would expect the MariaDB container to run reliably, and the SuiteCRM container to be able to connect to it

### What do you see instead?

As mentioned above

**Comment by carrodher** [comment]
Could you please provide the command used to deploy the docker-compose? I'm unable to reproduce the issue.

In the same way, is there any hint about the issue you're facing in the container logs?
