### ISSUE TITLE
[argo-events] Create image and helm chart

### ISSUE THREAD

**Issue by ognjen-it** [bitnami/containers#68553]
### Describe your suggestion as much as you can

Dear all,

As soon as I use a lot of containers and charts from Bitnami, I would like to contribute as much as I can to the community.

Since Bitnami already has argo-workflows, it would be good to have argo-events since it very powerful tool that can trigger argo workflow based on a lot of sources like AWS SNS, SQS, GCP PubSub, Azure Events Hub, Webhooks, etc.

Even though I have been a DevOps Engineer since 2018, have a lot of experience with helm charts and containers, and have already contributed to spark helm chart, I would need your support in the form of references to documentation or something like that.
My desire is to make both a container image and a helm chart, but I'm always open to someone joining me if they want.

What do you think, what could be next step?

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. To ensure that your idea receives the attention it deserves, we will apply the 'on-hold' label. This will prevent our automated system from prematurely closing the issue.

We will keep you updated on any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Comment by ognjen-it** [comment]
> Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.
> 
> We apologize for the inconvenience. We will reconsider it in the future.
> 
> Thanks for your suggestion!

Ok, thank you for your time spent for this issue. I hope that in the near future there will be a possibility to add it to your catalog.
