### ISSUE TITLE
wordpress-nginx structure reference error

### ISSUE THREAD

**Issue by bashbang** [bitnami/containers#68898]
### Name and Version

bitnami/wordpress-nginx

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The `.user_scripts_initialized` file is not present when it should.

Tested in a local docker container.  Went to the terminal and see the following:

The persistent volume path that's actually being used is /bitnami/wordpress

https://github.com/bitnami/containers/blob/main/bitnami/wordpress-nginx/6/debian-12/rootfs/post-init.sh#L13
```
if [[ ! -f "/bitnami/wordpress-nginx/.user_scripts_initialized" && -d "/docker-entrypoint-init.d" ]]; then
```
### What is the expected behavior?

The .user_scripts_initialized file is written to a location that the test scripts can read from.

### What do you see instead?

no .user_scripts_initialized file is created.

### Additional information

Although it may be as simple as changing the file reference to be wordpress it's also possible that the intent is to truly have a wordpress-nginx folder in which case the init section needs to be updated to write to wordpress-nginx rather than generate a wordpress structure.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
