### ISSUE TITLE
Getting error when tryingt o restore database to mariadb container

### ISSUE THREAD

**Issue by wthsia** [bitnami/containers#69184]
### Name and Version

docker.io/bitnami/mariadb:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

create docker container 
Run:
```
cat redmine.sql | docker exec -i CONTAINER_ID /usr/bin/mysql -u root --password=root bitnami_redmine
```

### What do you see instead?
```
ERROR 1050 (42S01) at line 2506: Table 'user' already exists
```

### Additional information

Is there a doc that shows how to backup a Redmine single stack installation to a Redmine container platform?

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/containers/tree/main/bitnami/redmine#maintenance) you can find some information about how to backup a Redmine container. Did you try those steps?

**Comment by wthsia** [comment]
My current Redmine installation is not a container. I'm trying to migrate from a single stack installation to a container.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
