### ISSUE TITLE
[bitnami/php-fpm] build fails due to missing packages

### ISSUE THREAD

**Issue by dennymao** [bitnami/containers#69193]
### Name and Version

bitnami/php-fpm 7.x ~ latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker build php-fpm:xxx .`
Lost file list: 
https://downloads.bitnami.com/files/stacksmith/php-8.2.1-0-linux-amd64-debian-11.tar.gz
https://downloads.bitnami.com/files/stacksmith/php-7.4.33-2-linux-amd64-debian-11.tar.gz
...

### What do you see instead?
```
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by dennymao** [comment]
Translation to English:
I think you are experiencing a malfunction? It seems that many versions of files are missing, and I tried building different Dockerfiles, but all of them couldn't find the files.

**Comment by carrodher** [comment]
Hi, it is not an issue but the retention policy applied to those intermediate files used to build the containers.

The already built container images can be found at DockerHub, i.e
- https://hub.docker.com/layers/bitnami/php-fpm/8.2.1/images/sha256-665a9dbfe58ac306d4c24b55c74f6912047803d9c1ffb9129ac21c03073c0e6a?context=explore
- https://hub.docker.com/layers/bitnami/php-fpm/7.4.33/images/sha256-50a2a791415ce0a36026071d774e616be001bd0a1e3343163f4e894ae36aeba8?context=explore
