### ISSUE TITLE
[bitnami/redmine] certificate error when connecting to exchange

### ISSUE THREAD

**Issue by wthsia** [bitnami/containers#69196]
### Name and Version

bitnami/redmine

### What architecture are you using?

None

### What steps will reproduce the bug?

`docker exec -i redmine_nossl /opt/bitnami/redmine/bin/bundle exec /opt/bitnami/redmine/bin/rake -f /opt/bitnami/redmine/Rakefile redmine:email:receive_imap port=993  RAILS_ENV="production" host=excpr01.farmcredit-ffcb.com username=user password=pass project=farmcredit tracker=Support ssl=true unknown_user=create`

### What is the expected behavior?

issue created from an email

### What do you see instead?
```
rake aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=172.16.2.162:993 state=error: certificate verify failed (unable to get local issuer certificate)
/opt/bitnami/redmine/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:46:in `connect_nonblock'
/opt/bitnami/redmine/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:46:in `ssl_socket_connect'
/opt/bitnami/redmine/vendor/bundle/ruby/3.1.0/gems/net-imap-0.3.7/lib/net/imap.rb:2377:in `start_tls_session'
/opt/bitnami/redmine/vendor/bundle/ruby/3.1.0/gems/net-imap-0.3.7/lib/net/imap.rb:2032:in `initialize'
/opt/bitnami/redmine/lib/redmine/imap.rb:32:in `new'
/opt/bitnami/redmine/lib/redmine/imap.rb:32:in `check'
/opt/bitnami/redmine/lib/tasks/email.rake:121:in `block (4 levels) in <top (required)>'
/opt/bitnami/redmine/app/models/mailer.rb:650:in `with_synched_deliveries'
/opt/bitnami/redmine/lib/tasks/email.rake:120:in `block (3 levels) in <top (required)>'
/opt/bitnami/redmine/vendor/bundle/ruby/3.1.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/redmine/bin/bundle:108:in `load'
/opt/bitnami/redmine/bin/bundle:108:in `<main>'
Tasks: TOP => redmine:email:receive_imap
(See full trace by running task with --trace)
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
