### ISSUE TITLE
[bitnami/kafka] kafka images for 2.7.1, 2.7.2 appear to be missing 

### ISSUE THREAD

**Issue by kevinburke** [bitnami/containers#69215]
### Name and Version

bitnami/kafka:2.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Kafka has releases for versions 2.7.1 and 2.7.2, you can find release notes here: https://kafka.apache.org/downloads

I expected to find matching releases in bitnami/kafka, but tagged releases go from 2.7.0 to 2.8.0 with nothing in between.

### What do you see instead?

I do not see uploaded images for v2.7.1 or v2.7.2.

**Comment by javsalgar** [comment]
Hi!

I don't recall the reason why but we're currently not maintaining the kafka 2.x branch. Here you can see the list of supported branches. https://github.com/bitnami/containers/tree/main/bitnami/kafka
