### ISSUE TITLE
bitnami/keycloak 24.0.5-debian-12-r3 regression regarding openid protocol

### ISSUE THREAD

**Issue by wkbrd** [bitnami/containers#69258]
### Name and Version

bitnami/keycloak 24.0.5-debian-12-r3

### What architecture are you using?

None

### What steps will reproduce the bug?

Updating from build -r2 to -r3 caused a regression such that the openid configuration file at:
https://<keycloak URL>/realms/<defaultRealm>
Is outputting a JSON document that has http URLs (not https URLs).

### What is the expected behavior?

URLs should have https.

### What do you see instead?

URLs have http protocol

### Additional information

This system has an ingress running https and Keycloak is running on http only.  Keycloak is running with proxy=edge.

**Comment by wkbrd** [comment]
I am currently testing with the Bitnami Keycloak Helm chart version 21.6.0 due to a bug in 21.6.1 that has not yet been merged.  The PR with the fix to the Helm chart is in: https://github.com/bitnami/charts/pull/27912

**Comment by wkbrd** [comment]
The bitnami Keycloak Helm chart uses KEYCLOAK_PROXY which was replaced by KEYCLOAK_PROXY_HEADERS, which is NOT used by the chart.  The changes in -r3 are NOT compatible with the current Helm chart.  It appears that https://github.com/bitnami/charts/pull/27890 was created for the matching changes.

**Comment by juan131** [comment]
Hi @Kajot-dev @wkbrd 

We released the container and didn't update the chart (yet) given the chart points to a specific tag by default, therefore it was safe to do the release independently. Once we merge the associate chart PR, the chart will be updated to use `24.0.5-debian-12-r3`.

**Comment by Kajot-dev** [comment]
@juan131 Oh, then my bad, sorry for confusion.
