### ISSUE TITLE
Kong fail using metrics

### ISSUE THREAD

**Issue by xavbourdeau** [bitnami/containers#69390]
### Name and Version

bitnami/kong:3.7.1-debian-12-r3

### What architecture are you using?

x86_64

### What steps will reproduce the bug?

If you set in the helm chart `metrics.enable: true`, then kong pods (kong container) will restart saying with following message:
```
kong: unrecognized parameter: c
```

### What is the expected behavior?

Kong should start normally

### What do you see instead?

Kong container fails with error
```
kong: unrecognized parameter: c
```

### Additional information

It's due to the fact that `bitnami/kong/3/debian-12/rootfs/opt/bitnami/scripts/libkong.sh` has a function `kong_stop` that use the following statements

```
kong stop -c "$KONG_CONF_FILE" -p "$KONG_PREFIX"
```

Which is wrong, `kong stop` doesn't have a `-c` nor `-p` arguments

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by xavbourdeau** [comment]
Issue closed because PR is merged
