### ISSUE TITLE
[bitnami/rabbitmq] Need container with rabbitmq 3.13.5 released

### ISSUE THREAD

**Issue by hillen** [bitnami/containers#69428]
### Name and Version

bitnami/rabbitmq:3.13.4-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

There is an issue with rabbitmq 3.13.4 where raft with not restart correctly in some restart scenarios with quorum queues resulting in the node not joining the queue.

I reported this in the following discussion:
https://github.com/rabbitmq/rabbitmq-server/discussions/11712

this PR was generated to fix the issue:
https://github.com/rabbitmq/rabbitmq-server/pull/11769

which was released in rabbitmq 3.13.5

The bot seems to have detected the release and built the rabbitmq package by running this command:
```
curl -RSsLf "https://downloads.bitnami.com/files/stacksmith/rabbitmq-3.13.5-0-linux-amd64-debian-12.tar.gz" -O

31407225 Jul 20 03:59 rabbitmq-3.13.5-0-linux-amd64-debian-12.tar.gz
```
However, I do not see the container bot detecting and building the rabbitmq container.

### What is the expected behavior?

rabbitmq 3.13.5 container built and picked up by the rabbitmq helm chart

### What do you see instead?

3.13.5 rabbitmq package is built, but the container is not built

**Comment by javsalgar** [comment]
Hi!

Just a note to let you know that we're working on it. It seems there is an issue in the automated pipeline.

**Comment by hillen** [comment]
The container has been built and the helm chart has been released. I have been able to install it in our test clusters. Thanks for addressing this. This issue can be closed.
