### ISSUE TITLE
[bitnami/kafka] Path about server.properties

### ISSUE THREAD

**Issue by wk989898** [bitnami/containers#69457]
### Name and Version

bitnami/kafka:2.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

docker run -dit bitnami/kafka:2.3.0 bash
docker exec -it xxx bash

### What is the expected behavior?

`server.properties` should be in `/opt/bitnami/kafka/config`

### What do you see instead?

 Found it in `/opt/bitnami/kafka/configtmp`

### Additional information

It becomes `server.properties.original` in `3.6.0`

**Comment by javsalgar** [comment]
Hi,

As you are using bash, you may be skipping part of the initialization that copies the configuration files to the proper place. This has to do with supporting readOnlyRootFilesystem in the helm chart.

**Comment by wk989898** [comment]
It seems that the command must be `/entrypoint.sh /run.sh`, but I can't set `KAFKA_CFG_ZOOKEEPER_CONNECT` dynamic.
e.g.
```yaml
command:  
    "/entrypoint.sh /run.sh"
env: 
    KAFKA_CFG_ZOOKEEPER_CONNECT: $ZK_CONNECT 
```
This config will cause `ERROR Unable to resolve address: ${ZK_CONNECT}`

**Comment by javsalgar** [comment]
You can try including your own init scripts in this folder `/docker-entrypoint-initdb.d`. You may be able to perform the customizations there.

**Comment by wk989898** [comment]
On version `2.2.0`, i execute `/entrypoint.sh /run.sh` but no file found in `/opt/bitnami/kafka/config/server.properties`.
Also on `1.1.0`, I can't update `server.properties`, code in `run.sh`: 
```
START_COMMAND="${KAFKA_HOME}/bin/kafka-server-start.sh -daemon ${KAFKA_HOME}/config/server.properties && ps ax | grep -i 'java.*kafka' | grep -
v grep | awk '{print \$1}'  > ${KAFKA_HOME}/tmp/kafka.pid  && tail -f ${KAFKA_HOME}/logs/server.log"```

**Comment by wk989898** [comment]
I found versions below `2.2.0`, entry point is `/app-entrypoint.sh`, and the others is `entrypoint.sh`. It's terrible for me to test Kafka version.
