### ISSUE TITLE
[bitnami/moodle]cant load, find, install php ldap extension

### ISSUE THREAD

**Issue by xDBSx** [bitnami/containers#69452]
### Name and Version

bitnami/moodle:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I had a moodle container setup and running with LDAP authentication. Last week I had to change the php upload limit and took the opportunity to rebuild with the latest image (I was running 4.3.5 or 4.3.2).

The new image started showing up an PHP error on console, and whenever I call php(php -v):  
```
[22-Jul-2024 19:17:52 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'ldap' (tried: /opt/bitnami/php/lib/php/extensions/ldap (/opt/bitnami/php/lib/php/extensions/ldap: cannot open shared object file: No such file or directory), /opt/bitnami/php/lib/php/extensions/ldap.so (/opt/bitnami/php/lib/php/extensions/ldap.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

And the auth gives the error: 
![image](https://github.com/user-attachments/assets/2ad84a63-93d7-41b2-af8a-acffd782180c)

I've checked my php.ini and the ldap extension is enabled, but the ldap.so is not present on the system.
If I try to manually install php-ldap with apt install it downloads the wrong version for php8.2, I couldnt sucessfully download the proper extension for the php version on the container(8.1.29) maybe my fault with tags.
![image](https://github.com/user-attachments/assets/4a8224a6-238e-4e0f-8c0c-0df15d5c0044)
![image](https://github.com/user-attachments/assets/c47f051a-5b0c-42b1-b44b-81db4652f6bf)

If I put the apt installed php-ldap ldap.so forcefully on the /bitnami/php/extensions folder it gives a compiled version error.

### What is the expected behavior?

PHP LDAP extension up and running.

### What do you see instead?

Install the wrong php-ldap extension on the container with apt.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by xDBSx** [comment]
Thanks for the reply, you were correct it wasnt related to the container image.

It was a configuration problem, the account used to bind to the LDAP had its password changed and I wasnt aware of, due to moodle poor error message I started poking around on the wrong direction since I had built the new image at the same time as the password changed.

LDAP auth is now working again.
