### ISSUE TITLE
just updated Docker-wordpress from Asustor nas

### ISSUE THREAD

**Issue by Baltimorepc** [bitnami/containers#70007]
### Name and Version

6.6.0.r01

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Ran the update on my Asustor NAS to the new Docker-Wordpress and now my database won't connect says, wrong user 

Trying to connect to the database server
```
2024-07-24 23:04:25 126 [Warning] Aborted connection 126 to db: 'unconnected' user: 'unauthenticated' host: 'removed ip' (This connection closed normally without authentication)
2024-07-24 23:04:31 127 [Warning] Aborted connection 127 to db: 'unconnected' user: 'unauthenticated' host: 'removed ip' (This connection closed normally without authentication)
2024-07-24 23:04:36 128 [Warning] Aborted connection 128 to db: 'unconnected' user: 'unauthenticated' host: 'removed ip' (This connection closed normally without authentication)
2024-07-24 23:04:41 129 [Warning] Aborted connection 129 to db: 'unconnected' user: 'unauthenticated' host: 'removed ip' (This connection closed normally without authentication)
2024-07-24 23:04:46 130 [Warning] Aborted connection 130 to db: 'unconnected' user: 'unauthenticated' host: 'removed ip' (This connection closed normally without authentication)
```
### What is the expected behavior?

This was working fine in till I ran the update showing in the Asustor Nas App Portal.

### What do you see instead?

Now WordPress is down and Docker shows for both the database and WordPress as saying trying to connect to the database and the database won't authenticate the user when all I did was an update. it shouldn't have deleted anything this isn't the first time I updated stuff

**Comment by Baltimorepc** [comment]
Can you at least let me know how i can pull your old image so i can at least get my website back up

**Comment by Baltimorepc** [comment]
i was able to go back to bitnami/wordpress:6.5.5-debian-12-r10 and the issue is now resolved. please let me know when this bug is is fixed

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by CommandLord** [comment]
I have the same issue and I am using basically this compose: https://github.com/bitnami/containers/blob/main/bitnami/wordpress/docker-compose.yml
The only difference is that the mariadb version 10.6 and its wordpress latest.

Maybe the db version is the problem? 

We perform automated updates every night and the one that caused the error was yesterday(24.07.) at 10 PM CEST. At that time the newest bitnami/mariadb:10.6 and bitnami/wordpress:latest were pulled and started causing the problem. It was working fine before.

**Comment by Baltimorepc** [comment]
The only downgrade I did was Bitnami Wordpress docker as soon as the container ran it connected and worked right away it has to be the bitnami update but I wasent able to see anything that may be causing it but I can try and look deeper into it when I get home

**Comment by LunkSnee** [comment]
I experienced the same thing. I had to downgrade to the previously downloaded image (id  3d86a98a387c) and everything worked again.
I'm connected from bitnami/wordpress:latest to bitnami/mariadb:10.11.

**Comment by timofey-drozhzhin** [comment]
I believe I was able to replicate this issue in https://github.com/bitnami/containers/issues/70392. Updating Mariadb to 11.4 should fix this.

**Comment by gongomgra** [comment]
Hi all,

I'm afraid I have not being able to reproduce your issue. According to our [GitHub history](https://github.com/bitnami/containers/commit/a4eaf536c1901a77a1a42e5676a244691e33389b), the MariaDB tag was updated to `11.4` two weeks ago, which seems to fix the issues you are sharing here. Apart from that I have removed all the images on my computer and have started the WordPress compose file a couple of times without any issues.

Can you check that you are using the latest docker-compose file?

**Comment by LunkSnee** [comment]
I was hoping to continue to use mariadb v10.11 which is LTS supported for another 3.5 years. But I tested upgrading to v11.4, and thankfully my databases upgraded without error. "latest" wordpress works again with mariadb 11.4, but not mariadb 10.11.

**Comment by gongomgra** [comment]
Hi @LunkSnee,

I'm glad it worked for you after migrating the database information. Can you check you are using the latest images for both services? I have updated the tag in our docker-compose to use `mariadb:10.11`, and WordPress has started without issues

```
$ git diff .
diff --git a/bitnami/wordpress/6/debian-12/docker-compose.yml b/bitnami/wordpress/6/debian-12/docker-compose.yml
index c47931cc59f..81fb4894779 100644
--- a/bitnami/wordpress/6/debian-12/docker-compose.yml
+++ b/bitnami/wordpress/6/debian-12/docker-compose.yml
@@ -4,7 +4,7 @@
 version: '2'
 services:
   mariadb:
-    image: docker.io/bitnami/mariadb:11.4
+    image: docker.io/bitnami/mariadb:10.11
     volumes:
       - 'mariadb_data:/bitnami/mariadb'
     environment:
     
$ docker-compose up -d && docker-compose logs -f wordpress

[+] Running 4/4
 ✔ wordpress Pulled                                                                                                                                                                                                                                                               40.5s
   ✔ f10caea65308 Pull complete                                                                                                                                                                                                                                                   36.2s
 ✔ mariadb Pulled                                                                                                                                                                                                                                                                 24.2s
   ✔ d5d79a82ea9b Pull complete
(...)
wordpress-1  | wordpress 09:25:23.10 INFO  ==> Ensuring WordPress directories exist
wordpress-1  | wordpress 09:25:23.10 INFO  ==> Trying to connect to the database server
(...)
wordpress-1  | wordpress 09:25:39.75 INFO  ==> Installing WordPress
wordpress-1  | Success: WordPress installed successfully.
wordpress-1  | Success: Updated custom field 'first_name'.
wordpress-1  | Success: Updated custom field 'last_name'.
wordpress-1  | Success: Rewrite structure set.
wordpress-1  | Success: Rewrite rules flushed.
wordpress-1  | wordpress 09:25:43.80 INFO  ==> Persisting WordPress installation
wordpress-1  | wordpress 09:25:47.08 INFO  ==> ** WordPress setup finished! **
wordpress-1  |
wordpress-1  | wordpress 09:25:47.11 INFO  ==> ** Starting Apache **
```

**Comment by gongomgra** [comment]
@LunkSnee I think I have found the issue and I'm working on a fix for it. 

I have found that we increased MySQL/MariaDB client minor version from `11.3` to `11.4` starting with image `wordpress-nginx:6.6.1` (see [pr/69977](https://github.com/bitnami/containers/pull/69977)). According to [MariaDB 11.4 changelog](https://mariadb.com/kb/en/mariadb-11-4-1-changelog/) they have enabled SSL by default for the client (unless the `--skip-ssl` flag is provided). I have also checked we are not having this into account on our side when the `MYSQL_CLIENT_ENABLE_SSL=no` environment variable is provided, so I will work on fixing this.

As a test, I have created a custom WordPress `6.6.1` image including the patch below and I have been able to start it against MariaDB tag `11.0.4` without issues when a database password is configured.

```
diff --git a/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh b/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh
index ad32c9c374b..1c76089d63f 100644
--- a/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh
+++ b/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh
@@ -934,6 +934,8 @@ mysql_client_extra_opts() {
             value="$(mysql_client_env_value "SSL_${key^^}_FILE")"
             [[ -n "${value}" ]] && opts+=("--ssl-${key}=${value}")
         done
+    else
+        opts+=("--skip-ssl")
     fi
     echo "${opts[@]:-}"
 }
```

Hope it works as a workaround for you as well while we work on a new release including the fix.

**Comment by gongomgra** [comment]
@LunkSnee we have just released a new revision of our WordPress image including the fix for this issue. 

```
docker pull bitnami/wordpress:6.6.1-debian-12-r3
```

You can check the changes included in this new image at https://github.com/bitnami/containers/commit/0a7377b834dcd2c3fd0cb562c37966a33c6e7708
