### ISSUE TITLE
[bitnami/discourse] Discourse doesn't start daemon processes

### ISSUE THREAD

**Issue by denysvitali** [bitnami/containers#7001]
### Name and Version

bitnami/discourse:2.8.8-debian-11-r3

### What steps will reproduce the bug?

1. Add the [Prometheus Exporter plugin](https://github.com/discourse/prometheus_exporter) to Discourse
2. Notice that it doesn't start

### What is the expected behavior?

1. Adding a plugin with a deamon makes said deamon to be registered and started by the web server

### What do you see instead?

The daemon doesn't start, because we're using `passenger` instead of `unicorn` to start Discourse, thus the [`unicorn.conf.rb`](https://github.com/discourse/discourse/blob/754ad4234493fa3af84517e8f1ed99a88ffd3171/config/unicorn.conf.rb), specifically [this part](https://github.com/discourse/discourse/blob/754ad4234493fa3af84517e8f1ed99a88ffd3171/config/unicorn.conf.rb#L116-L119) is never conisdered.

This makes the daemon to not work.

### Additional information

Is there a reason on why `passenger` is used instead of the officially supported `unicorn`?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
