### ISSUE TITLE
[bitnami/airflow-worker] base container has wrong path to dag 

### ISSUE THREAD

**Issue by malov** [bitnami/containers#7032]
### Name and Version

bitnamni/bitnami-docker-airflow-worker:2.2.2-debian-10-r8

### What steps will reproduce the bug?

1. I am upgrading currently running without issues Airflow setup based on older repos bitnami/bitnami-docker-airflow, bitnami/bitnami-docker-airflow-scheduler, bitnami/bitnami-docker-airflow-worker - from version 2.1.0-debian-10-r0 to a version 2.2.2-debian-10-r8.
2. Building new images version 2.2.2-debian-10-r8 runs fine for all components (scheduler, web, worker).
3. Building custom Airflow images happens without issues, no changes made except referencing new Bitnami images.
4. New images deployed using Bitnami Helm 11.4.2, file value.yml is not changed during upgrade, uses exactly the same parameters.
5. After deployment, web and scheduler containers created without errors, with minor but easily fixable schema errors.
6. Test dag failed to run with error:
```
[2022-09-19 18:03:26,111] {dagbag.py:500} INFO - Filling up the DagBag from /opt/bitnami/***/dags/test_dag.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 276, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 192, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: Dag 'test_dag' could not be found; either it does not exist or it failed to parse.
```

After checking worker pod, I found that in its description (see attached file testdag.dev.txt attached), base pod has Args
```
    Args:
      airflow
      tasks
      run
      test_dag
      print_current_date
      manual__2022-09-15T14:57:53.955329+00:00
      --local
      --subdir
      DAGS_FOLDER/test_dag.py
```
while in previous version, same Args looked differently (see attached file testdag.prod.txt):
```
    Args:
      airflow
      tasks
      run
      test_dag
      print_current_date
      2022-09-19T17:05:00+00:00
      --local
      --pool
      default_pool
      --subdir
      /airflow-workflows/dags/test_dag.py

```

Note the "subdir" argument, which in latter case has correct path to the dag.

[testdag.dev.txt](https://github.com/bitnami/containers/files/9601590/testdag.dev.txt)
[testdag.prod.txt](https://github.com/bitnami/containers/files/9601591/testdag.prod.txt)

### What is the expected behavior?

I would expect worker pod to have a correct path to the dag in its "subdir" argument

### What do you see instead?

I see that path to the dag has seemingly default value DAG_FOLDERS, unresolved.

### Additional information

Let me know if you need more information.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Airflow container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by malov** [comment]
I don't think it's an application configuration by itself, it's whatver has been changed between 2.1.0 and 2.2.2 versions. Reason: there has been no change in environment or application configuration during upgrade, only image version, but it triggered this problem.

**Comment by malov** [comment]
If you're too reluctant to work on this, could you at least point me - where should I look to troubleshoot it? How are these arguments built? If command is not picking up DAG path from anywhere where it's configured - where it's picking it up?

**Comment by carrodher** [comment]
In order to see what changed from 2.1.0 to 2.2.2, I recommend you to take a look at the [application changelog](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html) or ask in any support forum from the application itself

**Comment by malov** [comment]
Damn it. Don't you think I didn't look at it before posting here? It's not the problem of Airflow, it's a problem of YOUR packaging. I thought commercial support is useless, but yours is no better. Will recommend anyone against using your images.
Thanks for nothing.
