### ISSUE TITLE
Event Log Clarity 

### ISSUE THREAD

**Issue by sunflowerno0b** [bitnami/containers#7033]
### Name and Version

bitnami-docker-keycloak , version 15

### What steps will reproduce the bug?

1. Log into admin console 
2. On left panel, select Events 
3. Select Filter
4. Add client
5. Add username 
6. Select update 

### What is the expected behavior?

I want to be able to filter log in events by user. Additionally, I would like to be able to customize the fields within the event to reflect username rather than user ID string. When looking filtering through my users with their associated ID they should show in the results. currently, that does not happen.

### What do you see instead?

I do not see the filtered criteria when I enter a username.

### Additional information

When I try to filter by the user ID this also does not work. Ideally, I want to have a log of events that show me the date, IP, client, and username and user ID (optional).  I want to be able to go to my user list and filter for an userID and have results.

**Comment by rafariossaa** [comment]
Hi,
  This is a request for the keycloak application, I would suggest you to open a request in keycloak forums. This issues threads are for issues related to the container operation.

**Comment by sunflowerno0b** [comment]
closing - for those curious moved [here](https://github.com/keycloak/keycloak/issues/14506)
