### ISSUE TITLE
[bitnami/minio] deprecated setting

### ISSUE THREAD

**Issue by devarfima** [bitnami/containers#70393]
### Name and Version

bitnami/minio:2024.7.16-debian-12-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In a linux machine using docker compose.
2.  With the docker compose service:
```yaml
services:
  minio:
    container_name: mini
    image: bitnami/minio:2024.7.16-debian-12-r2

    volumes:
      - minio:/bitnami/minio/data


    restart: always

    env_file:
      - ./secrets/minio/.env

    ports:
      - '9000:9000'
      - '9001:9001'
volumes:
  minio:
    driver: local
```

And the env_file:
```
MINIO_SCHEME=http
MINIO_SERVER_URL=http://localhost:9091/rrr/
```
3. Run `docker compose up -d`.

### What is the expected behavior?

The expected behaviour is the service to start and being able to access minio.

### What do you see instead?

The container keeps restarting.

The log:
```
 16:50:32.48 INFO  ==> 
 16:50:32.48 INFO  ==> Welcome to the Bitnami minio container
 16:50:32.49 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 16:50:32.49 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:50:32.49 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
 16:50:32.49 INFO  ==> 
 16:50:32.49 INFO  ==> ** Starting MinIO setup **
minio 16:50:32.53 INFO  ==> Starting MinIO in background...
minio 16:50:42.61 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:50:47.64 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:50:52.67 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:50:57.71 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:02.73 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:07.76 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:12.81 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:17.83 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:22.86 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:27.90 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:32.93 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:51:37.97 INFO  ==> Adding local Minio host to 'mc' configuration...
Failed to add temporary MinIO server
minio 16:51:43.00 INFO  ==> MinIO is already stopped...
```

### Additional information

The issue comes from using `MINIO_SERVER_URL` which was [deprecated ](https://min.io/docs/minio/linux/reference/minio-server/settings/deprecated.html#envvar.MINIO_SERVER_URL) since RELEASE.2024-05-10T01-41-38Z. Using `MINIO_BROWSER_REDIRECT_URL` instead fixes the problem.

I think that the README should reflect that.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
