### ISSUE TITLE
[bitnami/keycloak] Use Java 21 starting with version 25

### ISSUE THREAD

**Issue by antikalk** [bitnami/containers#70424]
### Name and Version

bitnami/keycloak:25.0.2

### What is the problem this feature will solve?

With the release of Keycloak 25 the Keycloak Team deprecated the support for Java 17. With Keycloak 26 the support will be dropped completely. In favor of Java 17, Java 21 should be used. Find the official information here: https://www.keycloak.org/2024/06/keycloak-2500-released

### What is the feature you are proposing to solve the problem?

Providing Java 21 in the image.

**Comment by vquie** [comment]
This is also an issue when working with 3rd party plugins as they followed the update to Java 21.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
