### ISSUE TITLE
Error run image mysqld-exporter

### ISSUE THREAD

**Issue by Gil9091e10** [bitnami/containers#70449]
### Name and Version

bitnami/mysqld-exporter

### What architecture are you using?

amd64

### What steps will reproduce the bug?

run command 
```
docker run --name mysqld-exporter-node1 --network bd2-network bitnami/mysqld-exporter:latest --config.my-cnf=/.my.cnf
```
File content .my.cnf:
```
[client]
user=exporterBd2
password=ExporterBd2
host=bd2-mysql
port=33061
```
throw error: 
```
ts=2024-07-30T20:06:58.993Z caller=mysqld_exporter.go:220 level=info msg="Starting mysqld_exporter" version="(version=0.15.1, branch=HEAD, revision=cc349684494b5038ec5a52233bdca9eb9291e6f2)"
ts=2024-07-30T20:06:58.994Z caller=mysqld_exporter.go:221 level=info msg="Build context" build_context="(go=go1.21.12, platform=linux/amd64, user=root@14ea8ec3e811, date=20240704-10:10:59, tags=unknown)"
ts=2024-07-30T20:06:58.994Z caller=config.go:150 level=error msg="failed to validate config" section=client err="no user specified in section or parent"
ts=2024-07-30T20:06:58.994Z caller=mysqld_exporter.go:225 level=info msg="Error parsing host config" file=/.my.cnf err="no configuration found"
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
