### ISSUE TITLE
Drupal could not connect database

### ISSUE THREAD

**Issue by ces-truongvu** [bitnami/containers#70453]
### Name and Version

bitnami/drupal:10-debian-12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I have 2 components (drupal & mariadb) running in K3S cluster. 
2. A docker image built right before your latest updated working fine, after that I got the following issue

### What do you see instead?

```
drupal 04:19:26.76 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
drupal 04:19:31.77 ERROR ==> Could not connect to the database
```

**Comment by ces-truongvu** [comment]
It could be somehow related to this [commit](https://github.com/bitnami/containers/commit/60b852c046165397df3db4797fa8eabd26006461).

**Comment by gongomgra** [comment]
Hi @ces-truongvu,

Thanks for using Bitnami and for sharing this issue. It seems to be related to the MariaDB client update that was introduced in our recent releases. You can apply the workaround in the link below to the `libmysqlclient.sh` script included under the `bitnami/drupal` folder of the repo and build a custom image while we work on a new release with the fix.

https://github.com/bitnami/containers/issues/70392#issuecomment-2260885622

**Comment by ces-truongvu** [comment]
@gongomgra Thank you for your support.

**Comment by gongomgra** [comment]
Hi everyone,

We have just released a new revision of our Drupal image including the fix for this issue. 

```
docker pull bitnami/drupal:10.3.1-debian-12-r7
```

You can check the changes included in this new image at https://github.com/bitnami/containers/commit/124c08bcfc92d80c9a6ad5568b9bc3ed991fadee

**Comment by ces-truongvu** [comment]
@gongomgra It works. Thank you for all your assistance.
