### ISSUE TITLE
[bitnami/postgresql-repmgr] repmgr extension not installed when running container as root

### ISSUE THREAD

**Issue by melissa-hale** [bitnami/containers#70452]
### Name and Version

bitnami/postgresql-repmgr:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Run the `bitnami/postgresql-repmgr` image as UID 0
2. Observe error below when starting repmgrd about the extension not installed
```
postgresql-repmgr 00:48:12.76 INFO  ==> ** Starting repmgrd **
[2024-07-31 00:48:12] [NOTICE] repmgrd (repmgrd 5.4.1) starting up
[2024-07-31 00:48:12] [INFO] connecting to database "user=repmgr password=password host=primary dbname=repmgr port=5432 connect_timeout=5"
[2024-07-31 00:48:12] [DEBUG] connecting to: "user=repmgr password=password connect_timeout=5 dbname=repmgr host=primary port=5432 fallback_application_name=repmgr options=-csearch_path="
[2024-07-31 00:48:12] [ERROR] repmgr extension not found on this node
[2024-07-31 00:48:12] [DETAIL] repmgr extension is available but not installed in database "repmgr"
[2024-07-31 00:48:12] [HINT] check that this node is part of a repmgr cluster
```

### What is the expected behavior?

That repmgr starts successfully when the container is running as root

### What do you see instead?

Upon container start, when repmgrd was starting, the error was observed regarding the extension not being installed:

```
postgresql-repmgr 00:48:12.76 INFO  ==> ** Starting repmgrd **
[2024-07-31 00:48:12] [NOTICE] repmgrd (repmgrd 5.4.1) starting up
[2024-07-31 00:48:12] [INFO] connecting to database "user=repmgr password=password host=primary dbname=repmgr port=5432 connect_timeout=5"
[2024-07-31 00:48:12] [DEBUG] connecting to: "user=repmgr password=password connect_timeout=5 dbname=repmgr host=primary port=5432 fallback_application_name=repmgr options=-csearch_path="
[2024-07-31 00:48:12] [ERROR] repmgr extension not found on this node
[2024-07-31 00:48:12] [DETAIL] repmgr extension is available but not installed in database "repmgr"
[2024-07-31 00:48:12] [HINT] check that this node is part of a repmgr cluster
```

### Additional information

Wanted to mention the reason I need to run the image as root - I'm deploying this image to Railway, and I am mounting a volume to the container in order to persist the data.  When the volume is mounted, it is owned by root, and I do not have the ability to change the underlying host to change the permissions on the filesystem.  I tried a custom entrypoint solution, to CHOWN the mount path when the container starts, but this was problematic too since it required sudo and it seems the user 1001 is not known to the image until the container runs.

I hacked a bit on different solutions until deciding to flag this with the Bitnami team.  Some of the notes I see in the source repo, for example [this line here](https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/16/debian-12/rootfs/opt/bitnami/scripts/postgresql-repmgr/run.sh#L26), make me think you all intend for the image to work if run with root, but maybe it wasn't tested with repmgr.  Really hoping it's something simple!  Happy to provide any more information, or try anything in my implementation.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by melissa-hale** [comment]
I was able to address this error by updating the `librepmgr.sh` script to mimic the pattern in the `libpostgresql.sh` script and check whether the container is running as root.  If it is running as root, then explicitly run repmgr as the POSTGRESQL_DAEMON_USER.

as an example, the repmgr_register_primary() function -

Before:

```bash
repmgr_register_primary() {
    info "Registering Primary..."
    local -r flags=("-f" "$REPMGR_CONF_FILE" "master" "register" "--force")

    debug_execute "${REPMGR_BIN_DIR}/repmgr" "${flags[@]}"
}
```

After:

```bash
repmgr_register_primary() {
    info "Registering Primary..."
    local -r flags=("-f" "$REPMGR_CONF_FILE" "master" "register" "--force")
    local repmgr_cmd=()

    if am_i_root; then
        repmgr_cmd+=("run_as_user" "$POSTGRESQL_DAEMON_USER")
    fi

    repmgr_cmd+=("${REPMGR_BIN_DIR}/repmgr" "${flags[@]}")

    debug_execute "${repmgr_cmd[@]}"
}
```

**Comment by javsalgar** [comment]
Hi!

Thanks for sharing your solution. Would you like to submit a PR so the community can benefit from this?

**Comment by melissa-hale** [comment]
Heck yeah, would love to PR it.  I'll try to get one in by EOD

**Comment by javsalgar** [comment]
Thank you so much!
