### ISSUE TITLE
[bitnami/keycloak] Use Hostname v2 in Keycloak v25 images

### ISSUE THREAD

**Issue by singhbaljit** [bitnami/containers#70461]
### Name and Version

bitnami/keycloak:25

### What is the problem this feature will solve?

Hostname v1 options were [deprecated (disabled?) in Keycloak v25](https://www.keycloak.org/docs/latest/upgrading/index.html#new-hostname-options). Per docs:

> Hostname v2 options are supported by default, as the old hostname options are deprecated and will be removed in the following releases. New options are activated by default, so Keycloak will not recognize the old options.

We need to update container entrypoint scripts. Currently, there's only one variable `KEYCLOAK_HOSTNAME`. We should probably add `KEYCLOAK_HOSTNAME_ADMIN` as well. Currently, the chart is specifying `KC_HOSTNAME_URL` and `KC_HOSTNAME_ADMIN_URL` directly; the chart should use these variables instead (see https://github.com/bitnami/charts/issues/28586). `hostname-strict`/`hostname-backchannel-dynamic` options need to updated accordingly as well.

### What is the feature you are proposing to solve the problem?

Migrate to use V2 hostname so that we can simplify definition of these variables in the Keycloak chart.

### What alternatives have you considered?

No alternative as the v1 hostname variables are disabled by default, and will be removed.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by singhbaljit** [comment]
I'm working on an PR, will have it up shortly for review

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
