### ISSUE TITLE
(SuiteCRM and Mariadb) -> TLS/SSL error: SSL is required, but the server does not support it.

### ISSUE THREAD

**Issue by TomCalde** [bitnami/containers#70504]
### Name and Version

bitnami/suitecrm:8.6

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm using Docker Compose to run bitnami/suitecrm:8.6 with mariadb:10.11.

### What do you see instead?

![Sin título](https://github.com/user-attachments/assets/fb75426c-2c5f-4eba-b95e-13b00ae40ab8)

### Additional information

I'm using an image to run a container with mariadb:10.11 and suitecrm:8.6, and I'm receiving the following error: ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it.

**Comment by gongomgra** [comment]
Hi @TomCalde,

We have just released a new revision of our WordPress image including the fix for this issue. 

```
docker pull bitnami/suitecrm:8.6.1-debian-12-r5
```

You can check the changes included in this new image at https://github.com/bitnami/containers/commit/9084829eb13a051ae4de272e34483fc9cac3c7e2

**Comment by TomCalde** [comment]
Hi @gongomgra,

Thanks for the reply. It works.
