### ISSUE TITLE
Unable to upgrade minio from 2021.4.22-debian-10-r6 to 2022.4.30-debian-10-r2

### ISSUE THREAD

**Issue by varadaprakash** [bitnami/containers#70509]
### Name and Version

docker.io/bitnami/minio:2022.4.30-debian-10-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy minio:2021.4.22-debian-10-r6 as container
2. Upgrade minio:2022.4.30-debian-10-r2

### What is the expected behavior?

Upgrade should be successful.

### What do you see instead?

I see following minio is running in infinite loop with following message and error
```
minio 09:20:15.33 INFO  ==> Adding local Minio host to 'mc' configuration...
ERROR Unable to use the drive /data: Drive /data: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
```

I tried to look into the above mentioned migration link but it's not supported in containers.

### Additional information

Could you please help us to upgrade minio on containers from 2021.4.22-debian-10-r6 to 2024.5.10-debian-12-r2

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
