### ISSUE TITLE
auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.

### ISSUE THREAD

**Issue by shettypriy** [bitnami/containers#70515]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
mongodump --username=${MONGODB_ROOT_USER}
              --password=${MONGODB_ROOT_PASSWORD} --authenticationDatabase=admin
              --host=${MONGODB_SERVICE_NAME} --port=${MONGODB_PORT_NUMBER}
              ${MONGODB_CLIENT_EXTRA_FLAGS} --gzip
              --archive=${MONGODUMP_DIR}/mongodump-$(date '+%Y-%m-%d-%H-%M').gz
```
### What is the expected behavior?

mongodump should create the backup 

### What do you see instead?
```
container "mongodb-mongodump" in pod "mongodb-mongodump-202408021322-5zv4j" is waiting to start: ContainerCreating
2024-08-02T13:23:02.581+0000	Failed: can't create session: failed to connect to mongodb://mongodb:27017/: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.
```
### Additional information

using the mongodb chart version 15.6.16

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
