### ISSUE TITLE
debian base image - changing the locale to UTF-8

### ISSUE THREAD

**Issue by jarqvi** [bitnami/containers#70548]
### Name and Version

bitnami/*

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I just noticed that Bitnami uses Debian as the base image for their other images. However, I've also observed that several bugs related to changing the locale to UTF-8 have remained unresolved for many years:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684134
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=500164

For example, I can't use the -O flag to set the CHARSET in the unzip command, which forces me to use Ubuntu as the base image instead.

Does the bitnami team have a plan for this?

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is built on top of Debian 12 and there are no plans to change the distro in the mid-term. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4 & 5, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.

**Comment by jarqvi** [comment]
Thanks @carrodher
