### ISSUE TITLE
[bitnami/redis]  Container Doese not change default port ! 

### ISSUE THREAD

**Issue by ariyaee1367** [bitnami/containers#70578]
### Name and Version

/bitnami/redis:6.2.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

env 

### What is the expected behavior?

```
REDIS_DEFAULT_PORT_NUMBER=6320
```
doese not work !!!!
also change port on this path etc.default/redis-default.conf
etc.default/redis.conf
etc/redis-default.conf
etc/redis.conf
also change on this path /opt/ doese not work !!!!!!

### What do you see instead?

doese not chage default port redis !!!

### Additional information

!!

**Comment by javsalgar** [comment]
Hi,

Just to understand. Do you want to change the port in the default configuration files. Did you try setting REDIS_PORT_NUMBER to see if the container actually listens in the port you want at runtime?

**Comment by ariyaee1367** [comment]
> Hi,
> 
> Just to understand. Do you want to change the port in the default configuration files. Did you try setting REDIS_PORT_NUMBER to see if the container actually listens in the port you want at runtime?

Hi , 
Yes , i want change default port on the redis/bitnami docker image .
I change all port number on the bitnami container config files . but my chnages doese not write and my container listen default port  , also i set REDIS_PORT_NUMBER  env on the docker compose file , but frim container side diese not wire and my container listen to default port .
here is my compose file :

  redis-slave:
    container_name: redis-slave
    image: 'docker.mofid.dev/bitnami/redis:6.2.14'
    environment:
      - REDIS_MASTER_PASSWORD=1qazsweefkhbgjh
      - REDIS_PASSWORD=1qazsweefkhbgjh
      - REDIS_SENTINEL_HOSTS=192.168.1.1:26379,192.168.1.1:26379,192.168.1.1:26379
      - REDIS_DEFAULT_PORT_NUMBER=6320
    volumes:
      - /root/redis-sentinel/redis-slave-data:/bitnami
      - /root/redis-sentinel/slave/:/opt/bitnami/
    depends_on:
      - redis-master
on the volume path i change default port but doese not change , also this env REDIS_DEFAULT_PORT_NUMBER=6320   doese not work . for more condition i attach the container and change port my redis , that is default port,

**Comment by andresbono** [comment]
Hi, as my teammate mentioned, the env-var `REDIS_PORT_NUMBER` can be passed to change the port in which Redis will be listening to.

You will need to restart your docker compose.
