### ISSUE TITLE
bitnami/drupal installation issue on Azure file-share

### ISSUE THREAD

**Issue by dlynch33** [bitnami/containers#70584]
### Name and Version

bitnami/drupal:10.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy Bitnami  Drupal container to Azure Container Apps using an Azure storage account file share as the mounted volume.  Essentially following this approach: https://github.com/Azure-Samples/drupal-on-azure-container-apps

### What do you see instead?

Seeing some errors on container initialization:
```
drupal 20:32:34.41 INFO  ==> Persisting Drupal installation
setfacl: sites: Operation not permitted
setfacl: sites/default: Operation not permitted
setfacl: sites/default/files: Operation not permitted
setfacl: sites/default/files/.htaccess: Operation not permitted
setfacl: sites/default/files/styles: Operation not permitted
setfacl: sites/default/files/config_5oUIhbPoT0v3X14n7-jkhJIIQC4Sd9Vy4V0YMjvFtFZzf9lSyZztImRTz2CCYmWfvKLIJw4xzQ: Operation not permitted
setfacl: sites/default/files/config_5oUIhbPoT0v3X14n7-jkhJIIQC4Sd9Vy4V0YMjvFtFZzf9lSyZztImRTz2CCYmWfvKLIJw4xzQ/sync: Operation not permitted
setfacl: sites/default/files/config_5oUIhbPoT0v3X14n7-jkhJIIQC4Sd9Vy4V0YMjvFtFZzf9lSyZztImRTz2CCYmWfvKLIJw4xzQ/sync/README.txt: Operation not permitted
setfacl: sites/default/files/config_5oUIhbPoT0v3X14n7-jkhJIIQC4Sd9Vy4V0YMjvFtFZzf9lSyZztImRTz2CCYmWfvKLIJw4xzQ/sync/.htaccess: Operation not permitted
setfacl: sites/default/settings.php: Operation not permitted
setfacl: sites/default/default.settings.php: Operation not permitted
setfacl: sites/default/default.services.yml: Operation not permitted
setfacl: sites/development.services.yml: Operation not permitted
setfacl: sites/README.txt: Operation not permitted
setfacl: sites/example.sites.php: Operation not permitted
setfacl: sites/example.settings.local.php: Operation not permitted
```

Likely these are caused by the Azure SMB file-share not supporting POSIX permissions.  I've found that running the container as root surpresses these errors, but the commands don't do anything.

Any way to prevent the setfacl (and chmod) commands from being executed on files that are persisted to the mounted volume?

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by dlynch33** [comment]
Thanks @carrodher, running as non-root is definitely my preference and intent - switching to root was just temporary troubleshooting.  The setfacl, chmod, chown commands will never work on an Azure SMB file-share, so ideally, to support this deployment topology, there would be an option - e.g. an env var - that could be used to specify that they should be skipped.  Thoughts?  Thanks again!
