### ISSUE TITLE
[bitnami/postgresql-repmgr] Running custom script on primary database when container starting

### ISSUE THREAD

**Issue by ThomasRasmussen** [bitnami/containers#70606]
### Name and Version

bitnami/postgresql-repmgr:16.3.0

### What is the problem this feature will solve?

Whenever the database container is started, I want to have some sanity check preformed on the database and possibly fix something in the database if need be.
As far as I can see there is only the docker-entrypoint.initdb.d directory but this is only sourced the first time the database is initialized and then a file will prevent scripts here ever being run again.

One usecase is infact related to upgrading the container from 16.1.0 to 16.3.0 where a collation version needs to be refreshed. I wanted to dump a script that will detect if a collation refresh is needed and then perform the necessary actions. But I cannot see any way of implementing this in the current image.

### What is the feature you are proposing to solve the problem?

Having a change in the startup scripts that will always run the scripts in fx. /docker-entrypoint.d/*.{sh,sql} - something like the way it is done with /docker-entrypoint-initdb.d/ but without the limit on only running on initialization of database.

### What alternatives have you considered?

* manually hacking the startup scripts to implement this
* Having an external app running this (requires the app to have access to db as postgres user)

**Comment by javsalgar** [comment]
Hi,

In other containers like clickhouse or mariadb we have a `docker-entrypoint-startdb.d` which runs scripts always. Would this work for your use case? If so, I will forward it to the team, but as it is not a critical feature we cannot gurantee an ETA. If you want to speed up the process, you can submit a PR adding the same logic as we have in the mariadb container.

https://github.com/bitnami/containers/blob/main/bitnami/mariadb/11.4/debian-12/rootfs/opt/bitnami/scripts/mariadb/setup.sh#L37

**Comment by ThomasRasmussen** [comment]
Hi
Yes, I did try to "hack" it so it will always run the scripts and then it does work like other containers.

I'll see if I can create a PR to implement this feature

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
