### ISSUE TITLE
[bitnami/keycloak] Add management port to EXPOSE

### ISSUE THREAD

**Issue by antikalk** [bitnami/containers#70612]
### Name and Version

bitnami/keycloak:25.0.2

### What is the problem this feature will solve?

With keycloak 25 the default management port for metrics and health endpoint changed. It is no longer on the standard keycloak port but as per default on port `9000`. See https://www.keycloak.org/2024/06/keycloak-2500-released . This should be highlighted in the EXPOSE instruction of the dockerfile to improve the documentation. 

### What is the feature you are proposing to solve the problem?

Add port `9000` to the EXPOSE instruction.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
