### ISSUE TITLE
[bitnami/cassandra] Client TLS certificate generation fails due to non-existing certs folder

### ISSUE THREAD

**Issue by tbalzer** [bitnami/containers#70738]
### Name and Version

bitnami/cassandra:4.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In eks-based k8s cluster using `bitnami/cassandra` helm chart version `11.3.12`

2. with the following configuration

```yaml
tls:
  internodeEncryption: "all"
  clientEncryption: true
  autoGenerated: true
```

3. Install the helm chart and observe the pod logs

### What is the expected behavior?

Pod starting up with the provided certificate

### What do you see instead?

Errors in logs, pod not starting up:

init-certs:
```
Importing keystore /tmp/keystore.p12 to /opt/bitnami/cassandra/certs/keystore...
Entry for alias 1 successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Certificate was added to keystore
```
cassandra (skipping boilerplate):
```
Setting node as password seeder
cassandra 12:42:32.87 INFO  ==> ** Delaying Cassandra start by 10 seconds **
cassandra 12:42:42.87 INFO  ==> ** Starting Cassandra setup **
cassandra 12:42:42.89 WARN  ==> DB_HOST not set, defaulting to system hostname
cassandra 12:42:42.89 INFO  ==> Validating settings in DB_* env vars..
cassandra 12:42:42.91 INFO  ==> Validating TLS settings in DB_* env vars..
cassandra 12:42:42.92 INFO  ==> Initializing cassandra database...
cassandra 12:42:43.15 INFO  ==> Configuring client for SSL
Importing keystore /opt/bitnami/cassandra/certs/keystore to /opt/bitnami/cassandra/tmp/keystore.p12...
Entry for alias 1 successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
pkcs12: Can't open "/bitnami/cassandra/certs/tls.crt" for writing, No such file or directory
```
following startups show different error for cassandra:
```
Setting node as password seeder
cassandra 12:43:08.14 INFO  ==> ** Delaying Cassandra start by 10 seconds **
cassandra 12:43:18.14 INFO  ==> ** Starting Cassandra setup **
cassandra 12:43:18.16 WARN  ==> DB_HOST not set, defaulting to system hostname
cassandra 12:43:18.16 INFO  ==> Validating settings in DB_* env vars..
cassandra 12:43:18.18 INFO  ==> Validating TLS settings in DB_* env vars..
cassandra 12:43:18.19 INFO  ==> Initializing cassandra database...
cassandra 12:43:18.43 INFO  ==> Configuring client for SSL
Importing keystore /opt/bitnami/cassandra/certs/keystore to /opt/bitnami/cassandra/tmp/keystore.p12...
keytool error: java.lang.NullPointerException: invalid null input
Existing entry alias 1 exists, overwrite? [no]:  Enter new alias name   (RETURN to cancel import for this entry):  
```

### Additional information

I narrowed it down to https://github.com/bitnami/containers/blob/5b87c6c568387e7d89c11b2ef8c7335f0d6c7f37/bitnami/cassandra/4.1/debian-12/rootfs/opt/bitnami/scripts/libcassandra.sh#L71-L72

with the path defined in

https://github.com/bitnami/containers/blob/5b87c6c568387e7d89c11b2ef8c7335f0d6c7f37/bitnami/cassandra/4.1/debian-12/rootfs/opt/bitnami/scripts/cassandra-env.sh#L220-L221

not existing.

The `certs` directory is never created inside the volume which is mounted at `CASSANDRA_VOLUME_DIR`/`DB_VOLUME_DIR`

**Comment by tbalzer** [comment]
PR with fix is attached for your consideration

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
