### ISSUE TITLE
[bitnami/schema-registry] Support IAM auth way

### ISSUE THREAD

**Issue by hongbo-miao** [bitnami/containers#70769]
### Name and Version

bitnami/schema-registry:7.7.0

### What is the problem this feature will solve?

I am hoping to use AWS IAM auth way according to

- https://github.com/confluentinc/schema-registry/issues/1898#issuecomment-1289526114
- https://stackoverflow.com/questions/70500586/using-confluent-schema-registry-with-msk/70522089#70522089

But then found

- `SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_CLIENT_CALLBACK_HANDLER_CLASS`

do not exist in https://github.com/bitnami/containers/tree/main/bitnami/schema-registry#configuration

It only exist in [confluentinc/cp-schema-registry](https://hub.docker.com/r/confluentinc/cp-schema-registry).

### What is the feature you are proposing to solve the problem?

It would be great to support similar envs so that we can use IAM auth way, thanks!

### What alternatives have you considered?

Use [confluentinc/cp-schema-registry](https://hub.docker.com/r/confluentinc/cp-schema-registry) Docker image.

**Comment by carrodher** [comment]
The environment variables used by the bitnami/schema-registry container are listed at https://github.com/bitnami/containers/tree/main/bitnami/schema-registry#environment-variables. Although the exact name does not have to match other schema-registry containers, there is likely some variable for the same purpose.

**Comment by hongbo-miao** [comment]
Hi @carrodher sorry, I forgot to put that link in the description. I actually tried to find matched env in the list. But still cannot find these four corresponding ones 🥲

- `SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG`
- `SCHEMA_REGISTRY_KAFKASTORE_SASL_CLIENT_CALLBACK_HANDLER_CLASS`

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding support for these env vars.
