### ISSUE TITLE
[bitnami/discourse] Upgrade from 3.2.5 to 3.3.0 results in broken Discourse with chmod error for missing node_modules/ember-cli/bin/ember

### ISSUE THREAD

**Issue by sainty** [bitnami/containers#70884]
### Name and Version

bitnami/discourse:3.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Running Docker on UIbuntu 22.04.4 LTS with Bitnami Discourse 3.2.5 talking to a PostgreSQL DB without issues.
2. Stop Discourse 3.2.5 container via docker compose, as per usual.
3. Modify docker-compose to use the latest 3.3.0 tagged release.
4. Start Discourse 3.3.0 container via docker compose.

### What is the expected behavior?

With persistent storage, any migration tasks required should run without error, and Discourse 3.3.0 should successfully launch, handle connections, provide content, etc.

### What do you see instead?

Discourse 3.3.0 fails to launch...

```
discourse 06:27:20.63 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 06:27:20.65 DEBUG ==> Validating settings in DISCOURSE_* environment variables...
discourse 06:27:20.66 INFO  ==> Creating Discourse configuration file
...
discourse 06:27:20.71 INFO  ==> Enabling SMTP
...
discourse 06:27:32.84 INFO  ==> Restoring persisted Discourse installation
discourse 06:27:32.86 INFO  ==> Trying to connect to the database server
 ?column? 
----------
        1
(1 row)

discourse 06:27:32.89 INFO  ==> Running database migrations
chmod: cannot access '/opt/bitnami/discourse/app/assets/javascripts/node_modules/ember-cli/bin/ember': No such file or directory
```

This results in a loop of failed attempts to start Bitnami Discourse 3.3.0.

### Additional information

- I can confirm that `/opt/bitnami/discourse/app/assets/javascripts/node_modules/ember-cli/bin/ember` indeed does _not_ exist in the 3.3.0 image / container?
- Bitnami Discourse 3.2.5 was working 100% fine prior to the attempt to move to the 3.3.0 image.
- I've tried and replicated this more than once.

**Comment by javsalgar** [comment]
Hi!

We're currently working on fixing the issue in the new container image. As soon as we have more news, we will let you know.

**Comment by sainty** [comment]
That's fantastic @javsalgar , and a super quick reply. Thank you!  I'll look forward to testing it when its available... :+1:
