### ISSUE TITLE
[bitnami/redis] Mount Path for init-scripts?

### ISSUE THREAD

**Issue by manuschillernordlb** [bitnami/containers#70885]
### Name and Version

bitnami/redis:7.4.0-debian-12-r0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I want to run a post-configure script after redis started up successfully.
Therefore I tried mounting a script to the two default locations used by other bitnami containers:

```docker-compose.yaml
# docker-compose.yaml
version: "2.28.1"

services: 
  redis:
    image: bitnami/redis
    ports: [ "6379:6379" ]
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    configs:
      - source: redis-acl
        target: /docker-entrypoint-initdb.d/redis-init.sh
      - source: redis-acl
        target: /opt/bitnami/scripts/redis-init.sh
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep PONG
configs:
  redis-acl:
    file: ./docker/conf/redis/acl.sh
```

```docker/conf/redis/acl.sh
#!/bin/sh
# docker/conf/redis/acl.sh

# todo: login

ACL SETUSER "${CONSUMER_USERNAME}" on >"${CONSUMER_PASSWORD}" ~"${CONSUMER_GROUP_PREFIX}"* +xread +xack +xgroup +xreadgroup +xack
```

### What is the expected behavior?

The script gets executed after start-up

### What do you see instead?

The script does not get executed

**Comment by javsalgar** [comment]
Hi,

I'm afraid the redis container still does not have support for init scripts. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. However, if you want to speed up the process, you can submit a PR to the libredis.sh file (copying the logic used in other containers) and the team will check it.
