### ISSUE TITLE
[bitnami/odoo] session_db module will not install

### ISSUE THREAD

**Issue by b-milescu** [bitnami/containers#70922]
### Name and Version

bitnami/odoo15

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. download the addon from [here](https://github.com/OCA/server-tools/tree/15.0/session_db)
2. modify odoo.conf.tpl to add the line: `server_wide_modules = base,web,session_db`
3. rebuild the container image
4. edit the docker-compose file to mount the addon in the addons path
5. `docker-compose up`

### What is the expected behavior?

Addon should load without any issue

### What do you see instead?

```
debian-12-odoo-1        | 2024-08-14 10:29:43,207 1 CRITICAL ? odoo.modules.module: Couldn't load module session_db 
debian-12-odoo-1        | 2024-08-14 10:29:43,207 1 CRITICAL ? odoo.modules.module: No module named 'werkzeug.contrib' 
debian-12-odoo-1        | 2024-08-14 10:29:43,207 1 ERROR ? odoo.service.server: Failed to load server-wide module `session_db`. 
debian-12-odoo-1        | Traceback (most recent call last):
debian-12-odoo-1        |   File "/opt/bitnami/odoo/lib/odoo-15.0.post20240710-py3.10.egg/odoo/service/server.py", line 1210, in load_server_wide_modules
debian-12-odoo-1        |     odoo.modules.module.load_openerp_module(m)
debian-12-odoo-1        |   File "/opt/bitnami/odoo/lib/odoo-15.0.post20240710-py3.10.egg/odoo/modules/module.py", line 407, in load_openerp_module
debian-12-odoo-1        |     __import__('odoo.addons.' + module_name)
debian-12-odoo-1        |   File "/bitnami/odoo/addons/session_db/__init__.py", line 1, in <module>
debian-12-odoo-1        |     from . import pg_session_store
debian-12-odoo-1        |   File "/bitnami/odoo/addons/session_db/pg_session_store.py", line 12, in <module>
debian-12-odoo-1        |     import werkzeug.contrib.sessions
debian-12-odoo-1        | ModuleNotFoundError: No module named 'werkzeug.contrib'
```

### Additional information

I've tried to install the missing python [module](https://pypi.org/project/Werkzeug) but it throws the same error

**Comment by javsalgar** [comment]
Hi,

It seems that there is a python module missing that you may need to install. Could you double check it?

**Comment by javsalgar** [comment]
Could you ensure that you used this `/opt/bitnami/odoo/venv/bin/pip` command to install the missing module? By default it uses `/opt/bitnami/python/bin/pip` and that may not work as expected.

**Comment by b-milescu** [comment]
Sure, I'll test and get back

**Comment by b-milescu** [comment]
Worked OK, thanks!
