### ISSUE TITLE
[bitnami/openldap] LDAP_ROOT is not created when a LDAP_CUSTOM_LDIF_DIR is specified

### ISSUE THREAD

**Issue by FSeifer** [bitnami/containers#70944]
### Name and Version

bitnami/openldap:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Create a docker-compose.yml with the following entries:
```
      - LDAP_LOGLEVEL=512
      - LDAP_ROOT=dc=iamext,dc=de
      - LDAP_ADMIN_DN=cn=admin,dc=iamext,dc=de
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=<ADMINPW>
      - LDAP_USERS=readonly
      - LDAP_PASSWORDS=<USERPW>
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/iamext-ldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/iamext-ldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/CA-chain.crt
      - LDAP_TLS_DH_PARAMS_FILE=/opt/bitnami/openldap/certs/dhparams.pem
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_CUSTOM_LDIF_DIR=/opt/scripts
```
- Start the container
- Try to connect via ldapsearch

### What is the expected behavior?

It should list the directory with the root DN and the custom OUs added by the ldif file under /opt/scripts

### What do you see instead?

- Connection Error due to the fact that the certificate paths are not added to cn=config.ldif

### Additional information

Is it expected behavour that all the LDAP_TLS-Env-Vars are ignored when I specify  LDAP_CUSTOM_LDIF_DIR ?

**Comment by javsalgar** [comment]
Hi,

Could you share the initialization logs to see if there is anything meaningful?

**Comment by FSeifer** [comment]
There was in fact a simple typo in my custom ldif file, which lead to the slapd config not being written due to an error.

I am withdrawing the issue.
