### ISSUE TITLE
[bitnami/redis-cluster] Cannot create Redis cluster with other than default user

### ISSUE THREAD

**Issue by seppo498573908457** [bitnami/containers#70958]
### Name and Version

bitnami/redis-cluster:7.2.5

### What is the problem this feature will solve?

It's a common security best practice that the default administrator username is disabled. The ability to do so is explicitly stated in [Redis security documentation](https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/). This can be achieved in Redis cluster by creating new users into ACL and setting `masteruser` and `masterauth` configurations for replication. The ACL file can be created before-hand with another instance of redis-cluster.

However, there doesn't seem to be any way to set custom admin user name into bitnami redis-cluster creation. You have got the REDIS_PASSWORD environment variable, but that assumes default user for all operations.

If I disable the default user with ACL, cluster creation fails and docker log is filled with `AUTH failed: WRONGPASS invalid username-password pair or user is disabled.`.

I'm using bitnami/redis-cluster:7.2.5 on Docker. I switched to the 7.4.0 that was release a few days ago, but since it's source is not yet available in Github, I cannot tell if there are any new features regarding this.

### What is the feature you are proposing to solve the problem?

New environmental variables that can be configured through docker like the rest of them:

- "REDIS_USER". Default value "default".
- "REDIS_MASTER_USER". Default value inherits from "REDIS_USER".
- "REDIS_REQUIREPASS". Default value inherits from "REDIS_PASSWORD". This would be for backwards compatibility only, so if there is a cleaner approach, go for it.

And logic changes to scripts:

- All usages of this new variable should be paired with "--user" parameter in redis-cli.
- All existing "REDIS_PASSWORD" parameters should be paired with "--pass" parameter, instead of "-a" parameter, in redis-cli to indicate a change.
- If "REDIS_REQUIREPASS" is set, use it for current "--requirepass" parameters. If it's empty, don't set "--requirepass" and trust that the user has set redis.conf and ACL list accordingly.
- Use "REDIS_MASTER_USER" and "REDIS_MASTER_PASSWORD" (existing(?)) appropriately with "--masteruser" and "--masterauth" parameters. If the parameters are empty, they should have no effect and trust that user has set redis.conf and ACL list on all nodes accordingly. Right now there seems to be erronous usage in https://github.com/bitnami/containers/blob/main/bitnami/redis-cluster/7.2/debian-12/rootfs/opt/bitnami/scripts/redis-cluster/run.sh lines 28-31

### What alternatives have you considered?

There should be a possibility to pass arbitrary parameters into the start up commands. There currently is nothing to accomplish that with.

**Comment by andresbono** [comment]
Hi, thank you for opening this issue. Let me check first about the missing source code for 7.4.

**Comment by seppo498573908457** [comment]
I have made some scripts that comply with this request and I could share. But they are made from 7.2 sources, so I'd rather check against 7.4. Do you have the 7.4 source available?

**Comment by andresbono** [comment]
Thank you @seppo498573908457. We are looking into the issue right now. As soon as the folder for the 7.4 branch is made available, I will post a comment here.

**Comment by andresbono** [comment]
Please find the folder here: https://github.com/bitnami/containers/tree/main/bitnami/redis-cluster/7.4/debian-12

**Comment by seppo498573908457** [comment]
I have made some aforementioned changes to the scripts and tested them to some extent. I'm confused, can I create a PR to this repo?

**Comment by andresbono** [comment]
That's nice! Of course, you can create it! You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

**Comment by seppo498573908457** [comment]
Hi again.

I have created two PRs, for "redis" and "redis-cluster" images.

This is the first time I'm forking a public repo and submitting a PR to it like this, so please be patient if there are  some errors.

**Comment by seppo498573908457** [comment]
I had to recreate the PRs because they crooked an older commit message and caused conflicts. They should now be in a good shape for a review.

**Comment by andresbono** [comment]
Thank you so much for your contributions!! 🎉 The team will be checking the new PRs. Thank you again!

**Comment by andresbono** [comment]
Not stale, PRs under review
