### ISSUE TITLE
[bitnami/mysql] Shopware 6: Very slow migration.

### ISSUE THREAD

**Issue by anatol06** [bitnami/containers#70988]
### Name and Version

bitnami/mysql:8.0.37-debian-12-r2

Server OS: Ubuntu 20.04.6 LTS with Plesk Obsidian 18.0.62

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Migration from Shopware 5 to Shopware 6 using [Migration assistant extension ](https://store.shopware.com/en/swag257162657297f/migration-assistant.html)for Shopware 6 

### What is the expected behavior?

We are expecting migration taking about 4 hours, not 10 days

### What do you see instead?

It takes about 10 days

### Additional information

The problem is that the migration from Shopware 5 to Shopware 6 takes too long time. This ist he message from my coworker:

"When we switched the database from MariaDB to MySQL8 (to official MySQL containers with MySQL 8.0.36), the "customers and orders" migration took almost 4 hours. That means it can't be the server's fault. Nothing has changed there. The only thing we've changed is the MySQL versions (we switched to Bitnami containers with MySQL 8.0.37). Is that perhaps related to Bitnami? It could be that it's better for security reasons, but also slower?"

He also described the issue [here](https://forum.shopware.com/t/extrem-sw-migration-10-tage-und-mehr/104832):

What I observe is that during the migration, the database uses a significant amount of cached memory:

![image](https://github.com/user-attachments/assets/7b4b4105-9a2d-4f61-a476-70d0f3e9bbc9)

Could there be a connection between MySQL 8.0.37 running in non-root, secured containers from Bitnami and slow migration?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
