### ISSUE TITLE
[bitnami/keycloak] KEYCLOAK_ENABLE_HEALTH_ENDPOINTS environment variable rename

### ISSUE THREAD

**Issue by nix-power** [bitnami/containers#71077]
### Name and Version

bitnami/keycloak-25.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In official Krycloak documentation for 25.0.4 it appears that in order to enable healthcheck endpoints need to use
the following environment variable: KC_HEALTH_ENABLED: true

(https://www.keycloak.org/server/health)

The bitnami container still uses KEYCLOAK_ENABLE_HEALTH_ENDPOINTS variable which is confusing and hard to debug, while operating container in K8S using official bitnami helm chart

### What is the expected behavior?

when i use environment variable KC_HEALTH_ENABLED: true i supposed to view inside the configuration file keycloak.conf the following setting:

`health-enabled = true`

but i see it is equals to false. Only when i use  `KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true` i see the correct configuration reflected in the file

### What do you see instead?

`health-enabled = false`

**Comment by javsalgar** [comment]
Hi,

In other containers we allow aliases so both environment vars could be used. Would that work for your use case?

**Comment by nix-power** [comment]
Absolutely !

**Comment by gongomgra** [comment]
@nix-power if you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

**Comment by gongomgra** [comment]
We are working on adding the `KC_HEALTH_ENABLED` variable. We will keep you posted.

**Comment by gongomgra** [comment]
@nix-power starting with `bitnami/keycloak:25.0.5-debian-12-r1` we have included the `KC_HEALTH_ENABLED` alias for `KEYCLOAK_ENABLE_HEALTH_ENDPOINTS`. The rolling tags like `bitnami/keycloak:latest` have been also updated.

You can find more information on these changes in the next pull request: https://github.com/bitnami/containers/pull/72481

Hope it helps!
