### ISSUE TITLE
[NGINX] New image tagged 1.27.0 caused startup failure

### ISSUE THREAD

**Issue by tj-wd** [bitnami/containers#71175]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

Issue occurring in hosted EKS env

### Describe your issue as much as you can

We switched to bitnami/nginx 1.27.0 a couple weeks ago and everything was working great. We pull the image from the public AWS ECR.

Everything was working great until there was a new version pushed this morning with the same tag as what we were using: 1.27.0.

With this version on startup we are getting:
```
nginx: [emerg] mkdir() "/opt/bitnami/nginx/client_body_temp" failed (13: Permission denied)
```

Our k8s pods that run that container get stuck into a crash loop. Wondering two things:
- What might be causing this?
- Why was a new version published under the same tag as something that already existed?

**Comment by gongomgra** [comment]
Hi @tj-wd and @danielbarr3ra,

I have checked this with the engineering team and this issue seems to be located on our side. We are working on a fix for this.

**Comment by gongomgra** [comment]
Hi @tj-wd @danielbarr3ra,

We released a new revision of our NGINX container updating the `/opt/bitnami/nginx` default permission that should fix the reported issue:

```
$ docker-compose up -d && docker-compose logs -f
[+] Running 2/2
 ✔ nginx Pulled                                                                                                                                                                                                                                                                   20.6s
   ✔ 7018e03dc919 Pull complete                                                                                                                                                                                                                                                   15.2s
[+] Running 2/2
 ✔ Network nginx_default    Created                                                                                                                                                                                                                                                0.1s
 ✔ Container nginx-nginx-1  Started

$ docker-compose exec -it nginx bash
I have no name!@b2cf9c69738e:/app$ touch /opt/bitnami/nginx/test.txt

I have no name!@b2cf9c69738e:/app$ ls -larth /opt/bitnami/nginx
total 12K
drwxr-xr-x 1 root root   10 Aug 21 18:46 sbin
drwxr-xr-x 1 root root  232 Aug 21 18:46 modules
drwxr-xr-x 1 root root  314 Aug 21 18:46 licenses
-rw-r--r-- 1 root root 7.0K Aug 21 19:24 .spdx-nginx.spdx
drwxr-xr-x 1 root root   10 Aug 23 14:53 ..
drwxrwxr-x 1 root root   38 Aug 23 14:54 logs
lrwxrwxrwx 1 root root    4 Aug 23 14:54 html -> /app
drwxrwxr-x 1 root root  454 Aug 23 14:54 conf.default
drwxrwxr-x 1 root root   20 Aug 23 14:54 conf
drwxrwxr-x 1 root root   82 Aug 26 07:40 tmp
-rw-r--r-- 1 1001 root    0 Aug 26 07:41 test.txt
drwxrwxr-x 1 root root   30 Aug 26 07:41 .
```

You can get more details on the changes included in the new image from its associated pull request at https://github.com/bitnami/containers/pull/71178

Hope it helps!

**Comment by danielbarr3ra** [comment]
Checking :)

**Comment by fmulero** [comment]
Hi @danielbarr3ra, Have you found any issue? If everything is OK I will proceed to close the issue
