### ISSUE TITLE
[bitnami/kubectl] ecr bitnami/kubectl doesn't contains ARM64 image

### ISSUE THREAD

**Issue by guitarrapc** [bitnami/containers#71307]
### Name and Version

bitnami/kubectl:1.30

### What is the problem this feature will solve?

There are only x86-64 image but missing arm64 images. This indicate some OSS using bitnami/kubectl failed on ARM64 ec2.

### What is the feature you are proposing to solve the problem?

Inclde ARM64 as like https://hub.docker.com/layers/bitnami/kubectl/1.30/images/sha256-68a21ff34c2a67329faa4d6088272d54d4a4e7a21076b3a435624e45503a17ab?context=explore do.

### What alternatives have you considered?

Switch from ARM64 to AMD64 or other kubectl image registry like Docker Hub.

**Comment by guitarrapc** [comment]
Here's 1.30 looks like.

https://gallery.ecr.aws/bitnami/kubectl
![image](https://github.com/user-attachments/assets/72db6a55-f615-44ca-9210-bf48ca5981ba)

**Comment by beltran-rubo** [comment]
Thanks for your suggestion. Currently ARM64 architecture for Bitnami container images is only available into the DockerHub registry. 
The commercial version Tanzu Application Catalog https://tanzu.vmware.com/application-catalog provides support for delivering images into private registries like ECR and many others.

**Comment by guitarrapc** [comment]
Seems like, no plan to add ECR images at this stage?

**Comment by javsalgar** [comment]
I'm afraid there are no plans to include arm64 in ECR

**Comment by guitarrapc** [comment]
Thank you, let close issue.
