### ISSUE TITLE
[bitnami/kafka] linux run - error after terminate docker container problem

### ISSUE THREAD

**Issue by 3DPIT** [bitnami/containers#71311]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

If bitnami/kafka is suddenly turned off when running a Docker container, an error will occur if a duplicate topic is created when running again and the previous topic is raised first.

volumes mapping values             - ./shell/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

The strange thing is that when uploading from WSL's Linux or an actual Linux server if a duplicate topic is created, it dies when a kafka error occurs.

### What is the expected behavior?

When running Docker from a Windows folder, the container does not die even if the same error occurs. Could you explain the solution after determining the cause?

In the case of creating a topic of `docker-entrypoint-initdb.d`, I did multiple things, but if I turn it off in the middle while doing multiple things and then run it again, I hope that Kafka will not die even if an error occurs if there are duplicate topics while running `docker-entrypoint-initdb.d` from the beginning. Please solve it.

### What do you see instead?

error message
```
2024-08-26 08:37:06 Error while executing topic command : Topic 'queuing-amd-transfer' already exists.
2024-08-26 08:37:06 [2024-08-25 23:37:06,116] ERROR org.apache.kafka.common.errors.TopicExistsException: Topic 'queuing-amd-transfer' already exists.
2024-08-26 08:37:06  (kafka.admin.TopicCommand$)
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by OneCricketeer** [comment]
The broker shouldn't die. But you should add `if-not-exists` if you're using `kafka-topics.sh`
