### ISSUE TITLE
Bitnami - Redis - Docker / Plesk

### ISSUE THREAD

**Issue by othqsa95** [bitnami/containers#71312]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

I'm trying to create the container, with Plesk Panel, through Docker, using the docker image Bitnami/Redis

### What is the expected behavior?

Creating the container and running Redis through Docker, with Plesk.

### What do you see instead?
```
mkdir: cannot create directory '/bitnami/redis': Permission denied
```

**Comment by othqsa95** [comment]
![FB_IMG_1724639060305.jpg](https://github.com/user-attachments/assets/f556722f-4dfb-424c-9c51-e7109cd8f4e9)

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by othqsa95** [comment]
> Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.
> 
> For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
> 
> * [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
> * [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
> * [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
> * [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
> 
> These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

When I check the permission using the cmd : ls -ld /bitnami

I have this output: drwxr-xr-x 2 root root 4096 Jan 1 00:00 /bitnami

Do I need to change the permission with "sudo chown -R $USER:$USER /bitnami" ?

**Comment by carrodher** [comment]
Yes, that could work if both variables are properly defined
