### ISSUE TITLE
Failed to Site Replication from minio hosted in one cluster to other cluster due to unknown CA authority

### ISSUE THREAD

**Issue by shivgana** [bitnami/containers#71339]
### Name and Version

bitnami/minio:2024.7.4-debian-12-r0

### What steps will reproduce the bug?

We have installed minio in a cluster and exposed it to the internet, the same for replication installed in another cluster and exposed. Both minios are exposed with signed certificates. While the site replicating from one cluster minio to another cluster minio failed due to verifying the TLS certificate with an unknown CA.
Error:
```
API: SiteReplicationAdd
Time: 12:56:04 UTC 08/26/2024
DeploymentID: 626d42ce-d895-42e4-b7e9-91087d05906c
RequestID: 17EF488F821380A3
RemoteHost: 10.156.142.36
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0 MinIO Console/(dev)
Error: unable to fetch server info for replication: Get "https://minio.<company-fqdn>.se/minio/admin/v3/info?metrics=false": tls: failed to verify certificate: x509: certificate signed by unknown authority (cmd.SRError)
       4: internal/logger/logger.go:268:logger.LogIf()
       3: cmd/logging.go:46:cmd.adminLogIf()
       2: cmd/admin-handlers-site-replication.go:57:cmd.adminAPIHandlers.SiteReplicationAdd()
       1: net/http/server.go:2141:http.HandlerFunc.ServeHTTP()
```  

Didn't find any options to pass the CA for the second minio hosted?

### What do you see instead?

shared error in step to reproduce

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
