### ISSUE TITLE
[bitnami/rabbitmq] Allow setting load_definitions in rabbitmq.conf to a directory

### ISSUE THREAD

**Issue by hzpz** [bitnami/containers#71450]
### Name and Version

bitnami/rabbitmq:3.13.6

### What is the problem this feature will solve?

RabbitMQ supports loading multiple definition files from a directory, by setting `load_definitions` to a directory instead of a file. The Bitnami image allows setting  `load_definitions` via `RABBITMQ_DEFINITIONS_FILE`. Unfortunately, the startup script of the image validates, that `RABBITMQ_DEFINITIONS_FILE` points to a file instead of a directory (see [librabbitmq.sh](https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.13/debian-12/rootfs/opt/bitnami/scripts/librabbitmq.sh#L115)).

The only way I found to load definitions from a directory is to override the whole `rabbitmq.conf`. 

### What is the feature you are proposing to solve the problem?

Allow setting `load_definitions` to a directory, possibly by introducing another configuration variable like `RABBITMQ_DEFINITIONS_DIR`.

### What alternatives have you considered?

Overriding the whole `rabbitmq.conf` is a solution to this problem, but that way you also have to configure many settings "manually" that would normaly be configurable via configuration variables.

**Comment by javsalgar** [comment]
Hi! Thank you so much for the feature request! I will forward it to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and team will check it

**Comment by hzpz** [comment]
So, if I don't submit a PR, this issue will just be closed? 🤔

**Comment by javsalgar** [comment]
Removed the stale labl
