### ISSUE TITLE
[bitnami/matomo] Matomo initialisation fails to test database connection when there is # in the password

### ISSUE THREAD

**Issue by artm** [bitnami/containers#72352]
### Name and Version

bitnami/matomo:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

1. have a # in the database password
2. have matomo initialize
3. stop and remove the container, configuration is saved on the persistent volume
4. start the container, the configuration is read from the persistent volume
5. testing the database connection when "_Trying to connect to the database server_" is logged receive "_ERROR 1045 (28000): Access denied for user 'matomo'@'xxxxxxx' (using password: YES)_"

### What is the expected behavior?

matomo restarts

### What do you see instead?

"_Could not connect to the database_" in the log after several failed attempt

### Additional information

this happens because `ini-file get` [here][1] fails to read a password containing # (everying from # on is thrown away) 

[1]: https://github.com/bitnami/containers/blob/main/bitnami/matomo/5/debian-12/rootfs/opt/bitnami/scripts/libmatomo.sh#L231

**Comment by dgomezleon** [comment]
Hi @artm 

Thank you for bringing this issue to our attention

This is a particular scenario. Apart from avoiding that character, I can see 3 workarounds:
* Adapt [ini-file](https://github.com/bitnami/ini-file/) repo to support.
* Update the container logic to use a different approach to get the password (e.g. with `sed`)
* Validate the password at first boot to avoid those containing '#'

What do you think? If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team will review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

**Comment by artm** [comment]
Hi @dgomezleon 

We have indeed regenerated the password without # as a workaround.

I think fixing ini-file is the correct solution. I would like to give it a try.

**Comment by artm** [comment]
I had a look at the utility and think there is no need to fix it. `ini-file get` supports a flag `--ignore-inline-comments` which fixes the problem.

**Comment by artm** [comment]
On the other hand, treating # (or ;) inside a quoted string as a comment marker is still wrong, so I'm still considering how much effort it would be to fix.

**Comment by artm** [comment]
In fact, the problem was reported earlier and partially solved: https://github.com/bitnami/ini-file/issues/7
The # and ; aren't treated as comment markers between backticks, but not double or single quotes

**Comment by artm** [comment]
I was wrong, that issue is different, it is about output of ini-file set using backticks as string markers. 
But my next finding was correct: the reader treats backticked strings correctly, but not double/single quotes.

**Comment by dgomezleon** [comment]
Thanks for your implication here.

> I had a look at the utility and think there is no need to fix it. `ini-file get` supports a flag `--ignore-inline-comments` which fixes the problem.

I completely forgot that option. So to sum up a little bit. Would you consider adding the option for the container and create a separate issue/PR for `ini-file` repo if needed?

**Comment by artm** [comment]
sure!

I'm investigating the ini-file further, the actual ini file parsing is done by its dependency - https://github.com/go-ini/ini , I think the root cause is in that library, I'll go with my analysis. 

In the mean time I'll add a workaround with `--ignore-inline-comments` to the matomo container.

**Comment by dgomezleon** [comment]
Hi @artm ,

Find here our testing guides for [containers](https://github.com/bitnami/containers/blob/main/TESTING.md) and [charts](https://github.com/bitnami/charts/blob/main/TESTING.md). Note that our container testing is simpler than charts (something in our TODO list).
