### ISSUE TITLE
[bitnami/jupyter-base-notebook] Upgrade python version to python 3.12

### ISSUE THREAD

**Issue by Kumokage** [bitnami/containers#72362]
### Name and Version

bitnami/jupyter-base-notebook:5.1.0-debian-12-r3

### What is the problem this feature will solve?

Is there are any way to upgrade base python kernel from 3.10 to 3.12?

### What is the feature you are proposing to solve the problem?

Create some optional step that you can add yo your Docker container config to upgrade python version to required.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the only way to change the python version is via creating a fork. As it is using miniforge, the process is not trivial, as it would need to download all the required dependencies.
