### ISSUE TITLE
Unable access redis cluster data outside docker node

### ISSUE THREAD

**Issue by tigrankhojoyansporty** [bitnami/containers#72364]
### Name and Version

bitnami/redis-cluster:7.2

### What is the problem this feature will solve?

After running the container when I execute the redis command inside the parent machine cmd, the redis cli stuck on:
```
redis-cli -c -p 6379
127.0.0.1:6379> get a
-> Redirected to slot [15495] located at 172.28.0.2:6379
```
and exits with a timeout.

When I run the same command from any of pods, it works fine:
```
redis-cli -c 
127.0.0.1:6379> get a
-> Redirected to slot [15495] located at 172.28.0.2:6379
(nil)
172.28.0.2:6379> 
```
So, I'm unable to do any read/write operations outside of Redis pods. Is it expected behavior or not?

### What is the feature you are proposing to solve the problem?

Add(or fix) functionality to allow to read/write to Redis cluster outside container pods

### What alternatives have you considered?

Na alternatives :)

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
