### ISSUE TITLE
[bitnami/mongodb] can't use bitnami/mongo as root using azure container instance

### ISSUE THREAD

**Issue by paragikjain** [bitnami/containers#72401]
### Name and Version

bitnami/mongo

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using Azure Container Instances with the bitnami/mongo image. However, I am unsure how to log in as the root user. It seems that Azure Container Instances always log in with the container's default user, and in the case of the bitnami/mongo image, the default user is not root. Can you help me with this? I am using the following command:

az container exec --resource-group paragRG --name mongoshard --exec-command "/bin/bash"

### What is the expected behavior?

want to login as root user in azure container instance of image bitmapi/mongo

### What do you see instead?

Notn able to login as root user

**Comment by javsalgar** [comment]
Hi,

Our containers use non-root by default because of security reasons, could you explain the use case of using the container user `root`?
