### ISSUE TITLE
[bitnami/mongodb] can't use MONGODB_REPLICA_SET_MODE with value "dynamic"

### ISSUE THREAD

**Issue by guilherme-m-henriques-alb** [bitnami/containers#72516]
### Name and Version

bitnami/mongodb:7.0.14

### What is the problem this feature will solve?

I can see in the source code that `MONGODB_REPLICA_SET_MODE` can have the value dynamic, but it is not an accepted value. Is it possible to use this feature somehow? I would like to know if this is intended for future use or if there's a workaround to enable it.

### What is the feature you are proposing to solve the problem?

Document or support the dynamic value for `MONGODB_REPLICA_SET_MODE`, if it is meant to be functional. Alternatively, provide more clarity on its purpose and how users might utilize it.

**Comment by guilherme-m-henriques-alb** [comment]
This feature would be very helpful for deployments in kubernetes using a single statefulset for both primary + secondary members.

**Comment by carrodher** [comment]
You can set any supported value for that variable, please take a look at the [README](https://github.com/bitnami/containers/blob/main/bitnami/mongodb/README.md) where it is described and used in some examples
