### ISSUE TITLE
[bitnami/postgresql:11.6.0] Does not start and cannot access the container

### ISSUE THREAD

**Issue by riahc3** [bitnami/containers#72617]
### Name and Version

bitnami/postgresql:11.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Starting the container

### What do you see instead?

Error

### Additional information

I am trying to start my container with bitnami/postgresql:11.6.0 but I am seeing the logs (thru Rancher) the following message:
```
2024-09-19 09:52:28.151 GMT [169] LOG: database system was interrupted; last known up at 2024-09-17 13:54:43 GMT
2024-09-19 09:52:31.565 GMT [169] LOG: record with incorrect prev-link 200420/34000 at 3/832AE9F8
2024-09-19 09:52:31.565 GMT [169] LOG: invalid primary checkpoint record
2024-09-19 09:52:31.565 GMT [169] PANIC: could not locate a valid checkpoint record
2024-09-19 09:52:31.656 GMT [1] LOG: startup process (PID 169) was terminated by signal 6: Aborted
2024-09-19 09:52:31.656 GMT [1] LOG: aborting startup due to startup process failure
2024-09-19 09:52:31.659 GMT [1] LOG: database system is shut down
```
Even if I restore a backup from the 16th, this still happens.

I just want it to start back up... If there is data loss, so be it but right now the important part is to start it.

**Comment by wardahub-design** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by riahc3** [comment]
Could I get some feedback on what those links do, files, etc....More details

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by riahc3** [comment]
> The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.
> 
> If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
> 
> Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.
> 
> With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

Thank you for your reply.

I mostly wanted to know if it was a common seen issue, easy to reproduce, etc.
