### ISSUE TITLE
Cassandra 4.1 image, 'secret' config options paxos_variant, etc.

### ISSUE THREAD

**Issue by sergio-moreira-everi** [bitnami/containers#72632]
### Name and Version

bitnami/cassandra:4.1.X

### What is the problem this feature will solve?

There are certain config options that are not supplied in the standard cassandra yaml that would be good to have available for configuration.
Since 4.1 Cassandra notes a big improvement using paxos_variant v2, configurable via yaml and JMX. 

https://github.com/apache/cassandra/blob/trunk/NEWS.txt#L535

### What is the feature you are proposing to solve the problem?

We should have a way to either ship this config with the default cassandra yaml to be overwritten with a desired value, or maybe allow this to be enabled via an env var.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
