### ISSUE TITLE
[bitnami/postgresql] pgbench 

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#7264]
### Name and Version

bitnami/postgresql:14

### What steps will reproduce the bug?

1. Run container  `FROM bitnami/postgresql:14`
2. execute command : 
    - createdb pgbench  
    - pgbench  

### What is the expected behavior?

Run bench on postgresql

### What do you see instead?

error message user 1001

`could not look up effective user ID 1001: user does not exist ` 
`createdb: error: local user with ID 1001 does not exist `

**Comment by jotamartos** [comment]
Hi @siddjellali,

This is a PostgreSQL-related question and I can confirm there is nothing wrong in the solution. You need  to add the user to use to access the database 

```
createdb -U postgres pgbench
pgbench -i -U postgres pgbench
pgbench -U postgres pgbench
```

Please take a look at the documentation to know how to use the PostgreSQL's binaries and post a question in the PostgreSQL's community forums for the community to help you with any questions you may have. 

Thanks

**Comment by siddjellali** [comment]
Appreciate your support
