### ISSUE TITLE
The issue of "I have no name" being displayed inside a container

### ISSUE THREAD

**Issue by 642070630** [bitnami/containers#72644]
### Name and Version

bitnami/pgpool all 

### What architecture are you using?

None

### What steps will reproduce the bug?

When starting the container as root is not specified, "i have no name" is displayed when the user enters the container.

### What is the expected behavior?

Write user root in the build dockerfile, make the container start as root by default and enter the container to display the normal user name

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
