### ISSUE TITLE
ERROR: SCRAM authentication failed DETAIL: unable to decrypt password from pool_passwd HINT: verify the valid pool_key exists

### ISSUE THREAD

**Issue by 642070630** [bitnami/containers#72645]
### Name and Version

bitname/pgpool all

### What architecture are you using?

None

### What steps will reproduce the bug?

Start the container as root, run the scram-sha-256 authentication command, and connect to pgpool through `psql -h 127.0.0.1 -p 5432 -U postgres`

### What is the expected behavior?

When you run `psql -h 127.0.0.1 -p 5432 -U postgres` to connect to pgpool, the connection succeeds

### What do you see instead?

The following message is displayed when you run `psql -h 127.0.0.1 -p 5432 -U postgres` to connect to pgpool
```
 ERROR: SCRAM authentication failed DETAIL: unable to decrypt password from pool_passwd HINT: verify the valid pool_key exists
```
### Additional information

In the `pgpool_generate_password_file` function of libpgpool.sh, chmod 0600 "$PGPOOLKEYFILE" is used to set the permission for the key file to be too small. As a result, the key file cannot be read normally. If the authentication fails, you can set the permission of the KEY through "chmod 0644"

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
