### ISSUE TITLE
[bitnami/neo4j] Readiness and Liveness probe failed due to connection refused by pod

### ISSUE THREAD

**Issue by transformers4CD** [bitnami/containers#72712]
### Name and Version

registry-1.docker.io/bitnamicharts/neo4j:0.1.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

following these steps and corresponging error i am getting why?
[New Microsoft Word Document.docx](https://github.com/user-attachments/files/17129111/New.Microsoft.Word.Document.docx)

### What is the expected behavior?

pod should accept the connections for neo4j to run on localhost:7474

### What do you see instead?

Readiness probe failed: Get "$POD_IP:7474/": dial tcp $POD_IP:7474: connect: connection refused
Liveness probe failed: dial tcp $POD_IP:7687: connect: connection refused

### Additional information

same error comes for openshift deployment as well .

**Comment by javsalgar** [comment]
Hi!

Do the pods get to ready at some point?

**Comment by vg011895** [comment]
What was the resolution? I am facing the same issue.
