### ISSUE TITLE
[bitnami/schema-registry] Error while parsing `$schema` field in JSON schemas 

### ISSUE THREAD

**Issue by fzappia** [bitnami/containers#72723]
### Name and Version

bitnami/schema-registry:7.7.0-debian-12-r0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Start the docker container
2. Run the following request against the schema registry
```bash
curl -X POST -H 'Content-Type: application/vnd.schemaregistry.v1+json' --data '{"schemaType": "JSON", "schema": "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"title\":\"Product\",\"description\":\"A product from Acme'\''s catalog\",\"type\":\"object\",\"properties\":{\"productId\":{\"description\":\"The unique identifier for a product\",\"type\":\"integer\"}}}"}' --fail-with-body --silent --show-error http://localhost:8081/subjects/product/versions
```

### What is the expected behavior?

The request succeeds and the schema is registered.

### What do you see instead?

```
{"error_code":42201,"message":"Invalid schema {subject=product,version=0,id=-1,schemaType=JSON,references=[],metadata=null,ruleSet=null,schema={\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"title\":\"Product\",\"description\":\"A product from Acme's catalog\",\"type\":\"object\",\"properties\":{\"productId\":{\"description\":\"The unique identifier for a product\",\"type\":\"integer\"}}},schemaTags=null}, details: Invalid JSON Schema"}%                                               
```

### Additional information

- The issue cannot be reproduced on the `confluentinc/cp-schema-registry:7.7.0` or other tags.
- The issue cannot be reproduced on the `bitnami/schema-registry:7.6.1-debian-12-r6`

**Comment by fzappia** [comment]
@jotamartos Updates on this?

**Comment by jotamartos** [comment]
Hi @fzappia,

Sorry for the late reply here. I've been checking this issue and it seems that the error is related to the application, not to the Bitnami configuration. For some reason, it's returning an "Invalid JSON Schema" error message.

However, the API works when executing other commands like this one posted in its documentation

https://docs.confluent.io/platform/current/schema-registry/develop/using.html#common-sr-api-usage-examples

```
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" --data '{"schema": "{\"type\": \"string\"}"}' http://localhost:8081/subjects/Kafka-key/versions
```

**Comment by fzappia** [comment]
Hey @jotamartos I still could not reproduce the issue using the official [confluent/cp-schema-registry:7.7.0](https://hub.docker.com/r/confluentinc/cp-schema-registry) container

**Comment by jotamartos** [comment]
Hi @fzappia,

Is the request you are making documented somewhere? As I mentioned above, I copied the example of the documentation and the request worked as expected. In the case of your request, I do not know if they are making any extra change you need to the base configuration that we can apply to our solution. If that's the case, please follow [our contributing guidelines](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) so the whole community can benefit from it.
