### ISSUE TITLE
[bitnami/opensearch] Incorrect description for `OPENSEARCH_FS_SNAPSHOT_REPO_PATH`

### ISSUE THREAD

**Issue by lindhe** [bitnami/containers#72752]
### Name and Version

bitnami/opensearch

### What architecture are you using?

None

### What steps will reproduce the bug?

There's a typo here: https://github.com/bitnami/containers/blob/9f11aeb3ce86b29e491f309e7bee7d318bbf2059/bitnami/opensearch/README.md?plain=1#L201

### What do you see instead?

It seems to be a copy-paste error from `OPENSEARCH_TRANSPORT_PORT_NUMBER`.

### Additional information

I think it is important to describe if it's a list, like [`path.repo`](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#shared-file-system), or just a single path. If it is a list, please give examples of how items are separated.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by dgomezleon** [comment]
Hi @lindhe 

I have updated the description for this variable for ES and Opensearch. A new release has been triggered and should be released soon. Regards
