### ISSUE TITLE
[bitnami/redis-cluster] Redis cluster update IPs

### ISSUE THREAD

**Issue by skyckp123** [bitnami/containers#72796]
### Name and Version

bitnami/redis-cluser:7.4

### What is the problem this feature will solve?

During the bootstrap., why are we updating the redis node IPs in the nodes.conf file instead of issuing redis-cli cluster meet command?

whats the advantage we are gaining over redis-cli cluster meet command?

https://github.com/bitnami/containers/blob/main/bitnami/redis-cluster/7.4/debian-12/rootfs/opt/bitnami/scripts/librediscluster.sh#L205

### What is the feature you are proposing to solve the problem?

Use redis-cli cluster meet instead of update IPs.

**Comment by javsalgar** [comment]
Hi,

This was because the command was causing issues in Kubernetes installations, where the IPs are ephemeral and we needed to update them this way.
