### ISSUE TITLE
[bitnami/jasperreports] Sending emails using Office365

### ISSUE THREAD

**Issue by theoneno1** [bitnami/containers#7296]
### Name and Version

Jasper Reports 8.1.0

### What steps will reproduce the bug?

I am trying to configure Bitnami JasperReports image with Office365 email address for sending reports and scheduling them.
This link [https://community.jaspersoft.com/wiki/use-office-365-smtp-jasperreports-server](https://community.jaspersoft.com/wiki/use-office-365-smtp-jasperreports-server) describes that changes are required on (3) files: 
js.quartz.properties
applicationContext.xml
applicationContext-report-scheduling.xml

Changing the environment variables as described here [https://hub.docker.com/r/bitnami/jasperreports](https://hub.docker.com/r/bitnami/jasperreports) does not take into consideration those values:
```
mail.smtp.auth=true
mail.smtp.starttls.enable=true
```
I have tried to set the `JASPERREPORTS_SMTP_PROTOCOL` environment variable with the value "ssl" but still the `mail.smtp.auth=false` and `mail.smtp.starttls.enable` are not added to the javaMail bean in `applicationContext.xml`
and `applicationContext-report-scheduling.xml`

This issue says it will be automatically set, but I couldn't find that code and I'm not sure if takes affect: 

[https://github.com/bitnami/bitnami-docker-jasperreports/issues/81](https://github.com/bitnami/bitnami-docker-jasperreports/issues/81)

Would you please provide more information on how to set `mail.smtp.auth=true` and `mail.smtp.starttls.enable=true` values?

Thank you for the great support.

### What is the expected behavior?

Should be able to send emails using Office365.

### What do you see instead?

The value of `mail.smtp.auth` is still false.
`mail.smtp.starttls.enable` is not added to the context xml files.

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by grantemsley** [comment]
This was also reported in https://github.com/bitnami/containers/issues/4677 which was closed for becoming stale. And is fixed in my PR #7190 which still needs approval.

**Comment by javsalgar** [comment]
Thank you for the PR! The team will take a look
