### ISSUE TITLE
Restart error issue with Discourse

### ISSUE THREAD

**Issue by FrostScent** [bitnami/containers#72976]
### Name and Version

bitnami/discourse:3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are running bitnami/discourse:3 on Docker Swarm (which is similar to Docker Compose). After several unexpected restarts due to a cluster issue, the service is not starting up again.

### What is the expected behavior?

The Discourse page should be accessible normally.

### What do you see instead?

The discourse page shows the following page.

![image](https://github.com/user-attachments/assets/31d0adba-0884-40a9-a47b-7e890c89f867)

The discourse container shows the following logs.

![image](https://github.com/user-attachments/assets/392d9e97-3140-429d-934e-dc82d7ad7b80)

The Sidekiq container shows the following logs and then shuts down.

![image](https://github.com/user-attachments/assets/1a0f18c9-fe58-48ae-af9e-a68d055140cd)

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
