### ISSUE TITLE
[bitnami/kubernetes-event-exporter] Changing app maintainer

### ISSUE THREAD

**Issue by dev-dsp** [bitnami/containers#72975]
### Name and Version

kubernetes-event-exporter

### What is the problem this feature will solve?

Unmaintained project

### What is the feature you are proposing to solve the problem?

Change source to a new repository

### What alternatives have you considered?

Contacted resmo.io / jumpcloud.com with no response from them

**Comment by dev-dsp** [comment]
I've forked the source repository and going to maintain the app. What are the requirements / processes for changing the source for container images?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for contributing! We would expect the project to have:

  - An open source license
  - An official redirection from the unmaintained project
