### ISSUE TITLE
Incorrect PGOOL_PORT_NUMBER used for PostgreSQL node connection in PgPool

### ISSUE THREAD

**Issue by AlexShander** [bitnami/containers#72979]
### Name and Version

bitnami/pgpool:4.5.4

### What architecture are you using?

None

### What steps will reproduce the bug?

There is an issue with the `PGPOOL_PORT_NUMBER` variable in the bitnami/pgpool:4.5.4 container image, where the wrong port is used for connecting to a PostgreSQL node. Instead of connecting to the correct port of a node, the PgPool script incorrectly attempts to connect to the port of PgPool itself.

https://github.com/bitnami/containers/blob/7f4dbf453c2a132f3b14e4edaf9402efbb47a3e8/bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh#L319

### What is the expected behavior?

healthcheck.sh is connecting to the wrong port, leading to incorrect behaviour when interacting with PostgreSQL nodes.

### What do you see instead?

Connect to wrong port.

### Additional information

Suggested Fix
In the file libpgpool.sh, line 319, the following change is recommended:
```bash
local node_port="${node_info[2]}"

            if [[ $(PGCONNECT_TIMEOUT=3 PGPASSWORD="${PGPOOL_POSTGRES_PASSWORD}" psql -U "${PGPOOL_POSTGRES_USERNAME}" \
                -d postgres -h "${node_host}" -p "${node_port}" -tA -c "SELECT 1" || true) == 1 ]]; then
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
