### ISSUE TITLE
Configure an environment variable for `mongodb` that can enable remote access?

### ISSUE THREAD

**Issue by sanbei101** [bitnami/containers#73000]
### Name and Version

bitnami/mongodb@latest

### What is the problem this feature will solve?

I want to enable **remote access** to `Mongodb`, but there is no environment variable to enable this in the documentation. As far as I know, `bitnami/postgresql` has this option. Why doesn’t `Mongodb`?

### What is the feature you are proposing to solve the problem?

enable **remote access** to `Mongodb`

### What alternatives have you considered?

Enter the container to edit conf, but this is not very convenient.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by sanbei101** [comment]
ok,thanks
