### ISSUE TITLE
[bitnami/mongodb:7.0-debian-12] image fails to start

### ISSUE THREAD

**Issue by cyber-conor** [bitnami/containers#73076]
### Name and Version

bitnami/mongodb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker run bitnami/mongodb:latest` or `docker run bitnami/mongodb:7.0-debian-12` 

### What is the expected behavior?

The image should start mongodb without issue. Example working output: 
```
mongodb 14:46:14.28 INFO  ==>
mongodb 14:46:14.28 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 14:46:14.28 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 14:46:14.29 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 14:46:14.29 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
mongodb 14:46:14.29 INFO  ==>
mongodb 14:46:14.30 INFO  ==> ** Starting MongoDB setup **
mongodb 14:46:14.32 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 14:46:14.79 INFO  ==> Initializing MongoDB...
mongodb 14:46:14.87 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.17.0.2:27017
mongodb 14:46:16.72 INFO  ==> Creating users...
mongodb 14:46:16.72 INFO  ==> Users created
mongodb 14:46:16.75 INFO  ==> Stopping MongoDB...
mongodb 14:46:17.79 INFO  ==> ** MongoDB setup finished! **

mongodb 14:46:17.82 INFO  ==> ** Starting MongoDB **
{"t":{"$date":"2024-10-04T14:46:17.856Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"main","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":true}}}}
...
```

### What do you see instead?

The image fails to start and exits almost immediately without error. It stops at the "Deploying MongoDB from scratch..."

Example output: 
```
mongodb 14:49:08.84 INFO  ==>
mongodb 14:49:08.84 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 14:49:08.85 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 14:49:08.85 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 14:49:08.85 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
mongodb 14:49:08.85 INFO  ==>
mongodb 14:49:08.86 INFO  ==> ** Starting MongoDB setup **
mongodb 14:49:08.88 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 14:49:09.33 INFO  ==> Initializing MongoDB...
mongodb 14:49:09.39 INFO  ==> Deploying MongoDB from scratch...
```

### Additional information

This only seems to be occurring from an image that was released a few hours ago ((index digest `sha256:0d75f5051bba1ee02d47bef37cb0e38380b2815d9efaa4fb20cde789137deb3a`). 

I've been able to reproduce this issue across several boxes.

**Comment by vawaver** [comment]
I have similar problem.

```
mongodb 19:22:23.95 INFO  ==> Welcome to the Bitnami mongodb container

mongodb 19:22:23.95 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers

mongodb 19:22:23.95 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues

mongodb 19:22:23.95 INFO  ==> 

mongodb 19:22:23.96 INFO  ==> ** Starting MongoDB setup **

mongodb 19:22:23.97 INFO  ==> Validating settings in MONGODB_* env vars...

mongodb 19:22:24.10 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.

mongodb 19:22:24.11 INFO  ==> Initializing MongoDB...

mongodb 19:22:24.26 INFO  ==> Deploying MongoDB from scratch...

/opt/bitnami/scripts/libos.sh: line 346:    47 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
```

**Comment by raphielscape** [comment]
It seems like the issue https://github.com/bitnami/containers/issues/50109 has resurfaced in the latest image?

```
Unrecognized option: storage.journal.enabled
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

**Comment by arajczy** [comment]
same here

**Comment by eviltik** [comment]
same here

**Comment by eviltik** [comment]
Perhaps somewhere here  ?

https://github.com/bitnami/containers/blob/697e9c1a336ba438d20f78165c5f3579cdd32af1/bitnami/mongodb/8.0/debian-12/rootfs/opt/bitnami/scripts/libmongodb.sh#L491

**Comment by gongomgra** [comment]
Hi all,

Thank you for reporting these issues. We are working on a fix for it and we will post a new message once a new image is published. Sorry for the inconveniences

**Comment by gongomgra** [comment]
We have released a new image solving the initialization issues listed above. You can find more details on the implemented changes at https://github.com/bitnami/containers/pull/73130

Let us know if you find any other issues.

**Comment by vawaver** [comment]
@gongomgra Greetings,
I would like to ask you to fix MongoDB 5.0 latest as well. I use this image together with Rocket.chat. 
I am not IT pro and that is why I use the recommended `docker-compose.yml` file from the URL - https://github.com/RocketChat/Docker.Official.Image/blob/master/compose.yml
So I suppose that my problem is related to MongoDB 5.0 latest.

```
mongodb 13:58:22.10 INFO  ==> 

mongodb 13:58:22.10 INFO  ==> Welcome to the Bitnami mongodb container

mongodb 13:58:22.10 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers

mongodb 13:58:22.10 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues

mongodb 13:58:22.10 INFO  ==> 

mongodb 13:58:22.11 INFO  ==> ** Starting MongoDB setup **

mongodb 13:58:22.12 INFO  ==> Validating settings in MONGODB_* env vars...

mongodb 13:58:22.24 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.

mongodb 13:58:22.26 INFO  ==> Initializing MongoDB...

mongodb 13:58:22.40 INFO  ==> Deploying MongoDB from scratch...

/opt/bitnami/scripts/libos.sh: line 346:    47 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
```

**Comment by matiasbertani** [comment]
@vawaver 

I think what you are asking is totally out of scope of this issue and make noise. I would suggest you to open a different issue for your problem.

**Comment by eviltik** [comment]
@gongomgra thank you for reactivity !!

There is another problem, but not related to the bitnami image.

I followed every upgrades since v6 (v6 => v7 => now v8).

The docker restart (infinite loop).

The error in docker logs:

```
  "error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"6.0\" }. See https://docs.mongodb.com/master/release-notes/7.0-compatibility/#feature-compatibility. :: caused by :: Invalid feature compatibility version value '6.0'; expected '7.0' or '7.3' or '8.0'. 
  
  See https://docs.mongodb.com/master/release-notes/7.0-compatibility/#feature-compatibility.). 
  
  If the current featureCompatibilityVersion is below 7.0, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/7.0/#upgrade-procedures."}}
```

It seem's that we have to make some things related to the migration, related to featureCompatibilityVersion attribute value mongodb side.

Just some hints here:

* first go back to v7
* db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 });
=> change value to ???
* reinstall docker to v8.

My question is : does this change may/should/must be handled by a scripts provided by bitnami or users (me) should handle it ?

Btw: thanks for all bitnami teams for this repo !

**Comment by eviltik** [comment]
@cyber-conor hi, should be great if you can add mongodb version in the title of this ticket rather than "latest", ty ;)

**Comment by cyber-conor** [comment]
> @cyber-conor hi, should be great if you can add mongodb version in the title of this ticket rather than "latest", ty ;)

Done!

**Comment by eviltik** [comment]
History: 
* v6 to v7 migration does not require featureCompatibilityVersion changes.
* v7 to v8 does

How to proceed ?
* if you try v8 without success (see error message in https://github.com/bitnami/containers/issues/73076#issuecomment-2397452926 ), revert back to v7
* enter the docker `docker exec -it mongodb /bin/bash`
* open a mongo shell as root  `I have no name!@sysdio_mongodb:/$ mongosh -u root -p **********`
* select admin collection ` use admin;`
* dump featureCompatibilityVersion value `db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 });`
```
{
  featureCompatibilityVersion: { version: '6.0' },
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1728321482, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('jNObVftxpWh4piK/KpZLMZ5OSQI=', 0),
      keyId: Long('7357620887509532674')
    }
  },
  operationTime: Timestamp({ t: 1728321482, i: 1 })
}
```
* switch to 7.0 `db.adminCommand({ setFeatureCompatibilityVersion: "7.0" });`
```
MongoServerError[Location7369100]: Once you have upgraded to 7.0, you will not be able to downgrade FCV and binary version without support assistance. Please re-run this command with 'confirm: true' to acknowledge this and continue with the FCV upgrade.
```
* as you can see, force confirm attribute `replicaset [direct: primary] admin> db.adminCommand({ setFeatureCompatibilityVersion: "7.0", confirm:true });`
```
{
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1728321924, i: 3 }),
    signature: {
      hash: Binary.createFromBase64('sR+vf/2NGf5c57czCFB4RDbReV0=', 0),
      keyId: Long('7357620887509532674')
    }
  },
  operationTime: Timestamp({ t: 1728321924, i: 3 })
}
```
* exit mongosh
* exit docker
* restart v7 docker, check logs if everything is fine
* update your Dockerfile to use v8 `FROM bitnami/mongodb:8.0`
* stop + rm + system prune docker
* install bitnami mongodb v8
* check if everything is fine (ok on my side)

**Comment by cyber-conor** [comment]
The new latest image (`8.0-debian-12`) works for me now. Thanks for your help everyone!

**Comment by gongomgra** [comment]
Hi @eviltik,

Thanks for your message and for sharing your solution. As explained in the [MongoDB official docs](https://www.mongodb.com/docs/manual/release-notes/8.0/#upgrade-procedures), the upgrade procedure depends on your current deployment type and it requires different steps depending on your custom scenario. Thank you for sharing your solution, I'm sure it will be of help to other users in the future!

@cyber-conor can we consider the ticket is solved?

**Comment by cyber-conor** [comment]
@gongomgra solved! Thanks :)
