### ISSUE TITLE
Add a straightforward documented way to access dockerised redmine via HTTPS

### ISSUE THREAD

**Issue by jms19** [bitnami/containers#73136]
### Name and Version

redmine:5.1.2

### What is the problem this feature will solve?

Allow HTTPS access without re-building the container image

### What is the feature you are proposing to solve the problem?

Make it easy to run a container and point to certificates and key for HTTPS.

In the past we have used binary packages for Redmine but these are gone in favour of containers and VMs.

Looking at https://github.com/bitnami/containers/tree/main/bitnami/redmine#how-to-use-this-image the only mention of SSL is for SMTP.

### What alternatives have you considered?

Various people have workarounds but these don't co-exist with the idea of containers which should just work.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
