### ISSUE TITLE
[bitnami/keycloak] Upgrade to 26.0.0

### ISSUE THREAD

**Issue by tanadeau** [bitnami/containers#73138]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Latest features and fixes from Keycloak

### What is the feature you are proposing to solve the problem?

Image using the latest version of Keycloak

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, major versions require manual intervention.

Our team is actively working on it at the moment. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by tanadeau** [comment]
@carrodher: it looks like an image tag and a chart version for 26.0.0 is out as of 10/8 (yesterday). Can this be closed?

**Comment by carrodher** [comment]
Yes, the new image and Helm chart was released, we can close this ticket
