### ISSUE TITLE
MongoDB 5.0 Fails to Start with Rocket.Chat Installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by vawaver** [bitnami/containers#73143]
### Name and Version

/bitnami/mongodb

### What architecture are you using?

amd64

### **Issue Report: MongoDB 5.0 Fails to Start with Rocket.Chat Installation on Ubuntu 22.04**

Greetings,

I would like to report an issue with the latest MongoDB 5.0 image from Bitnami, which fails to start when used with Rocket.Chat. I am using the following setup:

- **Docker version**: 27.3.1 (build ce12230)
- **OS**: Ubuntu Server 24.04
- **MongoDB version**: 5.0 (bitnami/mongodb:5.0)
- **Rocket.Chat setup**: Using the official `docker-compose.yml` from Rocket.Chat's repository ([compose.yml link](https://github.com/RocketChat/Docker.Official.Image/blob/master/compose.yml))

Since I am using the recommended `docker-compose.yml`, I assume this issue is related specifically to MongoDB 5.0.

#### **Logs**:

```
mongodb 13:58:22.10 INFO  ==> 
mongodb 13:58:22.10 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 13:58:22.10 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 13:58:22.10 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 13:58:22.10 INFO  ==> 
mongodb 13:58:22.11 INFO  ==> ** Starting MongoDB setup **
mongodb 13:58:22.12 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 13:58:22.24 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 13:58:22.26 INFO  ==> Initializing MongoDB...
mongodb 13:58:22.40 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 346:    47 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
```

#### **Description**:
MongoDB fails to initialize, showing an "Illegal instruction (core dumped)" error during setup. The environment variable `ALLOW_EMPTY_PASSWORD=yes` is used, though this should not affect the initialization phase. This issue might be architecture-related or linked to compatibility with Rocket.Chat or Docker itself.

I would appreciate any guidance or fixes you can provide for resolving this issue. Let me know if further details or configurations are required.

### What is the expected behavior?

Rocket.chat start with MongoDB

### What do you see instead?

All info is above

**Comment by carrodher** [comment]
Are you deploying it in an ARM architecture? If that's the case, please note Bitnami MongoDB doesn't support ARM

**Comment by vawaver** [comment]
@carrodher My Ubuntu server is running on x86_64.

**Comment by carrodher** [comment]
I'm able to reproduce the issue in an ARM machine but not in AMD, which is the expected behavior given the lack of ARM images in MongoDB

**Comment by vawaver** [comment]
I already fix my issue.
I changed the CPU setting of my Proxmox VM (where is Ubuntu installed) to `host`.
This fixed my problem.
