### ISSUE TITLE
Ghost wont start, Hostname mysql and Ghost directory issues

### ISSUE THREAD

**Issue by hurley-code** [bitnami/containers#73146]
### Name and Version

bitnami/ghost

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In Unraid v6.12.4 
2. mariadb container already in use, container hostname is mariadb
3. setup a database for ghost with a user and a password
4. Set the environment variables correctly in the Ghost template
5. deploy 

### What is the expected behavior?

The docker container installs and starts up.

### What do you see instead?

The container will not start. Container log shows:
```
ghost 17:49:31.76 INFO  ==> Configuring libnss_wrapper
ghost 17:49:31.78 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 17:49:31.81 WARN  ==> Hostname mysql could not be resolved, this could lead to connection issues
ghost 17:49:31.81 INFO  ==> Ensuring Ghost directories exist
mkdir: cannot create directory '/bitnami/ghost': Permission denied
```

**Comment by hurley-code** [comment]
Oh and yes, they are both on the same proxy docker network

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
