### ISSUE TITLE
[bitnami/nginx-ingress-controller] Error Loading libabsl_synchronization.so.2206.0.0 when Enabling OpenTelemetry in Bitnami NGINX Ingress Controller

### ISSUE THREAD

**Issue by kobin23** [bitnami/containers#73142]
### Name and Version

bitnami/nginx-ingress-controller:1.11.2-debian-12-r5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable OpenTelemetry in the Helm Chart by specifying enable-opentelemetry: "true" in config section of values file.
2. Deploy the Bitnami NGINX Ingress Controller Helm Chart on a Kubernetes cluster.
3. Observe the error in the controller logs.

### What is the expected behavior?

Ingress controller should enable OpenTelemetry module

### What do you see instead?
```
Error: exit status 1
2024/10/07 17:09:53 [emerg] 1609#1609: dlopen() "/etc/nginx/modules/otel_ngx_module.so" failed (libabsl_synchronization.so.2206.0.0: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfg759397434:7
nginx: [emerg] dlopen() "/etc/nginx/modules/otel_ngx_module.so" failed (libabsl_synchronization.so.2206.0.0: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfg759397434:7
nginx: configuration file /tmp/nginx/nginx-cfg759397434 test failed
```

**Comment by migruiz4** [comment]
Thank you for reporting this issue @kobin23

We have detected an issue with the `/etc/nginx/modules/otel_ngx_module.so` linked dependencies and we are currently working on a fix.

```
I have no name!@nginx-ingress-controller-7cc6c57448-2ch4l:/etc/nginx$ ldd modules/otel_ngx_module.so 
...
        libabsl_synchronization.so.2206.0.0 => not found
...
```

**Comment by kobin23** [comment]
Hi @migruiz4!

Are there any updates on this issue?

**Comment by GEEugene** [comment]
Got the same issue. Waiting for fixes. It's very important.

**Comment by migruiz4** [comment]
Hi @GEEugene,

I'm sorry for the late response.  We updated the `bitnami/nginx-ingress-controller` image two weeks ago including a fix for this issue. Could you please confirm that your are using the image tag `1.11.3-debian-12-r2`?

```
$ docker run --rm -it --entrypoint bash bitnami/nginx-ingress-controller:1.11.3-debian-12-r2 ldd modules/otel_ngx_module.so
 ...
        libabsl_synchronization.so.20220623 => /lib/x86_64-linux-gnu/libabsl_synchronization.so.20220623 (0x00007f87d4252000)
 ...
```

I have noticed that we didn't release a new version of the chart, so I'm forcing it right now.

**Comment by kobin23** [comment]
Hi @migruiz4 

It's working now on Chart version 11.5.3
Thank you!
