### ISSUE TITLE
[bitnami/moodle] couldnt connect to sql [existing database]

### ISSUE THREAD

**Issue by bhanuprakashbahoju** [bitnami/containers#73151]
### Name and Version

bitnami/moodle:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using an Azure Flexible mysql server,
When the database is new and installing a fresh moodle works fine.
But when I restarted the container, it won't connect to the database,
I have persisted the Moodle data

I have checked the mysql server logs 
```
================LOGS=============
Access denied for user '0be4d'@'20.76.X.X' (using password: YES)
==================================
```
I don't why it's trying to connect with user 0be4d, I have never mentioned it in the compose file, and I even checked config.php, credentials are valid with what I was given in the compose file.

### What do you see instead?

Should reconnect to the database server without any error.

**Comment by bhanuprakashbahoju** [comment]
Hello<  Me again, I think I found the problem.

When database table name a hyphen(-) in it, its behaving like this.

As per MySQL Documentation when there are any special characters, the database name should be enclose in back tick's (``).

I guess the php JDBC driver is not handling that correctly (Just a guess, Not Sure)

**Comment by javsalgar** [comment]
Hi!

Did adding backticks in the env var fix the issue?
