### ISSUE TITLE
[suitecrm]: tag `8.7.0` does not appear to include `8.7.0` sources ... ?

### ISSUE THREAD

**Issue by JoshMcCullough** [bitnami/containers#73179]
### Name and Version

bitnami/suitecrm:8.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run the container and `exec` into it.
2. `cat /bitnami/suitecrm/public/legacy/suitecrm_version.php` --> shows version `8.6.0`
3. `env | grep 8.` --> shows `8.7.0`

Update: the file at `/opt/bitnami/suitecrm/public/legacy/suitecrm_version.php` **does** include the correct version.

### What is the expected behavior?

Version information should match that of the release. Unclear if the `8.7.0` tag is actually `8.7.0` or `8.6.0`.

### What do you see instead?

Version information shows both versions.

**Comment by JoshMcCullough** [comment]
Our host dir `/data/docker/volumes/suitecrm_data/_data` is mapped to the container dir `/bitnami/suitecrm`. This dir is the one that appears to contain the 8.6.0 sources. On the container itself (when running without the volume), the current/correct sources are within `/opt/bitnami/suitecrm`.


On our running instance, `/opt/bitnami/suitecrm` is a symlink to `/bitnami/suitecrm` (the mapped volume).

Could this be caused by the persistence feature of this image?

**Comment by migruiz4** [comment]
Hi @JoshMcCullough,

As you mentioned, the entire `/opt/bitnami/suitecrm` is a symlink to `/bitnami/suitecrm`, so it is expected behavior.

To upgrade your deployment, I would recommend taking a look at this section of the README.md: https://github.com/bitnami/containers/tree/main/bitnami/suitecrm#upgrade-this-image

**Comment by JoshMcCullough** [comment]
Thanks.
