### ISSUE TITLE
[bitnami/wordpress-nginx] Can't customize nginx.conf - directive is not allowed here in /opt/bitnami/nginx/conf/nginx.conf

### ISSUE THREAD

**Issue by andersonbosa** [bitnami/containers#73205]
### Name and Version

bitnami/wordpress-nginx:6.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Copy the `/opt/bitnami/nginx/conf/nginx.conf` from the container to host machine as if you want to customize it (but don't anything!).
2. Paste the same nginx.conf that you copied earlier, from the host machine to the container at `/opt/bitnami/nginx/conf/nginx.conf`.
    - Bug happens when using volumes in `docker-compose.yml` (you can also try change file permissions)
    ![image](https://github.com/user-attachments/assets/8826104c-1dca-4707-911d-9301ddfe2a69)
    - ALSO happens when using `COPY` in Dockerfile 
    ![image](https://github.com/user-attachments/assets/57ae86c8-8b9a-4b60-b7f9-71fb875fb62e)

### What is the expected behavior?

NGINX is expected to work normally, as the configuration is the same.

![image](https://github.com/user-attachments/assets/a822ae33-4cb3-43a6-b430-f9fe6a3ed9d5)

### What do you see instead?

What happens is that NGINX doesn't start as expected and the error is: 
```
nginx: [emerg] "worker_processes" directive is not allowed here in /opt/bitnami/nginx/conf/nginx.conf:4
```

![image](https://github.com/user-attachments/assets/ef50947a-9397-4a39-b81a-f26f9d979061)

### Additional information

Documentations I reviewed:
- https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx#customize-this-image
- https://github.com/bitnami/containers/tree/main/bitnami/nginx#full-configuration

Another problem I have while using `bitnami/wordpress-nginx`: I'm trying to get it to be served on `localhost:8072/blog/`, but everything I've tried I haven't been successful at. I would really appreciate it if you could help me with this second problem as well.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by andersonbosa** [comment]
Adding further info for future users:

I think I did found a new "how to reproduce"... When using Dockerfile and we use `COPY ../somefile.sh /docker-entrypoint-initdb.d/somefile.sh` the Nginx trigger the following error.

![image](https://github.com/user-attachments/assets/25a15442-7faa-44e3-97c9-eace377d75f1)
