### ISSUE TITLE
Arm64 architecture Ubuntu system cannot pull Bitnami/MongoDB image

### ISSUE THREAD

**Issue by linwanlong** [bitnami/containers#73224]
### Name and Version

bitnami/mongodb:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Arm64 architecture Ubuntu cannot pull MongoDB images

### What is the expected behavior?

Why is only the AMD64 architecture image provided? Can you tell me how to quickly use Bitnami's MongoDB image

### What do you see instead?

The Docker Harbor repository only contains MongoDB images with AMD64 architecture, not those with Arm64 architecture

### Additional information

I hope to quickly supplement the image of arm64 architecture

**Comment by carrodher** [comment]
ARM is not officially supported upstream. The latest version of MongoDB does not yet support ARM for Debian 12, see https://www.mongodb.com/try/download/community. ARM is only supported on Ubuntu and MacOS.

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 5, Ubuntu 22.04 & 24.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

Closing this issue as duplicated of https://github.com/bitnami/containers/issues/40947
