### ISSUE TITLE
[postgresql-repmgr] Add support for PostgreSQL 17

### ISSUE THREAD

**Issue by mfvanek** [bitnami/containers#73230]
### Name and Version

postgresql-repmgr:16

### What is the problem this feature will solve?

Allow to run PostgreSQL cluster on version 17

### What is the feature you are proposing to solve the problem?

PostgreSQL 17 is released https://www.postgresql.org/about/news/postgresql-17-released-2936/

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by javsalgar** [comment]
We are waiting for upstream repmgr to release a compatible version 

https://github.com/EnterpriseDB/repmgr/issues/856

**Comment by mfvanek** [comment]
I've tested `17.2.0`. Looks good. Thanks!
