### ISSUE TITLE
automated update

### ISSUE THREAD

**Issue by kale1d0code** [bitnami/containers#73270]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

will dramatically simplify and speed up the update process and would remove the human element making updates more consistent.

### What is the feature you are proposing to solve the problem?

automated update script which will compare the version of moodle persisted in the volume and cross reference this version with the version the image is built against, and then run through the update steps.

1. turn on maintenance mode.
2. swap current files with new files
3. bring back config.php from current files to new files
4. copy across all plugins from current files to new files (shouldn't be necessary)
5. update
6. turn off maintenance mode

### What alternatives have you considered?

build my own image based on alpine
or
https://moodle.org/mod/forum/discuss.php?d=402632

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
