### ISSUE TITLE
column "communication-&gt;contextid" cannot be modified. Dependency found with index "mdl_comm_con_ix (contextid)"

### ISSUE THREAD

**Issue by kale1d0code** [bitnami/containers#73284]
### Name and Version

bitnami/moodle:4.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Update from 4.2.5

### What is the expected behavior?

update to complete

### What do you see instead?

System
column "communication-&gt;contextid" cannot be modified. Dependency found with index "mdl_comm_con_ix (contextid)"

[More information about this error](https://docs.moodle.org/402/en/error/moodle/ddldependencyerror)

Debug info:
```
Error code: ddldependencyerror×Dismiss this notification
Stack trace:
line 734 of /lib/ddl/database_manager.php: ddl_dependency_exception thrown
line 591 of /lib/ddl/database_manager.php: call to database_manager->check_field_dependencies()
line 634 of /lib/ddl/database_manager.php: call to database_manager->change_field_type()
line 830 of /lib/db/upgrade.php: call to database_manager->change_field_notnull()
line 1871 of /lib/upgradelib.php: call to xmldb_main_upgrade()
line 525 of /admin/index.php: call to upgrade_core()
```

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by staples1347** [comment]
I also got this error
