### ISSUE TITLE
[suitecrm] pipe additional log files to stdout

### ISSUE THREAD

**Issue by JoshMcCullough** [bitnami/containers#73359]
### Name and Version

bitnami/suitecrm:8.7.0

### What is the problem this feature will solve?

Not all SuiteCRM log files are written to stdout, therefore they do not show up via `docker logs`.

### What is the feature you are proposing to solve the problem?

This does not work, but is the general idea:
```dockerfile
RUN <<`
set -e

BASE_DIR=/opt/bitnami/suitecrm/logs
LOG_FILES=(
    install.log
    prod/install.log
    prod/prod.log
    public/legacy/suitecrm.log
)

mkdir -p ${BASE_DIR}/prod
mkdir -p ${BASE_DIR}/public/legacy
chmod -R 777 ${BASE_DIR}

for F in "${LOG_FILES[@]}"; do
  F_PATH="${BASE_DIR}"/${F}

  echo "Linking log file to stdout: ${F_PATH}"
  touch ${F_PATH}
  ln -sf /proc/1/fd/1 ${F_PATH}
done


ls -lR ${BASE_DIR}
`
```

It doesn't work because this error occurs during startup:

> Running: check-route-access
> 
> In StreamHandler.php line 115:
>                                                                                
>   The stream or file "/opt/bitnami/suitecrm/logs/prod/prod.log" could not be   
>   opened in append mode: Failed to open stream: Permission denied  

### What alternatives have you considered?

The alternative is to `exec` into the container and look at the logs directly. This is not feasible for a production deployment.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
