### ISSUE TITLE
[bitnami/suitecrm] cannot use passwords with certain characters

### ISSUE THREAD

**Issue by JoshMcCullough** [bitnami/containers#73374]
### Name and Version

bitnami/suitecrm:8.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm not sure if this is a bug on the Bitnami or SuiteCRM side. If you set the `SUITECRM_DATABASE_PASSWORD` env var and include certain characters, SuiteCRM fails to start. For instance, set `SUITECRM_DATABASE_PASSWORD: abcd^123$456` in your `docker-compose.yml` and run the container (you will have to escape the dollar sign in the compose file (`$$`)). You will see an error like this:

> request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: "You have requested a non-existent parameter "5E123"." at App_KernelProdContainer.php line 2099 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException(code: 0): You have requested a non-existent parameter \"5E123\". at /bitnami/suitecrm/cache/prod/ContainerMJjGx0U/App_KernelProdContainer.php:2099)"} []

Note that `5E123` in the error message is coming from the `^123` portion of the password I set.

### What is the expected behavior?

Any character should work within the `SUITECRM_DATABASE_PASSWORD` env var.

### What do you see instead?

SuiteCRM fails to start with the above error message.

**Comment by javsalgar** [comment]
Hi!

Could you check the suitecrm configuration file if the password is correctly set? If so, then I'm afraid the issue is on SuiteCRM side, so my advice would be to check with the upstream developers.
