### ISSUE TITLE
[bitnami/moodle] Set a default language other than English with environment variable

### ISSUE THREAD

**Issue by rimkov** [bitnami/containers#7339]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

set the Moodle default language other than English

### What is the feature you are proposing to solve the problem?

modify the moodle_install function in the libmoodle.sh script by replacing "--lang=en" with "--lang=${MOODLE_LANG}"

### What alternatives have you considered?

modify config.php file after it has been generated by adding `$CFG->lang = 'fr';`
or
using Moosh command (installed with a post installation custom script) to change the default language after installation 
`moosh config-set lang fr`

**Comment by fmulero** [comment]
Moodle is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this asset. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
