### ISSUE TITLE
pgbouncer with bitnami repmgr container

### ISSUE THREAD

**Issue by TamarNR** [bitnami/containers#7342]
### Name and Version

bitnami/postgresql-repmgr:13.3.0-debian-10-r22

### What is the problem this feature will solve?

Hi,
I am using the docker containers bitnami/postgresql-repmgr:13.3.0-debian-10-r22 in order to enable automatic failover for PostgreSql (I have 2 containers on 2 servers, one is the primary, the other a standby).

Our application (using springboot) is using this connection string for the Postgres replication:
```
postgres.host=xx.xx.x.140
postgres.port=1054

postgres.cluster=[xx.xx.x.140:5433 (http://xx.xx.x.140:5433)],[xx.xx.x.97:5433(http://xx.xx.x.97:5433)]
```
In case the Primary (140) fails, and repmgr will make 97 the primary, the application will try to connect to 140, will fail, and so will try the next string in the connection string, and will connect successfully to the new primary 97.

However, when I start the failed primary as standby, the application can connect to it, and does so, but returns errors on "read only".

I was thinking of using pgbouncer to overcome this problem, but I am not sure how and if it can be integrated into the repmgr container.

Please advise.

Thanks,
Tamar

### What is the feature you are proposing to solve the problem?

repmgr-pgbouncer integration?

**Comment by carrodher** [comment]
Hi,

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
