### ISSUE TITLE
[bitnami/moodle] Where is source?

### ISSUE THREAD

**Issue by povserok** [bitnami/containers#73479]
### Name and Version

bitnami/moodle:4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I can see Bitnami docker image for Moodle 4.5, but I cannot see source on Github.

### What do you see instead?

Version 4.4. is the latest.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. This seems to be an issue in our automated process. I triggered a new automated release and the source code should appear.

**Comment by javsalgar** [comment]
Here's the source: https://github.com/bitnami/containers/commit/716aefca5896a305d159d49b01aedcf50f086eae

Thanks again for reporting
