### ISSUE TITLE
[bitnami/opensearch-dashboards] expose SERVER_BASEPATH and SERVER_REWRITEBASEPATH

### ISSUE THREAD

**Issue by eviltik** [bitnami/containers#73482]
### Name and Version

bitnami/opensearch-dashboards

### What is the problem this feature will solve?

We can't change the basepath with bitnami env vars right now.

Ability to change basepath of the web app is "critical" : no need to make a complex config related to cookie/location/html on-the-fly modification in the reverse proxy configuration (nginx like) 

### What is the feature you are proposing to solve the problem?

expose SERVER_BASEPATH and SERVER_REWRITEBASEPATH, see https://forum.opensearch.org/t/nginx-proxy-and-opensearchdashboard/14823/2

### What alternatives have you considered?

The hard way : playing with proxy directives nginx side (modify header location, modify the html ...)

While you consider/implement this feature, any alternatives are welcome (config files or scripts to add).

Thank you.

**Comment by javsalgar** [comment]
Hi,

Is this `SERVER_BASEPATH` env var consumed by opensearch-dashboards directly? If so, you can set the env var. Or does this env var change a configuration file?

**Comment by eviltik** [comment]
Finally, i end up with a security error opendashoard ui side  when playing with nginx rewrite config, for a good reason, so it's not possible to use a rewrite config to change the basepath.

@javsalgar setting theses env var don't have any effect. After some investigation, i need to customize /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml and enable + modify current value :

* server.basePath: ""
* server.rewriteBasePath: false

Should i try to copy my own opensearch_dashboards.yml trought the docker file ? let my try

**Comment by eviltik** [comment]
I succeed by copying my own opensearch_dashboards.yml file into /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml

Not sure if it's the good way, but it's working as expected.
