### ISSUE TITLE
[bitnami/thanos] Unable to open shell on containers, $PATH unknown

### ISSUE THREAD

**Issue by trip-pguedes** [bitnami/containers#73498]
### Name and Version

bitnami/thanos:0.36.1-debian-12-r3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. helm install my-release oci://registry-1.docker.io/bitnamicharts/thanos
2. try and open shell of thanos-query, thanos-queryfrontend or thanos-storegateway (example: kubectl exec -it bitnami-thanos-storegateway-0 -- echo $PATH)

### What is the expected behavior?

To be able to open shell and execute commands

### What do you see instead?

OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown

### Additional information

I fixed it by adding an sh from an existing image and building upon the existing bitnami thanos image:
FROM bitnami/thanos

COPY --from=busybox:1.37.0-uclibc /bin/sh /bin/sh

ENTRYPOINT [ "/bin/thanos" ]

**Comment by javsalgar** [comment]
Hi,

I'm afraid that, as the container is based on scratch, it is not possible to run commands inside it. However, this may be useful to you

https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container

**Comment by trip-pguedes** [comment]
I see, thank you!
