### ISSUE TITLE
[bitnami/pgpool] `pool_hba.conf` contains unknown users?

### ISSUE THREAD

**Issue by yukha-dw** [bitnami/containers#73526]
### Name and Version

bitnami/pgpool:4.5.4-debian-12-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It's not really a bug but I'm not sure where to ask. On default `pool_hba.conf`, current script let `pop_user` & `wide` users to be accessed without auth (`trust`). Is it intentional or remnant of previous version? I don't see any reference here nor pgpool's source code. Thank you in advance.

https://github.com/bitnami/containers/blob/2de4377adaaa5ba0ba682bc1aa62747cea63bc22/bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh#L365-L372

### What is the expected behavior?

`pool_hba.conf` doesn't contain give free pass to unknown users

### What do you see instead?

`pool_hba.conf` gives free pass to unknown users

**Comment by jotamartos** [comment]
Hi @yukha-dw,

Thank you for bringing this to our attention. I tried to find more information about why we have those 2 lines but couldn't find anything. It seems that it's something we added for a previous version but it's not necessary anymore. I also reviewed the charts repo and didn't find any reference. Would you like [to contribute](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) and update the code? 

Thanks

**Comment by yukha-dw** [comment]
@jotamartos, got it. I've created https://github.com/bitnami/containers/pull/74166 to remove them

**Comment by tankpanv** [comment]
bitnami/postgresql-repmgr@latest

i get the same problem 
pool_hba.conf gives free pass to unknown users
when i change
 cat pg_hba.conf 
pg_hba.conf
host     all            repmgr    0.0.0.0/0    md5
host     repmgr         repmgr    0.0.0.0/0    md5
host     repmgr         repmgr    ::/0         md5
host     replication      repmgr    0.0.0.0/0    md5
host     replication      repmgr    ::/0         md5
#hostssl     all             all             0.0.0.0/0               cert
#hostssl     all             all             ::/0                    cert
host     all              all       0.0.0.0/0    md5
host     all              all       ::/0         md5
local    all              all                    md5

then i restart the containerd
it come back to  all trust again
 is that problem fix on the latest containerd image ？

**Comment by yukha-dw** [comment]
@tankpanv As far I know, we can't directly edit any configuration from the container. It will be discarded on restart.

Try to disable configuration called `pgHbaTrustAll` (I forgot the actual name) and mount your `pg_hba.conf` to designed path. I haven't tested it yet, but latest image should support this feature.
