### ISSUE TITLE
[suitecrm] Schedule not enabled -- cron job is not configured

### ISSUE THREAD

**Issue by JoshMcCullough** [bitnami/containers#73548]
### Name and Version

bitnami/suitecrm:8.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run a container.
2. Check the crontab for the `daemon` user: `crontab -l -u daemon`
3. See that there are not jobs configured.

### What is the expected behavior?

A cron job needs to be added in order to enable the SuiteCRM Scheduler to run its jobs. Without this, much of the functionality will not work.

See: https://docs.suitecrm.com/blog/scheduler-jobs/

### What do you see instead?

No cron jobs exist, so the Scheduler does not run its jobs.

### Additional information

Here's what the crontab entry should look like (it must be "installed" for the `daemon` user):

```cron
* * * * * /opt/bitnami/php/bin/php /bitnami/suitecrm/public/legacy/cron.php
```

**Comment by JoshMcCullough** [comment]
Fixed with PR: https://github.com/bitnami/containers/pull/73549

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
