### ISSUE TITLE
[bitnami/pgbouncer] Support  max_user_connections

### ISSUE THREAD

**Issue by wootapa** [bitnami/containers#73724]
### Name and Version

bitnami/pgbouncer

### What is the problem this feature will solve?

PgBouncer supports limiting max connections per user with [`max_user_connections`](https://www.pgbouncer.org/config.html)

### What is the feature you are proposing to solve the problem?

Would be great if you could add an environment variable `PGBOUNCER_MAX_USER_CONNECTIONS ` to support it.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will check it.
