### ISSUE TITLE
Endless boot loop with Docker image in Azure App Services.

### ISSUE THREAD

**Issue by kristiandg** [bitnami/containers#73994]
### Name and Version

bitnami/suitecrm:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In the attached pics, you can see how it's configured in Azure, as well as the boot log, which shows it repeatedly running the same tasks (such as "Starting CRM Setup", "Generating Sample Certs", and "Running Setup Wizard").  The last thing it seems to do is "Configuring SMTP" before it starts the cycle over again. I don't see any error messages, just the next log stream entry is an item it said previously, and in the last pic you can see the log stream, where the top and bottom lines are "Starting Apache in Background". I had hoped to get into Kudu and issue a command-line command to test the database connection (thinking maybe that was the issue, that it wasn't connecting), but it didn't recognize any "mysql" commands at the CLI. 
<img width="933" alt="Screenshot 2024-10-27 at 10 15 36 AM" src="https://github.com/user-attachments/assets/152afefa-f68c-49f5-bd2d-7739aa194b6e">

<img width="702" alt="Screenshot 2024-10-27 at 9 58 17 AM" src="https://github.com/user-attachments/assets/9e1e081d-cda9-442c-a97d-eaba426e0d6c">
<img width="336" alt="Screenshot 2024-10-27 at 9 57 37 AM" src="https://github.com/user-attachments/assets/3e2a45e8-c031-4da5-894a-0e7a83a0e8eb">

What I end up with is this (endless loading - briefly the login fields appear, then the SuiteCRM logo takes over, and it keeps cycling through that):
<img width="1172" alt="Screenshot 2024-10-27 at 10 02 59 AM" src="https://github.com/user-attachments/assets/e269fed9-e1fa-423a-abdd-83f39037645b">

### What is the expected behavior?

I had expected it would boot fully, but it appears to be dying at some point, making it so my client is no longer in contact with the server (and I'm guessing the parts of the webpage that had already successfully downloaded, are seeing that lost connection and generating the overriding SuiteCRM "loading" logo).

### What do you see instead?

I'm seeing an endless loading screen on the web front-end, and repeating log entries indicating it's crashing right around Configuring SMTP, and then re-attempting to boot from startup.

**Comment by kristiandg** [comment]
After turning on the detailed logs, I found the error to be that the SUITECRM_DATA_TO_PERSIST=$SUITECRM_BASE_DIR was returning that no such directory existed.

Removing that line, allowed it to boot, and me to log in, but a subsequent restart of the image showed "Container not healthy, stopping".

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
