### ISSUE TITLE
valkey sentinel is broken

### ISSUE THREAD

**Issue by amirreza8002** [bitnami/containers#74017]
### Name and Version

bitnami/valkey-sentinel:7.2.7

### What architecture are you using?

None

### What steps will reproduce the bug?

running valkey:7.2.7 fails: `Unrecognized sentinel configuration statement.`

### What do you see instead?

seems like the sentinel conf is not supported by valkey:7.2.7
worth noting that this is a new error(3 days ago), the same tests had no problems some time ago

### Additional information

[7.2.7](https://github.com/amirreza8002/django-valkey/actions/runs/11561620322/job/32181035918) fails
[latest](https://github.com/amirreza8002/django-valkey/actions/runs/11561620322/job/32181035551) passes

**Comment by jotamartos** [comment]
We are working on building an updated version of the container and adding new test to our container

**Comment by jotamartos** [comment]
[7.2.7-debian-12-r3](https://github.com/bitnami/containers/pull/74092) was released with the changes to fix this issue. Did you have the chance to take a look at it?
