### ISSUE TITLE
add environment variable for db_maxconn for connection to odoo db

### ISSUE THREAD

**Issue by pedominguezbr** [bitnami/containers#74019]
### Name and Version

bitnami/odoo:16

### What is the problem this feature will solve?

will allow to increase the db_maxconn of the connection pool using an environment variable

### What is the feature you are proposing to solve the problem?

in the file bitnami/odoo/16/debian-12/rootfs/opt/bitnami/scripts/odoo/bitnami-templates/odoo.conf.tpl
update the line with ; db_maxconn = 64, to something like: db_maxconn = {{ODOO_DATABASE_MAXCONN}}
PR. #74018

### What alternatives have you considered?

A more complicated alternative would be to add the odoo.conf directly and not create the file using the template bitnami/odoo/16/debian-12/rootfs/opt/bitnami/scripts/odoo/bitnami-templates/odoo.conf.tpl

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
