### ISSUE TITLE
[OpenLDAP] Custom schema freezes the image

### ISSUE THREAD

**Issue by RensHoskens** [bitnami/containers#74023]
### Name and Version

bitnami/openldap:2.6.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am creating an LDAP testcontainer for Java using the `bitnami/openldap:2.6.8` image. 
The environment variables are the following:
- `LDAP_ROOT: dc=example,dc=org`
- `LDAP_ADMIN_USERNAME: admin`
- `LDAP_ADMIN_PASSWORD: adminpassword`

I have a custom schema (created in ApacheDS and then exported as OpenLDAP files).
```text
attributetype ( 1.3.6.1.4.1.99999.1.1 NAME 'myCustomAttribute'
	DESC ''
	USAGE userApplications )
objectclass ( 1.3.6.1.4.2.99999.1.1 NAME 'myCustomType'
	DESC ''
	STRUCTURAL
	MAY myCustomAttribute )
```

I mount the custom schema file in `/schema/custom.ldif` (which is automatically added as custom schema)

### What is the expected behavior?

I would expect that the image will add the schema to the openldap instance and then start up. The extra objectclass should be usable.

### What do you see instead?

The logfile mentions that it's adding the custom schema:

```text
 09:59:27.92 INFO  ==> ** Starting LDAP setup **
 09:59:27.93 INFO  ==> Validating settings in LDAP_* env vars
 09:59:27.94 INFO  ==> Initializing OpenLDAP...
 09:59:27.94 INFO  ==> Creating LDAP online configuration
 09:59:27.94 INFO  ==> Creating slapd.ldif
 09:59:27.96 INFO  ==> Starting OpenLDAP server in background
 09:59:28.96 INFO  ==> Configure LDAP credentials for admin user
 09:59:28.97 INFO  ==> Adding LDAP extra schemas
 09:59:28.98 INFO  ==> Adding custom Schema : /schema/custom.ldif ...
```

And then nothing more.  No additional logs, the image doesn't respond anymore. Port is also not open.

### Additional information

I'm guessing it has something to do with the [startup function](https://github.com/bitnami/containers/blob/6cba5c3ab04c2a2c75cbb6204964de68c3993438/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh#L487) being called.
Also, adjusting the `LDAP_LOGLEVEL` has no effect on this.

**Comment by carrodher** [comment]
Setting the `BITNAMI_DEBUG` env. variable to `true` will increase the verbosity of the initialization scripts, could please you try that?

**Comment by b17saurabh** [comment]
@RensHoskens Please add more info to this thread, contents of your schema file and how you have validated it.
