### ISSUE TITLE
[bitnami/wordpress] wp-config.php did not change on WORDPRESS_EXTRA_WP_CONFIG_CONTENT update

### ISSUE THREAD

**Issue by riupie** [bitnami/containers#74025]
### Name and Version

bitnami/wordpress:6.6.2-debian-12-r12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy on top kubernetes using helm chart
2. Add WORDPRESS_EXTRA_WP_CONFIG_CONTENT with some content
3. Deployed and run as expected
4. Update WORDPRESS_EXTRA_WP_CONFIG_CONTENT value
5. wp-config.php file did not reflect to new changes.

### What is the expected behavior?

Update on WORDPRESS_EXTRA_WP_CONFIG_CONTENT reflected on wp-config.php file.

### What do you see instead?

The wp-config.php file is still the same as the one used in the initial installation.

### Additional information

Should I exclude it from WORDPRESS_DATA_TO_PERSIST instead? Any drawback if I exclude wp-config.php from it?

**Comment by javsalgar** [comment]
Hi,

I'm afraid that currently, this value is set as first-boot. If you want to further update it, you would need to manualy edit it. I'm not sure that removing `wp-config.php` from DATA_TO_PERSIST may work in this case.
