### ISSUE TITLE
[bitnami/kong] Invalid `KONG_POSTGRESQL_PASSWORD_FILE`

### ISSUE THREAD

**Issue by yukha-dw** [bitnami/containers#74031]
### Name and Version

bitnami/kong:3.8.0-debian-12-r8

### What architecture are you using?

None

### What steps will reproduce the bug?

Shouldn't `KONG_POSTGRESQL_PASSWORD_FILE` be `KONG_PG_PASSWORD_FILE`? `KONG_POSTGRESQL_PASSWORD` is not an alias of `KONG_PG_PASSWORD`.

https://github.com/bitnami/containers/blob/95dd8afa0efa48cbcce76a9b8f78b44a2251cab6/bitnami/kong/3/debian-12/rootfs/opt/bitnami/scripts/libkong.sh#L83

One way to fix it perhaps by adding this line on `kong-env.sh`
```
kong_env_vars=(
    ...
    KONG_PG_PASSWORD
    KONG_POSTGRESQL_PASSWORD
)
...
KONG_PG_PASSWORD="${KONG_PG_PASSWORD:-"${KONG_POSTGRESQL_PASSWORD:-}"}"
export KONG_PG_PASSWORD="${KONG_PG_PASSWORD:-}"
```

### What is the expected behavior?

`KONG_POSTGRESQL_PASSWORD_FILE` becomes alias of `KONG_PG_PASSWORD_FILE`

### What do you see instead?

Container validates `KONG_POSTGRESQL_PASSWORD_FILE`, but does not use it

### Additional information

`KONG_POSTGRESQL_PASSWORD_FILE` is also mentioned in bitnami/charts

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by yukha-dw** [comment]
I've created the PR https://github.com/bitnami/containers/pull/74112. After further reading, I've decided to remove the validation as it does not work as intended, only causing bug when user tries to use it

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by yukha-dw** [comment]
I'll close this issue due to breaking change with kong's chart
