### ISSUE TITLE
Upgrade to `bitnami/mysql:8.0.38` causes `Server upgrade started with version 80038, but server upgrade of version 80038 is still pending` error

### ISSUE THREAD

**Issue by boutterudy** [bitnami/containers#74344]
### Name and Version

bitnami/mysql:8.0.38

### What architecture are you using?

None

### What steps will reproduce the bug?

Not 100% sure but I guess you can try:
1. In an environment running `bitnami/mysql:8.0` as of 30th June 2024
2. Update the container image to `bitnami/mysql:8.0.38`
3. Start the updated container
4. Observe repeated errors in the logs indicating data dictionary initialization failure and an aborted startup

### What is the expected behavior?

Upon upgrading the container image to version 8.0.38, the MySQL server should initialize correctly and continue to operate with existing data, completing any required internal upgrades seamlessly.

### What do you see instead?

The following logs repeatedly indicate that the server upgrade is still pending, resulting in an aborted startup:
```
2024-11-07T19:09:32.235161Z 1 [ERROR] [MY-013379] [Server] Server upgrade started with version 80038, but server upgrade of version 80038 is still pending.
2024-11-07T19:09:32.256141Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2024-11-07T19:09:32.256270Z 0 [ERROR] [MY-010119] [Server] Aborting
...
```

### Additional information

The issue appears to relate to a failed or incomplete data dictionary upgrade during initialization. Restarting the container continues to produce the same error.

I also tried to downgrade to lower versions, but I get the exact same error in loop.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
