### ISSUE TITLE
Airflow LDAP variables are checked incorrectly

### ISSUE THREAD

**Issue by HorusTheSonOfOsiris** [bitnami/containers#74359]
### Name and Version

bitnami/airflow:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Use the latest helm chart and enable ldap. Use the default ldap values.

the error says AIRFLOW_LDAP_USER_REGISTRATION: allowed values is yes or no. 

### What is the expected behavior?

Expected behaviour is to deploy helm chart with LDAP successfully. 

### What do you see instead?

When the web server runs the error in the logs says

AIRFLOW_LDAP_USER_REGISTRATION should be a yes or no value. 

### Additional information

I believe [this PR](https://github.com/bitnami/containers/pull/74028) introduced the issue by checking the value as yes or no. In the Helm charts the values are passed as True or False. I think value should be checked for True or False instead.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by HorusTheSonOfOsiris** [comment]
Hi @carrodher , I have raised a pull request to address this issue in Bitnami Airflow chart. Here is the link to [pull request](https://github.com/bitnami/charts/pull/30382).

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by juan131** [comment]
To be fixed at https://github.com/bitnami/charts/pull/30349
