### ISSUE TITLE
Bitnami:Postgres Running psql commands directly in container seem to "freeze".  Always need to use Cntl-C to break the command

### ISSUE THREAD

**Issue by kevdogg** [bitnami/containers#74379]
### Name and Version

bitnami/postgres:16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using the bitnami/postgres16 image with docker compose. I'm starting off with an empty database to test. The database is initialized and I log into the container via:

`sudo docker exec -it <name of containter> /bin/bash`

From inside the container I login to the database via:

`PGPASSPASSWORD=<POSTGRESQL_POSTGRES_PASSWORD variable defined in docker_compose.yml> psql -U psql`

Once logged in as the postgres user, I try something simple such as:

`postgres=# ALTER USER postgres WITH ENCRYPTED PASSWORD 'postgresql-postgresql-pass';`

The control process never returns to the command prompt.  I need to break the command with a Cntl-C.  Checking in this the command seems to be successfully completed (can log in via the new password) however with every command given at command line I need to break command.

### What is the expected behavior?

Process should execute and return the to the prompt. Such as:

```
postgres=# ALTER USER postgres WITH ENCRYPTED PASSWORD 'postgresql-postgresql-pass';

postgres=#
```

### What do you see instead?

I see a hanging cursor:

```
postgres=# ALTER USER postgres WITH ENCRYPTED PASSWORD 'postgresql-postgresql-pass';
[]
```

### Additional information

I originally thought it might be a permissions issue, but I don't think this is the case since in my example the password is actually changed. I've also tried running variations of this command by running this command from the psql command line prompt from within the docker container and it does the same thing in terms of "freezing" or not returning the command prompt.

**Comment by fmulero** [comment]
Thanks @kevdogg  for using bitnami/containers!

 I tried to reproduce your issue but I have no luck:
```console
$ docker run -d --rm --name psql -e POSTGRESQL_PASSWORD=test bitnami/postgresql:16
bcadea12ddebbe95b0b3c3676721d7a6138619ad577fc4c54a6269a217300d92
$ docker exec -it psql /bin/bash
I have no name!@bcadea12ddeb:/$ psql -U postgres
Password for user postgres: 
psql (16.6)
Type "help" for help.

postgres=# ALTER USER postgres WITH ENCRYPTED PASSWORD 'salami';
ALTER ROLE
postgres=# 
```

Could you provide your docker-compose to try to reproduce the issue?
