### ISSUE TITLE
[bitnami/postgresql] Release postgresql-16.4.0-debian-12-r25 cause issue with unexpected `POSTGRESQL_REPLICATION_USE_PASSFILE`

### ISSUE THREAD

**Issue by jonesbusy** [bitnami/containers#74804]
### Name and Version

bitnami/postgresql:16.4.0-debian-12-r25

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

Upgrade from postgresql-16.4.0-debian-12-r24 to postgresql-16.4.0-debian-12-r25 cause issue with 

`POSTGRESQL_REPLICATION_USE_PASSFILE: unbound variable`

For some reason this was added on https://github.com/bitnami/containers/pull/74787/files#diff-bfae4bf6b63bbf56c7572b773c8f5ce5088f09b8044edc934f49f5aacd26442aR395 but not sure why

Thanks

### What do you see instead?

`POSTGRESQL_REPLICATION_USE_PASSFILE: unbound variable`

**Comment by jonesbusy** [comment]
I lost full logs (only screenshot), but this occur exactly at https://github.com/bitnami/containers/pull/74787/files#diff-bfae4bf6b63bbf56c7572b773c8f5ce5088f09b8044edc934f49f5aacd26442aR395

![unbound](https://github.com/user-attachments/assets/f91491ed-7f0e-41bc-ad05-5205ebc1cc32)

**Comment by val-pez** [comment]
I had the same, and was using docker compose. I fixed it by setting:

    environment:
      - POSTGRESQL_REPLICATION_USE_PASSFILE=false

**Comment by azhalm94** [comment]
This is strange, when running the container locally is Ok, but have this issue with Github workflow

**Comment by jeffersonfelixdev** [comment]
Same problem here, I tested various versions (13,14,15,16). Same error

**Comment by eulixir** [comment]
Something changed in the latest version. I followed the same steps as @val-pez, and it worked!

I’m using POSTGRESQL_REPLICATION_USE_PASSFILE: "no" in my postgres image, and that fixed the issue.

**Comment by jeffersonfelixdev** [comment]
> Something changed in the latest version. I followed the same steps as @val-pez, and it worked!
> 
> I’m using POSTGRESQL_REPLICATION_USE_PASSFILE: "no" in my postgres image, and that fixed the issue.

Worked!

**Comment by carrodher** [comment]
Thank you for reaching out. We’re currently tracking this issue in another support ticket. To keep all updates centralized and ensure efficient troubleshooting, we’ll close this ticket as a duplicate. Please refer to ticket https://github.com/bitnami/containers/issues/74788 for ongoing updates and further assistance on this matter.

About the issue itself, we're looking into it and we'll update that ticket with our findings. We appreciate your patience and cooperation!
