### ISSUE TITLE
[bitnami/clickhouse] Unable to mount clickhouse data directory as volume in docker /bitnami/clickhouse/data

### ISSUE THREAD

**Issue by zubi-venturenox** [bitnami/containers#74874]
### Name and Version

bitnami/clickhouse:24.10.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Unable to mount the `CLICKHOUSE_DATA_DIR` or `CLICKHOUSE_VOLUME_DIR` directory as volumes in the docker-compose file. Compose I am using:
![image](https://github.com/user-attachments/assets/21a61f86-1a6d-4999-bd33-9c4b03ee9326)

### What is the expected behavior?

Volume should be mounted and data should persist

### What do you see instead?

When building the image docker shows these logs and exits.
Gives `Permission denied ["/var/lib/clickhouse/preprocessed_configs"]`
Complete logs attached
![Screenshot_20241113_164304](https://github.com/user-attachments/assets/3fea0245-740f-452d-8c22-b5e8e1ddcb35)

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by zubi-venturenox** [comment]
That may absolutely be the root cause of the issue but doesnt work out of the box in docker compose. Sure I can work around it in a Dockerfile but the problem here is how do you get it to work in docker compose?

**Comment by javsalgar** [comment]
Hi,

If you are bind-mounting local volumes, you need to give very open permissions so a non-root user can access them. You may need to provide the "others" group write permissions, for instance.
