### ISSUE TITLE
[discourse]Can an environment variable be added to control whether compress(gzip) is enabled or not?

### ISSUE THREAD

**Issue by wszgrcy** [bitnami/containers#74879]
### Name and Version

bitnami/discourse:latest

### What is the problem this feature will solve?

Currently using images, resources will be automatically compressed using gzip, but I want the compression to be managed by superiors (traefik, apisix, nginx...) because superiors support multiple compression formats (zstd, brolti, gzip), which will save some transmission data

### What is the feature you are proposing to solve the problem?

Add environment variables and disable internal gzip(nginx)

### What alternatives have you considered?

![image](https://github.com/user-attachments/assets/e79018b9-2658-44ff-bca2-8ce3ccdb9256)
![image](https://github.com/user-attachments/assets/aae361e8-8feb-44c9-82a2-14fb44914b68)

I started two services simultaneously using Traefik, one is Whoami (successfully using zstd), and the other is Discourse (supporting zstd but returning gzip)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
