### ISSUE TITLE
su - postgres is not working

### ISSUE THREAD

**Issue by cibilex** [bitnami/containers#74880]
### Name and Version

bitnami/postgresql:latest

### What architecture are you using?

None

### What steps will reproduce the bug?
`docker exec -it pod-pos bash` connecting the postgres container

### What is the expected behavior?

 I should be able to switch to the postgres user using the su - postgres command, allowing me to run PostgreSQL-related commands like createdb without needing to use the -U flag every time.

### Additional information

Unable to switch to `postgres` user with `su - postgres` in Bitnami PostgreSQL Docker image

I am using the `bitnami/postgresql` Docker image for PostgreSQL, and I’m encountering an issue where I cannot switch to the `postgres` user using the `su - postgres` command. When attempting to do so, I receive the following error:

```
su: user postgres does not exist or the user entry does not contain all the required fields
```

As a result, I am forced to use the `-U postgres` flag for all commands (e.g., `createdb -U postgres test`), which is inconvenient. Alternatively, I have to first connect to the database with `psql -U postgres` and then run the necessary commands, which feels like an unnecessary extra step.

Could you please advise on how to resolve this or if there's a known workaround?

**Comment by fluca1978** [comment]
Apparently, there is the same behaviour for `bitnami/postgresql-repmgr` where both `postgres` and `repmgr` users are missing from the `/etc/passwd` file. Configuration files are set to be owned by user `1001`, which does not exist.

**Comment by migruiz4** [comment]
Hi @fluca1978,

Users `postgres` and `repmgr` do not exist as system users, only as PostgreSQL users.

Bitnami containers are designed to operate using arbitrary UIDs to enhance its security. This practice is usually referred as 'non-root containers'. 
In our case, the user 1001 is the default UID which does not belong to any user in `/etc/passwd` on purpose. 

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
