### ISSUE TITLE
support for testcontainers

### ISSUE THREAD

**Issue by rajadilipkolli** [bitnami/containers#74973]
### Name and Version

postgres

### What is the problem this feature will solve?

Spring boot supports bitnami versions for docker-compose. To use the same in testcontainers it needs support from the bitnami team, for more information please refer to https://github.com/testcontainers/testcontainers-java/issues/9502#issuecomment-2458317053

### What is the feature you are proposing to solve the problem?

Support for testcontainers

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. We will apply the' on-hold' label to ensure that your idea receives the attention it deserves. This will prevent our automated system from prematurely closing the issue.

We'll let you know of any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
