### ISSUE TITLE
[ bitnami/airflow ] build fails due to missing packages

### ISSUE THREAD

**Issue by aquynh1682** [bitnami/containers#75032]
### Name and Version

bitnami/airflow:2.0.5-debian-11-r16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to rebuild Airflow.
The build failed, and I encountered an error indicating missing required packages (error log: curl: (22) The requested URL returned error: 404 Not Found).

Below is the list of required packages to build this version.
```
      "wait-for-port-1.0.6-linux-${OS_ARCH}-debian-11" \
      "python-3.8.6-1-linux-${OS_ARCH}-debian-11" \
      "postgresql-client-15.1.0-1-linux-${OS_ARCH}-debian-11" \
      "ini-file-1.4.4-2-linux-${OS_ARCH}-debian-11" \
      "gosu-1.16.0-1-linux-${OS_ARCH}-debian-11" \
      "airflow-worker-2.5.0-2-linux-${OS_ARCH}-debian-11" \
```
I know these packages have been removed, but I am unsure how to customize the base image as it is also encountering several issues.

### What is the expected behavior?

Can you re-upload these installation packages for 2-3 days?

### What do you see instead?

`error log: curl: (22) The requested URL returned error: 404 Not Found`

**Comment by carrodher** [comment]
Unfortunately, due to our retention policy, those packages have been removed, and recovering them is not straightforward. If you need to use an older version, could you consider using the already-built container image instead? Alternatively, if you need to apply customizations in the Dockerfile, would it be possible to use a more recent version as the base?

**Comment by aquynh1682** [comment]
Hi @carrodher , Unfortunately, I cannot use a newer version because my current version is incompatible with Spark due to the Python version mismatch. Is it possible to use a base image and downgrade its Python version to 3.8?
