### ISSUE TITLE
[bitnami/google-cloud-sdk] Google's gsutil still requires python 3.11, only 3.12 is shipped in sdk image

### ISSUE THREAD

**Issue by maxyz** [bitnami/containers#75091]
### Name and Version

bitnami/google-cloud-sdk:0.489.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Simply running gsutil in the generated container produces:
```
I have no name!@7f189755450a:/$ gsutil 
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
	1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
```

### What is the expected behavior?

Should be able to run gsutil, or at least other bitnami script should use gsutil.

### What do you see instead?

gsutil fails whenever you try to run it.

As a consequence this causes the influx_backup scripts from: https://github.com/bitnami/charts/blob/main/bitnami/influxdb/templates/configmap-backup.yaml

fail to run.

### Additional information

This is affecting other charts offered by bitnami.

The last working version is: 0.489.0-debian-12-r0
Still failing in: 0.502.0-debian-12-r0

commit that updates python to 3.12: https://github.com/bitnami/containers/commit/a5313d5d85da00df42759bcac180f3c11a547024

Alternatively, the influx backup scripts should use gcloud storage rsync instead of gsutil -m resync.

**Comment by jotamartos** [comment]
Thanks for reporting this issue. We are working on downgrading the Python version included in the container. We will also update our tests to validate the output of the `gsutil --version` command.
