### ISSUE TITLE
Wordpress-nginx Crashloopback

### ISSUE THREAD

**Issue by tausday** [bitnami/containers#75147]
Name and Version

bitnami/wordpress-nginx:v6.4.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install from Stock with parameters from the manual

### What is the expected behavior?

I started the container and after 3 seconds it crashed without any notice.

[Screenshot](https://ibb.co/r3cmqqX)

Any idea?

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
