### ISSUE TITLE
Just a question about the deprection notice

### ISSUE THREAD

**Issue by alex02th** [bitnami/containers#75141]
### Name and Version

bitnami/nginx/README.md

### What is the problem this feature will solve?

Hello,

I'm sorry to ask it here, I just didn't find information about this and I didn't know where to ask questions

Is there a reason why nginx containers will not be released anymore?
And will it be the same for the helm charts?

Thanks in advance

### What is the feature you are proposing to solve the problem?

I don't know

**Comment by carrodher** [comment]
Hi @alex02th, it was a mistake when deprecating a different container image. We just removed that paragraph that was added by mistake, see https://github.com/bitnami/containers/commit/b9ad685aa440aa2f7bfbde082cde424006a2a14c. 

Definitely, NGINX is not going to be deprecated! Sorry for the confusion and thanks for letting us know.
