### ISSUE TITLE
where store php logs?

### ISSUE THREAD

**Issue by tausday** [bitnami/containers#75211]
### Name and Version

bitnami/wordpress-nginx:v6.4.3.0

### What do you see instead?

Where can I find out why stop the page loads with error 502.

Where can I find the php error or in which file I can set up the right folder? thx

**Comment by carrodher** [comment]
Could you please double check the container you're using? `bitnami/wordpress-nginx:v6.4.3.0` is not a valid tag. Can you share the command you're running to deploy the container? Thanks
