### ISSUE TITLE
How to Increase client_max_body_size in Bitnami Mastodon Container for Larger File Uploads?

### ISSUE THREAD

**Issue by miroslavbucek** [bitnami/containers#75228]
### Describe your issue as much as you can

Hello,

I am running Mastodon using the Bitnami Docker Compose setup. I want to increase the upload file size limit beyond the default 99 MB. After some investigation, I found that the `client_max_body_size` directive in the Nginx configuration is responsible for this limitation.

However, since there is no separate Nginx container in the Bitnami setup and Nginx seems to be bundled inside the mastodon container, I am unsure where to locate and modify the `client_max_body_size` configuration.

Could you please guide me on:
	1.	The exact location of the Nginx configuration file inside the mastodon container?
	2.	How do changes persist in the configuration file across container restarts?
	3.	Do you know if there are any additional steps required to ensure the new limit is applied properly?

I’ve tried setting the `MAX_UPLOAD_SIZE` environment variable in docker-compose.yml, but this does not seem to address the Nginx-level limitation.

Thank you for your help!

**Comment by jotamartos** [comment]
Thank you for using Bitnami. The container uses Puma to start the web server

https://github.com/bitnami/containers/blob/main/bitnami/mastodon/4/debian-12/rootfs/opt/bitnami/scripts/mastodon/run.sh#L36

Please take a look at the Mastodon's documentation to know more about what configuration file to edit to configure the application the way you want.
