### ISSUE TITLE
Default EasyPanel + SuiteCRM Template Fails With Restarting Loop

### ISSUE THREAD

**Issue by jchambo** [bitnami/containers#75227]
### Name and Version

bitnami/suitecrm:8.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a new Vultr VPS 1-click EasyPanel Install via their Marketplace Apps
2. Add SuiteCRM Template / Service
3. suitecrm App service loops over and over

### What is the expected behavior?

App should launch

### What do you see instead?

![image](https://github.com/user-attachments/assets/b97f5f8c-3c67-4e39-830a-9f3228980818)

The project includes the App and MariaDB as well shown here:

![image](https://github.com/user-attachments/assets/4e33cee0-beca-4b0b-90a0-037cc08b9c62)

The MariaDB logs show the following:

![image](https://github.com/user-attachments/assets/b68ebdf0-c13a-4f4d-8e88-6a0ffb115efb)

The “suitecrm” App service just keeps going from green to yellow and loops over and over. Looks like the service is hung somehow. Is this an issue with the Git repository?

![image](https://github.com/user-attachments/assets/0472a8d1-371c-452d-8333-1a7b25698276)

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
