### ISSUE TITLE
[bitnami/vllm] feat: Add new container

### ISSUE THREAD

**Issue by zhekazuev** [bitnami/containers#75274]
### Name and Version

bitnami/vllm - 0.6.2, 0.6.3 and 0.6.4

Is it possible to add images for latest and previous versions?

Version 0.6.4 has some critical issues related gpu memory usage:
- https://github.com/vllm-project/vllm/issues/10451
- https://github.com/vllm-project/vllm/pull/10511
- https://github.com/vllm-project/vllm/pull/10498

And related default LLM that should be saved in docker image, looks like vLLM project uses [facebook/opt-125m](https://docs.vllm.ai/en/latest/getting_started/quickstart.html#offline-batched-inference) model.

### What is the problem this feature will solve?

- add new container for vllm - it makes possible to deploy LLMs to kubernetes cluster with vLLM engine.
- this image can be used in a potential Helm Chart by Bitnami - https://github.com/bitnami/charts/issues/30649

### What is the feature you are proposing to solve the problem?

- add Docker container for vllm

### What alternatives have you considered?

- use [official image](https://hub.docker.com/r/vllm/vllm-openai) by vllm-project team
- use [llama-based official image](https://hub.docker.com/r/ai/meta-llama) - added as an example

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Comment by zhekazuev** [comment]
Thank you for your response!

**Comment by zhekazuev** [comment]
> Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.
> 
> 
> 
> We apologize for the inconvenience. We will reconsider it in the future.
> 
> 
> 
> Thanks for your suggestion!

@carrodher Hi,

I have a question, related image for vllm. 

Bitnami don't have time for vllm image, but someone can create PR with that needed changes, or bitnami don't want to maintain vllm image at all?

Because if first, I think community can do that.

Let me know!

**Comment by carrodher** [comment]
Hi, thanks for reaching out! Currently, we don’t plan to include or maintain a vLLM image in the Bitnami catalog. While we appreciate community contributions, we focus on maintaining images that align with our roadmap and long-term support strategy.
