### ISSUE TITLE
Would someone please mirror kafka for me, thank you

### ISSUE THREAD

**Issue by gaoyuan5251** [bitnami/containers#75495]
### Name and Version

bitnami/kafka:3.7.1-debian-12-r4

### What architecture are you using?

None

### What steps will reproduce the bug?

Due to local restrictions, the image package cannot be obtained through docker

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is built on Debian 12 and published exclusively at [DockerHub](https://hub.docker.com/r/bitnami/kafka) and [AWS Public Gallery](https://gallery.ecr.aws/bitnami/kafka).

Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian, PhotonOS, Ubuntu, or RedHat UBI. Those images will be pushed alongside all the surrounding metadata to your chosen registry. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
