### ISSUE TITLE
[bitnami/kafka] How to enable remote storage and use the broker to auto-create topics?

### ISSUE THREAD

**Issue by tqanh2609** [bitnami/containers#75691]
### Name and Version

bitnami/kafka:3.9.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I have written a Dockerfile to build a custom Kafka image with remote storage to Minio S3, using Bitnami's Kafka image and Aiven's plugins. I then used that image to build a Kafka cluster in Kraft mode using the Docker Compose file (both the Dockerfile and Docker Compose file can be found in the zip folder).

[Kraft_kafka_cluster.zip](https://github.com/user-attachments/files/18094008/Kraft_kafka_cluster.zip) 

### What is the expected behavior?

The Kafka cluster started with the remote storage function enabled, and a topic was auto-created to serve that purpose.

### What do you see instead?

Instead, I'm experiencing two problems:
1. When I run `docker compose up`, a topic that should be auto-created fails due to the SASL configuration. 
2. When I remove the SASL configuration to test the remote storage function (thus the first problem is resolved), but when I try to create a topic with the remote storage function, I get the following error while I already has the Enable Tiered Storage config on: 
`ERROR org.apache.kafka.common.errors.InvalidConfigurationException: Tiered Storage functionality is disabled in the broker. Topic cannot be configured with remote log storage. (org.apache.kafka.tools.TopicCommand)`

### Additional information

Here is how I create a topic with the remote storage on: 

1. bash in the container of a broker, `cd opt/bitnami/kafka/bin/` to then create an admin.properties file:
```
sasl.mechanism=PLAIN \
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="sa" password="000000"; \
security.protocol=SASL_PLAINTEXT
```
2. then I create the topic like this: 
```
kafka-topics.sh --bootstrap-server 10.168.6.104:2093 \
  --create \
  --topic tiered_test1 \
  --config remote.storage.enable=true \
  --config segment.bytes=512000 \
  --config local.retention.bytes=1 \
  --config retention.bytes=107374182400
```

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by tqanh2609** [comment]
Has the remote storage function been implemented in the Bitnami/Kafka image? The configuration was correctly mapped to the server.properties file (as shown in the provided image), but when I try to create a topic with the remote storage function, I keep getting the following error: 
`Error while executing topic command : Tiered Storage functionality is disabled in the broker. Topic cannot be configured with remote log storage.
[2024-12-12 10:54:59,734] ERROR org.apache.kafka.common.errors.InvalidConfigurationException: Tiered Storage functionality is disabled in the broker. Topic cannot be configured with remote log storage.
`

![image](https://github.com/user-attachments/assets/54e167ed-5f87-4052-81c2-ef0b7fb0e3ea)

**Comment by ishaqsha** [comment]
Where is the resolution

**Comment by anisbatch** [comment]
I don't know if I got the same issue but for me I was deploying the config `remote.log.storage.system.enable=true` only on brokers, on the kraft controllers and adding only this line to controllers fixed my issue.
