### ISSUE TITLE
[bitnami/mongodb] start mongodb container fail

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#75716]
### Name and Version

bitnami/mongodb:8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. docker pull bitnami/mongodb:8.0
2. execute start command like : `docker run --rm -it --name=tmp-mongodb bitnami/mongodb:8.0`

then print these outputs and start faild:
```
bruce@bruce-22-x64:~/Internal-Docker/bitnami-mongodb$ docker run --rm -it --name=tmp-mongodb 3e464d7caba6
mongodb 01:11:56.30 INFO  ==> 
mongodb 01:11:56.31 INFO  ==> Welcome to the Bitnami mongodb container
mongodb 01:11:56.31 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 01:11:56.31 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
mongodb 01:11:56.32 INFO  ==> 
mongodb 01:11:56.33 INFO  ==> ** Starting MongoDB setup **
mongodb 01:11:56.35 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 01:11:56.38 INFO  ==> Initializing MongoDB...
mongodb 01:11:56.59 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 346:    43 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
`````

### What is the expected behavior?

start OK

### What do you see instead?

`/opt/bitnami/scripts/libos.sh: line 346:    43 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1`

PS: [/opt/bitnami/scripts/libos.sh: line 346](https://github.com/bitnami/containers/blob/3e9d59bb53d7b9626f1959c8eac077b636164b76/bitnami/mongodb/8.0/debian-12/prebuildfs/opt/bitnami/scripts/libos.sh#L346)

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/containers/issues?q=label%3Amongodb+%22Illegal+instruction%22+) you can find previous reports of users encountering the same issue. In all cases, the problem stemmed from running MongoDB on an ARM processor, which is not supported by the upstream in Debian 12.

We're consolidating all discussions related to ARM support for MongoDB at https://github.com/bitnami/containers/issues/40947.
