### ISSUE TITLE
rabbitmq stuck at boot

### ISSUE THREAD

**Issue by ewencodes** [bitnami/containers#75725]
### Name and Version

bitnami/rabbitmq:4.0.3

### What architecture are you using?

amd64

### What do you see instead?

since a restart of my Kubernetes cluster, my rabbitmq cluster composed of 3 nodes refuses to start and is stuck at boot.

![image](https://github.com/user-attachments/assets/25f47f00-9d70-4358-8436-58f6015f132c)

I can't figure out why this happens...

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by ewencodes** [comment]
hi @carrodher, thanks for your support. I will close this issue since I have a response from RabbitMQ maintainers on rabbitmq/rabbitmq-server repository.
have a great day.
