### ISSUE TITLE
[bitnami/elasticsearch] Missing version 8.15.5 to matching spring boot 3.4.1 default version

### ISSUE THREAD

**Issue by orwenxiang** [bitnami/containers#75873]
### Name and Version

bitnami/elasticsearch:8.15.5

### What is the problem this feature will solve?

Add bitnami/elasticsearch:8.15.5 version to matching spring boot 3.4.1 default reference version

### What is the feature you are proposing to solve the problem?

Add Elasticsearch 8.15.5 image version

**Comment by carrodher** [comment]
Could you please elaborate a bit more yon our request?

**Comment by orwenxiang** [comment]
Thanks for your response, we will keep 8.15.4 version or create it myself according this project.
