### ISSUE TITLE
[bitnami/harbor-adapter-trivy] Trivy adapter can't connect to port 6379

### ISSUE THREAD

**Issue by MayhemBill** [bitnami/containers#7848]
### Name and Version

docker.io/bitnami/harbor-adapter-trivy:2

### What steps will reproduce the bug?

run container

### What is the expected behavior?

it works

### What do you see instead?

dial tcp 127.0.0.1:6379: connect: connection refused

### Additional information

I have the container running in a docker compose with the rest of the harbor ecosystem, including the redis container, but it doesn't work. I am unsure why

**Comment by carrodher** [comment]
Could you check if the port is already in use by another container?

**Comment by MayhemBill** [comment]
the only container that is using the port is the redis container, which I believe is what the adapter is trying to connect to

**Comment by fmulero** [comment]
Hi @MayhemBill 

Please [refer to this documentation](https://github.com/aquasecurity/harbor-scanner-trivy/blob/main/README.md#configuration) to configure it properly. If you still having troubles please share your docker-compose.
