### ISSUE TITLE
Can not establish SSL connections with pgbouncer

### ISSUE THREAD

**Issue by juliansotoca** [bitnami/containers#8107]
### Name and Version

bitnami/pgbouncer:1.17.0-debian-11-r41

### What steps will reproduce the bug?

I used the container to connect to a Azure Postgresql Database with TLS enforced and it worked with the previous versions of the image.
I used these settings on the pgbouncer.ini:
```
server_tls_sslmode=verify-ca
server_tls_ca_file=/etc/ssl/certs/ca-certificates.crt
```
But now with the same config, it stopped working and I got this error message:
`WARNING TLS connect error: failed to load CA: No such file or directory`

This is because on line 62 of the Dockerfile (bitnami/pgbouncer/1/debian-11/Dockerfile) you are uninstalling the ca-certificates:
`apt-get autoremove --purge -y ca-certificates && \`

### What is the expected behavior?

PGbouncer can establish a connection with Azure Database over TLS.

### What do you see instead?
```
WARNING TLS connect error: failed to load CA: No such file or directory
```

**Comment by agomezmoron** [comment]
Hi @juliansotoca,

Thank you for filling the issue. The library was removed by error and we are working on restoring it back. I'll keep you posted.

Best

**Comment by carrodher** [comment]
There is a new revision (`1.17.0-debian-11-r43`) where the {{RUN apt-get autoremove --purge -y ca-certificates}} directive was removed from the _Dockerfile_, see https://github.com/bitnami/containers/pull/8114

Thanks again for letting us know
