### ISSUE TITLE
Phabricator missing

### ISSUE THREAD

**Issue by dev-clavis** [bitnami/containers#8177]
### Name and Version

bitnami/phabricator

### What steps will reproduce the bug?

Following the TL:DR steps on https://hub.docker.com/r/bitnami/phabricator will download an 404 and when searching on github it doesn't seem to exist.

### What is the expected behavior?

The repo or content of the docker-compose (https://raw.githubusercontent.com/bitnami/bitnami-docker-phabricator/master/docker-compose.yml) returns a 404

### What do you see instead?

Should return an docker-compose file or at least change the description on hub docker that it doesn't work anymore.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but as you can see in the README this image was deprecated, more or less a year ago.
  The image is kept in docker hub, but the related info in github was removed.

**Comment by dev-clavis** [comment]
Is there a specific reason to only remove it on github and not on both or couldn't it be left as archived repo ?
