### ISSUE TITLE
[bitnami/discourse] missing oxipng dependency

### ISSUE THREAD

**Issue by jgillich** [bitnami/containers#8668]
### Name and Version

bitnami/discourse:2.8.9

### What steps will reproduce the bug?

When uploading a image file, this error is emitted by sidekiq:
```
oxipng worker: `oxipng` not found; please provide proper binary or disable this worker (--no-oxipng argument or `:oxipng => false` through options)
```

The dependency on oxipng was added in https://github.com/discourse/discourse/commit/da9cd4f6928a36af77e98d0e44103d256d12bad5

oxipng is currently not packaged by debian. Not sure what's the best solution is here.

### What do you see instead?

-

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
