### ISSUE TITLE
[bitnami/apache] mod_ldap connect error - dependencies are missing for intranet services

### ISSUE THREAD

**Issue by gdraheim** [bitnami/containers#8822]
### Name and Version

bitnami/apache:2.4.54-debian-11-r27

### What steps will reproduce the bug?

1. we have closed environment without direct internet access 
2. the target server ssl certificate points OCSP to http://ocsp.globalsign.com/ca/dhltlscai5 
3. we have configured ldap for authnz
     LoadModule ldap_module modules/mod_ldap.so
     LoadModule authnz_ldap_module modules/mod_authnz_ldap.so

    <AuthnProviderAlias ldap ldap1>
     AuthLDAPURL "ldaps://ldap1.de:14636"
     AuthLDAPBindDN "uid=ldap1,ou=users,dc=crowd"
     AuthLDAPBindPassword xy
4. we find the ldap module to not be able to access the target ldap server
      > ....ent 172.17.0.1:35062] ldap_simple_bind() failed with server down (try 3)
     ...client 172.17.0.1:35062] AH01695: auth_ldap authenticate: user xx authentication failed; URI /arch [LDAP: ldap_simple_bind() failed][Can't contact LDAP server]
5. we find that ldapsearch (after apt-get install -y ldap-utils) shows the same problem
    > ldapsearch -H "ldaps://ldap1.de:19636 -d 225
    TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
ldap_msgfree
ldap_err2string
ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)`

However the ip connection to server and port work fine from the operating system level.

### What is the expected behavior?

 AH01617: user xy: authentication failure for "/arch/index.html": Password Mismatch

or any other authentication protocol diagnostic

### What do you see instead?

AH01695: auth_ldap authenticate: user xx authentication failed; URI /xyz [LDAP: ldap_simple_bind() failed][Can't contact LDAP server]

or more general: "Can't contact LDAP server". Using ldapsearch we were able to find a workaround.

### Additional information

we have found that reinstalling curl with all its dependencies solves the problems
   > apt -y install ca-certificates curl libbrotli1 libcurl4 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 openssl publicsuffix

Hint: it is not a misconfiguration problem in the apache conf or in the network path to the ldap server. After patching the docker image with the update packages the ldap configuration works fine.

**Comment by Mauraza** [comment]
Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. `curl` and some packages are not needed that’s why it was removed from the container.

You can use the `install_packages` script to install it if it is needed for your use case when creating your custom image based on Bitnami’s or using curl as part of any custom script.
