### ISSUE TITLE
[bitnami/apache] provide mod_auth_mellon

### ISSUE THREAD

**Issue by gdraheim** [bitnami/containers#8829]
### Name and Version

bitnami/apache:2.4.54-debian-11-r27

### What is the problem this feature will solve?

We want to interface with a keycloak based saml service.

We managed to create an apache conf for the redhat httpd docker image (rhlscl/httpd-24-rhel7) but we can not port it to the Bitnami helm chart deployment.

### What is the feature you are proposing to solve the problem?

We see that the bitnami/apache is based on Debian. That distro provides the mod_auth_mellon.so as an extra package

https://packages.debian.org/de/source/sid/libapache2-mod-auth-mellon

This should make it easy for upstream Bitnami docker images to make the same.

### What alternatives have you considered?

If Bitnami would use the standard Debian apt repositories then just running "apt install libapache2-mod-auth-mellon" would work.

However we find the Dockerfile in this project to point to some https://downloads.bitnami.com/files/stacksmith/apache-2.4.54-xxx archive which goes to setup some /opt path. As we can not find documentation how to patch a stacksmith installation, we are stuck here.

**Comment by javsalgar** [comment]
Hi,

I'm not entirely sure if the upstream debian package will be compatible, you could try placing the `.so` file in `/opt/bitnami/apache2/lib/`
