### ISSUE TITLE
[bitnami/apache] provide mod_dav_svn

### ISSUE THREAD

**Issue by gdraheim** [bitnami/containers#8830]
### Name and Version

bitnami/apache:2.4.54-debian-11-r27

### What is the problem this feature will solve?

We want to setup apache a subversion server.

We have an old setup based on mod_dav_svn on a VM but we can not port it to the Bitnami help chart deployment.

### What is the feature you are proposing to solve the problem?

We see that the bitnami/apache is based on Debian. That distro provides the mod_dav_svn as an extra package

https://packages.debian.org/de/sid/libapache2-mod-svn

This should make it easy for upstream Bitnami docker images to make the same.

### What alternatives have you considered?

If Bitnami would use the standard Debian apt repositories then just running "apt install libapache2-mod-svn" would work.

However we find the Dockerfile in this project to point to some https://downloads.bitnami.com/files/stacksmith/apache-2.4.54-xxx archive which goes to setup some /opt path. As we can not find documentation how to patch a stacksmith installation, we are stuck here.

**Comment by fmulero** [comment]
Hi @gdraheim, thanks a lot for using our images.

To be perfectly blunt, this topic doesn't have an easy answer. Our apache installation is compiled from source and any module used is also compiled. We don't plan to support mod_dav_svn in short term and we don't have in our roadmap moving to standard package for apache right now.

You can [extend our image](https://github.com/bitnami/containers/tree/main/bitnami/apache#customize-this-image) and compile the modules you need using for example apxs, [here](https://github.com/bitnami/bitnami-docker-apache/issues/100#issuecomment-616197340) an user described an example for `mod_aclr2`.
