### ISSUE TITLE
Curl package seem to be missing despite in Dockerfile

### ISSUE THREAD

**Issue by karthikgooner** [bitnami/containers#8952]
### Name and Version

bitnami/git:latest

### What steps will reproduce the bug?

Steps to reproduce: 

1. Run the container locally
2. run 
```
apt-get update
apt-get install sudo
sudo apt install -y python3
```
4. Try to download `kubectl` using `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"`

Error: 
```
root@41e5da64cb4c:/# curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
bash: curl: command not found
bash: curl: command not found
root@41e5da64cb4c:/# curl
bash: curl: command not found
root@41e5da64cb4c:/# apt-get install curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  curl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
```

### What is the expected behavior?

Until the last update, we did not face any problem with this image. `kubectl` was getting installed just fine

### What do you see instead?

Failing with `curl not found` error.

**Comment by recena** [comment]
@karthikgooner In this case where you need a customized image including tools like `kubectl` my suggestion is to build your own image based on the Bitnami ones.

**Comment by carrodher** [comment]
Please note `curl` was added back to the git container in https://github.com/bitnami/containers/pull/9875
