### ISSUE TITLE
[bitnami/harbor-jobservice]setup.sh: line 115: curl: command not found

### ISSUE THREAD

**Issue by geennuar** [bitnami/containers#8959]
### Name and Version

bitnami/harbor-jobservice:2.6

### What steps will reproduce the bug?

1.Deploy Harbor 2.6 by docker-compose freshly

### What is the expected behavior?

Everything goes fine.

### What do you see instead?
```
 09:42:29.42 
 09:42:29.43 Welcome to the Bitnami harbor-jobservice container
 09:42:29.43 Subscribe to project updates by watching https://github.com/bitnami/containers
 09:42:29.43 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 09:42:29.43 
 09:42:29.43 INFO  ==> ** Starting Harbor Job Service setup **
 09:42:29.44 INFO  ==> Validating Job Service settings...
 09:42:29.49 INFO  ==> No custom certificates were installed in the system
 09:42:29.50 INFO  ==> Waiting for Harbor Core to be started and ready
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
/opt/bitnami/scripts/harbor-jobservice/setup.sh: line 115: curl: command not found
 09:43:29.61 ERROR ==> Timeout waiting for Harbor Core to be available
```

**Comment by geennuar** [comment]
> 

Thanks very much for your information.

I  have no idea what's going on, but I don't think it makes sense to remove curl just for decreasing the image size, because harbor-jobservice  will not function rightly without curl, and it's not obvious for many newbies like me  to get in the container and then install curl manualy.

**Comment by yaakov-berkovitch** [comment]
We are failing on the same with the latest bitnami/python image available in docker hub. Is it something you are going to fix ?

**Comment by edeandrea** [comment]
I'm failing as well because of this (not this image, but in general).

**Comment by carrodher** [comment]
Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. `curl` is not needed in those container images you're mentioning, that's why was removed from the container. You can use the `install_packages` script to install it if it is needed for your use case.

**Comment by carrodher** [comment]
After a deep investigation, in the case of harbor-jobservice, we detected that `curl` is required by the application, so we will add it back to the container in the following release

**Comment by geennuar** [comment]
Thx

Carlos Rodríguez Hernández ***@***.***>于2022年10月7日 周五18:27写道：

**Comment by carrodher** [comment]
`curl` has been restored in harbor-jobservice in the new container image tagged as `2.6.0-debian-11-r15`, see https://github.com/bitnami/containers/pull/9464:
```diff
-RUN apt-get autoremove --purge -y curl && \
-    apt-get update && apt-get upgrade -y && \
+RUN apt-get update && apt-get upgrade -y && \
     apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
```
