### ISSUE TITLE
I can't restore a backup into a fresh Discourse instance.

### ISSUE THREAD

**Issue by jerrac** [bitnami/containers#9074]
### Name and Version

bitnami/discourse:2

### What steps will reproduce the bug?

I am using the [example docker-compose.yml](https://raw.githubusercontent.com/bitnami/containers/main/bitnami/discourse/docker-compose.yml) file. The only change is that I have set the `DISCOURSE_HOST` env var to `localhost` in order to run it locally and not run into CORS errors.

Once I log in, I immediately enable the `Allow restore, which can replace ALL site data! Leave disabled unless you plan to restore a backup` setting.

Then I go and upload my backup file in the Backup screen.

The file successfully uploads, but it never shows up in the Backup screen list. I even just left it running overnight to be sure.

Watching the logs, I always always see out this message shortly after uploading the file:

```
tmp-sidekiq-1     | 2022-10-06T03:33:36.957Z pid=1 tid=nxp class=Jobs::BackupChunksMerger jid=30713c04bc6a7f87b86fec61 ERROR: Job exception: No such file or directory @ rb_sysopen - /opt/bitnami/discourse/public/backups/default/tmp/624414820-sitename-2022-09-04-191921-v20211224011511targz/sitename-2022-09-04-191921-v20211224011511.tar.gz.part1
```

If I exec into the discourse container, I see this:

```
root@a4e14f7b36a3:/opt/bitnami/discourse/public/backups/default/tmp/624414820-sitename-2022-09-04-191921-v20211224011511targz# ls 
sitename-2022-09-04-191921-v20211224011511.tar.gz.part1	sitename-2022-09-04-191921-v20211224011511.tar.gz.part18  sitename-2022-09-04-191921-v20211224011511.tar.gz.part45  sitename-2022-09-04-191921-v20211224011511.tar.gz.part72
sitename-2022-09-04-191921-v20211224011511.tar.gz.part10	sitename-2022-09-04-191921-v20211224011511.tar.gz.part19  sitename-2022-09-04-191921-v20211224011511.tar.gz.part46  sitename-2022-09-04-191921-v20211224011511.tar.gz.part73
sitename-2022-09-04-191921-v20211224011511.tar.gz.part100	sitename-2022-09-04-191921-v20211224011511.tar.gz.part2   sitename-2022-09-04-191921-v20211224011511.tar.gz.part47  sitename-2022-09-04-191921-v20211224011511.tar.gz.part74
 ... truncated for brevity ...
sitename-2022-09-04-191921-v20211224011511.tar.gz.part17	sitename-2022-09-04-191921-v20211224011511.tar.gz.part44  sitename-2022-09-04-191921-v20211224011511.tar.gz.part71  sitename-2022-09-04-191921-v20211224011511.tar.gz.part99

```

If I make a backup with just one post, it works just fine.

But, after recreating a new instance, that tiny backup fails the same way as my larger one.

```
tmp-sidekiq-1     | 2022-10-06T03:31:26.819Z pid=1 tid=o11 class=Jobs::BackupChunksMerger jid=b9f7518fc9b1e5517decebc3 ERROR: Job exception: No such file or directory @ rb_sysopen - /opt/bitnami/discourse/public/backups/default/tmp/1196435-discourse-2022-10-06-032609-v20220920044310targz/discourse-2022-10-06-032609-v20220920044310.tar.gz.part1

```
```
root@a4e14f7b36a3:/opt/bitnami/discourse/public/backups/default/tmp/1196435-discourse-2022-10-06-032609-v20220920044310targz# ls
discourse-2022-10-06-032609-v20220920044310.tar.gz.part1

```

### What is the expected behavior?

The backup should show up and I should be able to restore it.

### What do you see instead?

Nothing.

### Additional information

I'm running these tests on PopOS 20.04. Docker 20.10.18.

Anyone have any ideas on how to fix this? I'm not a fan of how the official setup works. I was really hoping to replace it with Bitnami's version...

Thanks in advance!

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
