### ISSUE TITLE
[bitnami/keycloak] Image size doubled

### ISSUE THREAD

**Issue by madduci** [bitnami/containers#9468]
### Name and Version

bitnami/keycloak:19.0.3

### What steps will reproduce the bug?

In any environment, but also on DockerHub, a "docker pull" takes twice the space than the previous version (19.0.2). On Kubernetes this leads to timeout problems, since the default 2 Minutes are not respected

### What is the expected behavior?

The Image size is comparable to the previous one (19.0.2)

### What do you see instead?

The new image is almost 800 MB instead of ~400MB

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this.
  I am sorry, this is due to a bug in the docker file that is not removing the cached components (`/tmp/bitnami/pkg/cache/`).
  We are working to fix it.

**Comment by carrodher** [comment]
Thanks again for reporting this issue. We already applied a fix and released some new container images, please see below some examples obtained from [DockerHub](https://hub.docker.com/repository/docker/bitnami/keycloak/tags?page=1&ordering=last_updated):

- ✅ 19.0.2-debian-11-r7: 392.2 MB
- ✅ 19.0.2-debian-11-r7: 392.84 MB
- 🔴 19.0.3-debian-11-r0: 749.62 MB
- 🔴 19.0.3-debian-11-r1: 749.62 MB
- ✅ 19.0.3-debian-11-r2: 392.86 MB
- ✅ 19.0.3-debian-11-r3: 392.86 MB

The latest revisions of the container image are similar in size to the previous one.

**Comment by madduci** [comment]
many thanks @carrodher !
