### ISSUE TITLE
Drupal PostgreSQL Support

### ISSUE THREAD

**Issue by AtjonTV** [bitnami/containers#9469]
### Name and Version

bitnami/drupal:9.4.8-debian-11-r1

### What is the problem this feature will solve?

The Drupal image only allows to configure and use a MySQL or MariaDB Database.

### What is the feature you are proposing to solve the problem?

Extend the Chart to allow for both using MySQL/MariaDB or PostgreSQL. The official Drupal Docker container already has support for PostgreSQL, their work could be copied to some extend?

### What alternatives have you considered?

Deploying Drupal manually using Kubernetes Manifests with my existing Hosted PostgreSQL Service.

**Comment by rafariossaa** [comment]
Hi,
  Our image only support mysql at the moment as it is the [recommended](https://www.drupal.org/docs/system-requirements/database-server-requirements) database.
  I am creating an internal task to study this request. However, I can not provide an ETA.

**Comment by carrodher** [comment]
After internal analysis, we decided to continue with the current approach regarding the default database used by Drupal. Thanks for the suggestion.

In any way, PRs are welcome, just in case you would like to give a try by yourself. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
