### ISSUE TITLE
How to build a mariadb-galera image(arm64) with souce code?

### ISSUE THREAD

**Issue by huangyb520** [bitnami/containers#9472]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

We can compile  the source code for compatibility with different architectures（arm）。

### What is the feature you are proposing to solve the problem?

I need some help；

**Comment by fmulero** [comment]
Hi, we have created [this issue](https://github.com/bitnami/charts/issues/7305) that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.
