### ISSUE TITLE
opencve support

### ISSUE THREAD

**Issue by eviltik** [bitnami/containers#9473]
### Name and Version

opencve

### What is the problem this feature will solve?

There is no opencve bitnami docker image available.

### What is the feature you are proposing to solve the problem?

Consider a docker image for opencve

https://github.com/opencve/opencve-docker

### What alternatives have you considered?

Use original opencve docker image

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the product request! We will forward this for evaluation.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Comment by eviltik** [comment]
I just finished my own opencve like (but using nvd api v2), nodejs + mongo stack. 

Note that opencve itself require a full rewrite for using nvd api v2, so yes, it's not the time to make effort for a bitnami container.

Thank you !
