### ISSUE TITLE
non-root images but the unprivileged user in root group

### ISSUE THREAD

**Issue by Cronist** [bitnami/containers#9485]
### Name and Version

bitnami/postgresql:latest AND bitnami/mongodb:5.0 AND bitnami/redis:7.0.5

### What steps will reproduce the bug?
```
$ docker exec -it postgres id
uid=1001 gid=0(root) groups=0(root)
```
### What is the expected behavior?
```
$ docker exec -it postgres id
uid=1001 gid=1001(something except root) groups=1001(something except root)
```
### What do you see instead?
```
$ docker exec -it postgres id
uid=1001 gid=0(root) groups=0(root)
```
### Additional information

all the users running the containers are in root groups, so all the security scanners are alarming and marking the containers as NOT non-root. The security teams are unable to use these images because of this.

could you please add the users to a group that you created just before adding the user? Of course, some tests will be needed to do because the permissions of the new group will not be enough.

Until this will happen security groups are not able call these images non-root and secure. How can you help us?

**Comment by carrodher** [comment]
Bitnami images are configured with the proper permissions for the user and group in order to meet the requirements of platforms working with arbitrary UUIDs such as OpenShift. They do this by ensuring that the XXX user (1001 for instance) belongs to the _root_ group and that the directories have the appropriate read, write and execution permissions.

You can find more information about how Bitnami configures the non-root containers in the following articles:
- https://docs.bitnami.com/tutorials/work-with-non-root-containers
- https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security
- https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/

**Comment by Cronist** [comment]
Thank you so much. But it would be better if the users would be in another group rather than root group.

**Comment by ctmbl** [comment]
Hey I don't know if I can re-open this issue but I'd like an explanation about this unprivileged user belonging to the root group. I personally use the `bitnami/mongodb` image but this is similar.

I totally got why the container is run as a non-root user and why making it belonging to the root group can be a necessity for some directory/file access. 
However, doesn't it present a big vulnerability and also totally (or partially?) take down the protection given by the unprivileged user? 
I'm maybe missing something here but I can totally do:
```
$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS         PORTS                                                  NAMES
37139e55f4f4   bitnami/mongodb:latest   "/opt/bitnami/script…"   11 minutes ago   Up 9 minutes   0.0.0.0:3002->3002/tcp, :::3002->3002/tcp, 27017/tcp   mongodb-1
$ docker exec -it mongodb-1 bash
I have no name!@37139e55f4f4:/$ rm -rf --no-preserve-root /
```
And it totally destroy my container, so what prevents an attacker that would gain access to my DB container to completely wipe it?

**Comment by rafariossaa** [comment]
> And it totally destroys my container, so what prevents an attacker that would gain access to my DB container to completely wipe it? Nothing I guess, even without this root group they could delete my db but not the whole container.

Destroying a container it is not a problem. They are immutable, so you could rerun it again a you would have the very same as before the incident. However, you could lose your data, so backup are always recommended.

> So what are the real risks/advantages of making this user belonging to the root group? Does it totally prevent container escape? Or is it "just better than running as root but not perfect"?

The advantage is that you have better isolation. If by "container escape" you mean running a process in the host, this is something managed at docker and kernel level, so depending on the bug that would allow that maybe it is important the user that run the process inside the container, or maybe not.

Running process with a non-root user is better. 

Maybe you would like to take a look to the links @carrodher provided for further information.

**Comment by ctmbl** [comment]
@rafariossaa Thanks for your answer but I think it doesn't entirely address my question :confused: 

> Destroying a container it is not a problem. They are immutable, so you could rerun it again a you would have the very same as before the incident. However, you could lose your data, so backup are always recommended.

Yes I was worried about the data loss but ofc even without the user belonging to root group an attacker could destroy the data so I now clearly see the need of backup.

> The advantage is that you have better isolation. If by "container escape" you mean running a process in the host, this is something managed at docker and kernel level, so depending on the bug that would allow that maybe it is important the user that run the process inside the container, or maybe not.

I totally agree on the better isolation, and yes running a process in the host was what I meant. 
You're also right pointing out that it heavily depends on the bug used, some "container escape" techniques might need a root user some might not depend on the user at all.

Specifically my most important question was:
"Doesn't it present a big vulnerability to have the user belonging to the root group and also totally (or partially?) take down the "protection" given by the unprivileged user?"

I'm, for sure, missing something but it seems a bit odd to me to use a non-root user **that belongs to the root group**.

Once again tks for your reply and your time!

**Comment by rafariossaa** [comment]
The GID `0` has not any special privilege, it is not as being UID `0` that has special treatment on the kernel side. So, apart of reaching files in the filesystem, there is not risk of privileges escalation because of this.

There are some guidelines on how to create non-root images from RedHat that includes this topic.
- https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html
- https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids
