### ISSUE TITLE
[bitnami/postgresql] Logs on custom scripts located at docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#9797]
### Name and Version

bitnami/postgres:19

### What is the problem this feature will solve?

SQL scripts contain RAISE NOTICE but nothing in logs.
No logs in sdtout or anywhere.

### What is the feature you are proposing to solve the problem?

add redirect to postgres.log

**Example :**
`psql --log-file=plog.log -f file.sql  >clog.log 2>&1`****

**Comment by siddjellali** [comment]
**For instance**

```
DO
$do$
BEGIN
    IF NOT EXISTS ( SELECT FROM pg_user WHERE usename = 'b_keycloak')
    THEN
      CREATE ROLE b_keycloak WITH
      LOGIN
      NOSUPERUSER
      INHERIT
      CREATEDB
      NOCREATEROLE
      NOREPLICATION
      ENCRYPTED PASSWORD 'xxxxxxxxxxxxxxxxx';
      RAISE NOTICE ''USER CREATED'';
   ELSE
    RAISE NOTICE ''USER EXISTS'';
    END IF;
END
$do$; 
```

**Comment by fmulero** [comment]
Hi @siddjellali 

You can place your own `.sh` script in `/docker-entrypoint-initdb.d` to initialise the database and redirect the output where you need.  If you'd like to change the behaviour of the [init scripts  function](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L692-L721) The Bitnami team will be happy to review any PR and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
