### ISSUE TITLE
[bitnami/nginx-ingress-controller] ModSecurity audit logs are not configured like the official image

### ISSUE THREAD

**Issue by maxbrunet** [bitnami/containers#980]
The official documentation states the following:

> > Due to the value of the setting [SecAuditLogType=Concurrent](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secauditlogtype) the ModSecurity log is stored in multiple files inside the directory `/var/log/audit`. The default `Serial` value in SecAuditLogType can impact performance.

https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/

It does not seem to be the case in the Bitnami image:

```shell
$ docker run --rm -ti --entrypoint= \
    quay.io/bitnami/nginx-ingress-controller:1.0.4-debian-10-r8 \
    grep -E '^(SecAuditLogType|SecAuditLogStorageDir)' /etc/nginx/modsecurity/modsecurity.conf
SecAuditLogType Serial
```

In the official image:

```shell
$ docker run --rm -ti --entrypoint= \
    k8s.gcr.io/ingress-nginx/controller:v1.0.4 \
    grep -E '^(SecAuditLogType|SecAuditLogStorageDir)' /etc/nginx/modsecurity/modsecurity.conf
SecAuditLogType Concurrent
SecAuditLogStorageDir /var/log/audit/
```

The change appear to be made by this script upstream:
https://github.com/kubernetes/ingress-nginx/blob/af7d9581f47113f4e2cfd7fac92ba02ae9cd49f0/images/nginx/rootfs/build.sh#L550-L554

It would be nice to have this discrepancy corrected in both the 0.x and 1.x Bitnami images.

**Comment by aoterolorenzo** [comment]
@maxbrunet this issue has been now addressed within the latest container's release [1.3.1-debian-11-r1](https://hub.docker.com/layers/bitnami/nginx-ingress-controller/latest/images/sha256-2f8b68b0b94696e85174da2b18bc5de4d711a01b83d8c8c4398fd7ed48f9f94f?context=explore) and it is available also in the latest chart's release [9.3.7](https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller).
