### ISSUE TITLE
[bitnami/joomla] Joomla PostgreSQL Support

### ISSUE THREAD

**Issue by AtjonTV** [bitnami/containers#9803]
### Name and Version

bitnami/joomla:4.2.3-debian-11-r4

### What is the problem this feature will solve?

The Joomla image only allows to configure and use a MySQL or MariaDB Database.

### What is the feature you are proposing to solve the problem?

Extend the Chart to allow for both using MySQL/MariaDB or PostgreSQL.

It looks like the official Joomla Docker container will receive support for PostgreSQL soon: https://github.com/joomla-docker/docker-joomla/issues/42
 Their work could be copied to some extent?

### What alternatives have you considered?

None, as the official Joomla Docker container is still missing support.

**Comment by javsalgar** [comment]
Hi!

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
