### ISSUE TITLE
[bitnami/mediawiki] cannot connect database

### ISSUE THREAD

**Issue by dungsil** [bitnami/containers#9807]
### Name and Version

bitnami/mediawiki:1.38.4

### What steps will reproduce the bug?

**Dockerfile**:
```Dockerfile
FROM bitnami/mediawiki:1.38.4
```

1. Run command
```
$ docker run docker run -e MEDIAWIKI_DATABASE_HOST=ap-northeast.connect.psdb.cloud -e MEDIAWIKI_DATABASE_NAME=xxxx -e MEDIAWIKI_DATABASE_PASSWORD=xxxx -e MEDIAWIKI_DATABASE_USER=xxxx wiki
```

3. not connect database

### What is the expected behavior?

working normal

### What do you see instead?

```
mediawiki 12:18:13.09 Welcome to the Bitnami mediawiki container
mediawiki 12:18:13.09 Subscribe to project updates by watching https://github.com/bitnami/containers
mediawiki 12:18:13.09 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mediawiki 12:18:13.09 
mediawiki 12:18:13.10 INFO  ==> ** Starting MediaWiki setup **
realpath: /bitnami/apache/conf: No such file or directory
mediawiki 12:18:13.22 INFO  ==> Configuring Apache ServerTokens directive
mediawiki 12:18:13.35 INFO  ==> Configuring PHP options
mediawiki 12:18:13.35 INFO  ==> Setting PHP expose_php option
mediawiki 12:18:13.52 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
mediawiki 12:18:13.66 INFO  ==> Configuring file permissions for MediaWiki
mediawiki 12:18:13.68 INFO  ==> Trying to connect to the database server
mediawiki 12:19:18.00 ERROR ==> Could not connect to the database
```

### Additional information

**OS:** Windows 10 Pro 20H2 19042.2006 / Windows Feature Experience Pack 120.2212.4180.0
**Docker engine:** v20.10.17, build 100c701

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/mediawiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
