### ISSUE TITLE
No suitable driver found for jdbc:postgresql on bitnami/keycloak:18.0.2-debian-11-r3 and bitnami/keycloak:18.0.2-debian-11-r4

### ISSUE THREAD

**Issue by EStork09** [bitnami/containers#983]
### Name and Version

bitnami/keycloak:18.0.2-debian-11-r3

### What steps will reproduce the bug?

1. Running in the kubernetes environment with the 9.4.0 helm chart
2. Using the config with the standalone postgresql db
3. With image bitnami/keycloak:18.0.2-debian-11-r3 (and also bitnami/keycloak:18.0.2-debian-11-r4)
4. We see this error "No suitable driver found for jdbc:postgresql://keycloak-postgresql:5432/bitnami_keycloak?currentSchema=public" and the container fails to start

### What is the expected behavior?

keycloak should start up and pass healthchecks

### What do you see instead?

No suitable driver found for jdbc:postgresql://keycloak-postgresql:5432/bitnami_keycloak?currentSchema=public

### Additional information

We rolled back to r0 for the time being, but it looks like the driver got removed in the newer versions?

**Comment by alemorcuq** [comment]
Would you like to contribute with a PR, @tamcore ?
