### ISSUE TITLE
[bitnami/keycloak] Prepended extra startup args

### ISSUE THREAD

**Issue by Tasyp** [bitnami/containers#9840]
### Name and Version

bitnami/keycloak:19.0.3-debian-11-r1

### What is the problem this feature will solve?

Keycloak has gone through multiple updates this year. They have changed some behavior that can be only enabled back using special flags (For example, redirect_uri param which was discussed in this [issue](https://github.com/bitnami/containers/issues/1047))

The command with such a flag should look like the following:
```
bin/kc.sh --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start-dev
```

The issue is that bitnami keycloak docker image doesn't allow to prepend such flags _before_ the start command.

That's what is used as a start command in the image:
```
start_command=("${KEYCLOAK_BIN_DIR}/kc.sh" "-cf" "$conf_file" "$start_param")
```
We can only _append_ flags after the start command using `KEYCLOAK_EXTRA_ARGS` env variable.

### What is the feature you are proposing to solve the problem?

Let's add KEYCLOAK_EXTRA_ARGS_PREPEND env variable or something similar which would allow adding some arbitrary flags before the start command. If it sounds like a sensible proposition, I can create a PR that adds such behaviour.

### What alternatives have you considered?

One could utilize the custom configuration env variable to enable such behavior. However, I think it's not convenient because you lose the benefits of autogenerated configs which you have to maintain now. The new env variable sounds like an elegant solution for flags that enable backward-compatible behavior that will be removed anyway after a few keycloak upgrades.

**Comment by fmulero** [comment]
Hi @Tasyp for opening this issue, I've got your point.

Our capacity is limited and we can't give you any ETA. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Tasyp** [comment]
@fmulero Sure thing! I have opened a PR to add this feature: https://github.com/bitnami/containers/pull/10071
