### ISSUE TITLE
[bitnami/minio] Support for prefixing console with reverse proxy path

### ISSUE THREAD

**Issue by siddjellali** [bitnami/containers#9852]
### Name and Version

bitnami/minio@2022

### What is the problem this feature will solve?

I'm looking to see if its possible to have my minio instance behind a reverse proxy, both the server and the console, at the same domain.
I'd like to have my server available at https://minio.example.com/api/, and the console at https://minio.example.com/s3/.

### What is the feature you are proposing to solve the problem?

Add new environment variable `CONSOLE_SUBPATH`

from [#1247](https://github.com/minio/console/pull/1247)

**Comment by fmulero** [comment]
Hi @siddjellali, thanks for opening this issue

Have you tried to use it directly in deployment? It seems that env var is directly [read by minio](https://github.com/minio/console/pull/1247/files#diff-c19cd4cafc902f9abd3a30f1a4e167b5193d5135e2bec0357d42f57f98eb5beaR355)

**Comment by siddjellali** [comment]
[#15859](https://github.com/minio/minio/issues/15859 )

Thanks
