### ISSUE TITLE
Solr exits on second start of container (with docker-compose)

### ISSUE THREAD

**Issue by rosenbjerg** [bitnami/containers#986]
When starting the bitnami/solr container for the second time with docker-compose, it fails with:
`Port 8983 is already being used by another process (pid: 88)`

**Steps to reproduce the issue:**

1. Start bitnami/solr container with `docker-compose up`
`docker-compose.yml` file used:
```yaml
version: '3.5'

services:
  bitnami-solr:
    image: bitnami/solr:8
```
2. Stop container (eg. with Ctrl+C)
3. Restart container with `docker-compose up`

**Describe the results you received:**

On the very first startup, the solr instance starts up correctly and the container keeps running.
On second startup, the solr process is unable to use the same port again, probably because another instance of solr is running in the background and using that port.
The solr instance then exits with exit-code 1, and the container does the same. To be able to start a working solr container, I have to delete the existing container (i.e. with `docker-compose down`) and then start again. 
![image](https://user-images.githubusercontent.com/11181960/143776179-7242470d-3410-48f1-be75-74bbd33e6175.png)

**Describe the results you expected:**

I expect the container-image to be set up to allow for restarting an existing stopped container.
This problem seems to be caused by the ENTRYPOINT or CMD isn't properly handling that solr is already running in the background.
It may also be a mistake that solr is installed as a background service that automatically starts, since the ENTRYPOINT/CMD normally is supposed to be responsible for starting the "main" process of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

I can reproduce the error consistently with this extremely minimal docker-compose file.

Interestingly, sometimes the second startup will succeed and it will then fail on the third startup instead. I think this has to do with how quickly the container is stopped after startup. 

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:47:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 8
  Running: 5
  Paused: 0
  Stopped: 3
 Images: 17
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24.99GiB
 Name: docker-desktop
 ID: GIQ4:NRXM:3EIE:WBFD:CUTU:CMIW:T7GJ:VCKM:O3I7:IBBK:SJXR:4BM4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.1.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Unfortunately, this issue was created a year ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this year, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by nazerise** [comment]
I add this script to preStop in helm chart to stop solr gracefully 
#!/bin/bash
SOLR_PID=$(ps aux | grep 8983 | grep -v grep | awk '{print $2}')
SOLR_JAVA_HOME=$JAVA_HOME
DIR="/opt/bitnami/solr/server"
STOP_KEY="solrrocks"
SOLR_PID_DIR="/opt/bitnami/solr/tmp"
JAVA="$JAVA_HOME/bin/java"
JSTACK="$JAVA_HOME/bin/jstack"
JATTACH="$(command -v jattach)"
stop_solr() {

  DIR="$1"
  SOLR_PORT="$2"
  THIS_STOP_PORT="${STOP_PORT:-$((SOLR_PORT - 1000))}"
  STOP_KEY="$3"
  SOLR_PID="$4"

  if [ -n "$SOLR_PID"  ]; then
	 echo $SOLR_PID
    echo -e "Sending stop command to Solr running on port $SOLR_PORT ... waiting up to $SOLR_STOP_WAIT seconds to allow Jetty process $SOLR_PID to stop gracefully."
    # shellcheck disable=SC2086
    /opt/bitnami/java/bin/java  -jar /opt/bitnami/solr/server/start.jar STOP.PORT=8983 STOP.KEY=solrrocks --stop || true
      (loops=0
      while true
      do
        # Check if a process is running with the specified PID.
        # -o stat will output the STAT, where Z indicates a zombie
        # stat='' removes the header (--no-headers isn't supported on all platforms)
        # Note the space after '$('. It is needed to avoid confusion with special bash eval syntax
        STAT=$( (ps -o stat='' -p "$SOLR_PID" || :) | tr -d ' ')
        if [[ "${STAT:-Z}" != "Z" ]]; then
          slept=$((loops * 2))
          if [ $slept -lt $SOLR_STOP_WAIT ]; then
            sleep 2
            loops=$((loops+1))
          else
            exit # subshell!
          fi
        else
          exit # subshell!
        fi
      done) &
    rm -f "$SOLR_PID_DIR/solr-$SOLR_PORT.pid"
  else
    echo -e "No Solr nodes found to stop."
    exit 0
  fi

  # Note the space after '$('. It is needed to avoid confusion with special bash eval syntax
  STAT=$( (ps -o stat='' -p "$SOLR_PID" || :) | tr -d ' ')
  if [[ "${STAT:-Z}" != "Z" ]]; then
    if [ -n "${JSTACK:-}" ]; then
      echo -e "Solr process $SOLR_PID is still running; jstacking it now."
      $JSTACK "$SOLR_PID"
    elif [ "$JATTACH" != "" ]; then
      echo -e "Solr process $SOLR_PID is still running; jattach threaddumping it now."
      $JATTACH "$SOLR_PID" threaddump
    fi
    echo -e "Solr process $SOLR_PID is still running; forcefully killing it now."
    kill -9 "$SOLR_PID"
    echo "Killed process $SOLR_PID"
    rm -f "$SOLR_PID_DIR/solr-$SOLR_PORT.pid"
    sleep 10
  fi

  # Note the space after '$('. It is needed to avoid confusion with special bash eval syntax
  STAT=$( (ps -o stat='' -p "$SOLR_PID" || :) | tr -d ' ')
  if [ "${STAT:-}" == "Z" ]; then
    # This can happen if, for example, you are running Solr inside a docker container with multiple processes
    # rather than running it is as the only service. The --init flag on docker avoids that particular problem.
    echo -e "Solr process $SOLR_PID has terminated abnormally. Solr has exited but a zombie process entry remains."
    exit 1
  elif [ -n "${STAT:-}" ]; then
    echo "ERROR: Failed to kill previous Solr Java process $SOLR_PID ... script fails."
    exit 1
  fi
} # end stop_solr

stop_solr $DIR $SOLR_PORT_NUMBER $STOP_KEY $SOLR_PID

**Comment by nazerise** [comment]
I added a script to preStop in kubernetes to kill solr gracefully and it solved this problem
you can see the script here:
https://github.com/nazerise/solr/blob/main/templates/kill-solr.yaml
