### ISSUE TITLE
wordpress_initialize is not atomic

### ISSUE THREAD

**Issue by jfcoz** [bitnami/containers#988]
**Description**

During persistence initialization, if the copy is too long and is killed by the container startupProbe, at next start the wordpress_initialize function do not detect a partially initialized directory

**Steps to reproduce the issue:**

1. Build a custom image, adding big custom plugins
2. helm install …
3. StartupProbe will restart container
4. after the restart, the entrypoint will start Apache with a partialy initialized persisent directory

**Describe the results you received:**

Errors on Wordpress due to missing plugins

**Describe the results you expected:**

Atomicity of the wordpress_initialize, for example creating `.wordpress_initialize` file in the volume at the end of the function, and checking the file existence to detect fully initalized persisent volume.

**Workaround:**

Increase startupProbe failureThreshold

**Comment by carrodher** [comment]
Due to other priorities the team has and the limited scope of this issue which only appears under certain situations, it is not possible for us to work on it in the short/mid term.
