### ISSUE TITLE
Container logic restricts unprivileged ports

### ISSUE THREAD

**Issue by helvetia007** [bitnami/containers#989]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

Set your OpenLDAP to listen to official 636 port
Drops message about a privileged port

### What is the expected behavior?

Has to work and not drop a message. There are 0 reasons for this behaviour. Container scripts should be smarter and see if privileged port parameter has been overidden. 

### What do you see instead?

Error in container log about privileged port use

### Additional information

1. Docker allows non-root containers to use privileged ports with flag --sysctl net.ipv4.ip_unprivileged_port_start=0 .
2. Makes no sense to use container port 2636 and expose as 636 because in such case REPLICATION does not work due to wrong URI's. Repl target can't be ending with 636 when the actual daemon is listening on URI ending with 2636.
3. There is no reason to implement such logic in scripts as it highly limits the usage. There is no issue in setting minimum privileged port on non-root containers to 0 instead of 1024.

**Comment by timothylcooke** [comment]
We're experiencing the same issue with `docker.io/bitnami/wordpress:6`.

After setting environment variable `APACHE_HTTPS_PORT_NUMBER=443`, we get the message `ERROR ==> An invalid port was specified in the environment variable APACHE_HTTPS_PORT_NUMBER: privileged port requested.`

**Comment by rafariossaa** [comment]
Hi @helvetia007 , 
  I am taking a look to this issue, could you share how are you configuring replication ? I would like to create a similar scenario on my side and find a fix for this.

**Comment by helvetia007** [comment]
> Hi @helvetia007 , I am taking a look to this issue, could you share how are you configuring replication ? I would like to create a similar scenario on my side and find a fix for this.

Hi @rafariossaa  . For various privacy reasons I am unable to share my document. However, I can suggest to simply try and setup a basic replication between 2 servers. Try to run both servers on non-standard ports, above 1024. And there is simply no way to do a replication. You will encounter my original issue described at the top. 

What I did - I had a look at your scripts, made a change and then mounted my version to go over this bug.

**Comment by helvetia007** [comment]
@rafariossaa  it's been a little while since I been dealing with this original issue. But I don't think you need to setup replication in order to test privileged port issue. Try to reproduce the issue by making OpenLDAP to listen to ports below 1024. You will get an error which comes from some container script. This is what need's to be fixed. I will share some pieces from my own documentation.

Looking at my own resolution, I did 2 fixes:
1. Fixing a bug in run.sh . I added this line there so it listens to correct URI. Any other URI makes replication fail.
is_boolean_yes "$LDAP_ENABLE_TLS" && flags=("-h" "ldap://$LDAP_C_HOSTNAME:${LDAP_PORT_NUMBER}/ ldaps://$LDAP_C_HOSTNAME:${LDAP_LDAPS_PORT_NUMBER}/ ldapi:///")
Full paste below of lines around it so you can locate this in original file.
ulimit -n "$LDAP_ULIMIT_NOFILES"

flags=("-h" "ldap://:${LDAP_PORT_NUMBER}/ ldapi:///")

# Add LDAPS URI when TLS is enabled
is_boolean_yes "$LDAP_ENABLE_TLS" && flags=("-h" "ldap://$LDAP_C_HOSTNAME:${LDAP_PORT_NUMBER}/ ldaps://$LDAP_C_HOSTNAME:${LDAP_LDAPS_PORT_NUMBER}/ ldapi:///")

# Add "@" so users can add extra command line flags
flags+=("-F" "${LDAP_CONF_DIR}/slapd.d" "-d" "256" "$@")


2. In libvalidations.sh i made below change. You can find the lines in your original file by searching "privileged port requested"
        elif [[ "$value" -gt 65535 ]]; then
            echo "requested port is greater than 65535"
            return 2
        elif [[ "$unprivileged" = 1 && "$value" -lt $LDAPC_MINPRIVPORT ]]; then
            echo "privileged port requested"
            return 3

**Comment by rafariossaa** [comment]
Have into account that for security reasons, the user that runs the service in our containers is always an unprivileged user (aka non-root containers). This is also a requirement to run images in openshift environments.

I changed the Dockerfile to build my own image that allows privileged port usage by changing the `USER`, but no other changes to the files were added.


```
$ cat Dockerfile

FROM docker.io/bitnami/minideb:bullseye

ARG TARGETARCH

LABEL org.opencontainers.image.authors="https://bitnami.com/contact" \
      org.opencontainers.image.description="Application packaged by Bitnami" \
      org.opencontainers.image.ref.name="2.6.3-debian-11-r46" \
      org.opencontainers.image.source="https://github.com/bitnami/containers/tree/main/bitnami/openldap" \
      org.opencontainers.image.title="openldap" \
      org.opencontainers.image.vendor="VMware, Inc." \
      org.opencontainers.image.version="2.6.3"

ENV HOME="/" \
    OS_ARCH="${TARGETARCH:-amd64}" \
    OS_FLAVOUR="debian-11" \
    OS_NAME="linux"

COPY prebuildfs /
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# Install required system packages and dependencies
RUN install_packages ca-certificates curl libcom-err2 libcrypt1 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libltdl7 libnsl2 libnss3-tools libodbc1 libperl5.32 libsasl2-2 libssl1.1 libtirpc3 libwrap0 mdbtools procps psmisc
RUN mkdir -p /tmp/bitnami/pkg/cache/ && cd /tmp/bitnami/pkg/cache/ && \
    COMPONENTS=( \
      "openldap-2.6.3-6-linux-${OS_ARCH}-debian-11" \
      "gosu-1.14.0-155-linux-${OS_ARCH}-debian-11" \
    ) && \
    for COMPONENT in "${COMPONENTS[@]}"; do \
      if [ ! -f "${COMPONENT}.tar.gz" ]; then \
        curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O ; \
        curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O ; \
      fi && \
      sha256sum -c "${COMPONENT}.tar.gz.sha256" && \
      tar -zxf "${COMPONENT}.tar.gz" -C /opt/bitnami --strip-components=2 --no-same-owner --wildcards '*/files' && \
      rm -rf "${COMPONENT}".tar.gz{,.sha256} ; \
    done
RUN apt-get autoremove --purge -y curl && \
    apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
RUN chmod g+rwX /opt/bitnami

COPY rootfs /
RUN /opt/bitnami/scripts/openldap/postunpack.sh
ENV APP_VERSION="2.6.3" \
    BITNAMI_APP_NAME="openldap" \
    PATH="/opt/bitnami/openldap/bin:/opt/bitnami/openldap/sbin:/opt/bitnami/common/bin:$PATH"

EXPOSE 1389 1636

#USER 1001
USER 0
ENTRYPOINT [ "/opt/bitnami/scripts/openldap/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/openldap/run.sh" ]
```

build the image:
```
$ docker build -t myldap:v1 -f Dockerfile .

Sending build context to Docker daemon    130kB
Step 1/17 : FROM docker.io/bitnami/minideb:bullseye
 ---> ee9558d6f35f
Step 2/17 : ARG TARGETARCH

...


Successfully built 324cffdfda8c
Successfully tagged myldap:v1
````

Then, changed `docker-compose.yaml` to modify the ports, and the image.
```
$ cat docker-compose.yml
version: '2'

services:
  openldap:
    image:  myldap:v1
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_PORT_NUMBER=389
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local

```


Now, if you run `docker-compose  up`, you could check that process is listening to port `389`.
```
$ docker exec -it debian-11_openldap_1 ps -eo uid,user,args
  UID USER     COMMAND
 1000 slapd    /opt/bitnami/openldap/sbin/slapd -u slapd -h ldap://:389/ ldapi:/
    0 root     ps -eo uid,user,args
```

and from outside the container, form the host, I could search by using:
```
$ ldapsearch -x -b "dc=example,dc=org" -H ldap://localhost:389 'dn'


# extended LDIF
#
# LDAPv3
# base <dc=example,dc=org> with scope subtree
# filter: (objectclass=*)
# requesting: dn 
#

# example.org
dn: dc=example,dc=org

# users, example.org
dn: ou=users,dc=example,dc=org

# user01, users, example.org
dn: cn=user01,ou=users,dc=example,dc=org

# user02, users, example.org
dn: cn=user02,ou=users,dc=example,dc=org

# readers, users, example.org
dn: cn=readers,ou=users,dc=example,dc=org

# search result
search: 2
result: 0 Success

# numResponses: 6
# numEntries: 5
```

**Comment by helvetia007** [comment]
> Have into account that for security reasons, the user that runs the service in our containers is always an unprivileged user (aka non-root containers). This is also a requirement to run images in openshift environments.
> 
> I changed the Dockerfile to build my own image that allows privileged port usage by changing the `USER`, but no other changes to the files were added.
> 
> ```dockerfile
> FROM docker.io/bitnami/minideb:bullseye
> 
> ARG TARGETARCH
> 
> LABEL org.opencontainers.image.authors="https://bitnami.com/contact" \
>       org.opencontainers.image.description="Application packaged by Bitnami" \
>       org.opencontainers.image.ref.name="2.6.3-debian-11-r46" \
>       org.opencontainers.image.source="https://github.com/bitnami/containers/tree/main/bitnami/openldap" \
>       org.opencontainers.image.title="openldap" \
>       org.opencontainers.image.vendor="VMware, Inc." \
>       org.opencontainers.image.version="2.6.3"
> 
> ENV HOME="/" \
>     OS_ARCH="${TARGETARCH:-amd64}" \
>     OS_FLAVOUR="debian-11" \
>     OS_NAME="linux"
> 
> COPY prebuildfs /
> SHELL ["/bin/bash", "-o", "pipefail", "-c"]
> # Install required system packages and dependencies
> RUN install_packages ca-certificates curl libcom-err2 libcrypt1 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libltdl7 libnsl2 libnss3-tools libodbc1 libperl5.32 libsasl2-2 libssl1.1 libtirpc3 libwrap0 mdbtools procps psmisc
> RUN mkdir -p /tmp/bitnami/pkg/cache/ && cd /tmp/bitnami/pkg/cache/ && \
>     COMPONENTS=( \
>       "openldap-2.6.3-6-linux-${OS_ARCH}-debian-11" \
>       "gosu-1.14.0-155-linux-${OS_ARCH}-debian-11" \
>     ) && \
>     for COMPONENT in "${COMPONENTS[@]}"; do \
>       if [ ! -f "${COMPONENT}.tar.gz" ]; then \
>         curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O ; \
>         curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O ; \
>       fi && \
>       sha256sum -c "${COMPONENT}.tar.gz.sha256" && \
>       tar -zxf "${COMPONENT}.tar.gz" -C /opt/bitnami --strip-components=2 --no-same-owner --wildcards '*/files' && \
>       rm -rf "${COMPONENT}".tar.gz{,.sha256} ; \
>     done
> RUN apt-get autoremove --purge -y curl && \
>     apt-get update && apt-get upgrade -y && \
>     apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
> RUN chmod g+rwX /opt/bitnami
> 
> COPY rootfs /
> RUN /opt/bitnami/scripts/openldap/postunpack.sh
> ENV APP_VERSION="2.6.3" \
>     BITNAMI_APP_NAME="openldap" \
>     PATH="/opt/bitnami/openldap/bin:/opt/bitnami/openldap/sbin:/opt/bitnami/common/bin:$PATH"
> 
> EXPOSE 1389 1636
> 
> #USER 1001
> USER 0
> ENTRYPOINT [ "/opt/bitnami/scripts/openldap/entrypoint.sh" ]
> CMD [ "/opt/bitnami/scripts/openldap/run.sh" ]
> ```
> 
> build the image:
> 
> ```
> $ docker build -t myldap:v1 -f Dockerfile .
> Sending build context to Docker daemon    130kB
> Step 1/17 : FROM docker.io/bitnami/minideb:bullseye
>  ---> ee9558d6f35f
> Step 2/17 : ARG TARGETARCH
> ...
> Successfully built 324cffdfda8c
> Successfully tagged myldap:v1
> ```
> 
> Then, changed `docker-compose.yaml` to modify the ports, and the image.
> 
> ```yaml
> version: '2'
> 
> services:
>   openldap:
>     image:  myldap:v1
>     ports:
>       - '389:389'
>       - '636:636'
>     environment:
>       - LDAP_ADMIN_USERNAME=admin
>       - LDAP_ADMIN_PASSWORD=adminpassword
>       - LDAP_USERS=user01,user02
>       - LDAP_PASSWORDS=password1,password2
>       - LDAP_PORT_NUMBER=389
>     volumes:
>       - 'openldap_data:/bitnami/openldap'
> 
> volumes:
>   openldap_data:
>     driver: local
> ```
> 
> Now, if you run `docker-compose up`, you could check that process is listening to port `389`.
> 
> ```
> $ docker exec -it debian-11_openldap_1 ps -eo uid,user,args
>   UID USER     COMMAND
>  1000 slapd    /opt/bitnami/openldap/sbin/slapd -u slapd -h ldap://:389/ ldapi:/
>     0 root     ps -eo uid,user,args
> ```
> 
> and from outside the container, form the host, I could search by using:
> 
> ```
> $ ldapsearch -x -b "dc=example,dc=org" -H ldap://localhost:389 'dn'
> # extended LDIF
> #
> # LDAPv3
> # base <dc=example,dc=org> with scope subtree
> # filter: (objectclass=*)
> # requesting: dn 
> #
> 
> # example.org
> dn: dc=example,dc=org
> 
> # users, example.org
> dn: ou=users,dc=example,dc=org
> 
> # user01, users, example.org
> dn: cn=user01,ou=users,dc=example,dc=org
> 
> # user02, users, example.org
> dn: cn=user02,ou=users,dc=example,dc=org
> 
> # readers, users, example.org
> dn: cn=readers,ou=users,dc=example,dc=org
> 
> # search result
> search: 2
> result: 0 Success
> 
> # numResponses: 6
> # numEntries: 5
> ```

@rafariossaa What you wrote last is not a solution. I see 0 reasons why this container could not be used for official openldap ports + replication without rebuilding it.
1. Privileged ports - note that when running a container it is possible to issue a flag and allow container to use privileged ports.
2. Replication - from what I remember, it seems that you cannot have port 1636 inside a container and map it to a port 636 outside of container. It all results in errors. Inside and outside ports need to be the same for replication to work. So if replication uri is server:636, then openldap needs to listen to 636 and needs to be mapped to 636 port. If there is a difference, it just fails to work. Try to use existing container with oficial openldap ports and enable replication - you will see then.

**Comment by rafariossaa** [comment]
Hi,
  We have made a new release allowing the usage of privileged ports. 
  Could you give it a try ?

**Comment by helvetia007** [comment]
@rafariossaa  thanks
1. Which tags have this fix?
2. So now with --sysctl net.ipv4.ip_unprivileged_port_start=0 and -e LDAP_LDAPS_PORT_NUMBER=636 it will just work?
