### ISSUE TITLE
Add "io-threads" and "io-threads-do-reads" to redis-env.sh for 6 and 7

### ISSUE THREAD

**Issue by saytesnake** [bitnami/containers#997]
### Name and Version

bitnami/redis:6.2

### What is the problem this feature will solve?

Redis 6 or higher version arrives with multithreading for faster I/O. It's beneficial in many production environments. Of course I know that custom my own redis.conf can be do it well, but maybe put it in env just easy for it.

### What is the feature you are proposing to solve the problem?

Add "io-threads" and "io-threads-do-reads" environment variables to redis-env.sh.

Something like `docker run -it -e IO_THREADS=4 -e IO_THREADS_DO_READS=yes xxx`

**Comment by aoterolorenzo** [comment]
Hi @saytesnake,

This is now implemented and released through [[bitnami/redis] Release 6.2.7-debian-11-r17](https://github.com/bitnami/containers/pull/275#top) and [[bitnami/redis] Release 7.0.4-debian-11-r3](https://github.com/bitnami/containers/pull/273#top)
